CREATE TABLE IF NOT EXISTS users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(), email VARCHAR(255) UNIQUE NOT NULL, password_hash VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL, role VARCHAR(50) NOT NULL DEFAULT 'STANDARD_USER', is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS devices (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(), device_id VARCHAR(100) UNIQUE NOT NULL, name VARCHAR(255) NOT NULL,
    type VARCHAR(50) NOT NULL, status VARCHAR(50) NOT NULL DEFAULT 'ONLINE', battery_level INT NOT NULL DEFAULT 100,
    latitude DOUBLE PRECISION NOT NULL, longitude DOUBLE PRECISION NOT NULL, speed_kph DOUBLE PRECISION DEFAULT 0.0,
    geom GEOMETRY(Point, 4326), last_seen_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS device_locations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(), device_id VARCHAR(100) NOT NULL,
    latitude DOUBLE PRECISION NOT NULL, longitude DOUBLE PRECISION NOT NULL, speed_kph DOUBLE PRECISION DEFAULT 0.0,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS network_nodes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(), name VARCHAR(255) NOT NULL, ip_address VARCHAR(100) NOT NULL,
    type VARCHAR(50) NOT NULL, status VARCHAR(50) NOT NULL DEFAULT 'ONLINE', latency_ms DOUBLE PRECISION DEFAULT 10.0,
    packet_loss_percent DOUBLE PRECISION DEFAULT 0.0, uptime_percent DOUBLE PRECISION DEFAULT 99.9
);
CREATE TABLE IF NOT EXISTS network_links (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(), source_node_id UUID NOT NULL, target_node_id UUID NOT NULL,
    latency_ms DOUBLE PRECISION DEFAULT 5.0, status VARCHAR(50) DEFAULT 'OPTIMAL'
);
CREATE TABLE IF NOT EXISTS alerts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(), rule_name VARCHAR(255) NOT NULL, target_name VARCHAR(255) NOT NULL,
    severity VARCHAR(50) NOT NULL, status VARCHAR(50) NOT NULL DEFAULT 'OPEN', message TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
