import { UserRole, Permission } from '@geonet/types';
export const SYSTEM_CONSTANTS = {
  APP_NAME: 'GeoNet Sentinel', APP_VERSION: '1.0.0', DEFAULT_API_PORT: 4000, DEFAULT_WEB_PORT: 5173,
  JWT_DEFAULT_EXPIRATION: '3600s', JWT_REFRESH_EXPIRATION: '7d', PASSWORD_LOCKOUT_ATTEMPTS: 5,
  MAX_GPS_SPEED_KPH: 300, GPS_JITTER_METERS: 15, PROBER_DEFAULT_TIMEOUT_MS: 5000, PROBER_DEFAULT_INTERVAL_SECONDS: 30
};
export const DEFAULT_ALERT_THRESHOLDS = {
  LATENCY_WARNING_MS: 100, LATENCY_CRITICAL_MS: 250, PACKET_LOSS_WARNING_PERCENT: 5.0, PACKET_LOSS_CRITICAL_PERCENT: 15.0,
  CPU_WARNING_PERCENT: 75.0, CPU_CRITICAL_PERCENT: 90.0, BATTERY_WARNING_PERCENT: 20.0, BATTERY_CRITICAL_PERCENT: 10.0
};
