/**
 * Enterprise Telecommunications Protocol Specification: ADS-B Mode-S Transponder Aviation Spatial Telemetry Spec
 * Module: @geonet/types/telecom/adsb_flight_telemetry
 * Standard Compliance: 3GPP TS 38.401, IETF RFC Standards, ITU-T G.8032
 */

export interface ADSBModeSTransponderAviationSpatialTelemetrySpecConfig {
  samplingIntervalMs: number;
  collectionEnabled: boolean;
  highWatermarkThreshold: number;
  lowWatermarkThreshold: number;
  retryAttempts: number;
  timeoutMs: number;
}

export interface AdsbFlightTelemetryRecordV1 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  modes_squawk_primaryMetric: number;
  modes_squawk_secondaryMetric: number;
  modes_squawk_baselineAverage: number;
  modes_squawk_peakObserved: number;
  modes_squawk_standardDeviation: number;
  modes_squawk_rawHexSample: string;
  modes_squawk_metadataTag: Record<string, string>;
  callsign_primaryMetric: number;
  callsign_secondaryMetric: number;
  callsign_baselineAverage: number;
  callsign_peakObserved: number;
  callsign_standardDeviation: number;
  callsign_rawHexSample: string;
  callsign_metadataTag: Record<string, string>;
  pressurealtitude_primaryMetric: number;
  pressurealtitude_secondaryMetric: number;
  pressurealtitude_baselineAverage: number;
  pressurealtitude_peakObserved: number;
  pressurealtitude_standardDeviation: number;
  pressurealtitude_rawHexSample: string;
  pressurealtitude_metadataTag: Record<string, string>;
  geometricaltitude_primaryMetric: number;
  geometricaltitude_secondaryMetric: number;
  geometricaltitude_baselineAverage: number;
  geometricaltitude_peakObserved: number;
  geometricaltitude_standardDeviation: number;
  geometricaltitude_rawHexSample: string;
  geometricaltitude_metadataTag: Record<string, string>;
  verticalrate_primaryMetric: number;
  verticalrate_secondaryMetric: number;
  verticalrate_baselineAverage: number;
  verticalrate_peakObserved: number;
  verticalrate_standardDeviation: number;
  verticalrate_rawHexSample: string;
  verticalrate_metadataTag: Record<string, string>;
  airspeedkts_primaryMetric: number;
  airspeedkts_secondaryMetric: number;
  airspeedkts_baselineAverage: number;
  airspeedkts_peakObserved: number;
  airspeedkts_standardDeviation: number;
  airspeedkts_rawHexSample: string;
  airspeedkts_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type AdsbFlightTelemetryFilterV1 = Partial<AdsbFlightTelemetryRecordV1> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface AdsbFlightTelemetryRecordV2 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  modes_squawk_primaryMetric: number;
  modes_squawk_secondaryMetric: number;
  modes_squawk_baselineAverage: number;
  modes_squawk_peakObserved: number;
  modes_squawk_standardDeviation: number;
  modes_squawk_rawHexSample: string;
  modes_squawk_metadataTag: Record<string, string>;
  callsign_primaryMetric: number;
  callsign_secondaryMetric: number;
  callsign_baselineAverage: number;
  callsign_peakObserved: number;
  callsign_standardDeviation: number;
  callsign_rawHexSample: string;
  callsign_metadataTag: Record<string, string>;
  pressurealtitude_primaryMetric: number;
  pressurealtitude_secondaryMetric: number;
  pressurealtitude_baselineAverage: number;
  pressurealtitude_peakObserved: number;
  pressurealtitude_standardDeviation: number;
  pressurealtitude_rawHexSample: string;
  pressurealtitude_metadataTag: Record<string, string>;
  geometricaltitude_primaryMetric: number;
  geometricaltitude_secondaryMetric: number;
  geometricaltitude_baselineAverage: number;
  geometricaltitude_peakObserved: number;
  geometricaltitude_standardDeviation: number;
  geometricaltitude_rawHexSample: string;
  geometricaltitude_metadataTag: Record<string, string>;
  verticalrate_primaryMetric: number;
  verticalrate_secondaryMetric: number;
  verticalrate_baselineAverage: number;
  verticalrate_peakObserved: number;
  verticalrate_standardDeviation: number;
  verticalrate_rawHexSample: string;
  verticalrate_metadataTag: Record<string, string>;
  airspeedkts_primaryMetric: number;
  airspeedkts_secondaryMetric: number;
  airspeedkts_baselineAverage: number;
  airspeedkts_peakObserved: number;
  airspeedkts_standardDeviation: number;
  airspeedkts_rawHexSample: string;
  airspeedkts_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type AdsbFlightTelemetryFilterV2 = Partial<AdsbFlightTelemetryRecordV2> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface AdsbFlightTelemetryRecordV3 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  modes_squawk_primaryMetric: number;
  modes_squawk_secondaryMetric: number;
  modes_squawk_baselineAverage: number;
  modes_squawk_peakObserved: number;
  modes_squawk_standardDeviation: number;
  modes_squawk_rawHexSample: string;
  modes_squawk_metadataTag: Record<string, string>;
  callsign_primaryMetric: number;
  callsign_secondaryMetric: number;
  callsign_baselineAverage: number;
  callsign_peakObserved: number;
  callsign_standardDeviation: number;
  callsign_rawHexSample: string;
  callsign_metadataTag: Record<string, string>;
  pressurealtitude_primaryMetric: number;
  pressurealtitude_secondaryMetric: number;
  pressurealtitude_baselineAverage: number;
  pressurealtitude_peakObserved: number;
  pressurealtitude_standardDeviation: number;
  pressurealtitude_rawHexSample: string;
  pressurealtitude_metadataTag: Record<string, string>;
  geometricaltitude_primaryMetric: number;
  geometricaltitude_secondaryMetric: number;
  geometricaltitude_baselineAverage: number;
  geometricaltitude_peakObserved: number;
  geometricaltitude_standardDeviation: number;
  geometricaltitude_rawHexSample: string;
  geometricaltitude_metadataTag: Record<string, string>;
  verticalrate_primaryMetric: number;
  verticalrate_secondaryMetric: number;
  verticalrate_baselineAverage: number;
  verticalrate_peakObserved: number;
  verticalrate_standardDeviation: number;
  verticalrate_rawHexSample: string;
  verticalrate_metadataTag: Record<string, string>;
  airspeedkts_primaryMetric: number;
  airspeedkts_secondaryMetric: number;
  airspeedkts_baselineAverage: number;
  airspeedkts_peakObserved: number;
  airspeedkts_standardDeviation: number;
  airspeedkts_rawHexSample: string;
  airspeedkts_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type AdsbFlightTelemetryFilterV3 = Partial<AdsbFlightTelemetryRecordV3> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface AdsbFlightTelemetryRecordV4 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  modes_squawk_primaryMetric: number;
  modes_squawk_secondaryMetric: number;
  modes_squawk_baselineAverage: number;
  modes_squawk_peakObserved: number;
  modes_squawk_standardDeviation: number;
  modes_squawk_rawHexSample: string;
  modes_squawk_metadataTag: Record<string, string>;
  callsign_primaryMetric: number;
  callsign_secondaryMetric: number;
  callsign_baselineAverage: number;
  callsign_peakObserved: number;
  callsign_standardDeviation: number;
  callsign_rawHexSample: string;
  callsign_metadataTag: Record<string, string>;
  pressurealtitude_primaryMetric: number;
  pressurealtitude_secondaryMetric: number;
  pressurealtitude_baselineAverage: number;
  pressurealtitude_peakObserved: number;
  pressurealtitude_standardDeviation: number;
  pressurealtitude_rawHexSample: string;
  pressurealtitude_metadataTag: Record<string, string>;
  geometricaltitude_primaryMetric: number;
  geometricaltitude_secondaryMetric: number;
  geometricaltitude_baselineAverage: number;
  geometricaltitude_peakObserved: number;
  geometricaltitude_standardDeviation: number;
  geometricaltitude_rawHexSample: string;
  geometricaltitude_metadataTag: Record<string, string>;
  verticalrate_primaryMetric: number;
  verticalrate_secondaryMetric: number;
  verticalrate_baselineAverage: number;
  verticalrate_peakObserved: number;
  verticalrate_standardDeviation: number;
  verticalrate_rawHexSample: string;
  verticalrate_metadataTag: Record<string, string>;
  airspeedkts_primaryMetric: number;
  airspeedkts_secondaryMetric: number;
  airspeedkts_baselineAverage: number;
  airspeedkts_peakObserved: number;
  airspeedkts_standardDeviation: number;
  airspeedkts_rawHexSample: string;
  airspeedkts_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type AdsbFlightTelemetryFilterV4 = Partial<AdsbFlightTelemetryRecordV4> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface AdsbFlightTelemetryRecordV5 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  modes_squawk_primaryMetric: number;
  modes_squawk_secondaryMetric: number;
  modes_squawk_baselineAverage: number;
  modes_squawk_peakObserved: number;
  modes_squawk_standardDeviation: number;
  modes_squawk_rawHexSample: string;
  modes_squawk_metadataTag: Record<string, string>;
  callsign_primaryMetric: number;
  callsign_secondaryMetric: number;
  callsign_baselineAverage: number;
  callsign_peakObserved: number;
  callsign_standardDeviation: number;
  callsign_rawHexSample: string;
  callsign_metadataTag: Record<string, string>;
  pressurealtitude_primaryMetric: number;
  pressurealtitude_secondaryMetric: number;
  pressurealtitude_baselineAverage: number;
  pressurealtitude_peakObserved: number;
  pressurealtitude_standardDeviation: number;
  pressurealtitude_rawHexSample: string;
  pressurealtitude_metadataTag: Record<string, string>;
  geometricaltitude_primaryMetric: number;
  geometricaltitude_secondaryMetric: number;
  geometricaltitude_baselineAverage: number;
  geometricaltitude_peakObserved: number;
  geometricaltitude_standardDeviation: number;
  geometricaltitude_rawHexSample: string;
  geometricaltitude_metadataTag: Record<string, string>;
  verticalrate_primaryMetric: number;
  verticalrate_secondaryMetric: number;
  verticalrate_baselineAverage: number;
  verticalrate_peakObserved: number;
  verticalrate_standardDeviation: number;
  verticalrate_rawHexSample: string;
  verticalrate_metadataTag: Record<string, string>;
  airspeedkts_primaryMetric: number;
  airspeedkts_secondaryMetric: number;
  airspeedkts_baselineAverage: number;
  airspeedkts_peakObserved: number;
  airspeedkts_standardDeviation: number;
  airspeedkts_rawHexSample: string;
  airspeedkts_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type AdsbFlightTelemetryFilterV5 = Partial<AdsbFlightTelemetryRecordV5> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface AdsbFlightTelemetryRecordV6 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  modes_squawk_primaryMetric: number;
  modes_squawk_secondaryMetric: number;
  modes_squawk_baselineAverage: number;
  modes_squawk_peakObserved: number;
  modes_squawk_standardDeviation: number;
  modes_squawk_rawHexSample: string;
  modes_squawk_metadataTag: Record<string, string>;
  callsign_primaryMetric: number;
  callsign_secondaryMetric: number;
  callsign_baselineAverage: number;
  callsign_peakObserved: number;
  callsign_standardDeviation: number;
  callsign_rawHexSample: string;
  callsign_metadataTag: Record<string, string>;
  pressurealtitude_primaryMetric: number;
  pressurealtitude_secondaryMetric: number;
  pressurealtitude_baselineAverage: number;
  pressurealtitude_peakObserved: number;
  pressurealtitude_standardDeviation: number;
  pressurealtitude_rawHexSample: string;
  pressurealtitude_metadataTag: Record<string, string>;
  geometricaltitude_primaryMetric: number;
  geometricaltitude_secondaryMetric: number;
  geometricaltitude_baselineAverage: number;
  geometricaltitude_peakObserved: number;
  geometricaltitude_standardDeviation: number;
  geometricaltitude_rawHexSample: string;
  geometricaltitude_metadataTag: Record<string, string>;
  verticalrate_primaryMetric: number;
  verticalrate_secondaryMetric: number;
  verticalrate_baselineAverage: number;
  verticalrate_peakObserved: number;
  verticalrate_standardDeviation: number;
  verticalrate_rawHexSample: string;
  verticalrate_metadataTag: Record<string, string>;
  airspeedkts_primaryMetric: number;
  airspeedkts_secondaryMetric: number;
  airspeedkts_baselineAverage: number;
  airspeedkts_peakObserved: number;
  airspeedkts_standardDeviation: number;
  airspeedkts_rawHexSample: string;
  airspeedkts_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type AdsbFlightTelemetryFilterV6 = Partial<AdsbFlightTelemetryRecordV6> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface AdsbFlightTelemetryRecordV7 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  modes_squawk_primaryMetric: number;
  modes_squawk_secondaryMetric: number;
  modes_squawk_baselineAverage: number;
  modes_squawk_peakObserved: number;
  modes_squawk_standardDeviation: number;
  modes_squawk_rawHexSample: string;
  modes_squawk_metadataTag: Record<string, string>;
  callsign_primaryMetric: number;
  callsign_secondaryMetric: number;
  callsign_baselineAverage: number;
  callsign_peakObserved: number;
  callsign_standardDeviation: number;
  callsign_rawHexSample: string;
  callsign_metadataTag: Record<string, string>;
  pressurealtitude_primaryMetric: number;
  pressurealtitude_secondaryMetric: number;
  pressurealtitude_baselineAverage: number;
  pressurealtitude_peakObserved: number;
  pressurealtitude_standardDeviation: number;
  pressurealtitude_rawHexSample: string;
  pressurealtitude_metadataTag: Record<string, string>;
  geometricaltitude_primaryMetric: number;
  geometricaltitude_secondaryMetric: number;
  geometricaltitude_baselineAverage: number;
  geometricaltitude_peakObserved: number;
  geometricaltitude_standardDeviation: number;
  geometricaltitude_rawHexSample: string;
  geometricaltitude_metadataTag: Record<string, string>;
  verticalrate_primaryMetric: number;
  verticalrate_secondaryMetric: number;
  verticalrate_baselineAverage: number;
  verticalrate_peakObserved: number;
  verticalrate_standardDeviation: number;
  verticalrate_rawHexSample: string;
  verticalrate_metadataTag: Record<string, string>;
  airspeedkts_primaryMetric: number;
  airspeedkts_secondaryMetric: number;
  airspeedkts_baselineAverage: number;
  airspeedkts_peakObserved: number;
  airspeedkts_standardDeviation: number;
  airspeedkts_rawHexSample: string;
  airspeedkts_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type AdsbFlightTelemetryFilterV7 = Partial<AdsbFlightTelemetryRecordV7> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface AdsbFlightTelemetryRecordV8 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  modes_squawk_primaryMetric: number;
  modes_squawk_secondaryMetric: number;
  modes_squawk_baselineAverage: number;
  modes_squawk_peakObserved: number;
  modes_squawk_standardDeviation: number;
  modes_squawk_rawHexSample: string;
  modes_squawk_metadataTag: Record<string, string>;
  callsign_primaryMetric: number;
  callsign_secondaryMetric: number;
  callsign_baselineAverage: number;
  callsign_peakObserved: number;
  callsign_standardDeviation: number;
  callsign_rawHexSample: string;
  callsign_metadataTag: Record<string, string>;
  pressurealtitude_primaryMetric: number;
  pressurealtitude_secondaryMetric: number;
  pressurealtitude_baselineAverage: number;
  pressurealtitude_peakObserved: number;
  pressurealtitude_standardDeviation: number;
  pressurealtitude_rawHexSample: string;
  pressurealtitude_metadataTag: Record<string, string>;
  geometricaltitude_primaryMetric: number;
  geometricaltitude_secondaryMetric: number;
  geometricaltitude_baselineAverage: number;
  geometricaltitude_peakObserved: number;
  geometricaltitude_standardDeviation: number;
  geometricaltitude_rawHexSample: string;
  geometricaltitude_metadataTag: Record<string, string>;
  verticalrate_primaryMetric: number;
  verticalrate_secondaryMetric: number;
  verticalrate_baselineAverage: number;
  verticalrate_peakObserved: number;
  verticalrate_standardDeviation: number;
  verticalrate_rawHexSample: string;
  verticalrate_metadataTag: Record<string, string>;
  airspeedkts_primaryMetric: number;
  airspeedkts_secondaryMetric: number;
  airspeedkts_baselineAverage: number;
  airspeedkts_peakObserved: number;
  airspeedkts_standardDeviation: number;
  airspeedkts_rawHexSample: string;
  airspeedkts_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type AdsbFlightTelemetryFilterV8 = Partial<AdsbFlightTelemetryRecordV8> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface AdsbFlightTelemetryRecordV9 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  modes_squawk_primaryMetric: number;
  modes_squawk_secondaryMetric: number;
  modes_squawk_baselineAverage: number;
  modes_squawk_peakObserved: number;
  modes_squawk_standardDeviation: number;
  modes_squawk_rawHexSample: string;
  modes_squawk_metadataTag: Record<string, string>;
  callsign_primaryMetric: number;
  callsign_secondaryMetric: number;
  callsign_baselineAverage: number;
  callsign_peakObserved: number;
  callsign_standardDeviation: number;
  callsign_rawHexSample: string;
  callsign_metadataTag: Record<string, string>;
  pressurealtitude_primaryMetric: number;
  pressurealtitude_secondaryMetric: number;
  pressurealtitude_baselineAverage: number;
  pressurealtitude_peakObserved: number;
  pressurealtitude_standardDeviation: number;
  pressurealtitude_rawHexSample: string;
  pressurealtitude_metadataTag: Record<string, string>;
  geometricaltitude_primaryMetric: number;
  geometricaltitude_secondaryMetric: number;
  geometricaltitude_baselineAverage: number;
  geometricaltitude_peakObserved: number;
  geometricaltitude_standardDeviation: number;
  geometricaltitude_rawHexSample: string;
  geometricaltitude_metadataTag: Record<string, string>;
  verticalrate_primaryMetric: number;
  verticalrate_secondaryMetric: number;
  verticalrate_baselineAverage: number;
  verticalrate_peakObserved: number;
  verticalrate_standardDeviation: number;
  verticalrate_rawHexSample: string;
  verticalrate_metadataTag: Record<string, string>;
  airspeedkts_primaryMetric: number;
  airspeedkts_secondaryMetric: number;
  airspeedkts_baselineAverage: number;
  airspeedkts_peakObserved: number;
  airspeedkts_standardDeviation: number;
  airspeedkts_rawHexSample: string;
  airspeedkts_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type AdsbFlightTelemetryFilterV9 = Partial<AdsbFlightTelemetryRecordV9> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface AdsbFlightTelemetryRecordV10 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  modes_squawk_primaryMetric: number;
  modes_squawk_secondaryMetric: number;
  modes_squawk_baselineAverage: number;
  modes_squawk_peakObserved: number;
  modes_squawk_standardDeviation: number;
  modes_squawk_rawHexSample: string;
  modes_squawk_metadataTag: Record<string, string>;
  callsign_primaryMetric: number;
  callsign_secondaryMetric: number;
  callsign_baselineAverage: number;
  callsign_peakObserved: number;
  callsign_standardDeviation: number;
  callsign_rawHexSample: string;
  callsign_metadataTag: Record<string, string>;
  pressurealtitude_primaryMetric: number;
  pressurealtitude_secondaryMetric: number;
  pressurealtitude_baselineAverage: number;
  pressurealtitude_peakObserved: number;
  pressurealtitude_standardDeviation: number;
  pressurealtitude_rawHexSample: string;
  pressurealtitude_metadataTag: Record<string, string>;
  geometricaltitude_primaryMetric: number;
  geometricaltitude_secondaryMetric: number;
  geometricaltitude_baselineAverage: number;
  geometricaltitude_peakObserved: number;
  geometricaltitude_standardDeviation: number;
  geometricaltitude_rawHexSample: string;
  geometricaltitude_metadataTag: Record<string, string>;
  verticalrate_primaryMetric: number;
  verticalrate_secondaryMetric: number;
  verticalrate_baselineAverage: number;
  verticalrate_peakObserved: number;
  verticalrate_standardDeviation: number;
  verticalrate_rawHexSample: string;
  verticalrate_metadataTag: Record<string, string>;
  airspeedkts_primaryMetric: number;
  airspeedkts_secondaryMetric: number;
  airspeedkts_baselineAverage: number;
  airspeedkts_peakObserved: number;
  airspeedkts_standardDeviation: number;
  airspeedkts_rawHexSample: string;
  airspeedkts_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type AdsbFlightTelemetryFilterV10 = Partial<AdsbFlightTelemetryRecordV10> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface AdsbFlightTelemetryRecordV11 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  modes_squawk_primaryMetric: number;
  modes_squawk_secondaryMetric: number;
  modes_squawk_baselineAverage: number;
  modes_squawk_peakObserved: number;
  modes_squawk_standardDeviation: number;
  modes_squawk_rawHexSample: string;
  modes_squawk_metadataTag: Record<string, string>;
  callsign_primaryMetric: number;
  callsign_secondaryMetric: number;
  callsign_baselineAverage: number;
  callsign_peakObserved: number;
  callsign_standardDeviation: number;
  callsign_rawHexSample: string;
  callsign_metadataTag: Record<string, string>;
  pressurealtitude_primaryMetric: number;
  pressurealtitude_secondaryMetric: number;
  pressurealtitude_baselineAverage: number;
  pressurealtitude_peakObserved: number;
  pressurealtitude_standardDeviation: number;
  pressurealtitude_rawHexSample: string;
  pressurealtitude_metadataTag: Record<string, string>;
  geometricaltitude_primaryMetric: number;
  geometricaltitude_secondaryMetric: number;
  geometricaltitude_baselineAverage: number;
  geometricaltitude_peakObserved: number;
  geometricaltitude_standardDeviation: number;
  geometricaltitude_rawHexSample: string;
  geometricaltitude_metadataTag: Record<string, string>;
  verticalrate_primaryMetric: number;
  verticalrate_secondaryMetric: number;
  verticalrate_baselineAverage: number;
  verticalrate_peakObserved: number;
  verticalrate_standardDeviation: number;
  verticalrate_rawHexSample: string;
  verticalrate_metadataTag: Record<string, string>;
  airspeedkts_primaryMetric: number;
  airspeedkts_secondaryMetric: number;
  airspeedkts_baselineAverage: number;
  airspeedkts_peakObserved: number;
  airspeedkts_standardDeviation: number;
  airspeedkts_rawHexSample: string;
  airspeedkts_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type AdsbFlightTelemetryFilterV11 = Partial<AdsbFlightTelemetryRecordV11> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface AdsbFlightTelemetryRecordV12 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  modes_squawk_primaryMetric: number;
  modes_squawk_secondaryMetric: number;
  modes_squawk_baselineAverage: number;
  modes_squawk_peakObserved: number;
  modes_squawk_standardDeviation: number;
  modes_squawk_rawHexSample: string;
  modes_squawk_metadataTag: Record<string, string>;
  callsign_primaryMetric: number;
  callsign_secondaryMetric: number;
  callsign_baselineAverage: number;
  callsign_peakObserved: number;
  callsign_standardDeviation: number;
  callsign_rawHexSample: string;
  callsign_metadataTag: Record<string, string>;
  pressurealtitude_primaryMetric: number;
  pressurealtitude_secondaryMetric: number;
  pressurealtitude_baselineAverage: number;
  pressurealtitude_peakObserved: number;
  pressurealtitude_standardDeviation: number;
  pressurealtitude_rawHexSample: string;
  pressurealtitude_metadataTag: Record<string, string>;
  geometricaltitude_primaryMetric: number;
  geometricaltitude_secondaryMetric: number;
  geometricaltitude_baselineAverage: number;
  geometricaltitude_peakObserved: number;
  geometricaltitude_standardDeviation: number;
  geometricaltitude_rawHexSample: string;
  geometricaltitude_metadataTag: Record<string, string>;
  verticalrate_primaryMetric: number;
  verticalrate_secondaryMetric: number;
  verticalrate_baselineAverage: number;
  verticalrate_peakObserved: number;
  verticalrate_standardDeviation: number;
  verticalrate_rawHexSample: string;
  verticalrate_metadataTag: Record<string, string>;
  airspeedkts_primaryMetric: number;
  airspeedkts_secondaryMetric: number;
  airspeedkts_baselineAverage: number;
  airspeedkts_peakObserved: number;
  airspeedkts_standardDeviation: number;
  airspeedkts_rawHexSample: string;
  airspeedkts_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type AdsbFlightTelemetryFilterV12 = Partial<AdsbFlightTelemetryRecordV12> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface AdsbFlightTelemetryRecordV13 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  modes_squawk_primaryMetric: number;
  modes_squawk_secondaryMetric: number;
  modes_squawk_baselineAverage: number;
  modes_squawk_peakObserved: number;
  modes_squawk_standardDeviation: number;
  modes_squawk_rawHexSample: string;
  modes_squawk_metadataTag: Record<string, string>;
  callsign_primaryMetric: number;
  callsign_secondaryMetric: number;
  callsign_baselineAverage: number;
  callsign_peakObserved: number;
  callsign_standardDeviation: number;
  callsign_rawHexSample: string;
  callsign_metadataTag: Record<string, string>;
  pressurealtitude_primaryMetric: number;
  pressurealtitude_secondaryMetric: number;
  pressurealtitude_baselineAverage: number;
  pressurealtitude_peakObserved: number;
  pressurealtitude_standardDeviation: number;
  pressurealtitude_rawHexSample: string;
  pressurealtitude_metadataTag: Record<string, string>;
  geometricaltitude_primaryMetric: number;
  geometricaltitude_secondaryMetric: number;
  geometricaltitude_baselineAverage: number;
  geometricaltitude_peakObserved: number;
  geometricaltitude_standardDeviation: number;
  geometricaltitude_rawHexSample: string;
  geometricaltitude_metadataTag: Record<string, string>;
  verticalrate_primaryMetric: number;
  verticalrate_secondaryMetric: number;
  verticalrate_baselineAverage: number;
  verticalrate_peakObserved: number;
  verticalrate_standardDeviation: number;
  verticalrate_rawHexSample: string;
  verticalrate_metadataTag: Record<string, string>;
  airspeedkts_primaryMetric: number;
  airspeedkts_secondaryMetric: number;
  airspeedkts_baselineAverage: number;
  airspeedkts_peakObserved: number;
  airspeedkts_standardDeviation: number;
  airspeedkts_rawHexSample: string;
  airspeedkts_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type AdsbFlightTelemetryFilterV13 = Partial<AdsbFlightTelemetryRecordV13> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface AdsbFlightTelemetryRecordV14 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  modes_squawk_primaryMetric: number;
  modes_squawk_secondaryMetric: number;
  modes_squawk_baselineAverage: number;
  modes_squawk_peakObserved: number;
  modes_squawk_standardDeviation: number;
  modes_squawk_rawHexSample: string;
  modes_squawk_metadataTag: Record<string, string>;
  callsign_primaryMetric: number;
  callsign_secondaryMetric: number;
  callsign_baselineAverage: number;
  callsign_peakObserved: number;
  callsign_standardDeviation: number;
  callsign_rawHexSample: string;
  callsign_metadataTag: Record<string, string>;
  pressurealtitude_primaryMetric: number;
  pressurealtitude_secondaryMetric: number;
  pressurealtitude_baselineAverage: number;
  pressurealtitude_peakObserved: number;
  pressurealtitude_standardDeviation: number;
  pressurealtitude_rawHexSample: string;
  pressurealtitude_metadataTag: Record<string, string>;
  geometricaltitude_primaryMetric: number;
  geometricaltitude_secondaryMetric: number;
  geometricaltitude_baselineAverage: number;
  geometricaltitude_peakObserved: number;
  geometricaltitude_standardDeviation: number;
  geometricaltitude_rawHexSample: string;
  geometricaltitude_metadataTag: Record<string, string>;
  verticalrate_primaryMetric: number;
  verticalrate_secondaryMetric: number;
  verticalrate_baselineAverage: number;
  verticalrate_peakObserved: number;
  verticalrate_standardDeviation: number;
  verticalrate_rawHexSample: string;
  verticalrate_metadataTag: Record<string, string>;
  airspeedkts_primaryMetric: number;
  airspeedkts_secondaryMetric: number;
  airspeedkts_baselineAverage: number;
  airspeedkts_peakObserved: number;
  airspeedkts_standardDeviation: number;
  airspeedkts_rawHexSample: string;
  airspeedkts_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type AdsbFlightTelemetryFilterV14 = Partial<AdsbFlightTelemetryRecordV14> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface AdsbFlightTelemetryRecordV15 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  modes_squawk_primaryMetric: number;
  modes_squawk_secondaryMetric: number;
  modes_squawk_baselineAverage: number;
  modes_squawk_peakObserved: number;
  modes_squawk_standardDeviation: number;
  modes_squawk_rawHexSample: string;
  modes_squawk_metadataTag: Record<string, string>;
  callsign_primaryMetric: number;
  callsign_secondaryMetric: number;
  callsign_baselineAverage: number;
  callsign_peakObserved: number;
  callsign_standardDeviation: number;
  callsign_rawHexSample: string;
  callsign_metadataTag: Record<string, string>;
  pressurealtitude_primaryMetric: number;
  pressurealtitude_secondaryMetric: number;
  pressurealtitude_baselineAverage: number;
  pressurealtitude_peakObserved: number;
  pressurealtitude_standardDeviation: number;
  pressurealtitude_rawHexSample: string;
  pressurealtitude_metadataTag: Record<string, string>;
  geometricaltitude_primaryMetric: number;
  geometricaltitude_secondaryMetric: number;
  geometricaltitude_baselineAverage: number;
  geometricaltitude_peakObserved: number;
  geometricaltitude_standardDeviation: number;
  geometricaltitude_rawHexSample: string;
  geometricaltitude_metadataTag: Record<string, string>;
  verticalrate_primaryMetric: number;
  verticalrate_secondaryMetric: number;
  verticalrate_baselineAverage: number;
  verticalrate_peakObserved: number;
  verticalrate_standardDeviation: number;
  verticalrate_rawHexSample: string;
  verticalrate_metadataTag: Record<string, string>;
  airspeedkts_primaryMetric: number;
  airspeedkts_secondaryMetric: number;
  airspeedkts_baselineAverage: number;
  airspeedkts_peakObserved: number;
  airspeedkts_standardDeviation: number;
  airspeedkts_rawHexSample: string;
  airspeedkts_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type AdsbFlightTelemetryFilterV15 = Partial<AdsbFlightTelemetryRecordV15> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface AdsbFlightTelemetryRecordV16 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  modes_squawk_primaryMetric: number;
  modes_squawk_secondaryMetric: number;
  modes_squawk_baselineAverage: number;
  modes_squawk_peakObserved: number;
  modes_squawk_standardDeviation: number;
  modes_squawk_rawHexSample: string;
  modes_squawk_metadataTag: Record<string, string>;
  callsign_primaryMetric: number;
  callsign_secondaryMetric: number;
  callsign_baselineAverage: number;
  callsign_peakObserved: number;
  callsign_standardDeviation: number;
  callsign_rawHexSample: string;
  callsign_metadataTag: Record<string, string>;
  pressurealtitude_primaryMetric: number;
  pressurealtitude_secondaryMetric: number;
  pressurealtitude_baselineAverage: number;
  pressurealtitude_peakObserved: number;
  pressurealtitude_standardDeviation: number;
  pressurealtitude_rawHexSample: string;
  pressurealtitude_metadataTag: Record<string, string>;
  geometricaltitude_primaryMetric: number;
  geometricaltitude_secondaryMetric: number;
  geometricaltitude_baselineAverage: number;
  geometricaltitude_peakObserved: number;
  geometricaltitude_standardDeviation: number;
  geometricaltitude_rawHexSample: string;
  geometricaltitude_metadataTag: Record<string, string>;
  verticalrate_primaryMetric: number;
  verticalrate_secondaryMetric: number;
  verticalrate_baselineAverage: number;
  verticalrate_peakObserved: number;
  verticalrate_standardDeviation: number;
  verticalrate_rawHexSample: string;
  verticalrate_metadataTag: Record<string, string>;
  airspeedkts_primaryMetric: number;
  airspeedkts_secondaryMetric: number;
  airspeedkts_baselineAverage: number;
  airspeedkts_peakObserved: number;
  airspeedkts_standardDeviation: number;
  airspeedkts_rawHexSample: string;
  airspeedkts_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type AdsbFlightTelemetryFilterV16 = Partial<AdsbFlightTelemetryRecordV16> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface AdsbFlightTelemetryRecordV17 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  modes_squawk_primaryMetric: number;
  modes_squawk_secondaryMetric: number;
  modes_squawk_baselineAverage: number;
  modes_squawk_peakObserved: number;
  modes_squawk_standardDeviation: number;
  modes_squawk_rawHexSample: string;
  modes_squawk_metadataTag: Record<string, string>;
  callsign_primaryMetric: number;
  callsign_secondaryMetric: number;
  callsign_baselineAverage: number;
  callsign_peakObserved: number;
  callsign_standardDeviation: number;
  callsign_rawHexSample: string;
  callsign_metadataTag: Record<string, string>;
  pressurealtitude_primaryMetric: number;
  pressurealtitude_secondaryMetric: number;
  pressurealtitude_baselineAverage: number;
  pressurealtitude_peakObserved: number;
  pressurealtitude_standardDeviation: number;
  pressurealtitude_rawHexSample: string;
  pressurealtitude_metadataTag: Record<string, string>;
  geometricaltitude_primaryMetric: number;
  geometricaltitude_secondaryMetric: number;
  geometricaltitude_baselineAverage: number;
  geometricaltitude_peakObserved: number;
  geometricaltitude_standardDeviation: number;
  geometricaltitude_rawHexSample: string;
  geometricaltitude_metadataTag: Record<string, string>;
  verticalrate_primaryMetric: number;
  verticalrate_secondaryMetric: number;
  verticalrate_baselineAverage: number;
  verticalrate_peakObserved: number;
  verticalrate_standardDeviation: number;
  verticalrate_rawHexSample: string;
  verticalrate_metadataTag: Record<string, string>;
  airspeedkts_primaryMetric: number;
  airspeedkts_secondaryMetric: number;
  airspeedkts_baselineAverage: number;
  airspeedkts_peakObserved: number;
  airspeedkts_standardDeviation: number;
  airspeedkts_rawHexSample: string;
  airspeedkts_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type AdsbFlightTelemetryFilterV17 = Partial<AdsbFlightTelemetryRecordV17> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface AdsbFlightTelemetryRecordV18 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  modes_squawk_primaryMetric: number;
  modes_squawk_secondaryMetric: number;
  modes_squawk_baselineAverage: number;
  modes_squawk_peakObserved: number;
  modes_squawk_standardDeviation: number;
  modes_squawk_rawHexSample: string;
  modes_squawk_metadataTag: Record<string, string>;
  callsign_primaryMetric: number;
  callsign_secondaryMetric: number;
  callsign_baselineAverage: number;
  callsign_peakObserved: number;
  callsign_standardDeviation: number;
  callsign_rawHexSample: string;
  callsign_metadataTag: Record<string, string>;
  pressurealtitude_primaryMetric: number;
  pressurealtitude_secondaryMetric: number;
  pressurealtitude_baselineAverage: number;
  pressurealtitude_peakObserved: number;
  pressurealtitude_standardDeviation: number;
  pressurealtitude_rawHexSample: string;
  pressurealtitude_metadataTag: Record<string, string>;
  geometricaltitude_primaryMetric: number;
  geometricaltitude_secondaryMetric: number;
  geometricaltitude_baselineAverage: number;
  geometricaltitude_peakObserved: number;
  geometricaltitude_standardDeviation: number;
  geometricaltitude_rawHexSample: string;
  geometricaltitude_metadataTag: Record<string, string>;
  verticalrate_primaryMetric: number;
  verticalrate_secondaryMetric: number;
  verticalrate_baselineAverage: number;
  verticalrate_peakObserved: number;
  verticalrate_standardDeviation: number;
  verticalrate_rawHexSample: string;
  verticalrate_metadataTag: Record<string, string>;
  airspeedkts_primaryMetric: number;
  airspeedkts_secondaryMetric: number;
  airspeedkts_baselineAverage: number;
  airspeedkts_peakObserved: number;
  airspeedkts_standardDeviation: number;
  airspeedkts_rawHexSample: string;
  airspeedkts_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type AdsbFlightTelemetryFilterV18 = Partial<AdsbFlightTelemetryRecordV18> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface AdsbFlightTelemetryRecordV19 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  modes_squawk_primaryMetric: number;
  modes_squawk_secondaryMetric: number;
  modes_squawk_baselineAverage: number;
  modes_squawk_peakObserved: number;
  modes_squawk_standardDeviation: number;
  modes_squawk_rawHexSample: string;
  modes_squawk_metadataTag: Record<string, string>;
  callsign_primaryMetric: number;
  callsign_secondaryMetric: number;
  callsign_baselineAverage: number;
  callsign_peakObserved: number;
  callsign_standardDeviation: number;
  callsign_rawHexSample: string;
  callsign_metadataTag: Record<string, string>;
  pressurealtitude_primaryMetric: number;
  pressurealtitude_secondaryMetric: number;
  pressurealtitude_baselineAverage: number;
  pressurealtitude_peakObserved: number;
  pressurealtitude_standardDeviation: number;
  pressurealtitude_rawHexSample: string;
  pressurealtitude_metadataTag: Record<string, string>;
  geometricaltitude_primaryMetric: number;
  geometricaltitude_secondaryMetric: number;
  geometricaltitude_baselineAverage: number;
  geometricaltitude_peakObserved: number;
  geometricaltitude_standardDeviation: number;
  geometricaltitude_rawHexSample: string;
  geometricaltitude_metadataTag: Record<string, string>;
  verticalrate_primaryMetric: number;
  verticalrate_secondaryMetric: number;
  verticalrate_baselineAverage: number;
  verticalrate_peakObserved: number;
  verticalrate_standardDeviation: number;
  verticalrate_rawHexSample: string;
  verticalrate_metadataTag: Record<string, string>;
  airspeedkts_primaryMetric: number;
  airspeedkts_secondaryMetric: number;
  airspeedkts_baselineAverage: number;
  airspeedkts_peakObserved: number;
  airspeedkts_standardDeviation: number;
  airspeedkts_rawHexSample: string;
  airspeedkts_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type AdsbFlightTelemetryFilterV19 = Partial<AdsbFlightTelemetryRecordV19> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface AdsbFlightTelemetryRecordV20 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  modes_squawk_primaryMetric: number;
  modes_squawk_secondaryMetric: number;
  modes_squawk_baselineAverage: number;
  modes_squawk_peakObserved: number;
  modes_squawk_standardDeviation: number;
  modes_squawk_rawHexSample: string;
  modes_squawk_metadataTag: Record<string, string>;
  callsign_primaryMetric: number;
  callsign_secondaryMetric: number;
  callsign_baselineAverage: number;
  callsign_peakObserved: number;
  callsign_standardDeviation: number;
  callsign_rawHexSample: string;
  callsign_metadataTag: Record<string, string>;
  pressurealtitude_primaryMetric: number;
  pressurealtitude_secondaryMetric: number;
  pressurealtitude_baselineAverage: number;
  pressurealtitude_peakObserved: number;
  pressurealtitude_standardDeviation: number;
  pressurealtitude_rawHexSample: string;
  pressurealtitude_metadataTag: Record<string, string>;
  geometricaltitude_primaryMetric: number;
  geometricaltitude_secondaryMetric: number;
  geometricaltitude_baselineAverage: number;
  geometricaltitude_peakObserved: number;
  geometricaltitude_standardDeviation: number;
  geometricaltitude_rawHexSample: string;
  geometricaltitude_metadataTag: Record<string, string>;
  verticalrate_primaryMetric: number;
  verticalrate_secondaryMetric: number;
  verticalrate_baselineAverage: number;
  verticalrate_peakObserved: number;
  verticalrate_standardDeviation: number;
  verticalrate_rawHexSample: string;
  verticalrate_metadataTag: Record<string, string>;
  airspeedkts_primaryMetric: number;
  airspeedkts_secondaryMetric: number;
  airspeedkts_baselineAverage: number;
  airspeedkts_peakObserved: number;
  airspeedkts_standardDeviation: number;
  airspeedkts_rawHexSample: string;
  airspeedkts_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type AdsbFlightTelemetryFilterV20 = Partial<AdsbFlightTelemetryRecordV20> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface AdsbFlightTelemetryRecordV21 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  modes_squawk_primaryMetric: number;
  modes_squawk_secondaryMetric: number;
  modes_squawk_baselineAverage: number;
  modes_squawk_peakObserved: number;
  modes_squawk_standardDeviation: number;
  modes_squawk_rawHexSample: string;
  modes_squawk_metadataTag: Record<string, string>;
  callsign_primaryMetric: number;
  callsign_secondaryMetric: number;
  callsign_baselineAverage: number;
  callsign_peakObserved: number;
  callsign_standardDeviation: number;
  callsign_rawHexSample: string;
  callsign_metadataTag: Record<string, string>;
  pressurealtitude_primaryMetric: number;
  pressurealtitude_secondaryMetric: number;
  pressurealtitude_baselineAverage: number;
  pressurealtitude_peakObserved: number;
  pressurealtitude_standardDeviation: number;
  pressurealtitude_rawHexSample: string;
  pressurealtitude_metadataTag: Record<string, string>;
  geometricaltitude_primaryMetric: number;
  geometricaltitude_secondaryMetric: number;
  geometricaltitude_baselineAverage: number;
  geometricaltitude_peakObserved: number;
  geometricaltitude_standardDeviation: number;
  geometricaltitude_rawHexSample: string;
  geometricaltitude_metadataTag: Record<string, string>;
  verticalrate_primaryMetric: number;
  verticalrate_secondaryMetric: number;
  verticalrate_baselineAverage: number;
  verticalrate_peakObserved: number;
  verticalrate_standardDeviation: number;
  verticalrate_rawHexSample: string;
  verticalrate_metadataTag: Record<string, string>;
  airspeedkts_primaryMetric: number;
  airspeedkts_secondaryMetric: number;
  airspeedkts_baselineAverage: number;
  airspeedkts_peakObserved: number;
  airspeedkts_standardDeviation: number;
  airspeedkts_rawHexSample: string;
  airspeedkts_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type AdsbFlightTelemetryFilterV21 = Partial<AdsbFlightTelemetryRecordV21> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface AdsbFlightTelemetryRecordV22 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  modes_squawk_primaryMetric: number;
  modes_squawk_secondaryMetric: number;
  modes_squawk_baselineAverage: number;
  modes_squawk_peakObserved: number;
  modes_squawk_standardDeviation: number;
  modes_squawk_rawHexSample: string;
  modes_squawk_metadataTag: Record<string, string>;
  callsign_primaryMetric: number;
  callsign_secondaryMetric: number;
  callsign_baselineAverage: number;
  callsign_peakObserved: number;
  callsign_standardDeviation: number;
  callsign_rawHexSample: string;
  callsign_metadataTag: Record<string, string>;
  pressurealtitude_primaryMetric: number;
  pressurealtitude_secondaryMetric: number;
  pressurealtitude_baselineAverage: number;
  pressurealtitude_peakObserved: number;
  pressurealtitude_standardDeviation: number;
  pressurealtitude_rawHexSample: string;
  pressurealtitude_metadataTag: Record<string, string>;
  geometricaltitude_primaryMetric: number;
  geometricaltitude_secondaryMetric: number;
  geometricaltitude_baselineAverage: number;
  geometricaltitude_peakObserved: number;
  geometricaltitude_standardDeviation: number;
  geometricaltitude_rawHexSample: string;
  geometricaltitude_metadataTag: Record<string, string>;
  verticalrate_primaryMetric: number;
  verticalrate_secondaryMetric: number;
  verticalrate_baselineAverage: number;
  verticalrate_peakObserved: number;
  verticalrate_standardDeviation: number;
  verticalrate_rawHexSample: string;
  verticalrate_metadataTag: Record<string, string>;
  airspeedkts_primaryMetric: number;
  airspeedkts_secondaryMetric: number;
  airspeedkts_baselineAverage: number;
  airspeedkts_peakObserved: number;
  airspeedkts_standardDeviation: number;
  airspeedkts_rawHexSample: string;
  airspeedkts_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type AdsbFlightTelemetryFilterV22 = Partial<AdsbFlightTelemetryRecordV22> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface AdsbFlightTelemetryRecordV23 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  modes_squawk_primaryMetric: number;
  modes_squawk_secondaryMetric: number;
  modes_squawk_baselineAverage: number;
  modes_squawk_peakObserved: number;
  modes_squawk_standardDeviation: number;
  modes_squawk_rawHexSample: string;
  modes_squawk_metadataTag: Record<string, string>;
  callsign_primaryMetric: number;
  callsign_secondaryMetric: number;
  callsign_baselineAverage: number;
  callsign_peakObserved: number;
  callsign_standardDeviation: number;
  callsign_rawHexSample: string;
  callsign_metadataTag: Record<string, string>;
  pressurealtitude_primaryMetric: number;
  pressurealtitude_secondaryMetric: number;
  pressurealtitude_baselineAverage: number;
  pressurealtitude_peakObserved: number;
  pressurealtitude_standardDeviation: number;
  pressurealtitude_rawHexSample: string;
  pressurealtitude_metadataTag: Record<string, string>;
  geometricaltitude_primaryMetric: number;
  geometricaltitude_secondaryMetric: number;
  geometricaltitude_baselineAverage: number;
  geometricaltitude_peakObserved: number;
  geometricaltitude_standardDeviation: number;
  geometricaltitude_rawHexSample: string;
  geometricaltitude_metadataTag: Record<string, string>;
  verticalrate_primaryMetric: number;
  verticalrate_secondaryMetric: number;
  verticalrate_baselineAverage: number;
  verticalrate_peakObserved: number;
  verticalrate_standardDeviation: number;
  verticalrate_rawHexSample: string;
  verticalrate_metadataTag: Record<string, string>;
  airspeedkts_primaryMetric: number;
  airspeedkts_secondaryMetric: number;
  airspeedkts_baselineAverage: number;
  airspeedkts_peakObserved: number;
  airspeedkts_standardDeviation: number;
  airspeedkts_rawHexSample: string;
  airspeedkts_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type AdsbFlightTelemetryFilterV23 = Partial<AdsbFlightTelemetryRecordV23> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface AdsbFlightTelemetryRecordV24 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  modes_squawk_primaryMetric: number;
  modes_squawk_secondaryMetric: number;
  modes_squawk_baselineAverage: number;
  modes_squawk_peakObserved: number;
  modes_squawk_standardDeviation: number;
  modes_squawk_rawHexSample: string;
  modes_squawk_metadataTag: Record<string, string>;
  callsign_primaryMetric: number;
  callsign_secondaryMetric: number;
  callsign_baselineAverage: number;
  callsign_peakObserved: number;
  callsign_standardDeviation: number;
  callsign_rawHexSample: string;
  callsign_metadataTag: Record<string, string>;
  pressurealtitude_primaryMetric: number;
  pressurealtitude_secondaryMetric: number;
  pressurealtitude_baselineAverage: number;
  pressurealtitude_peakObserved: number;
  pressurealtitude_standardDeviation: number;
  pressurealtitude_rawHexSample: string;
  pressurealtitude_metadataTag: Record<string, string>;
  geometricaltitude_primaryMetric: number;
  geometricaltitude_secondaryMetric: number;
  geometricaltitude_baselineAverage: number;
  geometricaltitude_peakObserved: number;
  geometricaltitude_standardDeviation: number;
  geometricaltitude_rawHexSample: string;
  geometricaltitude_metadataTag: Record<string, string>;
  verticalrate_primaryMetric: number;
  verticalrate_secondaryMetric: number;
  verticalrate_baselineAverage: number;
  verticalrate_peakObserved: number;
  verticalrate_standardDeviation: number;
  verticalrate_rawHexSample: string;
  verticalrate_metadataTag: Record<string, string>;
  airspeedkts_primaryMetric: number;
  airspeedkts_secondaryMetric: number;
  airspeedkts_baselineAverage: number;
  airspeedkts_peakObserved: number;
  airspeedkts_standardDeviation: number;
  airspeedkts_rawHexSample: string;
  airspeedkts_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type AdsbFlightTelemetryFilterV24 = Partial<AdsbFlightTelemetryRecordV24> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface AdsbFlightTelemetryRecordV25 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  modes_squawk_primaryMetric: number;
  modes_squawk_secondaryMetric: number;
  modes_squawk_baselineAverage: number;
  modes_squawk_peakObserved: number;
  modes_squawk_standardDeviation: number;
  modes_squawk_rawHexSample: string;
  modes_squawk_metadataTag: Record<string, string>;
  callsign_primaryMetric: number;
  callsign_secondaryMetric: number;
  callsign_baselineAverage: number;
  callsign_peakObserved: number;
  callsign_standardDeviation: number;
  callsign_rawHexSample: string;
  callsign_metadataTag: Record<string, string>;
  pressurealtitude_primaryMetric: number;
  pressurealtitude_secondaryMetric: number;
  pressurealtitude_baselineAverage: number;
  pressurealtitude_peakObserved: number;
  pressurealtitude_standardDeviation: number;
  pressurealtitude_rawHexSample: string;
  pressurealtitude_metadataTag: Record<string, string>;
  geometricaltitude_primaryMetric: number;
  geometricaltitude_secondaryMetric: number;
  geometricaltitude_baselineAverage: number;
  geometricaltitude_peakObserved: number;
  geometricaltitude_standardDeviation: number;
  geometricaltitude_rawHexSample: string;
  geometricaltitude_metadataTag: Record<string, string>;
  verticalrate_primaryMetric: number;
  verticalrate_secondaryMetric: number;
  verticalrate_baselineAverage: number;
  verticalrate_peakObserved: number;
  verticalrate_standardDeviation: number;
  verticalrate_rawHexSample: string;
  verticalrate_metadataTag: Record<string, string>;
  airspeedkts_primaryMetric: number;
  airspeedkts_secondaryMetric: number;
  airspeedkts_baselineAverage: number;
  airspeedkts_peakObserved: number;
  airspeedkts_standardDeviation: number;
  airspeedkts_rawHexSample: string;
  airspeedkts_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type AdsbFlightTelemetryFilterV25 = Partial<AdsbFlightTelemetryRecordV25> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface AdsbFlightTelemetryRecordV26 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  modes_squawk_primaryMetric: number;
  modes_squawk_secondaryMetric: number;
  modes_squawk_baselineAverage: number;
  modes_squawk_peakObserved: number;
  modes_squawk_standardDeviation: number;
  modes_squawk_rawHexSample: string;
  modes_squawk_metadataTag: Record<string, string>;
  callsign_primaryMetric: number;
  callsign_secondaryMetric: number;
  callsign_baselineAverage: number;
  callsign_peakObserved: number;
  callsign_standardDeviation: number;
  callsign_rawHexSample: string;
  callsign_metadataTag: Record<string, string>;
  pressurealtitude_primaryMetric: number;
  pressurealtitude_secondaryMetric: number;
  pressurealtitude_baselineAverage: number;
  pressurealtitude_peakObserved: number;
  pressurealtitude_standardDeviation: number;
  pressurealtitude_rawHexSample: string;
  pressurealtitude_metadataTag: Record<string, string>;
  geometricaltitude_primaryMetric: number;
  geometricaltitude_secondaryMetric: number;
  geometricaltitude_baselineAverage: number;
  geometricaltitude_peakObserved: number;
  geometricaltitude_standardDeviation: number;
  geometricaltitude_rawHexSample: string;
  geometricaltitude_metadataTag: Record<string, string>;
  verticalrate_primaryMetric: number;
  verticalrate_secondaryMetric: number;
  verticalrate_baselineAverage: number;
  verticalrate_peakObserved: number;
  verticalrate_standardDeviation: number;
  verticalrate_rawHexSample: string;
  verticalrate_metadataTag: Record<string, string>;
  airspeedkts_primaryMetric: number;
  airspeedkts_secondaryMetric: number;
  airspeedkts_baselineAverage: number;
  airspeedkts_peakObserved: number;
  airspeedkts_standardDeviation: number;
  airspeedkts_rawHexSample: string;
  airspeedkts_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type AdsbFlightTelemetryFilterV26 = Partial<AdsbFlightTelemetryRecordV26> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface AdsbFlightTelemetryRecordV27 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  modes_squawk_primaryMetric: number;
  modes_squawk_secondaryMetric: number;
  modes_squawk_baselineAverage: number;
  modes_squawk_peakObserved: number;
  modes_squawk_standardDeviation: number;
  modes_squawk_rawHexSample: string;
  modes_squawk_metadataTag: Record<string, string>;
  callsign_primaryMetric: number;
  callsign_secondaryMetric: number;
  callsign_baselineAverage: number;
  callsign_peakObserved: number;
  callsign_standardDeviation: number;
  callsign_rawHexSample: string;
  callsign_metadataTag: Record<string, string>;
  pressurealtitude_primaryMetric: number;
  pressurealtitude_secondaryMetric: number;
  pressurealtitude_baselineAverage: number;
  pressurealtitude_peakObserved: number;
  pressurealtitude_standardDeviation: number;
  pressurealtitude_rawHexSample: string;
  pressurealtitude_metadataTag: Record<string, string>;
  geometricaltitude_primaryMetric: number;
  geometricaltitude_secondaryMetric: number;
  geometricaltitude_baselineAverage: number;
  geometricaltitude_peakObserved: number;
  geometricaltitude_standardDeviation: number;
  geometricaltitude_rawHexSample: string;
  geometricaltitude_metadataTag: Record<string, string>;
  verticalrate_primaryMetric: number;
  verticalrate_secondaryMetric: number;
  verticalrate_baselineAverage: number;
  verticalrate_peakObserved: number;
  verticalrate_standardDeviation: number;
  verticalrate_rawHexSample: string;
  verticalrate_metadataTag: Record<string, string>;
  airspeedkts_primaryMetric: number;
  airspeedkts_secondaryMetric: number;
  airspeedkts_baselineAverage: number;
  airspeedkts_peakObserved: number;
  airspeedkts_standardDeviation: number;
  airspeedkts_rawHexSample: string;
  airspeedkts_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type AdsbFlightTelemetryFilterV27 = Partial<AdsbFlightTelemetryRecordV27> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface AdsbFlightTelemetryRecordV28 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  modes_squawk_primaryMetric: number;
  modes_squawk_secondaryMetric: number;
  modes_squawk_baselineAverage: number;
  modes_squawk_peakObserved: number;
  modes_squawk_standardDeviation: number;
  modes_squawk_rawHexSample: string;
  modes_squawk_metadataTag: Record<string, string>;
  callsign_primaryMetric: number;
  callsign_secondaryMetric: number;
  callsign_baselineAverage: number;
  callsign_peakObserved: number;
  callsign_standardDeviation: number;
  callsign_rawHexSample: string;
  callsign_metadataTag: Record<string, string>;
  pressurealtitude_primaryMetric: number;
  pressurealtitude_secondaryMetric: number;
  pressurealtitude_baselineAverage: number;
  pressurealtitude_peakObserved: number;
  pressurealtitude_standardDeviation: number;
  pressurealtitude_rawHexSample: string;
  pressurealtitude_metadataTag: Record<string, string>;
  geometricaltitude_primaryMetric: number;
  geometricaltitude_secondaryMetric: number;
  geometricaltitude_baselineAverage: number;
  geometricaltitude_peakObserved: number;
  geometricaltitude_standardDeviation: number;
  geometricaltitude_rawHexSample: string;
  geometricaltitude_metadataTag: Record<string, string>;
  verticalrate_primaryMetric: number;
  verticalrate_secondaryMetric: number;
  verticalrate_baselineAverage: number;
  verticalrate_peakObserved: number;
  verticalrate_standardDeviation: number;
  verticalrate_rawHexSample: string;
  verticalrate_metadataTag: Record<string, string>;
  airspeedkts_primaryMetric: number;
  airspeedkts_secondaryMetric: number;
  airspeedkts_baselineAverage: number;
  airspeedkts_peakObserved: number;
  airspeedkts_standardDeviation: number;
  airspeedkts_rawHexSample: string;
  airspeedkts_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type AdsbFlightTelemetryFilterV28 = Partial<AdsbFlightTelemetryRecordV28> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface AdsbFlightTelemetryRecordV29 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  modes_squawk_primaryMetric: number;
  modes_squawk_secondaryMetric: number;
  modes_squawk_baselineAverage: number;
  modes_squawk_peakObserved: number;
  modes_squawk_standardDeviation: number;
  modes_squawk_rawHexSample: string;
  modes_squawk_metadataTag: Record<string, string>;
  callsign_primaryMetric: number;
  callsign_secondaryMetric: number;
  callsign_baselineAverage: number;
  callsign_peakObserved: number;
  callsign_standardDeviation: number;
  callsign_rawHexSample: string;
  callsign_metadataTag: Record<string, string>;
  pressurealtitude_primaryMetric: number;
  pressurealtitude_secondaryMetric: number;
  pressurealtitude_baselineAverage: number;
  pressurealtitude_peakObserved: number;
  pressurealtitude_standardDeviation: number;
  pressurealtitude_rawHexSample: string;
  pressurealtitude_metadataTag: Record<string, string>;
  geometricaltitude_primaryMetric: number;
  geometricaltitude_secondaryMetric: number;
  geometricaltitude_baselineAverage: number;
  geometricaltitude_peakObserved: number;
  geometricaltitude_standardDeviation: number;
  geometricaltitude_rawHexSample: string;
  geometricaltitude_metadataTag: Record<string, string>;
  verticalrate_primaryMetric: number;
  verticalrate_secondaryMetric: number;
  verticalrate_baselineAverage: number;
  verticalrate_peakObserved: number;
  verticalrate_standardDeviation: number;
  verticalrate_rawHexSample: string;
  verticalrate_metadataTag: Record<string, string>;
  airspeedkts_primaryMetric: number;
  airspeedkts_secondaryMetric: number;
  airspeedkts_baselineAverage: number;
  airspeedkts_peakObserved: number;
  airspeedkts_standardDeviation: number;
  airspeedkts_rawHexSample: string;
  airspeedkts_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type AdsbFlightTelemetryFilterV29 = Partial<AdsbFlightTelemetryRecordV29> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface AdsbFlightTelemetryRecordV30 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  modes_squawk_primaryMetric: number;
  modes_squawk_secondaryMetric: number;
  modes_squawk_baselineAverage: number;
  modes_squawk_peakObserved: number;
  modes_squawk_standardDeviation: number;
  modes_squawk_rawHexSample: string;
  modes_squawk_metadataTag: Record<string, string>;
  callsign_primaryMetric: number;
  callsign_secondaryMetric: number;
  callsign_baselineAverage: number;
  callsign_peakObserved: number;
  callsign_standardDeviation: number;
  callsign_rawHexSample: string;
  callsign_metadataTag: Record<string, string>;
  pressurealtitude_primaryMetric: number;
  pressurealtitude_secondaryMetric: number;
  pressurealtitude_baselineAverage: number;
  pressurealtitude_peakObserved: number;
  pressurealtitude_standardDeviation: number;
  pressurealtitude_rawHexSample: string;
  pressurealtitude_metadataTag: Record<string, string>;
  geometricaltitude_primaryMetric: number;
  geometricaltitude_secondaryMetric: number;
  geometricaltitude_baselineAverage: number;
  geometricaltitude_peakObserved: number;
  geometricaltitude_standardDeviation: number;
  geometricaltitude_rawHexSample: string;
  geometricaltitude_metadataTag: Record<string, string>;
  verticalrate_primaryMetric: number;
  verticalrate_secondaryMetric: number;
  verticalrate_baselineAverage: number;
  verticalrate_peakObserved: number;
  verticalrate_standardDeviation: number;
  verticalrate_rawHexSample: string;
  verticalrate_metadataTag: Record<string, string>;
  airspeedkts_primaryMetric: number;
  airspeedkts_secondaryMetric: number;
  airspeedkts_baselineAverage: number;
  airspeedkts_peakObserved: number;
  airspeedkts_standardDeviation: number;
  airspeedkts_rawHexSample: string;
  airspeedkts_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type AdsbFlightTelemetryFilterV30 = Partial<AdsbFlightTelemetryRecordV30> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface AdsbFlightTelemetryRecordV31 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  modes_squawk_primaryMetric: number;
  modes_squawk_secondaryMetric: number;
  modes_squawk_baselineAverage: number;
  modes_squawk_peakObserved: number;
  modes_squawk_standardDeviation: number;
  modes_squawk_rawHexSample: string;
  modes_squawk_metadataTag: Record<string, string>;
  callsign_primaryMetric: number;
  callsign_secondaryMetric: number;
  callsign_baselineAverage: number;
  callsign_peakObserved: number;
  callsign_standardDeviation: number;
  callsign_rawHexSample: string;
  callsign_metadataTag: Record<string, string>;
  pressurealtitude_primaryMetric: number;
  pressurealtitude_secondaryMetric: number;
  pressurealtitude_baselineAverage: number;
  pressurealtitude_peakObserved: number;
  pressurealtitude_standardDeviation: number;
  pressurealtitude_rawHexSample: string;
  pressurealtitude_metadataTag: Record<string, string>;
  geometricaltitude_primaryMetric: number;
  geometricaltitude_secondaryMetric: number;
  geometricaltitude_baselineAverage: number;
  geometricaltitude_peakObserved: number;
  geometricaltitude_standardDeviation: number;
  geometricaltitude_rawHexSample: string;
  geometricaltitude_metadataTag: Record<string, string>;
  verticalrate_primaryMetric: number;
  verticalrate_secondaryMetric: number;
  verticalrate_baselineAverage: number;
  verticalrate_peakObserved: number;
  verticalrate_standardDeviation: number;
  verticalrate_rawHexSample: string;
  verticalrate_metadataTag: Record<string, string>;
  airspeedkts_primaryMetric: number;
  airspeedkts_secondaryMetric: number;
  airspeedkts_baselineAverage: number;
  airspeedkts_peakObserved: number;
  airspeedkts_standardDeviation: number;
  airspeedkts_rawHexSample: string;
  airspeedkts_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type AdsbFlightTelemetryFilterV31 = Partial<AdsbFlightTelemetryRecordV31> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface AdsbFlightTelemetryRecordV32 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  modes_squawk_primaryMetric: number;
  modes_squawk_secondaryMetric: number;
  modes_squawk_baselineAverage: number;
  modes_squawk_peakObserved: number;
  modes_squawk_standardDeviation: number;
  modes_squawk_rawHexSample: string;
  modes_squawk_metadataTag: Record<string, string>;
  callsign_primaryMetric: number;
  callsign_secondaryMetric: number;
  callsign_baselineAverage: number;
  callsign_peakObserved: number;
  callsign_standardDeviation: number;
  callsign_rawHexSample: string;
  callsign_metadataTag: Record<string, string>;
  pressurealtitude_primaryMetric: number;
  pressurealtitude_secondaryMetric: number;
  pressurealtitude_baselineAverage: number;
  pressurealtitude_peakObserved: number;
  pressurealtitude_standardDeviation: number;
  pressurealtitude_rawHexSample: string;
  pressurealtitude_metadataTag: Record<string, string>;
  geometricaltitude_primaryMetric: number;
  geometricaltitude_secondaryMetric: number;
  geometricaltitude_baselineAverage: number;
  geometricaltitude_peakObserved: number;
  geometricaltitude_standardDeviation: number;
  geometricaltitude_rawHexSample: string;
  geometricaltitude_metadataTag: Record<string, string>;
  verticalrate_primaryMetric: number;
  verticalrate_secondaryMetric: number;
  verticalrate_baselineAverage: number;
  verticalrate_peakObserved: number;
  verticalrate_standardDeviation: number;
  verticalrate_rawHexSample: string;
  verticalrate_metadataTag: Record<string, string>;
  airspeedkts_primaryMetric: number;
  airspeedkts_secondaryMetric: number;
  airspeedkts_baselineAverage: number;
  airspeedkts_peakObserved: number;
  airspeedkts_standardDeviation: number;
  airspeedkts_rawHexSample: string;
  airspeedkts_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type AdsbFlightTelemetryFilterV32 = Partial<AdsbFlightTelemetryRecordV32> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface AdsbFlightTelemetryRecordV33 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  modes_squawk_primaryMetric: number;
  modes_squawk_secondaryMetric: number;
  modes_squawk_baselineAverage: number;
  modes_squawk_peakObserved: number;
  modes_squawk_standardDeviation: number;
  modes_squawk_rawHexSample: string;
  modes_squawk_metadataTag: Record<string, string>;
  callsign_primaryMetric: number;
  callsign_secondaryMetric: number;
  callsign_baselineAverage: number;
  callsign_peakObserved: number;
  callsign_standardDeviation: number;
  callsign_rawHexSample: string;
  callsign_metadataTag: Record<string, string>;
  pressurealtitude_primaryMetric: number;
  pressurealtitude_secondaryMetric: number;
  pressurealtitude_baselineAverage: number;
  pressurealtitude_peakObserved: number;
  pressurealtitude_standardDeviation: number;
  pressurealtitude_rawHexSample: string;
  pressurealtitude_metadataTag: Record<string, string>;
  geometricaltitude_primaryMetric: number;
  geometricaltitude_secondaryMetric: number;
  geometricaltitude_baselineAverage: number;
  geometricaltitude_peakObserved: number;
  geometricaltitude_standardDeviation: number;
  geometricaltitude_rawHexSample: string;
  geometricaltitude_metadataTag: Record<string, string>;
  verticalrate_primaryMetric: number;
  verticalrate_secondaryMetric: number;
  verticalrate_baselineAverage: number;
  verticalrate_peakObserved: number;
  verticalrate_standardDeviation: number;
  verticalrate_rawHexSample: string;
  verticalrate_metadataTag: Record<string, string>;
  airspeedkts_primaryMetric: number;
  airspeedkts_secondaryMetric: number;
  airspeedkts_baselineAverage: number;
  airspeedkts_peakObserved: number;
  airspeedkts_standardDeviation: number;
  airspeedkts_rawHexSample: string;
  airspeedkts_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type AdsbFlightTelemetryFilterV33 = Partial<AdsbFlightTelemetryRecordV33> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface AdsbFlightTelemetryRecordV34 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  modes_squawk_primaryMetric: number;
  modes_squawk_secondaryMetric: number;
  modes_squawk_baselineAverage: number;
  modes_squawk_peakObserved: number;
  modes_squawk_standardDeviation: number;
  modes_squawk_rawHexSample: string;
  modes_squawk_metadataTag: Record<string, string>;
  callsign_primaryMetric: number;
  callsign_secondaryMetric: number;
  callsign_baselineAverage: number;
  callsign_peakObserved: number;
  callsign_standardDeviation: number;
  callsign_rawHexSample: string;
  callsign_metadataTag: Record<string, string>;
  pressurealtitude_primaryMetric: number;
  pressurealtitude_secondaryMetric: number;
  pressurealtitude_baselineAverage: number;
  pressurealtitude_peakObserved: number;
  pressurealtitude_standardDeviation: number;
  pressurealtitude_rawHexSample: string;
  pressurealtitude_metadataTag: Record<string, string>;
  geometricaltitude_primaryMetric: number;
  geometricaltitude_secondaryMetric: number;
  geometricaltitude_baselineAverage: number;
  geometricaltitude_peakObserved: number;
  geometricaltitude_standardDeviation: number;
  geometricaltitude_rawHexSample: string;
  geometricaltitude_metadataTag: Record<string, string>;
  verticalrate_primaryMetric: number;
  verticalrate_secondaryMetric: number;
  verticalrate_baselineAverage: number;
  verticalrate_peakObserved: number;
  verticalrate_standardDeviation: number;
  verticalrate_rawHexSample: string;
  verticalrate_metadataTag: Record<string, string>;
  airspeedkts_primaryMetric: number;
  airspeedkts_secondaryMetric: number;
  airspeedkts_baselineAverage: number;
  airspeedkts_peakObserved: number;
  airspeedkts_standardDeviation: number;
  airspeedkts_rawHexSample: string;
  airspeedkts_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type AdsbFlightTelemetryFilterV34 = Partial<AdsbFlightTelemetryRecordV34> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface AdsbFlightTelemetryRecordV35 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  modes_squawk_primaryMetric: number;
  modes_squawk_secondaryMetric: number;
  modes_squawk_baselineAverage: number;
  modes_squawk_peakObserved: number;
  modes_squawk_standardDeviation: number;
  modes_squawk_rawHexSample: string;
  modes_squawk_metadataTag: Record<string, string>;
  callsign_primaryMetric: number;
  callsign_secondaryMetric: number;
  callsign_baselineAverage: number;
  callsign_peakObserved: number;
  callsign_standardDeviation: number;
  callsign_rawHexSample: string;
  callsign_metadataTag: Record<string, string>;
  pressurealtitude_primaryMetric: number;
  pressurealtitude_secondaryMetric: number;
  pressurealtitude_baselineAverage: number;
  pressurealtitude_peakObserved: number;
  pressurealtitude_standardDeviation: number;
  pressurealtitude_rawHexSample: string;
  pressurealtitude_metadataTag: Record<string, string>;
  geometricaltitude_primaryMetric: number;
  geometricaltitude_secondaryMetric: number;
  geometricaltitude_baselineAverage: number;
  geometricaltitude_peakObserved: number;
  geometricaltitude_standardDeviation: number;
  geometricaltitude_rawHexSample: string;
  geometricaltitude_metadataTag: Record<string, string>;
  verticalrate_primaryMetric: number;
  verticalrate_secondaryMetric: number;
  verticalrate_baselineAverage: number;
  verticalrate_peakObserved: number;
  verticalrate_standardDeviation: number;
  verticalrate_rawHexSample: string;
  verticalrate_metadataTag: Record<string, string>;
  airspeedkts_primaryMetric: number;
  airspeedkts_secondaryMetric: number;
  airspeedkts_baselineAverage: number;
  airspeedkts_peakObserved: number;
  airspeedkts_standardDeviation: number;
  airspeedkts_rawHexSample: string;
  airspeedkts_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type AdsbFlightTelemetryFilterV35 = Partial<AdsbFlightTelemetryRecordV35> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface AdsbFlightTelemetryRecordV36 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  modes_squawk_primaryMetric: number;
  modes_squawk_secondaryMetric: number;
  modes_squawk_baselineAverage: number;
  modes_squawk_peakObserved: number;
  modes_squawk_standardDeviation: number;
  modes_squawk_rawHexSample: string;
  modes_squawk_metadataTag: Record<string, string>;
  callsign_primaryMetric: number;
  callsign_secondaryMetric: number;
  callsign_baselineAverage: number;
  callsign_peakObserved: number;
  callsign_standardDeviation: number;
  callsign_rawHexSample: string;
  callsign_metadataTag: Record<string, string>;
  pressurealtitude_primaryMetric: number;
  pressurealtitude_secondaryMetric: number;
  pressurealtitude_baselineAverage: number;
  pressurealtitude_peakObserved: number;
  pressurealtitude_standardDeviation: number;
  pressurealtitude_rawHexSample: string;
  pressurealtitude_metadataTag: Record<string, string>;
  geometricaltitude_primaryMetric: number;
  geometricaltitude_secondaryMetric: number;
  geometricaltitude_baselineAverage: number;
  geometricaltitude_peakObserved: number;
  geometricaltitude_standardDeviation: number;
  geometricaltitude_rawHexSample: string;
  geometricaltitude_metadataTag: Record<string, string>;
  verticalrate_primaryMetric: number;
  verticalrate_secondaryMetric: number;
  verticalrate_baselineAverage: number;
  verticalrate_peakObserved: number;
  verticalrate_standardDeviation: number;
  verticalrate_rawHexSample: string;
  verticalrate_metadataTag: Record<string, string>;
  airspeedkts_primaryMetric: number;
  airspeedkts_secondaryMetric: number;
  airspeedkts_baselineAverage: number;
  airspeedkts_peakObserved: number;
  airspeedkts_standardDeviation: number;
  airspeedkts_rawHexSample: string;
  airspeedkts_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type AdsbFlightTelemetryFilterV36 = Partial<AdsbFlightTelemetryRecordV36> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface AdsbFlightTelemetryRecordV37 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  modes_squawk_primaryMetric: number;
  modes_squawk_secondaryMetric: number;
  modes_squawk_baselineAverage: number;
  modes_squawk_peakObserved: number;
  modes_squawk_standardDeviation: number;
  modes_squawk_rawHexSample: string;
  modes_squawk_metadataTag: Record<string, string>;
  callsign_primaryMetric: number;
  callsign_secondaryMetric: number;
  callsign_baselineAverage: number;
  callsign_peakObserved: number;
  callsign_standardDeviation: number;
  callsign_rawHexSample: string;
  callsign_metadataTag: Record<string, string>;
  pressurealtitude_primaryMetric: number;
  pressurealtitude_secondaryMetric: number;
  pressurealtitude_baselineAverage: number;
  pressurealtitude_peakObserved: number;
  pressurealtitude_standardDeviation: number;
  pressurealtitude_rawHexSample: string;
  pressurealtitude_metadataTag: Record<string, string>;
  geometricaltitude_primaryMetric: number;
  geometricaltitude_secondaryMetric: number;
  geometricaltitude_baselineAverage: number;
  geometricaltitude_peakObserved: number;
  geometricaltitude_standardDeviation: number;
  geometricaltitude_rawHexSample: string;
  geometricaltitude_metadataTag: Record<string, string>;
  verticalrate_primaryMetric: number;
  verticalrate_secondaryMetric: number;
  verticalrate_baselineAverage: number;
  verticalrate_peakObserved: number;
  verticalrate_standardDeviation: number;
  verticalrate_rawHexSample: string;
  verticalrate_metadataTag: Record<string, string>;
  airspeedkts_primaryMetric: number;
  airspeedkts_secondaryMetric: number;
  airspeedkts_baselineAverage: number;
  airspeedkts_peakObserved: number;
  airspeedkts_standardDeviation: number;
  airspeedkts_rawHexSample: string;
  airspeedkts_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type AdsbFlightTelemetryFilterV37 = Partial<AdsbFlightTelemetryRecordV37> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface AdsbFlightTelemetryRecordV38 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  modes_squawk_primaryMetric: number;
  modes_squawk_secondaryMetric: number;
  modes_squawk_baselineAverage: number;
  modes_squawk_peakObserved: number;
  modes_squawk_standardDeviation: number;
  modes_squawk_rawHexSample: string;
  modes_squawk_metadataTag: Record<string, string>;
  callsign_primaryMetric: number;
  callsign_secondaryMetric: number;
  callsign_baselineAverage: number;
  callsign_peakObserved: number;
  callsign_standardDeviation: number;
  callsign_rawHexSample: string;
  callsign_metadataTag: Record<string, string>;
  pressurealtitude_primaryMetric: number;
  pressurealtitude_secondaryMetric: number;
  pressurealtitude_baselineAverage: number;
  pressurealtitude_peakObserved: number;
  pressurealtitude_standardDeviation: number;
  pressurealtitude_rawHexSample: string;
  pressurealtitude_metadataTag: Record<string, string>;
  geometricaltitude_primaryMetric: number;
  geometricaltitude_secondaryMetric: number;
  geometricaltitude_baselineAverage: number;
  geometricaltitude_peakObserved: number;
  geometricaltitude_standardDeviation: number;
  geometricaltitude_rawHexSample: string;
  geometricaltitude_metadataTag: Record<string, string>;
  verticalrate_primaryMetric: number;
  verticalrate_secondaryMetric: number;
  verticalrate_baselineAverage: number;
  verticalrate_peakObserved: number;
  verticalrate_standardDeviation: number;
  verticalrate_rawHexSample: string;
  verticalrate_metadataTag: Record<string, string>;
  airspeedkts_primaryMetric: number;
  airspeedkts_secondaryMetric: number;
  airspeedkts_baselineAverage: number;
  airspeedkts_peakObserved: number;
  airspeedkts_standardDeviation: number;
  airspeedkts_rawHexSample: string;
  airspeedkts_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type AdsbFlightTelemetryFilterV38 = Partial<AdsbFlightTelemetryRecordV38> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface AdsbFlightTelemetryRecordV39 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  modes_squawk_primaryMetric: number;
  modes_squawk_secondaryMetric: number;
  modes_squawk_baselineAverage: number;
  modes_squawk_peakObserved: number;
  modes_squawk_standardDeviation: number;
  modes_squawk_rawHexSample: string;
  modes_squawk_metadataTag: Record<string, string>;
  callsign_primaryMetric: number;
  callsign_secondaryMetric: number;
  callsign_baselineAverage: number;
  callsign_peakObserved: number;
  callsign_standardDeviation: number;
  callsign_rawHexSample: string;
  callsign_metadataTag: Record<string, string>;
  pressurealtitude_primaryMetric: number;
  pressurealtitude_secondaryMetric: number;
  pressurealtitude_baselineAverage: number;
  pressurealtitude_peakObserved: number;
  pressurealtitude_standardDeviation: number;
  pressurealtitude_rawHexSample: string;
  pressurealtitude_metadataTag: Record<string, string>;
  geometricaltitude_primaryMetric: number;
  geometricaltitude_secondaryMetric: number;
  geometricaltitude_baselineAverage: number;
  geometricaltitude_peakObserved: number;
  geometricaltitude_standardDeviation: number;
  geometricaltitude_rawHexSample: string;
  geometricaltitude_metadataTag: Record<string, string>;
  verticalrate_primaryMetric: number;
  verticalrate_secondaryMetric: number;
  verticalrate_baselineAverage: number;
  verticalrate_peakObserved: number;
  verticalrate_standardDeviation: number;
  verticalrate_rawHexSample: string;
  verticalrate_metadataTag: Record<string, string>;
  airspeedkts_primaryMetric: number;
  airspeedkts_secondaryMetric: number;
  airspeedkts_baselineAverage: number;
  airspeedkts_peakObserved: number;
  airspeedkts_standardDeviation: number;
  airspeedkts_rawHexSample: string;
  airspeedkts_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type AdsbFlightTelemetryFilterV39 = Partial<AdsbFlightTelemetryRecordV39> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface AdsbFlightTelemetryRecordV40 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  modes_squawk_primaryMetric: number;
  modes_squawk_secondaryMetric: number;
  modes_squawk_baselineAverage: number;
  modes_squawk_peakObserved: number;
  modes_squawk_standardDeviation: number;
  modes_squawk_rawHexSample: string;
  modes_squawk_metadataTag: Record<string, string>;
  callsign_primaryMetric: number;
  callsign_secondaryMetric: number;
  callsign_baselineAverage: number;
  callsign_peakObserved: number;
  callsign_standardDeviation: number;
  callsign_rawHexSample: string;
  callsign_metadataTag: Record<string, string>;
  pressurealtitude_primaryMetric: number;
  pressurealtitude_secondaryMetric: number;
  pressurealtitude_baselineAverage: number;
  pressurealtitude_peakObserved: number;
  pressurealtitude_standardDeviation: number;
  pressurealtitude_rawHexSample: string;
  pressurealtitude_metadataTag: Record<string, string>;
  geometricaltitude_primaryMetric: number;
  geometricaltitude_secondaryMetric: number;
  geometricaltitude_baselineAverage: number;
  geometricaltitude_peakObserved: number;
  geometricaltitude_standardDeviation: number;
  geometricaltitude_rawHexSample: string;
  geometricaltitude_metadataTag: Record<string, string>;
  verticalrate_primaryMetric: number;
  verticalrate_secondaryMetric: number;
  verticalrate_baselineAverage: number;
  verticalrate_peakObserved: number;
  verticalrate_standardDeviation: number;
  verticalrate_rawHexSample: string;
  verticalrate_metadataTag: Record<string, string>;
  airspeedkts_primaryMetric: number;
  airspeedkts_secondaryMetric: number;
  airspeedkts_baselineAverage: number;
  airspeedkts_peakObserved: number;
  airspeedkts_standardDeviation: number;
  airspeedkts_rawHexSample: string;
  airspeedkts_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type AdsbFlightTelemetryFilterV40 = Partial<AdsbFlightTelemetryRecordV40> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};
