/**
 * Enterprise Telecommunications Protocol Specification: BGP-4 Peering, NLRI Prefix Advertisements and Flap Monitoring
 * Module: @geonet/types/telecom/bgp4_routing_telemetry
 * Standard Compliance: 3GPP TS 38.401, IETF RFC Standards, ITU-T G.8032
 */

export interface BGP4Peering,NLRIPrefixAdvertisementsandFlapMonitoringConfig {
  samplingIntervalMs: number;
  collectionEnabled: boolean;
  highWatermarkThreshold: number;
  lowWatermarkThreshold: number;
  retryAttempts: number;
  timeoutMs: number;
}

export interface Bgp4RoutingTelemetryRecordV1 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  peeras_primaryMetric: number;
  peeras_secondaryMetric: number;
  peeras_baselineAverage: number;
  peeras_peakObserved: number;
  peeras_standardDeviation: number;
  peeras_rawHexSample: string;
  peeras_metadataTag: Record<string, string>;
  localas_primaryMetric: number;
  localas_secondaryMetric: number;
  localas_baselineAverage: number;
  localas_peakObserved: number;
  localas_standardDeviation: number;
  localas_rawHexSample: string;
  localas_metadataTag: Record<string, string>;
  peerrouterid_primaryMetric: number;
  peerrouterid_secondaryMetric: number;
  peerrouterid_baselineAverage: number;
  peerrouterid_peakObserved: number;
  peerrouterid_standardDeviation: number;
  peerrouterid_rawHexSample: string;
  peerrouterid_metadataTag: Record<string, string>;
  bgpstate_primaryMetric: number;
  bgpstate_secondaryMetric: number;
  bgpstate_baselineAverage: number;
  bgpstate_peakObserved: number;
  bgpstate_standardDeviation: number;
  bgpstate_rawHexSample: string;
  bgpstate_metadataTag: Record<string, string>;
  advertisedprefixes_primaryMetric: number;
  advertisedprefixes_secondaryMetric: number;
  advertisedprefixes_baselineAverage: number;
  advertisedprefixes_peakObserved: number;
  advertisedprefixes_standardDeviation: number;
  advertisedprefixes_rawHexSample: string;
  advertisedprefixes_metadataTag: Record<string, string>;
  withdrawnprefixes_primaryMetric: number;
  withdrawnprefixes_secondaryMetric: number;
  withdrawnprefixes_baselineAverage: number;
  withdrawnprefixes_peakObserved: number;
  withdrawnprefixes_standardDeviation: number;
  withdrawnprefixes_rawHexSample: string;
  withdrawnprefixes_metadataTag: Record<string, string>;
  flapcount_primaryMetric: number;
  flapcount_secondaryMetric: number;
  flapcount_baselineAverage: number;
  flapcount_peakObserved: number;
  flapcount_standardDeviation: number;
  flapcount_rawHexSample: string;
  flapcount_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Bgp4RoutingTelemetryFilterV1 = Partial<Bgp4RoutingTelemetryRecordV1> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Bgp4RoutingTelemetryRecordV2 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  peeras_primaryMetric: number;
  peeras_secondaryMetric: number;
  peeras_baselineAverage: number;
  peeras_peakObserved: number;
  peeras_standardDeviation: number;
  peeras_rawHexSample: string;
  peeras_metadataTag: Record<string, string>;
  localas_primaryMetric: number;
  localas_secondaryMetric: number;
  localas_baselineAverage: number;
  localas_peakObserved: number;
  localas_standardDeviation: number;
  localas_rawHexSample: string;
  localas_metadataTag: Record<string, string>;
  peerrouterid_primaryMetric: number;
  peerrouterid_secondaryMetric: number;
  peerrouterid_baselineAverage: number;
  peerrouterid_peakObserved: number;
  peerrouterid_standardDeviation: number;
  peerrouterid_rawHexSample: string;
  peerrouterid_metadataTag: Record<string, string>;
  bgpstate_primaryMetric: number;
  bgpstate_secondaryMetric: number;
  bgpstate_baselineAverage: number;
  bgpstate_peakObserved: number;
  bgpstate_standardDeviation: number;
  bgpstate_rawHexSample: string;
  bgpstate_metadataTag: Record<string, string>;
  advertisedprefixes_primaryMetric: number;
  advertisedprefixes_secondaryMetric: number;
  advertisedprefixes_baselineAverage: number;
  advertisedprefixes_peakObserved: number;
  advertisedprefixes_standardDeviation: number;
  advertisedprefixes_rawHexSample: string;
  advertisedprefixes_metadataTag: Record<string, string>;
  withdrawnprefixes_primaryMetric: number;
  withdrawnprefixes_secondaryMetric: number;
  withdrawnprefixes_baselineAverage: number;
  withdrawnprefixes_peakObserved: number;
  withdrawnprefixes_standardDeviation: number;
  withdrawnprefixes_rawHexSample: string;
  withdrawnprefixes_metadataTag: Record<string, string>;
  flapcount_primaryMetric: number;
  flapcount_secondaryMetric: number;
  flapcount_baselineAverage: number;
  flapcount_peakObserved: number;
  flapcount_standardDeviation: number;
  flapcount_rawHexSample: string;
  flapcount_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Bgp4RoutingTelemetryFilterV2 = Partial<Bgp4RoutingTelemetryRecordV2> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Bgp4RoutingTelemetryRecordV3 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  peeras_primaryMetric: number;
  peeras_secondaryMetric: number;
  peeras_baselineAverage: number;
  peeras_peakObserved: number;
  peeras_standardDeviation: number;
  peeras_rawHexSample: string;
  peeras_metadataTag: Record<string, string>;
  localas_primaryMetric: number;
  localas_secondaryMetric: number;
  localas_baselineAverage: number;
  localas_peakObserved: number;
  localas_standardDeviation: number;
  localas_rawHexSample: string;
  localas_metadataTag: Record<string, string>;
  peerrouterid_primaryMetric: number;
  peerrouterid_secondaryMetric: number;
  peerrouterid_baselineAverage: number;
  peerrouterid_peakObserved: number;
  peerrouterid_standardDeviation: number;
  peerrouterid_rawHexSample: string;
  peerrouterid_metadataTag: Record<string, string>;
  bgpstate_primaryMetric: number;
  bgpstate_secondaryMetric: number;
  bgpstate_baselineAverage: number;
  bgpstate_peakObserved: number;
  bgpstate_standardDeviation: number;
  bgpstate_rawHexSample: string;
  bgpstate_metadataTag: Record<string, string>;
  advertisedprefixes_primaryMetric: number;
  advertisedprefixes_secondaryMetric: number;
  advertisedprefixes_baselineAverage: number;
  advertisedprefixes_peakObserved: number;
  advertisedprefixes_standardDeviation: number;
  advertisedprefixes_rawHexSample: string;
  advertisedprefixes_metadataTag: Record<string, string>;
  withdrawnprefixes_primaryMetric: number;
  withdrawnprefixes_secondaryMetric: number;
  withdrawnprefixes_baselineAverage: number;
  withdrawnprefixes_peakObserved: number;
  withdrawnprefixes_standardDeviation: number;
  withdrawnprefixes_rawHexSample: string;
  withdrawnprefixes_metadataTag: Record<string, string>;
  flapcount_primaryMetric: number;
  flapcount_secondaryMetric: number;
  flapcount_baselineAverage: number;
  flapcount_peakObserved: number;
  flapcount_standardDeviation: number;
  flapcount_rawHexSample: string;
  flapcount_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Bgp4RoutingTelemetryFilterV3 = Partial<Bgp4RoutingTelemetryRecordV3> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Bgp4RoutingTelemetryRecordV4 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  peeras_primaryMetric: number;
  peeras_secondaryMetric: number;
  peeras_baselineAverage: number;
  peeras_peakObserved: number;
  peeras_standardDeviation: number;
  peeras_rawHexSample: string;
  peeras_metadataTag: Record<string, string>;
  localas_primaryMetric: number;
  localas_secondaryMetric: number;
  localas_baselineAverage: number;
  localas_peakObserved: number;
  localas_standardDeviation: number;
  localas_rawHexSample: string;
  localas_metadataTag: Record<string, string>;
  peerrouterid_primaryMetric: number;
  peerrouterid_secondaryMetric: number;
  peerrouterid_baselineAverage: number;
  peerrouterid_peakObserved: number;
  peerrouterid_standardDeviation: number;
  peerrouterid_rawHexSample: string;
  peerrouterid_metadataTag: Record<string, string>;
  bgpstate_primaryMetric: number;
  bgpstate_secondaryMetric: number;
  bgpstate_baselineAverage: number;
  bgpstate_peakObserved: number;
  bgpstate_standardDeviation: number;
  bgpstate_rawHexSample: string;
  bgpstate_metadataTag: Record<string, string>;
  advertisedprefixes_primaryMetric: number;
  advertisedprefixes_secondaryMetric: number;
  advertisedprefixes_baselineAverage: number;
  advertisedprefixes_peakObserved: number;
  advertisedprefixes_standardDeviation: number;
  advertisedprefixes_rawHexSample: string;
  advertisedprefixes_metadataTag: Record<string, string>;
  withdrawnprefixes_primaryMetric: number;
  withdrawnprefixes_secondaryMetric: number;
  withdrawnprefixes_baselineAverage: number;
  withdrawnprefixes_peakObserved: number;
  withdrawnprefixes_standardDeviation: number;
  withdrawnprefixes_rawHexSample: string;
  withdrawnprefixes_metadataTag: Record<string, string>;
  flapcount_primaryMetric: number;
  flapcount_secondaryMetric: number;
  flapcount_baselineAverage: number;
  flapcount_peakObserved: number;
  flapcount_standardDeviation: number;
  flapcount_rawHexSample: string;
  flapcount_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Bgp4RoutingTelemetryFilterV4 = Partial<Bgp4RoutingTelemetryRecordV4> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Bgp4RoutingTelemetryRecordV5 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  peeras_primaryMetric: number;
  peeras_secondaryMetric: number;
  peeras_baselineAverage: number;
  peeras_peakObserved: number;
  peeras_standardDeviation: number;
  peeras_rawHexSample: string;
  peeras_metadataTag: Record<string, string>;
  localas_primaryMetric: number;
  localas_secondaryMetric: number;
  localas_baselineAverage: number;
  localas_peakObserved: number;
  localas_standardDeviation: number;
  localas_rawHexSample: string;
  localas_metadataTag: Record<string, string>;
  peerrouterid_primaryMetric: number;
  peerrouterid_secondaryMetric: number;
  peerrouterid_baselineAverage: number;
  peerrouterid_peakObserved: number;
  peerrouterid_standardDeviation: number;
  peerrouterid_rawHexSample: string;
  peerrouterid_metadataTag: Record<string, string>;
  bgpstate_primaryMetric: number;
  bgpstate_secondaryMetric: number;
  bgpstate_baselineAverage: number;
  bgpstate_peakObserved: number;
  bgpstate_standardDeviation: number;
  bgpstate_rawHexSample: string;
  bgpstate_metadataTag: Record<string, string>;
  advertisedprefixes_primaryMetric: number;
  advertisedprefixes_secondaryMetric: number;
  advertisedprefixes_baselineAverage: number;
  advertisedprefixes_peakObserved: number;
  advertisedprefixes_standardDeviation: number;
  advertisedprefixes_rawHexSample: string;
  advertisedprefixes_metadataTag: Record<string, string>;
  withdrawnprefixes_primaryMetric: number;
  withdrawnprefixes_secondaryMetric: number;
  withdrawnprefixes_baselineAverage: number;
  withdrawnprefixes_peakObserved: number;
  withdrawnprefixes_standardDeviation: number;
  withdrawnprefixes_rawHexSample: string;
  withdrawnprefixes_metadataTag: Record<string, string>;
  flapcount_primaryMetric: number;
  flapcount_secondaryMetric: number;
  flapcount_baselineAverage: number;
  flapcount_peakObserved: number;
  flapcount_standardDeviation: number;
  flapcount_rawHexSample: string;
  flapcount_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Bgp4RoutingTelemetryFilterV5 = Partial<Bgp4RoutingTelemetryRecordV5> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Bgp4RoutingTelemetryRecordV6 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  peeras_primaryMetric: number;
  peeras_secondaryMetric: number;
  peeras_baselineAverage: number;
  peeras_peakObserved: number;
  peeras_standardDeviation: number;
  peeras_rawHexSample: string;
  peeras_metadataTag: Record<string, string>;
  localas_primaryMetric: number;
  localas_secondaryMetric: number;
  localas_baselineAverage: number;
  localas_peakObserved: number;
  localas_standardDeviation: number;
  localas_rawHexSample: string;
  localas_metadataTag: Record<string, string>;
  peerrouterid_primaryMetric: number;
  peerrouterid_secondaryMetric: number;
  peerrouterid_baselineAverage: number;
  peerrouterid_peakObserved: number;
  peerrouterid_standardDeviation: number;
  peerrouterid_rawHexSample: string;
  peerrouterid_metadataTag: Record<string, string>;
  bgpstate_primaryMetric: number;
  bgpstate_secondaryMetric: number;
  bgpstate_baselineAverage: number;
  bgpstate_peakObserved: number;
  bgpstate_standardDeviation: number;
  bgpstate_rawHexSample: string;
  bgpstate_metadataTag: Record<string, string>;
  advertisedprefixes_primaryMetric: number;
  advertisedprefixes_secondaryMetric: number;
  advertisedprefixes_baselineAverage: number;
  advertisedprefixes_peakObserved: number;
  advertisedprefixes_standardDeviation: number;
  advertisedprefixes_rawHexSample: string;
  advertisedprefixes_metadataTag: Record<string, string>;
  withdrawnprefixes_primaryMetric: number;
  withdrawnprefixes_secondaryMetric: number;
  withdrawnprefixes_baselineAverage: number;
  withdrawnprefixes_peakObserved: number;
  withdrawnprefixes_standardDeviation: number;
  withdrawnprefixes_rawHexSample: string;
  withdrawnprefixes_metadataTag: Record<string, string>;
  flapcount_primaryMetric: number;
  flapcount_secondaryMetric: number;
  flapcount_baselineAverage: number;
  flapcount_peakObserved: number;
  flapcount_standardDeviation: number;
  flapcount_rawHexSample: string;
  flapcount_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Bgp4RoutingTelemetryFilterV6 = Partial<Bgp4RoutingTelemetryRecordV6> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Bgp4RoutingTelemetryRecordV7 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  peeras_primaryMetric: number;
  peeras_secondaryMetric: number;
  peeras_baselineAverage: number;
  peeras_peakObserved: number;
  peeras_standardDeviation: number;
  peeras_rawHexSample: string;
  peeras_metadataTag: Record<string, string>;
  localas_primaryMetric: number;
  localas_secondaryMetric: number;
  localas_baselineAverage: number;
  localas_peakObserved: number;
  localas_standardDeviation: number;
  localas_rawHexSample: string;
  localas_metadataTag: Record<string, string>;
  peerrouterid_primaryMetric: number;
  peerrouterid_secondaryMetric: number;
  peerrouterid_baselineAverage: number;
  peerrouterid_peakObserved: number;
  peerrouterid_standardDeviation: number;
  peerrouterid_rawHexSample: string;
  peerrouterid_metadataTag: Record<string, string>;
  bgpstate_primaryMetric: number;
  bgpstate_secondaryMetric: number;
  bgpstate_baselineAverage: number;
  bgpstate_peakObserved: number;
  bgpstate_standardDeviation: number;
  bgpstate_rawHexSample: string;
  bgpstate_metadataTag: Record<string, string>;
  advertisedprefixes_primaryMetric: number;
  advertisedprefixes_secondaryMetric: number;
  advertisedprefixes_baselineAverage: number;
  advertisedprefixes_peakObserved: number;
  advertisedprefixes_standardDeviation: number;
  advertisedprefixes_rawHexSample: string;
  advertisedprefixes_metadataTag: Record<string, string>;
  withdrawnprefixes_primaryMetric: number;
  withdrawnprefixes_secondaryMetric: number;
  withdrawnprefixes_baselineAverage: number;
  withdrawnprefixes_peakObserved: number;
  withdrawnprefixes_standardDeviation: number;
  withdrawnprefixes_rawHexSample: string;
  withdrawnprefixes_metadataTag: Record<string, string>;
  flapcount_primaryMetric: number;
  flapcount_secondaryMetric: number;
  flapcount_baselineAverage: number;
  flapcount_peakObserved: number;
  flapcount_standardDeviation: number;
  flapcount_rawHexSample: string;
  flapcount_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Bgp4RoutingTelemetryFilterV7 = Partial<Bgp4RoutingTelemetryRecordV7> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Bgp4RoutingTelemetryRecordV8 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  peeras_primaryMetric: number;
  peeras_secondaryMetric: number;
  peeras_baselineAverage: number;
  peeras_peakObserved: number;
  peeras_standardDeviation: number;
  peeras_rawHexSample: string;
  peeras_metadataTag: Record<string, string>;
  localas_primaryMetric: number;
  localas_secondaryMetric: number;
  localas_baselineAverage: number;
  localas_peakObserved: number;
  localas_standardDeviation: number;
  localas_rawHexSample: string;
  localas_metadataTag: Record<string, string>;
  peerrouterid_primaryMetric: number;
  peerrouterid_secondaryMetric: number;
  peerrouterid_baselineAverage: number;
  peerrouterid_peakObserved: number;
  peerrouterid_standardDeviation: number;
  peerrouterid_rawHexSample: string;
  peerrouterid_metadataTag: Record<string, string>;
  bgpstate_primaryMetric: number;
  bgpstate_secondaryMetric: number;
  bgpstate_baselineAverage: number;
  bgpstate_peakObserved: number;
  bgpstate_standardDeviation: number;
  bgpstate_rawHexSample: string;
  bgpstate_metadataTag: Record<string, string>;
  advertisedprefixes_primaryMetric: number;
  advertisedprefixes_secondaryMetric: number;
  advertisedprefixes_baselineAverage: number;
  advertisedprefixes_peakObserved: number;
  advertisedprefixes_standardDeviation: number;
  advertisedprefixes_rawHexSample: string;
  advertisedprefixes_metadataTag: Record<string, string>;
  withdrawnprefixes_primaryMetric: number;
  withdrawnprefixes_secondaryMetric: number;
  withdrawnprefixes_baselineAverage: number;
  withdrawnprefixes_peakObserved: number;
  withdrawnprefixes_standardDeviation: number;
  withdrawnprefixes_rawHexSample: string;
  withdrawnprefixes_metadataTag: Record<string, string>;
  flapcount_primaryMetric: number;
  flapcount_secondaryMetric: number;
  flapcount_baselineAverage: number;
  flapcount_peakObserved: number;
  flapcount_standardDeviation: number;
  flapcount_rawHexSample: string;
  flapcount_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Bgp4RoutingTelemetryFilterV8 = Partial<Bgp4RoutingTelemetryRecordV8> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Bgp4RoutingTelemetryRecordV9 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  peeras_primaryMetric: number;
  peeras_secondaryMetric: number;
  peeras_baselineAverage: number;
  peeras_peakObserved: number;
  peeras_standardDeviation: number;
  peeras_rawHexSample: string;
  peeras_metadataTag: Record<string, string>;
  localas_primaryMetric: number;
  localas_secondaryMetric: number;
  localas_baselineAverage: number;
  localas_peakObserved: number;
  localas_standardDeviation: number;
  localas_rawHexSample: string;
  localas_metadataTag: Record<string, string>;
  peerrouterid_primaryMetric: number;
  peerrouterid_secondaryMetric: number;
  peerrouterid_baselineAverage: number;
  peerrouterid_peakObserved: number;
  peerrouterid_standardDeviation: number;
  peerrouterid_rawHexSample: string;
  peerrouterid_metadataTag: Record<string, string>;
  bgpstate_primaryMetric: number;
  bgpstate_secondaryMetric: number;
  bgpstate_baselineAverage: number;
  bgpstate_peakObserved: number;
  bgpstate_standardDeviation: number;
  bgpstate_rawHexSample: string;
  bgpstate_metadataTag: Record<string, string>;
  advertisedprefixes_primaryMetric: number;
  advertisedprefixes_secondaryMetric: number;
  advertisedprefixes_baselineAverage: number;
  advertisedprefixes_peakObserved: number;
  advertisedprefixes_standardDeviation: number;
  advertisedprefixes_rawHexSample: string;
  advertisedprefixes_metadataTag: Record<string, string>;
  withdrawnprefixes_primaryMetric: number;
  withdrawnprefixes_secondaryMetric: number;
  withdrawnprefixes_baselineAverage: number;
  withdrawnprefixes_peakObserved: number;
  withdrawnprefixes_standardDeviation: number;
  withdrawnprefixes_rawHexSample: string;
  withdrawnprefixes_metadataTag: Record<string, string>;
  flapcount_primaryMetric: number;
  flapcount_secondaryMetric: number;
  flapcount_baselineAverage: number;
  flapcount_peakObserved: number;
  flapcount_standardDeviation: number;
  flapcount_rawHexSample: string;
  flapcount_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Bgp4RoutingTelemetryFilterV9 = Partial<Bgp4RoutingTelemetryRecordV9> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Bgp4RoutingTelemetryRecordV10 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  peeras_primaryMetric: number;
  peeras_secondaryMetric: number;
  peeras_baselineAverage: number;
  peeras_peakObserved: number;
  peeras_standardDeviation: number;
  peeras_rawHexSample: string;
  peeras_metadataTag: Record<string, string>;
  localas_primaryMetric: number;
  localas_secondaryMetric: number;
  localas_baselineAverage: number;
  localas_peakObserved: number;
  localas_standardDeviation: number;
  localas_rawHexSample: string;
  localas_metadataTag: Record<string, string>;
  peerrouterid_primaryMetric: number;
  peerrouterid_secondaryMetric: number;
  peerrouterid_baselineAverage: number;
  peerrouterid_peakObserved: number;
  peerrouterid_standardDeviation: number;
  peerrouterid_rawHexSample: string;
  peerrouterid_metadataTag: Record<string, string>;
  bgpstate_primaryMetric: number;
  bgpstate_secondaryMetric: number;
  bgpstate_baselineAverage: number;
  bgpstate_peakObserved: number;
  bgpstate_standardDeviation: number;
  bgpstate_rawHexSample: string;
  bgpstate_metadataTag: Record<string, string>;
  advertisedprefixes_primaryMetric: number;
  advertisedprefixes_secondaryMetric: number;
  advertisedprefixes_baselineAverage: number;
  advertisedprefixes_peakObserved: number;
  advertisedprefixes_standardDeviation: number;
  advertisedprefixes_rawHexSample: string;
  advertisedprefixes_metadataTag: Record<string, string>;
  withdrawnprefixes_primaryMetric: number;
  withdrawnprefixes_secondaryMetric: number;
  withdrawnprefixes_baselineAverage: number;
  withdrawnprefixes_peakObserved: number;
  withdrawnprefixes_standardDeviation: number;
  withdrawnprefixes_rawHexSample: string;
  withdrawnprefixes_metadataTag: Record<string, string>;
  flapcount_primaryMetric: number;
  flapcount_secondaryMetric: number;
  flapcount_baselineAverage: number;
  flapcount_peakObserved: number;
  flapcount_standardDeviation: number;
  flapcount_rawHexSample: string;
  flapcount_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Bgp4RoutingTelemetryFilterV10 = Partial<Bgp4RoutingTelemetryRecordV10> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Bgp4RoutingTelemetryRecordV11 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  peeras_primaryMetric: number;
  peeras_secondaryMetric: number;
  peeras_baselineAverage: number;
  peeras_peakObserved: number;
  peeras_standardDeviation: number;
  peeras_rawHexSample: string;
  peeras_metadataTag: Record<string, string>;
  localas_primaryMetric: number;
  localas_secondaryMetric: number;
  localas_baselineAverage: number;
  localas_peakObserved: number;
  localas_standardDeviation: number;
  localas_rawHexSample: string;
  localas_metadataTag: Record<string, string>;
  peerrouterid_primaryMetric: number;
  peerrouterid_secondaryMetric: number;
  peerrouterid_baselineAverage: number;
  peerrouterid_peakObserved: number;
  peerrouterid_standardDeviation: number;
  peerrouterid_rawHexSample: string;
  peerrouterid_metadataTag: Record<string, string>;
  bgpstate_primaryMetric: number;
  bgpstate_secondaryMetric: number;
  bgpstate_baselineAverage: number;
  bgpstate_peakObserved: number;
  bgpstate_standardDeviation: number;
  bgpstate_rawHexSample: string;
  bgpstate_metadataTag: Record<string, string>;
  advertisedprefixes_primaryMetric: number;
  advertisedprefixes_secondaryMetric: number;
  advertisedprefixes_baselineAverage: number;
  advertisedprefixes_peakObserved: number;
  advertisedprefixes_standardDeviation: number;
  advertisedprefixes_rawHexSample: string;
  advertisedprefixes_metadataTag: Record<string, string>;
  withdrawnprefixes_primaryMetric: number;
  withdrawnprefixes_secondaryMetric: number;
  withdrawnprefixes_baselineAverage: number;
  withdrawnprefixes_peakObserved: number;
  withdrawnprefixes_standardDeviation: number;
  withdrawnprefixes_rawHexSample: string;
  withdrawnprefixes_metadataTag: Record<string, string>;
  flapcount_primaryMetric: number;
  flapcount_secondaryMetric: number;
  flapcount_baselineAverage: number;
  flapcount_peakObserved: number;
  flapcount_standardDeviation: number;
  flapcount_rawHexSample: string;
  flapcount_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Bgp4RoutingTelemetryFilterV11 = Partial<Bgp4RoutingTelemetryRecordV11> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Bgp4RoutingTelemetryRecordV12 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  peeras_primaryMetric: number;
  peeras_secondaryMetric: number;
  peeras_baselineAverage: number;
  peeras_peakObserved: number;
  peeras_standardDeviation: number;
  peeras_rawHexSample: string;
  peeras_metadataTag: Record<string, string>;
  localas_primaryMetric: number;
  localas_secondaryMetric: number;
  localas_baselineAverage: number;
  localas_peakObserved: number;
  localas_standardDeviation: number;
  localas_rawHexSample: string;
  localas_metadataTag: Record<string, string>;
  peerrouterid_primaryMetric: number;
  peerrouterid_secondaryMetric: number;
  peerrouterid_baselineAverage: number;
  peerrouterid_peakObserved: number;
  peerrouterid_standardDeviation: number;
  peerrouterid_rawHexSample: string;
  peerrouterid_metadataTag: Record<string, string>;
  bgpstate_primaryMetric: number;
  bgpstate_secondaryMetric: number;
  bgpstate_baselineAverage: number;
  bgpstate_peakObserved: number;
  bgpstate_standardDeviation: number;
  bgpstate_rawHexSample: string;
  bgpstate_metadataTag: Record<string, string>;
  advertisedprefixes_primaryMetric: number;
  advertisedprefixes_secondaryMetric: number;
  advertisedprefixes_baselineAverage: number;
  advertisedprefixes_peakObserved: number;
  advertisedprefixes_standardDeviation: number;
  advertisedprefixes_rawHexSample: string;
  advertisedprefixes_metadataTag: Record<string, string>;
  withdrawnprefixes_primaryMetric: number;
  withdrawnprefixes_secondaryMetric: number;
  withdrawnprefixes_baselineAverage: number;
  withdrawnprefixes_peakObserved: number;
  withdrawnprefixes_standardDeviation: number;
  withdrawnprefixes_rawHexSample: string;
  withdrawnprefixes_metadataTag: Record<string, string>;
  flapcount_primaryMetric: number;
  flapcount_secondaryMetric: number;
  flapcount_baselineAverage: number;
  flapcount_peakObserved: number;
  flapcount_standardDeviation: number;
  flapcount_rawHexSample: string;
  flapcount_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Bgp4RoutingTelemetryFilterV12 = Partial<Bgp4RoutingTelemetryRecordV12> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Bgp4RoutingTelemetryRecordV13 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  peeras_primaryMetric: number;
  peeras_secondaryMetric: number;
  peeras_baselineAverage: number;
  peeras_peakObserved: number;
  peeras_standardDeviation: number;
  peeras_rawHexSample: string;
  peeras_metadataTag: Record<string, string>;
  localas_primaryMetric: number;
  localas_secondaryMetric: number;
  localas_baselineAverage: number;
  localas_peakObserved: number;
  localas_standardDeviation: number;
  localas_rawHexSample: string;
  localas_metadataTag: Record<string, string>;
  peerrouterid_primaryMetric: number;
  peerrouterid_secondaryMetric: number;
  peerrouterid_baselineAverage: number;
  peerrouterid_peakObserved: number;
  peerrouterid_standardDeviation: number;
  peerrouterid_rawHexSample: string;
  peerrouterid_metadataTag: Record<string, string>;
  bgpstate_primaryMetric: number;
  bgpstate_secondaryMetric: number;
  bgpstate_baselineAverage: number;
  bgpstate_peakObserved: number;
  bgpstate_standardDeviation: number;
  bgpstate_rawHexSample: string;
  bgpstate_metadataTag: Record<string, string>;
  advertisedprefixes_primaryMetric: number;
  advertisedprefixes_secondaryMetric: number;
  advertisedprefixes_baselineAverage: number;
  advertisedprefixes_peakObserved: number;
  advertisedprefixes_standardDeviation: number;
  advertisedprefixes_rawHexSample: string;
  advertisedprefixes_metadataTag: Record<string, string>;
  withdrawnprefixes_primaryMetric: number;
  withdrawnprefixes_secondaryMetric: number;
  withdrawnprefixes_baselineAverage: number;
  withdrawnprefixes_peakObserved: number;
  withdrawnprefixes_standardDeviation: number;
  withdrawnprefixes_rawHexSample: string;
  withdrawnprefixes_metadataTag: Record<string, string>;
  flapcount_primaryMetric: number;
  flapcount_secondaryMetric: number;
  flapcount_baselineAverage: number;
  flapcount_peakObserved: number;
  flapcount_standardDeviation: number;
  flapcount_rawHexSample: string;
  flapcount_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Bgp4RoutingTelemetryFilterV13 = Partial<Bgp4RoutingTelemetryRecordV13> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Bgp4RoutingTelemetryRecordV14 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  peeras_primaryMetric: number;
  peeras_secondaryMetric: number;
  peeras_baselineAverage: number;
  peeras_peakObserved: number;
  peeras_standardDeviation: number;
  peeras_rawHexSample: string;
  peeras_metadataTag: Record<string, string>;
  localas_primaryMetric: number;
  localas_secondaryMetric: number;
  localas_baselineAverage: number;
  localas_peakObserved: number;
  localas_standardDeviation: number;
  localas_rawHexSample: string;
  localas_metadataTag: Record<string, string>;
  peerrouterid_primaryMetric: number;
  peerrouterid_secondaryMetric: number;
  peerrouterid_baselineAverage: number;
  peerrouterid_peakObserved: number;
  peerrouterid_standardDeviation: number;
  peerrouterid_rawHexSample: string;
  peerrouterid_metadataTag: Record<string, string>;
  bgpstate_primaryMetric: number;
  bgpstate_secondaryMetric: number;
  bgpstate_baselineAverage: number;
  bgpstate_peakObserved: number;
  bgpstate_standardDeviation: number;
  bgpstate_rawHexSample: string;
  bgpstate_metadataTag: Record<string, string>;
  advertisedprefixes_primaryMetric: number;
  advertisedprefixes_secondaryMetric: number;
  advertisedprefixes_baselineAverage: number;
  advertisedprefixes_peakObserved: number;
  advertisedprefixes_standardDeviation: number;
  advertisedprefixes_rawHexSample: string;
  advertisedprefixes_metadataTag: Record<string, string>;
  withdrawnprefixes_primaryMetric: number;
  withdrawnprefixes_secondaryMetric: number;
  withdrawnprefixes_baselineAverage: number;
  withdrawnprefixes_peakObserved: number;
  withdrawnprefixes_standardDeviation: number;
  withdrawnprefixes_rawHexSample: string;
  withdrawnprefixes_metadataTag: Record<string, string>;
  flapcount_primaryMetric: number;
  flapcount_secondaryMetric: number;
  flapcount_baselineAverage: number;
  flapcount_peakObserved: number;
  flapcount_standardDeviation: number;
  flapcount_rawHexSample: string;
  flapcount_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Bgp4RoutingTelemetryFilterV14 = Partial<Bgp4RoutingTelemetryRecordV14> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Bgp4RoutingTelemetryRecordV15 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  peeras_primaryMetric: number;
  peeras_secondaryMetric: number;
  peeras_baselineAverage: number;
  peeras_peakObserved: number;
  peeras_standardDeviation: number;
  peeras_rawHexSample: string;
  peeras_metadataTag: Record<string, string>;
  localas_primaryMetric: number;
  localas_secondaryMetric: number;
  localas_baselineAverage: number;
  localas_peakObserved: number;
  localas_standardDeviation: number;
  localas_rawHexSample: string;
  localas_metadataTag: Record<string, string>;
  peerrouterid_primaryMetric: number;
  peerrouterid_secondaryMetric: number;
  peerrouterid_baselineAverage: number;
  peerrouterid_peakObserved: number;
  peerrouterid_standardDeviation: number;
  peerrouterid_rawHexSample: string;
  peerrouterid_metadataTag: Record<string, string>;
  bgpstate_primaryMetric: number;
  bgpstate_secondaryMetric: number;
  bgpstate_baselineAverage: number;
  bgpstate_peakObserved: number;
  bgpstate_standardDeviation: number;
  bgpstate_rawHexSample: string;
  bgpstate_metadataTag: Record<string, string>;
  advertisedprefixes_primaryMetric: number;
  advertisedprefixes_secondaryMetric: number;
  advertisedprefixes_baselineAverage: number;
  advertisedprefixes_peakObserved: number;
  advertisedprefixes_standardDeviation: number;
  advertisedprefixes_rawHexSample: string;
  advertisedprefixes_metadataTag: Record<string, string>;
  withdrawnprefixes_primaryMetric: number;
  withdrawnprefixes_secondaryMetric: number;
  withdrawnprefixes_baselineAverage: number;
  withdrawnprefixes_peakObserved: number;
  withdrawnprefixes_standardDeviation: number;
  withdrawnprefixes_rawHexSample: string;
  withdrawnprefixes_metadataTag: Record<string, string>;
  flapcount_primaryMetric: number;
  flapcount_secondaryMetric: number;
  flapcount_baselineAverage: number;
  flapcount_peakObserved: number;
  flapcount_standardDeviation: number;
  flapcount_rawHexSample: string;
  flapcount_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Bgp4RoutingTelemetryFilterV15 = Partial<Bgp4RoutingTelemetryRecordV15> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Bgp4RoutingTelemetryRecordV16 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  peeras_primaryMetric: number;
  peeras_secondaryMetric: number;
  peeras_baselineAverage: number;
  peeras_peakObserved: number;
  peeras_standardDeviation: number;
  peeras_rawHexSample: string;
  peeras_metadataTag: Record<string, string>;
  localas_primaryMetric: number;
  localas_secondaryMetric: number;
  localas_baselineAverage: number;
  localas_peakObserved: number;
  localas_standardDeviation: number;
  localas_rawHexSample: string;
  localas_metadataTag: Record<string, string>;
  peerrouterid_primaryMetric: number;
  peerrouterid_secondaryMetric: number;
  peerrouterid_baselineAverage: number;
  peerrouterid_peakObserved: number;
  peerrouterid_standardDeviation: number;
  peerrouterid_rawHexSample: string;
  peerrouterid_metadataTag: Record<string, string>;
  bgpstate_primaryMetric: number;
  bgpstate_secondaryMetric: number;
  bgpstate_baselineAverage: number;
  bgpstate_peakObserved: number;
  bgpstate_standardDeviation: number;
  bgpstate_rawHexSample: string;
  bgpstate_metadataTag: Record<string, string>;
  advertisedprefixes_primaryMetric: number;
  advertisedprefixes_secondaryMetric: number;
  advertisedprefixes_baselineAverage: number;
  advertisedprefixes_peakObserved: number;
  advertisedprefixes_standardDeviation: number;
  advertisedprefixes_rawHexSample: string;
  advertisedprefixes_metadataTag: Record<string, string>;
  withdrawnprefixes_primaryMetric: number;
  withdrawnprefixes_secondaryMetric: number;
  withdrawnprefixes_baselineAverage: number;
  withdrawnprefixes_peakObserved: number;
  withdrawnprefixes_standardDeviation: number;
  withdrawnprefixes_rawHexSample: string;
  withdrawnprefixes_metadataTag: Record<string, string>;
  flapcount_primaryMetric: number;
  flapcount_secondaryMetric: number;
  flapcount_baselineAverage: number;
  flapcount_peakObserved: number;
  flapcount_standardDeviation: number;
  flapcount_rawHexSample: string;
  flapcount_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Bgp4RoutingTelemetryFilterV16 = Partial<Bgp4RoutingTelemetryRecordV16> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Bgp4RoutingTelemetryRecordV17 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  peeras_primaryMetric: number;
  peeras_secondaryMetric: number;
  peeras_baselineAverage: number;
  peeras_peakObserved: number;
  peeras_standardDeviation: number;
  peeras_rawHexSample: string;
  peeras_metadataTag: Record<string, string>;
  localas_primaryMetric: number;
  localas_secondaryMetric: number;
  localas_baselineAverage: number;
  localas_peakObserved: number;
  localas_standardDeviation: number;
  localas_rawHexSample: string;
  localas_metadataTag: Record<string, string>;
  peerrouterid_primaryMetric: number;
  peerrouterid_secondaryMetric: number;
  peerrouterid_baselineAverage: number;
  peerrouterid_peakObserved: number;
  peerrouterid_standardDeviation: number;
  peerrouterid_rawHexSample: string;
  peerrouterid_metadataTag: Record<string, string>;
  bgpstate_primaryMetric: number;
  bgpstate_secondaryMetric: number;
  bgpstate_baselineAverage: number;
  bgpstate_peakObserved: number;
  bgpstate_standardDeviation: number;
  bgpstate_rawHexSample: string;
  bgpstate_metadataTag: Record<string, string>;
  advertisedprefixes_primaryMetric: number;
  advertisedprefixes_secondaryMetric: number;
  advertisedprefixes_baselineAverage: number;
  advertisedprefixes_peakObserved: number;
  advertisedprefixes_standardDeviation: number;
  advertisedprefixes_rawHexSample: string;
  advertisedprefixes_metadataTag: Record<string, string>;
  withdrawnprefixes_primaryMetric: number;
  withdrawnprefixes_secondaryMetric: number;
  withdrawnprefixes_baselineAverage: number;
  withdrawnprefixes_peakObserved: number;
  withdrawnprefixes_standardDeviation: number;
  withdrawnprefixes_rawHexSample: string;
  withdrawnprefixes_metadataTag: Record<string, string>;
  flapcount_primaryMetric: number;
  flapcount_secondaryMetric: number;
  flapcount_baselineAverage: number;
  flapcount_peakObserved: number;
  flapcount_standardDeviation: number;
  flapcount_rawHexSample: string;
  flapcount_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Bgp4RoutingTelemetryFilterV17 = Partial<Bgp4RoutingTelemetryRecordV17> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Bgp4RoutingTelemetryRecordV18 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  peeras_primaryMetric: number;
  peeras_secondaryMetric: number;
  peeras_baselineAverage: number;
  peeras_peakObserved: number;
  peeras_standardDeviation: number;
  peeras_rawHexSample: string;
  peeras_metadataTag: Record<string, string>;
  localas_primaryMetric: number;
  localas_secondaryMetric: number;
  localas_baselineAverage: number;
  localas_peakObserved: number;
  localas_standardDeviation: number;
  localas_rawHexSample: string;
  localas_metadataTag: Record<string, string>;
  peerrouterid_primaryMetric: number;
  peerrouterid_secondaryMetric: number;
  peerrouterid_baselineAverage: number;
  peerrouterid_peakObserved: number;
  peerrouterid_standardDeviation: number;
  peerrouterid_rawHexSample: string;
  peerrouterid_metadataTag: Record<string, string>;
  bgpstate_primaryMetric: number;
  bgpstate_secondaryMetric: number;
  bgpstate_baselineAverage: number;
  bgpstate_peakObserved: number;
  bgpstate_standardDeviation: number;
  bgpstate_rawHexSample: string;
  bgpstate_metadataTag: Record<string, string>;
  advertisedprefixes_primaryMetric: number;
  advertisedprefixes_secondaryMetric: number;
  advertisedprefixes_baselineAverage: number;
  advertisedprefixes_peakObserved: number;
  advertisedprefixes_standardDeviation: number;
  advertisedprefixes_rawHexSample: string;
  advertisedprefixes_metadataTag: Record<string, string>;
  withdrawnprefixes_primaryMetric: number;
  withdrawnprefixes_secondaryMetric: number;
  withdrawnprefixes_baselineAverage: number;
  withdrawnprefixes_peakObserved: number;
  withdrawnprefixes_standardDeviation: number;
  withdrawnprefixes_rawHexSample: string;
  withdrawnprefixes_metadataTag: Record<string, string>;
  flapcount_primaryMetric: number;
  flapcount_secondaryMetric: number;
  flapcount_baselineAverage: number;
  flapcount_peakObserved: number;
  flapcount_standardDeviation: number;
  flapcount_rawHexSample: string;
  flapcount_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Bgp4RoutingTelemetryFilterV18 = Partial<Bgp4RoutingTelemetryRecordV18> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Bgp4RoutingTelemetryRecordV19 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  peeras_primaryMetric: number;
  peeras_secondaryMetric: number;
  peeras_baselineAverage: number;
  peeras_peakObserved: number;
  peeras_standardDeviation: number;
  peeras_rawHexSample: string;
  peeras_metadataTag: Record<string, string>;
  localas_primaryMetric: number;
  localas_secondaryMetric: number;
  localas_baselineAverage: number;
  localas_peakObserved: number;
  localas_standardDeviation: number;
  localas_rawHexSample: string;
  localas_metadataTag: Record<string, string>;
  peerrouterid_primaryMetric: number;
  peerrouterid_secondaryMetric: number;
  peerrouterid_baselineAverage: number;
  peerrouterid_peakObserved: number;
  peerrouterid_standardDeviation: number;
  peerrouterid_rawHexSample: string;
  peerrouterid_metadataTag: Record<string, string>;
  bgpstate_primaryMetric: number;
  bgpstate_secondaryMetric: number;
  bgpstate_baselineAverage: number;
  bgpstate_peakObserved: number;
  bgpstate_standardDeviation: number;
  bgpstate_rawHexSample: string;
  bgpstate_metadataTag: Record<string, string>;
  advertisedprefixes_primaryMetric: number;
  advertisedprefixes_secondaryMetric: number;
  advertisedprefixes_baselineAverage: number;
  advertisedprefixes_peakObserved: number;
  advertisedprefixes_standardDeviation: number;
  advertisedprefixes_rawHexSample: string;
  advertisedprefixes_metadataTag: Record<string, string>;
  withdrawnprefixes_primaryMetric: number;
  withdrawnprefixes_secondaryMetric: number;
  withdrawnprefixes_baselineAverage: number;
  withdrawnprefixes_peakObserved: number;
  withdrawnprefixes_standardDeviation: number;
  withdrawnprefixes_rawHexSample: string;
  withdrawnprefixes_metadataTag: Record<string, string>;
  flapcount_primaryMetric: number;
  flapcount_secondaryMetric: number;
  flapcount_baselineAverage: number;
  flapcount_peakObserved: number;
  flapcount_standardDeviation: number;
  flapcount_rawHexSample: string;
  flapcount_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Bgp4RoutingTelemetryFilterV19 = Partial<Bgp4RoutingTelemetryRecordV19> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Bgp4RoutingTelemetryRecordV20 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  peeras_primaryMetric: number;
  peeras_secondaryMetric: number;
  peeras_baselineAverage: number;
  peeras_peakObserved: number;
  peeras_standardDeviation: number;
  peeras_rawHexSample: string;
  peeras_metadataTag: Record<string, string>;
  localas_primaryMetric: number;
  localas_secondaryMetric: number;
  localas_baselineAverage: number;
  localas_peakObserved: number;
  localas_standardDeviation: number;
  localas_rawHexSample: string;
  localas_metadataTag: Record<string, string>;
  peerrouterid_primaryMetric: number;
  peerrouterid_secondaryMetric: number;
  peerrouterid_baselineAverage: number;
  peerrouterid_peakObserved: number;
  peerrouterid_standardDeviation: number;
  peerrouterid_rawHexSample: string;
  peerrouterid_metadataTag: Record<string, string>;
  bgpstate_primaryMetric: number;
  bgpstate_secondaryMetric: number;
  bgpstate_baselineAverage: number;
  bgpstate_peakObserved: number;
  bgpstate_standardDeviation: number;
  bgpstate_rawHexSample: string;
  bgpstate_metadataTag: Record<string, string>;
  advertisedprefixes_primaryMetric: number;
  advertisedprefixes_secondaryMetric: number;
  advertisedprefixes_baselineAverage: number;
  advertisedprefixes_peakObserved: number;
  advertisedprefixes_standardDeviation: number;
  advertisedprefixes_rawHexSample: string;
  advertisedprefixes_metadataTag: Record<string, string>;
  withdrawnprefixes_primaryMetric: number;
  withdrawnprefixes_secondaryMetric: number;
  withdrawnprefixes_baselineAverage: number;
  withdrawnprefixes_peakObserved: number;
  withdrawnprefixes_standardDeviation: number;
  withdrawnprefixes_rawHexSample: string;
  withdrawnprefixes_metadataTag: Record<string, string>;
  flapcount_primaryMetric: number;
  flapcount_secondaryMetric: number;
  flapcount_baselineAverage: number;
  flapcount_peakObserved: number;
  flapcount_standardDeviation: number;
  flapcount_rawHexSample: string;
  flapcount_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Bgp4RoutingTelemetryFilterV20 = Partial<Bgp4RoutingTelemetryRecordV20> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Bgp4RoutingTelemetryRecordV21 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  peeras_primaryMetric: number;
  peeras_secondaryMetric: number;
  peeras_baselineAverage: number;
  peeras_peakObserved: number;
  peeras_standardDeviation: number;
  peeras_rawHexSample: string;
  peeras_metadataTag: Record<string, string>;
  localas_primaryMetric: number;
  localas_secondaryMetric: number;
  localas_baselineAverage: number;
  localas_peakObserved: number;
  localas_standardDeviation: number;
  localas_rawHexSample: string;
  localas_metadataTag: Record<string, string>;
  peerrouterid_primaryMetric: number;
  peerrouterid_secondaryMetric: number;
  peerrouterid_baselineAverage: number;
  peerrouterid_peakObserved: number;
  peerrouterid_standardDeviation: number;
  peerrouterid_rawHexSample: string;
  peerrouterid_metadataTag: Record<string, string>;
  bgpstate_primaryMetric: number;
  bgpstate_secondaryMetric: number;
  bgpstate_baselineAverage: number;
  bgpstate_peakObserved: number;
  bgpstate_standardDeviation: number;
  bgpstate_rawHexSample: string;
  bgpstate_metadataTag: Record<string, string>;
  advertisedprefixes_primaryMetric: number;
  advertisedprefixes_secondaryMetric: number;
  advertisedprefixes_baselineAverage: number;
  advertisedprefixes_peakObserved: number;
  advertisedprefixes_standardDeviation: number;
  advertisedprefixes_rawHexSample: string;
  advertisedprefixes_metadataTag: Record<string, string>;
  withdrawnprefixes_primaryMetric: number;
  withdrawnprefixes_secondaryMetric: number;
  withdrawnprefixes_baselineAverage: number;
  withdrawnprefixes_peakObserved: number;
  withdrawnprefixes_standardDeviation: number;
  withdrawnprefixes_rawHexSample: string;
  withdrawnprefixes_metadataTag: Record<string, string>;
  flapcount_primaryMetric: number;
  flapcount_secondaryMetric: number;
  flapcount_baselineAverage: number;
  flapcount_peakObserved: number;
  flapcount_standardDeviation: number;
  flapcount_rawHexSample: string;
  flapcount_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Bgp4RoutingTelemetryFilterV21 = Partial<Bgp4RoutingTelemetryRecordV21> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Bgp4RoutingTelemetryRecordV22 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  peeras_primaryMetric: number;
  peeras_secondaryMetric: number;
  peeras_baselineAverage: number;
  peeras_peakObserved: number;
  peeras_standardDeviation: number;
  peeras_rawHexSample: string;
  peeras_metadataTag: Record<string, string>;
  localas_primaryMetric: number;
  localas_secondaryMetric: number;
  localas_baselineAverage: number;
  localas_peakObserved: number;
  localas_standardDeviation: number;
  localas_rawHexSample: string;
  localas_metadataTag: Record<string, string>;
  peerrouterid_primaryMetric: number;
  peerrouterid_secondaryMetric: number;
  peerrouterid_baselineAverage: number;
  peerrouterid_peakObserved: number;
  peerrouterid_standardDeviation: number;
  peerrouterid_rawHexSample: string;
  peerrouterid_metadataTag: Record<string, string>;
  bgpstate_primaryMetric: number;
  bgpstate_secondaryMetric: number;
  bgpstate_baselineAverage: number;
  bgpstate_peakObserved: number;
  bgpstate_standardDeviation: number;
  bgpstate_rawHexSample: string;
  bgpstate_metadataTag: Record<string, string>;
  advertisedprefixes_primaryMetric: number;
  advertisedprefixes_secondaryMetric: number;
  advertisedprefixes_baselineAverage: number;
  advertisedprefixes_peakObserved: number;
  advertisedprefixes_standardDeviation: number;
  advertisedprefixes_rawHexSample: string;
  advertisedprefixes_metadataTag: Record<string, string>;
  withdrawnprefixes_primaryMetric: number;
  withdrawnprefixes_secondaryMetric: number;
  withdrawnprefixes_baselineAverage: number;
  withdrawnprefixes_peakObserved: number;
  withdrawnprefixes_standardDeviation: number;
  withdrawnprefixes_rawHexSample: string;
  withdrawnprefixes_metadataTag: Record<string, string>;
  flapcount_primaryMetric: number;
  flapcount_secondaryMetric: number;
  flapcount_baselineAverage: number;
  flapcount_peakObserved: number;
  flapcount_standardDeviation: number;
  flapcount_rawHexSample: string;
  flapcount_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Bgp4RoutingTelemetryFilterV22 = Partial<Bgp4RoutingTelemetryRecordV22> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Bgp4RoutingTelemetryRecordV23 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  peeras_primaryMetric: number;
  peeras_secondaryMetric: number;
  peeras_baselineAverage: number;
  peeras_peakObserved: number;
  peeras_standardDeviation: number;
  peeras_rawHexSample: string;
  peeras_metadataTag: Record<string, string>;
  localas_primaryMetric: number;
  localas_secondaryMetric: number;
  localas_baselineAverage: number;
  localas_peakObserved: number;
  localas_standardDeviation: number;
  localas_rawHexSample: string;
  localas_metadataTag: Record<string, string>;
  peerrouterid_primaryMetric: number;
  peerrouterid_secondaryMetric: number;
  peerrouterid_baselineAverage: number;
  peerrouterid_peakObserved: number;
  peerrouterid_standardDeviation: number;
  peerrouterid_rawHexSample: string;
  peerrouterid_metadataTag: Record<string, string>;
  bgpstate_primaryMetric: number;
  bgpstate_secondaryMetric: number;
  bgpstate_baselineAverage: number;
  bgpstate_peakObserved: number;
  bgpstate_standardDeviation: number;
  bgpstate_rawHexSample: string;
  bgpstate_metadataTag: Record<string, string>;
  advertisedprefixes_primaryMetric: number;
  advertisedprefixes_secondaryMetric: number;
  advertisedprefixes_baselineAverage: number;
  advertisedprefixes_peakObserved: number;
  advertisedprefixes_standardDeviation: number;
  advertisedprefixes_rawHexSample: string;
  advertisedprefixes_metadataTag: Record<string, string>;
  withdrawnprefixes_primaryMetric: number;
  withdrawnprefixes_secondaryMetric: number;
  withdrawnprefixes_baselineAverage: number;
  withdrawnprefixes_peakObserved: number;
  withdrawnprefixes_standardDeviation: number;
  withdrawnprefixes_rawHexSample: string;
  withdrawnprefixes_metadataTag: Record<string, string>;
  flapcount_primaryMetric: number;
  flapcount_secondaryMetric: number;
  flapcount_baselineAverage: number;
  flapcount_peakObserved: number;
  flapcount_standardDeviation: number;
  flapcount_rawHexSample: string;
  flapcount_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Bgp4RoutingTelemetryFilterV23 = Partial<Bgp4RoutingTelemetryRecordV23> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Bgp4RoutingTelemetryRecordV24 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  peeras_primaryMetric: number;
  peeras_secondaryMetric: number;
  peeras_baselineAverage: number;
  peeras_peakObserved: number;
  peeras_standardDeviation: number;
  peeras_rawHexSample: string;
  peeras_metadataTag: Record<string, string>;
  localas_primaryMetric: number;
  localas_secondaryMetric: number;
  localas_baselineAverage: number;
  localas_peakObserved: number;
  localas_standardDeviation: number;
  localas_rawHexSample: string;
  localas_metadataTag: Record<string, string>;
  peerrouterid_primaryMetric: number;
  peerrouterid_secondaryMetric: number;
  peerrouterid_baselineAverage: number;
  peerrouterid_peakObserved: number;
  peerrouterid_standardDeviation: number;
  peerrouterid_rawHexSample: string;
  peerrouterid_metadataTag: Record<string, string>;
  bgpstate_primaryMetric: number;
  bgpstate_secondaryMetric: number;
  bgpstate_baselineAverage: number;
  bgpstate_peakObserved: number;
  bgpstate_standardDeviation: number;
  bgpstate_rawHexSample: string;
  bgpstate_metadataTag: Record<string, string>;
  advertisedprefixes_primaryMetric: number;
  advertisedprefixes_secondaryMetric: number;
  advertisedprefixes_baselineAverage: number;
  advertisedprefixes_peakObserved: number;
  advertisedprefixes_standardDeviation: number;
  advertisedprefixes_rawHexSample: string;
  advertisedprefixes_metadataTag: Record<string, string>;
  withdrawnprefixes_primaryMetric: number;
  withdrawnprefixes_secondaryMetric: number;
  withdrawnprefixes_baselineAverage: number;
  withdrawnprefixes_peakObserved: number;
  withdrawnprefixes_standardDeviation: number;
  withdrawnprefixes_rawHexSample: string;
  withdrawnprefixes_metadataTag: Record<string, string>;
  flapcount_primaryMetric: number;
  flapcount_secondaryMetric: number;
  flapcount_baselineAverage: number;
  flapcount_peakObserved: number;
  flapcount_standardDeviation: number;
  flapcount_rawHexSample: string;
  flapcount_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Bgp4RoutingTelemetryFilterV24 = Partial<Bgp4RoutingTelemetryRecordV24> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Bgp4RoutingTelemetryRecordV25 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  peeras_primaryMetric: number;
  peeras_secondaryMetric: number;
  peeras_baselineAverage: number;
  peeras_peakObserved: number;
  peeras_standardDeviation: number;
  peeras_rawHexSample: string;
  peeras_metadataTag: Record<string, string>;
  localas_primaryMetric: number;
  localas_secondaryMetric: number;
  localas_baselineAverage: number;
  localas_peakObserved: number;
  localas_standardDeviation: number;
  localas_rawHexSample: string;
  localas_metadataTag: Record<string, string>;
  peerrouterid_primaryMetric: number;
  peerrouterid_secondaryMetric: number;
  peerrouterid_baselineAverage: number;
  peerrouterid_peakObserved: number;
  peerrouterid_standardDeviation: number;
  peerrouterid_rawHexSample: string;
  peerrouterid_metadataTag: Record<string, string>;
  bgpstate_primaryMetric: number;
  bgpstate_secondaryMetric: number;
  bgpstate_baselineAverage: number;
  bgpstate_peakObserved: number;
  bgpstate_standardDeviation: number;
  bgpstate_rawHexSample: string;
  bgpstate_metadataTag: Record<string, string>;
  advertisedprefixes_primaryMetric: number;
  advertisedprefixes_secondaryMetric: number;
  advertisedprefixes_baselineAverage: number;
  advertisedprefixes_peakObserved: number;
  advertisedprefixes_standardDeviation: number;
  advertisedprefixes_rawHexSample: string;
  advertisedprefixes_metadataTag: Record<string, string>;
  withdrawnprefixes_primaryMetric: number;
  withdrawnprefixes_secondaryMetric: number;
  withdrawnprefixes_baselineAverage: number;
  withdrawnprefixes_peakObserved: number;
  withdrawnprefixes_standardDeviation: number;
  withdrawnprefixes_rawHexSample: string;
  withdrawnprefixes_metadataTag: Record<string, string>;
  flapcount_primaryMetric: number;
  flapcount_secondaryMetric: number;
  flapcount_baselineAverage: number;
  flapcount_peakObserved: number;
  flapcount_standardDeviation: number;
  flapcount_rawHexSample: string;
  flapcount_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Bgp4RoutingTelemetryFilterV25 = Partial<Bgp4RoutingTelemetryRecordV25> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Bgp4RoutingTelemetryRecordV26 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  peeras_primaryMetric: number;
  peeras_secondaryMetric: number;
  peeras_baselineAverage: number;
  peeras_peakObserved: number;
  peeras_standardDeviation: number;
  peeras_rawHexSample: string;
  peeras_metadataTag: Record<string, string>;
  localas_primaryMetric: number;
  localas_secondaryMetric: number;
  localas_baselineAverage: number;
  localas_peakObserved: number;
  localas_standardDeviation: number;
  localas_rawHexSample: string;
  localas_metadataTag: Record<string, string>;
  peerrouterid_primaryMetric: number;
  peerrouterid_secondaryMetric: number;
  peerrouterid_baselineAverage: number;
  peerrouterid_peakObserved: number;
  peerrouterid_standardDeviation: number;
  peerrouterid_rawHexSample: string;
  peerrouterid_metadataTag: Record<string, string>;
  bgpstate_primaryMetric: number;
  bgpstate_secondaryMetric: number;
  bgpstate_baselineAverage: number;
  bgpstate_peakObserved: number;
  bgpstate_standardDeviation: number;
  bgpstate_rawHexSample: string;
  bgpstate_metadataTag: Record<string, string>;
  advertisedprefixes_primaryMetric: number;
  advertisedprefixes_secondaryMetric: number;
  advertisedprefixes_baselineAverage: number;
  advertisedprefixes_peakObserved: number;
  advertisedprefixes_standardDeviation: number;
  advertisedprefixes_rawHexSample: string;
  advertisedprefixes_metadataTag: Record<string, string>;
  withdrawnprefixes_primaryMetric: number;
  withdrawnprefixes_secondaryMetric: number;
  withdrawnprefixes_baselineAverage: number;
  withdrawnprefixes_peakObserved: number;
  withdrawnprefixes_standardDeviation: number;
  withdrawnprefixes_rawHexSample: string;
  withdrawnprefixes_metadataTag: Record<string, string>;
  flapcount_primaryMetric: number;
  flapcount_secondaryMetric: number;
  flapcount_baselineAverage: number;
  flapcount_peakObserved: number;
  flapcount_standardDeviation: number;
  flapcount_rawHexSample: string;
  flapcount_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Bgp4RoutingTelemetryFilterV26 = Partial<Bgp4RoutingTelemetryRecordV26> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Bgp4RoutingTelemetryRecordV27 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  peeras_primaryMetric: number;
  peeras_secondaryMetric: number;
  peeras_baselineAverage: number;
  peeras_peakObserved: number;
  peeras_standardDeviation: number;
  peeras_rawHexSample: string;
  peeras_metadataTag: Record<string, string>;
  localas_primaryMetric: number;
  localas_secondaryMetric: number;
  localas_baselineAverage: number;
  localas_peakObserved: number;
  localas_standardDeviation: number;
  localas_rawHexSample: string;
  localas_metadataTag: Record<string, string>;
  peerrouterid_primaryMetric: number;
  peerrouterid_secondaryMetric: number;
  peerrouterid_baselineAverage: number;
  peerrouterid_peakObserved: number;
  peerrouterid_standardDeviation: number;
  peerrouterid_rawHexSample: string;
  peerrouterid_metadataTag: Record<string, string>;
  bgpstate_primaryMetric: number;
  bgpstate_secondaryMetric: number;
  bgpstate_baselineAverage: number;
  bgpstate_peakObserved: number;
  bgpstate_standardDeviation: number;
  bgpstate_rawHexSample: string;
  bgpstate_metadataTag: Record<string, string>;
  advertisedprefixes_primaryMetric: number;
  advertisedprefixes_secondaryMetric: number;
  advertisedprefixes_baselineAverage: number;
  advertisedprefixes_peakObserved: number;
  advertisedprefixes_standardDeviation: number;
  advertisedprefixes_rawHexSample: string;
  advertisedprefixes_metadataTag: Record<string, string>;
  withdrawnprefixes_primaryMetric: number;
  withdrawnprefixes_secondaryMetric: number;
  withdrawnprefixes_baselineAverage: number;
  withdrawnprefixes_peakObserved: number;
  withdrawnprefixes_standardDeviation: number;
  withdrawnprefixes_rawHexSample: string;
  withdrawnprefixes_metadataTag: Record<string, string>;
  flapcount_primaryMetric: number;
  flapcount_secondaryMetric: number;
  flapcount_baselineAverage: number;
  flapcount_peakObserved: number;
  flapcount_standardDeviation: number;
  flapcount_rawHexSample: string;
  flapcount_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Bgp4RoutingTelemetryFilterV27 = Partial<Bgp4RoutingTelemetryRecordV27> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Bgp4RoutingTelemetryRecordV28 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  peeras_primaryMetric: number;
  peeras_secondaryMetric: number;
  peeras_baselineAverage: number;
  peeras_peakObserved: number;
  peeras_standardDeviation: number;
  peeras_rawHexSample: string;
  peeras_metadataTag: Record<string, string>;
  localas_primaryMetric: number;
  localas_secondaryMetric: number;
  localas_baselineAverage: number;
  localas_peakObserved: number;
  localas_standardDeviation: number;
  localas_rawHexSample: string;
  localas_metadataTag: Record<string, string>;
  peerrouterid_primaryMetric: number;
  peerrouterid_secondaryMetric: number;
  peerrouterid_baselineAverage: number;
  peerrouterid_peakObserved: number;
  peerrouterid_standardDeviation: number;
  peerrouterid_rawHexSample: string;
  peerrouterid_metadataTag: Record<string, string>;
  bgpstate_primaryMetric: number;
  bgpstate_secondaryMetric: number;
  bgpstate_baselineAverage: number;
  bgpstate_peakObserved: number;
  bgpstate_standardDeviation: number;
  bgpstate_rawHexSample: string;
  bgpstate_metadataTag: Record<string, string>;
  advertisedprefixes_primaryMetric: number;
  advertisedprefixes_secondaryMetric: number;
  advertisedprefixes_baselineAverage: number;
  advertisedprefixes_peakObserved: number;
  advertisedprefixes_standardDeviation: number;
  advertisedprefixes_rawHexSample: string;
  advertisedprefixes_metadataTag: Record<string, string>;
  withdrawnprefixes_primaryMetric: number;
  withdrawnprefixes_secondaryMetric: number;
  withdrawnprefixes_baselineAverage: number;
  withdrawnprefixes_peakObserved: number;
  withdrawnprefixes_standardDeviation: number;
  withdrawnprefixes_rawHexSample: string;
  withdrawnprefixes_metadataTag: Record<string, string>;
  flapcount_primaryMetric: number;
  flapcount_secondaryMetric: number;
  flapcount_baselineAverage: number;
  flapcount_peakObserved: number;
  flapcount_standardDeviation: number;
  flapcount_rawHexSample: string;
  flapcount_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Bgp4RoutingTelemetryFilterV28 = Partial<Bgp4RoutingTelemetryRecordV28> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Bgp4RoutingTelemetryRecordV29 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  peeras_primaryMetric: number;
  peeras_secondaryMetric: number;
  peeras_baselineAverage: number;
  peeras_peakObserved: number;
  peeras_standardDeviation: number;
  peeras_rawHexSample: string;
  peeras_metadataTag: Record<string, string>;
  localas_primaryMetric: number;
  localas_secondaryMetric: number;
  localas_baselineAverage: number;
  localas_peakObserved: number;
  localas_standardDeviation: number;
  localas_rawHexSample: string;
  localas_metadataTag: Record<string, string>;
  peerrouterid_primaryMetric: number;
  peerrouterid_secondaryMetric: number;
  peerrouterid_baselineAverage: number;
  peerrouterid_peakObserved: number;
  peerrouterid_standardDeviation: number;
  peerrouterid_rawHexSample: string;
  peerrouterid_metadataTag: Record<string, string>;
  bgpstate_primaryMetric: number;
  bgpstate_secondaryMetric: number;
  bgpstate_baselineAverage: number;
  bgpstate_peakObserved: number;
  bgpstate_standardDeviation: number;
  bgpstate_rawHexSample: string;
  bgpstate_metadataTag: Record<string, string>;
  advertisedprefixes_primaryMetric: number;
  advertisedprefixes_secondaryMetric: number;
  advertisedprefixes_baselineAverage: number;
  advertisedprefixes_peakObserved: number;
  advertisedprefixes_standardDeviation: number;
  advertisedprefixes_rawHexSample: string;
  advertisedprefixes_metadataTag: Record<string, string>;
  withdrawnprefixes_primaryMetric: number;
  withdrawnprefixes_secondaryMetric: number;
  withdrawnprefixes_baselineAverage: number;
  withdrawnprefixes_peakObserved: number;
  withdrawnprefixes_standardDeviation: number;
  withdrawnprefixes_rawHexSample: string;
  withdrawnprefixes_metadataTag: Record<string, string>;
  flapcount_primaryMetric: number;
  flapcount_secondaryMetric: number;
  flapcount_baselineAverage: number;
  flapcount_peakObserved: number;
  flapcount_standardDeviation: number;
  flapcount_rawHexSample: string;
  flapcount_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Bgp4RoutingTelemetryFilterV29 = Partial<Bgp4RoutingTelemetryRecordV29> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Bgp4RoutingTelemetryRecordV30 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  peeras_primaryMetric: number;
  peeras_secondaryMetric: number;
  peeras_baselineAverage: number;
  peeras_peakObserved: number;
  peeras_standardDeviation: number;
  peeras_rawHexSample: string;
  peeras_metadataTag: Record<string, string>;
  localas_primaryMetric: number;
  localas_secondaryMetric: number;
  localas_baselineAverage: number;
  localas_peakObserved: number;
  localas_standardDeviation: number;
  localas_rawHexSample: string;
  localas_metadataTag: Record<string, string>;
  peerrouterid_primaryMetric: number;
  peerrouterid_secondaryMetric: number;
  peerrouterid_baselineAverage: number;
  peerrouterid_peakObserved: number;
  peerrouterid_standardDeviation: number;
  peerrouterid_rawHexSample: string;
  peerrouterid_metadataTag: Record<string, string>;
  bgpstate_primaryMetric: number;
  bgpstate_secondaryMetric: number;
  bgpstate_baselineAverage: number;
  bgpstate_peakObserved: number;
  bgpstate_standardDeviation: number;
  bgpstate_rawHexSample: string;
  bgpstate_metadataTag: Record<string, string>;
  advertisedprefixes_primaryMetric: number;
  advertisedprefixes_secondaryMetric: number;
  advertisedprefixes_baselineAverage: number;
  advertisedprefixes_peakObserved: number;
  advertisedprefixes_standardDeviation: number;
  advertisedprefixes_rawHexSample: string;
  advertisedprefixes_metadataTag: Record<string, string>;
  withdrawnprefixes_primaryMetric: number;
  withdrawnprefixes_secondaryMetric: number;
  withdrawnprefixes_baselineAverage: number;
  withdrawnprefixes_peakObserved: number;
  withdrawnprefixes_standardDeviation: number;
  withdrawnprefixes_rawHexSample: string;
  withdrawnprefixes_metadataTag: Record<string, string>;
  flapcount_primaryMetric: number;
  flapcount_secondaryMetric: number;
  flapcount_baselineAverage: number;
  flapcount_peakObserved: number;
  flapcount_standardDeviation: number;
  flapcount_rawHexSample: string;
  flapcount_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Bgp4RoutingTelemetryFilterV30 = Partial<Bgp4RoutingTelemetryRecordV30> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Bgp4RoutingTelemetryRecordV31 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  peeras_primaryMetric: number;
  peeras_secondaryMetric: number;
  peeras_baselineAverage: number;
  peeras_peakObserved: number;
  peeras_standardDeviation: number;
  peeras_rawHexSample: string;
  peeras_metadataTag: Record<string, string>;
  localas_primaryMetric: number;
  localas_secondaryMetric: number;
  localas_baselineAverage: number;
  localas_peakObserved: number;
  localas_standardDeviation: number;
  localas_rawHexSample: string;
  localas_metadataTag: Record<string, string>;
  peerrouterid_primaryMetric: number;
  peerrouterid_secondaryMetric: number;
  peerrouterid_baselineAverage: number;
  peerrouterid_peakObserved: number;
  peerrouterid_standardDeviation: number;
  peerrouterid_rawHexSample: string;
  peerrouterid_metadataTag: Record<string, string>;
  bgpstate_primaryMetric: number;
  bgpstate_secondaryMetric: number;
  bgpstate_baselineAverage: number;
  bgpstate_peakObserved: number;
  bgpstate_standardDeviation: number;
  bgpstate_rawHexSample: string;
  bgpstate_metadataTag: Record<string, string>;
  advertisedprefixes_primaryMetric: number;
  advertisedprefixes_secondaryMetric: number;
  advertisedprefixes_baselineAverage: number;
  advertisedprefixes_peakObserved: number;
  advertisedprefixes_standardDeviation: number;
  advertisedprefixes_rawHexSample: string;
  advertisedprefixes_metadataTag: Record<string, string>;
  withdrawnprefixes_primaryMetric: number;
  withdrawnprefixes_secondaryMetric: number;
  withdrawnprefixes_baselineAverage: number;
  withdrawnprefixes_peakObserved: number;
  withdrawnprefixes_standardDeviation: number;
  withdrawnprefixes_rawHexSample: string;
  withdrawnprefixes_metadataTag: Record<string, string>;
  flapcount_primaryMetric: number;
  flapcount_secondaryMetric: number;
  flapcount_baselineAverage: number;
  flapcount_peakObserved: number;
  flapcount_standardDeviation: number;
  flapcount_rawHexSample: string;
  flapcount_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Bgp4RoutingTelemetryFilterV31 = Partial<Bgp4RoutingTelemetryRecordV31> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Bgp4RoutingTelemetryRecordV32 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  peeras_primaryMetric: number;
  peeras_secondaryMetric: number;
  peeras_baselineAverage: number;
  peeras_peakObserved: number;
  peeras_standardDeviation: number;
  peeras_rawHexSample: string;
  peeras_metadataTag: Record<string, string>;
  localas_primaryMetric: number;
  localas_secondaryMetric: number;
  localas_baselineAverage: number;
  localas_peakObserved: number;
  localas_standardDeviation: number;
  localas_rawHexSample: string;
  localas_metadataTag: Record<string, string>;
  peerrouterid_primaryMetric: number;
  peerrouterid_secondaryMetric: number;
  peerrouterid_baselineAverage: number;
  peerrouterid_peakObserved: number;
  peerrouterid_standardDeviation: number;
  peerrouterid_rawHexSample: string;
  peerrouterid_metadataTag: Record<string, string>;
  bgpstate_primaryMetric: number;
  bgpstate_secondaryMetric: number;
  bgpstate_baselineAverage: number;
  bgpstate_peakObserved: number;
  bgpstate_standardDeviation: number;
  bgpstate_rawHexSample: string;
  bgpstate_metadataTag: Record<string, string>;
  advertisedprefixes_primaryMetric: number;
  advertisedprefixes_secondaryMetric: number;
  advertisedprefixes_baselineAverage: number;
  advertisedprefixes_peakObserved: number;
  advertisedprefixes_standardDeviation: number;
  advertisedprefixes_rawHexSample: string;
  advertisedprefixes_metadataTag: Record<string, string>;
  withdrawnprefixes_primaryMetric: number;
  withdrawnprefixes_secondaryMetric: number;
  withdrawnprefixes_baselineAverage: number;
  withdrawnprefixes_peakObserved: number;
  withdrawnprefixes_standardDeviation: number;
  withdrawnprefixes_rawHexSample: string;
  withdrawnprefixes_metadataTag: Record<string, string>;
  flapcount_primaryMetric: number;
  flapcount_secondaryMetric: number;
  flapcount_baselineAverage: number;
  flapcount_peakObserved: number;
  flapcount_standardDeviation: number;
  flapcount_rawHexSample: string;
  flapcount_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Bgp4RoutingTelemetryFilterV32 = Partial<Bgp4RoutingTelemetryRecordV32> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Bgp4RoutingTelemetryRecordV33 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  peeras_primaryMetric: number;
  peeras_secondaryMetric: number;
  peeras_baselineAverage: number;
  peeras_peakObserved: number;
  peeras_standardDeviation: number;
  peeras_rawHexSample: string;
  peeras_metadataTag: Record<string, string>;
  localas_primaryMetric: number;
  localas_secondaryMetric: number;
  localas_baselineAverage: number;
  localas_peakObserved: number;
  localas_standardDeviation: number;
  localas_rawHexSample: string;
  localas_metadataTag: Record<string, string>;
  peerrouterid_primaryMetric: number;
  peerrouterid_secondaryMetric: number;
  peerrouterid_baselineAverage: number;
  peerrouterid_peakObserved: number;
  peerrouterid_standardDeviation: number;
  peerrouterid_rawHexSample: string;
  peerrouterid_metadataTag: Record<string, string>;
  bgpstate_primaryMetric: number;
  bgpstate_secondaryMetric: number;
  bgpstate_baselineAverage: number;
  bgpstate_peakObserved: number;
  bgpstate_standardDeviation: number;
  bgpstate_rawHexSample: string;
  bgpstate_metadataTag: Record<string, string>;
  advertisedprefixes_primaryMetric: number;
  advertisedprefixes_secondaryMetric: number;
  advertisedprefixes_baselineAverage: number;
  advertisedprefixes_peakObserved: number;
  advertisedprefixes_standardDeviation: number;
  advertisedprefixes_rawHexSample: string;
  advertisedprefixes_metadataTag: Record<string, string>;
  withdrawnprefixes_primaryMetric: number;
  withdrawnprefixes_secondaryMetric: number;
  withdrawnprefixes_baselineAverage: number;
  withdrawnprefixes_peakObserved: number;
  withdrawnprefixes_standardDeviation: number;
  withdrawnprefixes_rawHexSample: string;
  withdrawnprefixes_metadataTag: Record<string, string>;
  flapcount_primaryMetric: number;
  flapcount_secondaryMetric: number;
  flapcount_baselineAverage: number;
  flapcount_peakObserved: number;
  flapcount_standardDeviation: number;
  flapcount_rawHexSample: string;
  flapcount_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Bgp4RoutingTelemetryFilterV33 = Partial<Bgp4RoutingTelemetryRecordV33> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Bgp4RoutingTelemetryRecordV34 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  peeras_primaryMetric: number;
  peeras_secondaryMetric: number;
  peeras_baselineAverage: number;
  peeras_peakObserved: number;
  peeras_standardDeviation: number;
  peeras_rawHexSample: string;
  peeras_metadataTag: Record<string, string>;
  localas_primaryMetric: number;
  localas_secondaryMetric: number;
  localas_baselineAverage: number;
  localas_peakObserved: number;
  localas_standardDeviation: number;
  localas_rawHexSample: string;
  localas_metadataTag: Record<string, string>;
  peerrouterid_primaryMetric: number;
  peerrouterid_secondaryMetric: number;
  peerrouterid_baselineAverage: number;
  peerrouterid_peakObserved: number;
  peerrouterid_standardDeviation: number;
  peerrouterid_rawHexSample: string;
  peerrouterid_metadataTag: Record<string, string>;
  bgpstate_primaryMetric: number;
  bgpstate_secondaryMetric: number;
  bgpstate_baselineAverage: number;
  bgpstate_peakObserved: number;
  bgpstate_standardDeviation: number;
  bgpstate_rawHexSample: string;
  bgpstate_metadataTag: Record<string, string>;
  advertisedprefixes_primaryMetric: number;
  advertisedprefixes_secondaryMetric: number;
  advertisedprefixes_baselineAverage: number;
  advertisedprefixes_peakObserved: number;
  advertisedprefixes_standardDeviation: number;
  advertisedprefixes_rawHexSample: string;
  advertisedprefixes_metadataTag: Record<string, string>;
  withdrawnprefixes_primaryMetric: number;
  withdrawnprefixes_secondaryMetric: number;
  withdrawnprefixes_baselineAverage: number;
  withdrawnprefixes_peakObserved: number;
  withdrawnprefixes_standardDeviation: number;
  withdrawnprefixes_rawHexSample: string;
  withdrawnprefixes_metadataTag: Record<string, string>;
  flapcount_primaryMetric: number;
  flapcount_secondaryMetric: number;
  flapcount_baselineAverage: number;
  flapcount_peakObserved: number;
  flapcount_standardDeviation: number;
  flapcount_rawHexSample: string;
  flapcount_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Bgp4RoutingTelemetryFilterV34 = Partial<Bgp4RoutingTelemetryRecordV34> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Bgp4RoutingTelemetryRecordV35 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  peeras_primaryMetric: number;
  peeras_secondaryMetric: number;
  peeras_baselineAverage: number;
  peeras_peakObserved: number;
  peeras_standardDeviation: number;
  peeras_rawHexSample: string;
  peeras_metadataTag: Record<string, string>;
  localas_primaryMetric: number;
  localas_secondaryMetric: number;
  localas_baselineAverage: number;
  localas_peakObserved: number;
  localas_standardDeviation: number;
  localas_rawHexSample: string;
  localas_metadataTag: Record<string, string>;
  peerrouterid_primaryMetric: number;
  peerrouterid_secondaryMetric: number;
  peerrouterid_baselineAverage: number;
  peerrouterid_peakObserved: number;
  peerrouterid_standardDeviation: number;
  peerrouterid_rawHexSample: string;
  peerrouterid_metadataTag: Record<string, string>;
  bgpstate_primaryMetric: number;
  bgpstate_secondaryMetric: number;
  bgpstate_baselineAverage: number;
  bgpstate_peakObserved: number;
  bgpstate_standardDeviation: number;
  bgpstate_rawHexSample: string;
  bgpstate_metadataTag: Record<string, string>;
  advertisedprefixes_primaryMetric: number;
  advertisedprefixes_secondaryMetric: number;
  advertisedprefixes_baselineAverage: number;
  advertisedprefixes_peakObserved: number;
  advertisedprefixes_standardDeviation: number;
  advertisedprefixes_rawHexSample: string;
  advertisedprefixes_metadataTag: Record<string, string>;
  withdrawnprefixes_primaryMetric: number;
  withdrawnprefixes_secondaryMetric: number;
  withdrawnprefixes_baselineAverage: number;
  withdrawnprefixes_peakObserved: number;
  withdrawnprefixes_standardDeviation: number;
  withdrawnprefixes_rawHexSample: string;
  withdrawnprefixes_metadataTag: Record<string, string>;
  flapcount_primaryMetric: number;
  flapcount_secondaryMetric: number;
  flapcount_baselineAverage: number;
  flapcount_peakObserved: number;
  flapcount_standardDeviation: number;
  flapcount_rawHexSample: string;
  flapcount_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Bgp4RoutingTelemetryFilterV35 = Partial<Bgp4RoutingTelemetryRecordV35> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Bgp4RoutingTelemetryRecordV36 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  peeras_primaryMetric: number;
  peeras_secondaryMetric: number;
  peeras_baselineAverage: number;
  peeras_peakObserved: number;
  peeras_standardDeviation: number;
  peeras_rawHexSample: string;
  peeras_metadataTag: Record<string, string>;
  localas_primaryMetric: number;
  localas_secondaryMetric: number;
  localas_baselineAverage: number;
  localas_peakObserved: number;
  localas_standardDeviation: number;
  localas_rawHexSample: string;
  localas_metadataTag: Record<string, string>;
  peerrouterid_primaryMetric: number;
  peerrouterid_secondaryMetric: number;
  peerrouterid_baselineAverage: number;
  peerrouterid_peakObserved: number;
  peerrouterid_standardDeviation: number;
  peerrouterid_rawHexSample: string;
  peerrouterid_metadataTag: Record<string, string>;
  bgpstate_primaryMetric: number;
  bgpstate_secondaryMetric: number;
  bgpstate_baselineAverage: number;
  bgpstate_peakObserved: number;
  bgpstate_standardDeviation: number;
  bgpstate_rawHexSample: string;
  bgpstate_metadataTag: Record<string, string>;
  advertisedprefixes_primaryMetric: number;
  advertisedprefixes_secondaryMetric: number;
  advertisedprefixes_baselineAverage: number;
  advertisedprefixes_peakObserved: number;
  advertisedprefixes_standardDeviation: number;
  advertisedprefixes_rawHexSample: string;
  advertisedprefixes_metadataTag: Record<string, string>;
  withdrawnprefixes_primaryMetric: number;
  withdrawnprefixes_secondaryMetric: number;
  withdrawnprefixes_baselineAverage: number;
  withdrawnprefixes_peakObserved: number;
  withdrawnprefixes_standardDeviation: number;
  withdrawnprefixes_rawHexSample: string;
  withdrawnprefixes_metadataTag: Record<string, string>;
  flapcount_primaryMetric: number;
  flapcount_secondaryMetric: number;
  flapcount_baselineAverage: number;
  flapcount_peakObserved: number;
  flapcount_standardDeviation: number;
  flapcount_rawHexSample: string;
  flapcount_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Bgp4RoutingTelemetryFilterV36 = Partial<Bgp4RoutingTelemetryRecordV36> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Bgp4RoutingTelemetryRecordV37 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  peeras_primaryMetric: number;
  peeras_secondaryMetric: number;
  peeras_baselineAverage: number;
  peeras_peakObserved: number;
  peeras_standardDeviation: number;
  peeras_rawHexSample: string;
  peeras_metadataTag: Record<string, string>;
  localas_primaryMetric: number;
  localas_secondaryMetric: number;
  localas_baselineAverage: number;
  localas_peakObserved: number;
  localas_standardDeviation: number;
  localas_rawHexSample: string;
  localas_metadataTag: Record<string, string>;
  peerrouterid_primaryMetric: number;
  peerrouterid_secondaryMetric: number;
  peerrouterid_baselineAverage: number;
  peerrouterid_peakObserved: number;
  peerrouterid_standardDeviation: number;
  peerrouterid_rawHexSample: string;
  peerrouterid_metadataTag: Record<string, string>;
  bgpstate_primaryMetric: number;
  bgpstate_secondaryMetric: number;
  bgpstate_baselineAverage: number;
  bgpstate_peakObserved: number;
  bgpstate_standardDeviation: number;
  bgpstate_rawHexSample: string;
  bgpstate_metadataTag: Record<string, string>;
  advertisedprefixes_primaryMetric: number;
  advertisedprefixes_secondaryMetric: number;
  advertisedprefixes_baselineAverage: number;
  advertisedprefixes_peakObserved: number;
  advertisedprefixes_standardDeviation: number;
  advertisedprefixes_rawHexSample: string;
  advertisedprefixes_metadataTag: Record<string, string>;
  withdrawnprefixes_primaryMetric: number;
  withdrawnprefixes_secondaryMetric: number;
  withdrawnprefixes_baselineAverage: number;
  withdrawnprefixes_peakObserved: number;
  withdrawnprefixes_standardDeviation: number;
  withdrawnprefixes_rawHexSample: string;
  withdrawnprefixes_metadataTag: Record<string, string>;
  flapcount_primaryMetric: number;
  flapcount_secondaryMetric: number;
  flapcount_baselineAverage: number;
  flapcount_peakObserved: number;
  flapcount_standardDeviation: number;
  flapcount_rawHexSample: string;
  flapcount_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Bgp4RoutingTelemetryFilterV37 = Partial<Bgp4RoutingTelemetryRecordV37> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Bgp4RoutingTelemetryRecordV38 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  peeras_primaryMetric: number;
  peeras_secondaryMetric: number;
  peeras_baselineAverage: number;
  peeras_peakObserved: number;
  peeras_standardDeviation: number;
  peeras_rawHexSample: string;
  peeras_metadataTag: Record<string, string>;
  localas_primaryMetric: number;
  localas_secondaryMetric: number;
  localas_baselineAverage: number;
  localas_peakObserved: number;
  localas_standardDeviation: number;
  localas_rawHexSample: string;
  localas_metadataTag: Record<string, string>;
  peerrouterid_primaryMetric: number;
  peerrouterid_secondaryMetric: number;
  peerrouterid_baselineAverage: number;
  peerrouterid_peakObserved: number;
  peerrouterid_standardDeviation: number;
  peerrouterid_rawHexSample: string;
  peerrouterid_metadataTag: Record<string, string>;
  bgpstate_primaryMetric: number;
  bgpstate_secondaryMetric: number;
  bgpstate_baselineAverage: number;
  bgpstate_peakObserved: number;
  bgpstate_standardDeviation: number;
  bgpstate_rawHexSample: string;
  bgpstate_metadataTag: Record<string, string>;
  advertisedprefixes_primaryMetric: number;
  advertisedprefixes_secondaryMetric: number;
  advertisedprefixes_baselineAverage: number;
  advertisedprefixes_peakObserved: number;
  advertisedprefixes_standardDeviation: number;
  advertisedprefixes_rawHexSample: string;
  advertisedprefixes_metadataTag: Record<string, string>;
  withdrawnprefixes_primaryMetric: number;
  withdrawnprefixes_secondaryMetric: number;
  withdrawnprefixes_baselineAverage: number;
  withdrawnprefixes_peakObserved: number;
  withdrawnprefixes_standardDeviation: number;
  withdrawnprefixes_rawHexSample: string;
  withdrawnprefixes_metadataTag: Record<string, string>;
  flapcount_primaryMetric: number;
  flapcount_secondaryMetric: number;
  flapcount_baselineAverage: number;
  flapcount_peakObserved: number;
  flapcount_standardDeviation: number;
  flapcount_rawHexSample: string;
  flapcount_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Bgp4RoutingTelemetryFilterV38 = Partial<Bgp4RoutingTelemetryRecordV38> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Bgp4RoutingTelemetryRecordV39 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  peeras_primaryMetric: number;
  peeras_secondaryMetric: number;
  peeras_baselineAverage: number;
  peeras_peakObserved: number;
  peeras_standardDeviation: number;
  peeras_rawHexSample: string;
  peeras_metadataTag: Record<string, string>;
  localas_primaryMetric: number;
  localas_secondaryMetric: number;
  localas_baselineAverage: number;
  localas_peakObserved: number;
  localas_standardDeviation: number;
  localas_rawHexSample: string;
  localas_metadataTag: Record<string, string>;
  peerrouterid_primaryMetric: number;
  peerrouterid_secondaryMetric: number;
  peerrouterid_baselineAverage: number;
  peerrouterid_peakObserved: number;
  peerrouterid_standardDeviation: number;
  peerrouterid_rawHexSample: string;
  peerrouterid_metadataTag: Record<string, string>;
  bgpstate_primaryMetric: number;
  bgpstate_secondaryMetric: number;
  bgpstate_baselineAverage: number;
  bgpstate_peakObserved: number;
  bgpstate_standardDeviation: number;
  bgpstate_rawHexSample: string;
  bgpstate_metadataTag: Record<string, string>;
  advertisedprefixes_primaryMetric: number;
  advertisedprefixes_secondaryMetric: number;
  advertisedprefixes_baselineAverage: number;
  advertisedprefixes_peakObserved: number;
  advertisedprefixes_standardDeviation: number;
  advertisedprefixes_rawHexSample: string;
  advertisedprefixes_metadataTag: Record<string, string>;
  withdrawnprefixes_primaryMetric: number;
  withdrawnprefixes_secondaryMetric: number;
  withdrawnprefixes_baselineAverage: number;
  withdrawnprefixes_peakObserved: number;
  withdrawnprefixes_standardDeviation: number;
  withdrawnprefixes_rawHexSample: string;
  withdrawnprefixes_metadataTag: Record<string, string>;
  flapcount_primaryMetric: number;
  flapcount_secondaryMetric: number;
  flapcount_baselineAverage: number;
  flapcount_peakObserved: number;
  flapcount_standardDeviation: number;
  flapcount_rawHexSample: string;
  flapcount_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Bgp4RoutingTelemetryFilterV39 = Partial<Bgp4RoutingTelemetryRecordV39> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Bgp4RoutingTelemetryRecordV40 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  peeras_primaryMetric: number;
  peeras_secondaryMetric: number;
  peeras_baselineAverage: number;
  peeras_peakObserved: number;
  peeras_standardDeviation: number;
  peeras_rawHexSample: string;
  peeras_metadataTag: Record<string, string>;
  localas_primaryMetric: number;
  localas_secondaryMetric: number;
  localas_baselineAverage: number;
  localas_peakObserved: number;
  localas_standardDeviation: number;
  localas_rawHexSample: string;
  localas_metadataTag: Record<string, string>;
  peerrouterid_primaryMetric: number;
  peerrouterid_secondaryMetric: number;
  peerrouterid_baselineAverage: number;
  peerrouterid_peakObserved: number;
  peerrouterid_standardDeviation: number;
  peerrouterid_rawHexSample: string;
  peerrouterid_metadataTag: Record<string, string>;
  bgpstate_primaryMetric: number;
  bgpstate_secondaryMetric: number;
  bgpstate_baselineAverage: number;
  bgpstate_peakObserved: number;
  bgpstate_standardDeviation: number;
  bgpstate_rawHexSample: string;
  bgpstate_metadataTag: Record<string, string>;
  advertisedprefixes_primaryMetric: number;
  advertisedprefixes_secondaryMetric: number;
  advertisedprefixes_baselineAverage: number;
  advertisedprefixes_peakObserved: number;
  advertisedprefixes_standardDeviation: number;
  advertisedprefixes_rawHexSample: string;
  advertisedprefixes_metadataTag: Record<string, string>;
  withdrawnprefixes_primaryMetric: number;
  withdrawnprefixes_secondaryMetric: number;
  withdrawnprefixes_baselineAverage: number;
  withdrawnprefixes_peakObserved: number;
  withdrawnprefixes_standardDeviation: number;
  withdrawnprefixes_rawHexSample: string;
  withdrawnprefixes_metadataTag: Record<string, string>;
  flapcount_primaryMetric: number;
  flapcount_secondaryMetric: number;
  flapcount_baselineAverage: number;
  flapcount_peakObserved: number;
  flapcount_standardDeviation: number;
  flapcount_rawHexSample: string;
  flapcount_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Bgp4RoutingTelemetryFilterV40 = Partial<Bgp4RoutingTelemetryRecordV40> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};
