/**
 * Enterprise Telecommunications Protocol Specification: 5G User Plane Function (UPF) Throughput & Packet Processing
 * Module: @geonet/types/telecom/core_5g_upf_metrics
 * Standard Compliance: 3GPP TS 38.401, IETF RFC Standards, ITU-T G.8032
 */

export interface 5GUserPlaneFunctionUPFThroughput&PacketProcessingConfig {
  samplingIntervalMs: number;
  collectionEnabled: boolean;
  highWatermarkThreshold: number;
  lowWatermarkThreshold: number;
  retryAttempts: number;
  timeoutMs: number;
}

export interface Core5GUpfMetricsRecordV1 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  uplinkbytes_primaryMetric: number;
  uplinkbytes_secondaryMetric: number;
  uplinkbytes_baselineAverage: number;
  uplinkbytes_peakObserved: number;
  uplinkbytes_standardDeviation: number;
  uplinkbytes_rawHexSample: string;
  uplinkbytes_metadataTag: Record<string, string>;
  downlinkbytes_primaryMetric: number;
  downlinkbytes_secondaryMetric: number;
  downlinkbytes_baselineAverage: number;
  downlinkbytes_peakObserved: number;
  downlinkbytes_standardDeviation: number;
  downlinkbytes_rawHexSample: string;
  downlinkbytes_metadataTag: Record<string, string>;
  droppedpackets_primaryMetric: number;
  droppedpackets_secondaryMetric: number;
  droppedpackets_baselineAverage: number;
  droppedpackets_peakObserved: number;
  droppedpackets_standardDeviation: number;
  droppedpackets_rawHexSample: string;
  droppedpackets_metadataTag: Record<string, string>;
  bufferoccupancy_primaryMetric: number;
  bufferoccupancy_secondaryMetric: number;
  bufferoccupancy_baselineAverage: number;
  bufferoccupancy_peakObserved: number;
  bufferoccupancy_standardDeviation: number;
  bufferoccupancy_rawHexSample: string;
  bufferoccupancy_metadataTag: Record<string, string>;
  gtpuerrorcounter_primaryMetric: number;
  gtpuerrorcounter_secondaryMetric: number;
  gtpuerrorcounter_baselineAverage: number;
  gtpuerrorcounter_peakObserved: number;
  gtpuerrorcounter_standardDeviation: number;
  gtpuerrorcounter_rawHexSample: string;
  gtpuerrorcounter_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Core5GUpfMetricsFilterV1 = Partial<Core5GUpfMetricsRecordV1> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Core5GUpfMetricsRecordV2 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  uplinkbytes_primaryMetric: number;
  uplinkbytes_secondaryMetric: number;
  uplinkbytes_baselineAverage: number;
  uplinkbytes_peakObserved: number;
  uplinkbytes_standardDeviation: number;
  uplinkbytes_rawHexSample: string;
  uplinkbytes_metadataTag: Record<string, string>;
  downlinkbytes_primaryMetric: number;
  downlinkbytes_secondaryMetric: number;
  downlinkbytes_baselineAverage: number;
  downlinkbytes_peakObserved: number;
  downlinkbytes_standardDeviation: number;
  downlinkbytes_rawHexSample: string;
  downlinkbytes_metadataTag: Record<string, string>;
  droppedpackets_primaryMetric: number;
  droppedpackets_secondaryMetric: number;
  droppedpackets_baselineAverage: number;
  droppedpackets_peakObserved: number;
  droppedpackets_standardDeviation: number;
  droppedpackets_rawHexSample: string;
  droppedpackets_metadataTag: Record<string, string>;
  bufferoccupancy_primaryMetric: number;
  bufferoccupancy_secondaryMetric: number;
  bufferoccupancy_baselineAverage: number;
  bufferoccupancy_peakObserved: number;
  bufferoccupancy_standardDeviation: number;
  bufferoccupancy_rawHexSample: string;
  bufferoccupancy_metadataTag: Record<string, string>;
  gtpuerrorcounter_primaryMetric: number;
  gtpuerrorcounter_secondaryMetric: number;
  gtpuerrorcounter_baselineAverage: number;
  gtpuerrorcounter_peakObserved: number;
  gtpuerrorcounter_standardDeviation: number;
  gtpuerrorcounter_rawHexSample: string;
  gtpuerrorcounter_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Core5GUpfMetricsFilterV2 = Partial<Core5GUpfMetricsRecordV2> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Core5GUpfMetricsRecordV3 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  uplinkbytes_primaryMetric: number;
  uplinkbytes_secondaryMetric: number;
  uplinkbytes_baselineAverage: number;
  uplinkbytes_peakObserved: number;
  uplinkbytes_standardDeviation: number;
  uplinkbytes_rawHexSample: string;
  uplinkbytes_metadataTag: Record<string, string>;
  downlinkbytes_primaryMetric: number;
  downlinkbytes_secondaryMetric: number;
  downlinkbytes_baselineAverage: number;
  downlinkbytes_peakObserved: number;
  downlinkbytes_standardDeviation: number;
  downlinkbytes_rawHexSample: string;
  downlinkbytes_metadataTag: Record<string, string>;
  droppedpackets_primaryMetric: number;
  droppedpackets_secondaryMetric: number;
  droppedpackets_baselineAverage: number;
  droppedpackets_peakObserved: number;
  droppedpackets_standardDeviation: number;
  droppedpackets_rawHexSample: string;
  droppedpackets_metadataTag: Record<string, string>;
  bufferoccupancy_primaryMetric: number;
  bufferoccupancy_secondaryMetric: number;
  bufferoccupancy_baselineAverage: number;
  bufferoccupancy_peakObserved: number;
  bufferoccupancy_standardDeviation: number;
  bufferoccupancy_rawHexSample: string;
  bufferoccupancy_metadataTag: Record<string, string>;
  gtpuerrorcounter_primaryMetric: number;
  gtpuerrorcounter_secondaryMetric: number;
  gtpuerrorcounter_baselineAverage: number;
  gtpuerrorcounter_peakObserved: number;
  gtpuerrorcounter_standardDeviation: number;
  gtpuerrorcounter_rawHexSample: string;
  gtpuerrorcounter_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Core5GUpfMetricsFilterV3 = Partial<Core5GUpfMetricsRecordV3> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Core5GUpfMetricsRecordV4 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  uplinkbytes_primaryMetric: number;
  uplinkbytes_secondaryMetric: number;
  uplinkbytes_baselineAverage: number;
  uplinkbytes_peakObserved: number;
  uplinkbytes_standardDeviation: number;
  uplinkbytes_rawHexSample: string;
  uplinkbytes_metadataTag: Record<string, string>;
  downlinkbytes_primaryMetric: number;
  downlinkbytes_secondaryMetric: number;
  downlinkbytes_baselineAverage: number;
  downlinkbytes_peakObserved: number;
  downlinkbytes_standardDeviation: number;
  downlinkbytes_rawHexSample: string;
  downlinkbytes_metadataTag: Record<string, string>;
  droppedpackets_primaryMetric: number;
  droppedpackets_secondaryMetric: number;
  droppedpackets_baselineAverage: number;
  droppedpackets_peakObserved: number;
  droppedpackets_standardDeviation: number;
  droppedpackets_rawHexSample: string;
  droppedpackets_metadataTag: Record<string, string>;
  bufferoccupancy_primaryMetric: number;
  bufferoccupancy_secondaryMetric: number;
  bufferoccupancy_baselineAverage: number;
  bufferoccupancy_peakObserved: number;
  bufferoccupancy_standardDeviation: number;
  bufferoccupancy_rawHexSample: string;
  bufferoccupancy_metadataTag: Record<string, string>;
  gtpuerrorcounter_primaryMetric: number;
  gtpuerrorcounter_secondaryMetric: number;
  gtpuerrorcounter_baselineAverage: number;
  gtpuerrorcounter_peakObserved: number;
  gtpuerrorcounter_standardDeviation: number;
  gtpuerrorcounter_rawHexSample: string;
  gtpuerrorcounter_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Core5GUpfMetricsFilterV4 = Partial<Core5GUpfMetricsRecordV4> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Core5GUpfMetricsRecordV5 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  uplinkbytes_primaryMetric: number;
  uplinkbytes_secondaryMetric: number;
  uplinkbytes_baselineAverage: number;
  uplinkbytes_peakObserved: number;
  uplinkbytes_standardDeviation: number;
  uplinkbytes_rawHexSample: string;
  uplinkbytes_metadataTag: Record<string, string>;
  downlinkbytes_primaryMetric: number;
  downlinkbytes_secondaryMetric: number;
  downlinkbytes_baselineAverage: number;
  downlinkbytes_peakObserved: number;
  downlinkbytes_standardDeviation: number;
  downlinkbytes_rawHexSample: string;
  downlinkbytes_metadataTag: Record<string, string>;
  droppedpackets_primaryMetric: number;
  droppedpackets_secondaryMetric: number;
  droppedpackets_baselineAverage: number;
  droppedpackets_peakObserved: number;
  droppedpackets_standardDeviation: number;
  droppedpackets_rawHexSample: string;
  droppedpackets_metadataTag: Record<string, string>;
  bufferoccupancy_primaryMetric: number;
  bufferoccupancy_secondaryMetric: number;
  bufferoccupancy_baselineAverage: number;
  bufferoccupancy_peakObserved: number;
  bufferoccupancy_standardDeviation: number;
  bufferoccupancy_rawHexSample: string;
  bufferoccupancy_metadataTag: Record<string, string>;
  gtpuerrorcounter_primaryMetric: number;
  gtpuerrorcounter_secondaryMetric: number;
  gtpuerrorcounter_baselineAverage: number;
  gtpuerrorcounter_peakObserved: number;
  gtpuerrorcounter_standardDeviation: number;
  gtpuerrorcounter_rawHexSample: string;
  gtpuerrorcounter_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Core5GUpfMetricsFilterV5 = Partial<Core5GUpfMetricsRecordV5> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Core5GUpfMetricsRecordV6 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  uplinkbytes_primaryMetric: number;
  uplinkbytes_secondaryMetric: number;
  uplinkbytes_baselineAverage: number;
  uplinkbytes_peakObserved: number;
  uplinkbytes_standardDeviation: number;
  uplinkbytes_rawHexSample: string;
  uplinkbytes_metadataTag: Record<string, string>;
  downlinkbytes_primaryMetric: number;
  downlinkbytes_secondaryMetric: number;
  downlinkbytes_baselineAverage: number;
  downlinkbytes_peakObserved: number;
  downlinkbytes_standardDeviation: number;
  downlinkbytes_rawHexSample: string;
  downlinkbytes_metadataTag: Record<string, string>;
  droppedpackets_primaryMetric: number;
  droppedpackets_secondaryMetric: number;
  droppedpackets_baselineAverage: number;
  droppedpackets_peakObserved: number;
  droppedpackets_standardDeviation: number;
  droppedpackets_rawHexSample: string;
  droppedpackets_metadataTag: Record<string, string>;
  bufferoccupancy_primaryMetric: number;
  bufferoccupancy_secondaryMetric: number;
  bufferoccupancy_baselineAverage: number;
  bufferoccupancy_peakObserved: number;
  bufferoccupancy_standardDeviation: number;
  bufferoccupancy_rawHexSample: string;
  bufferoccupancy_metadataTag: Record<string, string>;
  gtpuerrorcounter_primaryMetric: number;
  gtpuerrorcounter_secondaryMetric: number;
  gtpuerrorcounter_baselineAverage: number;
  gtpuerrorcounter_peakObserved: number;
  gtpuerrorcounter_standardDeviation: number;
  gtpuerrorcounter_rawHexSample: string;
  gtpuerrorcounter_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Core5GUpfMetricsFilterV6 = Partial<Core5GUpfMetricsRecordV6> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Core5GUpfMetricsRecordV7 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  uplinkbytes_primaryMetric: number;
  uplinkbytes_secondaryMetric: number;
  uplinkbytes_baselineAverage: number;
  uplinkbytes_peakObserved: number;
  uplinkbytes_standardDeviation: number;
  uplinkbytes_rawHexSample: string;
  uplinkbytes_metadataTag: Record<string, string>;
  downlinkbytes_primaryMetric: number;
  downlinkbytes_secondaryMetric: number;
  downlinkbytes_baselineAverage: number;
  downlinkbytes_peakObserved: number;
  downlinkbytes_standardDeviation: number;
  downlinkbytes_rawHexSample: string;
  downlinkbytes_metadataTag: Record<string, string>;
  droppedpackets_primaryMetric: number;
  droppedpackets_secondaryMetric: number;
  droppedpackets_baselineAverage: number;
  droppedpackets_peakObserved: number;
  droppedpackets_standardDeviation: number;
  droppedpackets_rawHexSample: string;
  droppedpackets_metadataTag: Record<string, string>;
  bufferoccupancy_primaryMetric: number;
  bufferoccupancy_secondaryMetric: number;
  bufferoccupancy_baselineAverage: number;
  bufferoccupancy_peakObserved: number;
  bufferoccupancy_standardDeviation: number;
  bufferoccupancy_rawHexSample: string;
  bufferoccupancy_metadataTag: Record<string, string>;
  gtpuerrorcounter_primaryMetric: number;
  gtpuerrorcounter_secondaryMetric: number;
  gtpuerrorcounter_baselineAverage: number;
  gtpuerrorcounter_peakObserved: number;
  gtpuerrorcounter_standardDeviation: number;
  gtpuerrorcounter_rawHexSample: string;
  gtpuerrorcounter_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Core5GUpfMetricsFilterV7 = Partial<Core5GUpfMetricsRecordV7> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Core5GUpfMetricsRecordV8 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  uplinkbytes_primaryMetric: number;
  uplinkbytes_secondaryMetric: number;
  uplinkbytes_baselineAverage: number;
  uplinkbytes_peakObserved: number;
  uplinkbytes_standardDeviation: number;
  uplinkbytes_rawHexSample: string;
  uplinkbytes_metadataTag: Record<string, string>;
  downlinkbytes_primaryMetric: number;
  downlinkbytes_secondaryMetric: number;
  downlinkbytes_baselineAverage: number;
  downlinkbytes_peakObserved: number;
  downlinkbytes_standardDeviation: number;
  downlinkbytes_rawHexSample: string;
  downlinkbytes_metadataTag: Record<string, string>;
  droppedpackets_primaryMetric: number;
  droppedpackets_secondaryMetric: number;
  droppedpackets_baselineAverage: number;
  droppedpackets_peakObserved: number;
  droppedpackets_standardDeviation: number;
  droppedpackets_rawHexSample: string;
  droppedpackets_metadataTag: Record<string, string>;
  bufferoccupancy_primaryMetric: number;
  bufferoccupancy_secondaryMetric: number;
  bufferoccupancy_baselineAverage: number;
  bufferoccupancy_peakObserved: number;
  bufferoccupancy_standardDeviation: number;
  bufferoccupancy_rawHexSample: string;
  bufferoccupancy_metadataTag: Record<string, string>;
  gtpuerrorcounter_primaryMetric: number;
  gtpuerrorcounter_secondaryMetric: number;
  gtpuerrorcounter_baselineAverage: number;
  gtpuerrorcounter_peakObserved: number;
  gtpuerrorcounter_standardDeviation: number;
  gtpuerrorcounter_rawHexSample: string;
  gtpuerrorcounter_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Core5GUpfMetricsFilterV8 = Partial<Core5GUpfMetricsRecordV8> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Core5GUpfMetricsRecordV9 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  uplinkbytes_primaryMetric: number;
  uplinkbytes_secondaryMetric: number;
  uplinkbytes_baselineAverage: number;
  uplinkbytes_peakObserved: number;
  uplinkbytes_standardDeviation: number;
  uplinkbytes_rawHexSample: string;
  uplinkbytes_metadataTag: Record<string, string>;
  downlinkbytes_primaryMetric: number;
  downlinkbytes_secondaryMetric: number;
  downlinkbytes_baselineAverage: number;
  downlinkbytes_peakObserved: number;
  downlinkbytes_standardDeviation: number;
  downlinkbytes_rawHexSample: string;
  downlinkbytes_metadataTag: Record<string, string>;
  droppedpackets_primaryMetric: number;
  droppedpackets_secondaryMetric: number;
  droppedpackets_baselineAverage: number;
  droppedpackets_peakObserved: number;
  droppedpackets_standardDeviation: number;
  droppedpackets_rawHexSample: string;
  droppedpackets_metadataTag: Record<string, string>;
  bufferoccupancy_primaryMetric: number;
  bufferoccupancy_secondaryMetric: number;
  bufferoccupancy_baselineAverage: number;
  bufferoccupancy_peakObserved: number;
  bufferoccupancy_standardDeviation: number;
  bufferoccupancy_rawHexSample: string;
  bufferoccupancy_metadataTag: Record<string, string>;
  gtpuerrorcounter_primaryMetric: number;
  gtpuerrorcounter_secondaryMetric: number;
  gtpuerrorcounter_baselineAverage: number;
  gtpuerrorcounter_peakObserved: number;
  gtpuerrorcounter_standardDeviation: number;
  gtpuerrorcounter_rawHexSample: string;
  gtpuerrorcounter_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Core5GUpfMetricsFilterV9 = Partial<Core5GUpfMetricsRecordV9> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Core5GUpfMetricsRecordV10 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  uplinkbytes_primaryMetric: number;
  uplinkbytes_secondaryMetric: number;
  uplinkbytes_baselineAverage: number;
  uplinkbytes_peakObserved: number;
  uplinkbytes_standardDeviation: number;
  uplinkbytes_rawHexSample: string;
  uplinkbytes_metadataTag: Record<string, string>;
  downlinkbytes_primaryMetric: number;
  downlinkbytes_secondaryMetric: number;
  downlinkbytes_baselineAverage: number;
  downlinkbytes_peakObserved: number;
  downlinkbytes_standardDeviation: number;
  downlinkbytes_rawHexSample: string;
  downlinkbytes_metadataTag: Record<string, string>;
  droppedpackets_primaryMetric: number;
  droppedpackets_secondaryMetric: number;
  droppedpackets_baselineAverage: number;
  droppedpackets_peakObserved: number;
  droppedpackets_standardDeviation: number;
  droppedpackets_rawHexSample: string;
  droppedpackets_metadataTag: Record<string, string>;
  bufferoccupancy_primaryMetric: number;
  bufferoccupancy_secondaryMetric: number;
  bufferoccupancy_baselineAverage: number;
  bufferoccupancy_peakObserved: number;
  bufferoccupancy_standardDeviation: number;
  bufferoccupancy_rawHexSample: string;
  bufferoccupancy_metadataTag: Record<string, string>;
  gtpuerrorcounter_primaryMetric: number;
  gtpuerrorcounter_secondaryMetric: number;
  gtpuerrorcounter_baselineAverage: number;
  gtpuerrorcounter_peakObserved: number;
  gtpuerrorcounter_standardDeviation: number;
  gtpuerrorcounter_rawHexSample: string;
  gtpuerrorcounter_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Core5GUpfMetricsFilterV10 = Partial<Core5GUpfMetricsRecordV10> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Core5GUpfMetricsRecordV11 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  uplinkbytes_primaryMetric: number;
  uplinkbytes_secondaryMetric: number;
  uplinkbytes_baselineAverage: number;
  uplinkbytes_peakObserved: number;
  uplinkbytes_standardDeviation: number;
  uplinkbytes_rawHexSample: string;
  uplinkbytes_metadataTag: Record<string, string>;
  downlinkbytes_primaryMetric: number;
  downlinkbytes_secondaryMetric: number;
  downlinkbytes_baselineAverage: number;
  downlinkbytes_peakObserved: number;
  downlinkbytes_standardDeviation: number;
  downlinkbytes_rawHexSample: string;
  downlinkbytes_metadataTag: Record<string, string>;
  droppedpackets_primaryMetric: number;
  droppedpackets_secondaryMetric: number;
  droppedpackets_baselineAverage: number;
  droppedpackets_peakObserved: number;
  droppedpackets_standardDeviation: number;
  droppedpackets_rawHexSample: string;
  droppedpackets_metadataTag: Record<string, string>;
  bufferoccupancy_primaryMetric: number;
  bufferoccupancy_secondaryMetric: number;
  bufferoccupancy_baselineAverage: number;
  bufferoccupancy_peakObserved: number;
  bufferoccupancy_standardDeviation: number;
  bufferoccupancy_rawHexSample: string;
  bufferoccupancy_metadataTag: Record<string, string>;
  gtpuerrorcounter_primaryMetric: number;
  gtpuerrorcounter_secondaryMetric: number;
  gtpuerrorcounter_baselineAverage: number;
  gtpuerrorcounter_peakObserved: number;
  gtpuerrorcounter_standardDeviation: number;
  gtpuerrorcounter_rawHexSample: string;
  gtpuerrorcounter_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Core5GUpfMetricsFilterV11 = Partial<Core5GUpfMetricsRecordV11> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Core5GUpfMetricsRecordV12 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  uplinkbytes_primaryMetric: number;
  uplinkbytes_secondaryMetric: number;
  uplinkbytes_baselineAverage: number;
  uplinkbytes_peakObserved: number;
  uplinkbytes_standardDeviation: number;
  uplinkbytes_rawHexSample: string;
  uplinkbytes_metadataTag: Record<string, string>;
  downlinkbytes_primaryMetric: number;
  downlinkbytes_secondaryMetric: number;
  downlinkbytes_baselineAverage: number;
  downlinkbytes_peakObserved: number;
  downlinkbytes_standardDeviation: number;
  downlinkbytes_rawHexSample: string;
  downlinkbytes_metadataTag: Record<string, string>;
  droppedpackets_primaryMetric: number;
  droppedpackets_secondaryMetric: number;
  droppedpackets_baselineAverage: number;
  droppedpackets_peakObserved: number;
  droppedpackets_standardDeviation: number;
  droppedpackets_rawHexSample: string;
  droppedpackets_metadataTag: Record<string, string>;
  bufferoccupancy_primaryMetric: number;
  bufferoccupancy_secondaryMetric: number;
  bufferoccupancy_baselineAverage: number;
  bufferoccupancy_peakObserved: number;
  bufferoccupancy_standardDeviation: number;
  bufferoccupancy_rawHexSample: string;
  bufferoccupancy_metadataTag: Record<string, string>;
  gtpuerrorcounter_primaryMetric: number;
  gtpuerrorcounter_secondaryMetric: number;
  gtpuerrorcounter_baselineAverage: number;
  gtpuerrorcounter_peakObserved: number;
  gtpuerrorcounter_standardDeviation: number;
  gtpuerrorcounter_rawHexSample: string;
  gtpuerrorcounter_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Core5GUpfMetricsFilterV12 = Partial<Core5GUpfMetricsRecordV12> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Core5GUpfMetricsRecordV13 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  uplinkbytes_primaryMetric: number;
  uplinkbytes_secondaryMetric: number;
  uplinkbytes_baselineAverage: number;
  uplinkbytes_peakObserved: number;
  uplinkbytes_standardDeviation: number;
  uplinkbytes_rawHexSample: string;
  uplinkbytes_metadataTag: Record<string, string>;
  downlinkbytes_primaryMetric: number;
  downlinkbytes_secondaryMetric: number;
  downlinkbytes_baselineAverage: number;
  downlinkbytes_peakObserved: number;
  downlinkbytes_standardDeviation: number;
  downlinkbytes_rawHexSample: string;
  downlinkbytes_metadataTag: Record<string, string>;
  droppedpackets_primaryMetric: number;
  droppedpackets_secondaryMetric: number;
  droppedpackets_baselineAverage: number;
  droppedpackets_peakObserved: number;
  droppedpackets_standardDeviation: number;
  droppedpackets_rawHexSample: string;
  droppedpackets_metadataTag: Record<string, string>;
  bufferoccupancy_primaryMetric: number;
  bufferoccupancy_secondaryMetric: number;
  bufferoccupancy_baselineAverage: number;
  bufferoccupancy_peakObserved: number;
  bufferoccupancy_standardDeviation: number;
  bufferoccupancy_rawHexSample: string;
  bufferoccupancy_metadataTag: Record<string, string>;
  gtpuerrorcounter_primaryMetric: number;
  gtpuerrorcounter_secondaryMetric: number;
  gtpuerrorcounter_baselineAverage: number;
  gtpuerrorcounter_peakObserved: number;
  gtpuerrorcounter_standardDeviation: number;
  gtpuerrorcounter_rawHexSample: string;
  gtpuerrorcounter_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Core5GUpfMetricsFilterV13 = Partial<Core5GUpfMetricsRecordV13> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Core5GUpfMetricsRecordV14 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  uplinkbytes_primaryMetric: number;
  uplinkbytes_secondaryMetric: number;
  uplinkbytes_baselineAverage: number;
  uplinkbytes_peakObserved: number;
  uplinkbytes_standardDeviation: number;
  uplinkbytes_rawHexSample: string;
  uplinkbytes_metadataTag: Record<string, string>;
  downlinkbytes_primaryMetric: number;
  downlinkbytes_secondaryMetric: number;
  downlinkbytes_baselineAverage: number;
  downlinkbytes_peakObserved: number;
  downlinkbytes_standardDeviation: number;
  downlinkbytes_rawHexSample: string;
  downlinkbytes_metadataTag: Record<string, string>;
  droppedpackets_primaryMetric: number;
  droppedpackets_secondaryMetric: number;
  droppedpackets_baselineAverage: number;
  droppedpackets_peakObserved: number;
  droppedpackets_standardDeviation: number;
  droppedpackets_rawHexSample: string;
  droppedpackets_metadataTag: Record<string, string>;
  bufferoccupancy_primaryMetric: number;
  bufferoccupancy_secondaryMetric: number;
  bufferoccupancy_baselineAverage: number;
  bufferoccupancy_peakObserved: number;
  bufferoccupancy_standardDeviation: number;
  bufferoccupancy_rawHexSample: string;
  bufferoccupancy_metadataTag: Record<string, string>;
  gtpuerrorcounter_primaryMetric: number;
  gtpuerrorcounter_secondaryMetric: number;
  gtpuerrorcounter_baselineAverage: number;
  gtpuerrorcounter_peakObserved: number;
  gtpuerrorcounter_standardDeviation: number;
  gtpuerrorcounter_rawHexSample: string;
  gtpuerrorcounter_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Core5GUpfMetricsFilterV14 = Partial<Core5GUpfMetricsRecordV14> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Core5GUpfMetricsRecordV15 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  uplinkbytes_primaryMetric: number;
  uplinkbytes_secondaryMetric: number;
  uplinkbytes_baselineAverage: number;
  uplinkbytes_peakObserved: number;
  uplinkbytes_standardDeviation: number;
  uplinkbytes_rawHexSample: string;
  uplinkbytes_metadataTag: Record<string, string>;
  downlinkbytes_primaryMetric: number;
  downlinkbytes_secondaryMetric: number;
  downlinkbytes_baselineAverage: number;
  downlinkbytes_peakObserved: number;
  downlinkbytes_standardDeviation: number;
  downlinkbytes_rawHexSample: string;
  downlinkbytes_metadataTag: Record<string, string>;
  droppedpackets_primaryMetric: number;
  droppedpackets_secondaryMetric: number;
  droppedpackets_baselineAverage: number;
  droppedpackets_peakObserved: number;
  droppedpackets_standardDeviation: number;
  droppedpackets_rawHexSample: string;
  droppedpackets_metadataTag: Record<string, string>;
  bufferoccupancy_primaryMetric: number;
  bufferoccupancy_secondaryMetric: number;
  bufferoccupancy_baselineAverage: number;
  bufferoccupancy_peakObserved: number;
  bufferoccupancy_standardDeviation: number;
  bufferoccupancy_rawHexSample: string;
  bufferoccupancy_metadataTag: Record<string, string>;
  gtpuerrorcounter_primaryMetric: number;
  gtpuerrorcounter_secondaryMetric: number;
  gtpuerrorcounter_baselineAverage: number;
  gtpuerrorcounter_peakObserved: number;
  gtpuerrorcounter_standardDeviation: number;
  gtpuerrorcounter_rawHexSample: string;
  gtpuerrorcounter_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Core5GUpfMetricsFilterV15 = Partial<Core5GUpfMetricsRecordV15> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Core5GUpfMetricsRecordV16 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  uplinkbytes_primaryMetric: number;
  uplinkbytes_secondaryMetric: number;
  uplinkbytes_baselineAverage: number;
  uplinkbytes_peakObserved: number;
  uplinkbytes_standardDeviation: number;
  uplinkbytes_rawHexSample: string;
  uplinkbytes_metadataTag: Record<string, string>;
  downlinkbytes_primaryMetric: number;
  downlinkbytes_secondaryMetric: number;
  downlinkbytes_baselineAverage: number;
  downlinkbytes_peakObserved: number;
  downlinkbytes_standardDeviation: number;
  downlinkbytes_rawHexSample: string;
  downlinkbytes_metadataTag: Record<string, string>;
  droppedpackets_primaryMetric: number;
  droppedpackets_secondaryMetric: number;
  droppedpackets_baselineAverage: number;
  droppedpackets_peakObserved: number;
  droppedpackets_standardDeviation: number;
  droppedpackets_rawHexSample: string;
  droppedpackets_metadataTag: Record<string, string>;
  bufferoccupancy_primaryMetric: number;
  bufferoccupancy_secondaryMetric: number;
  bufferoccupancy_baselineAverage: number;
  bufferoccupancy_peakObserved: number;
  bufferoccupancy_standardDeviation: number;
  bufferoccupancy_rawHexSample: string;
  bufferoccupancy_metadataTag: Record<string, string>;
  gtpuerrorcounter_primaryMetric: number;
  gtpuerrorcounter_secondaryMetric: number;
  gtpuerrorcounter_baselineAverage: number;
  gtpuerrorcounter_peakObserved: number;
  gtpuerrorcounter_standardDeviation: number;
  gtpuerrorcounter_rawHexSample: string;
  gtpuerrorcounter_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Core5GUpfMetricsFilterV16 = Partial<Core5GUpfMetricsRecordV16> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Core5GUpfMetricsRecordV17 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  uplinkbytes_primaryMetric: number;
  uplinkbytes_secondaryMetric: number;
  uplinkbytes_baselineAverage: number;
  uplinkbytes_peakObserved: number;
  uplinkbytes_standardDeviation: number;
  uplinkbytes_rawHexSample: string;
  uplinkbytes_metadataTag: Record<string, string>;
  downlinkbytes_primaryMetric: number;
  downlinkbytes_secondaryMetric: number;
  downlinkbytes_baselineAverage: number;
  downlinkbytes_peakObserved: number;
  downlinkbytes_standardDeviation: number;
  downlinkbytes_rawHexSample: string;
  downlinkbytes_metadataTag: Record<string, string>;
  droppedpackets_primaryMetric: number;
  droppedpackets_secondaryMetric: number;
  droppedpackets_baselineAverage: number;
  droppedpackets_peakObserved: number;
  droppedpackets_standardDeviation: number;
  droppedpackets_rawHexSample: string;
  droppedpackets_metadataTag: Record<string, string>;
  bufferoccupancy_primaryMetric: number;
  bufferoccupancy_secondaryMetric: number;
  bufferoccupancy_baselineAverage: number;
  bufferoccupancy_peakObserved: number;
  bufferoccupancy_standardDeviation: number;
  bufferoccupancy_rawHexSample: string;
  bufferoccupancy_metadataTag: Record<string, string>;
  gtpuerrorcounter_primaryMetric: number;
  gtpuerrorcounter_secondaryMetric: number;
  gtpuerrorcounter_baselineAverage: number;
  gtpuerrorcounter_peakObserved: number;
  gtpuerrorcounter_standardDeviation: number;
  gtpuerrorcounter_rawHexSample: string;
  gtpuerrorcounter_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Core5GUpfMetricsFilterV17 = Partial<Core5GUpfMetricsRecordV17> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Core5GUpfMetricsRecordV18 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  uplinkbytes_primaryMetric: number;
  uplinkbytes_secondaryMetric: number;
  uplinkbytes_baselineAverage: number;
  uplinkbytes_peakObserved: number;
  uplinkbytes_standardDeviation: number;
  uplinkbytes_rawHexSample: string;
  uplinkbytes_metadataTag: Record<string, string>;
  downlinkbytes_primaryMetric: number;
  downlinkbytes_secondaryMetric: number;
  downlinkbytes_baselineAverage: number;
  downlinkbytes_peakObserved: number;
  downlinkbytes_standardDeviation: number;
  downlinkbytes_rawHexSample: string;
  downlinkbytes_metadataTag: Record<string, string>;
  droppedpackets_primaryMetric: number;
  droppedpackets_secondaryMetric: number;
  droppedpackets_baselineAverage: number;
  droppedpackets_peakObserved: number;
  droppedpackets_standardDeviation: number;
  droppedpackets_rawHexSample: string;
  droppedpackets_metadataTag: Record<string, string>;
  bufferoccupancy_primaryMetric: number;
  bufferoccupancy_secondaryMetric: number;
  bufferoccupancy_baselineAverage: number;
  bufferoccupancy_peakObserved: number;
  bufferoccupancy_standardDeviation: number;
  bufferoccupancy_rawHexSample: string;
  bufferoccupancy_metadataTag: Record<string, string>;
  gtpuerrorcounter_primaryMetric: number;
  gtpuerrorcounter_secondaryMetric: number;
  gtpuerrorcounter_baselineAverage: number;
  gtpuerrorcounter_peakObserved: number;
  gtpuerrorcounter_standardDeviation: number;
  gtpuerrorcounter_rawHexSample: string;
  gtpuerrorcounter_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Core5GUpfMetricsFilterV18 = Partial<Core5GUpfMetricsRecordV18> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Core5GUpfMetricsRecordV19 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  uplinkbytes_primaryMetric: number;
  uplinkbytes_secondaryMetric: number;
  uplinkbytes_baselineAverage: number;
  uplinkbytes_peakObserved: number;
  uplinkbytes_standardDeviation: number;
  uplinkbytes_rawHexSample: string;
  uplinkbytes_metadataTag: Record<string, string>;
  downlinkbytes_primaryMetric: number;
  downlinkbytes_secondaryMetric: number;
  downlinkbytes_baselineAverage: number;
  downlinkbytes_peakObserved: number;
  downlinkbytes_standardDeviation: number;
  downlinkbytes_rawHexSample: string;
  downlinkbytes_metadataTag: Record<string, string>;
  droppedpackets_primaryMetric: number;
  droppedpackets_secondaryMetric: number;
  droppedpackets_baselineAverage: number;
  droppedpackets_peakObserved: number;
  droppedpackets_standardDeviation: number;
  droppedpackets_rawHexSample: string;
  droppedpackets_metadataTag: Record<string, string>;
  bufferoccupancy_primaryMetric: number;
  bufferoccupancy_secondaryMetric: number;
  bufferoccupancy_baselineAverage: number;
  bufferoccupancy_peakObserved: number;
  bufferoccupancy_standardDeviation: number;
  bufferoccupancy_rawHexSample: string;
  bufferoccupancy_metadataTag: Record<string, string>;
  gtpuerrorcounter_primaryMetric: number;
  gtpuerrorcounter_secondaryMetric: number;
  gtpuerrorcounter_baselineAverage: number;
  gtpuerrorcounter_peakObserved: number;
  gtpuerrorcounter_standardDeviation: number;
  gtpuerrorcounter_rawHexSample: string;
  gtpuerrorcounter_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Core5GUpfMetricsFilterV19 = Partial<Core5GUpfMetricsRecordV19> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Core5GUpfMetricsRecordV20 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  uplinkbytes_primaryMetric: number;
  uplinkbytes_secondaryMetric: number;
  uplinkbytes_baselineAverage: number;
  uplinkbytes_peakObserved: number;
  uplinkbytes_standardDeviation: number;
  uplinkbytes_rawHexSample: string;
  uplinkbytes_metadataTag: Record<string, string>;
  downlinkbytes_primaryMetric: number;
  downlinkbytes_secondaryMetric: number;
  downlinkbytes_baselineAverage: number;
  downlinkbytes_peakObserved: number;
  downlinkbytes_standardDeviation: number;
  downlinkbytes_rawHexSample: string;
  downlinkbytes_metadataTag: Record<string, string>;
  droppedpackets_primaryMetric: number;
  droppedpackets_secondaryMetric: number;
  droppedpackets_baselineAverage: number;
  droppedpackets_peakObserved: number;
  droppedpackets_standardDeviation: number;
  droppedpackets_rawHexSample: string;
  droppedpackets_metadataTag: Record<string, string>;
  bufferoccupancy_primaryMetric: number;
  bufferoccupancy_secondaryMetric: number;
  bufferoccupancy_baselineAverage: number;
  bufferoccupancy_peakObserved: number;
  bufferoccupancy_standardDeviation: number;
  bufferoccupancy_rawHexSample: string;
  bufferoccupancy_metadataTag: Record<string, string>;
  gtpuerrorcounter_primaryMetric: number;
  gtpuerrorcounter_secondaryMetric: number;
  gtpuerrorcounter_baselineAverage: number;
  gtpuerrorcounter_peakObserved: number;
  gtpuerrorcounter_standardDeviation: number;
  gtpuerrorcounter_rawHexSample: string;
  gtpuerrorcounter_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Core5GUpfMetricsFilterV20 = Partial<Core5GUpfMetricsRecordV20> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Core5GUpfMetricsRecordV21 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  uplinkbytes_primaryMetric: number;
  uplinkbytes_secondaryMetric: number;
  uplinkbytes_baselineAverage: number;
  uplinkbytes_peakObserved: number;
  uplinkbytes_standardDeviation: number;
  uplinkbytes_rawHexSample: string;
  uplinkbytes_metadataTag: Record<string, string>;
  downlinkbytes_primaryMetric: number;
  downlinkbytes_secondaryMetric: number;
  downlinkbytes_baselineAverage: number;
  downlinkbytes_peakObserved: number;
  downlinkbytes_standardDeviation: number;
  downlinkbytes_rawHexSample: string;
  downlinkbytes_metadataTag: Record<string, string>;
  droppedpackets_primaryMetric: number;
  droppedpackets_secondaryMetric: number;
  droppedpackets_baselineAverage: number;
  droppedpackets_peakObserved: number;
  droppedpackets_standardDeviation: number;
  droppedpackets_rawHexSample: string;
  droppedpackets_metadataTag: Record<string, string>;
  bufferoccupancy_primaryMetric: number;
  bufferoccupancy_secondaryMetric: number;
  bufferoccupancy_baselineAverage: number;
  bufferoccupancy_peakObserved: number;
  bufferoccupancy_standardDeviation: number;
  bufferoccupancy_rawHexSample: string;
  bufferoccupancy_metadataTag: Record<string, string>;
  gtpuerrorcounter_primaryMetric: number;
  gtpuerrorcounter_secondaryMetric: number;
  gtpuerrorcounter_baselineAverage: number;
  gtpuerrorcounter_peakObserved: number;
  gtpuerrorcounter_standardDeviation: number;
  gtpuerrorcounter_rawHexSample: string;
  gtpuerrorcounter_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Core5GUpfMetricsFilterV21 = Partial<Core5GUpfMetricsRecordV21> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Core5GUpfMetricsRecordV22 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  uplinkbytes_primaryMetric: number;
  uplinkbytes_secondaryMetric: number;
  uplinkbytes_baselineAverage: number;
  uplinkbytes_peakObserved: number;
  uplinkbytes_standardDeviation: number;
  uplinkbytes_rawHexSample: string;
  uplinkbytes_metadataTag: Record<string, string>;
  downlinkbytes_primaryMetric: number;
  downlinkbytes_secondaryMetric: number;
  downlinkbytes_baselineAverage: number;
  downlinkbytes_peakObserved: number;
  downlinkbytes_standardDeviation: number;
  downlinkbytes_rawHexSample: string;
  downlinkbytes_metadataTag: Record<string, string>;
  droppedpackets_primaryMetric: number;
  droppedpackets_secondaryMetric: number;
  droppedpackets_baselineAverage: number;
  droppedpackets_peakObserved: number;
  droppedpackets_standardDeviation: number;
  droppedpackets_rawHexSample: string;
  droppedpackets_metadataTag: Record<string, string>;
  bufferoccupancy_primaryMetric: number;
  bufferoccupancy_secondaryMetric: number;
  bufferoccupancy_baselineAverage: number;
  bufferoccupancy_peakObserved: number;
  bufferoccupancy_standardDeviation: number;
  bufferoccupancy_rawHexSample: string;
  bufferoccupancy_metadataTag: Record<string, string>;
  gtpuerrorcounter_primaryMetric: number;
  gtpuerrorcounter_secondaryMetric: number;
  gtpuerrorcounter_baselineAverage: number;
  gtpuerrorcounter_peakObserved: number;
  gtpuerrorcounter_standardDeviation: number;
  gtpuerrorcounter_rawHexSample: string;
  gtpuerrorcounter_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Core5GUpfMetricsFilterV22 = Partial<Core5GUpfMetricsRecordV22> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Core5GUpfMetricsRecordV23 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  uplinkbytes_primaryMetric: number;
  uplinkbytes_secondaryMetric: number;
  uplinkbytes_baselineAverage: number;
  uplinkbytes_peakObserved: number;
  uplinkbytes_standardDeviation: number;
  uplinkbytes_rawHexSample: string;
  uplinkbytes_metadataTag: Record<string, string>;
  downlinkbytes_primaryMetric: number;
  downlinkbytes_secondaryMetric: number;
  downlinkbytes_baselineAverage: number;
  downlinkbytes_peakObserved: number;
  downlinkbytes_standardDeviation: number;
  downlinkbytes_rawHexSample: string;
  downlinkbytes_metadataTag: Record<string, string>;
  droppedpackets_primaryMetric: number;
  droppedpackets_secondaryMetric: number;
  droppedpackets_baselineAverage: number;
  droppedpackets_peakObserved: number;
  droppedpackets_standardDeviation: number;
  droppedpackets_rawHexSample: string;
  droppedpackets_metadataTag: Record<string, string>;
  bufferoccupancy_primaryMetric: number;
  bufferoccupancy_secondaryMetric: number;
  bufferoccupancy_baselineAverage: number;
  bufferoccupancy_peakObserved: number;
  bufferoccupancy_standardDeviation: number;
  bufferoccupancy_rawHexSample: string;
  bufferoccupancy_metadataTag: Record<string, string>;
  gtpuerrorcounter_primaryMetric: number;
  gtpuerrorcounter_secondaryMetric: number;
  gtpuerrorcounter_baselineAverage: number;
  gtpuerrorcounter_peakObserved: number;
  gtpuerrorcounter_standardDeviation: number;
  gtpuerrorcounter_rawHexSample: string;
  gtpuerrorcounter_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Core5GUpfMetricsFilterV23 = Partial<Core5GUpfMetricsRecordV23> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Core5GUpfMetricsRecordV24 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  uplinkbytes_primaryMetric: number;
  uplinkbytes_secondaryMetric: number;
  uplinkbytes_baselineAverage: number;
  uplinkbytes_peakObserved: number;
  uplinkbytes_standardDeviation: number;
  uplinkbytes_rawHexSample: string;
  uplinkbytes_metadataTag: Record<string, string>;
  downlinkbytes_primaryMetric: number;
  downlinkbytes_secondaryMetric: number;
  downlinkbytes_baselineAverage: number;
  downlinkbytes_peakObserved: number;
  downlinkbytes_standardDeviation: number;
  downlinkbytes_rawHexSample: string;
  downlinkbytes_metadataTag: Record<string, string>;
  droppedpackets_primaryMetric: number;
  droppedpackets_secondaryMetric: number;
  droppedpackets_baselineAverage: number;
  droppedpackets_peakObserved: number;
  droppedpackets_standardDeviation: number;
  droppedpackets_rawHexSample: string;
  droppedpackets_metadataTag: Record<string, string>;
  bufferoccupancy_primaryMetric: number;
  bufferoccupancy_secondaryMetric: number;
  bufferoccupancy_baselineAverage: number;
  bufferoccupancy_peakObserved: number;
  bufferoccupancy_standardDeviation: number;
  bufferoccupancy_rawHexSample: string;
  bufferoccupancy_metadataTag: Record<string, string>;
  gtpuerrorcounter_primaryMetric: number;
  gtpuerrorcounter_secondaryMetric: number;
  gtpuerrorcounter_baselineAverage: number;
  gtpuerrorcounter_peakObserved: number;
  gtpuerrorcounter_standardDeviation: number;
  gtpuerrorcounter_rawHexSample: string;
  gtpuerrorcounter_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Core5GUpfMetricsFilterV24 = Partial<Core5GUpfMetricsRecordV24> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Core5GUpfMetricsRecordV25 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  uplinkbytes_primaryMetric: number;
  uplinkbytes_secondaryMetric: number;
  uplinkbytes_baselineAverage: number;
  uplinkbytes_peakObserved: number;
  uplinkbytes_standardDeviation: number;
  uplinkbytes_rawHexSample: string;
  uplinkbytes_metadataTag: Record<string, string>;
  downlinkbytes_primaryMetric: number;
  downlinkbytes_secondaryMetric: number;
  downlinkbytes_baselineAverage: number;
  downlinkbytes_peakObserved: number;
  downlinkbytes_standardDeviation: number;
  downlinkbytes_rawHexSample: string;
  downlinkbytes_metadataTag: Record<string, string>;
  droppedpackets_primaryMetric: number;
  droppedpackets_secondaryMetric: number;
  droppedpackets_baselineAverage: number;
  droppedpackets_peakObserved: number;
  droppedpackets_standardDeviation: number;
  droppedpackets_rawHexSample: string;
  droppedpackets_metadataTag: Record<string, string>;
  bufferoccupancy_primaryMetric: number;
  bufferoccupancy_secondaryMetric: number;
  bufferoccupancy_baselineAverage: number;
  bufferoccupancy_peakObserved: number;
  bufferoccupancy_standardDeviation: number;
  bufferoccupancy_rawHexSample: string;
  bufferoccupancy_metadataTag: Record<string, string>;
  gtpuerrorcounter_primaryMetric: number;
  gtpuerrorcounter_secondaryMetric: number;
  gtpuerrorcounter_baselineAverage: number;
  gtpuerrorcounter_peakObserved: number;
  gtpuerrorcounter_standardDeviation: number;
  gtpuerrorcounter_rawHexSample: string;
  gtpuerrorcounter_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Core5GUpfMetricsFilterV25 = Partial<Core5GUpfMetricsRecordV25> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Core5GUpfMetricsRecordV26 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  uplinkbytes_primaryMetric: number;
  uplinkbytes_secondaryMetric: number;
  uplinkbytes_baselineAverage: number;
  uplinkbytes_peakObserved: number;
  uplinkbytes_standardDeviation: number;
  uplinkbytes_rawHexSample: string;
  uplinkbytes_metadataTag: Record<string, string>;
  downlinkbytes_primaryMetric: number;
  downlinkbytes_secondaryMetric: number;
  downlinkbytes_baselineAverage: number;
  downlinkbytes_peakObserved: number;
  downlinkbytes_standardDeviation: number;
  downlinkbytes_rawHexSample: string;
  downlinkbytes_metadataTag: Record<string, string>;
  droppedpackets_primaryMetric: number;
  droppedpackets_secondaryMetric: number;
  droppedpackets_baselineAverage: number;
  droppedpackets_peakObserved: number;
  droppedpackets_standardDeviation: number;
  droppedpackets_rawHexSample: string;
  droppedpackets_metadataTag: Record<string, string>;
  bufferoccupancy_primaryMetric: number;
  bufferoccupancy_secondaryMetric: number;
  bufferoccupancy_baselineAverage: number;
  bufferoccupancy_peakObserved: number;
  bufferoccupancy_standardDeviation: number;
  bufferoccupancy_rawHexSample: string;
  bufferoccupancy_metadataTag: Record<string, string>;
  gtpuerrorcounter_primaryMetric: number;
  gtpuerrorcounter_secondaryMetric: number;
  gtpuerrorcounter_baselineAverage: number;
  gtpuerrorcounter_peakObserved: number;
  gtpuerrorcounter_standardDeviation: number;
  gtpuerrorcounter_rawHexSample: string;
  gtpuerrorcounter_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Core5GUpfMetricsFilterV26 = Partial<Core5GUpfMetricsRecordV26> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Core5GUpfMetricsRecordV27 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  uplinkbytes_primaryMetric: number;
  uplinkbytes_secondaryMetric: number;
  uplinkbytes_baselineAverage: number;
  uplinkbytes_peakObserved: number;
  uplinkbytes_standardDeviation: number;
  uplinkbytes_rawHexSample: string;
  uplinkbytes_metadataTag: Record<string, string>;
  downlinkbytes_primaryMetric: number;
  downlinkbytes_secondaryMetric: number;
  downlinkbytes_baselineAverage: number;
  downlinkbytes_peakObserved: number;
  downlinkbytes_standardDeviation: number;
  downlinkbytes_rawHexSample: string;
  downlinkbytes_metadataTag: Record<string, string>;
  droppedpackets_primaryMetric: number;
  droppedpackets_secondaryMetric: number;
  droppedpackets_baselineAverage: number;
  droppedpackets_peakObserved: number;
  droppedpackets_standardDeviation: number;
  droppedpackets_rawHexSample: string;
  droppedpackets_metadataTag: Record<string, string>;
  bufferoccupancy_primaryMetric: number;
  bufferoccupancy_secondaryMetric: number;
  bufferoccupancy_baselineAverage: number;
  bufferoccupancy_peakObserved: number;
  bufferoccupancy_standardDeviation: number;
  bufferoccupancy_rawHexSample: string;
  bufferoccupancy_metadataTag: Record<string, string>;
  gtpuerrorcounter_primaryMetric: number;
  gtpuerrorcounter_secondaryMetric: number;
  gtpuerrorcounter_baselineAverage: number;
  gtpuerrorcounter_peakObserved: number;
  gtpuerrorcounter_standardDeviation: number;
  gtpuerrorcounter_rawHexSample: string;
  gtpuerrorcounter_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Core5GUpfMetricsFilterV27 = Partial<Core5GUpfMetricsRecordV27> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Core5GUpfMetricsRecordV28 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  uplinkbytes_primaryMetric: number;
  uplinkbytes_secondaryMetric: number;
  uplinkbytes_baselineAverage: number;
  uplinkbytes_peakObserved: number;
  uplinkbytes_standardDeviation: number;
  uplinkbytes_rawHexSample: string;
  uplinkbytes_metadataTag: Record<string, string>;
  downlinkbytes_primaryMetric: number;
  downlinkbytes_secondaryMetric: number;
  downlinkbytes_baselineAverage: number;
  downlinkbytes_peakObserved: number;
  downlinkbytes_standardDeviation: number;
  downlinkbytes_rawHexSample: string;
  downlinkbytes_metadataTag: Record<string, string>;
  droppedpackets_primaryMetric: number;
  droppedpackets_secondaryMetric: number;
  droppedpackets_baselineAverage: number;
  droppedpackets_peakObserved: number;
  droppedpackets_standardDeviation: number;
  droppedpackets_rawHexSample: string;
  droppedpackets_metadataTag: Record<string, string>;
  bufferoccupancy_primaryMetric: number;
  bufferoccupancy_secondaryMetric: number;
  bufferoccupancy_baselineAverage: number;
  bufferoccupancy_peakObserved: number;
  bufferoccupancy_standardDeviation: number;
  bufferoccupancy_rawHexSample: string;
  bufferoccupancy_metadataTag: Record<string, string>;
  gtpuerrorcounter_primaryMetric: number;
  gtpuerrorcounter_secondaryMetric: number;
  gtpuerrorcounter_baselineAverage: number;
  gtpuerrorcounter_peakObserved: number;
  gtpuerrorcounter_standardDeviation: number;
  gtpuerrorcounter_rawHexSample: string;
  gtpuerrorcounter_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Core5GUpfMetricsFilterV28 = Partial<Core5GUpfMetricsRecordV28> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Core5GUpfMetricsRecordV29 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  uplinkbytes_primaryMetric: number;
  uplinkbytes_secondaryMetric: number;
  uplinkbytes_baselineAverage: number;
  uplinkbytes_peakObserved: number;
  uplinkbytes_standardDeviation: number;
  uplinkbytes_rawHexSample: string;
  uplinkbytes_metadataTag: Record<string, string>;
  downlinkbytes_primaryMetric: number;
  downlinkbytes_secondaryMetric: number;
  downlinkbytes_baselineAverage: number;
  downlinkbytes_peakObserved: number;
  downlinkbytes_standardDeviation: number;
  downlinkbytes_rawHexSample: string;
  downlinkbytes_metadataTag: Record<string, string>;
  droppedpackets_primaryMetric: number;
  droppedpackets_secondaryMetric: number;
  droppedpackets_baselineAverage: number;
  droppedpackets_peakObserved: number;
  droppedpackets_standardDeviation: number;
  droppedpackets_rawHexSample: string;
  droppedpackets_metadataTag: Record<string, string>;
  bufferoccupancy_primaryMetric: number;
  bufferoccupancy_secondaryMetric: number;
  bufferoccupancy_baselineAverage: number;
  bufferoccupancy_peakObserved: number;
  bufferoccupancy_standardDeviation: number;
  bufferoccupancy_rawHexSample: string;
  bufferoccupancy_metadataTag: Record<string, string>;
  gtpuerrorcounter_primaryMetric: number;
  gtpuerrorcounter_secondaryMetric: number;
  gtpuerrorcounter_baselineAverage: number;
  gtpuerrorcounter_peakObserved: number;
  gtpuerrorcounter_standardDeviation: number;
  gtpuerrorcounter_rawHexSample: string;
  gtpuerrorcounter_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Core5GUpfMetricsFilterV29 = Partial<Core5GUpfMetricsRecordV29> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Core5GUpfMetricsRecordV30 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  uplinkbytes_primaryMetric: number;
  uplinkbytes_secondaryMetric: number;
  uplinkbytes_baselineAverage: number;
  uplinkbytes_peakObserved: number;
  uplinkbytes_standardDeviation: number;
  uplinkbytes_rawHexSample: string;
  uplinkbytes_metadataTag: Record<string, string>;
  downlinkbytes_primaryMetric: number;
  downlinkbytes_secondaryMetric: number;
  downlinkbytes_baselineAverage: number;
  downlinkbytes_peakObserved: number;
  downlinkbytes_standardDeviation: number;
  downlinkbytes_rawHexSample: string;
  downlinkbytes_metadataTag: Record<string, string>;
  droppedpackets_primaryMetric: number;
  droppedpackets_secondaryMetric: number;
  droppedpackets_baselineAverage: number;
  droppedpackets_peakObserved: number;
  droppedpackets_standardDeviation: number;
  droppedpackets_rawHexSample: string;
  droppedpackets_metadataTag: Record<string, string>;
  bufferoccupancy_primaryMetric: number;
  bufferoccupancy_secondaryMetric: number;
  bufferoccupancy_baselineAverage: number;
  bufferoccupancy_peakObserved: number;
  bufferoccupancy_standardDeviation: number;
  bufferoccupancy_rawHexSample: string;
  bufferoccupancy_metadataTag: Record<string, string>;
  gtpuerrorcounter_primaryMetric: number;
  gtpuerrorcounter_secondaryMetric: number;
  gtpuerrorcounter_baselineAverage: number;
  gtpuerrorcounter_peakObserved: number;
  gtpuerrorcounter_standardDeviation: number;
  gtpuerrorcounter_rawHexSample: string;
  gtpuerrorcounter_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Core5GUpfMetricsFilterV30 = Partial<Core5GUpfMetricsRecordV30> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Core5GUpfMetricsRecordV31 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  uplinkbytes_primaryMetric: number;
  uplinkbytes_secondaryMetric: number;
  uplinkbytes_baselineAverage: number;
  uplinkbytes_peakObserved: number;
  uplinkbytes_standardDeviation: number;
  uplinkbytes_rawHexSample: string;
  uplinkbytes_metadataTag: Record<string, string>;
  downlinkbytes_primaryMetric: number;
  downlinkbytes_secondaryMetric: number;
  downlinkbytes_baselineAverage: number;
  downlinkbytes_peakObserved: number;
  downlinkbytes_standardDeviation: number;
  downlinkbytes_rawHexSample: string;
  downlinkbytes_metadataTag: Record<string, string>;
  droppedpackets_primaryMetric: number;
  droppedpackets_secondaryMetric: number;
  droppedpackets_baselineAverage: number;
  droppedpackets_peakObserved: number;
  droppedpackets_standardDeviation: number;
  droppedpackets_rawHexSample: string;
  droppedpackets_metadataTag: Record<string, string>;
  bufferoccupancy_primaryMetric: number;
  bufferoccupancy_secondaryMetric: number;
  bufferoccupancy_baselineAverage: number;
  bufferoccupancy_peakObserved: number;
  bufferoccupancy_standardDeviation: number;
  bufferoccupancy_rawHexSample: string;
  bufferoccupancy_metadataTag: Record<string, string>;
  gtpuerrorcounter_primaryMetric: number;
  gtpuerrorcounter_secondaryMetric: number;
  gtpuerrorcounter_baselineAverage: number;
  gtpuerrorcounter_peakObserved: number;
  gtpuerrorcounter_standardDeviation: number;
  gtpuerrorcounter_rawHexSample: string;
  gtpuerrorcounter_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Core5GUpfMetricsFilterV31 = Partial<Core5GUpfMetricsRecordV31> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Core5GUpfMetricsRecordV32 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  uplinkbytes_primaryMetric: number;
  uplinkbytes_secondaryMetric: number;
  uplinkbytes_baselineAverage: number;
  uplinkbytes_peakObserved: number;
  uplinkbytes_standardDeviation: number;
  uplinkbytes_rawHexSample: string;
  uplinkbytes_metadataTag: Record<string, string>;
  downlinkbytes_primaryMetric: number;
  downlinkbytes_secondaryMetric: number;
  downlinkbytes_baselineAverage: number;
  downlinkbytes_peakObserved: number;
  downlinkbytes_standardDeviation: number;
  downlinkbytes_rawHexSample: string;
  downlinkbytes_metadataTag: Record<string, string>;
  droppedpackets_primaryMetric: number;
  droppedpackets_secondaryMetric: number;
  droppedpackets_baselineAverage: number;
  droppedpackets_peakObserved: number;
  droppedpackets_standardDeviation: number;
  droppedpackets_rawHexSample: string;
  droppedpackets_metadataTag: Record<string, string>;
  bufferoccupancy_primaryMetric: number;
  bufferoccupancy_secondaryMetric: number;
  bufferoccupancy_baselineAverage: number;
  bufferoccupancy_peakObserved: number;
  bufferoccupancy_standardDeviation: number;
  bufferoccupancy_rawHexSample: string;
  bufferoccupancy_metadataTag: Record<string, string>;
  gtpuerrorcounter_primaryMetric: number;
  gtpuerrorcounter_secondaryMetric: number;
  gtpuerrorcounter_baselineAverage: number;
  gtpuerrorcounter_peakObserved: number;
  gtpuerrorcounter_standardDeviation: number;
  gtpuerrorcounter_rawHexSample: string;
  gtpuerrorcounter_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Core5GUpfMetricsFilterV32 = Partial<Core5GUpfMetricsRecordV32> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Core5GUpfMetricsRecordV33 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  uplinkbytes_primaryMetric: number;
  uplinkbytes_secondaryMetric: number;
  uplinkbytes_baselineAverage: number;
  uplinkbytes_peakObserved: number;
  uplinkbytes_standardDeviation: number;
  uplinkbytes_rawHexSample: string;
  uplinkbytes_metadataTag: Record<string, string>;
  downlinkbytes_primaryMetric: number;
  downlinkbytes_secondaryMetric: number;
  downlinkbytes_baselineAverage: number;
  downlinkbytes_peakObserved: number;
  downlinkbytes_standardDeviation: number;
  downlinkbytes_rawHexSample: string;
  downlinkbytes_metadataTag: Record<string, string>;
  droppedpackets_primaryMetric: number;
  droppedpackets_secondaryMetric: number;
  droppedpackets_baselineAverage: number;
  droppedpackets_peakObserved: number;
  droppedpackets_standardDeviation: number;
  droppedpackets_rawHexSample: string;
  droppedpackets_metadataTag: Record<string, string>;
  bufferoccupancy_primaryMetric: number;
  bufferoccupancy_secondaryMetric: number;
  bufferoccupancy_baselineAverage: number;
  bufferoccupancy_peakObserved: number;
  bufferoccupancy_standardDeviation: number;
  bufferoccupancy_rawHexSample: string;
  bufferoccupancy_metadataTag: Record<string, string>;
  gtpuerrorcounter_primaryMetric: number;
  gtpuerrorcounter_secondaryMetric: number;
  gtpuerrorcounter_baselineAverage: number;
  gtpuerrorcounter_peakObserved: number;
  gtpuerrorcounter_standardDeviation: number;
  gtpuerrorcounter_rawHexSample: string;
  gtpuerrorcounter_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Core5GUpfMetricsFilterV33 = Partial<Core5GUpfMetricsRecordV33> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Core5GUpfMetricsRecordV34 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  uplinkbytes_primaryMetric: number;
  uplinkbytes_secondaryMetric: number;
  uplinkbytes_baselineAverage: number;
  uplinkbytes_peakObserved: number;
  uplinkbytes_standardDeviation: number;
  uplinkbytes_rawHexSample: string;
  uplinkbytes_metadataTag: Record<string, string>;
  downlinkbytes_primaryMetric: number;
  downlinkbytes_secondaryMetric: number;
  downlinkbytes_baselineAverage: number;
  downlinkbytes_peakObserved: number;
  downlinkbytes_standardDeviation: number;
  downlinkbytes_rawHexSample: string;
  downlinkbytes_metadataTag: Record<string, string>;
  droppedpackets_primaryMetric: number;
  droppedpackets_secondaryMetric: number;
  droppedpackets_baselineAverage: number;
  droppedpackets_peakObserved: number;
  droppedpackets_standardDeviation: number;
  droppedpackets_rawHexSample: string;
  droppedpackets_metadataTag: Record<string, string>;
  bufferoccupancy_primaryMetric: number;
  bufferoccupancy_secondaryMetric: number;
  bufferoccupancy_baselineAverage: number;
  bufferoccupancy_peakObserved: number;
  bufferoccupancy_standardDeviation: number;
  bufferoccupancy_rawHexSample: string;
  bufferoccupancy_metadataTag: Record<string, string>;
  gtpuerrorcounter_primaryMetric: number;
  gtpuerrorcounter_secondaryMetric: number;
  gtpuerrorcounter_baselineAverage: number;
  gtpuerrorcounter_peakObserved: number;
  gtpuerrorcounter_standardDeviation: number;
  gtpuerrorcounter_rawHexSample: string;
  gtpuerrorcounter_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Core5GUpfMetricsFilterV34 = Partial<Core5GUpfMetricsRecordV34> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Core5GUpfMetricsRecordV35 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  uplinkbytes_primaryMetric: number;
  uplinkbytes_secondaryMetric: number;
  uplinkbytes_baselineAverage: number;
  uplinkbytes_peakObserved: number;
  uplinkbytes_standardDeviation: number;
  uplinkbytes_rawHexSample: string;
  uplinkbytes_metadataTag: Record<string, string>;
  downlinkbytes_primaryMetric: number;
  downlinkbytes_secondaryMetric: number;
  downlinkbytes_baselineAverage: number;
  downlinkbytes_peakObserved: number;
  downlinkbytes_standardDeviation: number;
  downlinkbytes_rawHexSample: string;
  downlinkbytes_metadataTag: Record<string, string>;
  droppedpackets_primaryMetric: number;
  droppedpackets_secondaryMetric: number;
  droppedpackets_baselineAverage: number;
  droppedpackets_peakObserved: number;
  droppedpackets_standardDeviation: number;
  droppedpackets_rawHexSample: string;
  droppedpackets_metadataTag: Record<string, string>;
  bufferoccupancy_primaryMetric: number;
  bufferoccupancy_secondaryMetric: number;
  bufferoccupancy_baselineAverage: number;
  bufferoccupancy_peakObserved: number;
  bufferoccupancy_standardDeviation: number;
  bufferoccupancy_rawHexSample: string;
  bufferoccupancy_metadataTag: Record<string, string>;
  gtpuerrorcounter_primaryMetric: number;
  gtpuerrorcounter_secondaryMetric: number;
  gtpuerrorcounter_baselineAverage: number;
  gtpuerrorcounter_peakObserved: number;
  gtpuerrorcounter_standardDeviation: number;
  gtpuerrorcounter_rawHexSample: string;
  gtpuerrorcounter_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Core5GUpfMetricsFilterV35 = Partial<Core5GUpfMetricsRecordV35> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Core5GUpfMetricsRecordV36 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  uplinkbytes_primaryMetric: number;
  uplinkbytes_secondaryMetric: number;
  uplinkbytes_baselineAverage: number;
  uplinkbytes_peakObserved: number;
  uplinkbytes_standardDeviation: number;
  uplinkbytes_rawHexSample: string;
  uplinkbytes_metadataTag: Record<string, string>;
  downlinkbytes_primaryMetric: number;
  downlinkbytes_secondaryMetric: number;
  downlinkbytes_baselineAverage: number;
  downlinkbytes_peakObserved: number;
  downlinkbytes_standardDeviation: number;
  downlinkbytes_rawHexSample: string;
  downlinkbytes_metadataTag: Record<string, string>;
  droppedpackets_primaryMetric: number;
  droppedpackets_secondaryMetric: number;
  droppedpackets_baselineAverage: number;
  droppedpackets_peakObserved: number;
  droppedpackets_standardDeviation: number;
  droppedpackets_rawHexSample: string;
  droppedpackets_metadataTag: Record<string, string>;
  bufferoccupancy_primaryMetric: number;
  bufferoccupancy_secondaryMetric: number;
  bufferoccupancy_baselineAverage: number;
  bufferoccupancy_peakObserved: number;
  bufferoccupancy_standardDeviation: number;
  bufferoccupancy_rawHexSample: string;
  bufferoccupancy_metadataTag: Record<string, string>;
  gtpuerrorcounter_primaryMetric: number;
  gtpuerrorcounter_secondaryMetric: number;
  gtpuerrorcounter_baselineAverage: number;
  gtpuerrorcounter_peakObserved: number;
  gtpuerrorcounter_standardDeviation: number;
  gtpuerrorcounter_rawHexSample: string;
  gtpuerrorcounter_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Core5GUpfMetricsFilterV36 = Partial<Core5GUpfMetricsRecordV36> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Core5GUpfMetricsRecordV37 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  uplinkbytes_primaryMetric: number;
  uplinkbytes_secondaryMetric: number;
  uplinkbytes_baselineAverage: number;
  uplinkbytes_peakObserved: number;
  uplinkbytes_standardDeviation: number;
  uplinkbytes_rawHexSample: string;
  uplinkbytes_metadataTag: Record<string, string>;
  downlinkbytes_primaryMetric: number;
  downlinkbytes_secondaryMetric: number;
  downlinkbytes_baselineAverage: number;
  downlinkbytes_peakObserved: number;
  downlinkbytes_standardDeviation: number;
  downlinkbytes_rawHexSample: string;
  downlinkbytes_metadataTag: Record<string, string>;
  droppedpackets_primaryMetric: number;
  droppedpackets_secondaryMetric: number;
  droppedpackets_baselineAverage: number;
  droppedpackets_peakObserved: number;
  droppedpackets_standardDeviation: number;
  droppedpackets_rawHexSample: string;
  droppedpackets_metadataTag: Record<string, string>;
  bufferoccupancy_primaryMetric: number;
  bufferoccupancy_secondaryMetric: number;
  bufferoccupancy_baselineAverage: number;
  bufferoccupancy_peakObserved: number;
  bufferoccupancy_standardDeviation: number;
  bufferoccupancy_rawHexSample: string;
  bufferoccupancy_metadataTag: Record<string, string>;
  gtpuerrorcounter_primaryMetric: number;
  gtpuerrorcounter_secondaryMetric: number;
  gtpuerrorcounter_baselineAverage: number;
  gtpuerrorcounter_peakObserved: number;
  gtpuerrorcounter_standardDeviation: number;
  gtpuerrorcounter_rawHexSample: string;
  gtpuerrorcounter_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Core5GUpfMetricsFilterV37 = Partial<Core5GUpfMetricsRecordV37> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Core5GUpfMetricsRecordV38 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  uplinkbytes_primaryMetric: number;
  uplinkbytes_secondaryMetric: number;
  uplinkbytes_baselineAverage: number;
  uplinkbytes_peakObserved: number;
  uplinkbytes_standardDeviation: number;
  uplinkbytes_rawHexSample: string;
  uplinkbytes_metadataTag: Record<string, string>;
  downlinkbytes_primaryMetric: number;
  downlinkbytes_secondaryMetric: number;
  downlinkbytes_baselineAverage: number;
  downlinkbytes_peakObserved: number;
  downlinkbytes_standardDeviation: number;
  downlinkbytes_rawHexSample: string;
  downlinkbytes_metadataTag: Record<string, string>;
  droppedpackets_primaryMetric: number;
  droppedpackets_secondaryMetric: number;
  droppedpackets_baselineAverage: number;
  droppedpackets_peakObserved: number;
  droppedpackets_standardDeviation: number;
  droppedpackets_rawHexSample: string;
  droppedpackets_metadataTag: Record<string, string>;
  bufferoccupancy_primaryMetric: number;
  bufferoccupancy_secondaryMetric: number;
  bufferoccupancy_baselineAverage: number;
  bufferoccupancy_peakObserved: number;
  bufferoccupancy_standardDeviation: number;
  bufferoccupancy_rawHexSample: string;
  bufferoccupancy_metadataTag: Record<string, string>;
  gtpuerrorcounter_primaryMetric: number;
  gtpuerrorcounter_secondaryMetric: number;
  gtpuerrorcounter_baselineAverage: number;
  gtpuerrorcounter_peakObserved: number;
  gtpuerrorcounter_standardDeviation: number;
  gtpuerrorcounter_rawHexSample: string;
  gtpuerrorcounter_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Core5GUpfMetricsFilterV38 = Partial<Core5GUpfMetricsRecordV38> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Core5GUpfMetricsRecordV39 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  uplinkbytes_primaryMetric: number;
  uplinkbytes_secondaryMetric: number;
  uplinkbytes_baselineAverage: number;
  uplinkbytes_peakObserved: number;
  uplinkbytes_standardDeviation: number;
  uplinkbytes_rawHexSample: string;
  uplinkbytes_metadataTag: Record<string, string>;
  downlinkbytes_primaryMetric: number;
  downlinkbytes_secondaryMetric: number;
  downlinkbytes_baselineAverage: number;
  downlinkbytes_peakObserved: number;
  downlinkbytes_standardDeviation: number;
  downlinkbytes_rawHexSample: string;
  downlinkbytes_metadataTag: Record<string, string>;
  droppedpackets_primaryMetric: number;
  droppedpackets_secondaryMetric: number;
  droppedpackets_baselineAverage: number;
  droppedpackets_peakObserved: number;
  droppedpackets_standardDeviation: number;
  droppedpackets_rawHexSample: string;
  droppedpackets_metadataTag: Record<string, string>;
  bufferoccupancy_primaryMetric: number;
  bufferoccupancy_secondaryMetric: number;
  bufferoccupancy_baselineAverage: number;
  bufferoccupancy_peakObserved: number;
  bufferoccupancy_standardDeviation: number;
  bufferoccupancy_rawHexSample: string;
  bufferoccupancy_metadataTag: Record<string, string>;
  gtpuerrorcounter_primaryMetric: number;
  gtpuerrorcounter_secondaryMetric: number;
  gtpuerrorcounter_baselineAverage: number;
  gtpuerrorcounter_peakObserved: number;
  gtpuerrorcounter_standardDeviation: number;
  gtpuerrorcounter_rawHexSample: string;
  gtpuerrorcounter_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Core5GUpfMetricsFilterV39 = Partial<Core5GUpfMetricsRecordV39> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Core5GUpfMetricsRecordV40 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  uplinkbytes_primaryMetric: number;
  uplinkbytes_secondaryMetric: number;
  uplinkbytes_baselineAverage: number;
  uplinkbytes_peakObserved: number;
  uplinkbytes_standardDeviation: number;
  uplinkbytes_rawHexSample: string;
  uplinkbytes_metadataTag: Record<string, string>;
  downlinkbytes_primaryMetric: number;
  downlinkbytes_secondaryMetric: number;
  downlinkbytes_baselineAverage: number;
  downlinkbytes_peakObserved: number;
  downlinkbytes_standardDeviation: number;
  downlinkbytes_rawHexSample: string;
  downlinkbytes_metadataTag: Record<string, string>;
  droppedpackets_primaryMetric: number;
  droppedpackets_secondaryMetric: number;
  droppedpackets_baselineAverage: number;
  droppedpackets_peakObserved: number;
  droppedpackets_standardDeviation: number;
  droppedpackets_rawHexSample: string;
  droppedpackets_metadataTag: Record<string, string>;
  bufferoccupancy_primaryMetric: number;
  bufferoccupancy_secondaryMetric: number;
  bufferoccupancy_baselineAverage: number;
  bufferoccupancy_peakObserved: number;
  bufferoccupancy_standardDeviation: number;
  bufferoccupancy_rawHexSample: string;
  bufferoccupancy_metadataTag: Record<string, string>;
  gtpuerrorcounter_primaryMetric: number;
  gtpuerrorcounter_secondaryMetric: number;
  gtpuerrorcounter_baselineAverage: number;
  gtpuerrorcounter_peakObserved: number;
  gtpuerrorcounter_standardDeviation: number;
  gtpuerrorcounter_rawHexSample: string;
  gtpuerrorcounter_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Core5GUpfMetricsFilterV40 = Partial<Core5GUpfMetricsRecordV40> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};
