/**
 * Enterprise Telecommunications Protocol Specification: 5G Core AMF and SMF Session Management Telemetry
 * Module: @geonet/types/telecom/core_5g_amf_smf
 * Standard Compliance: 3GPP TS 38.401, IETF RFC Standards, ITU-T G.8032
 */

export interface 5GCoreAMFandSMFSessionManagementTelemetryConfig {
  samplingIntervalMs: number;
  collectionEnabled: boolean;
  highWatermarkThreshold: number;
  lowWatermarkThreshold: number;
  retryAttempts: number;
  timeoutMs: number;
}

export interface Core5GAmfSmfRecordV1 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  sessionid_primaryMetric: number;
  sessionid_secondaryMetric: number;
  sessionid_baselineAverage: number;
  sessionid_peakObserved: number;
  sessionid_standardDeviation: number;
  sessionid_rawHexSample: string;
  sessionid_metadataTag: Record<string, string>;
  pduaddress_primaryMetric: number;
  pduaddress_secondaryMetric: number;
  pduaddress_baselineAverage: number;
  pduaddress_peakObserved: number;
  pduaddress_standardDeviation: number;
  pduaddress_rawHexSample: string;
  pduaddress_metadataTag: Record<string, string>;
  qosflow_primaryMetric: number;
  qosflow_secondaryMetric: number;
  qosflow_baselineAverage: number;
  qosflow_peakObserved: number;
  qosflow_standardDeviation: number;
  qosflow_rawHexSample: string;
  qosflow_metadataTag: Record<string, string>;
  tunnelendpointidentifier_primaryMetric: number;
  tunnelendpointidentifier_secondaryMetric: number;
  tunnelendpointidentifier_baselineAverage: number;
  tunnelendpointidentifier_peakObserved: number;
  tunnelendpointidentifier_standardDeviation: number;
  tunnelendpointidentifier_rawHexSample: string;
  tunnelendpointidentifier_metadataTag: Record<string, string>;
  chargingprofile_primaryMetric: number;
  chargingprofile_secondaryMetric: number;
  chargingprofile_baselineAverage: number;
  chargingprofile_peakObserved: number;
  chargingprofile_standardDeviation: number;
  chargingprofile_rawHexSample: string;
  chargingprofile_metadataTag: Record<string, string>;
  policyrules_primaryMetric: number;
  policyrules_secondaryMetric: number;
  policyrules_baselineAverage: number;
  policyrules_peakObserved: number;
  policyrules_standardDeviation: number;
  policyrules_rawHexSample: string;
  policyrules_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Core5GAmfSmfFilterV1 = Partial<Core5GAmfSmfRecordV1> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Core5GAmfSmfRecordV2 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  sessionid_primaryMetric: number;
  sessionid_secondaryMetric: number;
  sessionid_baselineAverage: number;
  sessionid_peakObserved: number;
  sessionid_standardDeviation: number;
  sessionid_rawHexSample: string;
  sessionid_metadataTag: Record<string, string>;
  pduaddress_primaryMetric: number;
  pduaddress_secondaryMetric: number;
  pduaddress_baselineAverage: number;
  pduaddress_peakObserved: number;
  pduaddress_standardDeviation: number;
  pduaddress_rawHexSample: string;
  pduaddress_metadataTag: Record<string, string>;
  qosflow_primaryMetric: number;
  qosflow_secondaryMetric: number;
  qosflow_baselineAverage: number;
  qosflow_peakObserved: number;
  qosflow_standardDeviation: number;
  qosflow_rawHexSample: string;
  qosflow_metadataTag: Record<string, string>;
  tunnelendpointidentifier_primaryMetric: number;
  tunnelendpointidentifier_secondaryMetric: number;
  tunnelendpointidentifier_baselineAverage: number;
  tunnelendpointidentifier_peakObserved: number;
  tunnelendpointidentifier_standardDeviation: number;
  tunnelendpointidentifier_rawHexSample: string;
  tunnelendpointidentifier_metadataTag: Record<string, string>;
  chargingprofile_primaryMetric: number;
  chargingprofile_secondaryMetric: number;
  chargingprofile_baselineAverage: number;
  chargingprofile_peakObserved: number;
  chargingprofile_standardDeviation: number;
  chargingprofile_rawHexSample: string;
  chargingprofile_metadataTag: Record<string, string>;
  policyrules_primaryMetric: number;
  policyrules_secondaryMetric: number;
  policyrules_baselineAverage: number;
  policyrules_peakObserved: number;
  policyrules_standardDeviation: number;
  policyrules_rawHexSample: string;
  policyrules_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Core5GAmfSmfFilterV2 = Partial<Core5GAmfSmfRecordV2> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Core5GAmfSmfRecordV3 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  sessionid_primaryMetric: number;
  sessionid_secondaryMetric: number;
  sessionid_baselineAverage: number;
  sessionid_peakObserved: number;
  sessionid_standardDeviation: number;
  sessionid_rawHexSample: string;
  sessionid_metadataTag: Record<string, string>;
  pduaddress_primaryMetric: number;
  pduaddress_secondaryMetric: number;
  pduaddress_baselineAverage: number;
  pduaddress_peakObserved: number;
  pduaddress_standardDeviation: number;
  pduaddress_rawHexSample: string;
  pduaddress_metadataTag: Record<string, string>;
  qosflow_primaryMetric: number;
  qosflow_secondaryMetric: number;
  qosflow_baselineAverage: number;
  qosflow_peakObserved: number;
  qosflow_standardDeviation: number;
  qosflow_rawHexSample: string;
  qosflow_metadataTag: Record<string, string>;
  tunnelendpointidentifier_primaryMetric: number;
  tunnelendpointidentifier_secondaryMetric: number;
  tunnelendpointidentifier_baselineAverage: number;
  tunnelendpointidentifier_peakObserved: number;
  tunnelendpointidentifier_standardDeviation: number;
  tunnelendpointidentifier_rawHexSample: string;
  tunnelendpointidentifier_metadataTag: Record<string, string>;
  chargingprofile_primaryMetric: number;
  chargingprofile_secondaryMetric: number;
  chargingprofile_baselineAverage: number;
  chargingprofile_peakObserved: number;
  chargingprofile_standardDeviation: number;
  chargingprofile_rawHexSample: string;
  chargingprofile_metadataTag: Record<string, string>;
  policyrules_primaryMetric: number;
  policyrules_secondaryMetric: number;
  policyrules_baselineAverage: number;
  policyrules_peakObserved: number;
  policyrules_standardDeviation: number;
  policyrules_rawHexSample: string;
  policyrules_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Core5GAmfSmfFilterV3 = Partial<Core5GAmfSmfRecordV3> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Core5GAmfSmfRecordV4 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  sessionid_primaryMetric: number;
  sessionid_secondaryMetric: number;
  sessionid_baselineAverage: number;
  sessionid_peakObserved: number;
  sessionid_standardDeviation: number;
  sessionid_rawHexSample: string;
  sessionid_metadataTag: Record<string, string>;
  pduaddress_primaryMetric: number;
  pduaddress_secondaryMetric: number;
  pduaddress_baselineAverage: number;
  pduaddress_peakObserved: number;
  pduaddress_standardDeviation: number;
  pduaddress_rawHexSample: string;
  pduaddress_metadataTag: Record<string, string>;
  qosflow_primaryMetric: number;
  qosflow_secondaryMetric: number;
  qosflow_baselineAverage: number;
  qosflow_peakObserved: number;
  qosflow_standardDeviation: number;
  qosflow_rawHexSample: string;
  qosflow_metadataTag: Record<string, string>;
  tunnelendpointidentifier_primaryMetric: number;
  tunnelendpointidentifier_secondaryMetric: number;
  tunnelendpointidentifier_baselineAverage: number;
  tunnelendpointidentifier_peakObserved: number;
  tunnelendpointidentifier_standardDeviation: number;
  tunnelendpointidentifier_rawHexSample: string;
  tunnelendpointidentifier_metadataTag: Record<string, string>;
  chargingprofile_primaryMetric: number;
  chargingprofile_secondaryMetric: number;
  chargingprofile_baselineAverage: number;
  chargingprofile_peakObserved: number;
  chargingprofile_standardDeviation: number;
  chargingprofile_rawHexSample: string;
  chargingprofile_metadataTag: Record<string, string>;
  policyrules_primaryMetric: number;
  policyrules_secondaryMetric: number;
  policyrules_baselineAverage: number;
  policyrules_peakObserved: number;
  policyrules_standardDeviation: number;
  policyrules_rawHexSample: string;
  policyrules_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Core5GAmfSmfFilterV4 = Partial<Core5GAmfSmfRecordV4> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Core5GAmfSmfRecordV5 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  sessionid_primaryMetric: number;
  sessionid_secondaryMetric: number;
  sessionid_baselineAverage: number;
  sessionid_peakObserved: number;
  sessionid_standardDeviation: number;
  sessionid_rawHexSample: string;
  sessionid_metadataTag: Record<string, string>;
  pduaddress_primaryMetric: number;
  pduaddress_secondaryMetric: number;
  pduaddress_baselineAverage: number;
  pduaddress_peakObserved: number;
  pduaddress_standardDeviation: number;
  pduaddress_rawHexSample: string;
  pduaddress_metadataTag: Record<string, string>;
  qosflow_primaryMetric: number;
  qosflow_secondaryMetric: number;
  qosflow_baselineAverage: number;
  qosflow_peakObserved: number;
  qosflow_standardDeviation: number;
  qosflow_rawHexSample: string;
  qosflow_metadataTag: Record<string, string>;
  tunnelendpointidentifier_primaryMetric: number;
  tunnelendpointidentifier_secondaryMetric: number;
  tunnelendpointidentifier_baselineAverage: number;
  tunnelendpointidentifier_peakObserved: number;
  tunnelendpointidentifier_standardDeviation: number;
  tunnelendpointidentifier_rawHexSample: string;
  tunnelendpointidentifier_metadataTag: Record<string, string>;
  chargingprofile_primaryMetric: number;
  chargingprofile_secondaryMetric: number;
  chargingprofile_baselineAverage: number;
  chargingprofile_peakObserved: number;
  chargingprofile_standardDeviation: number;
  chargingprofile_rawHexSample: string;
  chargingprofile_metadataTag: Record<string, string>;
  policyrules_primaryMetric: number;
  policyrules_secondaryMetric: number;
  policyrules_baselineAverage: number;
  policyrules_peakObserved: number;
  policyrules_standardDeviation: number;
  policyrules_rawHexSample: string;
  policyrules_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Core5GAmfSmfFilterV5 = Partial<Core5GAmfSmfRecordV5> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Core5GAmfSmfRecordV6 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  sessionid_primaryMetric: number;
  sessionid_secondaryMetric: number;
  sessionid_baselineAverage: number;
  sessionid_peakObserved: number;
  sessionid_standardDeviation: number;
  sessionid_rawHexSample: string;
  sessionid_metadataTag: Record<string, string>;
  pduaddress_primaryMetric: number;
  pduaddress_secondaryMetric: number;
  pduaddress_baselineAverage: number;
  pduaddress_peakObserved: number;
  pduaddress_standardDeviation: number;
  pduaddress_rawHexSample: string;
  pduaddress_metadataTag: Record<string, string>;
  qosflow_primaryMetric: number;
  qosflow_secondaryMetric: number;
  qosflow_baselineAverage: number;
  qosflow_peakObserved: number;
  qosflow_standardDeviation: number;
  qosflow_rawHexSample: string;
  qosflow_metadataTag: Record<string, string>;
  tunnelendpointidentifier_primaryMetric: number;
  tunnelendpointidentifier_secondaryMetric: number;
  tunnelendpointidentifier_baselineAverage: number;
  tunnelendpointidentifier_peakObserved: number;
  tunnelendpointidentifier_standardDeviation: number;
  tunnelendpointidentifier_rawHexSample: string;
  tunnelendpointidentifier_metadataTag: Record<string, string>;
  chargingprofile_primaryMetric: number;
  chargingprofile_secondaryMetric: number;
  chargingprofile_baselineAverage: number;
  chargingprofile_peakObserved: number;
  chargingprofile_standardDeviation: number;
  chargingprofile_rawHexSample: string;
  chargingprofile_metadataTag: Record<string, string>;
  policyrules_primaryMetric: number;
  policyrules_secondaryMetric: number;
  policyrules_baselineAverage: number;
  policyrules_peakObserved: number;
  policyrules_standardDeviation: number;
  policyrules_rawHexSample: string;
  policyrules_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Core5GAmfSmfFilterV6 = Partial<Core5GAmfSmfRecordV6> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Core5GAmfSmfRecordV7 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  sessionid_primaryMetric: number;
  sessionid_secondaryMetric: number;
  sessionid_baselineAverage: number;
  sessionid_peakObserved: number;
  sessionid_standardDeviation: number;
  sessionid_rawHexSample: string;
  sessionid_metadataTag: Record<string, string>;
  pduaddress_primaryMetric: number;
  pduaddress_secondaryMetric: number;
  pduaddress_baselineAverage: number;
  pduaddress_peakObserved: number;
  pduaddress_standardDeviation: number;
  pduaddress_rawHexSample: string;
  pduaddress_metadataTag: Record<string, string>;
  qosflow_primaryMetric: number;
  qosflow_secondaryMetric: number;
  qosflow_baselineAverage: number;
  qosflow_peakObserved: number;
  qosflow_standardDeviation: number;
  qosflow_rawHexSample: string;
  qosflow_metadataTag: Record<string, string>;
  tunnelendpointidentifier_primaryMetric: number;
  tunnelendpointidentifier_secondaryMetric: number;
  tunnelendpointidentifier_baselineAverage: number;
  tunnelendpointidentifier_peakObserved: number;
  tunnelendpointidentifier_standardDeviation: number;
  tunnelendpointidentifier_rawHexSample: string;
  tunnelendpointidentifier_metadataTag: Record<string, string>;
  chargingprofile_primaryMetric: number;
  chargingprofile_secondaryMetric: number;
  chargingprofile_baselineAverage: number;
  chargingprofile_peakObserved: number;
  chargingprofile_standardDeviation: number;
  chargingprofile_rawHexSample: string;
  chargingprofile_metadataTag: Record<string, string>;
  policyrules_primaryMetric: number;
  policyrules_secondaryMetric: number;
  policyrules_baselineAverage: number;
  policyrules_peakObserved: number;
  policyrules_standardDeviation: number;
  policyrules_rawHexSample: string;
  policyrules_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Core5GAmfSmfFilterV7 = Partial<Core5GAmfSmfRecordV7> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Core5GAmfSmfRecordV8 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  sessionid_primaryMetric: number;
  sessionid_secondaryMetric: number;
  sessionid_baselineAverage: number;
  sessionid_peakObserved: number;
  sessionid_standardDeviation: number;
  sessionid_rawHexSample: string;
  sessionid_metadataTag: Record<string, string>;
  pduaddress_primaryMetric: number;
  pduaddress_secondaryMetric: number;
  pduaddress_baselineAverage: number;
  pduaddress_peakObserved: number;
  pduaddress_standardDeviation: number;
  pduaddress_rawHexSample: string;
  pduaddress_metadataTag: Record<string, string>;
  qosflow_primaryMetric: number;
  qosflow_secondaryMetric: number;
  qosflow_baselineAverage: number;
  qosflow_peakObserved: number;
  qosflow_standardDeviation: number;
  qosflow_rawHexSample: string;
  qosflow_metadataTag: Record<string, string>;
  tunnelendpointidentifier_primaryMetric: number;
  tunnelendpointidentifier_secondaryMetric: number;
  tunnelendpointidentifier_baselineAverage: number;
  tunnelendpointidentifier_peakObserved: number;
  tunnelendpointidentifier_standardDeviation: number;
  tunnelendpointidentifier_rawHexSample: string;
  tunnelendpointidentifier_metadataTag: Record<string, string>;
  chargingprofile_primaryMetric: number;
  chargingprofile_secondaryMetric: number;
  chargingprofile_baselineAverage: number;
  chargingprofile_peakObserved: number;
  chargingprofile_standardDeviation: number;
  chargingprofile_rawHexSample: string;
  chargingprofile_metadataTag: Record<string, string>;
  policyrules_primaryMetric: number;
  policyrules_secondaryMetric: number;
  policyrules_baselineAverage: number;
  policyrules_peakObserved: number;
  policyrules_standardDeviation: number;
  policyrules_rawHexSample: string;
  policyrules_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Core5GAmfSmfFilterV8 = Partial<Core5GAmfSmfRecordV8> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Core5GAmfSmfRecordV9 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  sessionid_primaryMetric: number;
  sessionid_secondaryMetric: number;
  sessionid_baselineAverage: number;
  sessionid_peakObserved: number;
  sessionid_standardDeviation: number;
  sessionid_rawHexSample: string;
  sessionid_metadataTag: Record<string, string>;
  pduaddress_primaryMetric: number;
  pduaddress_secondaryMetric: number;
  pduaddress_baselineAverage: number;
  pduaddress_peakObserved: number;
  pduaddress_standardDeviation: number;
  pduaddress_rawHexSample: string;
  pduaddress_metadataTag: Record<string, string>;
  qosflow_primaryMetric: number;
  qosflow_secondaryMetric: number;
  qosflow_baselineAverage: number;
  qosflow_peakObserved: number;
  qosflow_standardDeviation: number;
  qosflow_rawHexSample: string;
  qosflow_metadataTag: Record<string, string>;
  tunnelendpointidentifier_primaryMetric: number;
  tunnelendpointidentifier_secondaryMetric: number;
  tunnelendpointidentifier_baselineAverage: number;
  tunnelendpointidentifier_peakObserved: number;
  tunnelendpointidentifier_standardDeviation: number;
  tunnelendpointidentifier_rawHexSample: string;
  tunnelendpointidentifier_metadataTag: Record<string, string>;
  chargingprofile_primaryMetric: number;
  chargingprofile_secondaryMetric: number;
  chargingprofile_baselineAverage: number;
  chargingprofile_peakObserved: number;
  chargingprofile_standardDeviation: number;
  chargingprofile_rawHexSample: string;
  chargingprofile_metadataTag: Record<string, string>;
  policyrules_primaryMetric: number;
  policyrules_secondaryMetric: number;
  policyrules_baselineAverage: number;
  policyrules_peakObserved: number;
  policyrules_standardDeviation: number;
  policyrules_rawHexSample: string;
  policyrules_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Core5GAmfSmfFilterV9 = Partial<Core5GAmfSmfRecordV9> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Core5GAmfSmfRecordV10 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  sessionid_primaryMetric: number;
  sessionid_secondaryMetric: number;
  sessionid_baselineAverage: number;
  sessionid_peakObserved: number;
  sessionid_standardDeviation: number;
  sessionid_rawHexSample: string;
  sessionid_metadataTag: Record<string, string>;
  pduaddress_primaryMetric: number;
  pduaddress_secondaryMetric: number;
  pduaddress_baselineAverage: number;
  pduaddress_peakObserved: number;
  pduaddress_standardDeviation: number;
  pduaddress_rawHexSample: string;
  pduaddress_metadataTag: Record<string, string>;
  qosflow_primaryMetric: number;
  qosflow_secondaryMetric: number;
  qosflow_baselineAverage: number;
  qosflow_peakObserved: number;
  qosflow_standardDeviation: number;
  qosflow_rawHexSample: string;
  qosflow_metadataTag: Record<string, string>;
  tunnelendpointidentifier_primaryMetric: number;
  tunnelendpointidentifier_secondaryMetric: number;
  tunnelendpointidentifier_baselineAverage: number;
  tunnelendpointidentifier_peakObserved: number;
  tunnelendpointidentifier_standardDeviation: number;
  tunnelendpointidentifier_rawHexSample: string;
  tunnelendpointidentifier_metadataTag: Record<string, string>;
  chargingprofile_primaryMetric: number;
  chargingprofile_secondaryMetric: number;
  chargingprofile_baselineAverage: number;
  chargingprofile_peakObserved: number;
  chargingprofile_standardDeviation: number;
  chargingprofile_rawHexSample: string;
  chargingprofile_metadataTag: Record<string, string>;
  policyrules_primaryMetric: number;
  policyrules_secondaryMetric: number;
  policyrules_baselineAverage: number;
  policyrules_peakObserved: number;
  policyrules_standardDeviation: number;
  policyrules_rawHexSample: string;
  policyrules_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Core5GAmfSmfFilterV10 = Partial<Core5GAmfSmfRecordV10> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Core5GAmfSmfRecordV11 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  sessionid_primaryMetric: number;
  sessionid_secondaryMetric: number;
  sessionid_baselineAverage: number;
  sessionid_peakObserved: number;
  sessionid_standardDeviation: number;
  sessionid_rawHexSample: string;
  sessionid_metadataTag: Record<string, string>;
  pduaddress_primaryMetric: number;
  pduaddress_secondaryMetric: number;
  pduaddress_baselineAverage: number;
  pduaddress_peakObserved: number;
  pduaddress_standardDeviation: number;
  pduaddress_rawHexSample: string;
  pduaddress_metadataTag: Record<string, string>;
  qosflow_primaryMetric: number;
  qosflow_secondaryMetric: number;
  qosflow_baselineAverage: number;
  qosflow_peakObserved: number;
  qosflow_standardDeviation: number;
  qosflow_rawHexSample: string;
  qosflow_metadataTag: Record<string, string>;
  tunnelendpointidentifier_primaryMetric: number;
  tunnelendpointidentifier_secondaryMetric: number;
  tunnelendpointidentifier_baselineAverage: number;
  tunnelendpointidentifier_peakObserved: number;
  tunnelendpointidentifier_standardDeviation: number;
  tunnelendpointidentifier_rawHexSample: string;
  tunnelendpointidentifier_metadataTag: Record<string, string>;
  chargingprofile_primaryMetric: number;
  chargingprofile_secondaryMetric: number;
  chargingprofile_baselineAverage: number;
  chargingprofile_peakObserved: number;
  chargingprofile_standardDeviation: number;
  chargingprofile_rawHexSample: string;
  chargingprofile_metadataTag: Record<string, string>;
  policyrules_primaryMetric: number;
  policyrules_secondaryMetric: number;
  policyrules_baselineAverage: number;
  policyrules_peakObserved: number;
  policyrules_standardDeviation: number;
  policyrules_rawHexSample: string;
  policyrules_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Core5GAmfSmfFilterV11 = Partial<Core5GAmfSmfRecordV11> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Core5GAmfSmfRecordV12 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  sessionid_primaryMetric: number;
  sessionid_secondaryMetric: number;
  sessionid_baselineAverage: number;
  sessionid_peakObserved: number;
  sessionid_standardDeviation: number;
  sessionid_rawHexSample: string;
  sessionid_metadataTag: Record<string, string>;
  pduaddress_primaryMetric: number;
  pduaddress_secondaryMetric: number;
  pduaddress_baselineAverage: number;
  pduaddress_peakObserved: number;
  pduaddress_standardDeviation: number;
  pduaddress_rawHexSample: string;
  pduaddress_metadataTag: Record<string, string>;
  qosflow_primaryMetric: number;
  qosflow_secondaryMetric: number;
  qosflow_baselineAverage: number;
  qosflow_peakObserved: number;
  qosflow_standardDeviation: number;
  qosflow_rawHexSample: string;
  qosflow_metadataTag: Record<string, string>;
  tunnelendpointidentifier_primaryMetric: number;
  tunnelendpointidentifier_secondaryMetric: number;
  tunnelendpointidentifier_baselineAverage: number;
  tunnelendpointidentifier_peakObserved: number;
  tunnelendpointidentifier_standardDeviation: number;
  tunnelendpointidentifier_rawHexSample: string;
  tunnelendpointidentifier_metadataTag: Record<string, string>;
  chargingprofile_primaryMetric: number;
  chargingprofile_secondaryMetric: number;
  chargingprofile_baselineAverage: number;
  chargingprofile_peakObserved: number;
  chargingprofile_standardDeviation: number;
  chargingprofile_rawHexSample: string;
  chargingprofile_metadataTag: Record<string, string>;
  policyrules_primaryMetric: number;
  policyrules_secondaryMetric: number;
  policyrules_baselineAverage: number;
  policyrules_peakObserved: number;
  policyrules_standardDeviation: number;
  policyrules_rawHexSample: string;
  policyrules_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Core5GAmfSmfFilterV12 = Partial<Core5GAmfSmfRecordV12> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Core5GAmfSmfRecordV13 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  sessionid_primaryMetric: number;
  sessionid_secondaryMetric: number;
  sessionid_baselineAverage: number;
  sessionid_peakObserved: number;
  sessionid_standardDeviation: number;
  sessionid_rawHexSample: string;
  sessionid_metadataTag: Record<string, string>;
  pduaddress_primaryMetric: number;
  pduaddress_secondaryMetric: number;
  pduaddress_baselineAverage: number;
  pduaddress_peakObserved: number;
  pduaddress_standardDeviation: number;
  pduaddress_rawHexSample: string;
  pduaddress_metadataTag: Record<string, string>;
  qosflow_primaryMetric: number;
  qosflow_secondaryMetric: number;
  qosflow_baselineAverage: number;
  qosflow_peakObserved: number;
  qosflow_standardDeviation: number;
  qosflow_rawHexSample: string;
  qosflow_metadataTag: Record<string, string>;
  tunnelendpointidentifier_primaryMetric: number;
  tunnelendpointidentifier_secondaryMetric: number;
  tunnelendpointidentifier_baselineAverage: number;
  tunnelendpointidentifier_peakObserved: number;
  tunnelendpointidentifier_standardDeviation: number;
  tunnelendpointidentifier_rawHexSample: string;
  tunnelendpointidentifier_metadataTag: Record<string, string>;
  chargingprofile_primaryMetric: number;
  chargingprofile_secondaryMetric: number;
  chargingprofile_baselineAverage: number;
  chargingprofile_peakObserved: number;
  chargingprofile_standardDeviation: number;
  chargingprofile_rawHexSample: string;
  chargingprofile_metadataTag: Record<string, string>;
  policyrules_primaryMetric: number;
  policyrules_secondaryMetric: number;
  policyrules_baselineAverage: number;
  policyrules_peakObserved: number;
  policyrules_standardDeviation: number;
  policyrules_rawHexSample: string;
  policyrules_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Core5GAmfSmfFilterV13 = Partial<Core5GAmfSmfRecordV13> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Core5GAmfSmfRecordV14 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  sessionid_primaryMetric: number;
  sessionid_secondaryMetric: number;
  sessionid_baselineAverage: number;
  sessionid_peakObserved: number;
  sessionid_standardDeviation: number;
  sessionid_rawHexSample: string;
  sessionid_metadataTag: Record<string, string>;
  pduaddress_primaryMetric: number;
  pduaddress_secondaryMetric: number;
  pduaddress_baselineAverage: number;
  pduaddress_peakObserved: number;
  pduaddress_standardDeviation: number;
  pduaddress_rawHexSample: string;
  pduaddress_metadataTag: Record<string, string>;
  qosflow_primaryMetric: number;
  qosflow_secondaryMetric: number;
  qosflow_baselineAverage: number;
  qosflow_peakObserved: number;
  qosflow_standardDeviation: number;
  qosflow_rawHexSample: string;
  qosflow_metadataTag: Record<string, string>;
  tunnelendpointidentifier_primaryMetric: number;
  tunnelendpointidentifier_secondaryMetric: number;
  tunnelendpointidentifier_baselineAverage: number;
  tunnelendpointidentifier_peakObserved: number;
  tunnelendpointidentifier_standardDeviation: number;
  tunnelendpointidentifier_rawHexSample: string;
  tunnelendpointidentifier_metadataTag: Record<string, string>;
  chargingprofile_primaryMetric: number;
  chargingprofile_secondaryMetric: number;
  chargingprofile_baselineAverage: number;
  chargingprofile_peakObserved: number;
  chargingprofile_standardDeviation: number;
  chargingprofile_rawHexSample: string;
  chargingprofile_metadataTag: Record<string, string>;
  policyrules_primaryMetric: number;
  policyrules_secondaryMetric: number;
  policyrules_baselineAverage: number;
  policyrules_peakObserved: number;
  policyrules_standardDeviation: number;
  policyrules_rawHexSample: string;
  policyrules_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Core5GAmfSmfFilterV14 = Partial<Core5GAmfSmfRecordV14> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Core5GAmfSmfRecordV15 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  sessionid_primaryMetric: number;
  sessionid_secondaryMetric: number;
  sessionid_baselineAverage: number;
  sessionid_peakObserved: number;
  sessionid_standardDeviation: number;
  sessionid_rawHexSample: string;
  sessionid_metadataTag: Record<string, string>;
  pduaddress_primaryMetric: number;
  pduaddress_secondaryMetric: number;
  pduaddress_baselineAverage: number;
  pduaddress_peakObserved: number;
  pduaddress_standardDeviation: number;
  pduaddress_rawHexSample: string;
  pduaddress_metadataTag: Record<string, string>;
  qosflow_primaryMetric: number;
  qosflow_secondaryMetric: number;
  qosflow_baselineAverage: number;
  qosflow_peakObserved: number;
  qosflow_standardDeviation: number;
  qosflow_rawHexSample: string;
  qosflow_metadataTag: Record<string, string>;
  tunnelendpointidentifier_primaryMetric: number;
  tunnelendpointidentifier_secondaryMetric: number;
  tunnelendpointidentifier_baselineAverage: number;
  tunnelendpointidentifier_peakObserved: number;
  tunnelendpointidentifier_standardDeviation: number;
  tunnelendpointidentifier_rawHexSample: string;
  tunnelendpointidentifier_metadataTag: Record<string, string>;
  chargingprofile_primaryMetric: number;
  chargingprofile_secondaryMetric: number;
  chargingprofile_baselineAverage: number;
  chargingprofile_peakObserved: number;
  chargingprofile_standardDeviation: number;
  chargingprofile_rawHexSample: string;
  chargingprofile_metadataTag: Record<string, string>;
  policyrules_primaryMetric: number;
  policyrules_secondaryMetric: number;
  policyrules_baselineAverage: number;
  policyrules_peakObserved: number;
  policyrules_standardDeviation: number;
  policyrules_rawHexSample: string;
  policyrules_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Core5GAmfSmfFilterV15 = Partial<Core5GAmfSmfRecordV15> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Core5GAmfSmfRecordV16 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  sessionid_primaryMetric: number;
  sessionid_secondaryMetric: number;
  sessionid_baselineAverage: number;
  sessionid_peakObserved: number;
  sessionid_standardDeviation: number;
  sessionid_rawHexSample: string;
  sessionid_metadataTag: Record<string, string>;
  pduaddress_primaryMetric: number;
  pduaddress_secondaryMetric: number;
  pduaddress_baselineAverage: number;
  pduaddress_peakObserved: number;
  pduaddress_standardDeviation: number;
  pduaddress_rawHexSample: string;
  pduaddress_metadataTag: Record<string, string>;
  qosflow_primaryMetric: number;
  qosflow_secondaryMetric: number;
  qosflow_baselineAverage: number;
  qosflow_peakObserved: number;
  qosflow_standardDeviation: number;
  qosflow_rawHexSample: string;
  qosflow_metadataTag: Record<string, string>;
  tunnelendpointidentifier_primaryMetric: number;
  tunnelendpointidentifier_secondaryMetric: number;
  tunnelendpointidentifier_baselineAverage: number;
  tunnelendpointidentifier_peakObserved: number;
  tunnelendpointidentifier_standardDeviation: number;
  tunnelendpointidentifier_rawHexSample: string;
  tunnelendpointidentifier_metadataTag: Record<string, string>;
  chargingprofile_primaryMetric: number;
  chargingprofile_secondaryMetric: number;
  chargingprofile_baselineAverage: number;
  chargingprofile_peakObserved: number;
  chargingprofile_standardDeviation: number;
  chargingprofile_rawHexSample: string;
  chargingprofile_metadataTag: Record<string, string>;
  policyrules_primaryMetric: number;
  policyrules_secondaryMetric: number;
  policyrules_baselineAverage: number;
  policyrules_peakObserved: number;
  policyrules_standardDeviation: number;
  policyrules_rawHexSample: string;
  policyrules_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Core5GAmfSmfFilterV16 = Partial<Core5GAmfSmfRecordV16> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Core5GAmfSmfRecordV17 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  sessionid_primaryMetric: number;
  sessionid_secondaryMetric: number;
  sessionid_baselineAverage: number;
  sessionid_peakObserved: number;
  sessionid_standardDeviation: number;
  sessionid_rawHexSample: string;
  sessionid_metadataTag: Record<string, string>;
  pduaddress_primaryMetric: number;
  pduaddress_secondaryMetric: number;
  pduaddress_baselineAverage: number;
  pduaddress_peakObserved: number;
  pduaddress_standardDeviation: number;
  pduaddress_rawHexSample: string;
  pduaddress_metadataTag: Record<string, string>;
  qosflow_primaryMetric: number;
  qosflow_secondaryMetric: number;
  qosflow_baselineAverage: number;
  qosflow_peakObserved: number;
  qosflow_standardDeviation: number;
  qosflow_rawHexSample: string;
  qosflow_metadataTag: Record<string, string>;
  tunnelendpointidentifier_primaryMetric: number;
  tunnelendpointidentifier_secondaryMetric: number;
  tunnelendpointidentifier_baselineAverage: number;
  tunnelendpointidentifier_peakObserved: number;
  tunnelendpointidentifier_standardDeviation: number;
  tunnelendpointidentifier_rawHexSample: string;
  tunnelendpointidentifier_metadataTag: Record<string, string>;
  chargingprofile_primaryMetric: number;
  chargingprofile_secondaryMetric: number;
  chargingprofile_baselineAverage: number;
  chargingprofile_peakObserved: number;
  chargingprofile_standardDeviation: number;
  chargingprofile_rawHexSample: string;
  chargingprofile_metadataTag: Record<string, string>;
  policyrules_primaryMetric: number;
  policyrules_secondaryMetric: number;
  policyrules_baselineAverage: number;
  policyrules_peakObserved: number;
  policyrules_standardDeviation: number;
  policyrules_rawHexSample: string;
  policyrules_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Core5GAmfSmfFilterV17 = Partial<Core5GAmfSmfRecordV17> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Core5GAmfSmfRecordV18 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  sessionid_primaryMetric: number;
  sessionid_secondaryMetric: number;
  sessionid_baselineAverage: number;
  sessionid_peakObserved: number;
  sessionid_standardDeviation: number;
  sessionid_rawHexSample: string;
  sessionid_metadataTag: Record<string, string>;
  pduaddress_primaryMetric: number;
  pduaddress_secondaryMetric: number;
  pduaddress_baselineAverage: number;
  pduaddress_peakObserved: number;
  pduaddress_standardDeviation: number;
  pduaddress_rawHexSample: string;
  pduaddress_metadataTag: Record<string, string>;
  qosflow_primaryMetric: number;
  qosflow_secondaryMetric: number;
  qosflow_baselineAverage: number;
  qosflow_peakObserved: number;
  qosflow_standardDeviation: number;
  qosflow_rawHexSample: string;
  qosflow_metadataTag: Record<string, string>;
  tunnelendpointidentifier_primaryMetric: number;
  tunnelendpointidentifier_secondaryMetric: number;
  tunnelendpointidentifier_baselineAverage: number;
  tunnelendpointidentifier_peakObserved: number;
  tunnelendpointidentifier_standardDeviation: number;
  tunnelendpointidentifier_rawHexSample: string;
  tunnelendpointidentifier_metadataTag: Record<string, string>;
  chargingprofile_primaryMetric: number;
  chargingprofile_secondaryMetric: number;
  chargingprofile_baselineAverage: number;
  chargingprofile_peakObserved: number;
  chargingprofile_standardDeviation: number;
  chargingprofile_rawHexSample: string;
  chargingprofile_metadataTag: Record<string, string>;
  policyrules_primaryMetric: number;
  policyrules_secondaryMetric: number;
  policyrules_baselineAverage: number;
  policyrules_peakObserved: number;
  policyrules_standardDeviation: number;
  policyrules_rawHexSample: string;
  policyrules_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Core5GAmfSmfFilterV18 = Partial<Core5GAmfSmfRecordV18> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Core5GAmfSmfRecordV19 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  sessionid_primaryMetric: number;
  sessionid_secondaryMetric: number;
  sessionid_baselineAverage: number;
  sessionid_peakObserved: number;
  sessionid_standardDeviation: number;
  sessionid_rawHexSample: string;
  sessionid_metadataTag: Record<string, string>;
  pduaddress_primaryMetric: number;
  pduaddress_secondaryMetric: number;
  pduaddress_baselineAverage: number;
  pduaddress_peakObserved: number;
  pduaddress_standardDeviation: number;
  pduaddress_rawHexSample: string;
  pduaddress_metadataTag: Record<string, string>;
  qosflow_primaryMetric: number;
  qosflow_secondaryMetric: number;
  qosflow_baselineAverage: number;
  qosflow_peakObserved: number;
  qosflow_standardDeviation: number;
  qosflow_rawHexSample: string;
  qosflow_metadataTag: Record<string, string>;
  tunnelendpointidentifier_primaryMetric: number;
  tunnelendpointidentifier_secondaryMetric: number;
  tunnelendpointidentifier_baselineAverage: number;
  tunnelendpointidentifier_peakObserved: number;
  tunnelendpointidentifier_standardDeviation: number;
  tunnelendpointidentifier_rawHexSample: string;
  tunnelendpointidentifier_metadataTag: Record<string, string>;
  chargingprofile_primaryMetric: number;
  chargingprofile_secondaryMetric: number;
  chargingprofile_baselineAverage: number;
  chargingprofile_peakObserved: number;
  chargingprofile_standardDeviation: number;
  chargingprofile_rawHexSample: string;
  chargingprofile_metadataTag: Record<string, string>;
  policyrules_primaryMetric: number;
  policyrules_secondaryMetric: number;
  policyrules_baselineAverage: number;
  policyrules_peakObserved: number;
  policyrules_standardDeviation: number;
  policyrules_rawHexSample: string;
  policyrules_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Core5GAmfSmfFilterV19 = Partial<Core5GAmfSmfRecordV19> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Core5GAmfSmfRecordV20 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  sessionid_primaryMetric: number;
  sessionid_secondaryMetric: number;
  sessionid_baselineAverage: number;
  sessionid_peakObserved: number;
  sessionid_standardDeviation: number;
  sessionid_rawHexSample: string;
  sessionid_metadataTag: Record<string, string>;
  pduaddress_primaryMetric: number;
  pduaddress_secondaryMetric: number;
  pduaddress_baselineAverage: number;
  pduaddress_peakObserved: number;
  pduaddress_standardDeviation: number;
  pduaddress_rawHexSample: string;
  pduaddress_metadataTag: Record<string, string>;
  qosflow_primaryMetric: number;
  qosflow_secondaryMetric: number;
  qosflow_baselineAverage: number;
  qosflow_peakObserved: number;
  qosflow_standardDeviation: number;
  qosflow_rawHexSample: string;
  qosflow_metadataTag: Record<string, string>;
  tunnelendpointidentifier_primaryMetric: number;
  tunnelendpointidentifier_secondaryMetric: number;
  tunnelendpointidentifier_baselineAverage: number;
  tunnelendpointidentifier_peakObserved: number;
  tunnelendpointidentifier_standardDeviation: number;
  tunnelendpointidentifier_rawHexSample: string;
  tunnelendpointidentifier_metadataTag: Record<string, string>;
  chargingprofile_primaryMetric: number;
  chargingprofile_secondaryMetric: number;
  chargingprofile_baselineAverage: number;
  chargingprofile_peakObserved: number;
  chargingprofile_standardDeviation: number;
  chargingprofile_rawHexSample: string;
  chargingprofile_metadataTag: Record<string, string>;
  policyrules_primaryMetric: number;
  policyrules_secondaryMetric: number;
  policyrules_baselineAverage: number;
  policyrules_peakObserved: number;
  policyrules_standardDeviation: number;
  policyrules_rawHexSample: string;
  policyrules_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Core5GAmfSmfFilterV20 = Partial<Core5GAmfSmfRecordV20> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Core5GAmfSmfRecordV21 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  sessionid_primaryMetric: number;
  sessionid_secondaryMetric: number;
  sessionid_baselineAverage: number;
  sessionid_peakObserved: number;
  sessionid_standardDeviation: number;
  sessionid_rawHexSample: string;
  sessionid_metadataTag: Record<string, string>;
  pduaddress_primaryMetric: number;
  pduaddress_secondaryMetric: number;
  pduaddress_baselineAverage: number;
  pduaddress_peakObserved: number;
  pduaddress_standardDeviation: number;
  pduaddress_rawHexSample: string;
  pduaddress_metadataTag: Record<string, string>;
  qosflow_primaryMetric: number;
  qosflow_secondaryMetric: number;
  qosflow_baselineAverage: number;
  qosflow_peakObserved: number;
  qosflow_standardDeviation: number;
  qosflow_rawHexSample: string;
  qosflow_metadataTag: Record<string, string>;
  tunnelendpointidentifier_primaryMetric: number;
  tunnelendpointidentifier_secondaryMetric: number;
  tunnelendpointidentifier_baselineAverage: number;
  tunnelendpointidentifier_peakObserved: number;
  tunnelendpointidentifier_standardDeviation: number;
  tunnelendpointidentifier_rawHexSample: string;
  tunnelendpointidentifier_metadataTag: Record<string, string>;
  chargingprofile_primaryMetric: number;
  chargingprofile_secondaryMetric: number;
  chargingprofile_baselineAverage: number;
  chargingprofile_peakObserved: number;
  chargingprofile_standardDeviation: number;
  chargingprofile_rawHexSample: string;
  chargingprofile_metadataTag: Record<string, string>;
  policyrules_primaryMetric: number;
  policyrules_secondaryMetric: number;
  policyrules_baselineAverage: number;
  policyrules_peakObserved: number;
  policyrules_standardDeviation: number;
  policyrules_rawHexSample: string;
  policyrules_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Core5GAmfSmfFilterV21 = Partial<Core5GAmfSmfRecordV21> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Core5GAmfSmfRecordV22 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  sessionid_primaryMetric: number;
  sessionid_secondaryMetric: number;
  sessionid_baselineAverage: number;
  sessionid_peakObserved: number;
  sessionid_standardDeviation: number;
  sessionid_rawHexSample: string;
  sessionid_metadataTag: Record<string, string>;
  pduaddress_primaryMetric: number;
  pduaddress_secondaryMetric: number;
  pduaddress_baselineAverage: number;
  pduaddress_peakObserved: number;
  pduaddress_standardDeviation: number;
  pduaddress_rawHexSample: string;
  pduaddress_metadataTag: Record<string, string>;
  qosflow_primaryMetric: number;
  qosflow_secondaryMetric: number;
  qosflow_baselineAverage: number;
  qosflow_peakObserved: number;
  qosflow_standardDeviation: number;
  qosflow_rawHexSample: string;
  qosflow_metadataTag: Record<string, string>;
  tunnelendpointidentifier_primaryMetric: number;
  tunnelendpointidentifier_secondaryMetric: number;
  tunnelendpointidentifier_baselineAverage: number;
  tunnelendpointidentifier_peakObserved: number;
  tunnelendpointidentifier_standardDeviation: number;
  tunnelendpointidentifier_rawHexSample: string;
  tunnelendpointidentifier_metadataTag: Record<string, string>;
  chargingprofile_primaryMetric: number;
  chargingprofile_secondaryMetric: number;
  chargingprofile_baselineAverage: number;
  chargingprofile_peakObserved: number;
  chargingprofile_standardDeviation: number;
  chargingprofile_rawHexSample: string;
  chargingprofile_metadataTag: Record<string, string>;
  policyrules_primaryMetric: number;
  policyrules_secondaryMetric: number;
  policyrules_baselineAverage: number;
  policyrules_peakObserved: number;
  policyrules_standardDeviation: number;
  policyrules_rawHexSample: string;
  policyrules_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Core5GAmfSmfFilterV22 = Partial<Core5GAmfSmfRecordV22> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Core5GAmfSmfRecordV23 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  sessionid_primaryMetric: number;
  sessionid_secondaryMetric: number;
  sessionid_baselineAverage: number;
  sessionid_peakObserved: number;
  sessionid_standardDeviation: number;
  sessionid_rawHexSample: string;
  sessionid_metadataTag: Record<string, string>;
  pduaddress_primaryMetric: number;
  pduaddress_secondaryMetric: number;
  pduaddress_baselineAverage: number;
  pduaddress_peakObserved: number;
  pduaddress_standardDeviation: number;
  pduaddress_rawHexSample: string;
  pduaddress_metadataTag: Record<string, string>;
  qosflow_primaryMetric: number;
  qosflow_secondaryMetric: number;
  qosflow_baselineAverage: number;
  qosflow_peakObserved: number;
  qosflow_standardDeviation: number;
  qosflow_rawHexSample: string;
  qosflow_metadataTag: Record<string, string>;
  tunnelendpointidentifier_primaryMetric: number;
  tunnelendpointidentifier_secondaryMetric: number;
  tunnelendpointidentifier_baselineAverage: number;
  tunnelendpointidentifier_peakObserved: number;
  tunnelendpointidentifier_standardDeviation: number;
  tunnelendpointidentifier_rawHexSample: string;
  tunnelendpointidentifier_metadataTag: Record<string, string>;
  chargingprofile_primaryMetric: number;
  chargingprofile_secondaryMetric: number;
  chargingprofile_baselineAverage: number;
  chargingprofile_peakObserved: number;
  chargingprofile_standardDeviation: number;
  chargingprofile_rawHexSample: string;
  chargingprofile_metadataTag: Record<string, string>;
  policyrules_primaryMetric: number;
  policyrules_secondaryMetric: number;
  policyrules_baselineAverage: number;
  policyrules_peakObserved: number;
  policyrules_standardDeviation: number;
  policyrules_rawHexSample: string;
  policyrules_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Core5GAmfSmfFilterV23 = Partial<Core5GAmfSmfRecordV23> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Core5GAmfSmfRecordV24 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  sessionid_primaryMetric: number;
  sessionid_secondaryMetric: number;
  sessionid_baselineAverage: number;
  sessionid_peakObserved: number;
  sessionid_standardDeviation: number;
  sessionid_rawHexSample: string;
  sessionid_metadataTag: Record<string, string>;
  pduaddress_primaryMetric: number;
  pduaddress_secondaryMetric: number;
  pduaddress_baselineAverage: number;
  pduaddress_peakObserved: number;
  pduaddress_standardDeviation: number;
  pduaddress_rawHexSample: string;
  pduaddress_metadataTag: Record<string, string>;
  qosflow_primaryMetric: number;
  qosflow_secondaryMetric: number;
  qosflow_baselineAverage: number;
  qosflow_peakObserved: number;
  qosflow_standardDeviation: number;
  qosflow_rawHexSample: string;
  qosflow_metadataTag: Record<string, string>;
  tunnelendpointidentifier_primaryMetric: number;
  tunnelendpointidentifier_secondaryMetric: number;
  tunnelendpointidentifier_baselineAverage: number;
  tunnelendpointidentifier_peakObserved: number;
  tunnelendpointidentifier_standardDeviation: number;
  tunnelendpointidentifier_rawHexSample: string;
  tunnelendpointidentifier_metadataTag: Record<string, string>;
  chargingprofile_primaryMetric: number;
  chargingprofile_secondaryMetric: number;
  chargingprofile_baselineAverage: number;
  chargingprofile_peakObserved: number;
  chargingprofile_standardDeviation: number;
  chargingprofile_rawHexSample: string;
  chargingprofile_metadataTag: Record<string, string>;
  policyrules_primaryMetric: number;
  policyrules_secondaryMetric: number;
  policyrules_baselineAverage: number;
  policyrules_peakObserved: number;
  policyrules_standardDeviation: number;
  policyrules_rawHexSample: string;
  policyrules_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Core5GAmfSmfFilterV24 = Partial<Core5GAmfSmfRecordV24> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Core5GAmfSmfRecordV25 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  sessionid_primaryMetric: number;
  sessionid_secondaryMetric: number;
  sessionid_baselineAverage: number;
  sessionid_peakObserved: number;
  sessionid_standardDeviation: number;
  sessionid_rawHexSample: string;
  sessionid_metadataTag: Record<string, string>;
  pduaddress_primaryMetric: number;
  pduaddress_secondaryMetric: number;
  pduaddress_baselineAverage: number;
  pduaddress_peakObserved: number;
  pduaddress_standardDeviation: number;
  pduaddress_rawHexSample: string;
  pduaddress_metadataTag: Record<string, string>;
  qosflow_primaryMetric: number;
  qosflow_secondaryMetric: number;
  qosflow_baselineAverage: number;
  qosflow_peakObserved: number;
  qosflow_standardDeviation: number;
  qosflow_rawHexSample: string;
  qosflow_metadataTag: Record<string, string>;
  tunnelendpointidentifier_primaryMetric: number;
  tunnelendpointidentifier_secondaryMetric: number;
  tunnelendpointidentifier_baselineAverage: number;
  tunnelendpointidentifier_peakObserved: number;
  tunnelendpointidentifier_standardDeviation: number;
  tunnelendpointidentifier_rawHexSample: string;
  tunnelendpointidentifier_metadataTag: Record<string, string>;
  chargingprofile_primaryMetric: number;
  chargingprofile_secondaryMetric: number;
  chargingprofile_baselineAverage: number;
  chargingprofile_peakObserved: number;
  chargingprofile_standardDeviation: number;
  chargingprofile_rawHexSample: string;
  chargingprofile_metadataTag: Record<string, string>;
  policyrules_primaryMetric: number;
  policyrules_secondaryMetric: number;
  policyrules_baselineAverage: number;
  policyrules_peakObserved: number;
  policyrules_standardDeviation: number;
  policyrules_rawHexSample: string;
  policyrules_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Core5GAmfSmfFilterV25 = Partial<Core5GAmfSmfRecordV25> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Core5GAmfSmfRecordV26 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  sessionid_primaryMetric: number;
  sessionid_secondaryMetric: number;
  sessionid_baselineAverage: number;
  sessionid_peakObserved: number;
  sessionid_standardDeviation: number;
  sessionid_rawHexSample: string;
  sessionid_metadataTag: Record<string, string>;
  pduaddress_primaryMetric: number;
  pduaddress_secondaryMetric: number;
  pduaddress_baselineAverage: number;
  pduaddress_peakObserved: number;
  pduaddress_standardDeviation: number;
  pduaddress_rawHexSample: string;
  pduaddress_metadataTag: Record<string, string>;
  qosflow_primaryMetric: number;
  qosflow_secondaryMetric: number;
  qosflow_baselineAverage: number;
  qosflow_peakObserved: number;
  qosflow_standardDeviation: number;
  qosflow_rawHexSample: string;
  qosflow_metadataTag: Record<string, string>;
  tunnelendpointidentifier_primaryMetric: number;
  tunnelendpointidentifier_secondaryMetric: number;
  tunnelendpointidentifier_baselineAverage: number;
  tunnelendpointidentifier_peakObserved: number;
  tunnelendpointidentifier_standardDeviation: number;
  tunnelendpointidentifier_rawHexSample: string;
  tunnelendpointidentifier_metadataTag: Record<string, string>;
  chargingprofile_primaryMetric: number;
  chargingprofile_secondaryMetric: number;
  chargingprofile_baselineAverage: number;
  chargingprofile_peakObserved: number;
  chargingprofile_standardDeviation: number;
  chargingprofile_rawHexSample: string;
  chargingprofile_metadataTag: Record<string, string>;
  policyrules_primaryMetric: number;
  policyrules_secondaryMetric: number;
  policyrules_baselineAverage: number;
  policyrules_peakObserved: number;
  policyrules_standardDeviation: number;
  policyrules_rawHexSample: string;
  policyrules_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Core5GAmfSmfFilterV26 = Partial<Core5GAmfSmfRecordV26> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Core5GAmfSmfRecordV27 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  sessionid_primaryMetric: number;
  sessionid_secondaryMetric: number;
  sessionid_baselineAverage: number;
  sessionid_peakObserved: number;
  sessionid_standardDeviation: number;
  sessionid_rawHexSample: string;
  sessionid_metadataTag: Record<string, string>;
  pduaddress_primaryMetric: number;
  pduaddress_secondaryMetric: number;
  pduaddress_baselineAverage: number;
  pduaddress_peakObserved: number;
  pduaddress_standardDeviation: number;
  pduaddress_rawHexSample: string;
  pduaddress_metadataTag: Record<string, string>;
  qosflow_primaryMetric: number;
  qosflow_secondaryMetric: number;
  qosflow_baselineAverage: number;
  qosflow_peakObserved: number;
  qosflow_standardDeviation: number;
  qosflow_rawHexSample: string;
  qosflow_metadataTag: Record<string, string>;
  tunnelendpointidentifier_primaryMetric: number;
  tunnelendpointidentifier_secondaryMetric: number;
  tunnelendpointidentifier_baselineAverage: number;
  tunnelendpointidentifier_peakObserved: number;
  tunnelendpointidentifier_standardDeviation: number;
  tunnelendpointidentifier_rawHexSample: string;
  tunnelendpointidentifier_metadataTag: Record<string, string>;
  chargingprofile_primaryMetric: number;
  chargingprofile_secondaryMetric: number;
  chargingprofile_baselineAverage: number;
  chargingprofile_peakObserved: number;
  chargingprofile_standardDeviation: number;
  chargingprofile_rawHexSample: string;
  chargingprofile_metadataTag: Record<string, string>;
  policyrules_primaryMetric: number;
  policyrules_secondaryMetric: number;
  policyrules_baselineAverage: number;
  policyrules_peakObserved: number;
  policyrules_standardDeviation: number;
  policyrules_rawHexSample: string;
  policyrules_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Core5GAmfSmfFilterV27 = Partial<Core5GAmfSmfRecordV27> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Core5GAmfSmfRecordV28 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  sessionid_primaryMetric: number;
  sessionid_secondaryMetric: number;
  sessionid_baselineAverage: number;
  sessionid_peakObserved: number;
  sessionid_standardDeviation: number;
  sessionid_rawHexSample: string;
  sessionid_metadataTag: Record<string, string>;
  pduaddress_primaryMetric: number;
  pduaddress_secondaryMetric: number;
  pduaddress_baselineAverage: number;
  pduaddress_peakObserved: number;
  pduaddress_standardDeviation: number;
  pduaddress_rawHexSample: string;
  pduaddress_metadataTag: Record<string, string>;
  qosflow_primaryMetric: number;
  qosflow_secondaryMetric: number;
  qosflow_baselineAverage: number;
  qosflow_peakObserved: number;
  qosflow_standardDeviation: number;
  qosflow_rawHexSample: string;
  qosflow_metadataTag: Record<string, string>;
  tunnelendpointidentifier_primaryMetric: number;
  tunnelendpointidentifier_secondaryMetric: number;
  tunnelendpointidentifier_baselineAverage: number;
  tunnelendpointidentifier_peakObserved: number;
  tunnelendpointidentifier_standardDeviation: number;
  tunnelendpointidentifier_rawHexSample: string;
  tunnelendpointidentifier_metadataTag: Record<string, string>;
  chargingprofile_primaryMetric: number;
  chargingprofile_secondaryMetric: number;
  chargingprofile_baselineAverage: number;
  chargingprofile_peakObserved: number;
  chargingprofile_standardDeviation: number;
  chargingprofile_rawHexSample: string;
  chargingprofile_metadataTag: Record<string, string>;
  policyrules_primaryMetric: number;
  policyrules_secondaryMetric: number;
  policyrules_baselineAverage: number;
  policyrules_peakObserved: number;
  policyrules_standardDeviation: number;
  policyrules_rawHexSample: string;
  policyrules_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Core5GAmfSmfFilterV28 = Partial<Core5GAmfSmfRecordV28> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Core5GAmfSmfRecordV29 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  sessionid_primaryMetric: number;
  sessionid_secondaryMetric: number;
  sessionid_baselineAverage: number;
  sessionid_peakObserved: number;
  sessionid_standardDeviation: number;
  sessionid_rawHexSample: string;
  sessionid_metadataTag: Record<string, string>;
  pduaddress_primaryMetric: number;
  pduaddress_secondaryMetric: number;
  pduaddress_baselineAverage: number;
  pduaddress_peakObserved: number;
  pduaddress_standardDeviation: number;
  pduaddress_rawHexSample: string;
  pduaddress_metadataTag: Record<string, string>;
  qosflow_primaryMetric: number;
  qosflow_secondaryMetric: number;
  qosflow_baselineAverage: number;
  qosflow_peakObserved: number;
  qosflow_standardDeviation: number;
  qosflow_rawHexSample: string;
  qosflow_metadataTag: Record<string, string>;
  tunnelendpointidentifier_primaryMetric: number;
  tunnelendpointidentifier_secondaryMetric: number;
  tunnelendpointidentifier_baselineAverage: number;
  tunnelendpointidentifier_peakObserved: number;
  tunnelendpointidentifier_standardDeviation: number;
  tunnelendpointidentifier_rawHexSample: string;
  tunnelendpointidentifier_metadataTag: Record<string, string>;
  chargingprofile_primaryMetric: number;
  chargingprofile_secondaryMetric: number;
  chargingprofile_baselineAverage: number;
  chargingprofile_peakObserved: number;
  chargingprofile_standardDeviation: number;
  chargingprofile_rawHexSample: string;
  chargingprofile_metadataTag: Record<string, string>;
  policyrules_primaryMetric: number;
  policyrules_secondaryMetric: number;
  policyrules_baselineAverage: number;
  policyrules_peakObserved: number;
  policyrules_standardDeviation: number;
  policyrules_rawHexSample: string;
  policyrules_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Core5GAmfSmfFilterV29 = Partial<Core5GAmfSmfRecordV29> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Core5GAmfSmfRecordV30 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  sessionid_primaryMetric: number;
  sessionid_secondaryMetric: number;
  sessionid_baselineAverage: number;
  sessionid_peakObserved: number;
  sessionid_standardDeviation: number;
  sessionid_rawHexSample: string;
  sessionid_metadataTag: Record<string, string>;
  pduaddress_primaryMetric: number;
  pduaddress_secondaryMetric: number;
  pduaddress_baselineAverage: number;
  pduaddress_peakObserved: number;
  pduaddress_standardDeviation: number;
  pduaddress_rawHexSample: string;
  pduaddress_metadataTag: Record<string, string>;
  qosflow_primaryMetric: number;
  qosflow_secondaryMetric: number;
  qosflow_baselineAverage: number;
  qosflow_peakObserved: number;
  qosflow_standardDeviation: number;
  qosflow_rawHexSample: string;
  qosflow_metadataTag: Record<string, string>;
  tunnelendpointidentifier_primaryMetric: number;
  tunnelendpointidentifier_secondaryMetric: number;
  tunnelendpointidentifier_baselineAverage: number;
  tunnelendpointidentifier_peakObserved: number;
  tunnelendpointidentifier_standardDeviation: number;
  tunnelendpointidentifier_rawHexSample: string;
  tunnelendpointidentifier_metadataTag: Record<string, string>;
  chargingprofile_primaryMetric: number;
  chargingprofile_secondaryMetric: number;
  chargingprofile_baselineAverage: number;
  chargingprofile_peakObserved: number;
  chargingprofile_standardDeviation: number;
  chargingprofile_rawHexSample: string;
  chargingprofile_metadataTag: Record<string, string>;
  policyrules_primaryMetric: number;
  policyrules_secondaryMetric: number;
  policyrules_baselineAverage: number;
  policyrules_peakObserved: number;
  policyrules_standardDeviation: number;
  policyrules_rawHexSample: string;
  policyrules_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Core5GAmfSmfFilterV30 = Partial<Core5GAmfSmfRecordV30> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Core5GAmfSmfRecordV31 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  sessionid_primaryMetric: number;
  sessionid_secondaryMetric: number;
  sessionid_baselineAverage: number;
  sessionid_peakObserved: number;
  sessionid_standardDeviation: number;
  sessionid_rawHexSample: string;
  sessionid_metadataTag: Record<string, string>;
  pduaddress_primaryMetric: number;
  pduaddress_secondaryMetric: number;
  pduaddress_baselineAverage: number;
  pduaddress_peakObserved: number;
  pduaddress_standardDeviation: number;
  pduaddress_rawHexSample: string;
  pduaddress_metadataTag: Record<string, string>;
  qosflow_primaryMetric: number;
  qosflow_secondaryMetric: number;
  qosflow_baselineAverage: number;
  qosflow_peakObserved: number;
  qosflow_standardDeviation: number;
  qosflow_rawHexSample: string;
  qosflow_metadataTag: Record<string, string>;
  tunnelendpointidentifier_primaryMetric: number;
  tunnelendpointidentifier_secondaryMetric: number;
  tunnelendpointidentifier_baselineAverage: number;
  tunnelendpointidentifier_peakObserved: number;
  tunnelendpointidentifier_standardDeviation: number;
  tunnelendpointidentifier_rawHexSample: string;
  tunnelendpointidentifier_metadataTag: Record<string, string>;
  chargingprofile_primaryMetric: number;
  chargingprofile_secondaryMetric: number;
  chargingprofile_baselineAverage: number;
  chargingprofile_peakObserved: number;
  chargingprofile_standardDeviation: number;
  chargingprofile_rawHexSample: string;
  chargingprofile_metadataTag: Record<string, string>;
  policyrules_primaryMetric: number;
  policyrules_secondaryMetric: number;
  policyrules_baselineAverage: number;
  policyrules_peakObserved: number;
  policyrules_standardDeviation: number;
  policyrules_rawHexSample: string;
  policyrules_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Core5GAmfSmfFilterV31 = Partial<Core5GAmfSmfRecordV31> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Core5GAmfSmfRecordV32 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  sessionid_primaryMetric: number;
  sessionid_secondaryMetric: number;
  sessionid_baselineAverage: number;
  sessionid_peakObserved: number;
  sessionid_standardDeviation: number;
  sessionid_rawHexSample: string;
  sessionid_metadataTag: Record<string, string>;
  pduaddress_primaryMetric: number;
  pduaddress_secondaryMetric: number;
  pduaddress_baselineAverage: number;
  pduaddress_peakObserved: number;
  pduaddress_standardDeviation: number;
  pduaddress_rawHexSample: string;
  pduaddress_metadataTag: Record<string, string>;
  qosflow_primaryMetric: number;
  qosflow_secondaryMetric: number;
  qosflow_baselineAverage: number;
  qosflow_peakObserved: number;
  qosflow_standardDeviation: number;
  qosflow_rawHexSample: string;
  qosflow_metadataTag: Record<string, string>;
  tunnelendpointidentifier_primaryMetric: number;
  tunnelendpointidentifier_secondaryMetric: number;
  tunnelendpointidentifier_baselineAverage: number;
  tunnelendpointidentifier_peakObserved: number;
  tunnelendpointidentifier_standardDeviation: number;
  tunnelendpointidentifier_rawHexSample: string;
  tunnelendpointidentifier_metadataTag: Record<string, string>;
  chargingprofile_primaryMetric: number;
  chargingprofile_secondaryMetric: number;
  chargingprofile_baselineAverage: number;
  chargingprofile_peakObserved: number;
  chargingprofile_standardDeviation: number;
  chargingprofile_rawHexSample: string;
  chargingprofile_metadataTag: Record<string, string>;
  policyrules_primaryMetric: number;
  policyrules_secondaryMetric: number;
  policyrules_baselineAverage: number;
  policyrules_peakObserved: number;
  policyrules_standardDeviation: number;
  policyrules_rawHexSample: string;
  policyrules_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Core5GAmfSmfFilterV32 = Partial<Core5GAmfSmfRecordV32> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Core5GAmfSmfRecordV33 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  sessionid_primaryMetric: number;
  sessionid_secondaryMetric: number;
  sessionid_baselineAverage: number;
  sessionid_peakObserved: number;
  sessionid_standardDeviation: number;
  sessionid_rawHexSample: string;
  sessionid_metadataTag: Record<string, string>;
  pduaddress_primaryMetric: number;
  pduaddress_secondaryMetric: number;
  pduaddress_baselineAverage: number;
  pduaddress_peakObserved: number;
  pduaddress_standardDeviation: number;
  pduaddress_rawHexSample: string;
  pduaddress_metadataTag: Record<string, string>;
  qosflow_primaryMetric: number;
  qosflow_secondaryMetric: number;
  qosflow_baselineAverage: number;
  qosflow_peakObserved: number;
  qosflow_standardDeviation: number;
  qosflow_rawHexSample: string;
  qosflow_metadataTag: Record<string, string>;
  tunnelendpointidentifier_primaryMetric: number;
  tunnelendpointidentifier_secondaryMetric: number;
  tunnelendpointidentifier_baselineAverage: number;
  tunnelendpointidentifier_peakObserved: number;
  tunnelendpointidentifier_standardDeviation: number;
  tunnelendpointidentifier_rawHexSample: string;
  tunnelendpointidentifier_metadataTag: Record<string, string>;
  chargingprofile_primaryMetric: number;
  chargingprofile_secondaryMetric: number;
  chargingprofile_baselineAverage: number;
  chargingprofile_peakObserved: number;
  chargingprofile_standardDeviation: number;
  chargingprofile_rawHexSample: string;
  chargingprofile_metadataTag: Record<string, string>;
  policyrules_primaryMetric: number;
  policyrules_secondaryMetric: number;
  policyrules_baselineAverage: number;
  policyrules_peakObserved: number;
  policyrules_standardDeviation: number;
  policyrules_rawHexSample: string;
  policyrules_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Core5GAmfSmfFilterV33 = Partial<Core5GAmfSmfRecordV33> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Core5GAmfSmfRecordV34 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  sessionid_primaryMetric: number;
  sessionid_secondaryMetric: number;
  sessionid_baselineAverage: number;
  sessionid_peakObserved: number;
  sessionid_standardDeviation: number;
  sessionid_rawHexSample: string;
  sessionid_metadataTag: Record<string, string>;
  pduaddress_primaryMetric: number;
  pduaddress_secondaryMetric: number;
  pduaddress_baselineAverage: number;
  pduaddress_peakObserved: number;
  pduaddress_standardDeviation: number;
  pduaddress_rawHexSample: string;
  pduaddress_metadataTag: Record<string, string>;
  qosflow_primaryMetric: number;
  qosflow_secondaryMetric: number;
  qosflow_baselineAverage: number;
  qosflow_peakObserved: number;
  qosflow_standardDeviation: number;
  qosflow_rawHexSample: string;
  qosflow_metadataTag: Record<string, string>;
  tunnelendpointidentifier_primaryMetric: number;
  tunnelendpointidentifier_secondaryMetric: number;
  tunnelendpointidentifier_baselineAverage: number;
  tunnelendpointidentifier_peakObserved: number;
  tunnelendpointidentifier_standardDeviation: number;
  tunnelendpointidentifier_rawHexSample: string;
  tunnelendpointidentifier_metadataTag: Record<string, string>;
  chargingprofile_primaryMetric: number;
  chargingprofile_secondaryMetric: number;
  chargingprofile_baselineAverage: number;
  chargingprofile_peakObserved: number;
  chargingprofile_standardDeviation: number;
  chargingprofile_rawHexSample: string;
  chargingprofile_metadataTag: Record<string, string>;
  policyrules_primaryMetric: number;
  policyrules_secondaryMetric: number;
  policyrules_baselineAverage: number;
  policyrules_peakObserved: number;
  policyrules_standardDeviation: number;
  policyrules_rawHexSample: string;
  policyrules_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Core5GAmfSmfFilterV34 = Partial<Core5GAmfSmfRecordV34> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Core5GAmfSmfRecordV35 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  sessionid_primaryMetric: number;
  sessionid_secondaryMetric: number;
  sessionid_baselineAverage: number;
  sessionid_peakObserved: number;
  sessionid_standardDeviation: number;
  sessionid_rawHexSample: string;
  sessionid_metadataTag: Record<string, string>;
  pduaddress_primaryMetric: number;
  pduaddress_secondaryMetric: number;
  pduaddress_baselineAverage: number;
  pduaddress_peakObserved: number;
  pduaddress_standardDeviation: number;
  pduaddress_rawHexSample: string;
  pduaddress_metadataTag: Record<string, string>;
  qosflow_primaryMetric: number;
  qosflow_secondaryMetric: number;
  qosflow_baselineAverage: number;
  qosflow_peakObserved: number;
  qosflow_standardDeviation: number;
  qosflow_rawHexSample: string;
  qosflow_metadataTag: Record<string, string>;
  tunnelendpointidentifier_primaryMetric: number;
  tunnelendpointidentifier_secondaryMetric: number;
  tunnelendpointidentifier_baselineAverage: number;
  tunnelendpointidentifier_peakObserved: number;
  tunnelendpointidentifier_standardDeviation: number;
  tunnelendpointidentifier_rawHexSample: string;
  tunnelendpointidentifier_metadataTag: Record<string, string>;
  chargingprofile_primaryMetric: number;
  chargingprofile_secondaryMetric: number;
  chargingprofile_baselineAverage: number;
  chargingprofile_peakObserved: number;
  chargingprofile_standardDeviation: number;
  chargingprofile_rawHexSample: string;
  chargingprofile_metadataTag: Record<string, string>;
  policyrules_primaryMetric: number;
  policyrules_secondaryMetric: number;
  policyrules_baselineAverage: number;
  policyrules_peakObserved: number;
  policyrules_standardDeviation: number;
  policyrules_rawHexSample: string;
  policyrules_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Core5GAmfSmfFilterV35 = Partial<Core5GAmfSmfRecordV35> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Core5GAmfSmfRecordV36 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  sessionid_primaryMetric: number;
  sessionid_secondaryMetric: number;
  sessionid_baselineAverage: number;
  sessionid_peakObserved: number;
  sessionid_standardDeviation: number;
  sessionid_rawHexSample: string;
  sessionid_metadataTag: Record<string, string>;
  pduaddress_primaryMetric: number;
  pduaddress_secondaryMetric: number;
  pduaddress_baselineAverage: number;
  pduaddress_peakObserved: number;
  pduaddress_standardDeviation: number;
  pduaddress_rawHexSample: string;
  pduaddress_metadataTag: Record<string, string>;
  qosflow_primaryMetric: number;
  qosflow_secondaryMetric: number;
  qosflow_baselineAverage: number;
  qosflow_peakObserved: number;
  qosflow_standardDeviation: number;
  qosflow_rawHexSample: string;
  qosflow_metadataTag: Record<string, string>;
  tunnelendpointidentifier_primaryMetric: number;
  tunnelendpointidentifier_secondaryMetric: number;
  tunnelendpointidentifier_baselineAverage: number;
  tunnelendpointidentifier_peakObserved: number;
  tunnelendpointidentifier_standardDeviation: number;
  tunnelendpointidentifier_rawHexSample: string;
  tunnelendpointidentifier_metadataTag: Record<string, string>;
  chargingprofile_primaryMetric: number;
  chargingprofile_secondaryMetric: number;
  chargingprofile_baselineAverage: number;
  chargingprofile_peakObserved: number;
  chargingprofile_standardDeviation: number;
  chargingprofile_rawHexSample: string;
  chargingprofile_metadataTag: Record<string, string>;
  policyrules_primaryMetric: number;
  policyrules_secondaryMetric: number;
  policyrules_baselineAverage: number;
  policyrules_peakObserved: number;
  policyrules_standardDeviation: number;
  policyrules_rawHexSample: string;
  policyrules_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Core5GAmfSmfFilterV36 = Partial<Core5GAmfSmfRecordV36> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Core5GAmfSmfRecordV37 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  sessionid_primaryMetric: number;
  sessionid_secondaryMetric: number;
  sessionid_baselineAverage: number;
  sessionid_peakObserved: number;
  sessionid_standardDeviation: number;
  sessionid_rawHexSample: string;
  sessionid_metadataTag: Record<string, string>;
  pduaddress_primaryMetric: number;
  pduaddress_secondaryMetric: number;
  pduaddress_baselineAverage: number;
  pduaddress_peakObserved: number;
  pduaddress_standardDeviation: number;
  pduaddress_rawHexSample: string;
  pduaddress_metadataTag: Record<string, string>;
  qosflow_primaryMetric: number;
  qosflow_secondaryMetric: number;
  qosflow_baselineAverage: number;
  qosflow_peakObserved: number;
  qosflow_standardDeviation: number;
  qosflow_rawHexSample: string;
  qosflow_metadataTag: Record<string, string>;
  tunnelendpointidentifier_primaryMetric: number;
  tunnelendpointidentifier_secondaryMetric: number;
  tunnelendpointidentifier_baselineAverage: number;
  tunnelendpointidentifier_peakObserved: number;
  tunnelendpointidentifier_standardDeviation: number;
  tunnelendpointidentifier_rawHexSample: string;
  tunnelendpointidentifier_metadataTag: Record<string, string>;
  chargingprofile_primaryMetric: number;
  chargingprofile_secondaryMetric: number;
  chargingprofile_baselineAverage: number;
  chargingprofile_peakObserved: number;
  chargingprofile_standardDeviation: number;
  chargingprofile_rawHexSample: string;
  chargingprofile_metadataTag: Record<string, string>;
  policyrules_primaryMetric: number;
  policyrules_secondaryMetric: number;
  policyrules_baselineAverage: number;
  policyrules_peakObserved: number;
  policyrules_standardDeviation: number;
  policyrules_rawHexSample: string;
  policyrules_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Core5GAmfSmfFilterV37 = Partial<Core5GAmfSmfRecordV37> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Core5GAmfSmfRecordV38 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  sessionid_primaryMetric: number;
  sessionid_secondaryMetric: number;
  sessionid_baselineAverage: number;
  sessionid_peakObserved: number;
  sessionid_standardDeviation: number;
  sessionid_rawHexSample: string;
  sessionid_metadataTag: Record<string, string>;
  pduaddress_primaryMetric: number;
  pduaddress_secondaryMetric: number;
  pduaddress_baselineAverage: number;
  pduaddress_peakObserved: number;
  pduaddress_standardDeviation: number;
  pduaddress_rawHexSample: string;
  pduaddress_metadataTag: Record<string, string>;
  qosflow_primaryMetric: number;
  qosflow_secondaryMetric: number;
  qosflow_baselineAverage: number;
  qosflow_peakObserved: number;
  qosflow_standardDeviation: number;
  qosflow_rawHexSample: string;
  qosflow_metadataTag: Record<string, string>;
  tunnelendpointidentifier_primaryMetric: number;
  tunnelendpointidentifier_secondaryMetric: number;
  tunnelendpointidentifier_baselineAverage: number;
  tunnelendpointidentifier_peakObserved: number;
  tunnelendpointidentifier_standardDeviation: number;
  tunnelendpointidentifier_rawHexSample: string;
  tunnelendpointidentifier_metadataTag: Record<string, string>;
  chargingprofile_primaryMetric: number;
  chargingprofile_secondaryMetric: number;
  chargingprofile_baselineAverage: number;
  chargingprofile_peakObserved: number;
  chargingprofile_standardDeviation: number;
  chargingprofile_rawHexSample: string;
  chargingprofile_metadataTag: Record<string, string>;
  policyrules_primaryMetric: number;
  policyrules_secondaryMetric: number;
  policyrules_baselineAverage: number;
  policyrules_peakObserved: number;
  policyrules_standardDeviation: number;
  policyrules_rawHexSample: string;
  policyrules_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Core5GAmfSmfFilterV38 = Partial<Core5GAmfSmfRecordV38> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Core5GAmfSmfRecordV39 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  sessionid_primaryMetric: number;
  sessionid_secondaryMetric: number;
  sessionid_baselineAverage: number;
  sessionid_peakObserved: number;
  sessionid_standardDeviation: number;
  sessionid_rawHexSample: string;
  sessionid_metadataTag: Record<string, string>;
  pduaddress_primaryMetric: number;
  pduaddress_secondaryMetric: number;
  pduaddress_baselineAverage: number;
  pduaddress_peakObserved: number;
  pduaddress_standardDeviation: number;
  pduaddress_rawHexSample: string;
  pduaddress_metadataTag: Record<string, string>;
  qosflow_primaryMetric: number;
  qosflow_secondaryMetric: number;
  qosflow_baselineAverage: number;
  qosflow_peakObserved: number;
  qosflow_standardDeviation: number;
  qosflow_rawHexSample: string;
  qosflow_metadataTag: Record<string, string>;
  tunnelendpointidentifier_primaryMetric: number;
  tunnelendpointidentifier_secondaryMetric: number;
  tunnelendpointidentifier_baselineAverage: number;
  tunnelendpointidentifier_peakObserved: number;
  tunnelendpointidentifier_standardDeviation: number;
  tunnelendpointidentifier_rawHexSample: string;
  tunnelendpointidentifier_metadataTag: Record<string, string>;
  chargingprofile_primaryMetric: number;
  chargingprofile_secondaryMetric: number;
  chargingprofile_baselineAverage: number;
  chargingprofile_peakObserved: number;
  chargingprofile_standardDeviation: number;
  chargingprofile_rawHexSample: string;
  chargingprofile_metadataTag: Record<string, string>;
  policyrules_primaryMetric: number;
  policyrules_secondaryMetric: number;
  policyrules_baselineAverage: number;
  policyrules_peakObserved: number;
  policyrules_standardDeviation: number;
  policyrules_rawHexSample: string;
  policyrules_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Core5GAmfSmfFilterV39 = Partial<Core5GAmfSmfRecordV39> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Core5GAmfSmfRecordV40 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  sessionid_primaryMetric: number;
  sessionid_secondaryMetric: number;
  sessionid_baselineAverage: number;
  sessionid_peakObserved: number;
  sessionid_standardDeviation: number;
  sessionid_rawHexSample: string;
  sessionid_metadataTag: Record<string, string>;
  pduaddress_primaryMetric: number;
  pduaddress_secondaryMetric: number;
  pduaddress_baselineAverage: number;
  pduaddress_peakObserved: number;
  pduaddress_standardDeviation: number;
  pduaddress_rawHexSample: string;
  pduaddress_metadataTag: Record<string, string>;
  qosflow_primaryMetric: number;
  qosflow_secondaryMetric: number;
  qosflow_baselineAverage: number;
  qosflow_peakObserved: number;
  qosflow_standardDeviation: number;
  qosflow_rawHexSample: string;
  qosflow_metadataTag: Record<string, string>;
  tunnelendpointidentifier_primaryMetric: number;
  tunnelendpointidentifier_secondaryMetric: number;
  tunnelendpointidentifier_baselineAverage: number;
  tunnelendpointidentifier_peakObserved: number;
  tunnelendpointidentifier_standardDeviation: number;
  tunnelendpointidentifier_rawHexSample: string;
  tunnelendpointidentifier_metadataTag: Record<string, string>;
  chargingprofile_primaryMetric: number;
  chargingprofile_secondaryMetric: number;
  chargingprofile_baselineAverage: number;
  chargingprofile_peakObserved: number;
  chargingprofile_standardDeviation: number;
  chargingprofile_rawHexSample: string;
  chargingprofile_metadataTag: Record<string, string>;
  policyrules_primaryMetric: number;
  policyrules_secondaryMetric: number;
  policyrules_baselineAverage: number;
  policyrules_peakObserved: number;
  policyrules_standardDeviation: number;
  policyrules_rawHexSample: string;
  policyrules_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Core5GAmfSmfFilterV40 = Partial<Core5GAmfSmfRecordV40> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};
