/**
 * Enterprise Telecommunications Protocol Specification: MPLS Traffic Engineering (TE) Tunnel Latency & RSVP-TE Metrics
 * Module: @geonet/types/telecom/mpls_te_tunnel_metrics
 * Standard Compliance: 3GPP TS 38.401, IETF RFC Standards, ITU-T G.8032
 */

export interface MPLSTrafficEngineeringTETunnelLatency&RSVPTEMetricsConfig {
  samplingIntervalMs: number;
  collectionEnabled: boolean;
  highWatermarkThreshold: number;
  lowWatermarkThreshold: number;
  retryAttempts: number;
  timeoutMs: number;
}

export interface MplsTeTunnelMetricsRecordV1 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  tunnelid_primaryMetric: number;
  tunnelid_secondaryMetric: number;
  tunnelid_baselineAverage: number;
  tunnelid_peakObserved: number;
  tunnelid_standardDeviation: number;
  tunnelid_rawHexSample: string;
  tunnelid_metadataTag: Record<string, string>;
  ingressrouter_primaryMetric: number;
  ingressrouter_secondaryMetric: number;
  ingressrouter_baselineAverage: number;
  ingressrouter_peakObserved: number;
  ingressrouter_standardDeviation: number;
  ingressrouter_rawHexSample: string;
  ingressrouter_metadataTag: Record<string, string>;
  egressrouter_primaryMetric: number;
  egressrouter_secondaryMetric: number;
  egressrouter_baselineAverage: number;
  egressrouter_peakObserved: number;
  egressrouter_standardDeviation: number;
  egressrouter_rawHexSample: string;
  egressrouter_metadataTag: Record<string, string>;
  configuredbandwidth_primaryMetric: number;
  configuredbandwidth_secondaryMetric: number;
  configuredbandwidth_baselineAverage: number;
  configuredbandwidth_peakObserved: number;
  configuredbandwidth_standardDeviation: number;
  configuredbandwidth_rawHexSample: string;
  configuredbandwidth_metadataTag: Record<string, string>;
  actualthroughput_primaryMetric: number;
  actualthroughput_secondaryMetric: number;
  actualthroughput_baselineAverage: number;
  actualthroughput_peakObserved: number;
  actualthroughput_standardDeviation: number;
  actualthroughput_rawHexSample: string;
  actualthroughput_metadataTag: Record<string, string>;
  fastrerouteactive_primaryMetric: number;
  fastrerouteactive_secondaryMetric: number;
  fastrerouteactive_baselineAverage: number;
  fastrerouteactive_peakObserved: number;
  fastrerouteactive_standardDeviation: number;
  fastrerouteactive_rawHexSample: string;
  fastrerouteactive_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type MplsTeTunnelMetricsFilterV1 = Partial<MplsTeTunnelMetricsRecordV1> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface MplsTeTunnelMetricsRecordV2 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  tunnelid_primaryMetric: number;
  tunnelid_secondaryMetric: number;
  tunnelid_baselineAverage: number;
  tunnelid_peakObserved: number;
  tunnelid_standardDeviation: number;
  tunnelid_rawHexSample: string;
  tunnelid_metadataTag: Record<string, string>;
  ingressrouter_primaryMetric: number;
  ingressrouter_secondaryMetric: number;
  ingressrouter_baselineAverage: number;
  ingressrouter_peakObserved: number;
  ingressrouter_standardDeviation: number;
  ingressrouter_rawHexSample: string;
  ingressrouter_metadataTag: Record<string, string>;
  egressrouter_primaryMetric: number;
  egressrouter_secondaryMetric: number;
  egressrouter_baselineAverage: number;
  egressrouter_peakObserved: number;
  egressrouter_standardDeviation: number;
  egressrouter_rawHexSample: string;
  egressrouter_metadataTag: Record<string, string>;
  configuredbandwidth_primaryMetric: number;
  configuredbandwidth_secondaryMetric: number;
  configuredbandwidth_baselineAverage: number;
  configuredbandwidth_peakObserved: number;
  configuredbandwidth_standardDeviation: number;
  configuredbandwidth_rawHexSample: string;
  configuredbandwidth_metadataTag: Record<string, string>;
  actualthroughput_primaryMetric: number;
  actualthroughput_secondaryMetric: number;
  actualthroughput_baselineAverage: number;
  actualthroughput_peakObserved: number;
  actualthroughput_standardDeviation: number;
  actualthroughput_rawHexSample: string;
  actualthroughput_metadataTag: Record<string, string>;
  fastrerouteactive_primaryMetric: number;
  fastrerouteactive_secondaryMetric: number;
  fastrerouteactive_baselineAverage: number;
  fastrerouteactive_peakObserved: number;
  fastrerouteactive_standardDeviation: number;
  fastrerouteactive_rawHexSample: string;
  fastrerouteactive_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type MplsTeTunnelMetricsFilterV2 = Partial<MplsTeTunnelMetricsRecordV2> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface MplsTeTunnelMetricsRecordV3 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  tunnelid_primaryMetric: number;
  tunnelid_secondaryMetric: number;
  tunnelid_baselineAverage: number;
  tunnelid_peakObserved: number;
  tunnelid_standardDeviation: number;
  tunnelid_rawHexSample: string;
  tunnelid_metadataTag: Record<string, string>;
  ingressrouter_primaryMetric: number;
  ingressrouter_secondaryMetric: number;
  ingressrouter_baselineAverage: number;
  ingressrouter_peakObserved: number;
  ingressrouter_standardDeviation: number;
  ingressrouter_rawHexSample: string;
  ingressrouter_metadataTag: Record<string, string>;
  egressrouter_primaryMetric: number;
  egressrouter_secondaryMetric: number;
  egressrouter_baselineAverage: number;
  egressrouter_peakObserved: number;
  egressrouter_standardDeviation: number;
  egressrouter_rawHexSample: string;
  egressrouter_metadataTag: Record<string, string>;
  configuredbandwidth_primaryMetric: number;
  configuredbandwidth_secondaryMetric: number;
  configuredbandwidth_baselineAverage: number;
  configuredbandwidth_peakObserved: number;
  configuredbandwidth_standardDeviation: number;
  configuredbandwidth_rawHexSample: string;
  configuredbandwidth_metadataTag: Record<string, string>;
  actualthroughput_primaryMetric: number;
  actualthroughput_secondaryMetric: number;
  actualthroughput_baselineAverage: number;
  actualthroughput_peakObserved: number;
  actualthroughput_standardDeviation: number;
  actualthroughput_rawHexSample: string;
  actualthroughput_metadataTag: Record<string, string>;
  fastrerouteactive_primaryMetric: number;
  fastrerouteactive_secondaryMetric: number;
  fastrerouteactive_baselineAverage: number;
  fastrerouteactive_peakObserved: number;
  fastrerouteactive_standardDeviation: number;
  fastrerouteactive_rawHexSample: string;
  fastrerouteactive_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type MplsTeTunnelMetricsFilterV3 = Partial<MplsTeTunnelMetricsRecordV3> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface MplsTeTunnelMetricsRecordV4 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  tunnelid_primaryMetric: number;
  tunnelid_secondaryMetric: number;
  tunnelid_baselineAverage: number;
  tunnelid_peakObserved: number;
  tunnelid_standardDeviation: number;
  tunnelid_rawHexSample: string;
  tunnelid_metadataTag: Record<string, string>;
  ingressrouter_primaryMetric: number;
  ingressrouter_secondaryMetric: number;
  ingressrouter_baselineAverage: number;
  ingressrouter_peakObserved: number;
  ingressrouter_standardDeviation: number;
  ingressrouter_rawHexSample: string;
  ingressrouter_metadataTag: Record<string, string>;
  egressrouter_primaryMetric: number;
  egressrouter_secondaryMetric: number;
  egressrouter_baselineAverage: number;
  egressrouter_peakObserved: number;
  egressrouter_standardDeviation: number;
  egressrouter_rawHexSample: string;
  egressrouter_metadataTag: Record<string, string>;
  configuredbandwidth_primaryMetric: number;
  configuredbandwidth_secondaryMetric: number;
  configuredbandwidth_baselineAverage: number;
  configuredbandwidth_peakObserved: number;
  configuredbandwidth_standardDeviation: number;
  configuredbandwidth_rawHexSample: string;
  configuredbandwidth_metadataTag: Record<string, string>;
  actualthroughput_primaryMetric: number;
  actualthroughput_secondaryMetric: number;
  actualthroughput_baselineAverage: number;
  actualthroughput_peakObserved: number;
  actualthroughput_standardDeviation: number;
  actualthroughput_rawHexSample: string;
  actualthroughput_metadataTag: Record<string, string>;
  fastrerouteactive_primaryMetric: number;
  fastrerouteactive_secondaryMetric: number;
  fastrerouteactive_baselineAverage: number;
  fastrerouteactive_peakObserved: number;
  fastrerouteactive_standardDeviation: number;
  fastrerouteactive_rawHexSample: string;
  fastrerouteactive_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type MplsTeTunnelMetricsFilterV4 = Partial<MplsTeTunnelMetricsRecordV4> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface MplsTeTunnelMetricsRecordV5 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  tunnelid_primaryMetric: number;
  tunnelid_secondaryMetric: number;
  tunnelid_baselineAverage: number;
  tunnelid_peakObserved: number;
  tunnelid_standardDeviation: number;
  tunnelid_rawHexSample: string;
  tunnelid_metadataTag: Record<string, string>;
  ingressrouter_primaryMetric: number;
  ingressrouter_secondaryMetric: number;
  ingressrouter_baselineAverage: number;
  ingressrouter_peakObserved: number;
  ingressrouter_standardDeviation: number;
  ingressrouter_rawHexSample: string;
  ingressrouter_metadataTag: Record<string, string>;
  egressrouter_primaryMetric: number;
  egressrouter_secondaryMetric: number;
  egressrouter_baselineAverage: number;
  egressrouter_peakObserved: number;
  egressrouter_standardDeviation: number;
  egressrouter_rawHexSample: string;
  egressrouter_metadataTag: Record<string, string>;
  configuredbandwidth_primaryMetric: number;
  configuredbandwidth_secondaryMetric: number;
  configuredbandwidth_baselineAverage: number;
  configuredbandwidth_peakObserved: number;
  configuredbandwidth_standardDeviation: number;
  configuredbandwidth_rawHexSample: string;
  configuredbandwidth_metadataTag: Record<string, string>;
  actualthroughput_primaryMetric: number;
  actualthroughput_secondaryMetric: number;
  actualthroughput_baselineAverage: number;
  actualthroughput_peakObserved: number;
  actualthroughput_standardDeviation: number;
  actualthroughput_rawHexSample: string;
  actualthroughput_metadataTag: Record<string, string>;
  fastrerouteactive_primaryMetric: number;
  fastrerouteactive_secondaryMetric: number;
  fastrerouteactive_baselineAverage: number;
  fastrerouteactive_peakObserved: number;
  fastrerouteactive_standardDeviation: number;
  fastrerouteactive_rawHexSample: string;
  fastrerouteactive_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type MplsTeTunnelMetricsFilterV5 = Partial<MplsTeTunnelMetricsRecordV5> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface MplsTeTunnelMetricsRecordV6 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  tunnelid_primaryMetric: number;
  tunnelid_secondaryMetric: number;
  tunnelid_baselineAverage: number;
  tunnelid_peakObserved: number;
  tunnelid_standardDeviation: number;
  tunnelid_rawHexSample: string;
  tunnelid_metadataTag: Record<string, string>;
  ingressrouter_primaryMetric: number;
  ingressrouter_secondaryMetric: number;
  ingressrouter_baselineAverage: number;
  ingressrouter_peakObserved: number;
  ingressrouter_standardDeviation: number;
  ingressrouter_rawHexSample: string;
  ingressrouter_metadataTag: Record<string, string>;
  egressrouter_primaryMetric: number;
  egressrouter_secondaryMetric: number;
  egressrouter_baselineAverage: number;
  egressrouter_peakObserved: number;
  egressrouter_standardDeviation: number;
  egressrouter_rawHexSample: string;
  egressrouter_metadataTag: Record<string, string>;
  configuredbandwidth_primaryMetric: number;
  configuredbandwidth_secondaryMetric: number;
  configuredbandwidth_baselineAverage: number;
  configuredbandwidth_peakObserved: number;
  configuredbandwidth_standardDeviation: number;
  configuredbandwidth_rawHexSample: string;
  configuredbandwidth_metadataTag: Record<string, string>;
  actualthroughput_primaryMetric: number;
  actualthroughput_secondaryMetric: number;
  actualthroughput_baselineAverage: number;
  actualthroughput_peakObserved: number;
  actualthroughput_standardDeviation: number;
  actualthroughput_rawHexSample: string;
  actualthroughput_metadataTag: Record<string, string>;
  fastrerouteactive_primaryMetric: number;
  fastrerouteactive_secondaryMetric: number;
  fastrerouteactive_baselineAverage: number;
  fastrerouteactive_peakObserved: number;
  fastrerouteactive_standardDeviation: number;
  fastrerouteactive_rawHexSample: string;
  fastrerouteactive_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type MplsTeTunnelMetricsFilterV6 = Partial<MplsTeTunnelMetricsRecordV6> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface MplsTeTunnelMetricsRecordV7 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  tunnelid_primaryMetric: number;
  tunnelid_secondaryMetric: number;
  tunnelid_baselineAverage: number;
  tunnelid_peakObserved: number;
  tunnelid_standardDeviation: number;
  tunnelid_rawHexSample: string;
  tunnelid_metadataTag: Record<string, string>;
  ingressrouter_primaryMetric: number;
  ingressrouter_secondaryMetric: number;
  ingressrouter_baselineAverage: number;
  ingressrouter_peakObserved: number;
  ingressrouter_standardDeviation: number;
  ingressrouter_rawHexSample: string;
  ingressrouter_metadataTag: Record<string, string>;
  egressrouter_primaryMetric: number;
  egressrouter_secondaryMetric: number;
  egressrouter_baselineAverage: number;
  egressrouter_peakObserved: number;
  egressrouter_standardDeviation: number;
  egressrouter_rawHexSample: string;
  egressrouter_metadataTag: Record<string, string>;
  configuredbandwidth_primaryMetric: number;
  configuredbandwidth_secondaryMetric: number;
  configuredbandwidth_baselineAverage: number;
  configuredbandwidth_peakObserved: number;
  configuredbandwidth_standardDeviation: number;
  configuredbandwidth_rawHexSample: string;
  configuredbandwidth_metadataTag: Record<string, string>;
  actualthroughput_primaryMetric: number;
  actualthroughput_secondaryMetric: number;
  actualthroughput_baselineAverage: number;
  actualthroughput_peakObserved: number;
  actualthroughput_standardDeviation: number;
  actualthroughput_rawHexSample: string;
  actualthroughput_metadataTag: Record<string, string>;
  fastrerouteactive_primaryMetric: number;
  fastrerouteactive_secondaryMetric: number;
  fastrerouteactive_baselineAverage: number;
  fastrerouteactive_peakObserved: number;
  fastrerouteactive_standardDeviation: number;
  fastrerouteactive_rawHexSample: string;
  fastrerouteactive_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type MplsTeTunnelMetricsFilterV7 = Partial<MplsTeTunnelMetricsRecordV7> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface MplsTeTunnelMetricsRecordV8 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  tunnelid_primaryMetric: number;
  tunnelid_secondaryMetric: number;
  tunnelid_baselineAverage: number;
  tunnelid_peakObserved: number;
  tunnelid_standardDeviation: number;
  tunnelid_rawHexSample: string;
  tunnelid_metadataTag: Record<string, string>;
  ingressrouter_primaryMetric: number;
  ingressrouter_secondaryMetric: number;
  ingressrouter_baselineAverage: number;
  ingressrouter_peakObserved: number;
  ingressrouter_standardDeviation: number;
  ingressrouter_rawHexSample: string;
  ingressrouter_metadataTag: Record<string, string>;
  egressrouter_primaryMetric: number;
  egressrouter_secondaryMetric: number;
  egressrouter_baselineAverage: number;
  egressrouter_peakObserved: number;
  egressrouter_standardDeviation: number;
  egressrouter_rawHexSample: string;
  egressrouter_metadataTag: Record<string, string>;
  configuredbandwidth_primaryMetric: number;
  configuredbandwidth_secondaryMetric: number;
  configuredbandwidth_baselineAverage: number;
  configuredbandwidth_peakObserved: number;
  configuredbandwidth_standardDeviation: number;
  configuredbandwidth_rawHexSample: string;
  configuredbandwidth_metadataTag: Record<string, string>;
  actualthroughput_primaryMetric: number;
  actualthroughput_secondaryMetric: number;
  actualthroughput_baselineAverage: number;
  actualthroughput_peakObserved: number;
  actualthroughput_standardDeviation: number;
  actualthroughput_rawHexSample: string;
  actualthroughput_metadataTag: Record<string, string>;
  fastrerouteactive_primaryMetric: number;
  fastrerouteactive_secondaryMetric: number;
  fastrerouteactive_baselineAverage: number;
  fastrerouteactive_peakObserved: number;
  fastrerouteactive_standardDeviation: number;
  fastrerouteactive_rawHexSample: string;
  fastrerouteactive_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type MplsTeTunnelMetricsFilterV8 = Partial<MplsTeTunnelMetricsRecordV8> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface MplsTeTunnelMetricsRecordV9 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  tunnelid_primaryMetric: number;
  tunnelid_secondaryMetric: number;
  tunnelid_baselineAverage: number;
  tunnelid_peakObserved: number;
  tunnelid_standardDeviation: number;
  tunnelid_rawHexSample: string;
  tunnelid_metadataTag: Record<string, string>;
  ingressrouter_primaryMetric: number;
  ingressrouter_secondaryMetric: number;
  ingressrouter_baselineAverage: number;
  ingressrouter_peakObserved: number;
  ingressrouter_standardDeviation: number;
  ingressrouter_rawHexSample: string;
  ingressrouter_metadataTag: Record<string, string>;
  egressrouter_primaryMetric: number;
  egressrouter_secondaryMetric: number;
  egressrouter_baselineAverage: number;
  egressrouter_peakObserved: number;
  egressrouter_standardDeviation: number;
  egressrouter_rawHexSample: string;
  egressrouter_metadataTag: Record<string, string>;
  configuredbandwidth_primaryMetric: number;
  configuredbandwidth_secondaryMetric: number;
  configuredbandwidth_baselineAverage: number;
  configuredbandwidth_peakObserved: number;
  configuredbandwidth_standardDeviation: number;
  configuredbandwidth_rawHexSample: string;
  configuredbandwidth_metadataTag: Record<string, string>;
  actualthroughput_primaryMetric: number;
  actualthroughput_secondaryMetric: number;
  actualthroughput_baselineAverage: number;
  actualthroughput_peakObserved: number;
  actualthroughput_standardDeviation: number;
  actualthroughput_rawHexSample: string;
  actualthroughput_metadataTag: Record<string, string>;
  fastrerouteactive_primaryMetric: number;
  fastrerouteactive_secondaryMetric: number;
  fastrerouteactive_baselineAverage: number;
  fastrerouteactive_peakObserved: number;
  fastrerouteactive_standardDeviation: number;
  fastrerouteactive_rawHexSample: string;
  fastrerouteactive_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type MplsTeTunnelMetricsFilterV9 = Partial<MplsTeTunnelMetricsRecordV9> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface MplsTeTunnelMetricsRecordV10 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  tunnelid_primaryMetric: number;
  tunnelid_secondaryMetric: number;
  tunnelid_baselineAverage: number;
  tunnelid_peakObserved: number;
  tunnelid_standardDeviation: number;
  tunnelid_rawHexSample: string;
  tunnelid_metadataTag: Record<string, string>;
  ingressrouter_primaryMetric: number;
  ingressrouter_secondaryMetric: number;
  ingressrouter_baselineAverage: number;
  ingressrouter_peakObserved: number;
  ingressrouter_standardDeviation: number;
  ingressrouter_rawHexSample: string;
  ingressrouter_metadataTag: Record<string, string>;
  egressrouter_primaryMetric: number;
  egressrouter_secondaryMetric: number;
  egressrouter_baselineAverage: number;
  egressrouter_peakObserved: number;
  egressrouter_standardDeviation: number;
  egressrouter_rawHexSample: string;
  egressrouter_metadataTag: Record<string, string>;
  configuredbandwidth_primaryMetric: number;
  configuredbandwidth_secondaryMetric: number;
  configuredbandwidth_baselineAverage: number;
  configuredbandwidth_peakObserved: number;
  configuredbandwidth_standardDeviation: number;
  configuredbandwidth_rawHexSample: string;
  configuredbandwidth_metadataTag: Record<string, string>;
  actualthroughput_primaryMetric: number;
  actualthroughput_secondaryMetric: number;
  actualthroughput_baselineAverage: number;
  actualthroughput_peakObserved: number;
  actualthroughput_standardDeviation: number;
  actualthroughput_rawHexSample: string;
  actualthroughput_metadataTag: Record<string, string>;
  fastrerouteactive_primaryMetric: number;
  fastrerouteactive_secondaryMetric: number;
  fastrerouteactive_baselineAverage: number;
  fastrerouteactive_peakObserved: number;
  fastrerouteactive_standardDeviation: number;
  fastrerouteactive_rawHexSample: string;
  fastrerouteactive_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type MplsTeTunnelMetricsFilterV10 = Partial<MplsTeTunnelMetricsRecordV10> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface MplsTeTunnelMetricsRecordV11 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  tunnelid_primaryMetric: number;
  tunnelid_secondaryMetric: number;
  tunnelid_baselineAverage: number;
  tunnelid_peakObserved: number;
  tunnelid_standardDeviation: number;
  tunnelid_rawHexSample: string;
  tunnelid_metadataTag: Record<string, string>;
  ingressrouter_primaryMetric: number;
  ingressrouter_secondaryMetric: number;
  ingressrouter_baselineAverage: number;
  ingressrouter_peakObserved: number;
  ingressrouter_standardDeviation: number;
  ingressrouter_rawHexSample: string;
  ingressrouter_metadataTag: Record<string, string>;
  egressrouter_primaryMetric: number;
  egressrouter_secondaryMetric: number;
  egressrouter_baselineAverage: number;
  egressrouter_peakObserved: number;
  egressrouter_standardDeviation: number;
  egressrouter_rawHexSample: string;
  egressrouter_metadataTag: Record<string, string>;
  configuredbandwidth_primaryMetric: number;
  configuredbandwidth_secondaryMetric: number;
  configuredbandwidth_baselineAverage: number;
  configuredbandwidth_peakObserved: number;
  configuredbandwidth_standardDeviation: number;
  configuredbandwidth_rawHexSample: string;
  configuredbandwidth_metadataTag: Record<string, string>;
  actualthroughput_primaryMetric: number;
  actualthroughput_secondaryMetric: number;
  actualthroughput_baselineAverage: number;
  actualthroughput_peakObserved: number;
  actualthroughput_standardDeviation: number;
  actualthroughput_rawHexSample: string;
  actualthroughput_metadataTag: Record<string, string>;
  fastrerouteactive_primaryMetric: number;
  fastrerouteactive_secondaryMetric: number;
  fastrerouteactive_baselineAverage: number;
  fastrerouteactive_peakObserved: number;
  fastrerouteactive_standardDeviation: number;
  fastrerouteactive_rawHexSample: string;
  fastrerouteactive_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type MplsTeTunnelMetricsFilterV11 = Partial<MplsTeTunnelMetricsRecordV11> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface MplsTeTunnelMetricsRecordV12 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  tunnelid_primaryMetric: number;
  tunnelid_secondaryMetric: number;
  tunnelid_baselineAverage: number;
  tunnelid_peakObserved: number;
  tunnelid_standardDeviation: number;
  tunnelid_rawHexSample: string;
  tunnelid_metadataTag: Record<string, string>;
  ingressrouter_primaryMetric: number;
  ingressrouter_secondaryMetric: number;
  ingressrouter_baselineAverage: number;
  ingressrouter_peakObserved: number;
  ingressrouter_standardDeviation: number;
  ingressrouter_rawHexSample: string;
  ingressrouter_metadataTag: Record<string, string>;
  egressrouter_primaryMetric: number;
  egressrouter_secondaryMetric: number;
  egressrouter_baselineAverage: number;
  egressrouter_peakObserved: number;
  egressrouter_standardDeviation: number;
  egressrouter_rawHexSample: string;
  egressrouter_metadataTag: Record<string, string>;
  configuredbandwidth_primaryMetric: number;
  configuredbandwidth_secondaryMetric: number;
  configuredbandwidth_baselineAverage: number;
  configuredbandwidth_peakObserved: number;
  configuredbandwidth_standardDeviation: number;
  configuredbandwidth_rawHexSample: string;
  configuredbandwidth_metadataTag: Record<string, string>;
  actualthroughput_primaryMetric: number;
  actualthroughput_secondaryMetric: number;
  actualthroughput_baselineAverage: number;
  actualthroughput_peakObserved: number;
  actualthroughput_standardDeviation: number;
  actualthroughput_rawHexSample: string;
  actualthroughput_metadataTag: Record<string, string>;
  fastrerouteactive_primaryMetric: number;
  fastrerouteactive_secondaryMetric: number;
  fastrerouteactive_baselineAverage: number;
  fastrerouteactive_peakObserved: number;
  fastrerouteactive_standardDeviation: number;
  fastrerouteactive_rawHexSample: string;
  fastrerouteactive_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type MplsTeTunnelMetricsFilterV12 = Partial<MplsTeTunnelMetricsRecordV12> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface MplsTeTunnelMetricsRecordV13 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  tunnelid_primaryMetric: number;
  tunnelid_secondaryMetric: number;
  tunnelid_baselineAverage: number;
  tunnelid_peakObserved: number;
  tunnelid_standardDeviation: number;
  tunnelid_rawHexSample: string;
  tunnelid_metadataTag: Record<string, string>;
  ingressrouter_primaryMetric: number;
  ingressrouter_secondaryMetric: number;
  ingressrouter_baselineAverage: number;
  ingressrouter_peakObserved: number;
  ingressrouter_standardDeviation: number;
  ingressrouter_rawHexSample: string;
  ingressrouter_metadataTag: Record<string, string>;
  egressrouter_primaryMetric: number;
  egressrouter_secondaryMetric: number;
  egressrouter_baselineAverage: number;
  egressrouter_peakObserved: number;
  egressrouter_standardDeviation: number;
  egressrouter_rawHexSample: string;
  egressrouter_metadataTag: Record<string, string>;
  configuredbandwidth_primaryMetric: number;
  configuredbandwidth_secondaryMetric: number;
  configuredbandwidth_baselineAverage: number;
  configuredbandwidth_peakObserved: number;
  configuredbandwidth_standardDeviation: number;
  configuredbandwidth_rawHexSample: string;
  configuredbandwidth_metadataTag: Record<string, string>;
  actualthroughput_primaryMetric: number;
  actualthroughput_secondaryMetric: number;
  actualthroughput_baselineAverage: number;
  actualthroughput_peakObserved: number;
  actualthroughput_standardDeviation: number;
  actualthroughput_rawHexSample: string;
  actualthroughput_metadataTag: Record<string, string>;
  fastrerouteactive_primaryMetric: number;
  fastrerouteactive_secondaryMetric: number;
  fastrerouteactive_baselineAverage: number;
  fastrerouteactive_peakObserved: number;
  fastrerouteactive_standardDeviation: number;
  fastrerouteactive_rawHexSample: string;
  fastrerouteactive_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type MplsTeTunnelMetricsFilterV13 = Partial<MplsTeTunnelMetricsRecordV13> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface MplsTeTunnelMetricsRecordV14 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  tunnelid_primaryMetric: number;
  tunnelid_secondaryMetric: number;
  tunnelid_baselineAverage: number;
  tunnelid_peakObserved: number;
  tunnelid_standardDeviation: number;
  tunnelid_rawHexSample: string;
  tunnelid_metadataTag: Record<string, string>;
  ingressrouter_primaryMetric: number;
  ingressrouter_secondaryMetric: number;
  ingressrouter_baselineAverage: number;
  ingressrouter_peakObserved: number;
  ingressrouter_standardDeviation: number;
  ingressrouter_rawHexSample: string;
  ingressrouter_metadataTag: Record<string, string>;
  egressrouter_primaryMetric: number;
  egressrouter_secondaryMetric: number;
  egressrouter_baselineAverage: number;
  egressrouter_peakObserved: number;
  egressrouter_standardDeviation: number;
  egressrouter_rawHexSample: string;
  egressrouter_metadataTag: Record<string, string>;
  configuredbandwidth_primaryMetric: number;
  configuredbandwidth_secondaryMetric: number;
  configuredbandwidth_baselineAverage: number;
  configuredbandwidth_peakObserved: number;
  configuredbandwidth_standardDeviation: number;
  configuredbandwidth_rawHexSample: string;
  configuredbandwidth_metadataTag: Record<string, string>;
  actualthroughput_primaryMetric: number;
  actualthroughput_secondaryMetric: number;
  actualthroughput_baselineAverage: number;
  actualthroughput_peakObserved: number;
  actualthroughput_standardDeviation: number;
  actualthroughput_rawHexSample: string;
  actualthroughput_metadataTag: Record<string, string>;
  fastrerouteactive_primaryMetric: number;
  fastrerouteactive_secondaryMetric: number;
  fastrerouteactive_baselineAverage: number;
  fastrerouteactive_peakObserved: number;
  fastrerouteactive_standardDeviation: number;
  fastrerouteactive_rawHexSample: string;
  fastrerouteactive_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type MplsTeTunnelMetricsFilterV14 = Partial<MplsTeTunnelMetricsRecordV14> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface MplsTeTunnelMetricsRecordV15 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  tunnelid_primaryMetric: number;
  tunnelid_secondaryMetric: number;
  tunnelid_baselineAverage: number;
  tunnelid_peakObserved: number;
  tunnelid_standardDeviation: number;
  tunnelid_rawHexSample: string;
  tunnelid_metadataTag: Record<string, string>;
  ingressrouter_primaryMetric: number;
  ingressrouter_secondaryMetric: number;
  ingressrouter_baselineAverage: number;
  ingressrouter_peakObserved: number;
  ingressrouter_standardDeviation: number;
  ingressrouter_rawHexSample: string;
  ingressrouter_metadataTag: Record<string, string>;
  egressrouter_primaryMetric: number;
  egressrouter_secondaryMetric: number;
  egressrouter_baselineAverage: number;
  egressrouter_peakObserved: number;
  egressrouter_standardDeviation: number;
  egressrouter_rawHexSample: string;
  egressrouter_metadataTag: Record<string, string>;
  configuredbandwidth_primaryMetric: number;
  configuredbandwidth_secondaryMetric: number;
  configuredbandwidth_baselineAverage: number;
  configuredbandwidth_peakObserved: number;
  configuredbandwidth_standardDeviation: number;
  configuredbandwidth_rawHexSample: string;
  configuredbandwidth_metadataTag: Record<string, string>;
  actualthroughput_primaryMetric: number;
  actualthroughput_secondaryMetric: number;
  actualthroughput_baselineAverage: number;
  actualthroughput_peakObserved: number;
  actualthroughput_standardDeviation: number;
  actualthroughput_rawHexSample: string;
  actualthroughput_metadataTag: Record<string, string>;
  fastrerouteactive_primaryMetric: number;
  fastrerouteactive_secondaryMetric: number;
  fastrerouteactive_baselineAverage: number;
  fastrerouteactive_peakObserved: number;
  fastrerouteactive_standardDeviation: number;
  fastrerouteactive_rawHexSample: string;
  fastrerouteactive_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type MplsTeTunnelMetricsFilterV15 = Partial<MplsTeTunnelMetricsRecordV15> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface MplsTeTunnelMetricsRecordV16 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  tunnelid_primaryMetric: number;
  tunnelid_secondaryMetric: number;
  tunnelid_baselineAverage: number;
  tunnelid_peakObserved: number;
  tunnelid_standardDeviation: number;
  tunnelid_rawHexSample: string;
  tunnelid_metadataTag: Record<string, string>;
  ingressrouter_primaryMetric: number;
  ingressrouter_secondaryMetric: number;
  ingressrouter_baselineAverage: number;
  ingressrouter_peakObserved: number;
  ingressrouter_standardDeviation: number;
  ingressrouter_rawHexSample: string;
  ingressrouter_metadataTag: Record<string, string>;
  egressrouter_primaryMetric: number;
  egressrouter_secondaryMetric: number;
  egressrouter_baselineAverage: number;
  egressrouter_peakObserved: number;
  egressrouter_standardDeviation: number;
  egressrouter_rawHexSample: string;
  egressrouter_metadataTag: Record<string, string>;
  configuredbandwidth_primaryMetric: number;
  configuredbandwidth_secondaryMetric: number;
  configuredbandwidth_baselineAverage: number;
  configuredbandwidth_peakObserved: number;
  configuredbandwidth_standardDeviation: number;
  configuredbandwidth_rawHexSample: string;
  configuredbandwidth_metadataTag: Record<string, string>;
  actualthroughput_primaryMetric: number;
  actualthroughput_secondaryMetric: number;
  actualthroughput_baselineAverage: number;
  actualthroughput_peakObserved: number;
  actualthroughput_standardDeviation: number;
  actualthroughput_rawHexSample: string;
  actualthroughput_metadataTag: Record<string, string>;
  fastrerouteactive_primaryMetric: number;
  fastrerouteactive_secondaryMetric: number;
  fastrerouteactive_baselineAverage: number;
  fastrerouteactive_peakObserved: number;
  fastrerouteactive_standardDeviation: number;
  fastrerouteactive_rawHexSample: string;
  fastrerouteactive_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type MplsTeTunnelMetricsFilterV16 = Partial<MplsTeTunnelMetricsRecordV16> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface MplsTeTunnelMetricsRecordV17 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  tunnelid_primaryMetric: number;
  tunnelid_secondaryMetric: number;
  tunnelid_baselineAverage: number;
  tunnelid_peakObserved: number;
  tunnelid_standardDeviation: number;
  tunnelid_rawHexSample: string;
  tunnelid_metadataTag: Record<string, string>;
  ingressrouter_primaryMetric: number;
  ingressrouter_secondaryMetric: number;
  ingressrouter_baselineAverage: number;
  ingressrouter_peakObserved: number;
  ingressrouter_standardDeviation: number;
  ingressrouter_rawHexSample: string;
  ingressrouter_metadataTag: Record<string, string>;
  egressrouter_primaryMetric: number;
  egressrouter_secondaryMetric: number;
  egressrouter_baselineAverage: number;
  egressrouter_peakObserved: number;
  egressrouter_standardDeviation: number;
  egressrouter_rawHexSample: string;
  egressrouter_metadataTag: Record<string, string>;
  configuredbandwidth_primaryMetric: number;
  configuredbandwidth_secondaryMetric: number;
  configuredbandwidth_baselineAverage: number;
  configuredbandwidth_peakObserved: number;
  configuredbandwidth_standardDeviation: number;
  configuredbandwidth_rawHexSample: string;
  configuredbandwidth_metadataTag: Record<string, string>;
  actualthroughput_primaryMetric: number;
  actualthroughput_secondaryMetric: number;
  actualthroughput_baselineAverage: number;
  actualthroughput_peakObserved: number;
  actualthroughput_standardDeviation: number;
  actualthroughput_rawHexSample: string;
  actualthroughput_metadataTag: Record<string, string>;
  fastrerouteactive_primaryMetric: number;
  fastrerouteactive_secondaryMetric: number;
  fastrerouteactive_baselineAverage: number;
  fastrerouteactive_peakObserved: number;
  fastrerouteactive_standardDeviation: number;
  fastrerouteactive_rawHexSample: string;
  fastrerouteactive_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type MplsTeTunnelMetricsFilterV17 = Partial<MplsTeTunnelMetricsRecordV17> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface MplsTeTunnelMetricsRecordV18 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  tunnelid_primaryMetric: number;
  tunnelid_secondaryMetric: number;
  tunnelid_baselineAverage: number;
  tunnelid_peakObserved: number;
  tunnelid_standardDeviation: number;
  tunnelid_rawHexSample: string;
  tunnelid_metadataTag: Record<string, string>;
  ingressrouter_primaryMetric: number;
  ingressrouter_secondaryMetric: number;
  ingressrouter_baselineAverage: number;
  ingressrouter_peakObserved: number;
  ingressrouter_standardDeviation: number;
  ingressrouter_rawHexSample: string;
  ingressrouter_metadataTag: Record<string, string>;
  egressrouter_primaryMetric: number;
  egressrouter_secondaryMetric: number;
  egressrouter_baselineAverage: number;
  egressrouter_peakObserved: number;
  egressrouter_standardDeviation: number;
  egressrouter_rawHexSample: string;
  egressrouter_metadataTag: Record<string, string>;
  configuredbandwidth_primaryMetric: number;
  configuredbandwidth_secondaryMetric: number;
  configuredbandwidth_baselineAverage: number;
  configuredbandwidth_peakObserved: number;
  configuredbandwidth_standardDeviation: number;
  configuredbandwidth_rawHexSample: string;
  configuredbandwidth_metadataTag: Record<string, string>;
  actualthroughput_primaryMetric: number;
  actualthroughput_secondaryMetric: number;
  actualthroughput_baselineAverage: number;
  actualthroughput_peakObserved: number;
  actualthroughput_standardDeviation: number;
  actualthroughput_rawHexSample: string;
  actualthroughput_metadataTag: Record<string, string>;
  fastrerouteactive_primaryMetric: number;
  fastrerouteactive_secondaryMetric: number;
  fastrerouteactive_baselineAverage: number;
  fastrerouteactive_peakObserved: number;
  fastrerouteactive_standardDeviation: number;
  fastrerouteactive_rawHexSample: string;
  fastrerouteactive_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type MplsTeTunnelMetricsFilterV18 = Partial<MplsTeTunnelMetricsRecordV18> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface MplsTeTunnelMetricsRecordV19 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  tunnelid_primaryMetric: number;
  tunnelid_secondaryMetric: number;
  tunnelid_baselineAverage: number;
  tunnelid_peakObserved: number;
  tunnelid_standardDeviation: number;
  tunnelid_rawHexSample: string;
  tunnelid_metadataTag: Record<string, string>;
  ingressrouter_primaryMetric: number;
  ingressrouter_secondaryMetric: number;
  ingressrouter_baselineAverage: number;
  ingressrouter_peakObserved: number;
  ingressrouter_standardDeviation: number;
  ingressrouter_rawHexSample: string;
  ingressrouter_metadataTag: Record<string, string>;
  egressrouter_primaryMetric: number;
  egressrouter_secondaryMetric: number;
  egressrouter_baselineAverage: number;
  egressrouter_peakObserved: number;
  egressrouter_standardDeviation: number;
  egressrouter_rawHexSample: string;
  egressrouter_metadataTag: Record<string, string>;
  configuredbandwidth_primaryMetric: number;
  configuredbandwidth_secondaryMetric: number;
  configuredbandwidth_baselineAverage: number;
  configuredbandwidth_peakObserved: number;
  configuredbandwidth_standardDeviation: number;
  configuredbandwidth_rawHexSample: string;
  configuredbandwidth_metadataTag: Record<string, string>;
  actualthroughput_primaryMetric: number;
  actualthroughput_secondaryMetric: number;
  actualthroughput_baselineAverage: number;
  actualthroughput_peakObserved: number;
  actualthroughput_standardDeviation: number;
  actualthroughput_rawHexSample: string;
  actualthroughput_metadataTag: Record<string, string>;
  fastrerouteactive_primaryMetric: number;
  fastrerouteactive_secondaryMetric: number;
  fastrerouteactive_baselineAverage: number;
  fastrerouteactive_peakObserved: number;
  fastrerouteactive_standardDeviation: number;
  fastrerouteactive_rawHexSample: string;
  fastrerouteactive_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type MplsTeTunnelMetricsFilterV19 = Partial<MplsTeTunnelMetricsRecordV19> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface MplsTeTunnelMetricsRecordV20 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  tunnelid_primaryMetric: number;
  tunnelid_secondaryMetric: number;
  tunnelid_baselineAverage: number;
  tunnelid_peakObserved: number;
  tunnelid_standardDeviation: number;
  tunnelid_rawHexSample: string;
  tunnelid_metadataTag: Record<string, string>;
  ingressrouter_primaryMetric: number;
  ingressrouter_secondaryMetric: number;
  ingressrouter_baselineAverage: number;
  ingressrouter_peakObserved: number;
  ingressrouter_standardDeviation: number;
  ingressrouter_rawHexSample: string;
  ingressrouter_metadataTag: Record<string, string>;
  egressrouter_primaryMetric: number;
  egressrouter_secondaryMetric: number;
  egressrouter_baselineAverage: number;
  egressrouter_peakObserved: number;
  egressrouter_standardDeviation: number;
  egressrouter_rawHexSample: string;
  egressrouter_metadataTag: Record<string, string>;
  configuredbandwidth_primaryMetric: number;
  configuredbandwidth_secondaryMetric: number;
  configuredbandwidth_baselineAverage: number;
  configuredbandwidth_peakObserved: number;
  configuredbandwidth_standardDeviation: number;
  configuredbandwidth_rawHexSample: string;
  configuredbandwidth_metadataTag: Record<string, string>;
  actualthroughput_primaryMetric: number;
  actualthroughput_secondaryMetric: number;
  actualthroughput_baselineAverage: number;
  actualthroughput_peakObserved: number;
  actualthroughput_standardDeviation: number;
  actualthroughput_rawHexSample: string;
  actualthroughput_metadataTag: Record<string, string>;
  fastrerouteactive_primaryMetric: number;
  fastrerouteactive_secondaryMetric: number;
  fastrerouteactive_baselineAverage: number;
  fastrerouteactive_peakObserved: number;
  fastrerouteactive_standardDeviation: number;
  fastrerouteactive_rawHexSample: string;
  fastrerouteactive_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type MplsTeTunnelMetricsFilterV20 = Partial<MplsTeTunnelMetricsRecordV20> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface MplsTeTunnelMetricsRecordV21 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  tunnelid_primaryMetric: number;
  tunnelid_secondaryMetric: number;
  tunnelid_baselineAverage: number;
  tunnelid_peakObserved: number;
  tunnelid_standardDeviation: number;
  tunnelid_rawHexSample: string;
  tunnelid_metadataTag: Record<string, string>;
  ingressrouter_primaryMetric: number;
  ingressrouter_secondaryMetric: number;
  ingressrouter_baselineAverage: number;
  ingressrouter_peakObserved: number;
  ingressrouter_standardDeviation: number;
  ingressrouter_rawHexSample: string;
  ingressrouter_metadataTag: Record<string, string>;
  egressrouter_primaryMetric: number;
  egressrouter_secondaryMetric: number;
  egressrouter_baselineAverage: number;
  egressrouter_peakObserved: number;
  egressrouter_standardDeviation: number;
  egressrouter_rawHexSample: string;
  egressrouter_metadataTag: Record<string, string>;
  configuredbandwidth_primaryMetric: number;
  configuredbandwidth_secondaryMetric: number;
  configuredbandwidth_baselineAverage: number;
  configuredbandwidth_peakObserved: number;
  configuredbandwidth_standardDeviation: number;
  configuredbandwidth_rawHexSample: string;
  configuredbandwidth_metadataTag: Record<string, string>;
  actualthroughput_primaryMetric: number;
  actualthroughput_secondaryMetric: number;
  actualthroughput_baselineAverage: number;
  actualthroughput_peakObserved: number;
  actualthroughput_standardDeviation: number;
  actualthroughput_rawHexSample: string;
  actualthroughput_metadataTag: Record<string, string>;
  fastrerouteactive_primaryMetric: number;
  fastrerouteactive_secondaryMetric: number;
  fastrerouteactive_baselineAverage: number;
  fastrerouteactive_peakObserved: number;
  fastrerouteactive_standardDeviation: number;
  fastrerouteactive_rawHexSample: string;
  fastrerouteactive_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type MplsTeTunnelMetricsFilterV21 = Partial<MplsTeTunnelMetricsRecordV21> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface MplsTeTunnelMetricsRecordV22 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  tunnelid_primaryMetric: number;
  tunnelid_secondaryMetric: number;
  tunnelid_baselineAverage: number;
  tunnelid_peakObserved: number;
  tunnelid_standardDeviation: number;
  tunnelid_rawHexSample: string;
  tunnelid_metadataTag: Record<string, string>;
  ingressrouter_primaryMetric: number;
  ingressrouter_secondaryMetric: number;
  ingressrouter_baselineAverage: number;
  ingressrouter_peakObserved: number;
  ingressrouter_standardDeviation: number;
  ingressrouter_rawHexSample: string;
  ingressrouter_metadataTag: Record<string, string>;
  egressrouter_primaryMetric: number;
  egressrouter_secondaryMetric: number;
  egressrouter_baselineAverage: number;
  egressrouter_peakObserved: number;
  egressrouter_standardDeviation: number;
  egressrouter_rawHexSample: string;
  egressrouter_metadataTag: Record<string, string>;
  configuredbandwidth_primaryMetric: number;
  configuredbandwidth_secondaryMetric: number;
  configuredbandwidth_baselineAverage: number;
  configuredbandwidth_peakObserved: number;
  configuredbandwidth_standardDeviation: number;
  configuredbandwidth_rawHexSample: string;
  configuredbandwidth_metadataTag: Record<string, string>;
  actualthroughput_primaryMetric: number;
  actualthroughput_secondaryMetric: number;
  actualthroughput_baselineAverage: number;
  actualthroughput_peakObserved: number;
  actualthroughput_standardDeviation: number;
  actualthroughput_rawHexSample: string;
  actualthroughput_metadataTag: Record<string, string>;
  fastrerouteactive_primaryMetric: number;
  fastrerouteactive_secondaryMetric: number;
  fastrerouteactive_baselineAverage: number;
  fastrerouteactive_peakObserved: number;
  fastrerouteactive_standardDeviation: number;
  fastrerouteactive_rawHexSample: string;
  fastrerouteactive_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type MplsTeTunnelMetricsFilterV22 = Partial<MplsTeTunnelMetricsRecordV22> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface MplsTeTunnelMetricsRecordV23 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  tunnelid_primaryMetric: number;
  tunnelid_secondaryMetric: number;
  tunnelid_baselineAverage: number;
  tunnelid_peakObserved: number;
  tunnelid_standardDeviation: number;
  tunnelid_rawHexSample: string;
  tunnelid_metadataTag: Record<string, string>;
  ingressrouter_primaryMetric: number;
  ingressrouter_secondaryMetric: number;
  ingressrouter_baselineAverage: number;
  ingressrouter_peakObserved: number;
  ingressrouter_standardDeviation: number;
  ingressrouter_rawHexSample: string;
  ingressrouter_metadataTag: Record<string, string>;
  egressrouter_primaryMetric: number;
  egressrouter_secondaryMetric: number;
  egressrouter_baselineAverage: number;
  egressrouter_peakObserved: number;
  egressrouter_standardDeviation: number;
  egressrouter_rawHexSample: string;
  egressrouter_metadataTag: Record<string, string>;
  configuredbandwidth_primaryMetric: number;
  configuredbandwidth_secondaryMetric: number;
  configuredbandwidth_baselineAverage: number;
  configuredbandwidth_peakObserved: number;
  configuredbandwidth_standardDeviation: number;
  configuredbandwidth_rawHexSample: string;
  configuredbandwidth_metadataTag: Record<string, string>;
  actualthroughput_primaryMetric: number;
  actualthroughput_secondaryMetric: number;
  actualthroughput_baselineAverage: number;
  actualthroughput_peakObserved: number;
  actualthroughput_standardDeviation: number;
  actualthroughput_rawHexSample: string;
  actualthroughput_metadataTag: Record<string, string>;
  fastrerouteactive_primaryMetric: number;
  fastrerouteactive_secondaryMetric: number;
  fastrerouteactive_baselineAverage: number;
  fastrerouteactive_peakObserved: number;
  fastrerouteactive_standardDeviation: number;
  fastrerouteactive_rawHexSample: string;
  fastrerouteactive_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type MplsTeTunnelMetricsFilterV23 = Partial<MplsTeTunnelMetricsRecordV23> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface MplsTeTunnelMetricsRecordV24 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  tunnelid_primaryMetric: number;
  tunnelid_secondaryMetric: number;
  tunnelid_baselineAverage: number;
  tunnelid_peakObserved: number;
  tunnelid_standardDeviation: number;
  tunnelid_rawHexSample: string;
  tunnelid_metadataTag: Record<string, string>;
  ingressrouter_primaryMetric: number;
  ingressrouter_secondaryMetric: number;
  ingressrouter_baselineAverage: number;
  ingressrouter_peakObserved: number;
  ingressrouter_standardDeviation: number;
  ingressrouter_rawHexSample: string;
  ingressrouter_metadataTag: Record<string, string>;
  egressrouter_primaryMetric: number;
  egressrouter_secondaryMetric: number;
  egressrouter_baselineAverage: number;
  egressrouter_peakObserved: number;
  egressrouter_standardDeviation: number;
  egressrouter_rawHexSample: string;
  egressrouter_metadataTag: Record<string, string>;
  configuredbandwidth_primaryMetric: number;
  configuredbandwidth_secondaryMetric: number;
  configuredbandwidth_baselineAverage: number;
  configuredbandwidth_peakObserved: number;
  configuredbandwidth_standardDeviation: number;
  configuredbandwidth_rawHexSample: string;
  configuredbandwidth_metadataTag: Record<string, string>;
  actualthroughput_primaryMetric: number;
  actualthroughput_secondaryMetric: number;
  actualthroughput_baselineAverage: number;
  actualthroughput_peakObserved: number;
  actualthroughput_standardDeviation: number;
  actualthroughput_rawHexSample: string;
  actualthroughput_metadataTag: Record<string, string>;
  fastrerouteactive_primaryMetric: number;
  fastrerouteactive_secondaryMetric: number;
  fastrerouteactive_baselineAverage: number;
  fastrerouteactive_peakObserved: number;
  fastrerouteactive_standardDeviation: number;
  fastrerouteactive_rawHexSample: string;
  fastrerouteactive_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type MplsTeTunnelMetricsFilterV24 = Partial<MplsTeTunnelMetricsRecordV24> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface MplsTeTunnelMetricsRecordV25 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  tunnelid_primaryMetric: number;
  tunnelid_secondaryMetric: number;
  tunnelid_baselineAverage: number;
  tunnelid_peakObserved: number;
  tunnelid_standardDeviation: number;
  tunnelid_rawHexSample: string;
  tunnelid_metadataTag: Record<string, string>;
  ingressrouter_primaryMetric: number;
  ingressrouter_secondaryMetric: number;
  ingressrouter_baselineAverage: number;
  ingressrouter_peakObserved: number;
  ingressrouter_standardDeviation: number;
  ingressrouter_rawHexSample: string;
  ingressrouter_metadataTag: Record<string, string>;
  egressrouter_primaryMetric: number;
  egressrouter_secondaryMetric: number;
  egressrouter_baselineAverage: number;
  egressrouter_peakObserved: number;
  egressrouter_standardDeviation: number;
  egressrouter_rawHexSample: string;
  egressrouter_metadataTag: Record<string, string>;
  configuredbandwidth_primaryMetric: number;
  configuredbandwidth_secondaryMetric: number;
  configuredbandwidth_baselineAverage: number;
  configuredbandwidth_peakObserved: number;
  configuredbandwidth_standardDeviation: number;
  configuredbandwidth_rawHexSample: string;
  configuredbandwidth_metadataTag: Record<string, string>;
  actualthroughput_primaryMetric: number;
  actualthroughput_secondaryMetric: number;
  actualthroughput_baselineAverage: number;
  actualthroughput_peakObserved: number;
  actualthroughput_standardDeviation: number;
  actualthroughput_rawHexSample: string;
  actualthroughput_metadataTag: Record<string, string>;
  fastrerouteactive_primaryMetric: number;
  fastrerouteactive_secondaryMetric: number;
  fastrerouteactive_baselineAverage: number;
  fastrerouteactive_peakObserved: number;
  fastrerouteactive_standardDeviation: number;
  fastrerouteactive_rawHexSample: string;
  fastrerouteactive_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type MplsTeTunnelMetricsFilterV25 = Partial<MplsTeTunnelMetricsRecordV25> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface MplsTeTunnelMetricsRecordV26 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  tunnelid_primaryMetric: number;
  tunnelid_secondaryMetric: number;
  tunnelid_baselineAverage: number;
  tunnelid_peakObserved: number;
  tunnelid_standardDeviation: number;
  tunnelid_rawHexSample: string;
  tunnelid_metadataTag: Record<string, string>;
  ingressrouter_primaryMetric: number;
  ingressrouter_secondaryMetric: number;
  ingressrouter_baselineAverage: number;
  ingressrouter_peakObserved: number;
  ingressrouter_standardDeviation: number;
  ingressrouter_rawHexSample: string;
  ingressrouter_metadataTag: Record<string, string>;
  egressrouter_primaryMetric: number;
  egressrouter_secondaryMetric: number;
  egressrouter_baselineAverage: number;
  egressrouter_peakObserved: number;
  egressrouter_standardDeviation: number;
  egressrouter_rawHexSample: string;
  egressrouter_metadataTag: Record<string, string>;
  configuredbandwidth_primaryMetric: number;
  configuredbandwidth_secondaryMetric: number;
  configuredbandwidth_baselineAverage: number;
  configuredbandwidth_peakObserved: number;
  configuredbandwidth_standardDeviation: number;
  configuredbandwidth_rawHexSample: string;
  configuredbandwidth_metadataTag: Record<string, string>;
  actualthroughput_primaryMetric: number;
  actualthroughput_secondaryMetric: number;
  actualthroughput_baselineAverage: number;
  actualthroughput_peakObserved: number;
  actualthroughput_standardDeviation: number;
  actualthroughput_rawHexSample: string;
  actualthroughput_metadataTag: Record<string, string>;
  fastrerouteactive_primaryMetric: number;
  fastrerouteactive_secondaryMetric: number;
  fastrerouteactive_baselineAverage: number;
  fastrerouteactive_peakObserved: number;
  fastrerouteactive_standardDeviation: number;
  fastrerouteactive_rawHexSample: string;
  fastrerouteactive_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type MplsTeTunnelMetricsFilterV26 = Partial<MplsTeTunnelMetricsRecordV26> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface MplsTeTunnelMetricsRecordV27 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  tunnelid_primaryMetric: number;
  tunnelid_secondaryMetric: number;
  tunnelid_baselineAverage: number;
  tunnelid_peakObserved: number;
  tunnelid_standardDeviation: number;
  tunnelid_rawHexSample: string;
  tunnelid_metadataTag: Record<string, string>;
  ingressrouter_primaryMetric: number;
  ingressrouter_secondaryMetric: number;
  ingressrouter_baselineAverage: number;
  ingressrouter_peakObserved: number;
  ingressrouter_standardDeviation: number;
  ingressrouter_rawHexSample: string;
  ingressrouter_metadataTag: Record<string, string>;
  egressrouter_primaryMetric: number;
  egressrouter_secondaryMetric: number;
  egressrouter_baselineAverage: number;
  egressrouter_peakObserved: number;
  egressrouter_standardDeviation: number;
  egressrouter_rawHexSample: string;
  egressrouter_metadataTag: Record<string, string>;
  configuredbandwidth_primaryMetric: number;
  configuredbandwidth_secondaryMetric: number;
  configuredbandwidth_baselineAverage: number;
  configuredbandwidth_peakObserved: number;
  configuredbandwidth_standardDeviation: number;
  configuredbandwidth_rawHexSample: string;
  configuredbandwidth_metadataTag: Record<string, string>;
  actualthroughput_primaryMetric: number;
  actualthroughput_secondaryMetric: number;
  actualthroughput_baselineAverage: number;
  actualthroughput_peakObserved: number;
  actualthroughput_standardDeviation: number;
  actualthroughput_rawHexSample: string;
  actualthroughput_metadataTag: Record<string, string>;
  fastrerouteactive_primaryMetric: number;
  fastrerouteactive_secondaryMetric: number;
  fastrerouteactive_baselineAverage: number;
  fastrerouteactive_peakObserved: number;
  fastrerouteactive_standardDeviation: number;
  fastrerouteactive_rawHexSample: string;
  fastrerouteactive_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type MplsTeTunnelMetricsFilterV27 = Partial<MplsTeTunnelMetricsRecordV27> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface MplsTeTunnelMetricsRecordV28 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  tunnelid_primaryMetric: number;
  tunnelid_secondaryMetric: number;
  tunnelid_baselineAverage: number;
  tunnelid_peakObserved: number;
  tunnelid_standardDeviation: number;
  tunnelid_rawHexSample: string;
  tunnelid_metadataTag: Record<string, string>;
  ingressrouter_primaryMetric: number;
  ingressrouter_secondaryMetric: number;
  ingressrouter_baselineAverage: number;
  ingressrouter_peakObserved: number;
  ingressrouter_standardDeviation: number;
  ingressrouter_rawHexSample: string;
  ingressrouter_metadataTag: Record<string, string>;
  egressrouter_primaryMetric: number;
  egressrouter_secondaryMetric: number;
  egressrouter_baselineAverage: number;
  egressrouter_peakObserved: number;
  egressrouter_standardDeviation: number;
  egressrouter_rawHexSample: string;
  egressrouter_metadataTag: Record<string, string>;
  configuredbandwidth_primaryMetric: number;
  configuredbandwidth_secondaryMetric: number;
  configuredbandwidth_baselineAverage: number;
  configuredbandwidth_peakObserved: number;
  configuredbandwidth_standardDeviation: number;
  configuredbandwidth_rawHexSample: string;
  configuredbandwidth_metadataTag: Record<string, string>;
  actualthroughput_primaryMetric: number;
  actualthroughput_secondaryMetric: number;
  actualthroughput_baselineAverage: number;
  actualthroughput_peakObserved: number;
  actualthroughput_standardDeviation: number;
  actualthroughput_rawHexSample: string;
  actualthroughput_metadataTag: Record<string, string>;
  fastrerouteactive_primaryMetric: number;
  fastrerouteactive_secondaryMetric: number;
  fastrerouteactive_baselineAverage: number;
  fastrerouteactive_peakObserved: number;
  fastrerouteactive_standardDeviation: number;
  fastrerouteactive_rawHexSample: string;
  fastrerouteactive_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type MplsTeTunnelMetricsFilterV28 = Partial<MplsTeTunnelMetricsRecordV28> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface MplsTeTunnelMetricsRecordV29 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  tunnelid_primaryMetric: number;
  tunnelid_secondaryMetric: number;
  tunnelid_baselineAverage: number;
  tunnelid_peakObserved: number;
  tunnelid_standardDeviation: number;
  tunnelid_rawHexSample: string;
  tunnelid_metadataTag: Record<string, string>;
  ingressrouter_primaryMetric: number;
  ingressrouter_secondaryMetric: number;
  ingressrouter_baselineAverage: number;
  ingressrouter_peakObserved: number;
  ingressrouter_standardDeviation: number;
  ingressrouter_rawHexSample: string;
  ingressrouter_metadataTag: Record<string, string>;
  egressrouter_primaryMetric: number;
  egressrouter_secondaryMetric: number;
  egressrouter_baselineAverage: number;
  egressrouter_peakObserved: number;
  egressrouter_standardDeviation: number;
  egressrouter_rawHexSample: string;
  egressrouter_metadataTag: Record<string, string>;
  configuredbandwidth_primaryMetric: number;
  configuredbandwidth_secondaryMetric: number;
  configuredbandwidth_baselineAverage: number;
  configuredbandwidth_peakObserved: number;
  configuredbandwidth_standardDeviation: number;
  configuredbandwidth_rawHexSample: string;
  configuredbandwidth_metadataTag: Record<string, string>;
  actualthroughput_primaryMetric: number;
  actualthroughput_secondaryMetric: number;
  actualthroughput_baselineAverage: number;
  actualthroughput_peakObserved: number;
  actualthroughput_standardDeviation: number;
  actualthroughput_rawHexSample: string;
  actualthroughput_metadataTag: Record<string, string>;
  fastrerouteactive_primaryMetric: number;
  fastrerouteactive_secondaryMetric: number;
  fastrerouteactive_baselineAverage: number;
  fastrerouteactive_peakObserved: number;
  fastrerouteactive_standardDeviation: number;
  fastrerouteactive_rawHexSample: string;
  fastrerouteactive_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type MplsTeTunnelMetricsFilterV29 = Partial<MplsTeTunnelMetricsRecordV29> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface MplsTeTunnelMetricsRecordV30 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  tunnelid_primaryMetric: number;
  tunnelid_secondaryMetric: number;
  tunnelid_baselineAverage: number;
  tunnelid_peakObserved: number;
  tunnelid_standardDeviation: number;
  tunnelid_rawHexSample: string;
  tunnelid_metadataTag: Record<string, string>;
  ingressrouter_primaryMetric: number;
  ingressrouter_secondaryMetric: number;
  ingressrouter_baselineAverage: number;
  ingressrouter_peakObserved: number;
  ingressrouter_standardDeviation: number;
  ingressrouter_rawHexSample: string;
  ingressrouter_metadataTag: Record<string, string>;
  egressrouter_primaryMetric: number;
  egressrouter_secondaryMetric: number;
  egressrouter_baselineAverage: number;
  egressrouter_peakObserved: number;
  egressrouter_standardDeviation: number;
  egressrouter_rawHexSample: string;
  egressrouter_metadataTag: Record<string, string>;
  configuredbandwidth_primaryMetric: number;
  configuredbandwidth_secondaryMetric: number;
  configuredbandwidth_baselineAverage: number;
  configuredbandwidth_peakObserved: number;
  configuredbandwidth_standardDeviation: number;
  configuredbandwidth_rawHexSample: string;
  configuredbandwidth_metadataTag: Record<string, string>;
  actualthroughput_primaryMetric: number;
  actualthroughput_secondaryMetric: number;
  actualthroughput_baselineAverage: number;
  actualthroughput_peakObserved: number;
  actualthroughput_standardDeviation: number;
  actualthroughput_rawHexSample: string;
  actualthroughput_metadataTag: Record<string, string>;
  fastrerouteactive_primaryMetric: number;
  fastrerouteactive_secondaryMetric: number;
  fastrerouteactive_baselineAverage: number;
  fastrerouteactive_peakObserved: number;
  fastrerouteactive_standardDeviation: number;
  fastrerouteactive_rawHexSample: string;
  fastrerouteactive_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type MplsTeTunnelMetricsFilterV30 = Partial<MplsTeTunnelMetricsRecordV30> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface MplsTeTunnelMetricsRecordV31 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  tunnelid_primaryMetric: number;
  tunnelid_secondaryMetric: number;
  tunnelid_baselineAverage: number;
  tunnelid_peakObserved: number;
  tunnelid_standardDeviation: number;
  tunnelid_rawHexSample: string;
  tunnelid_metadataTag: Record<string, string>;
  ingressrouter_primaryMetric: number;
  ingressrouter_secondaryMetric: number;
  ingressrouter_baselineAverage: number;
  ingressrouter_peakObserved: number;
  ingressrouter_standardDeviation: number;
  ingressrouter_rawHexSample: string;
  ingressrouter_metadataTag: Record<string, string>;
  egressrouter_primaryMetric: number;
  egressrouter_secondaryMetric: number;
  egressrouter_baselineAverage: number;
  egressrouter_peakObserved: number;
  egressrouter_standardDeviation: number;
  egressrouter_rawHexSample: string;
  egressrouter_metadataTag: Record<string, string>;
  configuredbandwidth_primaryMetric: number;
  configuredbandwidth_secondaryMetric: number;
  configuredbandwidth_baselineAverage: number;
  configuredbandwidth_peakObserved: number;
  configuredbandwidth_standardDeviation: number;
  configuredbandwidth_rawHexSample: string;
  configuredbandwidth_metadataTag: Record<string, string>;
  actualthroughput_primaryMetric: number;
  actualthroughput_secondaryMetric: number;
  actualthroughput_baselineAverage: number;
  actualthroughput_peakObserved: number;
  actualthroughput_standardDeviation: number;
  actualthroughput_rawHexSample: string;
  actualthroughput_metadataTag: Record<string, string>;
  fastrerouteactive_primaryMetric: number;
  fastrerouteactive_secondaryMetric: number;
  fastrerouteactive_baselineAverage: number;
  fastrerouteactive_peakObserved: number;
  fastrerouteactive_standardDeviation: number;
  fastrerouteactive_rawHexSample: string;
  fastrerouteactive_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type MplsTeTunnelMetricsFilterV31 = Partial<MplsTeTunnelMetricsRecordV31> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface MplsTeTunnelMetricsRecordV32 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  tunnelid_primaryMetric: number;
  tunnelid_secondaryMetric: number;
  tunnelid_baselineAverage: number;
  tunnelid_peakObserved: number;
  tunnelid_standardDeviation: number;
  tunnelid_rawHexSample: string;
  tunnelid_metadataTag: Record<string, string>;
  ingressrouter_primaryMetric: number;
  ingressrouter_secondaryMetric: number;
  ingressrouter_baselineAverage: number;
  ingressrouter_peakObserved: number;
  ingressrouter_standardDeviation: number;
  ingressrouter_rawHexSample: string;
  ingressrouter_metadataTag: Record<string, string>;
  egressrouter_primaryMetric: number;
  egressrouter_secondaryMetric: number;
  egressrouter_baselineAverage: number;
  egressrouter_peakObserved: number;
  egressrouter_standardDeviation: number;
  egressrouter_rawHexSample: string;
  egressrouter_metadataTag: Record<string, string>;
  configuredbandwidth_primaryMetric: number;
  configuredbandwidth_secondaryMetric: number;
  configuredbandwidth_baselineAverage: number;
  configuredbandwidth_peakObserved: number;
  configuredbandwidth_standardDeviation: number;
  configuredbandwidth_rawHexSample: string;
  configuredbandwidth_metadataTag: Record<string, string>;
  actualthroughput_primaryMetric: number;
  actualthroughput_secondaryMetric: number;
  actualthroughput_baselineAverage: number;
  actualthroughput_peakObserved: number;
  actualthroughput_standardDeviation: number;
  actualthroughput_rawHexSample: string;
  actualthroughput_metadataTag: Record<string, string>;
  fastrerouteactive_primaryMetric: number;
  fastrerouteactive_secondaryMetric: number;
  fastrerouteactive_baselineAverage: number;
  fastrerouteactive_peakObserved: number;
  fastrerouteactive_standardDeviation: number;
  fastrerouteactive_rawHexSample: string;
  fastrerouteactive_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type MplsTeTunnelMetricsFilterV32 = Partial<MplsTeTunnelMetricsRecordV32> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface MplsTeTunnelMetricsRecordV33 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  tunnelid_primaryMetric: number;
  tunnelid_secondaryMetric: number;
  tunnelid_baselineAverage: number;
  tunnelid_peakObserved: number;
  tunnelid_standardDeviation: number;
  tunnelid_rawHexSample: string;
  tunnelid_metadataTag: Record<string, string>;
  ingressrouter_primaryMetric: number;
  ingressrouter_secondaryMetric: number;
  ingressrouter_baselineAverage: number;
  ingressrouter_peakObserved: number;
  ingressrouter_standardDeviation: number;
  ingressrouter_rawHexSample: string;
  ingressrouter_metadataTag: Record<string, string>;
  egressrouter_primaryMetric: number;
  egressrouter_secondaryMetric: number;
  egressrouter_baselineAverage: number;
  egressrouter_peakObserved: number;
  egressrouter_standardDeviation: number;
  egressrouter_rawHexSample: string;
  egressrouter_metadataTag: Record<string, string>;
  configuredbandwidth_primaryMetric: number;
  configuredbandwidth_secondaryMetric: number;
  configuredbandwidth_baselineAverage: number;
  configuredbandwidth_peakObserved: number;
  configuredbandwidth_standardDeviation: number;
  configuredbandwidth_rawHexSample: string;
  configuredbandwidth_metadataTag: Record<string, string>;
  actualthroughput_primaryMetric: number;
  actualthroughput_secondaryMetric: number;
  actualthroughput_baselineAverage: number;
  actualthroughput_peakObserved: number;
  actualthroughput_standardDeviation: number;
  actualthroughput_rawHexSample: string;
  actualthroughput_metadataTag: Record<string, string>;
  fastrerouteactive_primaryMetric: number;
  fastrerouteactive_secondaryMetric: number;
  fastrerouteactive_baselineAverage: number;
  fastrerouteactive_peakObserved: number;
  fastrerouteactive_standardDeviation: number;
  fastrerouteactive_rawHexSample: string;
  fastrerouteactive_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type MplsTeTunnelMetricsFilterV33 = Partial<MplsTeTunnelMetricsRecordV33> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface MplsTeTunnelMetricsRecordV34 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  tunnelid_primaryMetric: number;
  tunnelid_secondaryMetric: number;
  tunnelid_baselineAverage: number;
  tunnelid_peakObserved: number;
  tunnelid_standardDeviation: number;
  tunnelid_rawHexSample: string;
  tunnelid_metadataTag: Record<string, string>;
  ingressrouter_primaryMetric: number;
  ingressrouter_secondaryMetric: number;
  ingressrouter_baselineAverage: number;
  ingressrouter_peakObserved: number;
  ingressrouter_standardDeviation: number;
  ingressrouter_rawHexSample: string;
  ingressrouter_metadataTag: Record<string, string>;
  egressrouter_primaryMetric: number;
  egressrouter_secondaryMetric: number;
  egressrouter_baselineAverage: number;
  egressrouter_peakObserved: number;
  egressrouter_standardDeviation: number;
  egressrouter_rawHexSample: string;
  egressrouter_metadataTag: Record<string, string>;
  configuredbandwidth_primaryMetric: number;
  configuredbandwidth_secondaryMetric: number;
  configuredbandwidth_baselineAverage: number;
  configuredbandwidth_peakObserved: number;
  configuredbandwidth_standardDeviation: number;
  configuredbandwidth_rawHexSample: string;
  configuredbandwidth_metadataTag: Record<string, string>;
  actualthroughput_primaryMetric: number;
  actualthroughput_secondaryMetric: number;
  actualthroughput_baselineAverage: number;
  actualthroughput_peakObserved: number;
  actualthroughput_standardDeviation: number;
  actualthroughput_rawHexSample: string;
  actualthroughput_metadataTag: Record<string, string>;
  fastrerouteactive_primaryMetric: number;
  fastrerouteactive_secondaryMetric: number;
  fastrerouteactive_baselineAverage: number;
  fastrerouteactive_peakObserved: number;
  fastrerouteactive_standardDeviation: number;
  fastrerouteactive_rawHexSample: string;
  fastrerouteactive_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type MplsTeTunnelMetricsFilterV34 = Partial<MplsTeTunnelMetricsRecordV34> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface MplsTeTunnelMetricsRecordV35 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  tunnelid_primaryMetric: number;
  tunnelid_secondaryMetric: number;
  tunnelid_baselineAverage: number;
  tunnelid_peakObserved: number;
  tunnelid_standardDeviation: number;
  tunnelid_rawHexSample: string;
  tunnelid_metadataTag: Record<string, string>;
  ingressrouter_primaryMetric: number;
  ingressrouter_secondaryMetric: number;
  ingressrouter_baselineAverage: number;
  ingressrouter_peakObserved: number;
  ingressrouter_standardDeviation: number;
  ingressrouter_rawHexSample: string;
  ingressrouter_metadataTag: Record<string, string>;
  egressrouter_primaryMetric: number;
  egressrouter_secondaryMetric: number;
  egressrouter_baselineAverage: number;
  egressrouter_peakObserved: number;
  egressrouter_standardDeviation: number;
  egressrouter_rawHexSample: string;
  egressrouter_metadataTag: Record<string, string>;
  configuredbandwidth_primaryMetric: number;
  configuredbandwidth_secondaryMetric: number;
  configuredbandwidth_baselineAverage: number;
  configuredbandwidth_peakObserved: number;
  configuredbandwidth_standardDeviation: number;
  configuredbandwidth_rawHexSample: string;
  configuredbandwidth_metadataTag: Record<string, string>;
  actualthroughput_primaryMetric: number;
  actualthroughput_secondaryMetric: number;
  actualthroughput_baselineAverage: number;
  actualthroughput_peakObserved: number;
  actualthroughput_standardDeviation: number;
  actualthroughput_rawHexSample: string;
  actualthroughput_metadataTag: Record<string, string>;
  fastrerouteactive_primaryMetric: number;
  fastrerouteactive_secondaryMetric: number;
  fastrerouteactive_baselineAverage: number;
  fastrerouteactive_peakObserved: number;
  fastrerouteactive_standardDeviation: number;
  fastrerouteactive_rawHexSample: string;
  fastrerouteactive_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type MplsTeTunnelMetricsFilterV35 = Partial<MplsTeTunnelMetricsRecordV35> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface MplsTeTunnelMetricsRecordV36 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  tunnelid_primaryMetric: number;
  tunnelid_secondaryMetric: number;
  tunnelid_baselineAverage: number;
  tunnelid_peakObserved: number;
  tunnelid_standardDeviation: number;
  tunnelid_rawHexSample: string;
  tunnelid_metadataTag: Record<string, string>;
  ingressrouter_primaryMetric: number;
  ingressrouter_secondaryMetric: number;
  ingressrouter_baselineAverage: number;
  ingressrouter_peakObserved: number;
  ingressrouter_standardDeviation: number;
  ingressrouter_rawHexSample: string;
  ingressrouter_metadataTag: Record<string, string>;
  egressrouter_primaryMetric: number;
  egressrouter_secondaryMetric: number;
  egressrouter_baselineAverage: number;
  egressrouter_peakObserved: number;
  egressrouter_standardDeviation: number;
  egressrouter_rawHexSample: string;
  egressrouter_metadataTag: Record<string, string>;
  configuredbandwidth_primaryMetric: number;
  configuredbandwidth_secondaryMetric: number;
  configuredbandwidth_baselineAverage: number;
  configuredbandwidth_peakObserved: number;
  configuredbandwidth_standardDeviation: number;
  configuredbandwidth_rawHexSample: string;
  configuredbandwidth_metadataTag: Record<string, string>;
  actualthroughput_primaryMetric: number;
  actualthroughput_secondaryMetric: number;
  actualthroughput_baselineAverage: number;
  actualthroughput_peakObserved: number;
  actualthroughput_standardDeviation: number;
  actualthroughput_rawHexSample: string;
  actualthroughput_metadataTag: Record<string, string>;
  fastrerouteactive_primaryMetric: number;
  fastrerouteactive_secondaryMetric: number;
  fastrerouteactive_baselineAverage: number;
  fastrerouteactive_peakObserved: number;
  fastrerouteactive_standardDeviation: number;
  fastrerouteactive_rawHexSample: string;
  fastrerouteactive_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type MplsTeTunnelMetricsFilterV36 = Partial<MplsTeTunnelMetricsRecordV36> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface MplsTeTunnelMetricsRecordV37 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  tunnelid_primaryMetric: number;
  tunnelid_secondaryMetric: number;
  tunnelid_baselineAverage: number;
  tunnelid_peakObserved: number;
  tunnelid_standardDeviation: number;
  tunnelid_rawHexSample: string;
  tunnelid_metadataTag: Record<string, string>;
  ingressrouter_primaryMetric: number;
  ingressrouter_secondaryMetric: number;
  ingressrouter_baselineAverage: number;
  ingressrouter_peakObserved: number;
  ingressrouter_standardDeviation: number;
  ingressrouter_rawHexSample: string;
  ingressrouter_metadataTag: Record<string, string>;
  egressrouter_primaryMetric: number;
  egressrouter_secondaryMetric: number;
  egressrouter_baselineAverage: number;
  egressrouter_peakObserved: number;
  egressrouter_standardDeviation: number;
  egressrouter_rawHexSample: string;
  egressrouter_metadataTag: Record<string, string>;
  configuredbandwidth_primaryMetric: number;
  configuredbandwidth_secondaryMetric: number;
  configuredbandwidth_baselineAverage: number;
  configuredbandwidth_peakObserved: number;
  configuredbandwidth_standardDeviation: number;
  configuredbandwidth_rawHexSample: string;
  configuredbandwidth_metadataTag: Record<string, string>;
  actualthroughput_primaryMetric: number;
  actualthroughput_secondaryMetric: number;
  actualthroughput_baselineAverage: number;
  actualthroughput_peakObserved: number;
  actualthroughput_standardDeviation: number;
  actualthroughput_rawHexSample: string;
  actualthroughput_metadataTag: Record<string, string>;
  fastrerouteactive_primaryMetric: number;
  fastrerouteactive_secondaryMetric: number;
  fastrerouteactive_baselineAverage: number;
  fastrerouteactive_peakObserved: number;
  fastrerouteactive_standardDeviation: number;
  fastrerouteactive_rawHexSample: string;
  fastrerouteactive_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type MplsTeTunnelMetricsFilterV37 = Partial<MplsTeTunnelMetricsRecordV37> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface MplsTeTunnelMetricsRecordV38 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  tunnelid_primaryMetric: number;
  tunnelid_secondaryMetric: number;
  tunnelid_baselineAverage: number;
  tunnelid_peakObserved: number;
  tunnelid_standardDeviation: number;
  tunnelid_rawHexSample: string;
  tunnelid_metadataTag: Record<string, string>;
  ingressrouter_primaryMetric: number;
  ingressrouter_secondaryMetric: number;
  ingressrouter_baselineAverage: number;
  ingressrouter_peakObserved: number;
  ingressrouter_standardDeviation: number;
  ingressrouter_rawHexSample: string;
  ingressrouter_metadataTag: Record<string, string>;
  egressrouter_primaryMetric: number;
  egressrouter_secondaryMetric: number;
  egressrouter_baselineAverage: number;
  egressrouter_peakObserved: number;
  egressrouter_standardDeviation: number;
  egressrouter_rawHexSample: string;
  egressrouter_metadataTag: Record<string, string>;
  configuredbandwidth_primaryMetric: number;
  configuredbandwidth_secondaryMetric: number;
  configuredbandwidth_baselineAverage: number;
  configuredbandwidth_peakObserved: number;
  configuredbandwidth_standardDeviation: number;
  configuredbandwidth_rawHexSample: string;
  configuredbandwidth_metadataTag: Record<string, string>;
  actualthroughput_primaryMetric: number;
  actualthroughput_secondaryMetric: number;
  actualthroughput_baselineAverage: number;
  actualthroughput_peakObserved: number;
  actualthroughput_standardDeviation: number;
  actualthroughput_rawHexSample: string;
  actualthroughput_metadataTag: Record<string, string>;
  fastrerouteactive_primaryMetric: number;
  fastrerouteactive_secondaryMetric: number;
  fastrerouteactive_baselineAverage: number;
  fastrerouteactive_peakObserved: number;
  fastrerouteactive_standardDeviation: number;
  fastrerouteactive_rawHexSample: string;
  fastrerouteactive_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type MplsTeTunnelMetricsFilterV38 = Partial<MplsTeTunnelMetricsRecordV38> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface MplsTeTunnelMetricsRecordV39 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  tunnelid_primaryMetric: number;
  tunnelid_secondaryMetric: number;
  tunnelid_baselineAverage: number;
  tunnelid_peakObserved: number;
  tunnelid_standardDeviation: number;
  tunnelid_rawHexSample: string;
  tunnelid_metadataTag: Record<string, string>;
  ingressrouter_primaryMetric: number;
  ingressrouter_secondaryMetric: number;
  ingressrouter_baselineAverage: number;
  ingressrouter_peakObserved: number;
  ingressrouter_standardDeviation: number;
  ingressrouter_rawHexSample: string;
  ingressrouter_metadataTag: Record<string, string>;
  egressrouter_primaryMetric: number;
  egressrouter_secondaryMetric: number;
  egressrouter_baselineAverage: number;
  egressrouter_peakObserved: number;
  egressrouter_standardDeviation: number;
  egressrouter_rawHexSample: string;
  egressrouter_metadataTag: Record<string, string>;
  configuredbandwidth_primaryMetric: number;
  configuredbandwidth_secondaryMetric: number;
  configuredbandwidth_baselineAverage: number;
  configuredbandwidth_peakObserved: number;
  configuredbandwidth_standardDeviation: number;
  configuredbandwidth_rawHexSample: string;
  configuredbandwidth_metadataTag: Record<string, string>;
  actualthroughput_primaryMetric: number;
  actualthroughput_secondaryMetric: number;
  actualthroughput_baselineAverage: number;
  actualthroughput_peakObserved: number;
  actualthroughput_standardDeviation: number;
  actualthroughput_rawHexSample: string;
  actualthroughput_metadataTag: Record<string, string>;
  fastrerouteactive_primaryMetric: number;
  fastrerouteactive_secondaryMetric: number;
  fastrerouteactive_baselineAverage: number;
  fastrerouteactive_peakObserved: number;
  fastrerouteactive_standardDeviation: number;
  fastrerouteactive_rawHexSample: string;
  fastrerouteactive_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type MplsTeTunnelMetricsFilterV39 = Partial<MplsTeTunnelMetricsRecordV39> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface MplsTeTunnelMetricsRecordV40 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  tunnelid_primaryMetric: number;
  tunnelid_secondaryMetric: number;
  tunnelid_baselineAverage: number;
  tunnelid_peakObserved: number;
  tunnelid_standardDeviation: number;
  tunnelid_rawHexSample: string;
  tunnelid_metadataTag: Record<string, string>;
  ingressrouter_primaryMetric: number;
  ingressrouter_secondaryMetric: number;
  ingressrouter_baselineAverage: number;
  ingressrouter_peakObserved: number;
  ingressrouter_standardDeviation: number;
  ingressrouter_rawHexSample: string;
  ingressrouter_metadataTag: Record<string, string>;
  egressrouter_primaryMetric: number;
  egressrouter_secondaryMetric: number;
  egressrouter_baselineAverage: number;
  egressrouter_peakObserved: number;
  egressrouter_standardDeviation: number;
  egressrouter_rawHexSample: string;
  egressrouter_metadataTag: Record<string, string>;
  configuredbandwidth_primaryMetric: number;
  configuredbandwidth_secondaryMetric: number;
  configuredbandwidth_baselineAverage: number;
  configuredbandwidth_peakObserved: number;
  configuredbandwidth_standardDeviation: number;
  configuredbandwidth_rawHexSample: string;
  configuredbandwidth_metadataTag: Record<string, string>;
  actualthroughput_primaryMetric: number;
  actualthroughput_secondaryMetric: number;
  actualthroughput_baselineAverage: number;
  actualthroughput_peakObserved: number;
  actualthroughput_standardDeviation: number;
  actualthroughput_rawHexSample: string;
  actualthroughput_metadataTag: Record<string, string>;
  fastrerouteactive_primaryMetric: number;
  fastrerouteactive_secondaryMetric: number;
  fastrerouteactive_baselineAverage: number;
  fastrerouteactive_peakObserved: number;
  fastrerouteactive_standardDeviation: number;
  fastrerouteactive_rawHexSample: string;
  fastrerouteactive_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type MplsTeTunnelMetricsFilterV40 = Partial<MplsTeTunnelMetricsRecordV40> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};
