/**
 * Enterprise Telecommunications Protocol Specification: IETF RFC 7011 IPFIX and Cisco NetFlow v9 Flow Record Templates
 * Module: @geonet/types/telecom/netflow_v9_ipfix
 * Standard Compliance: 3GPP TS 38.401, IETF RFC Standards, ITU-T G.8032
 */

export interface IETFRFC7011IPFIXandCiscoNetFlowv9FlowRecordTemplatesConfig {
  samplingIntervalMs: number;
  collectionEnabled: boolean;
  highWatermarkThreshold: number;
  lowWatermarkThreshold: number;
  retryAttempts: number;
  timeoutMs: number;
}

export interface NetflowV9IpfixRecordV1 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  sourceipv4address_primaryMetric: number;
  sourceipv4address_secondaryMetric: number;
  sourceipv4address_baselineAverage: number;
  sourceipv4address_peakObserved: number;
  sourceipv4address_standardDeviation: number;
  sourceipv4address_rawHexSample: string;
  sourceipv4address_metadataTag: Record<string, string>;
  destinationipv4address_primaryMetric: number;
  destinationipv4address_secondaryMetric: number;
  destinationipv4address_baselineAverage: number;
  destinationipv4address_peakObserved: number;
  destinationipv4address_standardDeviation: number;
  destinationipv4address_rawHexSample: string;
  destinationipv4address_metadataTag: Record<string, string>;
  packetdeltacount_primaryMetric: number;
  packetdeltacount_secondaryMetric: number;
  packetdeltacount_baselineAverage: number;
  packetdeltacount_peakObserved: number;
  packetdeltacount_standardDeviation: number;
  packetdeltacount_rawHexSample: string;
  packetdeltacount_metadataTag: Record<string, string>;
  octetdeltacount_primaryMetric: number;
  octetdeltacount_secondaryMetric: number;
  octetdeltacount_baselineAverage: number;
  octetdeltacount_peakObserved: number;
  octetdeltacount_standardDeviation: number;
  octetdeltacount_rawHexSample: string;
  octetdeltacount_metadataTag: Record<string, string>;
  protocolidentifier_primaryMetric: number;
  protocolidentifier_secondaryMetric: number;
  protocolidentifier_baselineAverage: number;
  protocolidentifier_peakObserved: number;
  protocolidentifier_standardDeviation: number;
  protocolidentifier_rawHexSample: string;
  protocolidentifier_metadataTag: Record<string, string>;
  tcpcontrolbits_primaryMetric: number;
  tcpcontrolbits_secondaryMetric: number;
  tcpcontrolbits_baselineAverage: number;
  tcpcontrolbits_peakObserved: number;
  tcpcontrolbits_standardDeviation: number;
  tcpcontrolbits_rawHexSample: string;
  tcpcontrolbits_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type NetflowV9IpfixFilterV1 = Partial<NetflowV9IpfixRecordV1> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface NetflowV9IpfixRecordV2 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  sourceipv4address_primaryMetric: number;
  sourceipv4address_secondaryMetric: number;
  sourceipv4address_baselineAverage: number;
  sourceipv4address_peakObserved: number;
  sourceipv4address_standardDeviation: number;
  sourceipv4address_rawHexSample: string;
  sourceipv4address_metadataTag: Record<string, string>;
  destinationipv4address_primaryMetric: number;
  destinationipv4address_secondaryMetric: number;
  destinationipv4address_baselineAverage: number;
  destinationipv4address_peakObserved: number;
  destinationipv4address_standardDeviation: number;
  destinationipv4address_rawHexSample: string;
  destinationipv4address_metadataTag: Record<string, string>;
  packetdeltacount_primaryMetric: number;
  packetdeltacount_secondaryMetric: number;
  packetdeltacount_baselineAverage: number;
  packetdeltacount_peakObserved: number;
  packetdeltacount_standardDeviation: number;
  packetdeltacount_rawHexSample: string;
  packetdeltacount_metadataTag: Record<string, string>;
  octetdeltacount_primaryMetric: number;
  octetdeltacount_secondaryMetric: number;
  octetdeltacount_baselineAverage: number;
  octetdeltacount_peakObserved: number;
  octetdeltacount_standardDeviation: number;
  octetdeltacount_rawHexSample: string;
  octetdeltacount_metadataTag: Record<string, string>;
  protocolidentifier_primaryMetric: number;
  protocolidentifier_secondaryMetric: number;
  protocolidentifier_baselineAverage: number;
  protocolidentifier_peakObserved: number;
  protocolidentifier_standardDeviation: number;
  protocolidentifier_rawHexSample: string;
  protocolidentifier_metadataTag: Record<string, string>;
  tcpcontrolbits_primaryMetric: number;
  tcpcontrolbits_secondaryMetric: number;
  tcpcontrolbits_baselineAverage: number;
  tcpcontrolbits_peakObserved: number;
  tcpcontrolbits_standardDeviation: number;
  tcpcontrolbits_rawHexSample: string;
  tcpcontrolbits_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type NetflowV9IpfixFilterV2 = Partial<NetflowV9IpfixRecordV2> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface NetflowV9IpfixRecordV3 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  sourceipv4address_primaryMetric: number;
  sourceipv4address_secondaryMetric: number;
  sourceipv4address_baselineAverage: number;
  sourceipv4address_peakObserved: number;
  sourceipv4address_standardDeviation: number;
  sourceipv4address_rawHexSample: string;
  sourceipv4address_metadataTag: Record<string, string>;
  destinationipv4address_primaryMetric: number;
  destinationipv4address_secondaryMetric: number;
  destinationipv4address_baselineAverage: number;
  destinationipv4address_peakObserved: number;
  destinationipv4address_standardDeviation: number;
  destinationipv4address_rawHexSample: string;
  destinationipv4address_metadataTag: Record<string, string>;
  packetdeltacount_primaryMetric: number;
  packetdeltacount_secondaryMetric: number;
  packetdeltacount_baselineAverage: number;
  packetdeltacount_peakObserved: number;
  packetdeltacount_standardDeviation: number;
  packetdeltacount_rawHexSample: string;
  packetdeltacount_metadataTag: Record<string, string>;
  octetdeltacount_primaryMetric: number;
  octetdeltacount_secondaryMetric: number;
  octetdeltacount_baselineAverage: number;
  octetdeltacount_peakObserved: number;
  octetdeltacount_standardDeviation: number;
  octetdeltacount_rawHexSample: string;
  octetdeltacount_metadataTag: Record<string, string>;
  protocolidentifier_primaryMetric: number;
  protocolidentifier_secondaryMetric: number;
  protocolidentifier_baselineAverage: number;
  protocolidentifier_peakObserved: number;
  protocolidentifier_standardDeviation: number;
  protocolidentifier_rawHexSample: string;
  protocolidentifier_metadataTag: Record<string, string>;
  tcpcontrolbits_primaryMetric: number;
  tcpcontrolbits_secondaryMetric: number;
  tcpcontrolbits_baselineAverage: number;
  tcpcontrolbits_peakObserved: number;
  tcpcontrolbits_standardDeviation: number;
  tcpcontrolbits_rawHexSample: string;
  tcpcontrolbits_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type NetflowV9IpfixFilterV3 = Partial<NetflowV9IpfixRecordV3> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface NetflowV9IpfixRecordV4 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  sourceipv4address_primaryMetric: number;
  sourceipv4address_secondaryMetric: number;
  sourceipv4address_baselineAverage: number;
  sourceipv4address_peakObserved: number;
  sourceipv4address_standardDeviation: number;
  sourceipv4address_rawHexSample: string;
  sourceipv4address_metadataTag: Record<string, string>;
  destinationipv4address_primaryMetric: number;
  destinationipv4address_secondaryMetric: number;
  destinationipv4address_baselineAverage: number;
  destinationipv4address_peakObserved: number;
  destinationipv4address_standardDeviation: number;
  destinationipv4address_rawHexSample: string;
  destinationipv4address_metadataTag: Record<string, string>;
  packetdeltacount_primaryMetric: number;
  packetdeltacount_secondaryMetric: number;
  packetdeltacount_baselineAverage: number;
  packetdeltacount_peakObserved: number;
  packetdeltacount_standardDeviation: number;
  packetdeltacount_rawHexSample: string;
  packetdeltacount_metadataTag: Record<string, string>;
  octetdeltacount_primaryMetric: number;
  octetdeltacount_secondaryMetric: number;
  octetdeltacount_baselineAverage: number;
  octetdeltacount_peakObserved: number;
  octetdeltacount_standardDeviation: number;
  octetdeltacount_rawHexSample: string;
  octetdeltacount_metadataTag: Record<string, string>;
  protocolidentifier_primaryMetric: number;
  protocolidentifier_secondaryMetric: number;
  protocolidentifier_baselineAverage: number;
  protocolidentifier_peakObserved: number;
  protocolidentifier_standardDeviation: number;
  protocolidentifier_rawHexSample: string;
  protocolidentifier_metadataTag: Record<string, string>;
  tcpcontrolbits_primaryMetric: number;
  tcpcontrolbits_secondaryMetric: number;
  tcpcontrolbits_baselineAverage: number;
  tcpcontrolbits_peakObserved: number;
  tcpcontrolbits_standardDeviation: number;
  tcpcontrolbits_rawHexSample: string;
  tcpcontrolbits_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type NetflowV9IpfixFilterV4 = Partial<NetflowV9IpfixRecordV4> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface NetflowV9IpfixRecordV5 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  sourceipv4address_primaryMetric: number;
  sourceipv4address_secondaryMetric: number;
  sourceipv4address_baselineAverage: number;
  sourceipv4address_peakObserved: number;
  sourceipv4address_standardDeviation: number;
  sourceipv4address_rawHexSample: string;
  sourceipv4address_metadataTag: Record<string, string>;
  destinationipv4address_primaryMetric: number;
  destinationipv4address_secondaryMetric: number;
  destinationipv4address_baselineAverage: number;
  destinationipv4address_peakObserved: number;
  destinationipv4address_standardDeviation: number;
  destinationipv4address_rawHexSample: string;
  destinationipv4address_metadataTag: Record<string, string>;
  packetdeltacount_primaryMetric: number;
  packetdeltacount_secondaryMetric: number;
  packetdeltacount_baselineAverage: number;
  packetdeltacount_peakObserved: number;
  packetdeltacount_standardDeviation: number;
  packetdeltacount_rawHexSample: string;
  packetdeltacount_metadataTag: Record<string, string>;
  octetdeltacount_primaryMetric: number;
  octetdeltacount_secondaryMetric: number;
  octetdeltacount_baselineAverage: number;
  octetdeltacount_peakObserved: number;
  octetdeltacount_standardDeviation: number;
  octetdeltacount_rawHexSample: string;
  octetdeltacount_metadataTag: Record<string, string>;
  protocolidentifier_primaryMetric: number;
  protocolidentifier_secondaryMetric: number;
  protocolidentifier_baselineAverage: number;
  protocolidentifier_peakObserved: number;
  protocolidentifier_standardDeviation: number;
  protocolidentifier_rawHexSample: string;
  protocolidentifier_metadataTag: Record<string, string>;
  tcpcontrolbits_primaryMetric: number;
  tcpcontrolbits_secondaryMetric: number;
  tcpcontrolbits_baselineAverage: number;
  tcpcontrolbits_peakObserved: number;
  tcpcontrolbits_standardDeviation: number;
  tcpcontrolbits_rawHexSample: string;
  tcpcontrolbits_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type NetflowV9IpfixFilterV5 = Partial<NetflowV9IpfixRecordV5> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface NetflowV9IpfixRecordV6 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  sourceipv4address_primaryMetric: number;
  sourceipv4address_secondaryMetric: number;
  sourceipv4address_baselineAverage: number;
  sourceipv4address_peakObserved: number;
  sourceipv4address_standardDeviation: number;
  sourceipv4address_rawHexSample: string;
  sourceipv4address_metadataTag: Record<string, string>;
  destinationipv4address_primaryMetric: number;
  destinationipv4address_secondaryMetric: number;
  destinationipv4address_baselineAverage: number;
  destinationipv4address_peakObserved: number;
  destinationipv4address_standardDeviation: number;
  destinationipv4address_rawHexSample: string;
  destinationipv4address_metadataTag: Record<string, string>;
  packetdeltacount_primaryMetric: number;
  packetdeltacount_secondaryMetric: number;
  packetdeltacount_baselineAverage: number;
  packetdeltacount_peakObserved: number;
  packetdeltacount_standardDeviation: number;
  packetdeltacount_rawHexSample: string;
  packetdeltacount_metadataTag: Record<string, string>;
  octetdeltacount_primaryMetric: number;
  octetdeltacount_secondaryMetric: number;
  octetdeltacount_baselineAverage: number;
  octetdeltacount_peakObserved: number;
  octetdeltacount_standardDeviation: number;
  octetdeltacount_rawHexSample: string;
  octetdeltacount_metadataTag: Record<string, string>;
  protocolidentifier_primaryMetric: number;
  protocolidentifier_secondaryMetric: number;
  protocolidentifier_baselineAverage: number;
  protocolidentifier_peakObserved: number;
  protocolidentifier_standardDeviation: number;
  protocolidentifier_rawHexSample: string;
  protocolidentifier_metadataTag: Record<string, string>;
  tcpcontrolbits_primaryMetric: number;
  tcpcontrolbits_secondaryMetric: number;
  tcpcontrolbits_baselineAverage: number;
  tcpcontrolbits_peakObserved: number;
  tcpcontrolbits_standardDeviation: number;
  tcpcontrolbits_rawHexSample: string;
  tcpcontrolbits_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type NetflowV9IpfixFilterV6 = Partial<NetflowV9IpfixRecordV6> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface NetflowV9IpfixRecordV7 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  sourceipv4address_primaryMetric: number;
  sourceipv4address_secondaryMetric: number;
  sourceipv4address_baselineAverage: number;
  sourceipv4address_peakObserved: number;
  sourceipv4address_standardDeviation: number;
  sourceipv4address_rawHexSample: string;
  sourceipv4address_metadataTag: Record<string, string>;
  destinationipv4address_primaryMetric: number;
  destinationipv4address_secondaryMetric: number;
  destinationipv4address_baselineAverage: number;
  destinationipv4address_peakObserved: number;
  destinationipv4address_standardDeviation: number;
  destinationipv4address_rawHexSample: string;
  destinationipv4address_metadataTag: Record<string, string>;
  packetdeltacount_primaryMetric: number;
  packetdeltacount_secondaryMetric: number;
  packetdeltacount_baselineAverage: number;
  packetdeltacount_peakObserved: number;
  packetdeltacount_standardDeviation: number;
  packetdeltacount_rawHexSample: string;
  packetdeltacount_metadataTag: Record<string, string>;
  octetdeltacount_primaryMetric: number;
  octetdeltacount_secondaryMetric: number;
  octetdeltacount_baselineAverage: number;
  octetdeltacount_peakObserved: number;
  octetdeltacount_standardDeviation: number;
  octetdeltacount_rawHexSample: string;
  octetdeltacount_metadataTag: Record<string, string>;
  protocolidentifier_primaryMetric: number;
  protocolidentifier_secondaryMetric: number;
  protocolidentifier_baselineAverage: number;
  protocolidentifier_peakObserved: number;
  protocolidentifier_standardDeviation: number;
  protocolidentifier_rawHexSample: string;
  protocolidentifier_metadataTag: Record<string, string>;
  tcpcontrolbits_primaryMetric: number;
  tcpcontrolbits_secondaryMetric: number;
  tcpcontrolbits_baselineAverage: number;
  tcpcontrolbits_peakObserved: number;
  tcpcontrolbits_standardDeviation: number;
  tcpcontrolbits_rawHexSample: string;
  tcpcontrolbits_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type NetflowV9IpfixFilterV7 = Partial<NetflowV9IpfixRecordV7> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface NetflowV9IpfixRecordV8 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  sourceipv4address_primaryMetric: number;
  sourceipv4address_secondaryMetric: number;
  sourceipv4address_baselineAverage: number;
  sourceipv4address_peakObserved: number;
  sourceipv4address_standardDeviation: number;
  sourceipv4address_rawHexSample: string;
  sourceipv4address_metadataTag: Record<string, string>;
  destinationipv4address_primaryMetric: number;
  destinationipv4address_secondaryMetric: number;
  destinationipv4address_baselineAverage: number;
  destinationipv4address_peakObserved: number;
  destinationipv4address_standardDeviation: number;
  destinationipv4address_rawHexSample: string;
  destinationipv4address_metadataTag: Record<string, string>;
  packetdeltacount_primaryMetric: number;
  packetdeltacount_secondaryMetric: number;
  packetdeltacount_baselineAverage: number;
  packetdeltacount_peakObserved: number;
  packetdeltacount_standardDeviation: number;
  packetdeltacount_rawHexSample: string;
  packetdeltacount_metadataTag: Record<string, string>;
  octetdeltacount_primaryMetric: number;
  octetdeltacount_secondaryMetric: number;
  octetdeltacount_baselineAverage: number;
  octetdeltacount_peakObserved: number;
  octetdeltacount_standardDeviation: number;
  octetdeltacount_rawHexSample: string;
  octetdeltacount_metadataTag: Record<string, string>;
  protocolidentifier_primaryMetric: number;
  protocolidentifier_secondaryMetric: number;
  protocolidentifier_baselineAverage: number;
  protocolidentifier_peakObserved: number;
  protocolidentifier_standardDeviation: number;
  protocolidentifier_rawHexSample: string;
  protocolidentifier_metadataTag: Record<string, string>;
  tcpcontrolbits_primaryMetric: number;
  tcpcontrolbits_secondaryMetric: number;
  tcpcontrolbits_baselineAverage: number;
  tcpcontrolbits_peakObserved: number;
  tcpcontrolbits_standardDeviation: number;
  tcpcontrolbits_rawHexSample: string;
  tcpcontrolbits_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type NetflowV9IpfixFilterV8 = Partial<NetflowV9IpfixRecordV8> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface NetflowV9IpfixRecordV9 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  sourceipv4address_primaryMetric: number;
  sourceipv4address_secondaryMetric: number;
  sourceipv4address_baselineAverage: number;
  sourceipv4address_peakObserved: number;
  sourceipv4address_standardDeviation: number;
  sourceipv4address_rawHexSample: string;
  sourceipv4address_metadataTag: Record<string, string>;
  destinationipv4address_primaryMetric: number;
  destinationipv4address_secondaryMetric: number;
  destinationipv4address_baselineAverage: number;
  destinationipv4address_peakObserved: number;
  destinationipv4address_standardDeviation: number;
  destinationipv4address_rawHexSample: string;
  destinationipv4address_metadataTag: Record<string, string>;
  packetdeltacount_primaryMetric: number;
  packetdeltacount_secondaryMetric: number;
  packetdeltacount_baselineAverage: number;
  packetdeltacount_peakObserved: number;
  packetdeltacount_standardDeviation: number;
  packetdeltacount_rawHexSample: string;
  packetdeltacount_metadataTag: Record<string, string>;
  octetdeltacount_primaryMetric: number;
  octetdeltacount_secondaryMetric: number;
  octetdeltacount_baselineAverage: number;
  octetdeltacount_peakObserved: number;
  octetdeltacount_standardDeviation: number;
  octetdeltacount_rawHexSample: string;
  octetdeltacount_metadataTag: Record<string, string>;
  protocolidentifier_primaryMetric: number;
  protocolidentifier_secondaryMetric: number;
  protocolidentifier_baselineAverage: number;
  protocolidentifier_peakObserved: number;
  protocolidentifier_standardDeviation: number;
  protocolidentifier_rawHexSample: string;
  protocolidentifier_metadataTag: Record<string, string>;
  tcpcontrolbits_primaryMetric: number;
  tcpcontrolbits_secondaryMetric: number;
  tcpcontrolbits_baselineAverage: number;
  tcpcontrolbits_peakObserved: number;
  tcpcontrolbits_standardDeviation: number;
  tcpcontrolbits_rawHexSample: string;
  tcpcontrolbits_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type NetflowV9IpfixFilterV9 = Partial<NetflowV9IpfixRecordV9> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface NetflowV9IpfixRecordV10 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  sourceipv4address_primaryMetric: number;
  sourceipv4address_secondaryMetric: number;
  sourceipv4address_baselineAverage: number;
  sourceipv4address_peakObserved: number;
  sourceipv4address_standardDeviation: number;
  sourceipv4address_rawHexSample: string;
  sourceipv4address_metadataTag: Record<string, string>;
  destinationipv4address_primaryMetric: number;
  destinationipv4address_secondaryMetric: number;
  destinationipv4address_baselineAverage: number;
  destinationipv4address_peakObserved: number;
  destinationipv4address_standardDeviation: number;
  destinationipv4address_rawHexSample: string;
  destinationipv4address_metadataTag: Record<string, string>;
  packetdeltacount_primaryMetric: number;
  packetdeltacount_secondaryMetric: number;
  packetdeltacount_baselineAverage: number;
  packetdeltacount_peakObserved: number;
  packetdeltacount_standardDeviation: number;
  packetdeltacount_rawHexSample: string;
  packetdeltacount_metadataTag: Record<string, string>;
  octetdeltacount_primaryMetric: number;
  octetdeltacount_secondaryMetric: number;
  octetdeltacount_baselineAverage: number;
  octetdeltacount_peakObserved: number;
  octetdeltacount_standardDeviation: number;
  octetdeltacount_rawHexSample: string;
  octetdeltacount_metadataTag: Record<string, string>;
  protocolidentifier_primaryMetric: number;
  protocolidentifier_secondaryMetric: number;
  protocolidentifier_baselineAverage: number;
  protocolidentifier_peakObserved: number;
  protocolidentifier_standardDeviation: number;
  protocolidentifier_rawHexSample: string;
  protocolidentifier_metadataTag: Record<string, string>;
  tcpcontrolbits_primaryMetric: number;
  tcpcontrolbits_secondaryMetric: number;
  tcpcontrolbits_baselineAverage: number;
  tcpcontrolbits_peakObserved: number;
  tcpcontrolbits_standardDeviation: number;
  tcpcontrolbits_rawHexSample: string;
  tcpcontrolbits_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type NetflowV9IpfixFilterV10 = Partial<NetflowV9IpfixRecordV10> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface NetflowV9IpfixRecordV11 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  sourceipv4address_primaryMetric: number;
  sourceipv4address_secondaryMetric: number;
  sourceipv4address_baselineAverage: number;
  sourceipv4address_peakObserved: number;
  sourceipv4address_standardDeviation: number;
  sourceipv4address_rawHexSample: string;
  sourceipv4address_metadataTag: Record<string, string>;
  destinationipv4address_primaryMetric: number;
  destinationipv4address_secondaryMetric: number;
  destinationipv4address_baselineAverage: number;
  destinationipv4address_peakObserved: number;
  destinationipv4address_standardDeviation: number;
  destinationipv4address_rawHexSample: string;
  destinationipv4address_metadataTag: Record<string, string>;
  packetdeltacount_primaryMetric: number;
  packetdeltacount_secondaryMetric: number;
  packetdeltacount_baselineAverage: number;
  packetdeltacount_peakObserved: number;
  packetdeltacount_standardDeviation: number;
  packetdeltacount_rawHexSample: string;
  packetdeltacount_metadataTag: Record<string, string>;
  octetdeltacount_primaryMetric: number;
  octetdeltacount_secondaryMetric: number;
  octetdeltacount_baselineAverage: number;
  octetdeltacount_peakObserved: number;
  octetdeltacount_standardDeviation: number;
  octetdeltacount_rawHexSample: string;
  octetdeltacount_metadataTag: Record<string, string>;
  protocolidentifier_primaryMetric: number;
  protocolidentifier_secondaryMetric: number;
  protocolidentifier_baselineAverage: number;
  protocolidentifier_peakObserved: number;
  protocolidentifier_standardDeviation: number;
  protocolidentifier_rawHexSample: string;
  protocolidentifier_metadataTag: Record<string, string>;
  tcpcontrolbits_primaryMetric: number;
  tcpcontrolbits_secondaryMetric: number;
  tcpcontrolbits_baselineAverage: number;
  tcpcontrolbits_peakObserved: number;
  tcpcontrolbits_standardDeviation: number;
  tcpcontrolbits_rawHexSample: string;
  tcpcontrolbits_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type NetflowV9IpfixFilterV11 = Partial<NetflowV9IpfixRecordV11> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface NetflowV9IpfixRecordV12 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  sourceipv4address_primaryMetric: number;
  sourceipv4address_secondaryMetric: number;
  sourceipv4address_baselineAverage: number;
  sourceipv4address_peakObserved: number;
  sourceipv4address_standardDeviation: number;
  sourceipv4address_rawHexSample: string;
  sourceipv4address_metadataTag: Record<string, string>;
  destinationipv4address_primaryMetric: number;
  destinationipv4address_secondaryMetric: number;
  destinationipv4address_baselineAverage: number;
  destinationipv4address_peakObserved: number;
  destinationipv4address_standardDeviation: number;
  destinationipv4address_rawHexSample: string;
  destinationipv4address_metadataTag: Record<string, string>;
  packetdeltacount_primaryMetric: number;
  packetdeltacount_secondaryMetric: number;
  packetdeltacount_baselineAverage: number;
  packetdeltacount_peakObserved: number;
  packetdeltacount_standardDeviation: number;
  packetdeltacount_rawHexSample: string;
  packetdeltacount_metadataTag: Record<string, string>;
  octetdeltacount_primaryMetric: number;
  octetdeltacount_secondaryMetric: number;
  octetdeltacount_baselineAverage: number;
  octetdeltacount_peakObserved: number;
  octetdeltacount_standardDeviation: number;
  octetdeltacount_rawHexSample: string;
  octetdeltacount_metadataTag: Record<string, string>;
  protocolidentifier_primaryMetric: number;
  protocolidentifier_secondaryMetric: number;
  protocolidentifier_baselineAverage: number;
  protocolidentifier_peakObserved: number;
  protocolidentifier_standardDeviation: number;
  protocolidentifier_rawHexSample: string;
  protocolidentifier_metadataTag: Record<string, string>;
  tcpcontrolbits_primaryMetric: number;
  tcpcontrolbits_secondaryMetric: number;
  tcpcontrolbits_baselineAverage: number;
  tcpcontrolbits_peakObserved: number;
  tcpcontrolbits_standardDeviation: number;
  tcpcontrolbits_rawHexSample: string;
  tcpcontrolbits_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type NetflowV9IpfixFilterV12 = Partial<NetflowV9IpfixRecordV12> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface NetflowV9IpfixRecordV13 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  sourceipv4address_primaryMetric: number;
  sourceipv4address_secondaryMetric: number;
  sourceipv4address_baselineAverage: number;
  sourceipv4address_peakObserved: number;
  sourceipv4address_standardDeviation: number;
  sourceipv4address_rawHexSample: string;
  sourceipv4address_metadataTag: Record<string, string>;
  destinationipv4address_primaryMetric: number;
  destinationipv4address_secondaryMetric: number;
  destinationipv4address_baselineAverage: number;
  destinationipv4address_peakObserved: number;
  destinationipv4address_standardDeviation: number;
  destinationipv4address_rawHexSample: string;
  destinationipv4address_metadataTag: Record<string, string>;
  packetdeltacount_primaryMetric: number;
  packetdeltacount_secondaryMetric: number;
  packetdeltacount_baselineAverage: number;
  packetdeltacount_peakObserved: number;
  packetdeltacount_standardDeviation: number;
  packetdeltacount_rawHexSample: string;
  packetdeltacount_metadataTag: Record<string, string>;
  octetdeltacount_primaryMetric: number;
  octetdeltacount_secondaryMetric: number;
  octetdeltacount_baselineAverage: number;
  octetdeltacount_peakObserved: number;
  octetdeltacount_standardDeviation: number;
  octetdeltacount_rawHexSample: string;
  octetdeltacount_metadataTag: Record<string, string>;
  protocolidentifier_primaryMetric: number;
  protocolidentifier_secondaryMetric: number;
  protocolidentifier_baselineAverage: number;
  protocolidentifier_peakObserved: number;
  protocolidentifier_standardDeviation: number;
  protocolidentifier_rawHexSample: string;
  protocolidentifier_metadataTag: Record<string, string>;
  tcpcontrolbits_primaryMetric: number;
  tcpcontrolbits_secondaryMetric: number;
  tcpcontrolbits_baselineAverage: number;
  tcpcontrolbits_peakObserved: number;
  tcpcontrolbits_standardDeviation: number;
  tcpcontrolbits_rawHexSample: string;
  tcpcontrolbits_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type NetflowV9IpfixFilterV13 = Partial<NetflowV9IpfixRecordV13> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface NetflowV9IpfixRecordV14 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  sourceipv4address_primaryMetric: number;
  sourceipv4address_secondaryMetric: number;
  sourceipv4address_baselineAverage: number;
  sourceipv4address_peakObserved: number;
  sourceipv4address_standardDeviation: number;
  sourceipv4address_rawHexSample: string;
  sourceipv4address_metadataTag: Record<string, string>;
  destinationipv4address_primaryMetric: number;
  destinationipv4address_secondaryMetric: number;
  destinationipv4address_baselineAverage: number;
  destinationipv4address_peakObserved: number;
  destinationipv4address_standardDeviation: number;
  destinationipv4address_rawHexSample: string;
  destinationipv4address_metadataTag: Record<string, string>;
  packetdeltacount_primaryMetric: number;
  packetdeltacount_secondaryMetric: number;
  packetdeltacount_baselineAverage: number;
  packetdeltacount_peakObserved: number;
  packetdeltacount_standardDeviation: number;
  packetdeltacount_rawHexSample: string;
  packetdeltacount_metadataTag: Record<string, string>;
  octetdeltacount_primaryMetric: number;
  octetdeltacount_secondaryMetric: number;
  octetdeltacount_baselineAverage: number;
  octetdeltacount_peakObserved: number;
  octetdeltacount_standardDeviation: number;
  octetdeltacount_rawHexSample: string;
  octetdeltacount_metadataTag: Record<string, string>;
  protocolidentifier_primaryMetric: number;
  protocolidentifier_secondaryMetric: number;
  protocolidentifier_baselineAverage: number;
  protocolidentifier_peakObserved: number;
  protocolidentifier_standardDeviation: number;
  protocolidentifier_rawHexSample: string;
  protocolidentifier_metadataTag: Record<string, string>;
  tcpcontrolbits_primaryMetric: number;
  tcpcontrolbits_secondaryMetric: number;
  tcpcontrolbits_baselineAverage: number;
  tcpcontrolbits_peakObserved: number;
  tcpcontrolbits_standardDeviation: number;
  tcpcontrolbits_rawHexSample: string;
  tcpcontrolbits_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type NetflowV9IpfixFilterV14 = Partial<NetflowV9IpfixRecordV14> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface NetflowV9IpfixRecordV15 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  sourceipv4address_primaryMetric: number;
  sourceipv4address_secondaryMetric: number;
  sourceipv4address_baselineAverage: number;
  sourceipv4address_peakObserved: number;
  sourceipv4address_standardDeviation: number;
  sourceipv4address_rawHexSample: string;
  sourceipv4address_metadataTag: Record<string, string>;
  destinationipv4address_primaryMetric: number;
  destinationipv4address_secondaryMetric: number;
  destinationipv4address_baselineAverage: number;
  destinationipv4address_peakObserved: number;
  destinationipv4address_standardDeviation: number;
  destinationipv4address_rawHexSample: string;
  destinationipv4address_metadataTag: Record<string, string>;
  packetdeltacount_primaryMetric: number;
  packetdeltacount_secondaryMetric: number;
  packetdeltacount_baselineAverage: number;
  packetdeltacount_peakObserved: number;
  packetdeltacount_standardDeviation: number;
  packetdeltacount_rawHexSample: string;
  packetdeltacount_metadataTag: Record<string, string>;
  octetdeltacount_primaryMetric: number;
  octetdeltacount_secondaryMetric: number;
  octetdeltacount_baselineAverage: number;
  octetdeltacount_peakObserved: number;
  octetdeltacount_standardDeviation: number;
  octetdeltacount_rawHexSample: string;
  octetdeltacount_metadataTag: Record<string, string>;
  protocolidentifier_primaryMetric: number;
  protocolidentifier_secondaryMetric: number;
  protocolidentifier_baselineAverage: number;
  protocolidentifier_peakObserved: number;
  protocolidentifier_standardDeviation: number;
  protocolidentifier_rawHexSample: string;
  protocolidentifier_metadataTag: Record<string, string>;
  tcpcontrolbits_primaryMetric: number;
  tcpcontrolbits_secondaryMetric: number;
  tcpcontrolbits_baselineAverage: number;
  tcpcontrolbits_peakObserved: number;
  tcpcontrolbits_standardDeviation: number;
  tcpcontrolbits_rawHexSample: string;
  tcpcontrolbits_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type NetflowV9IpfixFilterV15 = Partial<NetflowV9IpfixRecordV15> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface NetflowV9IpfixRecordV16 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  sourceipv4address_primaryMetric: number;
  sourceipv4address_secondaryMetric: number;
  sourceipv4address_baselineAverage: number;
  sourceipv4address_peakObserved: number;
  sourceipv4address_standardDeviation: number;
  sourceipv4address_rawHexSample: string;
  sourceipv4address_metadataTag: Record<string, string>;
  destinationipv4address_primaryMetric: number;
  destinationipv4address_secondaryMetric: number;
  destinationipv4address_baselineAverage: number;
  destinationipv4address_peakObserved: number;
  destinationipv4address_standardDeviation: number;
  destinationipv4address_rawHexSample: string;
  destinationipv4address_metadataTag: Record<string, string>;
  packetdeltacount_primaryMetric: number;
  packetdeltacount_secondaryMetric: number;
  packetdeltacount_baselineAverage: number;
  packetdeltacount_peakObserved: number;
  packetdeltacount_standardDeviation: number;
  packetdeltacount_rawHexSample: string;
  packetdeltacount_metadataTag: Record<string, string>;
  octetdeltacount_primaryMetric: number;
  octetdeltacount_secondaryMetric: number;
  octetdeltacount_baselineAverage: number;
  octetdeltacount_peakObserved: number;
  octetdeltacount_standardDeviation: number;
  octetdeltacount_rawHexSample: string;
  octetdeltacount_metadataTag: Record<string, string>;
  protocolidentifier_primaryMetric: number;
  protocolidentifier_secondaryMetric: number;
  protocolidentifier_baselineAverage: number;
  protocolidentifier_peakObserved: number;
  protocolidentifier_standardDeviation: number;
  protocolidentifier_rawHexSample: string;
  protocolidentifier_metadataTag: Record<string, string>;
  tcpcontrolbits_primaryMetric: number;
  tcpcontrolbits_secondaryMetric: number;
  tcpcontrolbits_baselineAverage: number;
  tcpcontrolbits_peakObserved: number;
  tcpcontrolbits_standardDeviation: number;
  tcpcontrolbits_rawHexSample: string;
  tcpcontrolbits_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type NetflowV9IpfixFilterV16 = Partial<NetflowV9IpfixRecordV16> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface NetflowV9IpfixRecordV17 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  sourceipv4address_primaryMetric: number;
  sourceipv4address_secondaryMetric: number;
  sourceipv4address_baselineAverage: number;
  sourceipv4address_peakObserved: number;
  sourceipv4address_standardDeviation: number;
  sourceipv4address_rawHexSample: string;
  sourceipv4address_metadataTag: Record<string, string>;
  destinationipv4address_primaryMetric: number;
  destinationipv4address_secondaryMetric: number;
  destinationipv4address_baselineAverage: number;
  destinationipv4address_peakObserved: number;
  destinationipv4address_standardDeviation: number;
  destinationipv4address_rawHexSample: string;
  destinationipv4address_metadataTag: Record<string, string>;
  packetdeltacount_primaryMetric: number;
  packetdeltacount_secondaryMetric: number;
  packetdeltacount_baselineAverage: number;
  packetdeltacount_peakObserved: number;
  packetdeltacount_standardDeviation: number;
  packetdeltacount_rawHexSample: string;
  packetdeltacount_metadataTag: Record<string, string>;
  octetdeltacount_primaryMetric: number;
  octetdeltacount_secondaryMetric: number;
  octetdeltacount_baselineAverage: number;
  octetdeltacount_peakObserved: number;
  octetdeltacount_standardDeviation: number;
  octetdeltacount_rawHexSample: string;
  octetdeltacount_metadataTag: Record<string, string>;
  protocolidentifier_primaryMetric: number;
  protocolidentifier_secondaryMetric: number;
  protocolidentifier_baselineAverage: number;
  protocolidentifier_peakObserved: number;
  protocolidentifier_standardDeviation: number;
  protocolidentifier_rawHexSample: string;
  protocolidentifier_metadataTag: Record<string, string>;
  tcpcontrolbits_primaryMetric: number;
  tcpcontrolbits_secondaryMetric: number;
  tcpcontrolbits_baselineAverage: number;
  tcpcontrolbits_peakObserved: number;
  tcpcontrolbits_standardDeviation: number;
  tcpcontrolbits_rawHexSample: string;
  tcpcontrolbits_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type NetflowV9IpfixFilterV17 = Partial<NetflowV9IpfixRecordV17> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface NetflowV9IpfixRecordV18 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  sourceipv4address_primaryMetric: number;
  sourceipv4address_secondaryMetric: number;
  sourceipv4address_baselineAverage: number;
  sourceipv4address_peakObserved: number;
  sourceipv4address_standardDeviation: number;
  sourceipv4address_rawHexSample: string;
  sourceipv4address_metadataTag: Record<string, string>;
  destinationipv4address_primaryMetric: number;
  destinationipv4address_secondaryMetric: number;
  destinationipv4address_baselineAverage: number;
  destinationipv4address_peakObserved: number;
  destinationipv4address_standardDeviation: number;
  destinationipv4address_rawHexSample: string;
  destinationipv4address_metadataTag: Record<string, string>;
  packetdeltacount_primaryMetric: number;
  packetdeltacount_secondaryMetric: number;
  packetdeltacount_baselineAverage: number;
  packetdeltacount_peakObserved: number;
  packetdeltacount_standardDeviation: number;
  packetdeltacount_rawHexSample: string;
  packetdeltacount_metadataTag: Record<string, string>;
  octetdeltacount_primaryMetric: number;
  octetdeltacount_secondaryMetric: number;
  octetdeltacount_baselineAverage: number;
  octetdeltacount_peakObserved: number;
  octetdeltacount_standardDeviation: number;
  octetdeltacount_rawHexSample: string;
  octetdeltacount_metadataTag: Record<string, string>;
  protocolidentifier_primaryMetric: number;
  protocolidentifier_secondaryMetric: number;
  protocolidentifier_baselineAverage: number;
  protocolidentifier_peakObserved: number;
  protocolidentifier_standardDeviation: number;
  protocolidentifier_rawHexSample: string;
  protocolidentifier_metadataTag: Record<string, string>;
  tcpcontrolbits_primaryMetric: number;
  tcpcontrolbits_secondaryMetric: number;
  tcpcontrolbits_baselineAverage: number;
  tcpcontrolbits_peakObserved: number;
  tcpcontrolbits_standardDeviation: number;
  tcpcontrolbits_rawHexSample: string;
  tcpcontrolbits_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type NetflowV9IpfixFilterV18 = Partial<NetflowV9IpfixRecordV18> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface NetflowV9IpfixRecordV19 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  sourceipv4address_primaryMetric: number;
  sourceipv4address_secondaryMetric: number;
  sourceipv4address_baselineAverage: number;
  sourceipv4address_peakObserved: number;
  sourceipv4address_standardDeviation: number;
  sourceipv4address_rawHexSample: string;
  sourceipv4address_metadataTag: Record<string, string>;
  destinationipv4address_primaryMetric: number;
  destinationipv4address_secondaryMetric: number;
  destinationipv4address_baselineAverage: number;
  destinationipv4address_peakObserved: number;
  destinationipv4address_standardDeviation: number;
  destinationipv4address_rawHexSample: string;
  destinationipv4address_metadataTag: Record<string, string>;
  packetdeltacount_primaryMetric: number;
  packetdeltacount_secondaryMetric: number;
  packetdeltacount_baselineAverage: number;
  packetdeltacount_peakObserved: number;
  packetdeltacount_standardDeviation: number;
  packetdeltacount_rawHexSample: string;
  packetdeltacount_metadataTag: Record<string, string>;
  octetdeltacount_primaryMetric: number;
  octetdeltacount_secondaryMetric: number;
  octetdeltacount_baselineAverage: number;
  octetdeltacount_peakObserved: number;
  octetdeltacount_standardDeviation: number;
  octetdeltacount_rawHexSample: string;
  octetdeltacount_metadataTag: Record<string, string>;
  protocolidentifier_primaryMetric: number;
  protocolidentifier_secondaryMetric: number;
  protocolidentifier_baselineAverage: number;
  protocolidentifier_peakObserved: number;
  protocolidentifier_standardDeviation: number;
  protocolidentifier_rawHexSample: string;
  protocolidentifier_metadataTag: Record<string, string>;
  tcpcontrolbits_primaryMetric: number;
  tcpcontrolbits_secondaryMetric: number;
  tcpcontrolbits_baselineAverage: number;
  tcpcontrolbits_peakObserved: number;
  tcpcontrolbits_standardDeviation: number;
  tcpcontrolbits_rawHexSample: string;
  tcpcontrolbits_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type NetflowV9IpfixFilterV19 = Partial<NetflowV9IpfixRecordV19> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface NetflowV9IpfixRecordV20 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  sourceipv4address_primaryMetric: number;
  sourceipv4address_secondaryMetric: number;
  sourceipv4address_baselineAverage: number;
  sourceipv4address_peakObserved: number;
  sourceipv4address_standardDeviation: number;
  sourceipv4address_rawHexSample: string;
  sourceipv4address_metadataTag: Record<string, string>;
  destinationipv4address_primaryMetric: number;
  destinationipv4address_secondaryMetric: number;
  destinationipv4address_baselineAverage: number;
  destinationipv4address_peakObserved: number;
  destinationipv4address_standardDeviation: number;
  destinationipv4address_rawHexSample: string;
  destinationipv4address_metadataTag: Record<string, string>;
  packetdeltacount_primaryMetric: number;
  packetdeltacount_secondaryMetric: number;
  packetdeltacount_baselineAverage: number;
  packetdeltacount_peakObserved: number;
  packetdeltacount_standardDeviation: number;
  packetdeltacount_rawHexSample: string;
  packetdeltacount_metadataTag: Record<string, string>;
  octetdeltacount_primaryMetric: number;
  octetdeltacount_secondaryMetric: number;
  octetdeltacount_baselineAverage: number;
  octetdeltacount_peakObserved: number;
  octetdeltacount_standardDeviation: number;
  octetdeltacount_rawHexSample: string;
  octetdeltacount_metadataTag: Record<string, string>;
  protocolidentifier_primaryMetric: number;
  protocolidentifier_secondaryMetric: number;
  protocolidentifier_baselineAverage: number;
  protocolidentifier_peakObserved: number;
  protocolidentifier_standardDeviation: number;
  protocolidentifier_rawHexSample: string;
  protocolidentifier_metadataTag: Record<string, string>;
  tcpcontrolbits_primaryMetric: number;
  tcpcontrolbits_secondaryMetric: number;
  tcpcontrolbits_baselineAverage: number;
  tcpcontrolbits_peakObserved: number;
  tcpcontrolbits_standardDeviation: number;
  tcpcontrolbits_rawHexSample: string;
  tcpcontrolbits_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type NetflowV9IpfixFilterV20 = Partial<NetflowV9IpfixRecordV20> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface NetflowV9IpfixRecordV21 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  sourceipv4address_primaryMetric: number;
  sourceipv4address_secondaryMetric: number;
  sourceipv4address_baselineAverage: number;
  sourceipv4address_peakObserved: number;
  sourceipv4address_standardDeviation: number;
  sourceipv4address_rawHexSample: string;
  sourceipv4address_metadataTag: Record<string, string>;
  destinationipv4address_primaryMetric: number;
  destinationipv4address_secondaryMetric: number;
  destinationipv4address_baselineAverage: number;
  destinationipv4address_peakObserved: number;
  destinationipv4address_standardDeviation: number;
  destinationipv4address_rawHexSample: string;
  destinationipv4address_metadataTag: Record<string, string>;
  packetdeltacount_primaryMetric: number;
  packetdeltacount_secondaryMetric: number;
  packetdeltacount_baselineAverage: number;
  packetdeltacount_peakObserved: number;
  packetdeltacount_standardDeviation: number;
  packetdeltacount_rawHexSample: string;
  packetdeltacount_metadataTag: Record<string, string>;
  octetdeltacount_primaryMetric: number;
  octetdeltacount_secondaryMetric: number;
  octetdeltacount_baselineAverage: number;
  octetdeltacount_peakObserved: number;
  octetdeltacount_standardDeviation: number;
  octetdeltacount_rawHexSample: string;
  octetdeltacount_metadataTag: Record<string, string>;
  protocolidentifier_primaryMetric: number;
  protocolidentifier_secondaryMetric: number;
  protocolidentifier_baselineAverage: number;
  protocolidentifier_peakObserved: number;
  protocolidentifier_standardDeviation: number;
  protocolidentifier_rawHexSample: string;
  protocolidentifier_metadataTag: Record<string, string>;
  tcpcontrolbits_primaryMetric: number;
  tcpcontrolbits_secondaryMetric: number;
  tcpcontrolbits_baselineAverage: number;
  tcpcontrolbits_peakObserved: number;
  tcpcontrolbits_standardDeviation: number;
  tcpcontrolbits_rawHexSample: string;
  tcpcontrolbits_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type NetflowV9IpfixFilterV21 = Partial<NetflowV9IpfixRecordV21> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface NetflowV9IpfixRecordV22 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  sourceipv4address_primaryMetric: number;
  sourceipv4address_secondaryMetric: number;
  sourceipv4address_baselineAverage: number;
  sourceipv4address_peakObserved: number;
  sourceipv4address_standardDeviation: number;
  sourceipv4address_rawHexSample: string;
  sourceipv4address_metadataTag: Record<string, string>;
  destinationipv4address_primaryMetric: number;
  destinationipv4address_secondaryMetric: number;
  destinationipv4address_baselineAverage: number;
  destinationipv4address_peakObserved: number;
  destinationipv4address_standardDeviation: number;
  destinationipv4address_rawHexSample: string;
  destinationipv4address_metadataTag: Record<string, string>;
  packetdeltacount_primaryMetric: number;
  packetdeltacount_secondaryMetric: number;
  packetdeltacount_baselineAverage: number;
  packetdeltacount_peakObserved: number;
  packetdeltacount_standardDeviation: number;
  packetdeltacount_rawHexSample: string;
  packetdeltacount_metadataTag: Record<string, string>;
  octetdeltacount_primaryMetric: number;
  octetdeltacount_secondaryMetric: number;
  octetdeltacount_baselineAverage: number;
  octetdeltacount_peakObserved: number;
  octetdeltacount_standardDeviation: number;
  octetdeltacount_rawHexSample: string;
  octetdeltacount_metadataTag: Record<string, string>;
  protocolidentifier_primaryMetric: number;
  protocolidentifier_secondaryMetric: number;
  protocolidentifier_baselineAverage: number;
  protocolidentifier_peakObserved: number;
  protocolidentifier_standardDeviation: number;
  protocolidentifier_rawHexSample: string;
  protocolidentifier_metadataTag: Record<string, string>;
  tcpcontrolbits_primaryMetric: number;
  tcpcontrolbits_secondaryMetric: number;
  tcpcontrolbits_baselineAverage: number;
  tcpcontrolbits_peakObserved: number;
  tcpcontrolbits_standardDeviation: number;
  tcpcontrolbits_rawHexSample: string;
  tcpcontrolbits_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type NetflowV9IpfixFilterV22 = Partial<NetflowV9IpfixRecordV22> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface NetflowV9IpfixRecordV23 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  sourceipv4address_primaryMetric: number;
  sourceipv4address_secondaryMetric: number;
  sourceipv4address_baselineAverage: number;
  sourceipv4address_peakObserved: number;
  sourceipv4address_standardDeviation: number;
  sourceipv4address_rawHexSample: string;
  sourceipv4address_metadataTag: Record<string, string>;
  destinationipv4address_primaryMetric: number;
  destinationipv4address_secondaryMetric: number;
  destinationipv4address_baselineAverage: number;
  destinationipv4address_peakObserved: number;
  destinationipv4address_standardDeviation: number;
  destinationipv4address_rawHexSample: string;
  destinationipv4address_metadataTag: Record<string, string>;
  packetdeltacount_primaryMetric: number;
  packetdeltacount_secondaryMetric: number;
  packetdeltacount_baselineAverage: number;
  packetdeltacount_peakObserved: number;
  packetdeltacount_standardDeviation: number;
  packetdeltacount_rawHexSample: string;
  packetdeltacount_metadataTag: Record<string, string>;
  octetdeltacount_primaryMetric: number;
  octetdeltacount_secondaryMetric: number;
  octetdeltacount_baselineAverage: number;
  octetdeltacount_peakObserved: number;
  octetdeltacount_standardDeviation: number;
  octetdeltacount_rawHexSample: string;
  octetdeltacount_metadataTag: Record<string, string>;
  protocolidentifier_primaryMetric: number;
  protocolidentifier_secondaryMetric: number;
  protocolidentifier_baselineAverage: number;
  protocolidentifier_peakObserved: number;
  protocolidentifier_standardDeviation: number;
  protocolidentifier_rawHexSample: string;
  protocolidentifier_metadataTag: Record<string, string>;
  tcpcontrolbits_primaryMetric: number;
  tcpcontrolbits_secondaryMetric: number;
  tcpcontrolbits_baselineAverage: number;
  tcpcontrolbits_peakObserved: number;
  tcpcontrolbits_standardDeviation: number;
  tcpcontrolbits_rawHexSample: string;
  tcpcontrolbits_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type NetflowV9IpfixFilterV23 = Partial<NetflowV9IpfixRecordV23> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface NetflowV9IpfixRecordV24 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  sourceipv4address_primaryMetric: number;
  sourceipv4address_secondaryMetric: number;
  sourceipv4address_baselineAverage: number;
  sourceipv4address_peakObserved: number;
  sourceipv4address_standardDeviation: number;
  sourceipv4address_rawHexSample: string;
  sourceipv4address_metadataTag: Record<string, string>;
  destinationipv4address_primaryMetric: number;
  destinationipv4address_secondaryMetric: number;
  destinationipv4address_baselineAverage: number;
  destinationipv4address_peakObserved: number;
  destinationipv4address_standardDeviation: number;
  destinationipv4address_rawHexSample: string;
  destinationipv4address_metadataTag: Record<string, string>;
  packetdeltacount_primaryMetric: number;
  packetdeltacount_secondaryMetric: number;
  packetdeltacount_baselineAverage: number;
  packetdeltacount_peakObserved: number;
  packetdeltacount_standardDeviation: number;
  packetdeltacount_rawHexSample: string;
  packetdeltacount_metadataTag: Record<string, string>;
  octetdeltacount_primaryMetric: number;
  octetdeltacount_secondaryMetric: number;
  octetdeltacount_baselineAverage: number;
  octetdeltacount_peakObserved: number;
  octetdeltacount_standardDeviation: number;
  octetdeltacount_rawHexSample: string;
  octetdeltacount_metadataTag: Record<string, string>;
  protocolidentifier_primaryMetric: number;
  protocolidentifier_secondaryMetric: number;
  protocolidentifier_baselineAverage: number;
  protocolidentifier_peakObserved: number;
  protocolidentifier_standardDeviation: number;
  protocolidentifier_rawHexSample: string;
  protocolidentifier_metadataTag: Record<string, string>;
  tcpcontrolbits_primaryMetric: number;
  tcpcontrolbits_secondaryMetric: number;
  tcpcontrolbits_baselineAverage: number;
  tcpcontrolbits_peakObserved: number;
  tcpcontrolbits_standardDeviation: number;
  tcpcontrolbits_rawHexSample: string;
  tcpcontrolbits_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type NetflowV9IpfixFilterV24 = Partial<NetflowV9IpfixRecordV24> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface NetflowV9IpfixRecordV25 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  sourceipv4address_primaryMetric: number;
  sourceipv4address_secondaryMetric: number;
  sourceipv4address_baselineAverage: number;
  sourceipv4address_peakObserved: number;
  sourceipv4address_standardDeviation: number;
  sourceipv4address_rawHexSample: string;
  sourceipv4address_metadataTag: Record<string, string>;
  destinationipv4address_primaryMetric: number;
  destinationipv4address_secondaryMetric: number;
  destinationipv4address_baselineAverage: number;
  destinationipv4address_peakObserved: number;
  destinationipv4address_standardDeviation: number;
  destinationipv4address_rawHexSample: string;
  destinationipv4address_metadataTag: Record<string, string>;
  packetdeltacount_primaryMetric: number;
  packetdeltacount_secondaryMetric: number;
  packetdeltacount_baselineAverage: number;
  packetdeltacount_peakObserved: number;
  packetdeltacount_standardDeviation: number;
  packetdeltacount_rawHexSample: string;
  packetdeltacount_metadataTag: Record<string, string>;
  octetdeltacount_primaryMetric: number;
  octetdeltacount_secondaryMetric: number;
  octetdeltacount_baselineAverage: number;
  octetdeltacount_peakObserved: number;
  octetdeltacount_standardDeviation: number;
  octetdeltacount_rawHexSample: string;
  octetdeltacount_metadataTag: Record<string, string>;
  protocolidentifier_primaryMetric: number;
  protocolidentifier_secondaryMetric: number;
  protocolidentifier_baselineAverage: number;
  protocolidentifier_peakObserved: number;
  protocolidentifier_standardDeviation: number;
  protocolidentifier_rawHexSample: string;
  protocolidentifier_metadataTag: Record<string, string>;
  tcpcontrolbits_primaryMetric: number;
  tcpcontrolbits_secondaryMetric: number;
  tcpcontrolbits_baselineAverage: number;
  tcpcontrolbits_peakObserved: number;
  tcpcontrolbits_standardDeviation: number;
  tcpcontrolbits_rawHexSample: string;
  tcpcontrolbits_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type NetflowV9IpfixFilterV25 = Partial<NetflowV9IpfixRecordV25> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface NetflowV9IpfixRecordV26 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  sourceipv4address_primaryMetric: number;
  sourceipv4address_secondaryMetric: number;
  sourceipv4address_baselineAverage: number;
  sourceipv4address_peakObserved: number;
  sourceipv4address_standardDeviation: number;
  sourceipv4address_rawHexSample: string;
  sourceipv4address_metadataTag: Record<string, string>;
  destinationipv4address_primaryMetric: number;
  destinationipv4address_secondaryMetric: number;
  destinationipv4address_baselineAverage: number;
  destinationipv4address_peakObserved: number;
  destinationipv4address_standardDeviation: number;
  destinationipv4address_rawHexSample: string;
  destinationipv4address_metadataTag: Record<string, string>;
  packetdeltacount_primaryMetric: number;
  packetdeltacount_secondaryMetric: number;
  packetdeltacount_baselineAverage: number;
  packetdeltacount_peakObserved: number;
  packetdeltacount_standardDeviation: number;
  packetdeltacount_rawHexSample: string;
  packetdeltacount_metadataTag: Record<string, string>;
  octetdeltacount_primaryMetric: number;
  octetdeltacount_secondaryMetric: number;
  octetdeltacount_baselineAverage: number;
  octetdeltacount_peakObserved: number;
  octetdeltacount_standardDeviation: number;
  octetdeltacount_rawHexSample: string;
  octetdeltacount_metadataTag: Record<string, string>;
  protocolidentifier_primaryMetric: number;
  protocolidentifier_secondaryMetric: number;
  protocolidentifier_baselineAverage: number;
  protocolidentifier_peakObserved: number;
  protocolidentifier_standardDeviation: number;
  protocolidentifier_rawHexSample: string;
  protocolidentifier_metadataTag: Record<string, string>;
  tcpcontrolbits_primaryMetric: number;
  tcpcontrolbits_secondaryMetric: number;
  tcpcontrolbits_baselineAverage: number;
  tcpcontrolbits_peakObserved: number;
  tcpcontrolbits_standardDeviation: number;
  tcpcontrolbits_rawHexSample: string;
  tcpcontrolbits_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type NetflowV9IpfixFilterV26 = Partial<NetflowV9IpfixRecordV26> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface NetflowV9IpfixRecordV27 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  sourceipv4address_primaryMetric: number;
  sourceipv4address_secondaryMetric: number;
  sourceipv4address_baselineAverage: number;
  sourceipv4address_peakObserved: number;
  sourceipv4address_standardDeviation: number;
  sourceipv4address_rawHexSample: string;
  sourceipv4address_metadataTag: Record<string, string>;
  destinationipv4address_primaryMetric: number;
  destinationipv4address_secondaryMetric: number;
  destinationipv4address_baselineAverage: number;
  destinationipv4address_peakObserved: number;
  destinationipv4address_standardDeviation: number;
  destinationipv4address_rawHexSample: string;
  destinationipv4address_metadataTag: Record<string, string>;
  packetdeltacount_primaryMetric: number;
  packetdeltacount_secondaryMetric: number;
  packetdeltacount_baselineAverage: number;
  packetdeltacount_peakObserved: number;
  packetdeltacount_standardDeviation: number;
  packetdeltacount_rawHexSample: string;
  packetdeltacount_metadataTag: Record<string, string>;
  octetdeltacount_primaryMetric: number;
  octetdeltacount_secondaryMetric: number;
  octetdeltacount_baselineAverage: number;
  octetdeltacount_peakObserved: number;
  octetdeltacount_standardDeviation: number;
  octetdeltacount_rawHexSample: string;
  octetdeltacount_metadataTag: Record<string, string>;
  protocolidentifier_primaryMetric: number;
  protocolidentifier_secondaryMetric: number;
  protocolidentifier_baselineAverage: number;
  protocolidentifier_peakObserved: number;
  protocolidentifier_standardDeviation: number;
  protocolidentifier_rawHexSample: string;
  protocolidentifier_metadataTag: Record<string, string>;
  tcpcontrolbits_primaryMetric: number;
  tcpcontrolbits_secondaryMetric: number;
  tcpcontrolbits_baselineAverage: number;
  tcpcontrolbits_peakObserved: number;
  tcpcontrolbits_standardDeviation: number;
  tcpcontrolbits_rawHexSample: string;
  tcpcontrolbits_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type NetflowV9IpfixFilterV27 = Partial<NetflowV9IpfixRecordV27> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface NetflowV9IpfixRecordV28 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  sourceipv4address_primaryMetric: number;
  sourceipv4address_secondaryMetric: number;
  sourceipv4address_baselineAverage: number;
  sourceipv4address_peakObserved: number;
  sourceipv4address_standardDeviation: number;
  sourceipv4address_rawHexSample: string;
  sourceipv4address_metadataTag: Record<string, string>;
  destinationipv4address_primaryMetric: number;
  destinationipv4address_secondaryMetric: number;
  destinationipv4address_baselineAverage: number;
  destinationipv4address_peakObserved: number;
  destinationipv4address_standardDeviation: number;
  destinationipv4address_rawHexSample: string;
  destinationipv4address_metadataTag: Record<string, string>;
  packetdeltacount_primaryMetric: number;
  packetdeltacount_secondaryMetric: number;
  packetdeltacount_baselineAverage: number;
  packetdeltacount_peakObserved: number;
  packetdeltacount_standardDeviation: number;
  packetdeltacount_rawHexSample: string;
  packetdeltacount_metadataTag: Record<string, string>;
  octetdeltacount_primaryMetric: number;
  octetdeltacount_secondaryMetric: number;
  octetdeltacount_baselineAverage: number;
  octetdeltacount_peakObserved: number;
  octetdeltacount_standardDeviation: number;
  octetdeltacount_rawHexSample: string;
  octetdeltacount_metadataTag: Record<string, string>;
  protocolidentifier_primaryMetric: number;
  protocolidentifier_secondaryMetric: number;
  protocolidentifier_baselineAverage: number;
  protocolidentifier_peakObserved: number;
  protocolidentifier_standardDeviation: number;
  protocolidentifier_rawHexSample: string;
  protocolidentifier_metadataTag: Record<string, string>;
  tcpcontrolbits_primaryMetric: number;
  tcpcontrolbits_secondaryMetric: number;
  tcpcontrolbits_baselineAverage: number;
  tcpcontrolbits_peakObserved: number;
  tcpcontrolbits_standardDeviation: number;
  tcpcontrolbits_rawHexSample: string;
  tcpcontrolbits_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type NetflowV9IpfixFilterV28 = Partial<NetflowV9IpfixRecordV28> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface NetflowV9IpfixRecordV29 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  sourceipv4address_primaryMetric: number;
  sourceipv4address_secondaryMetric: number;
  sourceipv4address_baselineAverage: number;
  sourceipv4address_peakObserved: number;
  sourceipv4address_standardDeviation: number;
  sourceipv4address_rawHexSample: string;
  sourceipv4address_metadataTag: Record<string, string>;
  destinationipv4address_primaryMetric: number;
  destinationipv4address_secondaryMetric: number;
  destinationipv4address_baselineAverage: number;
  destinationipv4address_peakObserved: number;
  destinationipv4address_standardDeviation: number;
  destinationipv4address_rawHexSample: string;
  destinationipv4address_metadataTag: Record<string, string>;
  packetdeltacount_primaryMetric: number;
  packetdeltacount_secondaryMetric: number;
  packetdeltacount_baselineAverage: number;
  packetdeltacount_peakObserved: number;
  packetdeltacount_standardDeviation: number;
  packetdeltacount_rawHexSample: string;
  packetdeltacount_metadataTag: Record<string, string>;
  octetdeltacount_primaryMetric: number;
  octetdeltacount_secondaryMetric: number;
  octetdeltacount_baselineAverage: number;
  octetdeltacount_peakObserved: number;
  octetdeltacount_standardDeviation: number;
  octetdeltacount_rawHexSample: string;
  octetdeltacount_metadataTag: Record<string, string>;
  protocolidentifier_primaryMetric: number;
  protocolidentifier_secondaryMetric: number;
  protocolidentifier_baselineAverage: number;
  protocolidentifier_peakObserved: number;
  protocolidentifier_standardDeviation: number;
  protocolidentifier_rawHexSample: string;
  protocolidentifier_metadataTag: Record<string, string>;
  tcpcontrolbits_primaryMetric: number;
  tcpcontrolbits_secondaryMetric: number;
  tcpcontrolbits_baselineAverage: number;
  tcpcontrolbits_peakObserved: number;
  tcpcontrolbits_standardDeviation: number;
  tcpcontrolbits_rawHexSample: string;
  tcpcontrolbits_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type NetflowV9IpfixFilterV29 = Partial<NetflowV9IpfixRecordV29> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface NetflowV9IpfixRecordV30 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  sourceipv4address_primaryMetric: number;
  sourceipv4address_secondaryMetric: number;
  sourceipv4address_baselineAverage: number;
  sourceipv4address_peakObserved: number;
  sourceipv4address_standardDeviation: number;
  sourceipv4address_rawHexSample: string;
  sourceipv4address_metadataTag: Record<string, string>;
  destinationipv4address_primaryMetric: number;
  destinationipv4address_secondaryMetric: number;
  destinationipv4address_baselineAverage: number;
  destinationipv4address_peakObserved: number;
  destinationipv4address_standardDeviation: number;
  destinationipv4address_rawHexSample: string;
  destinationipv4address_metadataTag: Record<string, string>;
  packetdeltacount_primaryMetric: number;
  packetdeltacount_secondaryMetric: number;
  packetdeltacount_baselineAverage: number;
  packetdeltacount_peakObserved: number;
  packetdeltacount_standardDeviation: number;
  packetdeltacount_rawHexSample: string;
  packetdeltacount_metadataTag: Record<string, string>;
  octetdeltacount_primaryMetric: number;
  octetdeltacount_secondaryMetric: number;
  octetdeltacount_baselineAverage: number;
  octetdeltacount_peakObserved: number;
  octetdeltacount_standardDeviation: number;
  octetdeltacount_rawHexSample: string;
  octetdeltacount_metadataTag: Record<string, string>;
  protocolidentifier_primaryMetric: number;
  protocolidentifier_secondaryMetric: number;
  protocolidentifier_baselineAverage: number;
  protocolidentifier_peakObserved: number;
  protocolidentifier_standardDeviation: number;
  protocolidentifier_rawHexSample: string;
  protocolidentifier_metadataTag: Record<string, string>;
  tcpcontrolbits_primaryMetric: number;
  tcpcontrolbits_secondaryMetric: number;
  tcpcontrolbits_baselineAverage: number;
  tcpcontrolbits_peakObserved: number;
  tcpcontrolbits_standardDeviation: number;
  tcpcontrolbits_rawHexSample: string;
  tcpcontrolbits_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type NetflowV9IpfixFilterV30 = Partial<NetflowV9IpfixRecordV30> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface NetflowV9IpfixRecordV31 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  sourceipv4address_primaryMetric: number;
  sourceipv4address_secondaryMetric: number;
  sourceipv4address_baselineAverage: number;
  sourceipv4address_peakObserved: number;
  sourceipv4address_standardDeviation: number;
  sourceipv4address_rawHexSample: string;
  sourceipv4address_metadataTag: Record<string, string>;
  destinationipv4address_primaryMetric: number;
  destinationipv4address_secondaryMetric: number;
  destinationipv4address_baselineAverage: number;
  destinationipv4address_peakObserved: number;
  destinationipv4address_standardDeviation: number;
  destinationipv4address_rawHexSample: string;
  destinationipv4address_metadataTag: Record<string, string>;
  packetdeltacount_primaryMetric: number;
  packetdeltacount_secondaryMetric: number;
  packetdeltacount_baselineAverage: number;
  packetdeltacount_peakObserved: number;
  packetdeltacount_standardDeviation: number;
  packetdeltacount_rawHexSample: string;
  packetdeltacount_metadataTag: Record<string, string>;
  octetdeltacount_primaryMetric: number;
  octetdeltacount_secondaryMetric: number;
  octetdeltacount_baselineAverage: number;
  octetdeltacount_peakObserved: number;
  octetdeltacount_standardDeviation: number;
  octetdeltacount_rawHexSample: string;
  octetdeltacount_metadataTag: Record<string, string>;
  protocolidentifier_primaryMetric: number;
  protocolidentifier_secondaryMetric: number;
  protocolidentifier_baselineAverage: number;
  protocolidentifier_peakObserved: number;
  protocolidentifier_standardDeviation: number;
  protocolidentifier_rawHexSample: string;
  protocolidentifier_metadataTag: Record<string, string>;
  tcpcontrolbits_primaryMetric: number;
  tcpcontrolbits_secondaryMetric: number;
  tcpcontrolbits_baselineAverage: number;
  tcpcontrolbits_peakObserved: number;
  tcpcontrolbits_standardDeviation: number;
  tcpcontrolbits_rawHexSample: string;
  tcpcontrolbits_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type NetflowV9IpfixFilterV31 = Partial<NetflowV9IpfixRecordV31> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface NetflowV9IpfixRecordV32 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  sourceipv4address_primaryMetric: number;
  sourceipv4address_secondaryMetric: number;
  sourceipv4address_baselineAverage: number;
  sourceipv4address_peakObserved: number;
  sourceipv4address_standardDeviation: number;
  sourceipv4address_rawHexSample: string;
  sourceipv4address_metadataTag: Record<string, string>;
  destinationipv4address_primaryMetric: number;
  destinationipv4address_secondaryMetric: number;
  destinationipv4address_baselineAverage: number;
  destinationipv4address_peakObserved: number;
  destinationipv4address_standardDeviation: number;
  destinationipv4address_rawHexSample: string;
  destinationipv4address_metadataTag: Record<string, string>;
  packetdeltacount_primaryMetric: number;
  packetdeltacount_secondaryMetric: number;
  packetdeltacount_baselineAverage: number;
  packetdeltacount_peakObserved: number;
  packetdeltacount_standardDeviation: number;
  packetdeltacount_rawHexSample: string;
  packetdeltacount_metadataTag: Record<string, string>;
  octetdeltacount_primaryMetric: number;
  octetdeltacount_secondaryMetric: number;
  octetdeltacount_baselineAverage: number;
  octetdeltacount_peakObserved: number;
  octetdeltacount_standardDeviation: number;
  octetdeltacount_rawHexSample: string;
  octetdeltacount_metadataTag: Record<string, string>;
  protocolidentifier_primaryMetric: number;
  protocolidentifier_secondaryMetric: number;
  protocolidentifier_baselineAverage: number;
  protocolidentifier_peakObserved: number;
  protocolidentifier_standardDeviation: number;
  protocolidentifier_rawHexSample: string;
  protocolidentifier_metadataTag: Record<string, string>;
  tcpcontrolbits_primaryMetric: number;
  tcpcontrolbits_secondaryMetric: number;
  tcpcontrolbits_baselineAverage: number;
  tcpcontrolbits_peakObserved: number;
  tcpcontrolbits_standardDeviation: number;
  tcpcontrolbits_rawHexSample: string;
  tcpcontrolbits_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type NetflowV9IpfixFilterV32 = Partial<NetflowV9IpfixRecordV32> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface NetflowV9IpfixRecordV33 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  sourceipv4address_primaryMetric: number;
  sourceipv4address_secondaryMetric: number;
  sourceipv4address_baselineAverage: number;
  sourceipv4address_peakObserved: number;
  sourceipv4address_standardDeviation: number;
  sourceipv4address_rawHexSample: string;
  sourceipv4address_metadataTag: Record<string, string>;
  destinationipv4address_primaryMetric: number;
  destinationipv4address_secondaryMetric: number;
  destinationipv4address_baselineAverage: number;
  destinationipv4address_peakObserved: number;
  destinationipv4address_standardDeviation: number;
  destinationipv4address_rawHexSample: string;
  destinationipv4address_metadataTag: Record<string, string>;
  packetdeltacount_primaryMetric: number;
  packetdeltacount_secondaryMetric: number;
  packetdeltacount_baselineAverage: number;
  packetdeltacount_peakObserved: number;
  packetdeltacount_standardDeviation: number;
  packetdeltacount_rawHexSample: string;
  packetdeltacount_metadataTag: Record<string, string>;
  octetdeltacount_primaryMetric: number;
  octetdeltacount_secondaryMetric: number;
  octetdeltacount_baselineAverage: number;
  octetdeltacount_peakObserved: number;
  octetdeltacount_standardDeviation: number;
  octetdeltacount_rawHexSample: string;
  octetdeltacount_metadataTag: Record<string, string>;
  protocolidentifier_primaryMetric: number;
  protocolidentifier_secondaryMetric: number;
  protocolidentifier_baselineAverage: number;
  protocolidentifier_peakObserved: number;
  protocolidentifier_standardDeviation: number;
  protocolidentifier_rawHexSample: string;
  protocolidentifier_metadataTag: Record<string, string>;
  tcpcontrolbits_primaryMetric: number;
  tcpcontrolbits_secondaryMetric: number;
  tcpcontrolbits_baselineAverage: number;
  tcpcontrolbits_peakObserved: number;
  tcpcontrolbits_standardDeviation: number;
  tcpcontrolbits_rawHexSample: string;
  tcpcontrolbits_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type NetflowV9IpfixFilterV33 = Partial<NetflowV9IpfixRecordV33> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface NetflowV9IpfixRecordV34 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  sourceipv4address_primaryMetric: number;
  sourceipv4address_secondaryMetric: number;
  sourceipv4address_baselineAverage: number;
  sourceipv4address_peakObserved: number;
  sourceipv4address_standardDeviation: number;
  sourceipv4address_rawHexSample: string;
  sourceipv4address_metadataTag: Record<string, string>;
  destinationipv4address_primaryMetric: number;
  destinationipv4address_secondaryMetric: number;
  destinationipv4address_baselineAverage: number;
  destinationipv4address_peakObserved: number;
  destinationipv4address_standardDeviation: number;
  destinationipv4address_rawHexSample: string;
  destinationipv4address_metadataTag: Record<string, string>;
  packetdeltacount_primaryMetric: number;
  packetdeltacount_secondaryMetric: number;
  packetdeltacount_baselineAverage: number;
  packetdeltacount_peakObserved: number;
  packetdeltacount_standardDeviation: number;
  packetdeltacount_rawHexSample: string;
  packetdeltacount_metadataTag: Record<string, string>;
  octetdeltacount_primaryMetric: number;
  octetdeltacount_secondaryMetric: number;
  octetdeltacount_baselineAverage: number;
  octetdeltacount_peakObserved: number;
  octetdeltacount_standardDeviation: number;
  octetdeltacount_rawHexSample: string;
  octetdeltacount_metadataTag: Record<string, string>;
  protocolidentifier_primaryMetric: number;
  protocolidentifier_secondaryMetric: number;
  protocolidentifier_baselineAverage: number;
  protocolidentifier_peakObserved: number;
  protocolidentifier_standardDeviation: number;
  protocolidentifier_rawHexSample: string;
  protocolidentifier_metadataTag: Record<string, string>;
  tcpcontrolbits_primaryMetric: number;
  tcpcontrolbits_secondaryMetric: number;
  tcpcontrolbits_baselineAverage: number;
  tcpcontrolbits_peakObserved: number;
  tcpcontrolbits_standardDeviation: number;
  tcpcontrolbits_rawHexSample: string;
  tcpcontrolbits_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type NetflowV9IpfixFilterV34 = Partial<NetflowV9IpfixRecordV34> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface NetflowV9IpfixRecordV35 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  sourceipv4address_primaryMetric: number;
  sourceipv4address_secondaryMetric: number;
  sourceipv4address_baselineAverage: number;
  sourceipv4address_peakObserved: number;
  sourceipv4address_standardDeviation: number;
  sourceipv4address_rawHexSample: string;
  sourceipv4address_metadataTag: Record<string, string>;
  destinationipv4address_primaryMetric: number;
  destinationipv4address_secondaryMetric: number;
  destinationipv4address_baselineAverage: number;
  destinationipv4address_peakObserved: number;
  destinationipv4address_standardDeviation: number;
  destinationipv4address_rawHexSample: string;
  destinationipv4address_metadataTag: Record<string, string>;
  packetdeltacount_primaryMetric: number;
  packetdeltacount_secondaryMetric: number;
  packetdeltacount_baselineAverage: number;
  packetdeltacount_peakObserved: number;
  packetdeltacount_standardDeviation: number;
  packetdeltacount_rawHexSample: string;
  packetdeltacount_metadataTag: Record<string, string>;
  octetdeltacount_primaryMetric: number;
  octetdeltacount_secondaryMetric: number;
  octetdeltacount_baselineAverage: number;
  octetdeltacount_peakObserved: number;
  octetdeltacount_standardDeviation: number;
  octetdeltacount_rawHexSample: string;
  octetdeltacount_metadataTag: Record<string, string>;
  protocolidentifier_primaryMetric: number;
  protocolidentifier_secondaryMetric: number;
  protocolidentifier_baselineAverage: number;
  protocolidentifier_peakObserved: number;
  protocolidentifier_standardDeviation: number;
  protocolidentifier_rawHexSample: string;
  protocolidentifier_metadataTag: Record<string, string>;
  tcpcontrolbits_primaryMetric: number;
  tcpcontrolbits_secondaryMetric: number;
  tcpcontrolbits_baselineAverage: number;
  tcpcontrolbits_peakObserved: number;
  tcpcontrolbits_standardDeviation: number;
  tcpcontrolbits_rawHexSample: string;
  tcpcontrolbits_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type NetflowV9IpfixFilterV35 = Partial<NetflowV9IpfixRecordV35> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface NetflowV9IpfixRecordV36 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  sourceipv4address_primaryMetric: number;
  sourceipv4address_secondaryMetric: number;
  sourceipv4address_baselineAverage: number;
  sourceipv4address_peakObserved: number;
  sourceipv4address_standardDeviation: number;
  sourceipv4address_rawHexSample: string;
  sourceipv4address_metadataTag: Record<string, string>;
  destinationipv4address_primaryMetric: number;
  destinationipv4address_secondaryMetric: number;
  destinationipv4address_baselineAverage: number;
  destinationipv4address_peakObserved: number;
  destinationipv4address_standardDeviation: number;
  destinationipv4address_rawHexSample: string;
  destinationipv4address_metadataTag: Record<string, string>;
  packetdeltacount_primaryMetric: number;
  packetdeltacount_secondaryMetric: number;
  packetdeltacount_baselineAverage: number;
  packetdeltacount_peakObserved: number;
  packetdeltacount_standardDeviation: number;
  packetdeltacount_rawHexSample: string;
  packetdeltacount_metadataTag: Record<string, string>;
  octetdeltacount_primaryMetric: number;
  octetdeltacount_secondaryMetric: number;
  octetdeltacount_baselineAverage: number;
  octetdeltacount_peakObserved: number;
  octetdeltacount_standardDeviation: number;
  octetdeltacount_rawHexSample: string;
  octetdeltacount_metadataTag: Record<string, string>;
  protocolidentifier_primaryMetric: number;
  protocolidentifier_secondaryMetric: number;
  protocolidentifier_baselineAverage: number;
  protocolidentifier_peakObserved: number;
  protocolidentifier_standardDeviation: number;
  protocolidentifier_rawHexSample: string;
  protocolidentifier_metadataTag: Record<string, string>;
  tcpcontrolbits_primaryMetric: number;
  tcpcontrolbits_secondaryMetric: number;
  tcpcontrolbits_baselineAverage: number;
  tcpcontrolbits_peakObserved: number;
  tcpcontrolbits_standardDeviation: number;
  tcpcontrolbits_rawHexSample: string;
  tcpcontrolbits_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type NetflowV9IpfixFilterV36 = Partial<NetflowV9IpfixRecordV36> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface NetflowV9IpfixRecordV37 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  sourceipv4address_primaryMetric: number;
  sourceipv4address_secondaryMetric: number;
  sourceipv4address_baselineAverage: number;
  sourceipv4address_peakObserved: number;
  sourceipv4address_standardDeviation: number;
  sourceipv4address_rawHexSample: string;
  sourceipv4address_metadataTag: Record<string, string>;
  destinationipv4address_primaryMetric: number;
  destinationipv4address_secondaryMetric: number;
  destinationipv4address_baselineAverage: number;
  destinationipv4address_peakObserved: number;
  destinationipv4address_standardDeviation: number;
  destinationipv4address_rawHexSample: string;
  destinationipv4address_metadataTag: Record<string, string>;
  packetdeltacount_primaryMetric: number;
  packetdeltacount_secondaryMetric: number;
  packetdeltacount_baselineAverage: number;
  packetdeltacount_peakObserved: number;
  packetdeltacount_standardDeviation: number;
  packetdeltacount_rawHexSample: string;
  packetdeltacount_metadataTag: Record<string, string>;
  octetdeltacount_primaryMetric: number;
  octetdeltacount_secondaryMetric: number;
  octetdeltacount_baselineAverage: number;
  octetdeltacount_peakObserved: number;
  octetdeltacount_standardDeviation: number;
  octetdeltacount_rawHexSample: string;
  octetdeltacount_metadataTag: Record<string, string>;
  protocolidentifier_primaryMetric: number;
  protocolidentifier_secondaryMetric: number;
  protocolidentifier_baselineAverage: number;
  protocolidentifier_peakObserved: number;
  protocolidentifier_standardDeviation: number;
  protocolidentifier_rawHexSample: string;
  protocolidentifier_metadataTag: Record<string, string>;
  tcpcontrolbits_primaryMetric: number;
  tcpcontrolbits_secondaryMetric: number;
  tcpcontrolbits_baselineAverage: number;
  tcpcontrolbits_peakObserved: number;
  tcpcontrolbits_standardDeviation: number;
  tcpcontrolbits_rawHexSample: string;
  tcpcontrolbits_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type NetflowV9IpfixFilterV37 = Partial<NetflowV9IpfixRecordV37> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface NetflowV9IpfixRecordV38 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  sourceipv4address_primaryMetric: number;
  sourceipv4address_secondaryMetric: number;
  sourceipv4address_baselineAverage: number;
  sourceipv4address_peakObserved: number;
  sourceipv4address_standardDeviation: number;
  sourceipv4address_rawHexSample: string;
  sourceipv4address_metadataTag: Record<string, string>;
  destinationipv4address_primaryMetric: number;
  destinationipv4address_secondaryMetric: number;
  destinationipv4address_baselineAverage: number;
  destinationipv4address_peakObserved: number;
  destinationipv4address_standardDeviation: number;
  destinationipv4address_rawHexSample: string;
  destinationipv4address_metadataTag: Record<string, string>;
  packetdeltacount_primaryMetric: number;
  packetdeltacount_secondaryMetric: number;
  packetdeltacount_baselineAverage: number;
  packetdeltacount_peakObserved: number;
  packetdeltacount_standardDeviation: number;
  packetdeltacount_rawHexSample: string;
  packetdeltacount_metadataTag: Record<string, string>;
  octetdeltacount_primaryMetric: number;
  octetdeltacount_secondaryMetric: number;
  octetdeltacount_baselineAverage: number;
  octetdeltacount_peakObserved: number;
  octetdeltacount_standardDeviation: number;
  octetdeltacount_rawHexSample: string;
  octetdeltacount_metadataTag: Record<string, string>;
  protocolidentifier_primaryMetric: number;
  protocolidentifier_secondaryMetric: number;
  protocolidentifier_baselineAverage: number;
  protocolidentifier_peakObserved: number;
  protocolidentifier_standardDeviation: number;
  protocolidentifier_rawHexSample: string;
  protocolidentifier_metadataTag: Record<string, string>;
  tcpcontrolbits_primaryMetric: number;
  tcpcontrolbits_secondaryMetric: number;
  tcpcontrolbits_baselineAverage: number;
  tcpcontrolbits_peakObserved: number;
  tcpcontrolbits_standardDeviation: number;
  tcpcontrolbits_rawHexSample: string;
  tcpcontrolbits_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type NetflowV9IpfixFilterV38 = Partial<NetflowV9IpfixRecordV38> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface NetflowV9IpfixRecordV39 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  sourceipv4address_primaryMetric: number;
  sourceipv4address_secondaryMetric: number;
  sourceipv4address_baselineAverage: number;
  sourceipv4address_peakObserved: number;
  sourceipv4address_standardDeviation: number;
  sourceipv4address_rawHexSample: string;
  sourceipv4address_metadataTag: Record<string, string>;
  destinationipv4address_primaryMetric: number;
  destinationipv4address_secondaryMetric: number;
  destinationipv4address_baselineAverage: number;
  destinationipv4address_peakObserved: number;
  destinationipv4address_standardDeviation: number;
  destinationipv4address_rawHexSample: string;
  destinationipv4address_metadataTag: Record<string, string>;
  packetdeltacount_primaryMetric: number;
  packetdeltacount_secondaryMetric: number;
  packetdeltacount_baselineAverage: number;
  packetdeltacount_peakObserved: number;
  packetdeltacount_standardDeviation: number;
  packetdeltacount_rawHexSample: string;
  packetdeltacount_metadataTag: Record<string, string>;
  octetdeltacount_primaryMetric: number;
  octetdeltacount_secondaryMetric: number;
  octetdeltacount_baselineAverage: number;
  octetdeltacount_peakObserved: number;
  octetdeltacount_standardDeviation: number;
  octetdeltacount_rawHexSample: string;
  octetdeltacount_metadataTag: Record<string, string>;
  protocolidentifier_primaryMetric: number;
  protocolidentifier_secondaryMetric: number;
  protocolidentifier_baselineAverage: number;
  protocolidentifier_peakObserved: number;
  protocolidentifier_standardDeviation: number;
  protocolidentifier_rawHexSample: string;
  protocolidentifier_metadataTag: Record<string, string>;
  tcpcontrolbits_primaryMetric: number;
  tcpcontrolbits_secondaryMetric: number;
  tcpcontrolbits_baselineAverage: number;
  tcpcontrolbits_peakObserved: number;
  tcpcontrolbits_standardDeviation: number;
  tcpcontrolbits_rawHexSample: string;
  tcpcontrolbits_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type NetflowV9IpfixFilterV39 = Partial<NetflowV9IpfixRecordV39> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface NetflowV9IpfixRecordV40 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  sourceipv4address_primaryMetric: number;
  sourceipv4address_secondaryMetric: number;
  sourceipv4address_baselineAverage: number;
  sourceipv4address_peakObserved: number;
  sourceipv4address_standardDeviation: number;
  sourceipv4address_rawHexSample: string;
  sourceipv4address_metadataTag: Record<string, string>;
  destinationipv4address_primaryMetric: number;
  destinationipv4address_secondaryMetric: number;
  destinationipv4address_baselineAverage: number;
  destinationipv4address_peakObserved: number;
  destinationipv4address_standardDeviation: number;
  destinationipv4address_rawHexSample: string;
  destinationipv4address_metadataTag: Record<string, string>;
  packetdeltacount_primaryMetric: number;
  packetdeltacount_secondaryMetric: number;
  packetdeltacount_baselineAverage: number;
  packetdeltacount_peakObserved: number;
  packetdeltacount_standardDeviation: number;
  packetdeltacount_rawHexSample: string;
  packetdeltacount_metadataTag: Record<string, string>;
  octetdeltacount_primaryMetric: number;
  octetdeltacount_secondaryMetric: number;
  octetdeltacount_baselineAverage: number;
  octetdeltacount_peakObserved: number;
  octetdeltacount_standardDeviation: number;
  octetdeltacount_rawHexSample: string;
  octetdeltacount_metadataTag: Record<string, string>;
  protocolidentifier_primaryMetric: number;
  protocolidentifier_secondaryMetric: number;
  protocolidentifier_baselineAverage: number;
  protocolidentifier_peakObserved: number;
  protocolidentifier_standardDeviation: number;
  protocolidentifier_rawHexSample: string;
  protocolidentifier_metadataTag: Record<string, string>;
  tcpcontrolbits_primaryMetric: number;
  tcpcontrolbits_secondaryMetric: number;
  tcpcontrolbits_baselineAverage: number;
  tcpcontrolbits_peakObserved: number;
  tcpcontrolbits_standardDeviation: number;
  tcpcontrolbits_rawHexSample: string;
  tcpcontrolbits_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type NetflowV9IpfixFilterV40 = Partial<NetflowV9IpfixRecordV40> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};
