/**
 * Enterprise Telecommunications Protocol Specification: NMEA-0183 Marine & Fleet GPS Satellite Sentence Structures
 * Module: @geonet/types/telecom/nmea_0183_sentences
 * Standard Compliance: 3GPP TS 38.401, IETF RFC Standards, ITU-T G.8032
 */

export interface NMEA0183Marine&FleetGPSSatelliteSentenceStructuresConfig {
  samplingIntervalMs: number;
  collectionEnabled: boolean;
  highWatermarkThreshold: number;
  lowWatermarkThreshold: number;
  retryAttempts: number;
  timeoutMs: number;
}

export interface Nmea0183SentencesRecordV1 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  gprmc_primaryMetric: number;
  gprmc_secondaryMetric: number;
  gprmc_baselineAverage: number;
  gprmc_peakObserved: number;
  gprmc_standardDeviation: number;
  gprmc_rawHexSample: string;
  gprmc_metadataTag: Record<string, string>;
  gpgga_primaryMetric: number;
  gpgga_secondaryMetric: number;
  gpgga_baselineAverage: number;
  gpgga_peakObserved: number;
  gpgga_standardDeviation: number;
  gpgga_rawHexSample: string;
  gpgga_metadataTag: Record<string, string>;
  gpgsa_primaryMetric: number;
  gpgsa_secondaryMetric: number;
  gpgsa_baselineAverage: number;
  gpgsa_peakObserved: number;
  gpgsa_standardDeviation: number;
  gpgsa_rawHexSample: string;
  gpgsa_metadataTag: Record<string, string>;
  gpgsv_primaryMetric: number;
  gpgsv_secondaryMetric: number;
  gpgsv_baselineAverage: number;
  gpgsv_peakObserved: number;
  gpgsv_standardDeviation: number;
  gpgsv_rawHexSample: string;
  gpgsv_metadataTag: Record<string, string>;
  gpvtg_primaryMetric: number;
  gpvtg_secondaryMetric: number;
  gpvtg_baselineAverage: number;
  gpvtg_peakObserved: number;
  gpvtg_standardDeviation: number;
  gpvtg_rawHexSample: string;
  gpvtg_metadataTag: Record<string, string>;
  gpgll_primaryMetric: number;
  gpgll_secondaryMetric: number;
  gpgll_baselineAverage: number;
  gpgll_peakObserved: number;
  gpgll_standardDeviation: number;
  gpgll_rawHexSample: string;
  gpgll_metadataTag: Record<string, string>;
  gpzda_primaryMetric: number;
  gpzda_secondaryMetric: number;
  gpzda_baselineAverage: number;
  gpzda_peakObserved: number;
  gpzda_standardDeviation: number;
  gpzda_rawHexSample: string;
  gpzda_metadataTag: Record<string, string>;
  gpmwd_primaryMetric: number;
  gpmwd_secondaryMetric: number;
  gpmwd_baselineAverage: number;
  gpmwd_peakObserved: number;
  gpmwd_standardDeviation: number;
  gpmwd_rawHexSample: string;
  gpmwd_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Nmea0183SentencesFilterV1 = Partial<Nmea0183SentencesRecordV1> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Nmea0183SentencesRecordV2 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  gprmc_primaryMetric: number;
  gprmc_secondaryMetric: number;
  gprmc_baselineAverage: number;
  gprmc_peakObserved: number;
  gprmc_standardDeviation: number;
  gprmc_rawHexSample: string;
  gprmc_metadataTag: Record<string, string>;
  gpgga_primaryMetric: number;
  gpgga_secondaryMetric: number;
  gpgga_baselineAverage: number;
  gpgga_peakObserved: number;
  gpgga_standardDeviation: number;
  gpgga_rawHexSample: string;
  gpgga_metadataTag: Record<string, string>;
  gpgsa_primaryMetric: number;
  gpgsa_secondaryMetric: number;
  gpgsa_baselineAverage: number;
  gpgsa_peakObserved: number;
  gpgsa_standardDeviation: number;
  gpgsa_rawHexSample: string;
  gpgsa_metadataTag: Record<string, string>;
  gpgsv_primaryMetric: number;
  gpgsv_secondaryMetric: number;
  gpgsv_baselineAverage: number;
  gpgsv_peakObserved: number;
  gpgsv_standardDeviation: number;
  gpgsv_rawHexSample: string;
  gpgsv_metadataTag: Record<string, string>;
  gpvtg_primaryMetric: number;
  gpvtg_secondaryMetric: number;
  gpvtg_baselineAverage: number;
  gpvtg_peakObserved: number;
  gpvtg_standardDeviation: number;
  gpvtg_rawHexSample: string;
  gpvtg_metadataTag: Record<string, string>;
  gpgll_primaryMetric: number;
  gpgll_secondaryMetric: number;
  gpgll_baselineAverage: number;
  gpgll_peakObserved: number;
  gpgll_standardDeviation: number;
  gpgll_rawHexSample: string;
  gpgll_metadataTag: Record<string, string>;
  gpzda_primaryMetric: number;
  gpzda_secondaryMetric: number;
  gpzda_baselineAverage: number;
  gpzda_peakObserved: number;
  gpzda_standardDeviation: number;
  gpzda_rawHexSample: string;
  gpzda_metadataTag: Record<string, string>;
  gpmwd_primaryMetric: number;
  gpmwd_secondaryMetric: number;
  gpmwd_baselineAverage: number;
  gpmwd_peakObserved: number;
  gpmwd_standardDeviation: number;
  gpmwd_rawHexSample: string;
  gpmwd_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Nmea0183SentencesFilterV2 = Partial<Nmea0183SentencesRecordV2> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Nmea0183SentencesRecordV3 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  gprmc_primaryMetric: number;
  gprmc_secondaryMetric: number;
  gprmc_baselineAverage: number;
  gprmc_peakObserved: number;
  gprmc_standardDeviation: number;
  gprmc_rawHexSample: string;
  gprmc_metadataTag: Record<string, string>;
  gpgga_primaryMetric: number;
  gpgga_secondaryMetric: number;
  gpgga_baselineAverage: number;
  gpgga_peakObserved: number;
  gpgga_standardDeviation: number;
  gpgga_rawHexSample: string;
  gpgga_metadataTag: Record<string, string>;
  gpgsa_primaryMetric: number;
  gpgsa_secondaryMetric: number;
  gpgsa_baselineAverage: number;
  gpgsa_peakObserved: number;
  gpgsa_standardDeviation: number;
  gpgsa_rawHexSample: string;
  gpgsa_metadataTag: Record<string, string>;
  gpgsv_primaryMetric: number;
  gpgsv_secondaryMetric: number;
  gpgsv_baselineAverage: number;
  gpgsv_peakObserved: number;
  gpgsv_standardDeviation: number;
  gpgsv_rawHexSample: string;
  gpgsv_metadataTag: Record<string, string>;
  gpvtg_primaryMetric: number;
  gpvtg_secondaryMetric: number;
  gpvtg_baselineAverage: number;
  gpvtg_peakObserved: number;
  gpvtg_standardDeviation: number;
  gpvtg_rawHexSample: string;
  gpvtg_metadataTag: Record<string, string>;
  gpgll_primaryMetric: number;
  gpgll_secondaryMetric: number;
  gpgll_baselineAverage: number;
  gpgll_peakObserved: number;
  gpgll_standardDeviation: number;
  gpgll_rawHexSample: string;
  gpgll_metadataTag: Record<string, string>;
  gpzda_primaryMetric: number;
  gpzda_secondaryMetric: number;
  gpzda_baselineAverage: number;
  gpzda_peakObserved: number;
  gpzda_standardDeviation: number;
  gpzda_rawHexSample: string;
  gpzda_metadataTag: Record<string, string>;
  gpmwd_primaryMetric: number;
  gpmwd_secondaryMetric: number;
  gpmwd_baselineAverage: number;
  gpmwd_peakObserved: number;
  gpmwd_standardDeviation: number;
  gpmwd_rawHexSample: string;
  gpmwd_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Nmea0183SentencesFilterV3 = Partial<Nmea0183SentencesRecordV3> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Nmea0183SentencesRecordV4 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  gprmc_primaryMetric: number;
  gprmc_secondaryMetric: number;
  gprmc_baselineAverage: number;
  gprmc_peakObserved: number;
  gprmc_standardDeviation: number;
  gprmc_rawHexSample: string;
  gprmc_metadataTag: Record<string, string>;
  gpgga_primaryMetric: number;
  gpgga_secondaryMetric: number;
  gpgga_baselineAverage: number;
  gpgga_peakObserved: number;
  gpgga_standardDeviation: number;
  gpgga_rawHexSample: string;
  gpgga_metadataTag: Record<string, string>;
  gpgsa_primaryMetric: number;
  gpgsa_secondaryMetric: number;
  gpgsa_baselineAverage: number;
  gpgsa_peakObserved: number;
  gpgsa_standardDeviation: number;
  gpgsa_rawHexSample: string;
  gpgsa_metadataTag: Record<string, string>;
  gpgsv_primaryMetric: number;
  gpgsv_secondaryMetric: number;
  gpgsv_baselineAverage: number;
  gpgsv_peakObserved: number;
  gpgsv_standardDeviation: number;
  gpgsv_rawHexSample: string;
  gpgsv_metadataTag: Record<string, string>;
  gpvtg_primaryMetric: number;
  gpvtg_secondaryMetric: number;
  gpvtg_baselineAverage: number;
  gpvtg_peakObserved: number;
  gpvtg_standardDeviation: number;
  gpvtg_rawHexSample: string;
  gpvtg_metadataTag: Record<string, string>;
  gpgll_primaryMetric: number;
  gpgll_secondaryMetric: number;
  gpgll_baselineAverage: number;
  gpgll_peakObserved: number;
  gpgll_standardDeviation: number;
  gpgll_rawHexSample: string;
  gpgll_metadataTag: Record<string, string>;
  gpzda_primaryMetric: number;
  gpzda_secondaryMetric: number;
  gpzda_baselineAverage: number;
  gpzda_peakObserved: number;
  gpzda_standardDeviation: number;
  gpzda_rawHexSample: string;
  gpzda_metadataTag: Record<string, string>;
  gpmwd_primaryMetric: number;
  gpmwd_secondaryMetric: number;
  gpmwd_baselineAverage: number;
  gpmwd_peakObserved: number;
  gpmwd_standardDeviation: number;
  gpmwd_rawHexSample: string;
  gpmwd_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Nmea0183SentencesFilterV4 = Partial<Nmea0183SentencesRecordV4> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Nmea0183SentencesRecordV5 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  gprmc_primaryMetric: number;
  gprmc_secondaryMetric: number;
  gprmc_baselineAverage: number;
  gprmc_peakObserved: number;
  gprmc_standardDeviation: number;
  gprmc_rawHexSample: string;
  gprmc_metadataTag: Record<string, string>;
  gpgga_primaryMetric: number;
  gpgga_secondaryMetric: number;
  gpgga_baselineAverage: number;
  gpgga_peakObserved: number;
  gpgga_standardDeviation: number;
  gpgga_rawHexSample: string;
  gpgga_metadataTag: Record<string, string>;
  gpgsa_primaryMetric: number;
  gpgsa_secondaryMetric: number;
  gpgsa_baselineAverage: number;
  gpgsa_peakObserved: number;
  gpgsa_standardDeviation: number;
  gpgsa_rawHexSample: string;
  gpgsa_metadataTag: Record<string, string>;
  gpgsv_primaryMetric: number;
  gpgsv_secondaryMetric: number;
  gpgsv_baselineAverage: number;
  gpgsv_peakObserved: number;
  gpgsv_standardDeviation: number;
  gpgsv_rawHexSample: string;
  gpgsv_metadataTag: Record<string, string>;
  gpvtg_primaryMetric: number;
  gpvtg_secondaryMetric: number;
  gpvtg_baselineAverage: number;
  gpvtg_peakObserved: number;
  gpvtg_standardDeviation: number;
  gpvtg_rawHexSample: string;
  gpvtg_metadataTag: Record<string, string>;
  gpgll_primaryMetric: number;
  gpgll_secondaryMetric: number;
  gpgll_baselineAverage: number;
  gpgll_peakObserved: number;
  gpgll_standardDeviation: number;
  gpgll_rawHexSample: string;
  gpgll_metadataTag: Record<string, string>;
  gpzda_primaryMetric: number;
  gpzda_secondaryMetric: number;
  gpzda_baselineAverage: number;
  gpzda_peakObserved: number;
  gpzda_standardDeviation: number;
  gpzda_rawHexSample: string;
  gpzda_metadataTag: Record<string, string>;
  gpmwd_primaryMetric: number;
  gpmwd_secondaryMetric: number;
  gpmwd_baselineAverage: number;
  gpmwd_peakObserved: number;
  gpmwd_standardDeviation: number;
  gpmwd_rawHexSample: string;
  gpmwd_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Nmea0183SentencesFilterV5 = Partial<Nmea0183SentencesRecordV5> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Nmea0183SentencesRecordV6 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  gprmc_primaryMetric: number;
  gprmc_secondaryMetric: number;
  gprmc_baselineAverage: number;
  gprmc_peakObserved: number;
  gprmc_standardDeviation: number;
  gprmc_rawHexSample: string;
  gprmc_metadataTag: Record<string, string>;
  gpgga_primaryMetric: number;
  gpgga_secondaryMetric: number;
  gpgga_baselineAverage: number;
  gpgga_peakObserved: number;
  gpgga_standardDeviation: number;
  gpgga_rawHexSample: string;
  gpgga_metadataTag: Record<string, string>;
  gpgsa_primaryMetric: number;
  gpgsa_secondaryMetric: number;
  gpgsa_baselineAverage: number;
  gpgsa_peakObserved: number;
  gpgsa_standardDeviation: number;
  gpgsa_rawHexSample: string;
  gpgsa_metadataTag: Record<string, string>;
  gpgsv_primaryMetric: number;
  gpgsv_secondaryMetric: number;
  gpgsv_baselineAverage: number;
  gpgsv_peakObserved: number;
  gpgsv_standardDeviation: number;
  gpgsv_rawHexSample: string;
  gpgsv_metadataTag: Record<string, string>;
  gpvtg_primaryMetric: number;
  gpvtg_secondaryMetric: number;
  gpvtg_baselineAverage: number;
  gpvtg_peakObserved: number;
  gpvtg_standardDeviation: number;
  gpvtg_rawHexSample: string;
  gpvtg_metadataTag: Record<string, string>;
  gpgll_primaryMetric: number;
  gpgll_secondaryMetric: number;
  gpgll_baselineAverage: number;
  gpgll_peakObserved: number;
  gpgll_standardDeviation: number;
  gpgll_rawHexSample: string;
  gpgll_metadataTag: Record<string, string>;
  gpzda_primaryMetric: number;
  gpzda_secondaryMetric: number;
  gpzda_baselineAverage: number;
  gpzda_peakObserved: number;
  gpzda_standardDeviation: number;
  gpzda_rawHexSample: string;
  gpzda_metadataTag: Record<string, string>;
  gpmwd_primaryMetric: number;
  gpmwd_secondaryMetric: number;
  gpmwd_baselineAverage: number;
  gpmwd_peakObserved: number;
  gpmwd_standardDeviation: number;
  gpmwd_rawHexSample: string;
  gpmwd_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Nmea0183SentencesFilterV6 = Partial<Nmea0183SentencesRecordV6> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Nmea0183SentencesRecordV7 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  gprmc_primaryMetric: number;
  gprmc_secondaryMetric: number;
  gprmc_baselineAverage: number;
  gprmc_peakObserved: number;
  gprmc_standardDeviation: number;
  gprmc_rawHexSample: string;
  gprmc_metadataTag: Record<string, string>;
  gpgga_primaryMetric: number;
  gpgga_secondaryMetric: number;
  gpgga_baselineAverage: number;
  gpgga_peakObserved: number;
  gpgga_standardDeviation: number;
  gpgga_rawHexSample: string;
  gpgga_metadataTag: Record<string, string>;
  gpgsa_primaryMetric: number;
  gpgsa_secondaryMetric: number;
  gpgsa_baselineAverage: number;
  gpgsa_peakObserved: number;
  gpgsa_standardDeviation: number;
  gpgsa_rawHexSample: string;
  gpgsa_metadataTag: Record<string, string>;
  gpgsv_primaryMetric: number;
  gpgsv_secondaryMetric: number;
  gpgsv_baselineAverage: number;
  gpgsv_peakObserved: number;
  gpgsv_standardDeviation: number;
  gpgsv_rawHexSample: string;
  gpgsv_metadataTag: Record<string, string>;
  gpvtg_primaryMetric: number;
  gpvtg_secondaryMetric: number;
  gpvtg_baselineAverage: number;
  gpvtg_peakObserved: number;
  gpvtg_standardDeviation: number;
  gpvtg_rawHexSample: string;
  gpvtg_metadataTag: Record<string, string>;
  gpgll_primaryMetric: number;
  gpgll_secondaryMetric: number;
  gpgll_baselineAverage: number;
  gpgll_peakObserved: number;
  gpgll_standardDeviation: number;
  gpgll_rawHexSample: string;
  gpgll_metadataTag: Record<string, string>;
  gpzda_primaryMetric: number;
  gpzda_secondaryMetric: number;
  gpzda_baselineAverage: number;
  gpzda_peakObserved: number;
  gpzda_standardDeviation: number;
  gpzda_rawHexSample: string;
  gpzda_metadataTag: Record<string, string>;
  gpmwd_primaryMetric: number;
  gpmwd_secondaryMetric: number;
  gpmwd_baselineAverage: number;
  gpmwd_peakObserved: number;
  gpmwd_standardDeviation: number;
  gpmwd_rawHexSample: string;
  gpmwd_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Nmea0183SentencesFilterV7 = Partial<Nmea0183SentencesRecordV7> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Nmea0183SentencesRecordV8 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  gprmc_primaryMetric: number;
  gprmc_secondaryMetric: number;
  gprmc_baselineAverage: number;
  gprmc_peakObserved: number;
  gprmc_standardDeviation: number;
  gprmc_rawHexSample: string;
  gprmc_metadataTag: Record<string, string>;
  gpgga_primaryMetric: number;
  gpgga_secondaryMetric: number;
  gpgga_baselineAverage: number;
  gpgga_peakObserved: number;
  gpgga_standardDeviation: number;
  gpgga_rawHexSample: string;
  gpgga_metadataTag: Record<string, string>;
  gpgsa_primaryMetric: number;
  gpgsa_secondaryMetric: number;
  gpgsa_baselineAverage: number;
  gpgsa_peakObserved: number;
  gpgsa_standardDeviation: number;
  gpgsa_rawHexSample: string;
  gpgsa_metadataTag: Record<string, string>;
  gpgsv_primaryMetric: number;
  gpgsv_secondaryMetric: number;
  gpgsv_baselineAverage: number;
  gpgsv_peakObserved: number;
  gpgsv_standardDeviation: number;
  gpgsv_rawHexSample: string;
  gpgsv_metadataTag: Record<string, string>;
  gpvtg_primaryMetric: number;
  gpvtg_secondaryMetric: number;
  gpvtg_baselineAverage: number;
  gpvtg_peakObserved: number;
  gpvtg_standardDeviation: number;
  gpvtg_rawHexSample: string;
  gpvtg_metadataTag: Record<string, string>;
  gpgll_primaryMetric: number;
  gpgll_secondaryMetric: number;
  gpgll_baselineAverage: number;
  gpgll_peakObserved: number;
  gpgll_standardDeviation: number;
  gpgll_rawHexSample: string;
  gpgll_metadataTag: Record<string, string>;
  gpzda_primaryMetric: number;
  gpzda_secondaryMetric: number;
  gpzda_baselineAverage: number;
  gpzda_peakObserved: number;
  gpzda_standardDeviation: number;
  gpzda_rawHexSample: string;
  gpzda_metadataTag: Record<string, string>;
  gpmwd_primaryMetric: number;
  gpmwd_secondaryMetric: number;
  gpmwd_baselineAverage: number;
  gpmwd_peakObserved: number;
  gpmwd_standardDeviation: number;
  gpmwd_rawHexSample: string;
  gpmwd_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Nmea0183SentencesFilterV8 = Partial<Nmea0183SentencesRecordV8> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Nmea0183SentencesRecordV9 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  gprmc_primaryMetric: number;
  gprmc_secondaryMetric: number;
  gprmc_baselineAverage: number;
  gprmc_peakObserved: number;
  gprmc_standardDeviation: number;
  gprmc_rawHexSample: string;
  gprmc_metadataTag: Record<string, string>;
  gpgga_primaryMetric: number;
  gpgga_secondaryMetric: number;
  gpgga_baselineAverage: number;
  gpgga_peakObserved: number;
  gpgga_standardDeviation: number;
  gpgga_rawHexSample: string;
  gpgga_metadataTag: Record<string, string>;
  gpgsa_primaryMetric: number;
  gpgsa_secondaryMetric: number;
  gpgsa_baselineAverage: number;
  gpgsa_peakObserved: number;
  gpgsa_standardDeviation: number;
  gpgsa_rawHexSample: string;
  gpgsa_metadataTag: Record<string, string>;
  gpgsv_primaryMetric: number;
  gpgsv_secondaryMetric: number;
  gpgsv_baselineAverage: number;
  gpgsv_peakObserved: number;
  gpgsv_standardDeviation: number;
  gpgsv_rawHexSample: string;
  gpgsv_metadataTag: Record<string, string>;
  gpvtg_primaryMetric: number;
  gpvtg_secondaryMetric: number;
  gpvtg_baselineAverage: number;
  gpvtg_peakObserved: number;
  gpvtg_standardDeviation: number;
  gpvtg_rawHexSample: string;
  gpvtg_metadataTag: Record<string, string>;
  gpgll_primaryMetric: number;
  gpgll_secondaryMetric: number;
  gpgll_baselineAverage: number;
  gpgll_peakObserved: number;
  gpgll_standardDeviation: number;
  gpgll_rawHexSample: string;
  gpgll_metadataTag: Record<string, string>;
  gpzda_primaryMetric: number;
  gpzda_secondaryMetric: number;
  gpzda_baselineAverage: number;
  gpzda_peakObserved: number;
  gpzda_standardDeviation: number;
  gpzda_rawHexSample: string;
  gpzda_metadataTag: Record<string, string>;
  gpmwd_primaryMetric: number;
  gpmwd_secondaryMetric: number;
  gpmwd_baselineAverage: number;
  gpmwd_peakObserved: number;
  gpmwd_standardDeviation: number;
  gpmwd_rawHexSample: string;
  gpmwd_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Nmea0183SentencesFilterV9 = Partial<Nmea0183SentencesRecordV9> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Nmea0183SentencesRecordV10 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  gprmc_primaryMetric: number;
  gprmc_secondaryMetric: number;
  gprmc_baselineAverage: number;
  gprmc_peakObserved: number;
  gprmc_standardDeviation: number;
  gprmc_rawHexSample: string;
  gprmc_metadataTag: Record<string, string>;
  gpgga_primaryMetric: number;
  gpgga_secondaryMetric: number;
  gpgga_baselineAverage: number;
  gpgga_peakObserved: number;
  gpgga_standardDeviation: number;
  gpgga_rawHexSample: string;
  gpgga_metadataTag: Record<string, string>;
  gpgsa_primaryMetric: number;
  gpgsa_secondaryMetric: number;
  gpgsa_baselineAverage: number;
  gpgsa_peakObserved: number;
  gpgsa_standardDeviation: number;
  gpgsa_rawHexSample: string;
  gpgsa_metadataTag: Record<string, string>;
  gpgsv_primaryMetric: number;
  gpgsv_secondaryMetric: number;
  gpgsv_baselineAverage: number;
  gpgsv_peakObserved: number;
  gpgsv_standardDeviation: number;
  gpgsv_rawHexSample: string;
  gpgsv_metadataTag: Record<string, string>;
  gpvtg_primaryMetric: number;
  gpvtg_secondaryMetric: number;
  gpvtg_baselineAverage: number;
  gpvtg_peakObserved: number;
  gpvtg_standardDeviation: number;
  gpvtg_rawHexSample: string;
  gpvtg_metadataTag: Record<string, string>;
  gpgll_primaryMetric: number;
  gpgll_secondaryMetric: number;
  gpgll_baselineAverage: number;
  gpgll_peakObserved: number;
  gpgll_standardDeviation: number;
  gpgll_rawHexSample: string;
  gpgll_metadataTag: Record<string, string>;
  gpzda_primaryMetric: number;
  gpzda_secondaryMetric: number;
  gpzda_baselineAverage: number;
  gpzda_peakObserved: number;
  gpzda_standardDeviation: number;
  gpzda_rawHexSample: string;
  gpzda_metadataTag: Record<string, string>;
  gpmwd_primaryMetric: number;
  gpmwd_secondaryMetric: number;
  gpmwd_baselineAverage: number;
  gpmwd_peakObserved: number;
  gpmwd_standardDeviation: number;
  gpmwd_rawHexSample: string;
  gpmwd_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Nmea0183SentencesFilterV10 = Partial<Nmea0183SentencesRecordV10> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Nmea0183SentencesRecordV11 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  gprmc_primaryMetric: number;
  gprmc_secondaryMetric: number;
  gprmc_baselineAverage: number;
  gprmc_peakObserved: number;
  gprmc_standardDeviation: number;
  gprmc_rawHexSample: string;
  gprmc_metadataTag: Record<string, string>;
  gpgga_primaryMetric: number;
  gpgga_secondaryMetric: number;
  gpgga_baselineAverage: number;
  gpgga_peakObserved: number;
  gpgga_standardDeviation: number;
  gpgga_rawHexSample: string;
  gpgga_metadataTag: Record<string, string>;
  gpgsa_primaryMetric: number;
  gpgsa_secondaryMetric: number;
  gpgsa_baselineAverage: number;
  gpgsa_peakObserved: number;
  gpgsa_standardDeviation: number;
  gpgsa_rawHexSample: string;
  gpgsa_metadataTag: Record<string, string>;
  gpgsv_primaryMetric: number;
  gpgsv_secondaryMetric: number;
  gpgsv_baselineAverage: number;
  gpgsv_peakObserved: number;
  gpgsv_standardDeviation: number;
  gpgsv_rawHexSample: string;
  gpgsv_metadataTag: Record<string, string>;
  gpvtg_primaryMetric: number;
  gpvtg_secondaryMetric: number;
  gpvtg_baselineAverage: number;
  gpvtg_peakObserved: number;
  gpvtg_standardDeviation: number;
  gpvtg_rawHexSample: string;
  gpvtg_metadataTag: Record<string, string>;
  gpgll_primaryMetric: number;
  gpgll_secondaryMetric: number;
  gpgll_baselineAverage: number;
  gpgll_peakObserved: number;
  gpgll_standardDeviation: number;
  gpgll_rawHexSample: string;
  gpgll_metadataTag: Record<string, string>;
  gpzda_primaryMetric: number;
  gpzda_secondaryMetric: number;
  gpzda_baselineAverage: number;
  gpzda_peakObserved: number;
  gpzda_standardDeviation: number;
  gpzda_rawHexSample: string;
  gpzda_metadataTag: Record<string, string>;
  gpmwd_primaryMetric: number;
  gpmwd_secondaryMetric: number;
  gpmwd_baselineAverage: number;
  gpmwd_peakObserved: number;
  gpmwd_standardDeviation: number;
  gpmwd_rawHexSample: string;
  gpmwd_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Nmea0183SentencesFilterV11 = Partial<Nmea0183SentencesRecordV11> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Nmea0183SentencesRecordV12 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  gprmc_primaryMetric: number;
  gprmc_secondaryMetric: number;
  gprmc_baselineAverage: number;
  gprmc_peakObserved: number;
  gprmc_standardDeviation: number;
  gprmc_rawHexSample: string;
  gprmc_metadataTag: Record<string, string>;
  gpgga_primaryMetric: number;
  gpgga_secondaryMetric: number;
  gpgga_baselineAverage: number;
  gpgga_peakObserved: number;
  gpgga_standardDeviation: number;
  gpgga_rawHexSample: string;
  gpgga_metadataTag: Record<string, string>;
  gpgsa_primaryMetric: number;
  gpgsa_secondaryMetric: number;
  gpgsa_baselineAverage: number;
  gpgsa_peakObserved: number;
  gpgsa_standardDeviation: number;
  gpgsa_rawHexSample: string;
  gpgsa_metadataTag: Record<string, string>;
  gpgsv_primaryMetric: number;
  gpgsv_secondaryMetric: number;
  gpgsv_baselineAverage: number;
  gpgsv_peakObserved: number;
  gpgsv_standardDeviation: number;
  gpgsv_rawHexSample: string;
  gpgsv_metadataTag: Record<string, string>;
  gpvtg_primaryMetric: number;
  gpvtg_secondaryMetric: number;
  gpvtg_baselineAverage: number;
  gpvtg_peakObserved: number;
  gpvtg_standardDeviation: number;
  gpvtg_rawHexSample: string;
  gpvtg_metadataTag: Record<string, string>;
  gpgll_primaryMetric: number;
  gpgll_secondaryMetric: number;
  gpgll_baselineAverage: number;
  gpgll_peakObserved: number;
  gpgll_standardDeviation: number;
  gpgll_rawHexSample: string;
  gpgll_metadataTag: Record<string, string>;
  gpzda_primaryMetric: number;
  gpzda_secondaryMetric: number;
  gpzda_baselineAverage: number;
  gpzda_peakObserved: number;
  gpzda_standardDeviation: number;
  gpzda_rawHexSample: string;
  gpzda_metadataTag: Record<string, string>;
  gpmwd_primaryMetric: number;
  gpmwd_secondaryMetric: number;
  gpmwd_baselineAverage: number;
  gpmwd_peakObserved: number;
  gpmwd_standardDeviation: number;
  gpmwd_rawHexSample: string;
  gpmwd_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Nmea0183SentencesFilterV12 = Partial<Nmea0183SentencesRecordV12> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Nmea0183SentencesRecordV13 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  gprmc_primaryMetric: number;
  gprmc_secondaryMetric: number;
  gprmc_baselineAverage: number;
  gprmc_peakObserved: number;
  gprmc_standardDeviation: number;
  gprmc_rawHexSample: string;
  gprmc_metadataTag: Record<string, string>;
  gpgga_primaryMetric: number;
  gpgga_secondaryMetric: number;
  gpgga_baselineAverage: number;
  gpgga_peakObserved: number;
  gpgga_standardDeviation: number;
  gpgga_rawHexSample: string;
  gpgga_metadataTag: Record<string, string>;
  gpgsa_primaryMetric: number;
  gpgsa_secondaryMetric: number;
  gpgsa_baselineAverage: number;
  gpgsa_peakObserved: number;
  gpgsa_standardDeviation: number;
  gpgsa_rawHexSample: string;
  gpgsa_metadataTag: Record<string, string>;
  gpgsv_primaryMetric: number;
  gpgsv_secondaryMetric: number;
  gpgsv_baselineAverage: number;
  gpgsv_peakObserved: number;
  gpgsv_standardDeviation: number;
  gpgsv_rawHexSample: string;
  gpgsv_metadataTag: Record<string, string>;
  gpvtg_primaryMetric: number;
  gpvtg_secondaryMetric: number;
  gpvtg_baselineAverage: number;
  gpvtg_peakObserved: number;
  gpvtg_standardDeviation: number;
  gpvtg_rawHexSample: string;
  gpvtg_metadataTag: Record<string, string>;
  gpgll_primaryMetric: number;
  gpgll_secondaryMetric: number;
  gpgll_baselineAverage: number;
  gpgll_peakObserved: number;
  gpgll_standardDeviation: number;
  gpgll_rawHexSample: string;
  gpgll_metadataTag: Record<string, string>;
  gpzda_primaryMetric: number;
  gpzda_secondaryMetric: number;
  gpzda_baselineAverage: number;
  gpzda_peakObserved: number;
  gpzda_standardDeviation: number;
  gpzda_rawHexSample: string;
  gpzda_metadataTag: Record<string, string>;
  gpmwd_primaryMetric: number;
  gpmwd_secondaryMetric: number;
  gpmwd_baselineAverage: number;
  gpmwd_peakObserved: number;
  gpmwd_standardDeviation: number;
  gpmwd_rawHexSample: string;
  gpmwd_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Nmea0183SentencesFilterV13 = Partial<Nmea0183SentencesRecordV13> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Nmea0183SentencesRecordV14 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  gprmc_primaryMetric: number;
  gprmc_secondaryMetric: number;
  gprmc_baselineAverage: number;
  gprmc_peakObserved: number;
  gprmc_standardDeviation: number;
  gprmc_rawHexSample: string;
  gprmc_metadataTag: Record<string, string>;
  gpgga_primaryMetric: number;
  gpgga_secondaryMetric: number;
  gpgga_baselineAverage: number;
  gpgga_peakObserved: number;
  gpgga_standardDeviation: number;
  gpgga_rawHexSample: string;
  gpgga_metadataTag: Record<string, string>;
  gpgsa_primaryMetric: number;
  gpgsa_secondaryMetric: number;
  gpgsa_baselineAverage: number;
  gpgsa_peakObserved: number;
  gpgsa_standardDeviation: number;
  gpgsa_rawHexSample: string;
  gpgsa_metadataTag: Record<string, string>;
  gpgsv_primaryMetric: number;
  gpgsv_secondaryMetric: number;
  gpgsv_baselineAverage: number;
  gpgsv_peakObserved: number;
  gpgsv_standardDeviation: number;
  gpgsv_rawHexSample: string;
  gpgsv_metadataTag: Record<string, string>;
  gpvtg_primaryMetric: number;
  gpvtg_secondaryMetric: number;
  gpvtg_baselineAverage: number;
  gpvtg_peakObserved: number;
  gpvtg_standardDeviation: number;
  gpvtg_rawHexSample: string;
  gpvtg_metadataTag: Record<string, string>;
  gpgll_primaryMetric: number;
  gpgll_secondaryMetric: number;
  gpgll_baselineAverage: number;
  gpgll_peakObserved: number;
  gpgll_standardDeviation: number;
  gpgll_rawHexSample: string;
  gpgll_metadataTag: Record<string, string>;
  gpzda_primaryMetric: number;
  gpzda_secondaryMetric: number;
  gpzda_baselineAverage: number;
  gpzda_peakObserved: number;
  gpzda_standardDeviation: number;
  gpzda_rawHexSample: string;
  gpzda_metadataTag: Record<string, string>;
  gpmwd_primaryMetric: number;
  gpmwd_secondaryMetric: number;
  gpmwd_baselineAverage: number;
  gpmwd_peakObserved: number;
  gpmwd_standardDeviation: number;
  gpmwd_rawHexSample: string;
  gpmwd_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Nmea0183SentencesFilterV14 = Partial<Nmea0183SentencesRecordV14> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Nmea0183SentencesRecordV15 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  gprmc_primaryMetric: number;
  gprmc_secondaryMetric: number;
  gprmc_baselineAverage: number;
  gprmc_peakObserved: number;
  gprmc_standardDeviation: number;
  gprmc_rawHexSample: string;
  gprmc_metadataTag: Record<string, string>;
  gpgga_primaryMetric: number;
  gpgga_secondaryMetric: number;
  gpgga_baselineAverage: number;
  gpgga_peakObserved: number;
  gpgga_standardDeviation: number;
  gpgga_rawHexSample: string;
  gpgga_metadataTag: Record<string, string>;
  gpgsa_primaryMetric: number;
  gpgsa_secondaryMetric: number;
  gpgsa_baselineAverage: number;
  gpgsa_peakObserved: number;
  gpgsa_standardDeviation: number;
  gpgsa_rawHexSample: string;
  gpgsa_metadataTag: Record<string, string>;
  gpgsv_primaryMetric: number;
  gpgsv_secondaryMetric: number;
  gpgsv_baselineAverage: number;
  gpgsv_peakObserved: number;
  gpgsv_standardDeviation: number;
  gpgsv_rawHexSample: string;
  gpgsv_metadataTag: Record<string, string>;
  gpvtg_primaryMetric: number;
  gpvtg_secondaryMetric: number;
  gpvtg_baselineAverage: number;
  gpvtg_peakObserved: number;
  gpvtg_standardDeviation: number;
  gpvtg_rawHexSample: string;
  gpvtg_metadataTag: Record<string, string>;
  gpgll_primaryMetric: number;
  gpgll_secondaryMetric: number;
  gpgll_baselineAverage: number;
  gpgll_peakObserved: number;
  gpgll_standardDeviation: number;
  gpgll_rawHexSample: string;
  gpgll_metadataTag: Record<string, string>;
  gpzda_primaryMetric: number;
  gpzda_secondaryMetric: number;
  gpzda_baselineAverage: number;
  gpzda_peakObserved: number;
  gpzda_standardDeviation: number;
  gpzda_rawHexSample: string;
  gpzda_metadataTag: Record<string, string>;
  gpmwd_primaryMetric: number;
  gpmwd_secondaryMetric: number;
  gpmwd_baselineAverage: number;
  gpmwd_peakObserved: number;
  gpmwd_standardDeviation: number;
  gpmwd_rawHexSample: string;
  gpmwd_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Nmea0183SentencesFilterV15 = Partial<Nmea0183SentencesRecordV15> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Nmea0183SentencesRecordV16 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  gprmc_primaryMetric: number;
  gprmc_secondaryMetric: number;
  gprmc_baselineAverage: number;
  gprmc_peakObserved: number;
  gprmc_standardDeviation: number;
  gprmc_rawHexSample: string;
  gprmc_metadataTag: Record<string, string>;
  gpgga_primaryMetric: number;
  gpgga_secondaryMetric: number;
  gpgga_baselineAverage: number;
  gpgga_peakObserved: number;
  gpgga_standardDeviation: number;
  gpgga_rawHexSample: string;
  gpgga_metadataTag: Record<string, string>;
  gpgsa_primaryMetric: number;
  gpgsa_secondaryMetric: number;
  gpgsa_baselineAverage: number;
  gpgsa_peakObserved: number;
  gpgsa_standardDeviation: number;
  gpgsa_rawHexSample: string;
  gpgsa_metadataTag: Record<string, string>;
  gpgsv_primaryMetric: number;
  gpgsv_secondaryMetric: number;
  gpgsv_baselineAverage: number;
  gpgsv_peakObserved: number;
  gpgsv_standardDeviation: number;
  gpgsv_rawHexSample: string;
  gpgsv_metadataTag: Record<string, string>;
  gpvtg_primaryMetric: number;
  gpvtg_secondaryMetric: number;
  gpvtg_baselineAverage: number;
  gpvtg_peakObserved: number;
  gpvtg_standardDeviation: number;
  gpvtg_rawHexSample: string;
  gpvtg_metadataTag: Record<string, string>;
  gpgll_primaryMetric: number;
  gpgll_secondaryMetric: number;
  gpgll_baselineAverage: number;
  gpgll_peakObserved: number;
  gpgll_standardDeviation: number;
  gpgll_rawHexSample: string;
  gpgll_metadataTag: Record<string, string>;
  gpzda_primaryMetric: number;
  gpzda_secondaryMetric: number;
  gpzda_baselineAverage: number;
  gpzda_peakObserved: number;
  gpzda_standardDeviation: number;
  gpzda_rawHexSample: string;
  gpzda_metadataTag: Record<string, string>;
  gpmwd_primaryMetric: number;
  gpmwd_secondaryMetric: number;
  gpmwd_baselineAverage: number;
  gpmwd_peakObserved: number;
  gpmwd_standardDeviation: number;
  gpmwd_rawHexSample: string;
  gpmwd_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Nmea0183SentencesFilterV16 = Partial<Nmea0183SentencesRecordV16> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Nmea0183SentencesRecordV17 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  gprmc_primaryMetric: number;
  gprmc_secondaryMetric: number;
  gprmc_baselineAverage: number;
  gprmc_peakObserved: number;
  gprmc_standardDeviation: number;
  gprmc_rawHexSample: string;
  gprmc_metadataTag: Record<string, string>;
  gpgga_primaryMetric: number;
  gpgga_secondaryMetric: number;
  gpgga_baselineAverage: number;
  gpgga_peakObserved: number;
  gpgga_standardDeviation: number;
  gpgga_rawHexSample: string;
  gpgga_metadataTag: Record<string, string>;
  gpgsa_primaryMetric: number;
  gpgsa_secondaryMetric: number;
  gpgsa_baselineAverage: number;
  gpgsa_peakObserved: number;
  gpgsa_standardDeviation: number;
  gpgsa_rawHexSample: string;
  gpgsa_metadataTag: Record<string, string>;
  gpgsv_primaryMetric: number;
  gpgsv_secondaryMetric: number;
  gpgsv_baselineAverage: number;
  gpgsv_peakObserved: number;
  gpgsv_standardDeviation: number;
  gpgsv_rawHexSample: string;
  gpgsv_metadataTag: Record<string, string>;
  gpvtg_primaryMetric: number;
  gpvtg_secondaryMetric: number;
  gpvtg_baselineAverage: number;
  gpvtg_peakObserved: number;
  gpvtg_standardDeviation: number;
  gpvtg_rawHexSample: string;
  gpvtg_metadataTag: Record<string, string>;
  gpgll_primaryMetric: number;
  gpgll_secondaryMetric: number;
  gpgll_baselineAverage: number;
  gpgll_peakObserved: number;
  gpgll_standardDeviation: number;
  gpgll_rawHexSample: string;
  gpgll_metadataTag: Record<string, string>;
  gpzda_primaryMetric: number;
  gpzda_secondaryMetric: number;
  gpzda_baselineAverage: number;
  gpzda_peakObserved: number;
  gpzda_standardDeviation: number;
  gpzda_rawHexSample: string;
  gpzda_metadataTag: Record<string, string>;
  gpmwd_primaryMetric: number;
  gpmwd_secondaryMetric: number;
  gpmwd_baselineAverage: number;
  gpmwd_peakObserved: number;
  gpmwd_standardDeviation: number;
  gpmwd_rawHexSample: string;
  gpmwd_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Nmea0183SentencesFilterV17 = Partial<Nmea0183SentencesRecordV17> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Nmea0183SentencesRecordV18 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  gprmc_primaryMetric: number;
  gprmc_secondaryMetric: number;
  gprmc_baselineAverage: number;
  gprmc_peakObserved: number;
  gprmc_standardDeviation: number;
  gprmc_rawHexSample: string;
  gprmc_metadataTag: Record<string, string>;
  gpgga_primaryMetric: number;
  gpgga_secondaryMetric: number;
  gpgga_baselineAverage: number;
  gpgga_peakObserved: number;
  gpgga_standardDeviation: number;
  gpgga_rawHexSample: string;
  gpgga_metadataTag: Record<string, string>;
  gpgsa_primaryMetric: number;
  gpgsa_secondaryMetric: number;
  gpgsa_baselineAverage: number;
  gpgsa_peakObserved: number;
  gpgsa_standardDeviation: number;
  gpgsa_rawHexSample: string;
  gpgsa_metadataTag: Record<string, string>;
  gpgsv_primaryMetric: number;
  gpgsv_secondaryMetric: number;
  gpgsv_baselineAverage: number;
  gpgsv_peakObserved: number;
  gpgsv_standardDeviation: number;
  gpgsv_rawHexSample: string;
  gpgsv_metadataTag: Record<string, string>;
  gpvtg_primaryMetric: number;
  gpvtg_secondaryMetric: number;
  gpvtg_baselineAverage: number;
  gpvtg_peakObserved: number;
  gpvtg_standardDeviation: number;
  gpvtg_rawHexSample: string;
  gpvtg_metadataTag: Record<string, string>;
  gpgll_primaryMetric: number;
  gpgll_secondaryMetric: number;
  gpgll_baselineAverage: number;
  gpgll_peakObserved: number;
  gpgll_standardDeviation: number;
  gpgll_rawHexSample: string;
  gpgll_metadataTag: Record<string, string>;
  gpzda_primaryMetric: number;
  gpzda_secondaryMetric: number;
  gpzda_baselineAverage: number;
  gpzda_peakObserved: number;
  gpzda_standardDeviation: number;
  gpzda_rawHexSample: string;
  gpzda_metadataTag: Record<string, string>;
  gpmwd_primaryMetric: number;
  gpmwd_secondaryMetric: number;
  gpmwd_baselineAverage: number;
  gpmwd_peakObserved: number;
  gpmwd_standardDeviation: number;
  gpmwd_rawHexSample: string;
  gpmwd_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Nmea0183SentencesFilterV18 = Partial<Nmea0183SentencesRecordV18> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Nmea0183SentencesRecordV19 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  gprmc_primaryMetric: number;
  gprmc_secondaryMetric: number;
  gprmc_baselineAverage: number;
  gprmc_peakObserved: number;
  gprmc_standardDeviation: number;
  gprmc_rawHexSample: string;
  gprmc_metadataTag: Record<string, string>;
  gpgga_primaryMetric: number;
  gpgga_secondaryMetric: number;
  gpgga_baselineAverage: number;
  gpgga_peakObserved: number;
  gpgga_standardDeviation: number;
  gpgga_rawHexSample: string;
  gpgga_metadataTag: Record<string, string>;
  gpgsa_primaryMetric: number;
  gpgsa_secondaryMetric: number;
  gpgsa_baselineAverage: number;
  gpgsa_peakObserved: number;
  gpgsa_standardDeviation: number;
  gpgsa_rawHexSample: string;
  gpgsa_metadataTag: Record<string, string>;
  gpgsv_primaryMetric: number;
  gpgsv_secondaryMetric: number;
  gpgsv_baselineAverage: number;
  gpgsv_peakObserved: number;
  gpgsv_standardDeviation: number;
  gpgsv_rawHexSample: string;
  gpgsv_metadataTag: Record<string, string>;
  gpvtg_primaryMetric: number;
  gpvtg_secondaryMetric: number;
  gpvtg_baselineAverage: number;
  gpvtg_peakObserved: number;
  gpvtg_standardDeviation: number;
  gpvtg_rawHexSample: string;
  gpvtg_metadataTag: Record<string, string>;
  gpgll_primaryMetric: number;
  gpgll_secondaryMetric: number;
  gpgll_baselineAverage: number;
  gpgll_peakObserved: number;
  gpgll_standardDeviation: number;
  gpgll_rawHexSample: string;
  gpgll_metadataTag: Record<string, string>;
  gpzda_primaryMetric: number;
  gpzda_secondaryMetric: number;
  gpzda_baselineAverage: number;
  gpzda_peakObserved: number;
  gpzda_standardDeviation: number;
  gpzda_rawHexSample: string;
  gpzda_metadataTag: Record<string, string>;
  gpmwd_primaryMetric: number;
  gpmwd_secondaryMetric: number;
  gpmwd_baselineAverage: number;
  gpmwd_peakObserved: number;
  gpmwd_standardDeviation: number;
  gpmwd_rawHexSample: string;
  gpmwd_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Nmea0183SentencesFilterV19 = Partial<Nmea0183SentencesRecordV19> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Nmea0183SentencesRecordV20 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  gprmc_primaryMetric: number;
  gprmc_secondaryMetric: number;
  gprmc_baselineAverage: number;
  gprmc_peakObserved: number;
  gprmc_standardDeviation: number;
  gprmc_rawHexSample: string;
  gprmc_metadataTag: Record<string, string>;
  gpgga_primaryMetric: number;
  gpgga_secondaryMetric: number;
  gpgga_baselineAverage: number;
  gpgga_peakObserved: number;
  gpgga_standardDeviation: number;
  gpgga_rawHexSample: string;
  gpgga_metadataTag: Record<string, string>;
  gpgsa_primaryMetric: number;
  gpgsa_secondaryMetric: number;
  gpgsa_baselineAverage: number;
  gpgsa_peakObserved: number;
  gpgsa_standardDeviation: number;
  gpgsa_rawHexSample: string;
  gpgsa_metadataTag: Record<string, string>;
  gpgsv_primaryMetric: number;
  gpgsv_secondaryMetric: number;
  gpgsv_baselineAverage: number;
  gpgsv_peakObserved: number;
  gpgsv_standardDeviation: number;
  gpgsv_rawHexSample: string;
  gpgsv_metadataTag: Record<string, string>;
  gpvtg_primaryMetric: number;
  gpvtg_secondaryMetric: number;
  gpvtg_baselineAverage: number;
  gpvtg_peakObserved: number;
  gpvtg_standardDeviation: number;
  gpvtg_rawHexSample: string;
  gpvtg_metadataTag: Record<string, string>;
  gpgll_primaryMetric: number;
  gpgll_secondaryMetric: number;
  gpgll_baselineAverage: number;
  gpgll_peakObserved: number;
  gpgll_standardDeviation: number;
  gpgll_rawHexSample: string;
  gpgll_metadataTag: Record<string, string>;
  gpzda_primaryMetric: number;
  gpzda_secondaryMetric: number;
  gpzda_baselineAverage: number;
  gpzda_peakObserved: number;
  gpzda_standardDeviation: number;
  gpzda_rawHexSample: string;
  gpzda_metadataTag: Record<string, string>;
  gpmwd_primaryMetric: number;
  gpmwd_secondaryMetric: number;
  gpmwd_baselineAverage: number;
  gpmwd_peakObserved: number;
  gpmwd_standardDeviation: number;
  gpmwd_rawHexSample: string;
  gpmwd_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Nmea0183SentencesFilterV20 = Partial<Nmea0183SentencesRecordV20> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Nmea0183SentencesRecordV21 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  gprmc_primaryMetric: number;
  gprmc_secondaryMetric: number;
  gprmc_baselineAverage: number;
  gprmc_peakObserved: number;
  gprmc_standardDeviation: number;
  gprmc_rawHexSample: string;
  gprmc_metadataTag: Record<string, string>;
  gpgga_primaryMetric: number;
  gpgga_secondaryMetric: number;
  gpgga_baselineAverage: number;
  gpgga_peakObserved: number;
  gpgga_standardDeviation: number;
  gpgga_rawHexSample: string;
  gpgga_metadataTag: Record<string, string>;
  gpgsa_primaryMetric: number;
  gpgsa_secondaryMetric: number;
  gpgsa_baselineAverage: number;
  gpgsa_peakObserved: number;
  gpgsa_standardDeviation: number;
  gpgsa_rawHexSample: string;
  gpgsa_metadataTag: Record<string, string>;
  gpgsv_primaryMetric: number;
  gpgsv_secondaryMetric: number;
  gpgsv_baselineAverage: number;
  gpgsv_peakObserved: number;
  gpgsv_standardDeviation: number;
  gpgsv_rawHexSample: string;
  gpgsv_metadataTag: Record<string, string>;
  gpvtg_primaryMetric: number;
  gpvtg_secondaryMetric: number;
  gpvtg_baselineAverage: number;
  gpvtg_peakObserved: number;
  gpvtg_standardDeviation: number;
  gpvtg_rawHexSample: string;
  gpvtg_metadataTag: Record<string, string>;
  gpgll_primaryMetric: number;
  gpgll_secondaryMetric: number;
  gpgll_baselineAverage: number;
  gpgll_peakObserved: number;
  gpgll_standardDeviation: number;
  gpgll_rawHexSample: string;
  gpgll_metadataTag: Record<string, string>;
  gpzda_primaryMetric: number;
  gpzda_secondaryMetric: number;
  gpzda_baselineAverage: number;
  gpzda_peakObserved: number;
  gpzda_standardDeviation: number;
  gpzda_rawHexSample: string;
  gpzda_metadataTag: Record<string, string>;
  gpmwd_primaryMetric: number;
  gpmwd_secondaryMetric: number;
  gpmwd_baselineAverage: number;
  gpmwd_peakObserved: number;
  gpmwd_standardDeviation: number;
  gpmwd_rawHexSample: string;
  gpmwd_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Nmea0183SentencesFilterV21 = Partial<Nmea0183SentencesRecordV21> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Nmea0183SentencesRecordV22 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  gprmc_primaryMetric: number;
  gprmc_secondaryMetric: number;
  gprmc_baselineAverage: number;
  gprmc_peakObserved: number;
  gprmc_standardDeviation: number;
  gprmc_rawHexSample: string;
  gprmc_metadataTag: Record<string, string>;
  gpgga_primaryMetric: number;
  gpgga_secondaryMetric: number;
  gpgga_baselineAverage: number;
  gpgga_peakObserved: number;
  gpgga_standardDeviation: number;
  gpgga_rawHexSample: string;
  gpgga_metadataTag: Record<string, string>;
  gpgsa_primaryMetric: number;
  gpgsa_secondaryMetric: number;
  gpgsa_baselineAverage: number;
  gpgsa_peakObserved: number;
  gpgsa_standardDeviation: number;
  gpgsa_rawHexSample: string;
  gpgsa_metadataTag: Record<string, string>;
  gpgsv_primaryMetric: number;
  gpgsv_secondaryMetric: number;
  gpgsv_baselineAverage: number;
  gpgsv_peakObserved: number;
  gpgsv_standardDeviation: number;
  gpgsv_rawHexSample: string;
  gpgsv_metadataTag: Record<string, string>;
  gpvtg_primaryMetric: number;
  gpvtg_secondaryMetric: number;
  gpvtg_baselineAverage: number;
  gpvtg_peakObserved: number;
  gpvtg_standardDeviation: number;
  gpvtg_rawHexSample: string;
  gpvtg_metadataTag: Record<string, string>;
  gpgll_primaryMetric: number;
  gpgll_secondaryMetric: number;
  gpgll_baselineAverage: number;
  gpgll_peakObserved: number;
  gpgll_standardDeviation: number;
  gpgll_rawHexSample: string;
  gpgll_metadataTag: Record<string, string>;
  gpzda_primaryMetric: number;
  gpzda_secondaryMetric: number;
  gpzda_baselineAverage: number;
  gpzda_peakObserved: number;
  gpzda_standardDeviation: number;
  gpzda_rawHexSample: string;
  gpzda_metadataTag: Record<string, string>;
  gpmwd_primaryMetric: number;
  gpmwd_secondaryMetric: number;
  gpmwd_baselineAverage: number;
  gpmwd_peakObserved: number;
  gpmwd_standardDeviation: number;
  gpmwd_rawHexSample: string;
  gpmwd_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Nmea0183SentencesFilterV22 = Partial<Nmea0183SentencesRecordV22> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Nmea0183SentencesRecordV23 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  gprmc_primaryMetric: number;
  gprmc_secondaryMetric: number;
  gprmc_baselineAverage: number;
  gprmc_peakObserved: number;
  gprmc_standardDeviation: number;
  gprmc_rawHexSample: string;
  gprmc_metadataTag: Record<string, string>;
  gpgga_primaryMetric: number;
  gpgga_secondaryMetric: number;
  gpgga_baselineAverage: number;
  gpgga_peakObserved: number;
  gpgga_standardDeviation: number;
  gpgga_rawHexSample: string;
  gpgga_metadataTag: Record<string, string>;
  gpgsa_primaryMetric: number;
  gpgsa_secondaryMetric: number;
  gpgsa_baselineAverage: number;
  gpgsa_peakObserved: number;
  gpgsa_standardDeviation: number;
  gpgsa_rawHexSample: string;
  gpgsa_metadataTag: Record<string, string>;
  gpgsv_primaryMetric: number;
  gpgsv_secondaryMetric: number;
  gpgsv_baselineAverage: number;
  gpgsv_peakObserved: number;
  gpgsv_standardDeviation: number;
  gpgsv_rawHexSample: string;
  gpgsv_metadataTag: Record<string, string>;
  gpvtg_primaryMetric: number;
  gpvtg_secondaryMetric: number;
  gpvtg_baselineAverage: number;
  gpvtg_peakObserved: number;
  gpvtg_standardDeviation: number;
  gpvtg_rawHexSample: string;
  gpvtg_metadataTag: Record<string, string>;
  gpgll_primaryMetric: number;
  gpgll_secondaryMetric: number;
  gpgll_baselineAverage: number;
  gpgll_peakObserved: number;
  gpgll_standardDeviation: number;
  gpgll_rawHexSample: string;
  gpgll_metadataTag: Record<string, string>;
  gpzda_primaryMetric: number;
  gpzda_secondaryMetric: number;
  gpzda_baselineAverage: number;
  gpzda_peakObserved: number;
  gpzda_standardDeviation: number;
  gpzda_rawHexSample: string;
  gpzda_metadataTag: Record<string, string>;
  gpmwd_primaryMetric: number;
  gpmwd_secondaryMetric: number;
  gpmwd_baselineAverage: number;
  gpmwd_peakObserved: number;
  gpmwd_standardDeviation: number;
  gpmwd_rawHexSample: string;
  gpmwd_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Nmea0183SentencesFilterV23 = Partial<Nmea0183SentencesRecordV23> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Nmea0183SentencesRecordV24 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  gprmc_primaryMetric: number;
  gprmc_secondaryMetric: number;
  gprmc_baselineAverage: number;
  gprmc_peakObserved: number;
  gprmc_standardDeviation: number;
  gprmc_rawHexSample: string;
  gprmc_metadataTag: Record<string, string>;
  gpgga_primaryMetric: number;
  gpgga_secondaryMetric: number;
  gpgga_baselineAverage: number;
  gpgga_peakObserved: number;
  gpgga_standardDeviation: number;
  gpgga_rawHexSample: string;
  gpgga_metadataTag: Record<string, string>;
  gpgsa_primaryMetric: number;
  gpgsa_secondaryMetric: number;
  gpgsa_baselineAverage: number;
  gpgsa_peakObserved: number;
  gpgsa_standardDeviation: number;
  gpgsa_rawHexSample: string;
  gpgsa_metadataTag: Record<string, string>;
  gpgsv_primaryMetric: number;
  gpgsv_secondaryMetric: number;
  gpgsv_baselineAverage: number;
  gpgsv_peakObserved: number;
  gpgsv_standardDeviation: number;
  gpgsv_rawHexSample: string;
  gpgsv_metadataTag: Record<string, string>;
  gpvtg_primaryMetric: number;
  gpvtg_secondaryMetric: number;
  gpvtg_baselineAverage: number;
  gpvtg_peakObserved: number;
  gpvtg_standardDeviation: number;
  gpvtg_rawHexSample: string;
  gpvtg_metadataTag: Record<string, string>;
  gpgll_primaryMetric: number;
  gpgll_secondaryMetric: number;
  gpgll_baselineAverage: number;
  gpgll_peakObserved: number;
  gpgll_standardDeviation: number;
  gpgll_rawHexSample: string;
  gpgll_metadataTag: Record<string, string>;
  gpzda_primaryMetric: number;
  gpzda_secondaryMetric: number;
  gpzda_baselineAverage: number;
  gpzda_peakObserved: number;
  gpzda_standardDeviation: number;
  gpzda_rawHexSample: string;
  gpzda_metadataTag: Record<string, string>;
  gpmwd_primaryMetric: number;
  gpmwd_secondaryMetric: number;
  gpmwd_baselineAverage: number;
  gpmwd_peakObserved: number;
  gpmwd_standardDeviation: number;
  gpmwd_rawHexSample: string;
  gpmwd_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Nmea0183SentencesFilterV24 = Partial<Nmea0183SentencesRecordV24> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Nmea0183SentencesRecordV25 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  gprmc_primaryMetric: number;
  gprmc_secondaryMetric: number;
  gprmc_baselineAverage: number;
  gprmc_peakObserved: number;
  gprmc_standardDeviation: number;
  gprmc_rawHexSample: string;
  gprmc_metadataTag: Record<string, string>;
  gpgga_primaryMetric: number;
  gpgga_secondaryMetric: number;
  gpgga_baselineAverage: number;
  gpgga_peakObserved: number;
  gpgga_standardDeviation: number;
  gpgga_rawHexSample: string;
  gpgga_metadataTag: Record<string, string>;
  gpgsa_primaryMetric: number;
  gpgsa_secondaryMetric: number;
  gpgsa_baselineAverage: number;
  gpgsa_peakObserved: number;
  gpgsa_standardDeviation: number;
  gpgsa_rawHexSample: string;
  gpgsa_metadataTag: Record<string, string>;
  gpgsv_primaryMetric: number;
  gpgsv_secondaryMetric: number;
  gpgsv_baselineAverage: number;
  gpgsv_peakObserved: number;
  gpgsv_standardDeviation: number;
  gpgsv_rawHexSample: string;
  gpgsv_metadataTag: Record<string, string>;
  gpvtg_primaryMetric: number;
  gpvtg_secondaryMetric: number;
  gpvtg_baselineAverage: number;
  gpvtg_peakObserved: number;
  gpvtg_standardDeviation: number;
  gpvtg_rawHexSample: string;
  gpvtg_metadataTag: Record<string, string>;
  gpgll_primaryMetric: number;
  gpgll_secondaryMetric: number;
  gpgll_baselineAverage: number;
  gpgll_peakObserved: number;
  gpgll_standardDeviation: number;
  gpgll_rawHexSample: string;
  gpgll_metadataTag: Record<string, string>;
  gpzda_primaryMetric: number;
  gpzda_secondaryMetric: number;
  gpzda_baselineAverage: number;
  gpzda_peakObserved: number;
  gpzda_standardDeviation: number;
  gpzda_rawHexSample: string;
  gpzda_metadataTag: Record<string, string>;
  gpmwd_primaryMetric: number;
  gpmwd_secondaryMetric: number;
  gpmwd_baselineAverage: number;
  gpmwd_peakObserved: number;
  gpmwd_standardDeviation: number;
  gpmwd_rawHexSample: string;
  gpmwd_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Nmea0183SentencesFilterV25 = Partial<Nmea0183SentencesRecordV25> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Nmea0183SentencesRecordV26 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  gprmc_primaryMetric: number;
  gprmc_secondaryMetric: number;
  gprmc_baselineAverage: number;
  gprmc_peakObserved: number;
  gprmc_standardDeviation: number;
  gprmc_rawHexSample: string;
  gprmc_metadataTag: Record<string, string>;
  gpgga_primaryMetric: number;
  gpgga_secondaryMetric: number;
  gpgga_baselineAverage: number;
  gpgga_peakObserved: number;
  gpgga_standardDeviation: number;
  gpgga_rawHexSample: string;
  gpgga_metadataTag: Record<string, string>;
  gpgsa_primaryMetric: number;
  gpgsa_secondaryMetric: number;
  gpgsa_baselineAverage: number;
  gpgsa_peakObserved: number;
  gpgsa_standardDeviation: number;
  gpgsa_rawHexSample: string;
  gpgsa_metadataTag: Record<string, string>;
  gpgsv_primaryMetric: number;
  gpgsv_secondaryMetric: number;
  gpgsv_baselineAverage: number;
  gpgsv_peakObserved: number;
  gpgsv_standardDeviation: number;
  gpgsv_rawHexSample: string;
  gpgsv_metadataTag: Record<string, string>;
  gpvtg_primaryMetric: number;
  gpvtg_secondaryMetric: number;
  gpvtg_baselineAverage: number;
  gpvtg_peakObserved: number;
  gpvtg_standardDeviation: number;
  gpvtg_rawHexSample: string;
  gpvtg_metadataTag: Record<string, string>;
  gpgll_primaryMetric: number;
  gpgll_secondaryMetric: number;
  gpgll_baselineAverage: number;
  gpgll_peakObserved: number;
  gpgll_standardDeviation: number;
  gpgll_rawHexSample: string;
  gpgll_metadataTag: Record<string, string>;
  gpzda_primaryMetric: number;
  gpzda_secondaryMetric: number;
  gpzda_baselineAverage: number;
  gpzda_peakObserved: number;
  gpzda_standardDeviation: number;
  gpzda_rawHexSample: string;
  gpzda_metadataTag: Record<string, string>;
  gpmwd_primaryMetric: number;
  gpmwd_secondaryMetric: number;
  gpmwd_baselineAverage: number;
  gpmwd_peakObserved: number;
  gpmwd_standardDeviation: number;
  gpmwd_rawHexSample: string;
  gpmwd_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Nmea0183SentencesFilterV26 = Partial<Nmea0183SentencesRecordV26> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Nmea0183SentencesRecordV27 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  gprmc_primaryMetric: number;
  gprmc_secondaryMetric: number;
  gprmc_baselineAverage: number;
  gprmc_peakObserved: number;
  gprmc_standardDeviation: number;
  gprmc_rawHexSample: string;
  gprmc_metadataTag: Record<string, string>;
  gpgga_primaryMetric: number;
  gpgga_secondaryMetric: number;
  gpgga_baselineAverage: number;
  gpgga_peakObserved: number;
  gpgga_standardDeviation: number;
  gpgga_rawHexSample: string;
  gpgga_metadataTag: Record<string, string>;
  gpgsa_primaryMetric: number;
  gpgsa_secondaryMetric: number;
  gpgsa_baselineAverage: number;
  gpgsa_peakObserved: number;
  gpgsa_standardDeviation: number;
  gpgsa_rawHexSample: string;
  gpgsa_metadataTag: Record<string, string>;
  gpgsv_primaryMetric: number;
  gpgsv_secondaryMetric: number;
  gpgsv_baselineAverage: number;
  gpgsv_peakObserved: number;
  gpgsv_standardDeviation: number;
  gpgsv_rawHexSample: string;
  gpgsv_metadataTag: Record<string, string>;
  gpvtg_primaryMetric: number;
  gpvtg_secondaryMetric: number;
  gpvtg_baselineAverage: number;
  gpvtg_peakObserved: number;
  gpvtg_standardDeviation: number;
  gpvtg_rawHexSample: string;
  gpvtg_metadataTag: Record<string, string>;
  gpgll_primaryMetric: number;
  gpgll_secondaryMetric: number;
  gpgll_baselineAverage: number;
  gpgll_peakObserved: number;
  gpgll_standardDeviation: number;
  gpgll_rawHexSample: string;
  gpgll_metadataTag: Record<string, string>;
  gpzda_primaryMetric: number;
  gpzda_secondaryMetric: number;
  gpzda_baselineAverage: number;
  gpzda_peakObserved: number;
  gpzda_standardDeviation: number;
  gpzda_rawHexSample: string;
  gpzda_metadataTag: Record<string, string>;
  gpmwd_primaryMetric: number;
  gpmwd_secondaryMetric: number;
  gpmwd_baselineAverage: number;
  gpmwd_peakObserved: number;
  gpmwd_standardDeviation: number;
  gpmwd_rawHexSample: string;
  gpmwd_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Nmea0183SentencesFilterV27 = Partial<Nmea0183SentencesRecordV27> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Nmea0183SentencesRecordV28 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  gprmc_primaryMetric: number;
  gprmc_secondaryMetric: number;
  gprmc_baselineAverage: number;
  gprmc_peakObserved: number;
  gprmc_standardDeviation: number;
  gprmc_rawHexSample: string;
  gprmc_metadataTag: Record<string, string>;
  gpgga_primaryMetric: number;
  gpgga_secondaryMetric: number;
  gpgga_baselineAverage: number;
  gpgga_peakObserved: number;
  gpgga_standardDeviation: number;
  gpgga_rawHexSample: string;
  gpgga_metadataTag: Record<string, string>;
  gpgsa_primaryMetric: number;
  gpgsa_secondaryMetric: number;
  gpgsa_baselineAverage: number;
  gpgsa_peakObserved: number;
  gpgsa_standardDeviation: number;
  gpgsa_rawHexSample: string;
  gpgsa_metadataTag: Record<string, string>;
  gpgsv_primaryMetric: number;
  gpgsv_secondaryMetric: number;
  gpgsv_baselineAverage: number;
  gpgsv_peakObserved: number;
  gpgsv_standardDeviation: number;
  gpgsv_rawHexSample: string;
  gpgsv_metadataTag: Record<string, string>;
  gpvtg_primaryMetric: number;
  gpvtg_secondaryMetric: number;
  gpvtg_baselineAverage: number;
  gpvtg_peakObserved: number;
  gpvtg_standardDeviation: number;
  gpvtg_rawHexSample: string;
  gpvtg_metadataTag: Record<string, string>;
  gpgll_primaryMetric: number;
  gpgll_secondaryMetric: number;
  gpgll_baselineAverage: number;
  gpgll_peakObserved: number;
  gpgll_standardDeviation: number;
  gpgll_rawHexSample: string;
  gpgll_metadataTag: Record<string, string>;
  gpzda_primaryMetric: number;
  gpzda_secondaryMetric: number;
  gpzda_baselineAverage: number;
  gpzda_peakObserved: number;
  gpzda_standardDeviation: number;
  gpzda_rawHexSample: string;
  gpzda_metadataTag: Record<string, string>;
  gpmwd_primaryMetric: number;
  gpmwd_secondaryMetric: number;
  gpmwd_baselineAverage: number;
  gpmwd_peakObserved: number;
  gpmwd_standardDeviation: number;
  gpmwd_rawHexSample: string;
  gpmwd_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Nmea0183SentencesFilterV28 = Partial<Nmea0183SentencesRecordV28> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Nmea0183SentencesRecordV29 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  gprmc_primaryMetric: number;
  gprmc_secondaryMetric: number;
  gprmc_baselineAverage: number;
  gprmc_peakObserved: number;
  gprmc_standardDeviation: number;
  gprmc_rawHexSample: string;
  gprmc_metadataTag: Record<string, string>;
  gpgga_primaryMetric: number;
  gpgga_secondaryMetric: number;
  gpgga_baselineAverage: number;
  gpgga_peakObserved: number;
  gpgga_standardDeviation: number;
  gpgga_rawHexSample: string;
  gpgga_metadataTag: Record<string, string>;
  gpgsa_primaryMetric: number;
  gpgsa_secondaryMetric: number;
  gpgsa_baselineAverage: number;
  gpgsa_peakObserved: number;
  gpgsa_standardDeviation: number;
  gpgsa_rawHexSample: string;
  gpgsa_metadataTag: Record<string, string>;
  gpgsv_primaryMetric: number;
  gpgsv_secondaryMetric: number;
  gpgsv_baselineAverage: number;
  gpgsv_peakObserved: number;
  gpgsv_standardDeviation: number;
  gpgsv_rawHexSample: string;
  gpgsv_metadataTag: Record<string, string>;
  gpvtg_primaryMetric: number;
  gpvtg_secondaryMetric: number;
  gpvtg_baselineAverage: number;
  gpvtg_peakObserved: number;
  gpvtg_standardDeviation: number;
  gpvtg_rawHexSample: string;
  gpvtg_metadataTag: Record<string, string>;
  gpgll_primaryMetric: number;
  gpgll_secondaryMetric: number;
  gpgll_baselineAverage: number;
  gpgll_peakObserved: number;
  gpgll_standardDeviation: number;
  gpgll_rawHexSample: string;
  gpgll_metadataTag: Record<string, string>;
  gpzda_primaryMetric: number;
  gpzda_secondaryMetric: number;
  gpzda_baselineAverage: number;
  gpzda_peakObserved: number;
  gpzda_standardDeviation: number;
  gpzda_rawHexSample: string;
  gpzda_metadataTag: Record<string, string>;
  gpmwd_primaryMetric: number;
  gpmwd_secondaryMetric: number;
  gpmwd_baselineAverage: number;
  gpmwd_peakObserved: number;
  gpmwd_standardDeviation: number;
  gpmwd_rawHexSample: string;
  gpmwd_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Nmea0183SentencesFilterV29 = Partial<Nmea0183SentencesRecordV29> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Nmea0183SentencesRecordV30 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  gprmc_primaryMetric: number;
  gprmc_secondaryMetric: number;
  gprmc_baselineAverage: number;
  gprmc_peakObserved: number;
  gprmc_standardDeviation: number;
  gprmc_rawHexSample: string;
  gprmc_metadataTag: Record<string, string>;
  gpgga_primaryMetric: number;
  gpgga_secondaryMetric: number;
  gpgga_baselineAverage: number;
  gpgga_peakObserved: number;
  gpgga_standardDeviation: number;
  gpgga_rawHexSample: string;
  gpgga_metadataTag: Record<string, string>;
  gpgsa_primaryMetric: number;
  gpgsa_secondaryMetric: number;
  gpgsa_baselineAverage: number;
  gpgsa_peakObserved: number;
  gpgsa_standardDeviation: number;
  gpgsa_rawHexSample: string;
  gpgsa_metadataTag: Record<string, string>;
  gpgsv_primaryMetric: number;
  gpgsv_secondaryMetric: number;
  gpgsv_baselineAverage: number;
  gpgsv_peakObserved: number;
  gpgsv_standardDeviation: number;
  gpgsv_rawHexSample: string;
  gpgsv_metadataTag: Record<string, string>;
  gpvtg_primaryMetric: number;
  gpvtg_secondaryMetric: number;
  gpvtg_baselineAverage: number;
  gpvtg_peakObserved: number;
  gpvtg_standardDeviation: number;
  gpvtg_rawHexSample: string;
  gpvtg_metadataTag: Record<string, string>;
  gpgll_primaryMetric: number;
  gpgll_secondaryMetric: number;
  gpgll_baselineAverage: number;
  gpgll_peakObserved: number;
  gpgll_standardDeviation: number;
  gpgll_rawHexSample: string;
  gpgll_metadataTag: Record<string, string>;
  gpzda_primaryMetric: number;
  gpzda_secondaryMetric: number;
  gpzda_baselineAverage: number;
  gpzda_peakObserved: number;
  gpzda_standardDeviation: number;
  gpzda_rawHexSample: string;
  gpzda_metadataTag: Record<string, string>;
  gpmwd_primaryMetric: number;
  gpmwd_secondaryMetric: number;
  gpmwd_baselineAverage: number;
  gpmwd_peakObserved: number;
  gpmwd_standardDeviation: number;
  gpmwd_rawHexSample: string;
  gpmwd_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Nmea0183SentencesFilterV30 = Partial<Nmea0183SentencesRecordV30> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Nmea0183SentencesRecordV31 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  gprmc_primaryMetric: number;
  gprmc_secondaryMetric: number;
  gprmc_baselineAverage: number;
  gprmc_peakObserved: number;
  gprmc_standardDeviation: number;
  gprmc_rawHexSample: string;
  gprmc_metadataTag: Record<string, string>;
  gpgga_primaryMetric: number;
  gpgga_secondaryMetric: number;
  gpgga_baselineAverage: number;
  gpgga_peakObserved: number;
  gpgga_standardDeviation: number;
  gpgga_rawHexSample: string;
  gpgga_metadataTag: Record<string, string>;
  gpgsa_primaryMetric: number;
  gpgsa_secondaryMetric: number;
  gpgsa_baselineAverage: number;
  gpgsa_peakObserved: number;
  gpgsa_standardDeviation: number;
  gpgsa_rawHexSample: string;
  gpgsa_metadataTag: Record<string, string>;
  gpgsv_primaryMetric: number;
  gpgsv_secondaryMetric: number;
  gpgsv_baselineAverage: number;
  gpgsv_peakObserved: number;
  gpgsv_standardDeviation: number;
  gpgsv_rawHexSample: string;
  gpgsv_metadataTag: Record<string, string>;
  gpvtg_primaryMetric: number;
  gpvtg_secondaryMetric: number;
  gpvtg_baselineAverage: number;
  gpvtg_peakObserved: number;
  gpvtg_standardDeviation: number;
  gpvtg_rawHexSample: string;
  gpvtg_metadataTag: Record<string, string>;
  gpgll_primaryMetric: number;
  gpgll_secondaryMetric: number;
  gpgll_baselineAverage: number;
  gpgll_peakObserved: number;
  gpgll_standardDeviation: number;
  gpgll_rawHexSample: string;
  gpgll_metadataTag: Record<string, string>;
  gpzda_primaryMetric: number;
  gpzda_secondaryMetric: number;
  gpzda_baselineAverage: number;
  gpzda_peakObserved: number;
  gpzda_standardDeviation: number;
  gpzda_rawHexSample: string;
  gpzda_metadataTag: Record<string, string>;
  gpmwd_primaryMetric: number;
  gpmwd_secondaryMetric: number;
  gpmwd_baselineAverage: number;
  gpmwd_peakObserved: number;
  gpmwd_standardDeviation: number;
  gpmwd_rawHexSample: string;
  gpmwd_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Nmea0183SentencesFilterV31 = Partial<Nmea0183SentencesRecordV31> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Nmea0183SentencesRecordV32 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  gprmc_primaryMetric: number;
  gprmc_secondaryMetric: number;
  gprmc_baselineAverage: number;
  gprmc_peakObserved: number;
  gprmc_standardDeviation: number;
  gprmc_rawHexSample: string;
  gprmc_metadataTag: Record<string, string>;
  gpgga_primaryMetric: number;
  gpgga_secondaryMetric: number;
  gpgga_baselineAverage: number;
  gpgga_peakObserved: number;
  gpgga_standardDeviation: number;
  gpgga_rawHexSample: string;
  gpgga_metadataTag: Record<string, string>;
  gpgsa_primaryMetric: number;
  gpgsa_secondaryMetric: number;
  gpgsa_baselineAverage: number;
  gpgsa_peakObserved: number;
  gpgsa_standardDeviation: number;
  gpgsa_rawHexSample: string;
  gpgsa_metadataTag: Record<string, string>;
  gpgsv_primaryMetric: number;
  gpgsv_secondaryMetric: number;
  gpgsv_baselineAverage: number;
  gpgsv_peakObserved: number;
  gpgsv_standardDeviation: number;
  gpgsv_rawHexSample: string;
  gpgsv_metadataTag: Record<string, string>;
  gpvtg_primaryMetric: number;
  gpvtg_secondaryMetric: number;
  gpvtg_baselineAverage: number;
  gpvtg_peakObserved: number;
  gpvtg_standardDeviation: number;
  gpvtg_rawHexSample: string;
  gpvtg_metadataTag: Record<string, string>;
  gpgll_primaryMetric: number;
  gpgll_secondaryMetric: number;
  gpgll_baselineAverage: number;
  gpgll_peakObserved: number;
  gpgll_standardDeviation: number;
  gpgll_rawHexSample: string;
  gpgll_metadataTag: Record<string, string>;
  gpzda_primaryMetric: number;
  gpzda_secondaryMetric: number;
  gpzda_baselineAverage: number;
  gpzda_peakObserved: number;
  gpzda_standardDeviation: number;
  gpzda_rawHexSample: string;
  gpzda_metadataTag: Record<string, string>;
  gpmwd_primaryMetric: number;
  gpmwd_secondaryMetric: number;
  gpmwd_baselineAverage: number;
  gpmwd_peakObserved: number;
  gpmwd_standardDeviation: number;
  gpmwd_rawHexSample: string;
  gpmwd_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Nmea0183SentencesFilterV32 = Partial<Nmea0183SentencesRecordV32> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Nmea0183SentencesRecordV33 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  gprmc_primaryMetric: number;
  gprmc_secondaryMetric: number;
  gprmc_baselineAverage: number;
  gprmc_peakObserved: number;
  gprmc_standardDeviation: number;
  gprmc_rawHexSample: string;
  gprmc_metadataTag: Record<string, string>;
  gpgga_primaryMetric: number;
  gpgga_secondaryMetric: number;
  gpgga_baselineAverage: number;
  gpgga_peakObserved: number;
  gpgga_standardDeviation: number;
  gpgga_rawHexSample: string;
  gpgga_metadataTag: Record<string, string>;
  gpgsa_primaryMetric: number;
  gpgsa_secondaryMetric: number;
  gpgsa_baselineAverage: number;
  gpgsa_peakObserved: number;
  gpgsa_standardDeviation: number;
  gpgsa_rawHexSample: string;
  gpgsa_metadataTag: Record<string, string>;
  gpgsv_primaryMetric: number;
  gpgsv_secondaryMetric: number;
  gpgsv_baselineAverage: number;
  gpgsv_peakObserved: number;
  gpgsv_standardDeviation: number;
  gpgsv_rawHexSample: string;
  gpgsv_metadataTag: Record<string, string>;
  gpvtg_primaryMetric: number;
  gpvtg_secondaryMetric: number;
  gpvtg_baselineAverage: number;
  gpvtg_peakObserved: number;
  gpvtg_standardDeviation: number;
  gpvtg_rawHexSample: string;
  gpvtg_metadataTag: Record<string, string>;
  gpgll_primaryMetric: number;
  gpgll_secondaryMetric: number;
  gpgll_baselineAverage: number;
  gpgll_peakObserved: number;
  gpgll_standardDeviation: number;
  gpgll_rawHexSample: string;
  gpgll_metadataTag: Record<string, string>;
  gpzda_primaryMetric: number;
  gpzda_secondaryMetric: number;
  gpzda_baselineAverage: number;
  gpzda_peakObserved: number;
  gpzda_standardDeviation: number;
  gpzda_rawHexSample: string;
  gpzda_metadataTag: Record<string, string>;
  gpmwd_primaryMetric: number;
  gpmwd_secondaryMetric: number;
  gpmwd_baselineAverage: number;
  gpmwd_peakObserved: number;
  gpmwd_standardDeviation: number;
  gpmwd_rawHexSample: string;
  gpmwd_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Nmea0183SentencesFilterV33 = Partial<Nmea0183SentencesRecordV33> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Nmea0183SentencesRecordV34 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  gprmc_primaryMetric: number;
  gprmc_secondaryMetric: number;
  gprmc_baselineAverage: number;
  gprmc_peakObserved: number;
  gprmc_standardDeviation: number;
  gprmc_rawHexSample: string;
  gprmc_metadataTag: Record<string, string>;
  gpgga_primaryMetric: number;
  gpgga_secondaryMetric: number;
  gpgga_baselineAverage: number;
  gpgga_peakObserved: number;
  gpgga_standardDeviation: number;
  gpgga_rawHexSample: string;
  gpgga_metadataTag: Record<string, string>;
  gpgsa_primaryMetric: number;
  gpgsa_secondaryMetric: number;
  gpgsa_baselineAverage: number;
  gpgsa_peakObserved: number;
  gpgsa_standardDeviation: number;
  gpgsa_rawHexSample: string;
  gpgsa_metadataTag: Record<string, string>;
  gpgsv_primaryMetric: number;
  gpgsv_secondaryMetric: number;
  gpgsv_baselineAverage: number;
  gpgsv_peakObserved: number;
  gpgsv_standardDeviation: number;
  gpgsv_rawHexSample: string;
  gpgsv_metadataTag: Record<string, string>;
  gpvtg_primaryMetric: number;
  gpvtg_secondaryMetric: number;
  gpvtg_baselineAverage: number;
  gpvtg_peakObserved: number;
  gpvtg_standardDeviation: number;
  gpvtg_rawHexSample: string;
  gpvtg_metadataTag: Record<string, string>;
  gpgll_primaryMetric: number;
  gpgll_secondaryMetric: number;
  gpgll_baselineAverage: number;
  gpgll_peakObserved: number;
  gpgll_standardDeviation: number;
  gpgll_rawHexSample: string;
  gpgll_metadataTag: Record<string, string>;
  gpzda_primaryMetric: number;
  gpzda_secondaryMetric: number;
  gpzda_baselineAverage: number;
  gpzda_peakObserved: number;
  gpzda_standardDeviation: number;
  gpzda_rawHexSample: string;
  gpzda_metadataTag: Record<string, string>;
  gpmwd_primaryMetric: number;
  gpmwd_secondaryMetric: number;
  gpmwd_baselineAverage: number;
  gpmwd_peakObserved: number;
  gpmwd_standardDeviation: number;
  gpmwd_rawHexSample: string;
  gpmwd_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Nmea0183SentencesFilterV34 = Partial<Nmea0183SentencesRecordV34> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Nmea0183SentencesRecordV35 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  gprmc_primaryMetric: number;
  gprmc_secondaryMetric: number;
  gprmc_baselineAverage: number;
  gprmc_peakObserved: number;
  gprmc_standardDeviation: number;
  gprmc_rawHexSample: string;
  gprmc_metadataTag: Record<string, string>;
  gpgga_primaryMetric: number;
  gpgga_secondaryMetric: number;
  gpgga_baselineAverage: number;
  gpgga_peakObserved: number;
  gpgga_standardDeviation: number;
  gpgga_rawHexSample: string;
  gpgga_metadataTag: Record<string, string>;
  gpgsa_primaryMetric: number;
  gpgsa_secondaryMetric: number;
  gpgsa_baselineAverage: number;
  gpgsa_peakObserved: number;
  gpgsa_standardDeviation: number;
  gpgsa_rawHexSample: string;
  gpgsa_metadataTag: Record<string, string>;
  gpgsv_primaryMetric: number;
  gpgsv_secondaryMetric: number;
  gpgsv_baselineAverage: number;
  gpgsv_peakObserved: number;
  gpgsv_standardDeviation: number;
  gpgsv_rawHexSample: string;
  gpgsv_metadataTag: Record<string, string>;
  gpvtg_primaryMetric: number;
  gpvtg_secondaryMetric: number;
  gpvtg_baselineAverage: number;
  gpvtg_peakObserved: number;
  gpvtg_standardDeviation: number;
  gpvtg_rawHexSample: string;
  gpvtg_metadataTag: Record<string, string>;
  gpgll_primaryMetric: number;
  gpgll_secondaryMetric: number;
  gpgll_baselineAverage: number;
  gpgll_peakObserved: number;
  gpgll_standardDeviation: number;
  gpgll_rawHexSample: string;
  gpgll_metadataTag: Record<string, string>;
  gpzda_primaryMetric: number;
  gpzda_secondaryMetric: number;
  gpzda_baselineAverage: number;
  gpzda_peakObserved: number;
  gpzda_standardDeviation: number;
  gpzda_rawHexSample: string;
  gpzda_metadataTag: Record<string, string>;
  gpmwd_primaryMetric: number;
  gpmwd_secondaryMetric: number;
  gpmwd_baselineAverage: number;
  gpmwd_peakObserved: number;
  gpmwd_standardDeviation: number;
  gpmwd_rawHexSample: string;
  gpmwd_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Nmea0183SentencesFilterV35 = Partial<Nmea0183SentencesRecordV35> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Nmea0183SentencesRecordV36 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  gprmc_primaryMetric: number;
  gprmc_secondaryMetric: number;
  gprmc_baselineAverage: number;
  gprmc_peakObserved: number;
  gprmc_standardDeviation: number;
  gprmc_rawHexSample: string;
  gprmc_metadataTag: Record<string, string>;
  gpgga_primaryMetric: number;
  gpgga_secondaryMetric: number;
  gpgga_baselineAverage: number;
  gpgga_peakObserved: number;
  gpgga_standardDeviation: number;
  gpgga_rawHexSample: string;
  gpgga_metadataTag: Record<string, string>;
  gpgsa_primaryMetric: number;
  gpgsa_secondaryMetric: number;
  gpgsa_baselineAverage: number;
  gpgsa_peakObserved: number;
  gpgsa_standardDeviation: number;
  gpgsa_rawHexSample: string;
  gpgsa_metadataTag: Record<string, string>;
  gpgsv_primaryMetric: number;
  gpgsv_secondaryMetric: number;
  gpgsv_baselineAverage: number;
  gpgsv_peakObserved: number;
  gpgsv_standardDeviation: number;
  gpgsv_rawHexSample: string;
  gpgsv_metadataTag: Record<string, string>;
  gpvtg_primaryMetric: number;
  gpvtg_secondaryMetric: number;
  gpvtg_baselineAverage: number;
  gpvtg_peakObserved: number;
  gpvtg_standardDeviation: number;
  gpvtg_rawHexSample: string;
  gpvtg_metadataTag: Record<string, string>;
  gpgll_primaryMetric: number;
  gpgll_secondaryMetric: number;
  gpgll_baselineAverage: number;
  gpgll_peakObserved: number;
  gpgll_standardDeviation: number;
  gpgll_rawHexSample: string;
  gpgll_metadataTag: Record<string, string>;
  gpzda_primaryMetric: number;
  gpzda_secondaryMetric: number;
  gpzda_baselineAverage: number;
  gpzda_peakObserved: number;
  gpzda_standardDeviation: number;
  gpzda_rawHexSample: string;
  gpzda_metadataTag: Record<string, string>;
  gpmwd_primaryMetric: number;
  gpmwd_secondaryMetric: number;
  gpmwd_baselineAverage: number;
  gpmwd_peakObserved: number;
  gpmwd_standardDeviation: number;
  gpmwd_rawHexSample: string;
  gpmwd_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Nmea0183SentencesFilterV36 = Partial<Nmea0183SentencesRecordV36> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Nmea0183SentencesRecordV37 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  gprmc_primaryMetric: number;
  gprmc_secondaryMetric: number;
  gprmc_baselineAverage: number;
  gprmc_peakObserved: number;
  gprmc_standardDeviation: number;
  gprmc_rawHexSample: string;
  gprmc_metadataTag: Record<string, string>;
  gpgga_primaryMetric: number;
  gpgga_secondaryMetric: number;
  gpgga_baselineAverage: number;
  gpgga_peakObserved: number;
  gpgga_standardDeviation: number;
  gpgga_rawHexSample: string;
  gpgga_metadataTag: Record<string, string>;
  gpgsa_primaryMetric: number;
  gpgsa_secondaryMetric: number;
  gpgsa_baselineAverage: number;
  gpgsa_peakObserved: number;
  gpgsa_standardDeviation: number;
  gpgsa_rawHexSample: string;
  gpgsa_metadataTag: Record<string, string>;
  gpgsv_primaryMetric: number;
  gpgsv_secondaryMetric: number;
  gpgsv_baselineAverage: number;
  gpgsv_peakObserved: number;
  gpgsv_standardDeviation: number;
  gpgsv_rawHexSample: string;
  gpgsv_metadataTag: Record<string, string>;
  gpvtg_primaryMetric: number;
  gpvtg_secondaryMetric: number;
  gpvtg_baselineAverage: number;
  gpvtg_peakObserved: number;
  gpvtg_standardDeviation: number;
  gpvtg_rawHexSample: string;
  gpvtg_metadataTag: Record<string, string>;
  gpgll_primaryMetric: number;
  gpgll_secondaryMetric: number;
  gpgll_baselineAverage: number;
  gpgll_peakObserved: number;
  gpgll_standardDeviation: number;
  gpgll_rawHexSample: string;
  gpgll_metadataTag: Record<string, string>;
  gpzda_primaryMetric: number;
  gpzda_secondaryMetric: number;
  gpzda_baselineAverage: number;
  gpzda_peakObserved: number;
  gpzda_standardDeviation: number;
  gpzda_rawHexSample: string;
  gpzda_metadataTag: Record<string, string>;
  gpmwd_primaryMetric: number;
  gpmwd_secondaryMetric: number;
  gpmwd_baselineAverage: number;
  gpmwd_peakObserved: number;
  gpmwd_standardDeviation: number;
  gpmwd_rawHexSample: string;
  gpmwd_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Nmea0183SentencesFilterV37 = Partial<Nmea0183SentencesRecordV37> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Nmea0183SentencesRecordV38 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  gprmc_primaryMetric: number;
  gprmc_secondaryMetric: number;
  gprmc_baselineAverage: number;
  gprmc_peakObserved: number;
  gprmc_standardDeviation: number;
  gprmc_rawHexSample: string;
  gprmc_metadataTag: Record<string, string>;
  gpgga_primaryMetric: number;
  gpgga_secondaryMetric: number;
  gpgga_baselineAverage: number;
  gpgga_peakObserved: number;
  gpgga_standardDeviation: number;
  gpgga_rawHexSample: string;
  gpgga_metadataTag: Record<string, string>;
  gpgsa_primaryMetric: number;
  gpgsa_secondaryMetric: number;
  gpgsa_baselineAverage: number;
  gpgsa_peakObserved: number;
  gpgsa_standardDeviation: number;
  gpgsa_rawHexSample: string;
  gpgsa_metadataTag: Record<string, string>;
  gpgsv_primaryMetric: number;
  gpgsv_secondaryMetric: number;
  gpgsv_baselineAverage: number;
  gpgsv_peakObserved: number;
  gpgsv_standardDeviation: number;
  gpgsv_rawHexSample: string;
  gpgsv_metadataTag: Record<string, string>;
  gpvtg_primaryMetric: number;
  gpvtg_secondaryMetric: number;
  gpvtg_baselineAverage: number;
  gpvtg_peakObserved: number;
  gpvtg_standardDeviation: number;
  gpvtg_rawHexSample: string;
  gpvtg_metadataTag: Record<string, string>;
  gpgll_primaryMetric: number;
  gpgll_secondaryMetric: number;
  gpgll_baselineAverage: number;
  gpgll_peakObserved: number;
  gpgll_standardDeviation: number;
  gpgll_rawHexSample: string;
  gpgll_metadataTag: Record<string, string>;
  gpzda_primaryMetric: number;
  gpzda_secondaryMetric: number;
  gpzda_baselineAverage: number;
  gpzda_peakObserved: number;
  gpzda_standardDeviation: number;
  gpzda_rawHexSample: string;
  gpzda_metadataTag: Record<string, string>;
  gpmwd_primaryMetric: number;
  gpmwd_secondaryMetric: number;
  gpmwd_baselineAverage: number;
  gpmwd_peakObserved: number;
  gpmwd_standardDeviation: number;
  gpmwd_rawHexSample: string;
  gpmwd_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Nmea0183SentencesFilterV38 = Partial<Nmea0183SentencesRecordV38> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Nmea0183SentencesRecordV39 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  gprmc_primaryMetric: number;
  gprmc_secondaryMetric: number;
  gprmc_baselineAverage: number;
  gprmc_peakObserved: number;
  gprmc_standardDeviation: number;
  gprmc_rawHexSample: string;
  gprmc_metadataTag: Record<string, string>;
  gpgga_primaryMetric: number;
  gpgga_secondaryMetric: number;
  gpgga_baselineAverage: number;
  gpgga_peakObserved: number;
  gpgga_standardDeviation: number;
  gpgga_rawHexSample: string;
  gpgga_metadataTag: Record<string, string>;
  gpgsa_primaryMetric: number;
  gpgsa_secondaryMetric: number;
  gpgsa_baselineAverage: number;
  gpgsa_peakObserved: number;
  gpgsa_standardDeviation: number;
  gpgsa_rawHexSample: string;
  gpgsa_metadataTag: Record<string, string>;
  gpgsv_primaryMetric: number;
  gpgsv_secondaryMetric: number;
  gpgsv_baselineAverage: number;
  gpgsv_peakObserved: number;
  gpgsv_standardDeviation: number;
  gpgsv_rawHexSample: string;
  gpgsv_metadataTag: Record<string, string>;
  gpvtg_primaryMetric: number;
  gpvtg_secondaryMetric: number;
  gpvtg_baselineAverage: number;
  gpvtg_peakObserved: number;
  gpvtg_standardDeviation: number;
  gpvtg_rawHexSample: string;
  gpvtg_metadataTag: Record<string, string>;
  gpgll_primaryMetric: number;
  gpgll_secondaryMetric: number;
  gpgll_baselineAverage: number;
  gpgll_peakObserved: number;
  gpgll_standardDeviation: number;
  gpgll_rawHexSample: string;
  gpgll_metadataTag: Record<string, string>;
  gpzda_primaryMetric: number;
  gpzda_secondaryMetric: number;
  gpzda_baselineAverage: number;
  gpzda_peakObserved: number;
  gpzda_standardDeviation: number;
  gpzda_rawHexSample: string;
  gpzda_metadataTag: Record<string, string>;
  gpmwd_primaryMetric: number;
  gpmwd_secondaryMetric: number;
  gpmwd_baselineAverage: number;
  gpmwd_peakObserved: number;
  gpmwd_standardDeviation: number;
  gpmwd_rawHexSample: string;
  gpmwd_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Nmea0183SentencesFilterV39 = Partial<Nmea0183SentencesRecordV39> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface Nmea0183SentencesRecordV40 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  gprmc_primaryMetric: number;
  gprmc_secondaryMetric: number;
  gprmc_baselineAverage: number;
  gprmc_peakObserved: number;
  gprmc_standardDeviation: number;
  gprmc_rawHexSample: string;
  gprmc_metadataTag: Record<string, string>;
  gpgga_primaryMetric: number;
  gpgga_secondaryMetric: number;
  gpgga_baselineAverage: number;
  gpgga_peakObserved: number;
  gpgga_standardDeviation: number;
  gpgga_rawHexSample: string;
  gpgga_metadataTag: Record<string, string>;
  gpgsa_primaryMetric: number;
  gpgsa_secondaryMetric: number;
  gpgsa_baselineAverage: number;
  gpgsa_peakObserved: number;
  gpgsa_standardDeviation: number;
  gpgsa_rawHexSample: string;
  gpgsa_metadataTag: Record<string, string>;
  gpgsv_primaryMetric: number;
  gpgsv_secondaryMetric: number;
  gpgsv_baselineAverage: number;
  gpgsv_peakObserved: number;
  gpgsv_standardDeviation: number;
  gpgsv_rawHexSample: string;
  gpgsv_metadataTag: Record<string, string>;
  gpvtg_primaryMetric: number;
  gpvtg_secondaryMetric: number;
  gpvtg_baselineAverage: number;
  gpvtg_peakObserved: number;
  gpvtg_standardDeviation: number;
  gpvtg_rawHexSample: string;
  gpvtg_metadataTag: Record<string, string>;
  gpgll_primaryMetric: number;
  gpgll_secondaryMetric: number;
  gpgll_baselineAverage: number;
  gpgll_peakObserved: number;
  gpgll_standardDeviation: number;
  gpgll_rawHexSample: string;
  gpgll_metadataTag: Record<string, string>;
  gpzda_primaryMetric: number;
  gpzda_secondaryMetric: number;
  gpzda_baselineAverage: number;
  gpzda_peakObserved: number;
  gpzda_standardDeviation: number;
  gpzda_rawHexSample: string;
  gpzda_metadataTag: Record<string, string>;
  gpmwd_primaryMetric: number;
  gpmwd_secondaryMetric: number;
  gpmwd_baselineAverage: number;
  gpmwd_peakObserved: number;
  gpmwd_standardDeviation: number;
  gpmwd_rawHexSample: string;
  gpmwd_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type Nmea0183SentencesFilterV40 = Partial<Nmea0183SentencesRecordV40> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};
