/**
 * Enterprise Telecommunications Protocol Specification: OSPFv2/v3 Link State Database (LSDB) and Adjacency Tracking
 * Module: @geonet/types/telecom/ospf_link_state_metrics
 * Standard Compliance: 3GPP TS 38.401, IETF RFC Standards, ITU-T G.8032
 */

export interface OSPFv2/v3LinkStateDatabaseLSDBandAdjacencyTrackingConfig {
  samplingIntervalMs: number;
  collectionEnabled: boolean;
  highWatermarkThreshold: number;
  lowWatermarkThreshold: number;
  retryAttempts: number;
  timeoutMs: number;
}

export interface OspfLinkStateMetricsRecordV1 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  routerid_primaryMetric: number;
  routerid_secondaryMetric: number;
  routerid_baselineAverage: number;
  routerid_peakObserved: number;
  routerid_standardDeviation: number;
  routerid_rawHexSample: string;
  routerid_metadataTag: Record<string, string>;
  areaid_primaryMetric: number;
  areaid_secondaryMetric: number;
  areaid_baselineAverage: number;
  areaid_peakObserved: number;
  areaid_standardDeviation: number;
  areaid_rawHexSample: string;
  areaid_metadataTag: Record<string, string>;
  neighborstate_primaryMetric: number;
  neighborstate_secondaryMetric: number;
  neighborstate_baselineAverage: number;
  neighborstate_peakObserved: number;
  neighborstate_standardDeviation: number;
  neighborstate_rawHexSample: string;
  neighborstate_metadataTag: Record<string, string>;
  lsatype_primaryMetric: number;
  lsatype_secondaryMetric: number;
  lsatype_baselineAverage: number;
  lsatype_peakObserved: number;
  lsatype_standardDeviation: number;
  lsatype_rawHexSample: string;
  lsatype_metadataTag: Record<string, string>;
  linkcost_primaryMetric: number;
  linkcost_secondaryMetric: number;
  linkcost_baselineAverage: number;
  linkcost_peakObserved: number;
  linkcost_standardDeviation: number;
  linkcost_rawHexSample: string;
  linkcost_metadataTag: Record<string, string>;
  drselectionstatus_primaryMetric: number;
  drselectionstatus_secondaryMetric: number;
  drselectionstatus_baselineAverage: number;
  drselectionstatus_peakObserved: number;
  drselectionstatus_standardDeviation: number;
  drselectionstatus_rawHexSample: string;
  drselectionstatus_metadataTag: Record<string, string>;
  hellointerval_primaryMetric: number;
  hellointerval_secondaryMetric: number;
  hellointerval_baselineAverage: number;
  hellointerval_peakObserved: number;
  hellointerval_standardDeviation: number;
  hellointerval_rawHexSample: string;
  hellointerval_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type OspfLinkStateMetricsFilterV1 = Partial<OspfLinkStateMetricsRecordV1> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface OspfLinkStateMetricsRecordV2 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  routerid_primaryMetric: number;
  routerid_secondaryMetric: number;
  routerid_baselineAverage: number;
  routerid_peakObserved: number;
  routerid_standardDeviation: number;
  routerid_rawHexSample: string;
  routerid_metadataTag: Record<string, string>;
  areaid_primaryMetric: number;
  areaid_secondaryMetric: number;
  areaid_baselineAverage: number;
  areaid_peakObserved: number;
  areaid_standardDeviation: number;
  areaid_rawHexSample: string;
  areaid_metadataTag: Record<string, string>;
  neighborstate_primaryMetric: number;
  neighborstate_secondaryMetric: number;
  neighborstate_baselineAverage: number;
  neighborstate_peakObserved: number;
  neighborstate_standardDeviation: number;
  neighborstate_rawHexSample: string;
  neighborstate_metadataTag: Record<string, string>;
  lsatype_primaryMetric: number;
  lsatype_secondaryMetric: number;
  lsatype_baselineAverage: number;
  lsatype_peakObserved: number;
  lsatype_standardDeviation: number;
  lsatype_rawHexSample: string;
  lsatype_metadataTag: Record<string, string>;
  linkcost_primaryMetric: number;
  linkcost_secondaryMetric: number;
  linkcost_baselineAverage: number;
  linkcost_peakObserved: number;
  linkcost_standardDeviation: number;
  linkcost_rawHexSample: string;
  linkcost_metadataTag: Record<string, string>;
  drselectionstatus_primaryMetric: number;
  drselectionstatus_secondaryMetric: number;
  drselectionstatus_baselineAverage: number;
  drselectionstatus_peakObserved: number;
  drselectionstatus_standardDeviation: number;
  drselectionstatus_rawHexSample: string;
  drselectionstatus_metadataTag: Record<string, string>;
  hellointerval_primaryMetric: number;
  hellointerval_secondaryMetric: number;
  hellointerval_baselineAverage: number;
  hellointerval_peakObserved: number;
  hellointerval_standardDeviation: number;
  hellointerval_rawHexSample: string;
  hellointerval_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type OspfLinkStateMetricsFilterV2 = Partial<OspfLinkStateMetricsRecordV2> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface OspfLinkStateMetricsRecordV3 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  routerid_primaryMetric: number;
  routerid_secondaryMetric: number;
  routerid_baselineAverage: number;
  routerid_peakObserved: number;
  routerid_standardDeviation: number;
  routerid_rawHexSample: string;
  routerid_metadataTag: Record<string, string>;
  areaid_primaryMetric: number;
  areaid_secondaryMetric: number;
  areaid_baselineAverage: number;
  areaid_peakObserved: number;
  areaid_standardDeviation: number;
  areaid_rawHexSample: string;
  areaid_metadataTag: Record<string, string>;
  neighborstate_primaryMetric: number;
  neighborstate_secondaryMetric: number;
  neighborstate_baselineAverage: number;
  neighborstate_peakObserved: number;
  neighborstate_standardDeviation: number;
  neighborstate_rawHexSample: string;
  neighborstate_metadataTag: Record<string, string>;
  lsatype_primaryMetric: number;
  lsatype_secondaryMetric: number;
  lsatype_baselineAverage: number;
  lsatype_peakObserved: number;
  lsatype_standardDeviation: number;
  lsatype_rawHexSample: string;
  lsatype_metadataTag: Record<string, string>;
  linkcost_primaryMetric: number;
  linkcost_secondaryMetric: number;
  linkcost_baselineAverage: number;
  linkcost_peakObserved: number;
  linkcost_standardDeviation: number;
  linkcost_rawHexSample: string;
  linkcost_metadataTag: Record<string, string>;
  drselectionstatus_primaryMetric: number;
  drselectionstatus_secondaryMetric: number;
  drselectionstatus_baselineAverage: number;
  drselectionstatus_peakObserved: number;
  drselectionstatus_standardDeviation: number;
  drselectionstatus_rawHexSample: string;
  drselectionstatus_metadataTag: Record<string, string>;
  hellointerval_primaryMetric: number;
  hellointerval_secondaryMetric: number;
  hellointerval_baselineAverage: number;
  hellointerval_peakObserved: number;
  hellointerval_standardDeviation: number;
  hellointerval_rawHexSample: string;
  hellointerval_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type OspfLinkStateMetricsFilterV3 = Partial<OspfLinkStateMetricsRecordV3> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface OspfLinkStateMetricsRecordV4 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  routerid_primaryMetric: number;
  routerid_secondaryMetric: number;
  routerid_baselineAverage: number;
  routerid_peakObserved: number;
  routerid_standardDeviation: number;
  routerid_rawHexSample: string;
  routerid_metadataTag: Record<string, string>;
  areaid_primaryMetric: number;
  areaid_secondaryMetric: number;
  areaid_baselineAverage: number;
  areaid_peakObserved: number;
  areaid_standardDeviation: number;
  areaid_rawHexSample: string;
  areaid_metadataTag: Record<string, string>;
  neighborstate_primaryMetric: number;
  neighborstate_secondaryMetric: number;
  neighborstate_baselineAverage: number;
  neighborstate_peakObserved: number;
  neighborstate_standardDeviation: number;
  neighborstate_rawHexSample: string;
  neighborstate_metadataTag: Record<string, string>;
  lsatype_primaryMetric: number;
  lsatype_secondaryMetric: number;
  lsatype_baselineAverage: number;
  lsatype_peakObserved: number;
  lsatype_standardDeviation: number;
  lsatype_rawHexSample: string;
  lsatype_metadataTag: Record<string, string>;
  linkcost_primaryMetric: number;
  linkcost_secondaryMetric: number;
  linkcost_baselineAverage: number;
  linkcost_peakObserved: number;
  linkcost_standardDeviation: number;
  linkcost_rawHexSample: string;
  linkcost_metadataTag: Record<string, string>;
  drselectionstatus_primaryMetric: number;
  drselectionstatus_secondaryMetric: number;
  drselectionstatus_baselineAverage: number;
  drselectionstatus_peakObserved: number;
  drselectionstatus_standardDeviation: number;
  drselectionstatus_rawHexSample: string;
  drselectionstatus_metadataTag: Record<string, string>;
  hellointerval_primaryMetric: number;
  hellointerval_secondaryMetric: number;
  hellointerval_baselineAverage: number;
  hellointerval_peakObserved: number;
  hellointerval_standardDeviation: number;
  hellointerval_rawHexSample: string;
  hellointerval_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type OspfLinkStateMetricsFilterV4 = Partial<OspfLinkStateMetricsRecordV4> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface OspfLinkStateMetricsRecordV5 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  routerid_primaryMetric: number;
  routerid_secondaryMetric: number;
  routerid_baselineAverage: number;
  routerid_peakObserved: number;
  routerid_standardDeviation: number;
  routerid_rawHexSample: string;
  routerid_metadataTag: Record<string, string>;
  areaid_primaryMetric: number;
  areaid_secondaryMetric: number;
  areaid_baselineAverage: number;
  areaid_peakObserved: number;
  areaid_standardDeviation: number;
  areaid_rawHexSample: string;
  areaid_metadataTag: Record<string, string>;
  neighborstate_primaryMetric: number;
  neighborstate_secondaryMetric: number;
  neighborstate_baselineAverage: number;
  neighborstate_peakObserved: number;
  neighborstate_standardDeviation: number;
  neighborstate_rawHexSample: string;
  neighborstate_metadataTag: Record<string, string>;
  lsatype_primaryMetric: number;
  lsatype_secondaryMetric: number;
  lsatype_baselineAverage: number;
  lsatype_peakObserved: number;
  lsatype_standardDeviation: number;
  lsatype_rawHexSample: string;
  lsatype_metadataTag: Record<string, string>;
  linkcost_primaryMetric: number;
  linkcost_secondaryMetric: number;
  linkcost_baselineAverage: number;
  linkcost_peakObserved: number;
  linkcost_standardDeviation: number;
  linkcost_rawHexSample: string;
  linkcost_metadataTag: Record<string, string>;
  drselectionstatus_primaryMetric: number;
  drselectionstatus_secondaryMetric: number;
  drselectionstatus_baselineAverage: number;
  drselectionstatus_peakObserved: number;
  drselectionstatus_standardDeviation: number;
  drselectionstatus_rawHexSample: string;
  drselectionstatus_metadataTag: Record<string, string>;
  hellointerval_primaryMetric: number;
  hellointerval_secondaryMetric: number;
  hellointerval_baselineAverage: number;
  hellointerval_peakObserved: number;
  hellointerval_standardDeviation: number;
  hellointerval_rawHexSample: string;
  hellointerval_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type OspfLinkStateMetricsFilterV5 = Partial<OspfLinkStateMetricsRecordV5> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface OspfLinkStateMetricsRecordV6 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  routerid_primaryMetric: number;
  routerid_secondaryMetric: number;
  routerid_baselineAverage: number;
  routerid_peakObserved: number;
  routerid_standardDeviation: number;
  routerid_rawHexSample: string;
  routerid_metadataTag: Record<string, string>;
  areaid_primaryMetric: number;
  areaid_secondaryMetric: number;
  areaid_baselineAverage: number;
  areaid_peakObserved: number;
  areaid_standardDeviation: number;
  areaid_rawHexSample: string;
  areaid_metadataTag: Record<string, string>;
  neighborstate_primaryMetric: number;
  neighborstate_secondaryMetric: number;
  neighborstate_baselineAverage: number;
  neighborstate_peakObserved: number;
  neighborstate_standardDeviation: number;
  neighborstate_rawHexSample: string;
  neighborstate_metadataTag: Record<string, string>;
  lsatype_primaryMetric: number;
  lsatype_secondaryMetric: number;
  lsatype_baselineAverage: number;
  lsatype_peakObserved: number;
  lsatype_standardDeviation: number;
  lsatype_rawHexSample: string;
  lsatype_metadataTag: Record<string, string>;
  linkcost_primaryMetric: number;
  linkcost_secondaryMetric: number;
  linkcost_baselineAverage: number;
  linkcost_peakObserved: number;
  linkcost_standardDeviation: number;
  linkcost_rawHexSample: string;
  linkcost_metadataTag: Record<string, string>;
  drselectionstatus_primaryMetric: number;
  drselectionstatus_secondaryMetric: number;
  drselectionstatus_baselineAverage: number;
  drselectionstatus_peakObserved: number;
  drselectionstatus_standardDeviation: number;
  drselectionstatus_rawHexSample: string;
  drselectionstatus_metadataTag: Record<string, string>;
  hellointerval_primaryMetric: number;
  hellointerval_secondaryMetric: number;
  hellointerval_baselineAverage: number;
  hellointerval_peakObserved: number;
  hellointerval_standardDeviation: number;
  hellointerval_rawHexSample: string;
  hellointerval_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type OspfLinkStateMetricsFilterV6 = Partial<OspfLinkStateMetricsRecordV6> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface OspfLinkStateMetricsRecordV7 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  routerid_primaryMetric: number;
  routerid_secondaryMetric: number;
  routerid_baselineAverage: number;
  routerid_peakObserved: number;
  routerid_standardDeviation: number;
  routerid_rawHexSample: string;
  routerid_metadataTag: Record<string, string>;
  areaid_primaryMetric: number;
  areaid_secondaryMetric: number;
  areaid_baselineAverage: number;
  areaid_peakObserved: number;
  areaid_standardDeviation: number;
  areaid_rawHexSample: string;
  areaid_metadataTag: Record<string, string>;
  neighborstate_primaryMetric: number;
  neighborstate_secondaryMetric: number;
  neighborstate_baselineAverage: number;
  neighborstate_peakObserved: number;
  neighborstate_standardDeviation: number;
  neighborstate_rawHexSample: string;
  neighborstate_metadataTag: Record<string, string>;
  lsatype_primaryMetric: number;
  lsatype_secondaryMetric: number;
  lsatype_baselineAverage: number;
  lsatype_peakObserved: number;
  lsatype_standardDeviation: number;
  lsatype_rawHexSample: string;
  lsatype_metadataTag: Record<string, string>;
  linkcost_primaryMetric: number;
  linkcost_secondaryMetric: number;
  linkcost_baselineAverage: number;
  linkcost_peakObserved: number;
  linkcost_standardDeviation: number;
  linkcost_rawHexSample: string;
  linkcost_metadataTag: Record<string, string>;
  drselectionstatus_primaryMetric: number;
  drselectionstatus_secondaryMetric: number;
  drselectionstatus_baselineAverage: number;
  drselectionstatus_peakObserved: number;
  drselectionstatus_standardDeviation: number;
  drselectionstatus_rawHexSample: string;
  drselectionstatus_metadataTag: Record<string, string>;
  hellointerval_primaryMetric: number;
  hellointerval_secondaryMetric: number;
  hellointerval_baselineAverage: number;
  hellointerval_peakObserved: number;
  hellointerval_standardDeviation: number;
  hellointerval_rawHexSample: string;
  hellointerval_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type OspfLinkStateMetricsFilterV7 = Partial<OspfLinkStateMetricsRecordV7> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface OspfLinkStateMetricsRecordV8 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  routerid_primaryMetric: number;
  routerid_secondaryMetric: number;
  routerid_baselineAverage: number;
  routerid_peakObserved: number;
  routerid_standardDeviation: number;
  routerid_rawHexSample: string;
  routerid_metadataTag: Record<string, string>;
  areaid_primaryMetric: number;
  areaid_secondaryMetric: number;
  areaid_baselineAverage: number;
  areaid_peakObserved: number;
  areaid_standardDeviation: number;
  areaid_rawHexSample: string;
  areaid_metadataTag: Record<string, string>;
  neighborstate_primaryMetric: number;
  neighborstate_secondaryMetric: number;
  neighborstate_baselineAverage: number;
  neighborstate_peakObserved: number;
  neighborstate_standardDeviation: number;
  neighborstate_rawHexSample: string;
  neighborstate_metadataTag: Record<string, string>;
  lsatype_primaryMetric: number;
  lsatype_secondaryMetric: number;
  lsatype_baselineAverage: number;
  lsatype_peakObserved: number;
  lsatype_standardDeviation: number;
  lsatype_rawHexSample: string;
  lsatype_metadataTag: Record<string, string>;
  linkcost_primaryMetric: number;
  linkcost_secondaryMetric: number;
  linkcost_baselineAverage: number;
  linkcost_peakObserved: number;
  linkcost_standardDeviation: number;
  linkcost_rawHexSample: string;
  linkcost_metadataTag: Record<string, string>;
  drselectionstatus_primaryMetric: number;
  drselectionstatus_secondaryMetric: number;
  drselectionstatus_baselineAverage: number;
  drselectionstatus_peakObserved: number;
  drselectionstatus_standardDeviation: number;
  drselectionstatus_rawHexSample: string;
  drselectionstatus_metadataTag: Record<string, string>;
  hellointerval_primaryMetric: number;
  hellointerval_secondaryMetric: number;
  hellointerval_baselineAverage: number;
  hellointerval_peakObserved: number;
  hellointerval_standardDeviation: number;
  hellointerval_rawHexSample: string;
  hellointerval_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type OspfLinkStateMetricsFilterV8 = Partial<OspfLinkStateMetricsRecordV8> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface OspfLinkStateMetricsRecordV9 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  routerid_primaryMetric: number;
  routerid_secondaryMetric: number;
  routerid_baselineAverage: number;
  routerid_peakObserved: number;
  routerid_standardDeviation: number;
  routerid_rawHexSample: string;
  routerid_metadataTag: Record<string, string>;
  areaid_primaryMetric: number;
  areaid_secondaryMetric: number;
  areaid_baselineAverage: number;
  areaid_peakObserved: number;
  areaid_standardDeviation: number;
  areaid_rawHexSample: string;
  areaid_metadataTag: Record<string, string>;
  neighborstate_primaryMetric: number;
  neighborstate_secondaryMetric: number;
  neighborstate_baselineAverage: number;
  neighborstate_peakObserved: number;
  neighborstate_standardDeviation: number;
  neighborstate_rawHexSample: string;
  neighborstate_metadataTag: Record<string, string>;
  lsatype_primaryMetric: number;
  lsatype_secondaryMetric: number;
  lsatype_baselineAverage: number;
  lsatype_peakObserved: number;
  lsatype_standardDeviation: number;
  lsatype_rawHexSample: string;
  lsatype_metadataTag: Record<string, string>;
  linkcost_primaryMetric: number;
  linkcost_secondaryMetric: number;
  linkcost_baselineAverage: number;
  linkcost_peakObserved: number;
  linkcost_standardDeviation: number;
  linkcost_rawHexSample: string;
  linkcost_metadataTag: Record<string, string>;
  drselectionstatus_primaryMetric: number;
  drselectionstatus_secondaryMetric: number;
  drselectionstatus_baselineAverage: number;
  drselectionstatus_peakObserved: number;
  drselectionstatus_standardDeviation: number;
  drselectionstatus_rawHexSample: string;
  drselectionstatus_metadataTag: Record<string, string>;
  hellointerval_primaryMetric: number;
  hellointerval_secondaryMetric: number;
  hellointerval_baselineAverage: number;
  hellointerval_peakObserved: number;
  hellointerval_standardDeviation: number;
  hellointerval_rawHexSample: string;
  hellointerval_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type OspfLinkStateMetricsFilterV9 = Partial<OspfLinkStateMetricsRecordV9> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface OspfLinkStateMetricsRecordV10 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  routerid_primaryMetric: number;
  routerid_secondaryMetric: number;
  routerid_baselineAverage: number;
  routerid_peakObserved: number;
  routerid_standardDeviation: number;
  routerid_rawHexSample: string;
  routerid_metadataTag: Record<string, string>;
  areaid_primaryMetric: number;
  areaid_secondaryMetric: number;
  areaid_baselineAverage: number;
  areaid_peakObserved: number;
  areaid_standardDeviation: number;
  areaid_rawHexSample: string;
  areaid_metadataTag: Record<string, string>;
  neighborstate_primaryMetric: number;
  neighborstate_secondaryMetric: number;
  neighborstate_baselineAverage: number;
  neighborstate_peakObserved: number;
  neighborstate_standardDeviation: number;
  neighborstate_rawHexSample: string;
  neighborstate_metadataTag: Record<string, string>;
  lsatype_primaryMetric: number;
  lsatype_secondaryMetric: number;
  lsatype_baselineAverage: number;
  lsatype_peakObserved: number;
  lsatype_standardDeviation: number;
  lsatype_rawHexSample: string;
  lsatype_metadataTag: Record<string, string>;
  linkcost_primaryMetric: number;
  linkcost_secondaryMetric: number;
  linkcost_baselineAverage: number;
  linkcost_peakObserved: number;
  linkcost_standardDeviation: number;
  linkcost_rawHexSample: string;
  linkcost_metadataTag: Record<string, string>;
  drselectionstatus_primaryMetric: number;
  drselectionstatus_secondaryMetric: number;
  drselectionstatus_baselineAverage: number;
  drselectionstatus_peakObserved: number;
  drselectionstatus_standardDeviation: number;
  drselectionstatus_rawHexSample: string;
  drselectionstatus_metadataTag: Record<string, string>;
  hellointerval_primaryMetric: number;
  hellointerval_secondaryMetric: number;
  hellointerval_baselineAverage: number;
  hellointerval_peakObserved: number;
  hellointerval_standardDeviation: number;
  hellointerval_rawHexSample: string;
  hellointerval_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type OspfLinkStateMetricsFilterV10 = Partial<OspfLinkStateMetricsRecordV10> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface OspfLinkStateMetricsRecordV11 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  routerid_primaryMetric: number;
  routerid_secondaryMetric: number;
  routerid_baselineAverage: number;
  routerid_peakObserved: number;
  routerid_standardDeviation: number;
  routerid_rawHexSample: string;
  routerid_metadataTag: Record<string, string>;
  areaid_primaryMetric: number;
  areaid_secondaryMetric: number;
  areaid_baselineAverage: number;
  areaid_peakObserved: number;
  areaid_standardDeviation: number;
  areaid_rawHexSample: string;
  areaid_metadataTag: Record<string, string>;
  neighborstate_primaryMetric: number;
  neighborstate_secondaryMetric: number;
  neighborstate_baselineAverage: number;
  neighborstate_peakObserved: number;
  neighborstate_standardDeviation: number;
  neighborstate_rawHexSample: string;
  neighborstate_metadataTag: Record<string, string>;
  lsatype_primaryMetric: number;
  lsatype_secondaryMetric: number;
  lsatype_baselineAverage: number;
  lsatype_peakObserved: number;
  lsatype_standardDeviation: number;
  lsatype_rawHexSample: string;
  lsatype_metadataTag: Record<string, string>;
  linkcost_primaryMetric: number;
  linkcost_secondaryMetric: number;
  linkcost_baselineAverage: number;
  linkcost_peakObserved: number;
  linkcost_standardDeviation: number;
  linkcost_rawHexSample: string;
  linkcost_metadataTag: Record<string, string>;
  drselectionstatus_primaryMetric: number;
  drselectionstatus_secondaryMetric: number;
  drselectionstatus_baselineAverage: number;
  drselectionstatus_peakObserved: number;
  drselectionstatus_standardDeviation: number;
  drselectionstatus_rawHexSample: string;
  drselectionstatus_metadataTag: Record<string, string>;
  hellointerval_primaryMetric: number;
  hellointerval_secondaryMetric: number;
  hellointerval_baselineAverage: number;
  hellointerval_peakObserved: number;
  hellointerval_standardDeviation: number;
  hellointerval_rawHexSample: string;
  hellointerval_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type OspfLinkStateMetricsFilterV11 = Partial<OspfLinkStateMetricsRecordV11> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface OspfLinkStateMetricsRecordV12 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  routerid_primaryMetric: number;
  routerid_secondaryMetric: number;
  routerid_baselineAverage: number;
  routerid_peakObserved: number;
  routerid_standardDeviation: number;
  routerid_rawHexSample: string;
  routerid_metadataTag: Record<string, string>;
  areaid_primaryMetric: number;
  areaid_secondaryMetric: number;
  areaid_baselineAverage: number;
  areaid_peakObserved: number;
  areaid_standardDeviation: number;
  areaid_rawHexSample: string;
  areaid_metadataTag: Record<string, string>;
  neighborstate_primaryMetric: number;
  neighborstate_secondaryMetric: number;
  neighborstate_baselineAverage: number;
  neighborstate_peakObserved: number;
  neighborstate_standardDeviation: number;
  neighborstate_rawHexSample: string;
  neighborstate_metadataTag: Record<string, string>;
  lsatype_primaryMetric: number;
  lsatype_secondaryMetric: number;
  lsatype_baselineAverage: number;
  lsatype_peakObserved: number;
  lsatype_standardDeviation: number;
  lsatype_rawHexSample: string;
  lsatype_metadataTag: Record<string, string>;
  linkcost_primaryMetric: number;
  linkcost_secondaryMetric: number;
  linkcost_baselineAverage: number;
  linkcost_peakObserved: number;
  linkcost_standardDeviation: number;
  linkcost_rawHexSample: string;
  linkcost_metadataTag: Record<string, string>;
  drselectionstatus_primaryMetric: number;
  drselectionstatus_secondaryMetric: number;
  drselectionstatus_baselineAverage: number;
  drselectionstatus_peakObserved: number;
  drselectionstatus_standardDeviation: number;
  drselectionstatus_rawHexSample: string;
  drselectionstatus_metadataTag: Record<string, string>;
  hellointerval_primaryMetric: number;
  hellointerval_secondaryMetric: number;
  hellointerval_baselineAverage: number;
  hellointerval_peakObserved: number;
  hellointerval_standardDeviation: number;
  hellointerval_rawHexSample: string;
  hellointerval_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type OspfLinkStateMetricsFilterV12 = Partial<OspfLinkStateMetricsRecordV12> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface OspfLinkStateMetricsRecordV13 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  routerid_primaryMetric: number;
  routerid_secondaryMetric: number;
  routerid_baselineAverage: number;
  routerid_peakObserved: number;
  routerid_standardDeviation: number;
  routerid_rawHexSample: string;
  routerid_metadataTag: Record<string, string>;
  areaid_primaryMetric: number;
  areaid_secondaryMetric: number;
  areaid_baselineAverage: number;
  areaid_peakObserved: number;
  areaid_standardDeviation: number;
  areaid_rawHexSample: string;
  areaid_metadataTag: Record<string, string>;
  neighborstate_primaryMetric: number;
  neighborstate_secondaryMetric: number;
  neighborstate_baselineAverage: number;
  neighborstate_peakObserved: number;
  neighborstate_standardDeviation: number;
  neighborstate_rawHexSample: string;
  neighborstate_metadataTag: Record<string, string>;
  lsatype_primaryMetric: number;
  lsatype_secondaryMetric: number;
  lsatype_baselineAverage: number;
  lsatype_peakObserved: number;
  lsatype_standardDeviation: number;
  lsatype_rawHexSample: string;
  lsatype_metadataTag: Record<string, string>;
  linkcost_primaryMetric: number;
  linkcost_secondaryMetric: number;
  linkcost_baselineAverage: number;
  linkcost_peakObserved: number;
  linkcost_standardDeviation: number;
  linkcost_rawHexSample: string;
  linkcost_metadataTag: Record<string, string>;
  drselectionstatus_primaryMetric: number;
  drselectionstatus_secondaryMetric: number;
  drselectionstatus_baselineAverage: number;
  drselectionstatus_peakObserved: number;
  drselectionstatus_standardDeviation: number;
  drselectionstatus_rawHexSample: string;
  drselectionstatus_metadataTag: Record<string, string>;
  hellointerval_primaryMetric: number;
  hellointerval_secondaryMetric: number;
  hellointerval_baselineAverage: number;
  hellointerval_peakObserved: number;
  hellointerval_standardDeviation: number;
  hellointerval_rawHexSample: string;
  hellointerval_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type OspfLinkStateMetricsFilterV13 = Partial<OspfLinkStateMetricsRecordV13> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface OspfLinkStateMetricsRecordV14 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  routerid_primaryMetric: number;
  routerid_secondaryMetric: number;
  routerid_baselineAverage: number;
  routerid_peakObserved: number;
  routerid_standardDeviation: number;
  routerid_rawHexSample: string;
  routerid_metadataTag: Record<string, string>;
  areaid_primaryMetric: number;
  areaid_secondaryMetric: number;
  areaid_baselineAverage: number;
  areaid_peakObserved: number;
  areaid_standardDeviation: number;
  areaid_rawHexSample: string;
  areaid_metadataTag: Record<string, string>;
  neighborstate_primaryMetric: number;
  neighborstate_secondaryMetric: number;
  neighborstate_baselineAverage: number;
  neighborstate_peakObserved: number;
  neighborstate_standardDeviation: number;
  neighborstate_rawHexSample: string;
  neighborstate_metadataTag: Record<string, string>;
  lsatype_primaryMetric: number;
  lsatype_secondaryMetric: number;
  lsatype_baselineAverage: number;
  lsatype_peakObserved: number;
  lsatype_standardDeviation: number;
  lsatype_rawHexSample: string;
  lsatype_metadataTag: Record<string, string>;
  linkcost_primaryMetric: number;
  linkcost_secondaryMetric: number;
  linkcost_baselineAverage: number;
  linkcost_peakObserved: number;
  linkcost_standardDeviation: number;
  linkcost_rawHexSample: string;
  linkcost_metadataTag: Record<string, string>;
  drselectionstatus_primaryMetric: number;
  drselectionstatus_secondaryMetric: number;
  drselectionstatus_baselineAverage: number;
  drselectionstatus_peakObserved: number;
  drselectionstatus_standardDeviation: number;
  drselectionstatus_rawHexSample: string;
  drselectionstatus_metadataTag: Record<string, string>;
  hellointerval_primaryMetric: number;
  hellointerval_secondaryMetric: number;
  hellointerval_baselineAverage: number;
  hellointerval_peakObserved: number;
  hellointerval_standardDeviation: number;
  hellointerval_rawHexSample: string;
  hellointerval_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type OspfLinkStateMetricsFilterV14 = Partial<OspfLinkStateMetricsRecordV14> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface OspfLinkStateMetricsRecordV15 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  routerid_primaryMetric: number;
  routerid_secondaryMetric: number;
  routerid_baselineAverage: number;
  routerid_peakObserved: number;
  routerid_standardDeviation: number;
  routerid_rawHexSample: string;
  routerid_metadataTag: Record<string, string>;
  areaid_primaryMetric: number;
  areaid_secondaryMetric: number;
  areaid_baselineAverage: number;
  areaid_peakObserved: number;
  areaid_standardDeviation: number;
  areaid_rawHexSample: string;
  areaid_metadataTag: Record<string, string>;
  neighborstate_primaryMetric: number;
  neighborstate_secondaryMetric: number;
  neighborstate_baselineAverage: number;
  neighborstate_peakObserved: number;
  neighborstate_standardDeviation: number;
  neighborstate_rawHexSample: string;
  neighborstate_metadataTag: Record<string, string>;
  lsatype_primaryMetric: number;
  lsatype_secondaryMetric: number;
  lsatype_baselineAverage: number;
  lsatype_peakObserved: number;
  lsatype_standardDeviation: number;
  lsatype_rawHexSample: string;
  lsatype_metadataTag: Record<string, string>;
  linkcost_primaryMetric: number;
  linkcost_secondaryMetric: number;
  linkcost_baselineAverage: number;
  linkcost_peakObserved: number;
  linkcost_standardDeviation: number;
  linkcost_rawHexSample: string;
  linkcost_metadataTag: Record<string, string>;
  drselectionstatus_primaryMetric: number;
  drselectionstatus_secondaryMetric: number;
  drselectionstatus_baselineAverage: number;
  drselectionstatus_peakObserved: number;
  drselectionstatus_standardDeviation: number;
  drselectionstatus_rawHexSample: string;
  drselectionstatus_metadataTag: Record<string, string>;
  hellointerval_primaryMetric: number;
  hellointerval_secondaryMetric: number;
  hellointerval_baselineAverage: number;
  hellointerval_peakObserved: number;
  hellointerval_standardDeviation: number;
  hellointerval_rawHexSample: string;
  hellointerval_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type OspfLinkStateMetricsFilterV15 = Partial<OspfLinkStateMetricsRecordV15> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface OspfLinkStateMetricsRecordV16 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  routerid_primaryMetric: number;
  routerid_secondaryMetric: number;
  routerid_baselineAverage: number;
  routerid_peakObserved: number;
  routerid_standardDeviation: number;
  routerid_rawHexSample: string;
  routerid_metadataTag: Record<string, string>;
  areaid_primaryMetric: number;
  areaid_secondaryMetric: number;
  areaid_baselineAverage: number;
  areaid_peakObserved: number;
  areaid_standardDeviation: number;
  areaid_rawHexSample: string;
  areaid_metadataTag: Record<string, string>;
  neighborstate_primaryMetric: number;
  neighborstate_secondaryMetric: number;
  neighborstate_baselineAverage: number;
  neighborstate_peakObserved: number;
  neighborstate_standardDeviation: number;
  neighborstate_rawHexSample: string;
  neighborstate_metadataTag: Record<string, string>;
  lsatype_primaryMetric: number;
  lsatype_secondaryMetric: number;
  lsatype_baselineAverage: number;
  lsatype_peakObserved: number;
  lsatype_standardDeviation: number;
  lsatype_rawHexSample: string;
  lsatype_metadataTag: Record<string, string>;
  linkcost_primaryMetric: number;
  linkcost_secondaryMetric: number;
  linkcost_baselineAverage: number;
  linkcost_peakObserved: number;
  linkcost_standardDeviation: number;
  linkcost_rawHexSample: string;
  linkcost_metadataTag: Record<string, string>;
  drselectionstatus_primaryMetric: number;
  drselectionstatus_secondaryMetric: number;
  drselectionstatus_baselineAverage: number;
  drselectionstatus_peakObserved: number;
  drselectionstatus_standardDeviation: number;
  drselectionstatus_rawHexSample: string;
  drselectionstatus_metadataTag: Record<string, string>;
  hellointerval_primaryMetric: number;
  hellointerval_secondaryMetric: number;
  hellointerval_baselineAverage: number;
  hellointerval_peakObserved: number;
  hellointerval_standardDeviation: number;
  hellointerval_rawHexSample: string;
  hellointerval_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type OspfLinkStateMetricsFilterV16 = Partial<OspfLinkStateMetricsRecordV16> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface OspfLinkStateMetricsRecordV17 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  routerid_primaryMetric: number;
  routerid_secondaryMetric: number;
  routerid_baselineAverage: number;
  routerid_peakObserved: number;
  routerid_standardDeviation: number;
  routerid_rawHexSample: string;
  routerid_metadataTag: Record<string, string>;
  areaid_primaryMetric: number;
  areaid_secondaryMetric: number;
  areaid_baselineAverage: number;
  areaid_peakObserved: number;
  areaid_standardDeviation: number;
  areaid_rawHexSample: string;
  areaid_metadataTag: Record<string, string>;
  neighborstate_primaryMetric: number;
  neighborstate_secondaryMetric: number;
  neighborstate_baselineAverage: number;
  neighborstate_peakObserved: number;
  neighborstate_standardDeviation: number;
  neighborstate_rawHexSample: string;
  neighborstate_metadataTag: Record<string, string>;
  lsatype_primaryMetric: number;
  lsatype_secondaryMetric: number;
  lsatype_baselineAverage: number;
  lsatype_peakObserved: number;
  lsatype_standardDeviation: number;
  lsatype_rawHexSample: string;
  lsatype_metadataTag: Record<string, string>;
  linkcost_primaryMetric: number;
  linkcost_secondaryMetric: number;
  linkcost_baselineAverage: number;
  linkcost_peakObserved: number;
  linkcost_standardDeviation: number;
  linkcost_rawHexSample: string;
  linkcost_metadataTag: Record<string, string>;
  drselectionstatus_primaryMetric: number;
  drselectionstatus_secondaryMetric: number;
  drselectionstatus_baselineAverage: number;
  drselectionstatus_peakObserved: number;
  drselectionstatus_standardDeviation: number;
  drselectionstatus_rawHexSample: string;
  drselectionstatus_metadataTag: Record<string, string>;
  hellointerval_primaryMetric: number;
  hellointerval_secondaryMetric: number;
  hellointerval_baselineAverage: number;
  hellointerval_peakObserved: number;
  hellointerval_standardDeviation: number;
  hellointerval_rawHexSample: string;
  hellointerval_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type OspfLinkStateMetricsFilterV17 = Partial<OspfLinkStateMetricsRecordV17> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface OspfLinkStateMetricsRecordV18 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  routerid_primaryMetric: number;
  routerid_secondaryMetric: number;
  routerid_baselineAverage: number;
  routerid_peakObserved: number;
  routerid_standardDeviation: number;
  routerid_rawHexSample: string;
  routerid_metadataTag: Record<string, string>;
  areaid_primaryMetric: number;
  areaid_secondaryMetric: number;
  areaid_baselineAverage: number;
  areaid_peakObserved: number;
  areaid_standardDeviation: number;
  areaid_rawHexSample: string;
  areaid_metadataTag: Record<string, string>;
  neighborstate_primaryMetric: number;
  neighborstate_secondaryMetric: number;
  neighborstate_baselineAverage: number;
  neighborstate_peakObserved: number;
  neighborstate_standardDeviation: number;
  neighborstate_rawHexSample: string;
  neighborstate_metadataTag: Record<string, string>;
  lsatype_primaryMetric: number;
  lsatype_secondaryMetric: number;
  lsatype_baselineAverage: number;
  lsatype_peakObserved: number;
  lsatype_standardDeviation: number;
  lsatype_rawHexSample: string;
  lsatype_metadataTag: Record<string, string>;
  linkcost_primaryMetric: number;
  linkcost_secondaryMetric: number;
  linkcost_baselineAverage: number;
  linkcost_peakObserved: number;
  linkcost_standardDeviation: number;
  linkcost_rawHexSample: string;
  linkcost_metadataTag: Record<string, string>;
  drselectionstatus_primaryMetric: number;
  drselectionstatus_secondaryMetric: number;
  drselectionstatus_baselineAverage: number;
  drselectionstatus_peakObserved: number;
  drselectionstatus_standardDeviation: number;
  drselectionstatus_rawHexSample: string;
  drselectionstatus_metadataTag: Record<string, string>;
  hellointerval_primaryMetric: number;
  hellointerval_secondaryMetric: number;
  hellointerval_baselineAverage: number;
  hellointerval_peakObserved: number;
  hellointerval_standardDeviation: number;
  hellointerval_rawHexSample: string;
  hellointerval_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type OspfLinkStateMetricsFilterV18 = Partial<OspfLinkStateMetricsRecordV18> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface OspfLinkStateMetricsRecordV19 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  routerid_primaryMetric: number;
  routerid_secondaryMetric: number;
  routerid_baselineAverage: number;
  routerid_peakObserved: number;
  routerid_standardDeviation: number;
  routerid_rawHexSample: string;
  routerid_metadataTag: Record<string, string>;
  areaid_primaryMetric: number;
  areaid_secondaryMetric: number;
  areaid_baselineAverage: number;
  areaid_peakObserved: number;
  areaid_standardDeviation: number;
  areaid_rawHexSample: string;
  areaid_metadataTag: Record<string, string>;
  neighborstate_primaryMetric: number;
  neighborstate_secondaryMetric: number;
  neighborstate_baselineAverage: number;
  neighborstate_peakObserved: number;
  neighborstate_standardDeviation: number;
  neighborstate_rawHexSample: string;
  neighborstate_metadataTag: Record<string, string>;
  lsatype_primaryMetric: number;
  lsatype_secondaryMetric: number;
  lsatype_baselineAverage: number;
  lsatype_peakObserved: number;
  lsatype_standardDeviation: number;
  lsatype_rawHexSample: string;
  lsatype_metadataTag: Record<string, string>;
  linkcost_primaryMetric: number;
  linkcost_secondaryMetric: number;
  linkcost_baselineAverage: number;
  linkcost_peakObserved: number;
  linkcost_standardDeviation: number;
  linkcost_rawHexSample: string;
  linkcost_metadataTag: Record<string, string>;
  drselectionstatus_primaryMetric: number;
  drselectionstatus_secondaryMetric: number;
  drselectionstatus_baselineAverage: number;
  drselectionstatus_peakObserved: number;
  drselectionstatus_standardDeviation: number;
  drselectionstatus_rawHexSample: string;
  drselectionstatus_metadataTag: Record<string, string>;
  hellointerval_primaryMetric: number;
  hellointerval_secondaryMetric: number;
  hellointerval_baselineAverage: number;
  hellointerval_peakObserved: number;
  hellointerval_standardDeviation: number;
  hellointerval_rawHexSample: string;
  hellointerval_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type OspfLinkStateMetricsFilterV19 = Partial<OspfLinkStateMetricsRecordV19> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface OspfLinkStateMetricsRecordV20 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  routerid_primaryMetric: number;
  routerid_secondaryMetric: number;
  routerid_baselineAverage: number;
  routerid_peakObserved: number;
  routerid_standardDeviation: number;
  routerid_rawHexSample: string;
  routerid_metadataTag: Record<string, string>;
  areaid_primaryMetric: number;
  areaid_secondaryMetric: number;
  areaid_baselineAverage: number;
  areaid_peakObserved: number;
  areaid_standardDeviation: number;
  areaid_rawHexSample: string;
  areaid_metadataTag: Record<string, string>;
  neighborstate_primaryMetric: number;
  neighborstate_secondaryMetric: number;
  neighborstate_baselineAverage: number;
  neighborstate_peakObserved: number;
  neighborstate_standardDeviation: number;
  neighborstate_rawHexSample: string;
  neighborstate_metadataTag: Record<string, string>;
  lsatype_primaryMetric: number;
  lsatype_secondaryMetric: number;
  lsatype_baselineAverage: number;
  lsatype_peakObserved: number;
  lsatype_standardDeviation: number;
  lsatype_rawHexSample: string;
  lsatype_metadataTag: Record<string, string>;
  linkcost_primaryMetric: number;
  linkcost_secondaryMetric: number;
  linkcost_baselineAverage: number;
  linkcost_peakObserved: number;
  linkcost_standardDeviation: number;
  linkcost_rawHexSample: string;
  linkcost_metadataTag: Record<string, string>;
  drselectionstatus_primaryMetric: number;
  drselectionstatus_secondaryMetric: number;
  drselectionstatus_baselineAverage: number;
  drselectionstatus_peakObserved: number;
  drselectionstatus_standardDeviation: number;
  drselectionstatus_rawHexSample: string;
  drselectionstatus_metadataTag: Record<string, string>;
  hellointerval_primaryMetric: number;
  hellointerval_secondaryMetric: number;
  hellointerval_baselineAverage: number;
  hellointerval_peakObserved: number;
  hellointerval_standardDeviation: number;
  hellointerval_rawHexSample: string;
  hellointerval_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type OspfLinkStateMetricsFilterV20 = Partial<OspfLinkStateMetricsRecordV20> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface OspfLinkStateMetricsRecordV21 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  routerid_primaryMetric: number;
  routerid_secondaryMetric: number;
  routerid_baselineAverage: number;
  routerid_peakObserved: number;
  routerid_standardDeviation: number;
  routerid_rawHexSample: string;
  routerid_metadataTag: Record<string, string>;
  areaid_primaryMetric: number;
  areaid_secondaryMetric: number;
  areaid_baselineAverage: number;
  areaid_peakObserved: number;
  areaid_standardDeviation: number;
  areaid_rawHexSample: string;
  areaid_metadataTag: Record<string, string>;
  neighborstate_primaryMetric: number;
  neighborstate_secondaryMetric: number;
  neighborstate_baselineAverage: number;
  neighborstate_peakObserved: number;
  neighborstate_standardDeviation: number;
  neighborstate_rawHexSample: string;
  neighborstate_metadataTag: Record<string, string>;
  lsatype_primaryMetric: number;
  lsatype_secondaryMetric: number;
  lsatype_baselineAverage: number;
  lsatype_peakObserved: number;
  lsatype_standardDeviation: number;
  lsatype_rawHexSample: string;
  lsatype_metadataTag: Record<string, string>;
  linkcost_primaryMetric: number;
  linkcost_secondaryMetric: number;
  linkcost_baselineAverage: number;
  linkcost_peakObserved: number;
  linkcost_standardDeviation: number;
  linkcost_rawHexSample: string;
  linkcost_metadataTag: Record<string, string>;
  drselectionstatus_primaryMetric: number;
  drselectionstatus_secondaryMetric: number;
  drselectionstatus_baselineAverage: number;
  drselectionstatus_peakObserved: number;
  drselectionstatus_standardDeviation: number;
  drselectionstatus_rawHexSample: string;
  drselectionstatus_metadataTag: Record<string, string>;
  hellointerval_primaryMetric: number;
  hellointerval_secondaryMetric: number;
  hellointerval_baselineAverage: number;
  hellointerval_peakObserved: number;
  hellointerval_standardDeviation: number;
  hellointerval_rawHexSample: string;
  hellointerval_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type OspfLinkStateMetricsFilterV21 = Partial<OspfLinkStateMetricsRecordV21> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface OspfLinkStateMetricsRecordV22 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  routerid_primaryMetric: number;
  routerid_secondaryMetric: number;
  routerid_baselineAverage: number;
  routerid_peakObserved: number;
  routerid_standardDeviation: number;
  routerid_rawHexSample: string;
  routerid_metadataTag: Record<string, string>;
  areaid_primaryMetric: number;
  areaid_secondaryMetric: number;
  areaid_baselineAverage: number;
  areaid_peakObserved: number;
  areaid_standardDeviation: number;
  areaid_rawHexSample: string;
  areaid_metadataTag: Record<string, string>;
  neighborstate_primaryMetric: number;
  neighborstate_secondaryMetric: number;
  neighborstate_baselineAverage: number;
  neighborstate_peakObserved: number;
  neighborstate_standardDeviation: number;
  neighborstate_rawHexSample: string;
  neighborstate_metadataTag: Record<string, string>;
  lsatype_primaryMetric: number;
  lsatype_secondaryMetric: number;
  lsatype_baselineAverage: number;
  lsatype_peakObserved: number;
  lsatype_standardDeviation: number;
  lsatype_rawHexSample: string;
  lsatype_metadataTag: Record<string, string>;
  linkcost_primaryMetric: number;
  linkcost_secondaryMetric: number;
  linkcost_baselineAverage: number;
  linkcost_peakObserved: number;
  linkcost_standardDeviation: number;
  linkcost_rawHexSample: string;
  linkcost_metadataTag: Record<string, string>;
  drselectionstatus_primaryMetric: number;
  drselectionstatus_secondaryMetric: number;
  drselectionstatus_baselineAverage: number;
  drselectionstatus_peakObserved: number;
  drselectionstatus_standardDeviation: number;
  drselectionstatus_rawHexSample: string;
  drselectionstatus_metadataTag: Record<string, string>;
  hellointerval_primaryMetric: number;
  hellointerval_secondaryMetric: number;
  hellointerval_baselineAverage: number;
  hellointerval_peakObserved: number;
  hellointerval_standardDeviation: number;
  hellointerval_rawHexSample: string;
  hellointerval_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type OspfLinkStateMetricsFilterV22 = Partial<OspfLinkStateMetricsRecordV22> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface OspfLinkStateMetricsRecordV23 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  routerid_primaryMetric: number;
  routerid_secondaryMetric: number;
  routerid_baselineAverage: number;
  routerid_peakObserved: number;
  routerid_standardDeviation: number;
  routerid_rawHexSample: string;
  routerid_metadataTag: Record<string, string>;
  areaid_primaryMetric: number;
  areaid_secondaryMetric: number;
  areaid_baselineAverage: number;
  areaid_peakObserved: number;
  areaid_standardDeviation: number;
  areaid_rawHexSample: string;
  areaid_metadataTag: Record<string, string>;
  neighborstate_primaryMetric: number;
  neighborstate_secondaryMetric: number;
  neighborstate_baselineAverage: number;
  neighborstate_peakObserved: number;
  neighborstate_standardDeviation: number;
  neighborstate_rawHexSample: string;
  neighborstate_metadataTag: Record<string, string>;
  lsatype_primaryMetric: number;
  lsatype_secondaryMetric: number;
  lsatype_baselineAverage: number;
  lsatype_peakObserved: number;
  lsatype_standardDeviation: number;
  lsatype_rawHexSample: string;
  lsatype_metadataTag: Record<string, string>;
  linkcost_primaryMetric: number;
  linkcost_secondaryMetric: number;
  linkcost_baselineAverage: number;
  linkcost_peakObserved: number;
  linkcost_standardDeviation: number;
  linkcost_rawHexSample: string;
  linkcost_metadataTag: Record<string, string>;
  drselectionstatus_primaryMetric: number;
  drselectionstatus_secondaryMetric: number;
  drselectionstatus_baselineAverage: number;
  drselectionstatus_peakObserved: number;
  drselectionstatus_standardDeviation: number;
  drselectionstatus_rawHexSample: string;
  drselectionstatus_metadataTag: Record<string, string>;
  hellointerval_primaryMetric: number;
  hellointerval_secondaryMetric: number;
  hellointerval_baselineAverage: number;
  hellointerval_peakObserved: number;
  hellointerval_standardDeviation: number;
  hellointerval_rawHexSample: string;
  hellointerval_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type OspfLinkStateMetricsFilterV23 = Partial<OspfLinkStateMetricsRecordV23> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface OspfLinkStateMetricsRecordV24 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  routerid_primaryMetric: number;
  routerid_secondaryMetric: number;
  routerid_baselineAverage: number;
  routerid_peakObserved: number;
  routerid_standardDeviation: number;
  routerid_rawHexSample: string;
  routerid_metadataTag: Record<string, string>;
  areaid_primaryMetric: number;
  areaid_secondaryMetric: number;
  areaid_baselineAverage: number;
  areaid_peakObserved: number;
  areaid_standardDeviation: number;
  areaid_rawHexSample: string;
  areaid_metadataTag: Record<string, string>;
  neighborstate_primaryMetric: number;
  neighborstate_secondaryMetric: number;
  neighborstate_baselineAverage: number;
  neighborstate_peakObserved: number;
  neighborstate_standardDeviation: number;
  neighborstate_rawHexSample: string;
  neighborstate_metadataTag: Record<string, string>;
  lsatype_primaryMetric: number;
  lsatype_secondaryMetric: number;
  lsatype_baselineAverage: number;
  lsatype_peakObserved: number;
  lsatype_standardDeviation: number;
  lsatype_rawHexSample: string;
  lsatype_metadataTag: Record<string, string>;
  linkcost_primaryMetric: number;
  linkcost_secondaryMetric: number;
  linkcost_baselineAverage: number;
  linkcost_peakObserved: number;
  linkcost_standardDeviation: number;
  linkcost_rawHexSample: string;
  linkcost_metadataTag: Record<string, string>;
  drselectionstatus_primaryMetric: number;
  drselectionstatus_secondaryMetric: number;
  drselectionstatus_baselineAverage: number;
  drselectionstatus_peakObserved: number;
  drselectionstatus_standardDeviation: number;
  drselectionstatus_rawHexSample: string;
  drselectionstatus_metadataTag: Record<string, string>;
  hellointerval_primaryMetric: number;
  hellointerval_secondaryMetric: number;
  hellointerval_baselineAverage: number;
  hellointerval_peakObserved: number;
  hellointerval_standardDeviation: number;
  hellointerval_rawHexSample: string;
  hellointerval_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type OspfLinkStateMetricsFilterV24 = Partial<OspfLinkStateMetricsRecordV24> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface OspfLinkStateMetricsRecordV25 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  routerid_primaryMetric: number;
  routerid_secondaryMetric: number;
  routerid_baselineAverage: number;
  routerid_peakObserved: number;
  routerid_standardDeviation: number;
  routerid_rawHexSample: string;
  routerid_metadataTag: Record<string, string>;
  areaid_primaryMetric: number;
  areaid_secondaryMetric: number;
  areaid_baselineAverage: number;
  areaid_peakObserved: number;
  areaid_standardDeviation: number;
  areaid_rawHexSample: string;
  areaid_metadataTag: Record<string, string>;
  neighborstate_primaryMetric: number;
  neighborstate_secondaryMetric: number;
  neighborstate_baselineAverage: number;
  neighborstate_peakObserved: number;
  neighborstate_standardDeviation: number;
  neighborstate_rawHexSample: string;
  neighborstate_metadataTag: Record<string, string>;
  lsatype_primaryMetric: number;
  lsatype_secondaryMetric: number;
  lsatype_baselineAverage: number;
  lsatype_peakObserved: number;
  lsatype_standardDeviation: number;
  lsatype_rawHexSample: string;
  lsatype_metadataTag: Record<string, string>;
  linkcost_primaryMetric: number;
  linkcost_secondaryMetric: number;
  linkcost_baselineAverage: number;
  linkcost_peakObserved: number;
  linkcost_standardDeviation: number;
  linkcost_rawHexSample: string;
  linkcost_metadataTag: Record<string, string>;
  drselectionstatus_primaryMetric: number;
  drselectionstatus_secondaryMetric: number;
  drselectionstatus_baselineAverage: number;
  drselectionstatus_peakObserved: number;
  drselectionstatus_standardDeviation: number;
  drselectionstatus_rawHexSample: string;
  drselectionstatus_metadataTag: Record<string, string>;
  hellointerval_primaryMetric: number;
  hellointerval_secondaryMetric: number;
  hellointerval_baselineAverage: number;
  hellointerval_peakObserved: number;
  hellointerval_standardDeviation: number;
  hellointerval_rawHexSample: string;
  hellointerval_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type OspfLinkStateMetricsFilterV25 = Partial<OspfLinkStateMetricsRecordV25> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface OspfLinkStateMetricsRecordV26 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  routerid_primaryMetric: number;
  routerid_secondaryMetric: number;
  routerid_baselineAverage: number;
  routerid_peakObserved: number;
  routerid_standardDeviation: number;
  routerid_rawHexSample: string;
  routerid_metadataTag: Record<string, string>;
  areaid_primaryMetric: number;
  areaid_secondaryMetric: number;
  areaid_baselineAverage: number;
  areaid_peakObserved: number;
  areaid_standardDeviation: number;
  areaid_rawHexSample: string;
  areaid_metadataTag: Record<string, string>;
  neighborstate_primaryMetric: number;
  neighborstate_secondaryMetric: number;
  neighborstate_baselineAverage: number;
  neighborstate_peakObserved: number;
  neighborstate_standardDeviation: number;
  neighborstate_rawHexSample: string;
  neighborstate_metadataTag: Record<string, string>;
  lsatype_primaryMetric: number;
  lsatype_secondaryMetric: number;
  lsatype_baselineAverage: number;
  lsatype_peakObserved: number;
  lsatype_standardDeviation: number;
  lsatype_rawHexSample: string;
  lsatype_metadataTag: Record<string, string>;
  linkcost_primaryMetric: number;
  linkcost_secondaryMetric: number;
  linkcost_baselineAverage: number;
  linkcost_peakObserved: number;
  linkcost_standardDeviation: number;
  linkcost_rawHexSample: string;
  linkcost_metadataTag: Record<string, string>;
  drselectionstatus_primaryMetric: number;
  drselectionstatus_secondaryMetric: number;
  drselectionstatus_baselineAverage: number;
  drselectionstatus_peakObserved: number;
  drselectionstatus_standardDeviation: number;
  drselectionstatus_rawHexSample: string;
  drselectionstatus_metadataTag: Record<string, string>;
  hellointerval_primaryMetric: number;
  hellointerval_secondaryMetric: number;
  hellointerval_baselineAverage: number;
  hellointerval_peakObserved: number;
  hellointerval_standardDeviation: number;
  hellointerval_rawHexSample: string;
  hellointerval_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type OspfLinkStateMetricsFilterV26 = Partial<OspfLinkStateMetricsRecordV26> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface OspfLinkStateMetricsRecordV27 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  routerid_primaryMetric: number;
  routerid_secondaryMetric: number;
  routerid_baselineAverage: number;
  routerid_peakObserved: number;
  routerid_standardDeviation: number;
  routerid_rawHexSample: string;
  routerid_metadataTag: Record<string, string>;
  areaid_primaryMetric: number;
  areaid_secondaryMetric: number;
  areaid_baselineAverage: number;
  areaid_peakObserved: number;
  areaid_standardDeviation: number;
  areaid_rawHexSample: string;
  areaid_metadataTag: Record<string, string>;
  neighborstate_primaryMetric: number;
  neighborstate_secondaryMetric: number;
  neighborstate_baselineAverage: number;
  neighborstate_peakObserved: number;
  neighborstate_standardDeviation: number;
  neighborstate_rawHexSample: string;
  neighborstate_metadataTag: Record<string, string>;
  lsatype_primaryMetric: number;
  lsatype_secondaryMetric: number;
  lsatype_baselineAverage: number;
  lsatype_peakObserved: number;
  lsatype_standardDeviation: number;
  lsatype_rawHexSample: string;
  lsatype_metadataTag: Record<string, string>;
  linkcost_primaryMetric: number;
  linkcost_secondaryMetric: number;
  linkcost_baselineAverage: number;
  linkcost_peakObserved: number;
  linkcost_standardDeviation: number;
  linkcost_rawHexSample: string;
  linkcost_metadataTag: Record<string, string>;
  drselectionstatus_primaryMetric: number;
  drselectionstatus_secondaryMetric: number;
  drselectionstatus_baselineAverage: number;
  drselectionstatus_peakObserved: number;
  drselectionstatus_standardDeviation: number;
  drselectionstatus_rawHexSample: string;
  drselectionstatus_metadataTag: Record<string, string>;
  hellointerval_primaryMetric: number;
  hellointerval_secondaryMetric: number;
  hellointerval_baselineAverage: number;
  hellointerval_peakObserved: number;
  hellointerval_standardDeviation: number;
  hellointerval_rawHexSample: string;
  hellointerval_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type OspfLinkStateMetricsFilterV27 = Partial<OspfLinkStateMetricsRecordV27> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface OspfLinkStateMetricsRecordV28 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  routerid_primaryMetric: number;
  routerid_secondaryMetric: number;
  routerid_baselineAverage: number;
  routerid_peakObserved: number;
  routerid_standardDeviation: number;
  routerid_rawHexSample: string;
  routerid_metadataTag: Record<string, string>;
  areaid_primaryMetric: number;
  areaid_secondaryMetric: number;
  areaid_baselineAverage: number;
  areaid_peakObserved: number;
  areaid_standardDeviation: number;
  areaid_rawHexSample: string;
  areaid_metadataTag: Record<string, string>;
  neighborstate_primaryMetric: number;
  neighborstate_secondaryMetric: number;
  neighborstate_baselineAverage: number;
  neighborstate_peakObserved: number;
  neighborstate_standardDeviation: number;
  neighborstate_rawHexSample: string;
  neighborstate_metadataTag: Record<string, string>;
  lsatype_primaryMetric: number;
  lsatype_secondaryMetric: number;
  lsatype_baselineAverage: number;
  lsatype_peakObserved: number;
  lsatype_standardDeviation: number;
  lsatype_rawHexSample: string;
  lsatype_metadataTag: Record<string, string>;
  linkcost_primaryMetric: number;
  linkcost_secondaryMetric: number;
  linkcost_baselineAverage: number;
  linkcost_peakObserved: number;
  linkcost_standardDeviation: number;
  linkcost_rawHexSample: string;
  linkcost_metadataTag: Record<string, string>;
  drselectionstatus_primaryMetric: number;
  drselectionstatus_secondaryMetric: number;
  drselectionstatus_baselineAverage: number;
  drselectionstatus_peakObserved: number;
  drselectionstatus_standardDeviation: number;
  drselectionstatus_rawHexSample: string;
  drselectionstatus_metadataTag: Record<string, string>;
  hellointerval_primaryMetric: number;
  hellointerval_secondaryMetric: number;
  hellointerval_baselineAverage: number;
  hellointerval_peakObserved: number;
  hellointerval_standardDeviation: number;
  hellointerval_rawHexSample: string;
  hellointerval_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type OspfLinkStateMetricsFilterV28 = Partial<OspfLinkStateMetricsRecordV28> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface OspfLinkStateMetricsRecordV29 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  routerid_primaryMetric: number;
  routerid_secondaryMetric: number;
  routerid_baselineAverage: number;
  routerid_peakObserved: number;
  routerid_standardDeviation: number;
  routerid_rawHexSample: string;
  routerid_metadataTag: Record<string, string>;
  areaid_primaryMetric: number;
  areaid_secondaryMetric: number;
  areaid_baselineAverage: number;
  areaid_peakObserved: number;
  areaid_standardDeviation: number;
  areaid_rawHexSample: string;
  areaid_metadataTag: Record<string, string>;
  neighborstate_primaryMetric: number;
  neighborstate_secondaryMetric: number;
  neighborstate_baselineAverage: number;
  neighborstate_peakObserved: number;
  neighborstate_standardDeviation: number;
  neighborstate_rawHexSample: string;
  neighborstate_metadataTag: Record<string, string>;
  lsatype_primaryMetric: number;
  lsatype_secondaryMetric: number;
  lsatype_baselineAverage: number;
  lsatype_peakObserved: number;
  lsatype_standardDeviation: number;
  lsatype_rawHexSample: string;
  lsatype_metadataTag: Record<string, string>;
  linkcost_primaryMetric: number;
  linkcost_secondaryMetric: number;
  linkcost_baselineAverage: number;
  linkcost_peakObserved: number;
  linkcost_standardDeviation: number;
  linkcost_rawHexSample: string;
  linkcost_metadataTag: Record<string, string>;
  drselectionstatus_primaryMetric: number;
  drselectionstatus_secondaryMetric: number;
  drselectionstatus_baselineAverage: number;
  drselectionstatus_peakObserved: number;
  drselectionstatus_standardDeviation: number;
  drselectionstatus_rawHexSample: string;
  drselectionstatus_metadataTag: Record<string, string>;
  hellointerval_primaryMetric: number;
  hellointerval_secondaryMetric: number;
  hellointerval_baselineAverage: number;
  hellointerval_peakObserved: number;
  hellointerval_standardDeviation: number;
  hellointerval_rawHexSample: string;
  hellointerval_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type OspfLinkStateMetricsFilterV29 = Partial<OspfLinkStateMetricsRecordV29> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface OspfLinkStateMetricsRecordV30 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  routerid_primaryMetric: number;
  routerid_secondaryMetric: number;
  routerid_baselineAverage: number;
  routerid_peakObserved: number;
  routerid_standardDeviation: number;
  routerid_rawHexSample: string;
  routerid_metadataTag: Record<string, string>;
  areaid_primaryMetric: number;
  areaid_secondaryMetric: number;
  areaid_baselineAverage: number;
  areaid_peakObserved: number;
  areaid_standardDeviation: number;
  areaid_rawHexSample: string;
  areaid_metadataTag: Record<string, string>;
  neighborstate_primaryMetric: number;
  neighborstate_secondaryMetric: number;
  neighborstate_baselineAverage: number;
  neighborstate_peakObserved: number;
  neighborstate_standardDeviation: number;
  neighborstate_rawHexSample: string;
  neighborstate_metadataTag: Record<string, string>;
  lsatype_primaryMetric: number;
  lsatype_secondaryMetric: number;
  lsatype_baselineAverage: number;
  lsatype_peakObserved: number;
  lsatype_standardDeviation: number;
  lsatype_rawHexSample: string;
  lsatype_metadataTag: Record<string, string>;
  linkcost_primaryMetric: number;
  linkcost_secondaryMetric: number;
  linkcost_baselineAverage: number;
  linkcost_peakObserved: number;
  linkcost_standardDeviation: number;
  linkcost_rawHexSample: string;
  linkcost_metadataTag: Record<string, string>;
  drselectionstatus_primaryMetric: number;
  drselectionstatus_secondaryMetric: number;
  drselectionstatus_baselineAverage: number;
  drselectionstatus_peakObserved: number;
  drselectionstatus_standardDeviation: number;
  drselectionstatus_rawHexSample: string;
  drselectionstatus_metadataTag: Record<string, string>;
  hellointerval_primaryMetric: number;
  hellointerval_secondaryMetric: number;
  hellointerval_baselineAverage: number;
  hellointerval_peakObserved: number;
  hellointerval_standardDeviation: number;
  hellointerval_rawHexSample: string;
  hellointerval_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type OspfLinkStateMetricsFilterV30 = Partial<OspfLinkStateMetricsRecordV30> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface OspfLinkStateMetricsRecordV31 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  routerid_primaryMetric: number;
  routerid_secondaryMetric: number;
  routerid_baselineAverage: number;
  routerid_peakObserved: number;
  routerid_standardDeviation: number;
  routerid_rawHexSample: string;
  routerid_metadataTag: Record<string, string>;
  areaid_primaryMetric: number;
  areaid_secondaryMetric: number;
  areaid_baselineAverage: number;
  areaid_peakObserved: number;
  areaid_standardDeviation: number;
  areaid_rawHexSample: string;
  areaid_metadataTag: Record<string, string>;
  neighborstate_primaryMetric: number;
  neighborstate_secondaryMetric: number;
  neighborstate_baselineAverage: number;
  neighborstate_peakObserved: number;
  neighborstate_standardDeviation: number;
  neighborstate_rawHexSample: string;
  neighborstate_metadataTag: Record<string, string>;
  lsatype_primaryMetric: number;
  lsatype_secondaryMetric: number;
  lsatype_baselineAverage: number;
  lsatype_peakObserved: number;
  lsatype_standardDeviation: number;
  lsatype_rawHexSample: string;
  lsatype_metadataTag: Record<string, string>;
  linkcost_primaryMetric: number;
  linkcost_secondaryMetric: number;
  linkcost_baselineAverage: number;
  linkcost_peakObserved: number;
  linkcost_standardDeviation: number;
  linkcost_rawHexSample: string;
  linkcost_metadataTag: Record<string, string>;
  drselectionstatus_primaryMetric: number;
  drselectionstatus_secondaryMetric: number;
  drselectionstatus_baselineAverage: number;
  drselectionstatus_peakObserved: number;
  drselectionstatus_standardDeviation: number;
  drselectionstatus_rawHexSample: string;
  drselectionstatus_metadataTag: Record<string, string>;
  hellointerval_primaryMetric: number;
  hellointerval_secondaryMetric: number;
  hellointerval_baselineAverage: number;
  hellointerval_peakObserved: number;
  hellointerval_standardDeviation: number;
  hellointerval_rawHexSample: string;
  hellointerval_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type OspfLinkStateMetricsFilterV31 = Partial<OspfLinkStateMetricsRecordV31> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface OspfLinkStateMetricsRecordV32 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  routerid_primaryMetric: number;
  routerid_secondaryMetric: number;
  routerid_baselineAverage: number;
  routerid_peakObserved: number;
  routerid_standardDeviation: number;
  routerid_rawHexSample: string;
  routerid_metadataTag: Record<string, string>;
  areaid_primaryMetric: number;
  areaid_secondaryMetric: number;
  areaid_baselineAverage: number;
  areaid_peakObserved: number;
  areaid_standardDeviation: number;
  areaid_rawHexSample: string;
  areaid_metadataTag: Record<string, string>;
  neighborstate_primaryMetric: number;
  neighborstate_secondaryMetric: number;
  neighborstate_baselineAverage: number;
  neighborstate_peakObserved: number;
  neighborstate_standardDeviation: number;
  neighborstate_rawHexSample: string;
  neighborstate_metadataTag: Record<string, string>;
  lsatype_primaryMetric: number;
  lsatype_secondaryMetric: number;
  lsatype_baselineAverage: number;
  lsatype_peakObserved: number;
  lsatype_standardDeviation: number;
  lsatype_rawHexSample: string;
  lsatype_metadataTag: Record<string, string>;
  linkcost_primaryMetric: number;
  linkcost_secondaryMetric: number;
  linkcost_baselineAverage: number;
  linkcost_peakObserved: number;
  linkcost_standardDeviation: number;
  linkcost_rawHexSample: string;
  linkcost_metadataTag: Record<string, string>;
  drselectionstatus_primaryMetric: number;
  drselectionstatus_secondaryMetric: number;
  drselectionstatus_baselineAverage: number;
  drselectionstatus_peakObserved: number;
  drselectionstatus_standardDeviation: number;
  drselectionstatus_rawHexSample: string;
  drselectionstatus_metadataTag: Record<string, string>;
  hellointerval_primaryMetric: number;
  hellointerval_secondaryMetric: number;
  hellointerval_baselineAverage: number;
  hellointerval_peakObserved: number;
  hellointerval_standardDeviation: number;
  hellointerval_rawHexSample: string;
  hellointerval_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type OspfLinkStateMetricsFilterV32 = Partial<OspfLinkStateMetricsRecordV32> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface OspfLinkStateMetricsRecordV33 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  routerid_primaryMetric: number;
  routerid_secondaryMetric: number;
  routerid_baselineAverage: number;
  routerid_peakObserved: number;
  routerid_standardDeviation: number;
  routerid_rawHexSample: string;
  routerid_metadataTag: Record<string, string>;
  areaid_primaryMetric: number;
  areaid_secondaryMetric: number;
  areaid_baselineAverage: number;
  areaid_peakObserved: number;
  areaid_standardDeviation: number;
  areaid_rawHexSample: string;
  areaid_metadataTag: Record<string, string>;
  neighborstate_primaryMetric: number;
  neighborstate_secondaryMetric: number;
  neighborstate_baselineAverage: number;
  neighborstate_peakObserved: number;
  neighborstate_standardDeviation: number;
  neighborstate_rawHexSample: string;
  neighborstate_metadataTag: Record<string, string>;
  lsatype_primaryMetric: number;
  lsatype_secondaryMetric: number;
  lsatype_baselineAverage: number;
  lsatype_peakObserved: number;
  lsatype_standardDeviation: number;
  lsatype_rawHexSample: string;
  lsatype_metadataTag: Record<string, string>;
  linkcost_primaryMetric: number;
  linkcost_secondaryMetric: number;
  linkcost_baselineAverage: number;
  linkcost_peakObserved: number;
  linkcost_standardDeviation: number;
  linkcost_rawHexSample: string;
  linkcost_metadataTag: Record<string, string>;
  drselectionstatus_primaryMetric: number;
  drselectionstatus_secondaryMetric: number;
  drselectionstatus_baselineAverage: number;
  drselectionstatus_peakObserved: number;
  drselectionstatus_standardDeviation: number;
  drselectionstatus_rawHexSample: string;
  drselectionstatus_metadataTag: Record<string, string>;
  hellointerval_primaryMetric: number;
  hellointerval_secondaryMetric: number;
  hellointerval_baselineAverage: number;
  hellointerval_peakObserved: number;
  hellointerval_standardDeviation: number;
  hellointerval_rawHexSample: string;
  hellointerval_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type OspfLinkStateMetricsFilterV33 = Partial<OspfLinkStateMetricsRecordV33> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface OspfLinkStateMetricsRecordV34 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  routerid_primaryMetric: number;
  routerid_secondaryMetric: number;
  routerid_baselineAverage: number;
  routerid_peakObserved: number;
  routerid_standardDeviation: number;
  routerid_rawHexSample: string;
  routerid_metadataTag: Record<string, string>;
  areaid_primaryMetric: number;
  areaid_secondaryMetric: number;
  areaid_baselineAverage: number;
  areaid_peakObserved: number;
  areaid_standardDeviation: number;
  areaid_rawHexSample: string;
  areaid_metadataTag: Record<string, string>;
  neighborstate_primaryMetric: number;
  neighborstate_secondaryMetric: number;
  neighborstate_baselineAverage: number;
  neighborstate_peakObserved: number;
  neighborstate_standardDeviation: number;
  neighborstate_rawHexSample: string;
  neighborstate_metadataTag: Record<string, string>;
  lsatype_primaryMetric: number;
  lsatype_secondaryMetric: number;
  lsatype_baselineAverage: number;
  lsatype_peakObserved: number;
  lsatype_standardDeviation: number;
  lsatype_rawHexSample: string;
  lsatype_metadataTag: Record<string, string>;
  linkcost_primaryMetric: number;
  linkcost_secondaryMetric: number;
  linkcost_baselineAverage: number;
  linkcost_peakObserved: number;
  linkcost_standardDeviation: number;
  linkcost_rawHexSample: string;
  linkcost_metadataTag: Record<string, string>;
  drselectionstatus_primaryMetric: number;
  drselectionstatus_secondaryMetric: number;
  drselectionstatus_baselineAverage: number;
  drselectionstatus_peakObserved: number;
  drselectionstatus_standardDeviation: number;
  drselectionstatus_rawHexSample: string;
  drselectionstatus_metadataTag: Record<string, string>;
  hellointerval_primaryMetric: number;
  hellointerval_secondaryMetric: number;
  hellointerval_baselineAverage: number;
  hellointerval_peakObserved: number;
  hellointerval_standardDeviation: number;
  hellointerval_rawHexSample: string;
  hellointerval_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type OspfLinkStateMetricsFilterV34 = Partial<OspfLinkStateMetricsRecordV34> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface OspfLinkStateMetricsRecordV35 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  routerid_primaryMetric: number;
  routerid_secondaryMetric: number;
  routerid_baselineAverage: number;
  routerid_peakObserved: number;
  routerid_standardDeviation: number;
  routerid_rawHexSample: string;
  routerid_metadataTag: Record<string, string>;
  areaid_primaryMetric: number;
  areaid_secondaryMetric: number;
  areaid_baselineAverage: number;
  areaid_peakObserved: number;
  areaid_standardDeviation: number;
  areaid_rawHexSample: string;
  areaid_metadataTag: Record<string, string>;
  neighborstate_primaryMetric: number;
  neighborstate_secondaryMetric: number;
  neighborstate_baselineAverage: number;
  neighborstate_peakObserved: number;
  neighborstate_standardDeviation: number;
  neighborstate_rawHexSample: string;
  neighborstate_metadataTag: Record<string, string>;
  lsatype_primaryMetric: number;
  lsatype_secondaryMetric: number;
  lsatype_baselineAverage: number;
  lsatype_peakObserved: number;
  lsatype_standardDeviation: number;
  lsatype_rawHexSample: string;
  lsatype_metadataTag: Record<string, string>;
  linkcost_primaryMetric: number;
  linkcost_secondaryMetric: number;
  linkcost_baselineAverage: number;
  linkcost_peakObserved: number;
  linkcost_standardDeviation: number;
  linkcost_rawHexSample: string;
  linkcost_metadataTag: Record<string, string>;
  drselectionstatus_primaryMetric: number;
  drselectionstatus_secondaryMetric: number;
  drselectionstatus_baselineAverage: number;
  drselectionstatus_peakObserved: number;
  drselectionstatus_standardDeviation: number;
  drselectionstatus_rawHexSample: string;
  drselectionstatus_metadataTag: Record<string, string>;
  hellointerval_primaryMetric: number;
  hellointerval_secondaryMetric: number;
  hellointerval_baselineAverage: number;
  hellointerval_peakObserved: number;
  hellointerval_standardDeviation: number;
  hellointerval_rawHexSample: string;
  hellointerval_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type OspfLinkStateMetricsFilterV35 = Partial<OspfLinkStateMetricsRecordV35> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface OspfLinkStateMetricsRecordV36 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  routerid_primaryMetric: number;
  routerid_secondaryMetric: number;
  routerid_baselineAverage: number;
  routerid_peakObserved: number;
  routerid_standardDeviation: number;
  routerid_rawHexSample: string;
  routerid_metadataTag: Record<string, string>;
  areaid_primaryMetric: number;
  areaid_secondaryMetric: number;
  areaid_baselineAverage: number;
  areaid_peakObserved: number;
  areaid_standardDeviation: number;
  areaid_rawHexSample: string;
  areaid_metadataTag: Record<string, string>;
  neighborstate_primaryMetric: number;
  neighborstate_secondaryMetric: number;
  neighborstate_baselineAverage: number;
  neighborstate_peakObserved: number;
  neighborstate_standardDeviation: number;
  neighborstate_rawHexSample: string;
  neighborstate_metadataTag: Record<string, string>;
  lsatype_primaryMetric: number;
  lsatype_secondaryMetric: number;
  lsatype_baselineAverage: number;
  lsatype_peakObserved: number;
  lsatype_standardDeviation: number;
  lsatype_rawHexSample: string;
  lsatype_metadataTag: Record<string, string>;
  linkcost_primaryMetric: number;
  linkcost_secondaryMetric: number;
  linkcost_baselineAverage: number;
  linkcost_peakObserved: number;
  linkcost_standardDeviation: number;
  linkcost_rawHexSample: string;
  linkcost_metadataTag: Record<string, string>;
  drselectionstatus_primaryMetric: number;
  drselectionstatus_secondaryMetric: number;
  drselectionstatus_baselineAverage: number;
  drselectionstatus_peakObserved: number;
  drselectionstatus_standardDeviation: number;
  drselectionstatus_rawHexSample: string;
  drselectionstatus_metadataTag: Record<string, string>;
  hellointerval_primaryMetric: number;
  hellointerval_secondaryMetric: number;
  hellointerval_baselineAverage: number;
  hellointerval_peakObserved: number;
  hellointerval_standardDeviation: number;
  hellointerval_rawHexSample: string;
  hellointerval_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type OspfLinkStateMetricsFilterV36 = Partial<OspfLinkStateMetricsRecordV36> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface OspfLinkStateMetricsRecordV37 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  routerid_primaryMetric: number;
  routerid_secondaryMetric: number;
  routerid_baselineAverage: number;
  routerid_peakObserved: number;
  routerid_standardDeviation: number;
  routerid_rawHexSample: string;
  routerid_metadataTag: Record<string, string>;
  areaid_primaryMetric: number;
  areaid_secondaryMetric: number;
  areaid_baselineAverage: number;
  areaid_peakObserved: number;
  areaid_standardDeviation: number;
  areaid_rawHexSample: string;
  areaid_metadataTag: Record<string, string>;
  neighborstate_primaryMetric: number;
  neighborstate_secondaryMetric: number;
  neighborstate_baselineAverage: number;
  neighborstate_peakObserved: number;
  neighborstate_standardDeviation: number;
  neighborstate_rawHexSample: string;
  neighborstate_metadataTag: Record<string, string>;
  lsatype_primaryMetric: number;
  lsatype_secondaryMetric: number;
  lsatype_baselineAverage: number;
  lsatype_peakObserved: number;
  lsatype_standardDeviation: number;
  lsatype_rawHexSample: string;
  lsatype_metadataTag: Record<string, string>;
  linkcost_primaryMetric: number;
  linkcost_secondaryMetric: number;
  linkcost_baselineAverage: number;
  linkcost_peakObserved: number;
  linkcost_standardDeviation: number;
  linkcost_rawHexSample: string;
  linkcost_metadataTag: Record<string, string>;
  drselectionstatus_primaryMetric: number;
  drselectionstatus_secondaryMetric: number;
  drselectionstatus_baselineAverage: number;
  drselectionstatus_peakObserved: number;
  drselectionstatus_standardDeviation: number;
  drselectionstatus_rawHexSample: string;
  drselectionstatus_metadataTag: Record<string, string>;
  hellointerval_primaryMetric: number;
  hellointerval_secondaryMetric: number;
  hellointerval_baselineAverage: number;
  hellointerval_peakObserved: number;
  hellointerval_standardDeviation: number;
  hellointerval_rawHexSample: string;
  hellointerval_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type OspfLinkStateMetricsFilterV37 = Partial<OspfLinkStateMetricsRecordV37> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface OspfLinkStateMetricsRecordV38 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  routerid_primaryMetric: number;
  routerid_secondaryMetric: number;
  routerid_baselineAverage: number;
  routerid_peakObserved: number;
  routerid_standardDeviation: number;
  routerid_rawHexSample: string;
  routerid_metadataTag: Record<string, string>;
  areaid_primaryMetric: number;
  areaid_secondaryMetric: number;
  areaid_baselineAverage: number;
  areaid_peakObserved: number;
  areaid_standardDeviation: number;
  areaid_rawHexSample: string;
  areaid_metadataTag: Record<string, string>;
  neighborstate_primaryMetric: number;
  neighborstate_secondaryMetric: number;
  neighborstate_baselineAverage: number;
  neighborstate_peakObserved: number;
  neighborstate_standardDeviation: number;
  neighborstate_rawHexSample: string;
  neighborstate_metadataTag: Record<string, string>;
  lsatype_primaryMetric: number;
  lsatype_secondaryMetric: number;
  lsatype_baselineAverage: number;
  lsatype_peakObserved: number;
  lsatype_standardDeviation: number;
  lsatype_rawHexSample: string;
  lsatype_metadataTag: Record<string, string>;
  linkcost_primaryMetric: number;
  linkcost_secondaryMetric: number;
  linkcost_baselineAverage: number;
  linkcost_peakObserved: number;
  linkcost_standardDeviation: number;
  linkcost_rawHexSample: string;
  linkcost_metadataTag: Record<string, string>;
  drselectionstatus_primaryMetric: number;
  drselectionstatus_secondaryMetric: number;
  drselectionstatus_baselineAverage: number;
  drselectionstatus_peakObserved: number;
  drselectionstatus_standardDeviation: number;
  drselectionstatus_rawHexSample: string;
  drselectionstatus_metadataTag: Record<string, string>;
  hellointerval_primaryMetric: number;
  hellointerval_secondaryMetric: number;
  hellointerval_baselineAverage: number;
  hellointerval_peakObserved: number;
  hellointerval_standardDeviation: number;
  hellointerval_rawHexSample: string;
  hellointerval_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type OspfLinkStateMetricsFilterV38 = Partial<OspfLinkStateMetricsRecordV38> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface OspfLinkStateMetricsRecordV39 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  routerid_primaryMetric: number;
  routerid_secondaryMetric: number;
  routerid_baselineAverage: number;
  routerid_peakObserved: number;
  routerid_standardDeviation: number;
  routerid_rawHexSample: string;
  routerid_metadataTag: Record<string, string>;
  areaid_primaryMetric: number;
  areaid_secondaryMetric: number;
  areaid_baselineAverage: number;
  areaid_peakObserved: number;
  areaid_standardDeviation: number;
  areaid_rawHexSample: string;
  areaid_metadataTag: Record<string, string>;
  neighborstate_primaryMetric: number;
  neighborstate_secondaryMetric: number;
  neighborstate_baselineAverage: number;
  neighborstate_peakObserved: number;
  neighborstate_standardDeviation: number;
  neighborstate_rawHexSample: string;
  neighborstate_metadataTag: Record<string, string>;
  lsatype_primaryMetric: number;
  lsatype_secondaryMetric: number;
  lsatype_baselineAverage: number;
  lsatype_peakObserved: number;
  lsatype_standardDeviation: number;
  lsatype_rawHexSample: string;
  lsatype_metadataTag: Record<string, string>;
  linkcost_primaryMetric: number;
  linkcost_secondaryMetric: number;
  linkcost_baselineAverage: number;
  linkcost_peakObserved: number;
  linkcost_standardDeviation: number;
  linkcost_rawHexSample: string;
  linkcost_metadataTag: Record<string, string>;
  drselectionstatus_primaryMetric: number;
  drselectionstatus_secondaryMetric: number;
  drselectionstatus_baselineAverage: number;
  drselectionstatus_peakObserved: number;
  drselectionstatus_standardDeviation: number;
  drselectionstatus_rawHexSample: string;
  drselectionstatus_metadataTag: Record<string, string>;
  hellointerval_primaryMetric: number;
  hellointerval_secondaryMetric: number;
  hellointerval_baselineAverage: number;
  hellointerval_peakObserved: number;
  hellointerval_standardDeviation: number;
  hellointerval_rawHexSample: string;
  hellointerval_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type OspfLinkStateMetricsFilterV39 = Partial<OspfLinkStateMetricsRecordV39> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface OspfLinkStateMetricsRecordV40 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  routerid_primaryMetric: number;
  routerid_secondaryMetric: number;
  routerid_baselineAverage: number;
  routerid_peakObserved: number;
  routerid_standardDeviation: number;
  routerid_rawHexSample: string;
  routerid_metadataTag: Record<string, string>;
  areaid_primaryMetric: number;
  areaid_secondaryMetric: number;
  areaid_baselineAverage: number;
  areaid_peakObserved: number;
  areaid_standardDeviation: number;
  areaid_rawHexSample: string;
  areaid_metadataTag: Record<string, string>;
  neighborstate_primaryMetric: number;
  neighborstate_secondaryMetric: number;
  neighborstate_baselineAverage: number;
  neighborstate_peakObserved: number;
  neighborstate_standardDeviation: number;
  neighborstate_rawHexSample: string;
  neighborstate_metadataTag: Record<string, string>;
  lsatype_primaryMetric: number;
  lsatype_secondaryMetric: number;
  lsatype_baselineAverage: number;
  lsatype_peakObserved: number;
  lsatype_standardDeviation: number;
  lsatype_rawHexSample: string;
  lsatype_metadataTag: Record<string, string>;
  linkcost_primaryMetric: number;
  linkcost_secondaryMetric: number;
  linkcost_baselineAverage: number;
  linkcost_peakObserved: number;
  linkcost_standardDeviation: number;
  linkcost_rawHexSample: string;
  linkcost_metadataTag: Record<string, string>;
  drselectionstatus_primaryMetric: number;
  drselectionstatus_secondaryMetric: number;
  drselectionstatus_baselineAverage: number;
  drselectionstatus_peakObserved: number;
  drselectionstatus_standardDeviation: number;
  drselectionstatus_rawHexSample: string;
  drselectionstatus_metadataTag: Record<string, string>;
  hellointerval_primaryMetric: number;
  hellointerval_secondaryMetric: number;
  hellointerval_baselineAverage: number;
  hellointerval_peakObserved: number;
  hellointerval_standardDeviation: number;
  hellointerval_rawHexSample: string;
  hellointerval_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type OspfLinkStateMetricsFilterV40 = Partial<OspfLinkStateMetricsRecordV40> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};
