/**
 * Enterprise Telecommunications Protocol Specification: Juniper Junos Routing Engine & PFE Interface Telemetry MIB
 * Module: @geonet/types/telecom/snmp_juniper_junos
 * Standard Compliance: 3GPP TS 38.401, IETF RFC Standards, ITU-T G.8032
 */

export interface JuniperJunosRoutingEngine&PFEInterfaceTelemetryMIBConfig {
  samplingIntervalMs: number;
  collectionEnabled: boolean;
  highWatermarkThreshold: number;
  lowWatermarkThreshold: number;
  retryAttempts: number;
  timeoutMs: number;
}

export interface SnmpJuniperJunosRecordV1 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  jnxboxanatomy_primaryMetric: number;
  jnxboxanatomy_secondaryMetric: number;
  jnxboxanatomy_baselineAverage: number;
  jnxboxanatomy_peakObserved: number;
  jnxboxanatomy_standardDeviation: number;
  jnxboxanatomy_rawHexSample: string;
  jnxboxanatomy_metadataTag: Record<string, string>;
  jnxoperatingcpu_primaryMetric: number;
  jnxoperatingcpu_secondaryMetric: number;
  jnxoperatingcpu_baselineAverage: number;
  jnxoperatingcpu_peakObserved: number;
  jnxoperatingcpu_standardDeviation: number;
  jnxoperatingcpu_rawHexSample: string;
  jnxoperatingcpu_metadataTag: Record<string, string>;
  jnxoperatingbuffer_primaryMetric: number;
  jnxoperatingbuffer_secondaryMetric: number;
  jnxoperatingbuffer_baselineAverage: number;
  jnxoperatingbuffer_peakObserved: number;
  jnxoperatingbuffer_standardDeviation: number;
  jnxoperatingbuffer_rawHexSample: string;
  jnxoperatingbuffer_metadataTag: Record<string, string>;
  jnxcosqueuedroppkts_primaryMetric: number;
  jnxcosqueuedroppkts_secondaryMetric: number;
  jnxcosqueuedroppkts_baselineAverage: number;
  jnxcosqueuedroppkts_peakObserved: number;
  jnxcosqueuedroppkts_standardDeviation: number;
  jnxcosqueuedroppkts_rawHexSample: string;
  jnxcosqueuedroppkts_metadataTag: Record<string, string>;
  jnxbgpm2peerstatus_primaryMetric: number;
  jnxbgpm2peerstatus_secondaryMetric: number;
  jnxbgpm2peerstatus_baselineAverage: number;
  jnxbgpm2peerstatus_peakObserved: number;
  jnxbgpm2peerstatus_standardDeviation: number;
  jnxbgpm2peerstatus_rawHexSample: string;
  jnxbgpm2peerstatus_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type SnmpJuniperJunosFilterV1 = Partial<SnmpJuniperJunosRecordV1> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface SnmpJuniperJunosRecordV2 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  jnxboxanatomy_primaryMetric: number;
  jnxboxanatomy_secondaryMetric: number;
  jnxboxanatomy_baselineAverage: number;
  jnxboxanatomy_peakObserved: number;
  jnxboxanatomy_standardDeviation: number;
  jnxboxanatomy_rawHexSample: string;
  jnxboxanatomy_metadataTag: Record<string, string>;
  jnxoperatingcpu_primaryMetric: number;
  jnxoperatingcpu_secondaryMetric: number;
  jnxoperatingcpu_baselineAverage: number;
  jnxoperatingcpu_peakObserved: number;
  jnxoperatingcpu_standardDeviation: number;
  jnxoperatingcpu_rawHexSample: string;
  jnxoperatingcpu_metadataTag: Record<string, string>;
  jnxoperatingbuffer_primaryMetric: number;
  jnxoperatingbuffer_secondaryMetric: number;
  jnxoperatingbuffer_baselineAverage: number;
  jnxoperatingbuffer_peakObserved: number;
  jnxoperatingbuffer_standardDeviation: number;
  jnxoperatingbuffer_rawHexSample: string;
  jnxoperatingbuffer_metadataTag: Record<string, string>;
  jnxcosqueuedroppkts_primaryMetric: number;
  jnxcosqueuedroppkts_secondaryMetric: number;
  jnxcosqueuedroppkts_baselineAverage: number;
  jnxcosqueuedroppkts_peakObserved: number;
  jnxcosqueuedroppkts_standardDeviation: number;
  jnxcosqueuedroppkts_rawHexSample: string;
  jnxcosqueuedroppkts_metadataTag: Record<string, string>;
  jnxbgpm2peerstatus_primaryMetric: number;
  jnxbgpm2peerstatus_secondaryMetric: number;
  jnxbgpm2peerstatus_baselineAverage: number;
  jnxbgpm2peerstatus_peakObserved: number;
  jnxbgpm2peerstatus_standardDeviation: number;
  jnxbgpm2peerstatus_rawHexSample: string;
  jnxbgpm2peerstatus_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type SnmpJuniperJunosFilterV2 = Partial<SnmpJuniperJunosRecordV2> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface SnmpJuniperJunosRecordV3 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  jnxboxanatomy_primaryMetric: number;
  jnxboxanatomy_secondaryMetric: number;
  jnxboxanatomy_baselineAverage: number;
  jnxboxanatomy_peakObserved: number;
  jnxboxanatomy_standardDeviation: number;
  jnxboxanatomy_rawHexSample: string;
  jnxboxanatomy_metadataTag: Record<string, string>;
  jnxoperatingcpu_primaryMetric: number;
  jnxoperatingcpu_secondaryMetric: number;
  jnxoperatingcpu_baselineAverage: number;
  jnxoperatingcpu_peakObserved: number;
  jnxoperatingcpu_standardDeviation: number;
  jnxoperatingcpu_rawHexSample: string;
  jnxoperatingcpu_metadataTag: Record<string, string>;
  jnxoperatingbuffer_primaryMetric: number;
  jnxoperatingbuffer_secondaryMetric: number;
  jnxoperatingbuffer_baselineAverage: number;
  jnxoperatingbuffer_peakObserved: number;
  jnxoperatingbuffer_standardDeviation: number;
  jnxoperatingbuffer_rawHexSample: string;
  jnxoperatingbuffer_metadataTag: Record<string, string>;
  jnxcosqueuedroppkts_primaryMetric: number;
  jnxcosqueuedroppkts_secondaryMetric: number;
  jnxcosqueuedroppkts_baselineAverage: number;
  jnxcosqueuedroppkts_peakObserved: number;
  jnxcosqueuedroppkts_standardDeviation: number;
  jnxcosqueuedroppkts_rawHexSample: string;
  jnxcosqueuedroppkts_metadataTag: Record<string, string>;
  jnxbgpm2peerstatus_primaryMetric: number;
  jnxbgpm2peerstatus_secondaryMetric: number;
  jnxbgpm2peerstatus_baselineAverage: number;
  jnxbgpm2peerstatus_peakObserved: number;
  jnxbgpm2peerstatus_standardDeviation: number;
  jnxbgpm2peerstatus_rawHexSample: string;
  jnxbgpm2peerstatus_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type SnmpJuniperJunosFilterV3 = Partial<SnmpJuniperJunosRecordV3> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface SnmpJuniperJunosRecordV4 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  jnxboxanatomy_primaryMetric: number;
  jnxboxanatomy_secondaryMetric: number;
  jnxboxanatomy_baselineAverage: number;
  jnxboxanatomy_peakObserved: number;
  jnxboxanatomy_standardDeviation: number;
  jnxboxanatomy_rawHexSample: string;
  jnxboxanatomy_metadataTag: Record<string, string>;
  jnxoperatingcpu_primaryMetric: number;
  jnxoperatingcpu_secondaryMetric: number;
  jnxoperatingcpu_baselineAverage: number;
  jnxoperatingcpu_peakObserved: number;
  jnxoperatingcpu_standardDeviation: number;
  jnxoperatingcpu_rawHexSample: string;
  jnxoperatingcpu_metadataTag: Record<string, string>;
  jnxoperatingbuffer_primaryMetric: number;
  jnxoperatingbuffer_secondaryMetric: number;
  jnxoperatingbuffer_baselineAverage: number;
  jnxoperatingbuffer_peakObserved: number;
  jnxoperatingbuffer_standardDeviation: number;
  jnxoperatingbuffer_rawHexSample: string;
  jnxoperatingbuffer_metadataTag: Record<string, string>;
  jnxcosqueuedroppkts_primaryMetric: number;
  jnxcosqueuedroppkts_secondaryMetric: number;
  jnxcosqueuedroppkts_baselineAverage: number;
  jnxcosqueuedroppkts_peakObserved: number;
  jnxcosqueuedroppkts_standardDeviation: number;
  jnxcosqueuedroppkts_rawHexSample: string;
  jnxcosqueuedroppkts_metadataTag: Record<string, string>;
  jnxbgpm2peerstatus_primaryMetric: number;
  jnxbgpm2peerstatus_secondaryMetric: number;
  jnxbgpm2peerstatus_baselineAverage: number;
  jnxbgpm2peerstatus_peakObserved: number;
  jnxbgpm2peerstatus_standardDeviation: number;
  jnxbgpm2peerstatus_rawHexSample: string;
  jnxbgpm2peerstatus_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type SnmpJuniperJunosFilterV4 = Partial<SnmpJuniperJunosRecordV4> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface SnmpJuniperJunosRecordV5 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  jnxboxanatomy_primaryMetric: number;
  jnxboxanatomy_secondaryMetric: number;
  jnxboxanatomy_baselineAverage: number;
  jnxboxanatomy_peakObserved: number;
  jnxboxanatomy_standardDeviation: number;
  jnxboxanatomy_rawHexSample: string;
  jnxboxanatomy_metadataTag: Record<string, string>;
  jnxoperatingcpu_primaryMetric: number;
  jnxoperatingcpu_secondaryMetric: number;
  jnxoperatingcpu_baselineAverage: number;
  jnxoperatingcpu_peakObserved: number;
  jnxoperatingcpu_standardDeviation: number;
  jnxoperatingcpu_rawHexSample: string;
  jnxoperatingcpu_metadataTag: Record<string, string>;
  jnxoperatingbuffer_primaryMetric: number;
  jnxoperatingbuffer_secondaryMetric: number;
  jnxoperatingbuffer_baselineAverage: number;
  jnxoperatingbuffer_peakObserved: number;
  jnxoperatingbuffer_standardDeviation: number;
  jnxoperatingbuffer_rawHexSample: string;
  jnxoperatingbuffer_metadataTag: Record<string, string>;
  jnxcosqueuedroppkts_primaryMetric: number;
  jnxcosqueuedroppkts_secondaryMetric: number;
  jnxcosqueuedroppkts_baselineAverage: number;
  jnxcosqueuedroppkts_peakObserved: number;
  jnxcosqueuedroppkts_standardDeviation: number;
  jnxcosqueuedroppkts_rawHexSample: string;
  jnxcosqueuedroppkts_metadataTag: Record<string, string>;
  jnxbgpm2peerstatus_primaryMetric: number;
  jnxbgpm2peerstatus_secondaryMetric: number;
  jnxbgpm2peerstatus_baselineAverage: number;
  jnxbgpm2peerstatus_peakObserved: number;
  jnxbgpm2peerstatus_standardDeviation: number;
  jnxbgpm2peerstatus_rawHexSample: string;
  jnxbgpm2peerstatus_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type SnmpJuniperJunosFilterV5 = Partial<SnmpJuniperJunosRecordV5> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface SnmpJuniperJunosRecordV6 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  jnxboxanatomy_primaryMetric: number;
  jnxboxanatomy_secondaryMetric: number;
  jnxboxanatomy_baselineAverage: number;
  jnxboxanatomy_peakObserved: number;
  jnxboxanatomy_standardDeviation: number;
  jnxboxanatomy_rawHexSample: string;
  jnxboxanatomy_metadataTag: Record<string, string>;
  jnxoperatingcpu_primaryMetric: number;
  jnxoperatingcpu_secondaryMetric: number;
  jnxoperatingcpu_baselineAverage: number;
  jnxoperatingcpu_peakObserved: number;
  jnxoperatingcpu_standardDeviation: number;
  jnxoperatingcpu_rawHexSample: string;
  jnxoperatingcpu_metadataTag: Record<string, string>;
  jnxoperatingbuffer_primaryMetric: number;
  jnxoperatingbuffer_secondaryMetric: number;
  jnxoperatingbuffer_baselineAverage: number;
  jnxoperatingbuffer_peakObserved: number;
  jnxoperatingbuffer_standardDeviation: number;
  jnxoperatingbuffer_rawHexSample: string;
  jnxoperatingbuffer_metadataTag: Record<string, string>;
  jnxcosqueuedroppkts_primaryMetric: number;
  jnxcosqueuedroppkts_secondaryMetric: number;
  jnxcosqueuedroppkts_baselineAverage: number;
  jnxcosqueuedroppkts_peakObserved: number;
  jnxcosqueuedroppkts_standardDeviation: number;
  jnxcosqueuedroppkts_rawHexSample: string;
  jnxcosqueuedroppkts_metadataTag: Record<string, string>;
  jnxbgpm2peerstatus_primaryMetric: number;
  jnxbgpm2peerstatus_secondaryMetric: number;
  jnxbgpm2peerstatus_baselineAverage: number;
  jnxbgpm2peerstatus_peakObserved: number;
  jnxbgpm2peerstatus_standardDeviation: number;
  jnxbgpm2peerstatus_rawHexSample: string;
  jnxbgpm2peerstatus_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type SnmpJuniperJunosFilterV6 = Partial<SnmpJuniperJunosRecordV6> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface SnmpJuniperJunosRecordV7 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  jnxboxanatomy_primaryMetric: number;
  jnxboxanatomy_secondaryMetric: number;
  jnxboxanatomy_baselineAverage: number;
  jnxboxanatomy_peakObserved: number;
  jnxboxanatomy_standardDeviation: number;
  jnxboxanatomy_rawHexSample: string;
  jnxboxanatomy_metadataTag: Record<string, string>;
  jnxoperatingcpu_primaryMetric: number;
  jnxoperatingcpu_secondaryMetric: number;
  jnxoperatingcpu_baselineAverage: number;
  jnxoperatingcpu_peakObserved: number;
  jnxoperatingcpu_standardDeviation: number;
  jnxoperatingcpu_rawHexSample: string;
  jnxoperatingcpu_metadataTag: Record<string, string>;
  jnxoperatingbuffer_primaryMetric: number;
  jnxoperatingbuffer_secondaryMetric: number;
  jnxoperatingbuffer_baselineAverage: number;
  jnxoperatingbuffer_peakObserved: number;
  jnxoperatingbuffer_standardDeviation: number;
  jnxoperatingbuffer_rawHexSample: string;
  jnxoperatingbuffer_metadataTag: Record<string, string>;
  jnxcosqueuedroppkts_primaryMetric: number;
  jnxcosqueuedroppkts_secondaryMetric: number;
  jnxcosqueuedroppkts_baselineAverage: number;
  jnxcosqueuedroppkts_peakObserved: number;
  jnxcosqueuedroppkts_standardDeviation: number;
  jnxcosqueuedroppkts_rawHexSample: string;
  jnxcosqueuedroppkts_metadataTag: Record<string, string>;
  jnxbgpm2peerstatus_primaryMetric: number;
  jnxbgpm2peerstatus_secondaryMetric: number;
  jnxbgpm2peerstatus_baselineAverage: number;
  jnxbgpm2peerstatus_peakObserved: number;
  jnxbgpm2peerstatus_standardDeviation: number;
  jnxbgpm2peerstatus_rawHexSample: string;
  jnxbgpm2peerstatus_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type SnmpJuniperJunosFilterV7 = Partial<SnmpJuniperJunosRecordV7> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface SnmpJuniperJunosRecordV8 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  jnxboxanatomy_primaryMetric: number;
  jnxboxanatomy_secondaryMetric: number;
  jnxboxanatomy_baselineAverage: number;
  jnxboxanatomy_peakObserved: number;
  jnxboxanatomy_standardDeviation: number;
  jnxboxanatomy_rawHexSample: string;
  jnxboxanatomy_metadataTag: Record<string, string>;
  jnxoperatingcpu_primaryMetric: number;
  jnxoperatingcpu_secondaryMetric: number;
  jnxoperatingcpu_baselineAverage: number;
  jnxoperatingcpu_peakObserved: number;
  jnxoperatingcpu_standardDeviation: number;
  jnxoperatingcpu_rawHexSample: string;
  jnxoperatingcpu_metadataTag: Record<string, string>;
  jnxoperatingbuffer_primaryMetric: number;
  jnxoperatingbuffer_secondaryMetric: number;
  jnxoperatingbuffer_baselineAverage: number;
  jnxoperatingbuffer_peakObserved: number;
  jnxoperatingbuffer_standardDeviation: number;
  jnxoperatingbuffer_rawHexSample: string;
  jnxoperatingbuffer_metadataTag: Record<string, string>;
  jnxcosqueuedroppkts_primaryMetric: number;
  jnxcosqueuedroppkts_secondaryMetric: number;
  jnxcosqueuedroppkts_baselineAverage: number;
  jnxcosqueuedroppkts_peakObserved: number;
  jnxcosqueuedroppkts_standardDeviation: number;
  jnxcosqueuedroppkts_rawHexSample: string;
  jnxcosqueuedroppkts_metadataTag: Record<string, string>;
  jnxbgpm2peerstatus_primaryMetric: number;
  jnxbgpm2peerstatus_secondaryMetric: number;
  jnxbgpm2peerstatus_baselineAverage: number;
  jnxbgpm2peerstatus_peakObserved: number;
  jnxbgpm2peerstatus_standardDeviation: number;
  jnxbgpm2peerstatus_rawHexSample: string;
  jnxbgpm2peerstatus_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type SnmpJuniperJunosFilterV8 = Partial<SnmpJuniperJunosRecordV8> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface SnmpJuniperJunosRecordV9 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  jnxboxanatomy_primaryMetric: number;
  jnxboxanatomy_secondaryMetric: number;
  jnxboxanatomy_baselineAverage: number;
  jnxboxanatomy_peakObserved: number;
  jnxboxanatomy_standardDeviation: number;
  jnxboxanatomy_rawHexSample: string;
  jnxboxanatomy_metadataTag: Record<string, string>;
  jnxoperatingcpu_primaryMetric: number;
  jnxoperatingcpu_secondaryMetric: number;
  jnxoperatingcpu_baselineAverage: number;
  jnxoperatingcpu_peakObserved: number;
  jnxoperatingcpu_standardDeviation: number;
  jnxoperatingcpu_rawHexSample: string;
  jnxoperatingcpu_metadataTag: Record<string, string>;
  jnxoperatingbuffer_primaryMetric: number;
  jnxoperatingbuffer_secondaryMetric: number;
  jnxoperatingbuffer_baselineAverage: number;
  jnxoperatingbuffer_peakObserved: number;
  jnxoperatingbuffer_standardDeviation: number;
  jnxoperatingbuffer_rawHexSample: string;
  jnxoperatingbuffer_metadataTag: Record<string, string>;
  jnxcosqueuedroppkts_primaryMetric: number;
  jnxcosqueuedroppkts_secondaryMetric: number;
  jnxcosqueuedroppkts_baselineAverage: number;
  jnxcosqueuedroppkts_peakObserved: number;
  jnxcosqueuedroppkts_standardDeviation: number;
  jnxcosqueuedroppkts_rawHexSample: string;
  jnxcosqueuedroppkts_metadataTag: Record<string, string>;
  jnxbgpm2peerstatus_primaryMetric: number;
  jnxbgpm2peerstatus_secondaryMetric: number;
  jnxbgpm2peerstatus_baselineAverage: number;
  jnxbgpm2peerstatus_peakObserved: number;
  jnxbgpm2peerstatus_standardDeviation: number;
  jnxbgpm2peerstatus_rawHexSample: string;
  jnxbgpm2peerstatus_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type SnmpJuniperJunosFilterV9 = Partial<SnmpJuniperJunosRecordV9> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface SnmpJuniperJunosRecordV10 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  jnxboxanatomy_primaryMetric: number;
  jnxboxanatomy_secondaryMetric: number;
  jnxboxanatomy_baselineAverage: number;
  jnxboxanatomy_peakObserved: number;
  jnxboxanatomy_standardDeviation: number;
  jnxboxanatomy_rawHexSample: string;
  jnxboxanatomy_metadataTag: Record<string, string>;
  jnxoperatingcpu_primaryMetric: number;
  jnxoperatingcpu_secondaryMetric: number;
  jnxoperatingcpu_baselineAverage: number;
  jnxoperatingcpu_peakObserved: number;
  jnxoperatingcpu_standardDeviation: number;
  jnxoperatingcpu_rawHexSample: string;
  jnxoperatingcpu_metadataTag: Record<string, string>;
  jnxoperatingbuffer_primaryMetric: number;
  jnxoperatingbuffer_secondaryMetric: number;
  jnxoperatingbuffer_baselineAverage: number;
  jnxoperatingbuffer_peakObserved: number;
  jnxoperatingbuffer_standardDeviation: number;
  jnxoperatingbuffer_rawHexSample: string;
  jnxoperatingbuffer_metadataTag: Record<string, string>;
  jnxcosqueuedroppkts_primaryMetric: number;
  jnxcosqueuedroppkts_secondaryMetric: number;
  jnxcosqueuedroppkts_baselineAverage: number;
  jnxcosqueuedroppkts_peakObserved: number;
  jnxcosqueuedroppkts_standardDeviation: number;
  jnxcosqueuedroppkts_rawHexSample: string;
  jnxcosqueuedroppkts_metadataTag: Record<string, string>;
  jnxbgpm2peerstatus_primaryMetric: number;
  jnxbgpm2peerstatus_secondaryMetric: number;
  jnxbgpm2peerstatus_baselineAverage: number;
  jnxbgpm2peerstatus_peakObserved: number;
  jnxbgpm2peerstatus_standardDeviation: number;
  jnxbgpm2peerstatus_rawHexSample: string;
  jnxbgpm2peerstatus_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type SnmpJuniperJunosFilterV10 = Partial<SnmpJuniperJunosRecordV10> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface SnmpJuniperJunosRecordV11 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  jnxboxanatomy_primaryMetric: number;
  jnxboxanatomy_secondaryMetric: number;
  jnxboxanatomy_baselineAverage: number;
  jnxboxanatomy_peakObserved: number;
  jnxboxanatomy_standardDeviation: number;
  jnxboxanatomy_rawHexSample: string;
  jnxboxanatomy_metadataTag: Record<string, string>;
  jnxoperatingcpu_primaryMetric: number;
  jnxoperatingcpu_secondaryMetric: number;
  jnxoperatingcpu_baselineAverage: number;
  jnxoperatingcpu_peakObserved: number;
  jnxoperatingcpu_standardDeviation: number;
  jnxoperatingcpu_rawHexSample: string;
  jnxoperatingcpu_metadataTag: Record<string, string>;
  jnxoperatingbuffer_primaryMetric: number;
  jnxoperatingbuffer_secondaryMetric: number;
  jnxoperatingbuffer_baselineAverage: number;
  jnxoperatingbuffer_peakObserved: number;
  jnxoperatingbuffer_standardDeviation: number;
  jnxoperatingbuffer_rawHexSample: string;
  jnxoperatingbuffer_metadataTag: Record<string, string>;
  jnxcosqueuedroppkts_primaryMetric: number;
  jnxcosqueuedroppkts_secondaryMetric: number;
  jnxcosqueuedroppkts_baselineAverage: number;
  jnxcosqueuedroppkts_peakObserved: number;
  jnxcosqueuedroppkts_standardDeviation: number;
  jnxcosqueuedroppkts_rawHexSample: string;
  jnxcosqueuedroppkts_metadataTag: Record<string, string>;
  jnxbgpm2peerstatus_primaryMetric: number;
  jnxbgpm2peerstatus_secondaryMetric: number;
  jnxbgpm2peerstatus_baselineAverage: number;
  jnxbgpm2peerstatus_peakObserved: number;
  jnxbgpm2peerstatus_standardDeviation: number;
  jnxbgpm2peerstatus_rawHexSample: string;
  jnxbgpm2peerstatus_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type SnmpJuniperJunosFilterV11 = Partial<SnmpJuniperJunosRecordV11> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface SnmpJuniperJunosRecordV12 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  jnxboxanatomy_primaryMetric: number;
  jnxboxanatomy_secondaryMetric: number;
  jnxboxanatomy_baselineAverage: number;
  jnxboxanatomy_peakObserved: number;
  jnxboxanatomy_standardDeviation: number;
  jnxboxanatomy_rawHexSample: string;
  jnxboxanatomy_metadataTag: Record<string, string>;
  jnxoperatingcpu_primaryMetric: number;
  jnxoperatingcpu_secondaryMetric: number;
  jnxoperatingcpu_baselineAverage: number;
  jnxoperatingcpu_peakObserved: number;
  jnxoperatingcpu_standardDeviation: number;
  jnxoperatingcpu_rawHexSample: string;
  jnxoperatingcpu_metadataTag: Record<string, string>;
  jnxoperatingbuffer_primaryMetric: number;
  jnxoperatingbuffer_secondaryMetric: number;
  jnxoperatingbuffer_baselineAverage: number;
  jnxoperatingbuffer_peakObserved: number;
  jnxoperatingbuffer_standardDeviation: number;
  jnxoperatingbuffer_rawHexSample: string;
  jnxoperatingbuffer_metadataTag: Record<string, string>;
  jnxcosqueuedroppkts_primaryMetric: number;
  jnxcosqueuedroppkts_secondaryMetric: number;
  jnxcosqueuedroppkts_baselineAverage: number;
  jnxcosqueuedroppkts_peakObserved: number;
  jnxcosqueuedroppkts_standardDeviation: number;
  jnxcosqueuedroppkts_rawHexSample: string;
  jnxcosqueuedroppkts_metadataTag: Record<string, string>;
  jnxbgpm2peerstatus_primaryMetric: number;
  jnxbgpm2peerstatus_secondaryMetric: number;
  jnxbgpm2peerstatus_baselineAverage: number;
  jnxbgpm2peerstatus_peakObserved: number;
  jnxbgpm2peerstatus_standardDeviation: number;
  jnxbgpm2peerstatus_rawHexSample: string;
  jnxbgpm2peerstatus_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type SnmpJuniperJunosFilterV12 = Partial<SnmpJuniperJunosRecordV12> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface SnmpJuniperJunosRecordV13 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  jnxboxanatomy_primaryMetric: number;
  jnxboxanatomy_secondaryMetric: number;
  jnxboxanatomy_baselineAverage: number;
  jnxboxanatomy_peakObserved: number;
  jnxboxanatomy_standardDeviation: number;
  jnxboxanatomy_rawHexSample: string;
  jnxboxanatomy_metadataTag: Record<string, string>;
  jnxoperatingcpu_primaryMetric: number;
  jnxoperatingcpu_secondaryMetric: number;
  jnxoperatingcpu_baselineAverage: number;
  jnxoperatingcpu_peakObserved: number;
  jnxoperatingcpu_standardDeviation: number;
  jnxoperatingcpu_rawHexSample: string;
  jnxoperatingcpu_metadataTag: Record<string, string>;
  jnxoperatingbuffer_primaryMetric: number;
  jnxoperatingbuffer_secondaryMetric: number;
  jnxoperatingbuffer_baselineAverage: number;
  jnxoperatingbuffer_peakObserved: number;
  jnxoperatingbuffer_standardDeviation: number;
  jnxoperatingbuffer_rawHexSample: string;
  jnxoperatingbuffer_metadataTag: Record<string, string>;
  jnxcosqueuedroppkts_primaryMetric: number;
  jnxcosqueuedroppkts_secondaryMetric: number;
  jnxcosqueuedroppkts_baselineAverage: number;
  jnxcosqueuedroppkts_peakObserved: number;
  jnxcosqueuedroppkts_standardDeviation: number;
  jnxcosqueuedroppkts_rawHexSample: string;
  jnxcosqueuedroppkts_metadataTag: Record<string, string>;
  jnxbgpm2peerstatus_primaryMetric: number;
  jnxbgpm2peerstatus_secondaryMetric: number;
  jnxbgpm2peerstatus_baselineAverage: number;
  jnxbgpm2peerstatus_peakObserved: number;
  jnxbgpm2peerstatus_standardDeviation: number;
  jnxbgpm2peerstatus_rawHexSample: string;
  jnxbgpm2peerstatus_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type SnmpJuniperJunosFilterV13 = Partial<SnmpJuniperJunosRecordV13> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface SnmpJuniperJunosRecordV14 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  jnxboxanatomy_primaryMetric: number;
  jnxboxanatomy_secondaryMetric: number;
  jnxboxanatomy_baselineAverage: number;
  jnxboxanatomy_peakObserved: number;
  jnxboxanatomy_standardDeviation: number;
  jnxboxanatomy_rawHexSample: string;
  jnxboxanatomy_metadataTag: Record<string, string>;
  jnxoperatingcpu_primaryMetric: number;
  jnxoperatingcpu_secondaryMetric: number;
  jnxoperatingcpu_baselineAverage: number;
  jnxoperatingcpu_peakObserved: number;
  jnxoperatingcpu_standardDeviation: number;
  jnxoperatingcpu_rawHexSample: string;
  jnxoperatingcpu_metadataTag: Record<string, string>;
  jnxoperatingbuffer_primaryMetric: number;
  jnxoperatingbuffer_secondaryMetric: number;
  jnxoperatingbuffer_baselineAverage: number;
  jnxoperatingbuffer_peakObserved: number;
  jnxoperatingbuffer_standardDeviation: number;
  jnxoperatingbuffer_rawHexSample: string;
  jnxoperatingbuffer_metadataTag: Record<string, string>;
  jnxcosqueuedroppkts_primaryMetric: number;
  jnxcosqueuedroppkts_secondaryMetric: number;
  jnxcosqueuedroppkts_baselineAverage: number;
  jnxcosqueuedroppkts_peakObserved: number;
  jnxcosqueuedroppkts_standardDeviation: number;
  jnxcosqueuedroppkts_rawHexSample: string;
  jnxcosqueuedroppkts_metadataTag: Record<string, string>;
  jnxbgpm2peerstatus_primaryMetric: number;
  jnxbgpm2peerstatus_secondaryMetric: number;
  jnxbgpm2peerstatus_baselineAverage: number;
  jnxbgpm2peerstatus_peakObserved: number;
  jnxbgpm2peerstatus_standardDeviation: number;
  jnxbgpm2peerstatus_rawHexSample: string;
  jnxbgpm2peerstatus_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type SnmpJuniperJunosFilterV14 = Partial<SnmpJuniperJunosRecordV14> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface SnmpJuniperJunosRecordV15 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  jnxboxanatomy_primaryMetric: number;
  jnxboxanatomy_secondaryMetric: number;
  jnxboxanatomy_baselineAverage: number;
  jnxboxanatomy_peakObserved: number;
  jnxboxanatomy_standardDeviation: number;
  jnxboxanatomy_rawHexSample: string;
  jnxboxanatomy_metadataTag: Record<string, string>;
  jnxoperatingcpu_primaryMetric: number;
  jnxoperatingcpu_secondaryMetric: number;
  jnxoperatingcpu_baselineAverage: number;
  jnxoperatingcpu_peakObserved: number;
  jnxoperatingcpu_standardDeviation: number;
  jnxoperatingcpu_rawHexSample: string;
  jnxoperatingcpu_metadataTag: Record<string, string>;
  jnxoperatingbuffer_primaryMetric: number;
  jnxoperatingbuffer_secondaryMetric: number;
  jnxoperatingbuffer_baselineAverage: number;
  jnxoperatingbuffer_peakObserved: number;
  jnxoperatingbuffer_standardDeviation: number;
  jnxoperatingbuffer_rawHexSample: string;
  jnxoperatingbuffer_metadataTag: Record<string, string>;
  jnxcosqueuedroppkts_primaryMetric: number;
  jnxcosqueuedroppkts_secondaryMetric: number;
  jnxcosqueuedroppkts_baselineAverage: number;
  jnxcosqueuedroppkts_peakObserved: number;
  jnxcosqueuedroppkts_standardDeviation: number;
  jnxcosqueuedroppkts_rawHexSample: string;
  jnxcosqueuedroppkts_metadataTag: Record<string, string>;
  jnxbgpm2peerstatus_primaryMetric: number;
  jnxbgpm2peerstatus_secondaryMetric: number;
  jnxbgpm2peerstatus_baselineAverage: number;
  jnxbgpm2peerstatus_peakObserved: number;
  jnxbgpm2peerstatus_standardDeviation: number;
  jnxbgpm2peerstatus_rawHexSample: string;
  jnxbgpm2peerstatus_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type SnmpJuniperJunosFilterV15 = Partial<SnmpJuniperJunosRecordV15> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface SnmpJuniperJunosRecordV16 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  jnxboxanatomy_primaryMetric: number;
  jnxboxanatomy_secondaryMetric: number;
  jnxboxanatomy_baselineAverage: number;
  jnxboxanatomy_peakObserved: number;
  jnxboxanatomy_standardDeviation: number;
  jnxboxanatomy_rawHexSample: string;
  jnxboxanatomy_metadataTag: Record<string, string>;
  jnxoperatingcpu_primaryMetric: number;
  jnxoperatingcpu_secondaryMetric: number;
  jnxoperatingcpu_baselineAverage: number;
  jnxoperatingcpu_peakObserved: number;
  jnxoperatingcpu_standardDeviation: number;
  jnxoperatingcpu_rawHexSample: string;
  jnxoperatingcpu_metadataTag: Record<string, string>;
  jnxoperatingbuffer_primaryMetric: number;
  jnxoperatingbuffer_secondaryMetric: number;
  jnxoperatingbuffer_baselineAverage: number;
  jnxoperatingbuffer_peakObserved: number;
  jnxoperatingbuffer_standardDeviation: number;
  jnxoperatingbuffer_rawHexSample: string;
  jnxoperatingbuffer_metadataTag: Record<string, string>;
  jnxcosqueuedroppkts_primaryMetric: number;
  jnxcosqueuedroppkts_secondaryMetric: number;
  jnxcosqueuedroppkts_baselineAverage: number;
  jnxcosqueuedroppkts_peakObserved: number;
  jnxcosqueuedroppkts_standardDeviation: number;
  jnxcosqueuedroppkts_rawHexSample: string;
  jnxcosqueuedroppkts_metadataTag: Record<string, string>;
  jnxbgpm2peerstatus_primaryMetric: number;
  jnxbgpm2peerstatus_secondaryMetric: number;
  jnxbgpm2peerstatus_baselineAverage: number;
  jnxbgpm2peerstatus_peakObserved: number;
  jnxbgpm2peerstatus_standardDeviation: number;
  jnxbgpm2peerstatus_rawHexSample: string;
  jnxbgpm2peerstatus_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type SnmpJuniperJunosFilterV16 = Partial<SnmpJuniperJunosRecordV16> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface SnmpJuniperJunosRecordV17 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  jnxboxanatomy_primaryMetric: number;
  jnxboxanatomy_secondaryMetric: number;
  jnxboxanatomy_baselineAverage: number;
  jnxboxanatomy_peakObserved: number;
  jnxboxanatomy_standardDeviation: number;
  jnxboxanatomy_rawHexSample: string;
  jnxboxanatomy_metadataTag: Record<string, string>;
  jnxoperatingcpu_primaryMetric: number;
  jnxoperatingcpu_secondaryMetric: number;
  jnxoperatingcpu_baselineAverage: number;
  jnxoperatingcpu_peakObserved: number;
  jnxoperatingcpu_standardDeviation: number;
  jnxoperatingcpu_rawHexSample: string;
  jnxoperatingcpu_metadataTag: Record<string, string>;
  jnxoperatingbuffer_primaryMetric: number;
  jnxoperatingbuffer_secondaryMetric: number;
  jnxoperatingbuffer_baselineAverage: number;
  jnxoperatingbuffer_peakObserved: number;
  jnxoperatingbuffer_standardDeviation: number;
  jnxoperatingbuffer_rawHexSample: string;
  jnxoperatingbuffer_metadataTag: Record<string, string>;
  jnxcosqueuedroppkts_primaryMetric: number;
  jnxcosqueuedroppkts_secondaryMetric: number;
  jnxcosqueuedroppkts_baselineAverage: number;
  jnxcosqueuedroppkts_peakObserved: number;
  jnxcosqueuedroppkts_standardDeviation: number;
  jnxcosqueuedroppkts_rawHexSample: string;
  jnxcosqueuedroppkts_metadataTag: Record<string, string>;
  jnxbgpm2peerstatus_primaryMetric: number;
  jnxbgpm2peerstatus_secondaryMetric: number;
  jnxbgpm2peerstatus_baselineAverage: number;
  jnxbgpm2peerstatus_peakObserved: number;
  jnxbgpm2peerstatus_standardDeviation: number;
  jnxbgpm2peerstatus_rawHexSample: string;
  jnxbgpm2peerstatus_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type SnmpJuniperJunosFilterV17 = Partial<SnmpJuniperJunosRecordV17> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface SnmpJuniperJunosRecordV18 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  jnxboxanatomy_primaryMetric: number;
  jnxboxanatomy_secondaryMetric: number;
  jnxboxanatomy_baselineAverage: number;
  jnxboxanatomy_peakObserved: number;
  jnxboxanatomy_standardDeviation: number;
  jnxboxanatomy_rawHexSample: string;
  jnxboxanatomy_metadataTag: Record<string, string>;
  jnxoperatingcpu_primaryMetric: number;
  jnxoperatingcpu_secondaryMetric: number;
  jnxoperatingcpu_baselineAverage: number;
  jnxoperatingcpu_peakObserved: number;
  jnxoperatingcpu_standardDeviation: number;
  jnxoperatingcpu_rawHexSample: string;
  jnxoperatingcpu_metadataTag: Record<string, string>;
  jnxoperatingbuffer_primaryMetric: number;
  jnxoperatingbuffer_secondaryMetric: number;
  jnxoperatingbuffer_baselineAverage: number;
  jnxoperatingbuffer_peakObserved: number;
  jnxoperatingbuffer_standardDeviation: number;
  jnxoperatingbuffer_rawHexSample: string;
  jnxoperatingbuffer_metadataTag: Record<string, string>;
  jnxcosqueuedroppkts_primaryMetric: number;
  jnxcosqueuedroppkts_secondaryMetric: number;
  jnxcosqueuedroppkts_baselineAverage: number;
  jnxcosqueuedroppkts_peakObserved: number;
  jnxcosqueuedroppkts_standardDeviation: number;
  jnxcosqueuedroppkts_rawHexSample: string;
  jnxcosqueuedroppkts_metadataTag: Record<string, string>;
  jnxbgpm2peerstatus_primaryMetric: number;
  jnxbgpm2peerstatus_secondaryMetric: number;
  jnxbgpm2peerstatus_baselineAverage: number;
  jnxbgpm2peerstatus_peakObserved: number;
  jnxbgpm2peerstatus_standardDeviation: number;
  jnxbgpm2peerstatus_rawHexSample: string;
  jnxbgpm2peerstatus_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type SnmpJuniperJunosFilterV18 = Partial<SnmpJuniperJunosRecordV18> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface SnmpJuniperJunosRecordV19 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  jnxboxanatomy_primaryMetric: number;
  jnxboxanatomy_secondaryMetric: number;
  jnxboxanatomy_baselineAverage: number;
  jnxboxanatomy_peakObserved: number;
  jnxboxanatomy_standardDeviation: number;
  jnxboxanatomy_rawHexSample: string;
  jnxboxanatomy_metadataTag: Record<string, string>;
  jnxoperatingcpu_primaryMetric: number;
  jnxoperatingcpu_secondaryMetric: number;
  jnxoperatingcpu_baselineAverage: number;
  jnxoperatingcpu_peakObserved: number;
  jnxoperatingcpu_standardDeviation: number;
  jnxoperatingcpu_rawHexSample: string;
  jnxoperatingcpu_metadataTag: Record<string, string>;
  jnxoperatingbuffer_primaryMetric: number;
  jnxoperatingbuffer_secondaryMetric: number;
  jnxoperatingbuffer_baselineAverage: number;
  jnxoperatingbuffer_peakObserved: number;
  jnxoperatingbuffer_standardDeviation: number;
  jnxoperatingbuffer_rawHexSample: string;
  jnxoperatingbuffer_metadataTag: Record<string, string>;
  jnxcosqueuedroppkts_primaryMetric: number;
  jnxcosqueuedroppkts_secondaryMetric: number;
  jnxcosqueuedroppkts_baselineAverage: number;
  jnxcosqueuedroppkts_peakObserved: number;
  jnxcosqueuedroppkts_standardDeviation: number;
  jnxcosqueuedroppkts_rawHexSample: string;
  jnxcosqueuedroppkts_metadataTag: Record<string, string>;
  jnxbgpm2peerstatus_primaryMetric: number;
  jnxbgpm2peerstatus_secondaryMetric: number;
  jnxbgpm2peerstatus_baselineAverage: number;
  jnxbgpm2peerstatus_peakObserved: number;
  jnxbgpm2peerstatus_standardDeviation: number;
  jnxbgpm2peerstatus_rawHexSample: string;
  jnxbgpm2peerstatus_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type SnmpJuniperJunosFilterV19 = Partial<SnmpJuniperJunosRecordV19> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface SnmpJuniperJunosRecordV20 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  jnxboxanatomy_primaryMetric: number;
  jnxboxanatomy_secondaryMetric: number;
  jnxboxanatomy_baselineAverage: number;
  jnxboxanatomy_peakObserved: number;
  jnxboxanatomy_standardDeviation: number;
  jnxboxanatomy_rawHexSample: string;
  jnxboxanatomy_metadataTag: Record<string, string>;
  jnxoperatingcpu_primaryMetric: number;
  jnxoperatingcpu_secondaryMetric: number;
  jnxoperatingcpu_baselineAverage: number;
  jnxoperatingcpu_peakObserved: number;
  jnxoperatingcpu_standardDeviation: number;
  jnxoperatingcpu_rawHexSample: string;
  jnxoperatingcpu_metadataTag: Record<string, string>;
  jnxoperatingbuffer_primaryMetric: number;
  jnxoperatingbuffer_secondaryMetric: number;
  jnxoperatingbuffer_baselineAverage: number;
  jnxoperatingbuffer_peakObserved: number;
  jnxoperatingbuffer_standardDeviation: number;
  jnxoperatingbuffer_rawHexSample: string;
  jnxoperatingbuffer_metadataTag: Record<string, string>;
  jnxcosqueuedroppkts_primaryMetric: number;
  jnxcosqueuedroppkts_secondaryMetric: number;
  jnxcosqueuedroppkts_baselineAverage: number;
  jnxcosqueuedroppkts_peakObserved: number;
  jnxcosqueuedroppkts_standardDeviation: number;
  jnxcosqueuedroppkts_rawHexSample: string;
  jnxcosqueuedroppkts_metadataTag: Record<string, string>;
  jnxbgpm2peerstatus_primaryMetric: number;
  jnxbgpm2peerstatus_secondaryMetric: number;
  jnxbgpm2peerstatus_baselineAverage: number;
  jnxbgpm2peerstatus_peakObserved: number;
  jnxbgpm2peerstatus_standardDeviation: number;
  jnxbgpm2peerstatus_rawHexSample: string;
  jnxbgpm2peerstatus_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type SnmpJuniperJunosFilterV20 = Partial<SnmpJuniperJunosRecordV20> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface SnmpJuniperJunosRecordV21 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  jnxboxanatomy_primaryMetric: number;
  jnxboxanatomy_secondaryMetric: number;
  jnxboxanatomy_baselineAverage: number;
  jnxboxanatomy_peakObserved: number;
  jnxboxanatomy_standardDeviation: number;
  jnxboxanatomy_rawHexSample: string;
  jnxboxanatomy_metadataTag: Record<string, string>;
  jnxoperatingcpu_primaryMetric: number;
  jnxoperatingcpu_secondaryMetric: number;
  jnxoperatingcpu_baselineAverage: number;
  jnxoperatingcpu_peakObserved: number;
  jnxoperatingcpu_standardDeviation: number;
  jnxoperatingcpu_rawHexSample: string;
  jnxoperatingcpu_metadataTag: Record<string, string>;
  jnxoperatingbuffer_primaryMetric: number;
  jnxoperatingbuffer_secondaryMetric: number;
  jnxoperatingbuffer_baselineAverage: number;
  jnxoperatingbuffer_peakObserved: number;
  jnxoperatingbuffer_standardDeviation: number;
  jnxoperatingbuffer_rawHexSample: string;
  jnxoperatingbuffer_metadataTag: Record<string, string>;
  jnxcosqueuedroppkts_primaryMetric: number;
  jnxcosqueuedroppkts_secondaryMetric: number;
  jnxcosqueuedroppkts_baselineAverage: number;
  jnxcosqueuedroppkts_peakObserved: number;
  jnxcosqueuedroppkts_standardDeviation: number;
  jnxcosqueuedroppkts_rawHexSample: string;
  jnxcosqueuedroppkts_metadataTag: Record<string, string>;
  jnxbgpm2peerstatus_primaryMetric: number;
  jnxbgpm2peerstatus_secondaryMetric: number;
  jnxbgpm2peerstatus_baselineAverage: number;
  jnxbgpm2peerstatus_peakObserved: number;
  jnxbgpm2peerstatus_standardDeviation: number;
  jnxbgpm2peerstatus_rawHexSample: string;
  jnxbgpm2peerstatus_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type SnmpJuniperJunosFilterV21 = Partial<SnmpJuniperJunosRecordV21> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface SnmpJuniperJunosRecordV22 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  jnxboxanatomy_primaryMetric: number;
  jnxboxanatomy_secondaryMetric: number;
  jnxboxanatomy_baselineAverage: number;
  jnxboxanatomy_peakObserved: number;
  jnxboxanatomy_standardDeviation: number;
  jnxboxanatomy_rawHexSample: string;
  jnxboxanatomy_metadataTag: Record<string, string>;
  jnxoperatingcpu_primaryMetric: number;
  jnxoperatingcpu_secondaryMetric: number;
  jnxoperatingcpu_baselineAverage: number;
  jnxoperatingcpu_peakObserved: number;
  jnxoperatingcpu_standardDeviation: number;
  jnxoperatingcpu_rawHexSample: string;
  jnxoperatingcpu_metadataTag: Record<string, string>;
  jnxoperatingbuffer_primaryMetric: number;
  jnxoperatingbuffer_secondaryMetric: number;
  jnxoperatingbuffer_baselineAverage: number;
  jnxoperatingbuffer_peakObserved: number;
  jnxoperatingbuffer_standardDeviation: number;
  jnxoperatingbuffer_rawHexSample: string;
  jnxoperatingbuffer_metadataTag: Record<string, string>;
  jnxcosqueuedroppkts_primaryMetric: number;
  jnxcosqueuedroppkts_secondaryMetric: number;
  jnxcosqueuedroppkts_baselineAverage: number;
  jnxcosqueuedroppkts_peakObserved: number;
  jnxcosqueuedroppkts_standardDeviation: number;
  jnxcosqueuedroppkts_rawHexSample: string;
  jnxcosqueuedroppkts_metadataTag: Record<string, string>;
  jnxbgpm2peerstatus_primaryMetric: number;
  jnxbgpm2peerstatus_secondaryMetric: number;
  jnxbgpm2peerstatus_baselineAverage: number;
  jnxbgpm2peerstatus_peakObserved: number;
  jnxbgpm2peerstatus_standardDeviation: number;
  jnxbgpm2peerstatus_rawHexSample: string;
  jnxbgpm2peerstatus_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type SnmpJuniperJunosFilterV22 = Partial<SnmpJuniperJunosRecordV22> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface SnmpJuniperJunosRecordV23 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  jnxboxanatomy_primaryMetric: number;
  jnxboxanatomy_secondaryMetric: number;
  jnxboxanatomy_baselineAverage: number;
  jnxboxanatomy_peakObserved: number;
  jnxboxanatomy_standardDeviation: number;
  jnxboxanatomy_rawHexSample: string;
  jnxboxanatomy_metadataTag: Record<string, string>;
  jnxoperatingcpu_primaryMetric: number;
  jnxoperatingcpu_secondaryMetric: number;
  jnxoperatingcpu_baselineAverage: number;
  jnxoperatingcpu_peakObserved: number;
  jnxoperatingcpu_standardDeviation: number;
  jnxoperatingcpu_rawHexSample: string;
  jnxoperatingcpu_metadataTag: Record<string, string>;
  jnxoperatingbuffer_primaryMetric: number;
  jnxoperatingbuffer_secondaryMetric: number;
  jnxoperatingbuffer_baselineAverage: number;
  jnxoperatingbuffer_peakObserved: number;
  jnxoperatingbuffer_standardDeviation: number;
  jnxoperatingbuffer_rawHexSample: string;
  jnxoperatingbuffer_metadataTag: Record<string, string>;
  jnxcosqueuedroppkts_primaryMetric: number;
  jnxcosqueuedroppkts_secondaryMetric: number;
  jnxcosqueuedroppkts_baselineAverage: number;
  jnxcosqueuedroppkts_peakObserved: number;
  jnxcosqueuedroppkts_standardDeviation: number;
  jnxcosqueuedroppkts_rawHexSample: string;
  jnxcosqueuedroppkts_metadataTag: Record<string, string>;
  jnxbgpm2peerstatus_primaryMetric: number;
  jnxbgpm2peerstatus_secondaryMetric: number;
  jnxbgpm2peerstatus_baselineAverage: number;
  jnxbgpm2peerstatus_peakObserved: number;
  jnxbgpm2peerstatus_standardDeviation: number;
  jnxbgpm2peerstatus_rawHexSample: string;
  jnxbgpm2peerstatus_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type SnmpJuniperJunosFilterV23 = Partial<SnmpJuniperJunosRecordV23> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface SnmpJuniperJunosRecordV24 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  jnxboxanatomy_primaryMetric: number;
  jnxboxanatomy_secondaryMetric: number;
  jnxboxanatomy_baselineAverage: number;
  jnxboxanatomy_peakObserved: number;
  jnxboxanatomy_standardDeviation: number;
  jnxboxanatomy_rawHexSample: string;
  jnxboxanatomy_metadataTag: Record<string, string>;
  jnxoperatingcpu_primaryMetric: number;
  jnxoperatingcpu_secondaryMetric: number;
  jnxoperatingcpu_baselineAverage: number;
  jnxoperatingcpu_peakObserved: number;
  jnxoperatingcpu_standardDeviation: number;
  jnxoperatingcpu_rawHexSample: string;
  jnxoperatingcpu_metadataTag: Record<string, string>;
  jnxoperatingbuffer_primaryMetric: number;
  jnxoperatingbuffer_secondaryMetric: number;
  jnxoperatingbuffer_baselineAverage: number;
  jnxoperatingbuffer_peakObserved: number;
  jnxoperatingbuffer_standardDeviation: number;
  jnxoperatingbuffer_rawHexSample: string;
  jnxoperatingbuffer_metadataTag: Record<string, string>;
  jnxcosqueuedroppkts_primaryMetric: number;
  jnxcosqueuedroppkts_secondaryMetric: number;
  jnxcosqueuedroppkts_baselineAverage: number;
  jnxcosqueuedroppkts_peakObserved: number;
  jnxcosqueuedroppkts_standardDeviation: number;
  jnxcosqueuedroppkts_rawHexSample: string;
  jnxcosqueuedroppkts_metadataTag: Record<string, string>;
  jnxbgpm2peerstatus_primaryMetric: number;
  jnxbgpm2peerstatus_secondaryMetric: number;
  jnxbgpm2peerstatus_baselineAverage: number;
  jnxbgpm2peerstatus_peakObserved: number;
  jnxbgpm2peerstatus_standardDeviation: number;
  jnxbgpm2peerstatus_rawHexSample: string;
  jnxbgpm2peerstatus_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type SnmpJuniperJunosFilterV24 = Partial<SnmpJuniperJunosRecordV24> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface SnmpJuniperJunosRecordV25 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  jnxboxanatomy_primaryMetric: number;
  jnxboxanatomy_secondaryMetric: number;
  jnxboxanatomy_baselineAverage: number;
  jnxboxanatomy_peakObserved: number;
  jnxboxanatomy_standardDeviation: number;
  jnxboxanatomy_rawHexSample: string;
  jnxboxanatomy_metadataTag: Record<string, string>;
  jnxoperatingcpu_primaryMetric: number;
  jnxoperatingcpu_secondaryMetric: number;
  jnxoperatingcpu_baselineAverage: number;
  jnxoperatingcpu_peakObserved: number;
  jnxoperatingcpu_standardDeviation: number;
  jnxoperatingcpu_rawHexSample: string;
  jnxoperatingcpu_metadataTag: Record<string, string>;
  jnxoperatingbuffer_primaryMetric: number;
  jnxoperatingbuffer_secondaryMetric: number;
  jnxoperatingbuffer_baselineAverage: number;
  jnxoperatingbuffer_peakObserved: number;
  jnxoperatingbuffer_standardDeviation: number;
  jnxoperatingbuffer_rawHexSample: string;
  jnxoperatingbuffer_metadataTag: Record<string, string>;
  jnxcosqueuedroppkts_primaryMetric: number;
  jnxcosqueuedroppkts_secondaryMetric: number;
  jnxcosqueuedroppkts_baselineAverage: number;
  jnxcosqueuedroppkts_peakObserved: number;
  jnxcosqueuedroppkts_standardDeviation: number;
  jnxcosqueuedroppkts_rawHexSample: string;
  jnxcosqueuedroppkts_metadataTag: Record<string, string>;
  jnxbgpm2peerstatus_primaryMetric: number;
  jnxbgpm2peerstatus_secondaryMetric: number;
  jnxbgpm2peerstatus_baselineAverage: number;
  jnxbgpm2peerstatus_peakObserved: number;
  jnxbgpm2peerstatus_standardDeviation: number;
  jnxbgpm2peerstatus_rawHexSample: string;
  jnxbgpm2peerstatus_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type SnmpJuniperJunosFilterV25 = Partial<SnmpJuniperJunosRecordV25> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface SnmpJuniperJunosRecordV26 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  jnxboxanatomy_primaryMetric: number;
  jnxboxanatomy_secondaryMetric: number;
  jnxboxanatomy_baselineAverage: number;
  jnxboxanatomy_peakObserved: number;
  jnxboxanatomy_standardDeviation: number;
  jnxboxanatomy_rawHexSample: string;
  jnxboxanatomy_metadataTag: Record<string, string>;
  jnxoperatingcpu_primaryMetric: number;
  jnxoperatingcpu_secondaryMetric: number;
  jnxoperatingcpu_baselineAverage: number;
  jnxoperatingcpu_peakObserved: number;
  jnxoperatingcpu_standardDeviation: number;
  jnxoperatingcpu_rawHexSample: string;
  jnxoperatingcpu_metadataTag: Record<string, string>;
  jnxoperatingbuffer_primaryMetric: number;
  jnxoperatingbuffer_secondaryMetric: number;
  jnxoperatingbuffer_baselineAverage: number;
  jnxoperatingbuffer_peakObserved: number;
  jnxoperatingbuffer_standardDeviation: number;
  jnxoperatingbuffer_rawHexSample: string;
  jnxoperatingbuffer_metadataTag: Record<string, string>;
  jnxcosqueuedroppkts_primaryMetric: number;
  jnxcosqueuedroppkts_secondaryMetric: number;
  jnxcosqueuedroppkts_baselineAverage: number;
  jnxcosqueuedroppkts_peakObserved: number;
  jnxcosqueuedroppkts_standardDeviation: number;
  jnxcosqueuedroppkts_rawHexSample: string;
  jnxcosqueuedroppkts_metadataTag: Record<string, string>;
  jnxbgpm2peerstatus_primaryMetric: number;
  jnxbgpm2peerstatus_secondaryMetric: number;
  jnxbgpm2peerstatus_baselineAverage: number;
  jnxbgpm2peerstatus_peakObserved: number;
  jnxbgpm2peerstatus_standardDeviation: number;
  jnxbgpm2peerstatus_rawHexSample: string;
  jnxbgpm2peerstatus_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type SnmpJuniperJunosFilterV26 = Partial<SnmpJuniperJunosRecordV26> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface SnmpJuniperJunosRecordV27 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  jnxboxanatomy_primaryMetric: number;
  jnxboxanatomy_secondaryMetric: number;
  jnxboxanatomy_baselineAverage: number;
  jnxboxanatomy_peakObserved: number;
  jnxboxanatomy_standardDeviation: number;
  jnxboxanatomy_rawHexSample: string;
  jnxboxanatomy_metadataTag: Record<string, string>;
  jnxoperatingcpu_primaryMetric: number;
  jnxoperatingcpu_secondaryMetric: number;
  jnxoperatingcpu_baselineAverage: number;
  jnxoperatingcpu_peakObserved: number;
  jnxoperatingcpu_standardDeviation: number;
  jnxoperatingcpu_rawHexSample: string;
  jnxoperatingcpu_metadataTag: Record<string, string>;
  jnxoperatingbuffer_primaryMetric: number;
  jnxoperatingbuffer_secondaryMetric: number;
  jnxoperatingbuffer_baselineAverage: number;
  jnxoperatingbuffer_peakObserved: number;
  jnxoperatingbuffer_standardDeviation: number;
  jnxoperatingbuffer_rawHexSample: string;
  jnxoperatingbuffer_metadataTag: Record<string, string>;
  jnxcosqueuedroppkts_primaryMetric: number;
  jnxcosqueuedroppkts_secondaryMetric: number;
  jnxcosqueuedroppkts_baselineAverage: number;
  jnxcosqueuedroppkts_peakObserved: number;
  jnxcosqueuedroppkts_standardDeviation: number;
  jnxcosqueuedroppkts_rawHexSample: string;
  jnxcosqueuedroppkts_metadataTag: Record<string, string>;
  jnxbgpm2peerstatus_primaryMetric: number;
  jnxbgpm2peerstatus_secondaryMetric: number;
  jnxbgpm2peerstatus_baselineAverage: number;
  jnxbgpm2peerstatus_peakObserved: number;
  jnxbgpm2peerstatus_standardDeviation: number;
  jnxbgpm2peerstatus_rawHexSample: string;
  jnxbgpm2peerstatus_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type SnmpJuniperJunosFilterV27 = Partial<SnmpJuniperJunosRecordV27> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface SnmpJuniperJunosRecordV28 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  jnxboxanatomy_primaryMetric: number;
  jnxboxanatomy_secondaryMetric: number;
  jnxboxanatomy_baselineAverage: number;
  jnxboxanatomy_peakObserved: number;
  jnxboxanatomy_standardDeviation: number;
  jnxboxanatomy_rawHexSample: string;
  jnxboxanatomy_metadataTag: Record<string, string>;
  jnxoperatingcpu_primaryMetric: number;
  jnxoperatingcpu_secondaryMetric: number;
  jnxoperatingcpu_baselineAverage: number;
  jnxoperatingcpu_peakObserved: number;
  jnxoperatingcpu_standardDeviation: number;
  jnxoperatingcpu_rawHexSample: string;
  jnxoperatingcpu_metadataTag: Record<string, string>;
  jnxoperatingbuffer_primaryMetric: number;
  jnxoperatingbuffer_secondaryMetric: number;
  jnxoperatingbuffer_baselineAverage: number;
  jnxoperatingbuffer_peakObserved: number;
  jnxoperatingbuffer_standardDeviation: number;
  jnxoperatingbuffer_rawHexSample: string;
  jnxoperatingbuffer_metadataTag: Record<string, string>;
  jnxcosqueuedroppkts_primaryMetric: number;
  jnxcosqueuedroppkts_secondaryMetric: number;
  jnxcosqueuedroppkts_baselineAverage: number;
  jnxcosqueuedroppkts_peakObserved: number;
  jnxcosqueuedroppkts_standardDeviation: number;
  jnxcosqueuedroppkts_rawHexSample: string;
  jnxcosqueuedroppkts_metadataTag: Record<string, string>;
  jnxbgpm2peerstatus_primaryMetric: number;
  jnxbgpm2peerstatus_secondaryMetric: number;
  jnxbgpm2peerstatus_baselineAverage: number;
  jnxbgpm2peerstatus_peakObserved: number;
  jnxbgpm2peerstatus_standardDeviation: number;
  jnxbgpm2peerstatus_rawHexSample: string;
  jnxbgpm2peerstatus_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type SnmpJuniperJunosFilterV28 = Partial<SnmpJuniperJunosRecordV28> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface SnmpJuniperJunosRecordV29 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  jnxboxanatomy_primaryMetric: number;
  jnxboxanatomy_secondaryMetric: number;
  jnxboxanatomy_baselineAverage: number;
  jnxboxanatomy_peakObserved: number;
  jnxboxanatomy_standardDeviation: number;
  jnxboxanatomy_rawHexSample: string;
  jnxboxanatomy_metadataTag: Record<string, string>;
  jnxoperatingcpu_primaryMetric: number;
  jnxoperatingcpu_secondaryMetric: number;
  jnxoperatingcpu_baselineAverage: number;
  jnxoperatingcpu_peakObserved: number;
  jnxoperatingcpu_standardDeviation: number;
  jnxoperatingcpu_rawHexSample: string;
  jnxoperatingcpu_metadataTag: Record<string, string>;
  jnxoperatingbuffer_primaryMetric: number;
  jnxoperatingbuffer_secondaryMetric: number;
  jnxoperatingbuffer_baselineAverage: number;
  jnxoperatingbuffer_peakObserved: number;
  jnxoperatingbuffer_standardDeviation: number;
  jnxoperatingbuffer_rawHexSample: string;
  jnxoperatingbuffer_metadataTag: Record<string, string>;
  jnxcosqueuedroppkts_primaryMetric: number;
  jnxcosqueuedroppkts_secondaryMetric: number;
  jnxcosqueuedroppkts_baselineAverage: number;
  jnxcosqueuedroppkts_peakObserved: number;
  jnxcosqueuedroppkts_standardDeviation: number;
  jnxcosqueuedroppkts_rawHexSample: string;
  jnxcosqueuedroppkts_metadataTag: Record<string, string>;
  jnxbgpm2peerstatus_primaryMetric: number;
  jnxbgpm2peerstatus_secondaryMetric: number;
  jnxbgpm2peerstatus_baselineAverage: number;
  jnxbgpm2peerstatus_peakObserved: number;
  jnxbgpm2peerstatus_standardDeviation: number;
  jnxbgpm2peerstatus_rawHexSample: string;
  jnxbgpm2peerstatus_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type SnmpJuniperJunosFilterV29 = Partial<SnmpJuniperJunosRecordV29> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface SnmpJuniperJunosRecordV30 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  jnxboxanatomy_primaryMetric: number;
  jnxboxanatomy_secondaryMetric: number;
  jnxboxanatomy_baselineAverage: number;
  jnxboxanatomy_peakObserved: number;
  jnxboxanatomy_standardDeviation: number;
  jnxboxanatomy_rawHexSample: string;
  jnxboxanatomy_metadataTag: Record<string, string>;
  jnxoperatingcpu_primaryMetric: number;
  jnxoperatingcpu_secondaryMetric: number;
  jnxoperatingcpu_baselineAverage: number;
  jnxoperatingcpu_peakObserved: number;
  jnxoperatingcpu_standardDeviation: number;
  jnxoperatingcpu_rawHexSample: string;
  jnxoperatingcpu_metadataTag: Record<string, string>;
  jnxoperatingbuffer_primaryMetric: number;
  jnxoperatingbuffer_secondaryMetric: number;
  jnxoperatingbuffer_baselineAverage: number;
  jnxoperatingbuffer_peakObserved: number;
  jnxoperatingbuffer_standardDeviation: number;
  jnxoperatingbuffer_rawHexSample: string;
  jnxoperatingbuffer_metadataTag: Record<string, string>;
  jnxcosqueuedroppkts_primaryMetric: number;
  jnxcosqueuedroppkts_secondaryMetric: number;
  jnxcosqueuedroppkts_baselineAverage: number;
  jnxcosqueuedroppkts_peakObserved: number;
  jnxcosqueuedroppkts_standardDeviation: number;
  jnxcosqueuedroppkts_rawHexSample: string;
  jnxcosqueuedroppkts_metadataTag: Record<string, string>;
  jnxbgpm2peerstatus_primaryMetric: number;
  jnxbgpm2peerstatus_secondaryMetric: number;
  jnxbgpm2peerstatus_baselineAverage: number;
  jnxbgpm2peerstatus_peakObserved: number;
  jnxbgpm2peerstatus_standardDeviation: number;
  jnxbgpm2peerstatus_rawHexSample: string;
  jnxbgpm2peerstatus_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type SnmpJuniperJunosFilterV30 = Partial<SnmpJuniperJunosRecordV30> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface SnmpJuniperJunosRecordV31 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  jnxboxanatomy_primaryMetric: number;
  jnxboxanatomy_secondaryMetric: number;
  jnxboxanatomy_baselineAverage: number;
  jnxboxanatomy_peakObserved: number;
  jnxboxanatomy_standardDeviation: number;
  jnxboxanatomy_rawHexSample: string;
  jnxboxanatomy_metadataTag: Record<string, string>;
  jnxoperatingcpu_primaryMetric: number;
  jnxoperatingcpu_secondaryMetric: number;
  jnxoperatingcpu_baselineAverage: number;
  jnxoperatingcpu_peakObserved: number;
  jnxoperatingcpu_standardDeviation: number;
  jnxoperatingcpu_rawHexSample: string;
  jnxoperatingcpu_metadataTag: Record<string, string>;
  jnxoperatingbuffer_primaryMetric: number;
  jnxoperatingbuffer_secondaryMetric: number;
  jnxoperatingbuffer_baselineAverage: number;
  jnxoperatingbuffer_peakObserved: number;
  jnxoperatingbuffer_standardDeviation: number;
  jnxoperatingbuffer_rawHexSample: string;
  jnxoperatingbuffer_metadataTag: Record<string, string>;
  jnxcosqueuedroppkts_primaryMetric: number;
  jnxcosqueuedroppkts_secondaryMetric: number;
  jnxcosqueuedroppkts_baselineAverage: number;
  jnxcosqueuedroppkts_peakObserved: number;
  jnxcosqueuedroppkts_standardDeviation: number;
  jnxcosqueuedroppkts_rawHexSample: string;
  jnxcosqueuedroppkts_metadataTag: Record<string, string>;
  jnxbgpm2peerstatus_primaryMetric: number;
  jnxbgpm2peerstatus_secondaryMetric: number;
  jnxbgpm2peerstatus_baselineAverage: number;
  jnxbgpm2peerstatus_peakObserved: number;
  jnxbgpm2peerstatus_standardDeviation: number;
  jnxbgpm2peerstatus_rawHexSample: string;
  jnxbgpm2peerstatus_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type SnmpJuniperJunosFilterV31 = Partial<SnmpJuniperJunosRecordV31> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface SnmpJuniperJunosRecordV32 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  jnxboxanatomy_primaryMetric: number;
  jnxboxanatomy_secondaryMetric: number;
  jnxboxanatomy_baselineAverage: number;
  jnxboxanatomy_peakObserved: number;
  jnxboxanatomy_standardDeviation: number;
  jnxboxanatomy_rawHexSample: string;
  jnxboxanatomy_metadataTag: Record<string, string>;
  jnxoperatingcpu_primaryMetric: number;
  jnxoperatingcpu_secondaryMetric: number;
  jnxoperatingcpu_baselineAverage: number;
  jnxoperatingcpu_peakObserved: number;
  jnxoperatingcpu_standardDeviation: number;
  jnxoperatingcpu_rawHexSample: string;
  jnxoperatingcpu_metadataTag: Record<string, string>;
  jnxoperatingbuffer_primaryMetric: number;
  jnxoperatingbuffer_secondaryMetric: number;
  jnxoperatingbuffer_baselineAverage: number;
  jnxoperatingbuffer_peakObserved: number;
  jnxoperatingbuffer_standardDeviation: number;
  jnxoperatingbuffer_rawHexSample: string;
  jnxoperatingbuffer_metadataTag: Record<string, string>;
  jnxcosqueuedroppkts_primaryMetric: number;
  jnxcosqueuedroppkts_secondaryMetric: number;
  jnxcosqueuedroppkts_baselineAverage: number;
  jnxcosqueuedroppkts_peakObserved: number;
  jnxcosqueuedroppkts_standardDeviation: number;
  jnxcosqueuedroppkts_rawHexSample: string;
  jnxcosqueuedroppkts_metadataTag: Record<string, string>;
  jnxbgpm2peerstatus_primaryMetric: number;
  jnxbgpm2peerstatus_secondaryMetric: number;
  jnxbgpm2peerstatus_baselineAverage: number;
  jnxbgpm2peerstatus_peakObserved: number;
  jnxbgpm2peerstatus_standardDeviation: number;
  jnxbgpm2peerstatus_rawHexSample: string;
  jnxbgpm2peerstatus_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type SnmpJuniperJunosFilterV32 = Partial<SnmpJuniperJunosRecordV32> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface SnmpJuniperJunosRecordV33 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  jnxboxanatomy_primaryMetric: number;
  jnxboxanatomy_secondaryMetric: number;
  jnxboxanatomy_baselineAverage: number;
  jnxboxanatomy_peakObserved: number;
  jnxboxanatomy_standardDeviation: number;
  jnxboxanatomy_rawHexSample: string;
  jnxboxanatomy_metadataTag: Record<string, string>;
  jnxoperatingcpu_primaryMetric: number;
  jnxoperatingcpu_secondaryMetric: number;
  jnxoperatingcpu_baselineAverage: number;
  jnxoperatingcpu_peakObserved: number;
  jnxoperatingcpu_standardDeviation: number;
  jnxoperatingcpu_rawHexSample: string;
  jnxoperatingcpu_metadataTag: Record<string, string>;
  jnxoperatingbuffer_primaryMetric: number;
  jnxoperatingbuffer_secondaryMetric: number;
  jnxoperatingbuffer_baselineAverage: number;
  jnxoperatingbuffer_peakObserved: number;
  jnxoperatingbuffer_standardDeviation: number;
  jnxoperatingbuffer_rawHexSample: string;
  jnxoperatingbuffer_metadataTag: Record<string, string>;
  jnxcosqueuedroppkts_primaryMetric: number;
  jnxcosqueuedroppkts_secondaryMetric: number;
  jnxcosqueuedroppkts_baselineAverage: number;
  jnxcosqueuedroppkts_peakObserved: number;
  jnxcosqueuedroppkts_standardDeviation: number;
  jnxcosqueuedroppkts_rawHexSample: string;
  jnxcosqueuedroppkts_metadataTag: Record<string, string>;
  jnxbgpm2peerstatus_primaryMetric: number;
  jnxbgpm2peerstatus_secondaryMetric: number;
  jnxbgpm2peerstatus_baselineAverage: number;
  jnxbgpm2peerstatus_peakObserved: number;
  jnxbgpm2peerstatus_standardDeviation: number;
  jnxbgpm2peerstatus_rawHexSample: string;
  jnxbgpm2peerstatus_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type SnmpJuniperJunosFilterV33 = Partial<SnmpJuniperJunosRecordV33> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface SnmpJuniperJunosRecordV34 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  jnxboxanatomy_primaryMetric: number;
  jnxboxanatomy_secondaryMetric: number;
  jnxboxanatomy_baselineAverage: number;
  jnxboxanatomy_peakObserved: number;
  jnxboxanatomy_standardDeviation: number;
  jnxboxanatomy_rawHexSample: string;
  jnxboxanatomy_metadataTag: Record<string, string>;
  jnxoperatingcpu_primaryMetric: number;
  jnxoperatingcpu_secondaryMetric: number;
  jnxoperatingcpu_baselineAverage: number;
  jnxoperatingcpu_peakObserved: number;
  jnxoperatingcpu_standardDeviation: number;
  jnxoperatingcpu_rawHexSample: string;
  jnxoperatingcpu_metadataTag: Record<string, string>;
  jnxoperatingbuffer_primaryMetric: number;
  jnxoperatingbuffer_secondaryMetric: number;
  jnxoperatingbuffer_baselineAverage: number;
  jnxoperatingbuffer_peakObserved: number;
  jnxoperatingbuffer_standardDeviation: number;
  jnxoperatingbuffer_rawHexSample: string;
  jnxoperatingbuffer_metadataTag: Record<string, string>;
  jnxcosqueuedroppkts_primaryMetric: number;
  jnxcosqueuedroppkts_secondaryMetric: number;
  jnxcosqueuedroppkts_baselineAverage: number;
  jnxcosqueuedroppkts_peakObserved: number;
  jnxcosqueuedroppkts_standardDeviation: number;
  jnxcosqueuedroppkts_rawHexSample: string;
  jnxcosqueuedroppkts_metadataTag: Record<string, string>;
  jnxbgpm2peerstatus_primaryMetric: number;
  jnxbgpm2peerstatus_secondaryMetric: number;
  jnxbgpm2peerstatus_baselineAverage: number;
  jnxbgpm2peerstatus_peakObserved: number;
  jnxbgpm2peerstatus_standardDeviation: number;
  jnxbgpm2peerstatus_rawHexSample: string;
  jnxbgpm2peerstatus_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type SnmpJuniperJunosFilterV34 = Partial<SnmpJuniperJunosRecordV34> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface SnmpJuniperJunosRecordV35 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  jnxboxanatomy_primaryMetric: number;
  jnxboxanatomy_secondaryMetric: number;
  jnxboxanatomy_baselineAverage: number;
  jnxboxanatomy_peakObserved: number;
  jnxboxanatomy_standardDeviation: number;
  jnxboxanatomy_rawHexSample: string;
  jnxboxanatomy_metadataTag: Record<string, string>;
  jnxoperatingcpu_primaryMetric: number;
  jnxoperatingcpu_secondaryMetric: number;
  jnxoperatingcpu_baselineAverage: number;
  jnxoperatingcpu_peakObserved: number;
  jnxoperatingcpu_standardDeviation: number;
  jnxoperatingcpu_rawHexSample: string;
  jnxoperatingcpu_metadataTag: Record<string, string>;
  jnxoperatingbuffer_primaryMetric: number;
  jnxoperatingbuffer_secondaryMetric: number;
  jnxoperatingbuffer_baselineAverage: number;
  jnxoperatingbuffer_peakObserved: number;
  jnxoperatingbuffer_standardDeviation: number;
  jnxoperatingbuffer_rawHexSample: string;
  jnxoperatingbuffer_metadataTag: Record<string, string>;
  jnxcosqueuedroppkts_primaryMetric: number;
  jnxcosqueuedroppkts_secondaryMetric: number;
  jnxcosqueuedroppkts_baselineAverage: number;
  jnxcosqueuedroppkts_peakObserved: number;
  jnxcosqueuedroppkts_standardDeviation: number;
  jnxcosqueuedroppkts_rawHexSample: string;
  jnxcosqueuedroppkts_metadataTag: Record<string, string>;
  jnxbgpm2peerstatus_primaryMetric: number;
  jnxbgpm2peerstatus_secondaryMetric: number;
  jnxbgpm2peerstatus_baselineAverage: number;
  jnxbgpm2peerstatus_peakObserved: number;
  jnxbgpm2peerstatus_standardDeviation: number;
  jnxbgpm2peerstatus_rawHexSample: string;
  jnxbgpm2peerstatus_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type SnmpJuniperJunosFilterV35 = Partial<SnmpJuniperJunosRecordV35> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface SnmpJuniperJunosRecordV36 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  jnxboxanatomy_primaryMetric: number;
  jnxboxanatomy_secondaryMetric: number;
  jnxboxanatomy_baselineAverage: number;
  jnxboxanatomy_peakObserved: number;
  jnxboxanatomy_standardDeviation: number;
  jnxboxanatomy_rawHexSample: string;
  jnxboxanatomy_metadataTag: Record<string, string>;
  jnxoperatingcpu_primaryMetric: number;
  jnxoperatingcpu_secondaryMetric: number;
  jnxoperatingcpu_baselineAverage: number;
  jnxoperatingcpu_peakObserved: number;
  jnxoperatingcpu_standardDeviation: number;
  jnxoperatingcpu_rawHexSample: string;
  jnxoperatingcpu_metadataTag: Record<string, string>;
  jnxoperatingbuffer_primaryMetric: number;
  jnxoperatingbuffer_secondaryMetric: number;
  jnxoperatingbuffer_baselineAverage: number;
  jnxoperatingbuffer_peakObserved: number;
  jnxoperatingbuffer_standardDeviation: number;
  jnxoperatingbuffer_rawHexSample: string;
  jnxoperatingbuffer_metadataTag: Record<string, string>;
  jnxcosqueuedroppkts_primaryMetric: number;
  jnxcosqueuedroppkts_secondaryMetric: number;
  jnxcosqueuedroppkts_baselineAverage: number;
  jnxcosqueuedroppkts_peakObserved: number;
  jnxcosqueuedroppkts_standardDeviation: number;
  jnxcosqueuedroppkts_rawHexSample: string;
  jnxcosqueuedroppkts_metadataTag: Record<string, string>;
  jnxbgpm2peerstatus_primaryMetric: number;
  jnxbgpm2peerstatus_secondaryMetric: number;
  jnxbgpm2peerstatus_baselineAverage: number;
  jnxbgpm2peerstatus_peakObserved: number;
  jnxbgpm2peerstatus_standardDeviation: number;
  jnxbgpm2peerstatus_rawHexSample: string;
  jnxbgpm2peerstatus_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type SnmpJuniperJunosFilterV36 = Partial<SnmpJuniperJunosRecordV36> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface SnmpJuniperJunosRecordV37 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  jnxboxanatomy_primaryMetric: number;
  jnxboxanatomy_secondaryMetric: number;
  jnxboxanatomy_baselineAverage: number;
  jnxboxanatomy_peakObserved: number;
  jnxboxanatomy_standardDeviation: number;
  jnxboxanatomy_rawHexSample: string;
  jnxboxanatomy_metadataTag: Record<string, string>;
  jnxoperatingcpu_primaryMetric: number;
  jnxoperatingcpu_secondaryMetric: number;
  jnxoperatingcpu_baselineAverage: number;
  jnxoperatingcpu_peakObserved: number;
  jnxoperatingcpu_standardDeviation: number;
  jnxoperatingcpu_rawHexSample: string;
  jnxoperatingcpu_metadataTag: Record<string, string>;
  jnxoperatingbuffer_primaryMetric: number;
  jnxoperatingbuffer_secondaryMetric: number;
  jnxoperatingbuffer_baselineAverage: number;
  jnxoperatingbuffer_peakObserved: number;
  jnxoperatingbuffer_standardDeviation: number;
  jnxoperatingbuffer_rawHexSample: string;
  jnxoperatingbuffer_metadataTag: Record<string, string>;
  jnxcosqueuedroppkts_primaryMetric: number;
  jnxcosqueuedroppkts_secondaryMetric: number;
  jnxcosqueuedroppkts_baselineAverage: number;
  jnxcosqueuedroppkts_peakObserved: number;
  jnxcosqueuedroppkts_standardDeviation: number;
  jnxcosqueuedroppkts_rawHexSample: string;
  jnxcosqueuedroppkts_metadataTag: Record<string, string>;
  jnxbgpm2peerstatus_primaryMetric: number;
  jnxbgpm2peerstatus_secondaryMetric: number;
  jnxbgpm2peerstatus_baselineAverage: number;
  jnxbgpm2peerstatus_peakObserved: number;
  jnxbgpm2peerstatus_standardDeviation: number;
  jnxbgpm2peerstatus_rawHexSample: string;
  jnxbgpm2peerstatus_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type SnmpJuniperJunosFilterV37 = Partial<SnmpJuniperJunosRecordV37> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface SnmpJuniperJunosRecordV38 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  jnxboxanatomy_primaryMetric: number;
  jnxboxanatomy_secondaryMetric: number;
  jnxboxanatomy_baselineAverage: number;
  jnxboxanatomy_peakObserved: number;
  jnxboxanatomy_standardDeviation: number;
  jnxboxanatomy_rawHexSample: string;
  jnxboxanatomy_metadataTag: Record<string, string>;
  jnxoperatingcpu_primaryMetric: number;
  jnxoperatingcpu_secondaryMetric: number;
  jnxoperatingcpu_baselineAverage: number;
  jnxoperatingcpu_peakObserved: number;
  jnxoperatingcpu_standardDeviation: number;
  jnxoperatingcpu_rawHexSample: string;
  jnxoperatingcpu_metadataTag: Record<string, string>;
  jnxoperatingbuffer_primaryMetric: number;
  jnxoperatingbuffer_secondaryMetric: number;
  jnxoperatingbuffer_baselineAverage: number;
  jnxoperatingbuffer_peakObserved: number;
  jnxoperatingbuffer_standardDeviation: number;
  jnxoperatingbuffer_rawHexSample: string;
  jnxoperatingbuffer_metadataTag: Record<string, string>;
  jnxcosqueuedroppkts_primaryMetric: number;
  jnxcosqueuedroppkts_secondaryMetric: number;
  jnxcosqueuedroppkts_baselineAverage: number;
  jnxcosqueuedroppkts_peakObserved: number;
  jnxcosqueuedroppkts_standardDeviation: number;
  jnxcosqueuedroppkts_rawHexSample: string;
  jnxcosqueuedroppkts_metadataTag: Record<string, string>;
  jnxbgpm2peerstatus_primaryMetric: number;
  jnxbgpm2peerstatus_secondaryMetric: number;
  jnxbgpm2peerstatus_baselineAverage: number;
  jnxbgpm2peerstatus_peakObserved: number;
  jnxbgpm2peerstatus_standardDeviation: number;
  jnxbgpm2peerstatus_rawHexSample: string;
  jnxbgpm2peerstatus_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type SnmpJuniperJunosFilterV38 = Partial<SnmpJuniperJunosRecordV38> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface SnmpJuniperJunosRecordV39 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  jnxboxanatomy_primaryMetric: number;
  jnxboxanatomy_secondaryMetric: number;
  jnxboxanatomy_baselineAverage: number;
  jnxboxanatomy_peakObserved: number;
  jnxboxanatomy_standardDeviation: number;
  jnxboxanatomy_rawHexSample: string;
  jnxboxanatomy_metadataTag: Record<string, string>;
  jnxoperatingcpu_primaryMetric: number;
  jnxoperatingcpu_secondaryMetric: number;
  jnxoperatingcpu_baselineAverage: number;
  jnxoperatingcpu_peakObserved: number;
  jnxoperatingcpu_standardDeviation: number;
  jnxoperatingcpu_rawHexSample: string;
  jnxoperatingcpu_metadataTag: Record<string, string>;
  jnxoperatingbuffer_primaryMetric: number;
  jnxoperatingbuffer_secondaryMetric: number;
  jnxoperatingbuffer_baselineAverage: number;
  jnxoperatingbuffer_peakObserved: number;
  jnxoperatingbuffer_standardDeviation: number;
  jnxoperatingbuffer_rawHexSample: string;
  jnxoperatingbuffer_metadataTag: Record<string, string>;
  jnxcosqueuedroppkts_primaryMetric: number;
  jnxcosqueuedroppkts_secondaryMetric: number;
  jnxcosqueuedroppkts_baselineAverage: number;
  jnxcosqueuedroppkts_peakObserved: number;
  jnxcosqueuedroppkts_standardDeviation: number;
  jnxcosqueuedroppkts_rawHexSample: string;
  jnxcosqueuedroppkts_metadataTag: Record<string, string>;
  jnxbgpm2peerstatus_primaryMetric: number;
  jnxbgpm2peerstatus_secondaryMetric: number;
  jnxbgpm2peerstatus_baselineAverage: number;
  jnxbgpm2peerstatus_peakObserved: number;
  jnxbgpm2peerstatus_standardDeviation: number;
  jnxbgpm2peerstatus_rawHexSample: string;
  jnxbgpm2peerstatus_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type SnmpJuniperJunosFilterV39 = Partial<SnmpJuniperJunosRecordV39> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface SnmpJuniperJunosRecordV40 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  jnxboxanatomy_primaryMetric: number;
  jnxboxanatomy_secondaryMetric: number;
  jnxboxanatomy_baselineAverage: number;
  jnxboxanatomy_peakObserved: number;
  jnxboxanatomy_standardDeviation: number;
  jnxboxanatomy_rawHexSample: string;
  jnxboxanatomy_metadataTag: Record<string, string>;
  jnxoperatingcpu_primaryMetric: number;
  jnxoperatingcpu_secondaryMetric: number;
  jnxoperatingcpu_baselineAverage: number;
  jnxoperatingcpu_peakObserved: number;
  jnxoperatingcpu_standardDeviation: number;
  jnxoperatingcpu_rawHexSample: string;
  jnxoperatingcpu_metadataTag: Record<string, string>;
  jnxoperatingbuffer_primaryMetric: number;
  jnxoperatingbuffer_secondaryMetric: number;
  jnxoperatingbuffer_baselineAverage: number;
  jnxoperatingbuffer_peakObserved: number;
  jnxoperatingbuffer_standardDeviation: number;
  jnxoperatingbuffer_rawHexSample: string;
  jnxoperatingbuffer_metadataTag: Record<string, string>;
  jnxcosqueuedroppkts_primaryMetric: number;
  jnxcosqueuedroppkts_secondaryMetric: number;
  jnxcosqueuedroppkts_baselineAverage: number;
  jnxcosqueuedroppkts_peakObserved: number;
  jnxcosqueuedroppkts_standardDeviation: number;
  jnxcosqueuedroppkts_rawHexSample: string;
  jnxcosqueuedroppkts_metadataTag: Record<string, string>;
  jnxbgpm2peerstatus_primaryMetric: number;
  jnxbgpm2peerstatus_secondaryMetric: number;
  jnxbgpm2peerstatus_baselineAverage: number;
  jnxbgpm2peerstatus_peakObserved: number;
  jnxbgpm2peerstatus_standardDeviation: number;
  jnxbgpm2peerstatus_rawHexSample: string;
  jnxbgpm2peerstatus_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type SnmpJuniperJunosFilterV40 = Partial<SnmpJuniperJunosRecordV40> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};
