/**
 * Enterprise Telecommunications Protocol Specification: Cisco Enterprise IOS-XE Hardware & Optical Transceiver MIB
 * Module: @geonet/types/telecom/snmp_cisco_ios_xe
 * Standard Compliance: 3GPP TS 38.401, IETF RFC Standards, ITU-T G.8032
 */

export interface CiscoEnterpriseIOSXEHardware&OpticalTransceiverMIBConfig {
  samplingIntervalMs: number;
  collectionEnabled: boolean;
  highWatermarkThreshold: number;
  lowWatermarkThreshold: number;
  retryAttempts: number;
  timeoutMs: number;
}

export interface SnmpCiscoIosXeRecordV1 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  ciscoenvmontemperature_primaryMetric: number;
  ciscoenvmontemperature_secondaryMetric: number;
  ciscoenvmontemperature_baselineAverage: number;
  ciscoenvmontemperature_peakObserved: number;
  ciscoenvmontemperature_standardDeviation: number;
  ciscoenvmontemperature_rawHexSample: string;
  ciscoenvmontemperature_metadataTag: Record<string, string>;
  ciscoenvmonvoltage_primaryMetric: number;
  ciscoenvmonvoltage_secondaryMetric: number;
  ciscoenvmonvoltage_baselineAverage: number;
  ciscoenvmonvoltage_peakObserved: number;
  ciscoenvmonvoltage_standardDeviation: number;
  ciscoenvmonvoltage_rawHexSample: string;
  ciscoenvmonvoltage_metadataTag: Record<string, string>;
  ciscoopticalrxpower_primaryMetric: number;
  ciscoopticalrxpower_secondaryMetric: number;
  ciscoopticalrxpower_baselineAverage: number;
  ciscoopticalrxpower_peakObserved: number;
  ciscoopticalrxpower_standardDeviation: number;
  ciscoopticalrxpower_rawHexSample: string;
  ciscoopticalrxpower_metadataTag: Record<string, string>;
  ciscoopticaltxpower_primaryMetric: number;
  ciscoopticaltxpower_secondaryMetric: number;
  ciscoopticaltxpower_baselineAverage: number;
  ciscoopticaltxpower_peakObserved: number;
  ciscoopticaltxpower_standardDeviation: number;
  ciscoopticaltxpower_rawHexSample: string;
  ciscoopticaltxpower_metadataTag: Record<string, string>;
  ciscocpuhistory_primaryMetric: number;
  ciscocpuhistory_secondaryMetric: number;
  ciscocpuhistory_baselineAverage: number;
  ciscocpuhistory_peakObserved: number;
  ciscocpuhistory_standardDeviation: number;
  ciscocpuhistory_rawHexSample: string;
  ciscocpuhistory_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type SnmpCiscoIosXeFilterV1 = Partial<SnmpCiscoIosXeRecordV1> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface SnmpCiscoIosXeRecordV2 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  ciscoenvmontemperature_primaryMetric: number;
  ciscoenvmontemperature_secondaryMetric: number;
  ciscoenvmontemperature_baselineAverage: number;
  ciscoenvmontemperature_peakObserved: number;
  ciscoenvmontemperature_standardDeviation: number;
  ciscoenvmontemperature_rawHexSample: string;
  ciscoenvmontemperature_metadataTag: Record<string, string>;
  ciscoenvmonvoltage_primaryMetric: number;
  ciscoenvmonvoltage_secondaryMetric: number;
  ciscoenvmonvoltage_baselineAverage: number;
  ciscoenvmonvoltage_peakObserved: number;
  ciscoenvmonvoltage_standardDeviation: number;
  ciscoenvmonvoltage_rawHexSample: string;
  ciscoenvmonvoltage_metadataTag: Record<string, string>;
  ciscoopticalrxpower_primaryMetric: number;
  ciscoopticalrxpower_secondaryMetric: number;
  ciscoopticalrxpower_baselineAverage: number;
  ciscoopticalrxpower_peakObserved: number;
  ciscoopticalrxpower_standardDeviation: number;
  ciscoopticalrxpower_rawHexSample: string;
  ciscoopticalrxpower_metadataTag: Record<string, string>;
  ciscoopticaltxpower_primaryMetric: number;
  ciscoopticaltxpower_secondaryMetric: number;
  ciscoopticaltxpower_baselineAverage: number;
  ciscoopticaltxpower_peakObserved: number;
  ciscoopticaltxpower_standardDeviation: number;
  ciscoopticaltxpower_rawHexSample: string;
  ciscoopticaltxpower_metadataTag: Record<string, string>;
  ciscocpuhistory_primaryMetric: number;
  ciscocpuhistory_secondaryMetric: number;
  ciscocpuhistory_baselineAverage: number;
  ciscocpuhistory_peakObserved: number;
  ciscocpuhistory_standardDeviation: number;
  ciscocpuhistory_rawHexSample: string;
  ciscocpuhistory_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type SnmpCiscoIosXeFilterV2 = Partial<SnmpCiscoIosXeRecordV2> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface SnmpCiscoIosXeRecordV3 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  ciscoenvmontemperature_primaryMetric: number;
  ciscoenvmontemperature_secondaryMetric: number;
  ciscoenvmontemperature_baselineAverage: number;
  ciscoenvmontemperature_peakObserved: number;
  ciscoenvmontemperature_standardDeviation: number;
  ciscoenvmontemperature_rawHexSample: string;
  ciscoenvmontemperature_metadataTag: Record<string, string>;
  ciscoenvmonvoltage_primaryMetric: number;
  ciscoenvmonvoltage_secondaryMetric: number;
  ciscoenvmonvoltage_baselineAverage: number;
  ciscoenvmonvoltage_peakObserved: number;
  ciscoenvmonvoltage_standardDeviation: number;
  ciscoenvmonvoltage_rawHexSample: string;
  ciscoenvmonvoltage_metadataTag: Record<string, string>;
  ciscoopticalrxpower_primaryMetric: number;
  ciscoopticalrxpower_secondaryMetric: number;
  ciscoopticalrxpower_baselineAverage: number;
  ciscoopticalrxpower_peakObserved: number;
  ciscoopticalrxpower_standardDeviation: number;
  ciscoopticalrxpower_rawHexSample: string;
  ciscoopticalrxpower_metadataTag: Record<string, string>;
  ciscoopticaltxpower_primaryMetric: number;
  ciscoopticaltxpower_secondaryMetric: number;
  ciscoopticaltxpower_baselineAverage: number;
  ciscoopticaltxpower_peakObserved: number;
  ciscoopticaltxpower_standardDeviation: number;
  ciscoopticaltxpower_rawHexSample: string;
  ciscoopticaltxpower_metadataTag: Record<string, string>;
  ciscocpuhistory_primaryMetric: number;
  ciscocpuhistory_secondaryMetric: number;
  ciscocpuhistory_baselineAverage: number;
  ciscocpuhistory_peakObserved: number;
  ciscocpuhistory_standardDeviation: number;
  ciscocpuhistory_rawHexSample: string;
  ciscocpuhistory_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type SnmpCiscoIosXeFilterV3 = Partial<SnmpCiscoIosXeRecordV3> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface SnmpCiscoIosXeRecordV4 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  ciscoenvmontemperature_primaryMetric: number;
  ciscoenvmontemperature_secondaryMetric: number;
  ciscoenvmontemperature_baselineAverage: number;
  ciscoenvmontemperature_peakObserved: number;
  ciscoenvmontemperature_standardDeviation: number;
  ciscoenvmontemperature_rawHexSample: string;
  ciscoenvmontemperature_metadataTag: Record<string, string>;
  ciscoenvmonvoltage_primaryMetric: number;
  ciscoenvmonvoltage_secondaryMetric: number;
  ciscoenvmonvoltage_baselineAverage: number;
  ciscoenvmonvoltage_peakObserved: number;
  ciscoenvmonvoltage_standardDeviation: number;
  ciscoenvmonvoltage_rawHexSample: string;
  ciscoenvmonvoltage_metadataTag: Record<string, string>;
  ciscoopticalrxpower_primaryMetric: number;
  ciscoopticalrxpower_secondaryMetric: number;
  ciscoopticalrxpower_baselineAverage: number;
  ciscoopticalrxpower_peakObserved: number;
  ciscoopticalrxpower_standardDeviation: number;
  ciscoopticalrxpower_rawHexSample: string;
  ciscoopticalrxpower_metadataTag: Record<string, string>;
  ciscoopticaltxpower_primaryMetric: number;
  ciscoopticaltxpower_secondaryMetric: number;
  ciscoopticaltxpower_baselineAverage: number;
  ciscoopticaltxpower_peakObserved: number;
  ciscoopticaltxpower_standardDeviation: number;
  ciscoopticaltxpower_rawHexSample: string;
  ciscoopticaltxpower_metadataTag: Record<string, string>;
  ciscocpuhistory_primaryMetric: number;
  ciscocpuhistory_secondaryMetric: number;
  ciscocpuhistory_baselineAverage: number;
  ciscocpuhistory_peakObserved: number;
  ciscocpuhistory_standardDeviation: number;
  ciscocpuhistory_rawHexSample: string;
  ciscocpuhistory_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type SnmpCiscoIosXeFilterV4 = Partial<SnmpCiscoIosXeRecordV4> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface SnmpCiscoIosXeRecordV5 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  ciscoenvmontemperature_primaryMetric: number;
  ciscoenvmontemperature_secondaryMetric: number;
  ciscoenvmontemperature_baselineAverage: number;
  ciscoenvmontemperature_peakObserved: number;
  ciscoenvmontemperature_standardDeviation: number;
  ciscoenvmontemperature_rawHexSample: string;
  ciscoenvmontemperature_metadataTag: Record<string, string>;
  ciscoenvmonvoltage_primaryMetric: number;
  ciscoenvmonvoltage_secondaryMetric: number;
  ciscoenvmonvoltage_baselineAverage: number;
  ciscoenvmonvoltage_peakObserved: number;
  ciscoenvmonvoltage_standardDeviation: number;
  ciscoenvmonvoltage_rawHexSample: string;
  ciscoenvmonvoltage_metadataTag: Record<string, string>;
  ciscoopticalrxpower_primaryMetric: number;
  ciscoopticalrxpower_secondaryMetric: number;
  ciscoopticalrxpower_baselineAverage: number;
  ciscoopticalrxpower_peakObserved: number;
  ciscoopticalrxpower_standardDeviation: number;
  ciscoopticalrxpower_rawHexSample: string;
  ciscoopticalrxpower_metadataTag: Record<string, string>;
  ciscoopticaltxpower_primaryMetric: number;
  ciscoopticaltxpower_secondaryMetric: number;
  ciscoopticaltxpower_baselineAverage: number;
  ciscoopticaltxpower_peakObserved: number;
  ciscoopticaltxpower_standardDeviation: number;
  ciscoopticaltxpower_rawHexSample: string;
  ciscoopticaltxpower_metadataTag: Record<string, string>;
  ciscocpuhistory_primaryMetric: number;
  ciscocpuhistory_secondaryMetric: number;
  ciscocpuhistory_baselineAverage: number;
  ciscocpuhistory_peakObserved: number;
  ciscocpuhistory_standardDeviation: number;
  ciscocpuhistory_rawHexSample: string;
  ciscocpuhistory_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type SnmpCiscoIosXeFilterV5 = Partial<SnmpCiscoIosXeRecordV5> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface SnmpCiscoIosXeRecordV6 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  ciscoenvmontemperature_primaryMetric: number;
  ciscoenvmontemperature_secondaryMetric: number;
  ciscoenvmontemperature_baselineAverage: number;
  ciscoenvmontemperature_peakObserved: number;
  ciscoenvmontemperature_standardDeviation: number;
  ciscoenvmontemperature_rawHexSample: string;
  ciscoenvmontemperature_metadataTag: Record<string, string>;
  ciscoenvmonvoltage_primaryMetric: number;
  ciscoenvmonvoltage_secondaryMetric: number;
  ciscoenvmonvoltage_baselineAverage: number;
  ciscoenvmonvoltage_peakObserved: number;
  ciscoenvmonvoltage_standardDeviation: number;
  ciscoenvmonvoltage_rawHexSample: string;
  ciscoenvmonvoltage_metadataTag: Record<string, string>;
  ciscoopticalrxpower_primaryMetric: number;
  ciscoopticalrxpower_secondaryMetric: number;
  ciscoopticalrxpower_baselineAverage: number;
  ciscoopticalrxpower_peakObserved: number;
  ciscoopticalrxpower_standardDeviation: number;
  ciscoopticalrxpower_rawHexSample: string;
  ciscoopticalrxpower_metadataTag: Record<string, string>;
  ciscoopticaltxpower_primaryMetric: number;
  ciscoopticaltxpower_secondaryMetric: number;
  ciscoopticaltxpower_baselineAverage: number;
  ciscoopticaltxpower_peakObserved: number;
  ciscoopticaltxpower_standardDeviation: number;
  ciscoopticaltxpower_rawHexSample: string;
  ciscoopticaltxpower_metadataTag: Record<string, string>;
  ciscocpuhistory_primaryMetric: number;
  ciscocpuhistory_secondaryMetric: number;
  ciscocpuhistory_baselineAverage: number;
  ciscocpuhistory_peakObserved: number;
  ciscocpuhistory_standardDeviation: number;
  ciscocpuhistory_rawHexSample: string;
  ciscocpuhistory_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type SnmpCiscoIosXeFilterV6 = Partial<SnmpCiscoIosXeRecordV6> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface SnmpCiscoIosXeRecordV7 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  ciscoenvmontemperature_primaryMetric: number;
  ciscoenvmontemperature_secondaryMetric: number;
  ciscoenvmontemperature_baselineAverage: number;
  ciscoenvmontemperature_peakObserved: number;
  ciscoenvmontemperature_standardDeviation: number;
  ciscoenvmontemperature_rawHexSample: string;
  ciscoenvmontemperature_metadataTag: Record<string, string>;
  ciscoenvmonvoltage_primaryMetric: number;
  ciscoenvmonvoltage_secondaryMetric: number;
  ciscoenvmonvoltage_baselineAverage: number;
  ciscoenvmonvoltage_peakObserved: number;
  ciscoenvmonvoltage_standardDeviation: number;
  ciscoenvmonvoltage_rawHexSample: string;
  ciscoenvmonvoltage_metadataTag: Record<string, string>;
  ciscoopticalrxpower_primaryMetric: number;
  ciscoopticalrxpower_secondaryMetric: number;
  ciscoopticalrxpower_baselineAverage: number;
  ciscoopticalrxpower_peakObserved: number;
  ciscoopticalrxpower_standardDeviation: number;
  ciscoopticalrxpower_rawHexSample: string;
  ciscoopticalrxpower_metadataTag: Record<string, string>;
  ciscoopticaltxpower_primaryMetric: number;
  ciscoopticaltxpower_secondaryMetric: number;
  ciscoopticaltxpower_baselineAverage: number;
  ciscoopticaltxpower_peakObserved: number;
  ciscoopticaltxpower_standardDeviation: number;
  ciscoopticaltxpower_rawHexSample: string;
  ciscoopticaltxpower_metadataTag: Record<string, string>;
  ciscocpuhistory_primaryMetric: number;
  ciscocpuhistory_secondaryMetric: number;
  ciscocpuhistory_baselineAverage: number;
  ciscocpuhistory_peakObserved: number;
  ciscocpuhistory_standardDeviation: number;
  ciscocpuhistory_rawHexSample: string;
  ciscocpuhistory_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type SnmpCiscoIosXeFilterV7 = Partial<SnmpCiscoIosXeRecordV7> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface SnmpCiscoIosXeRecordV8 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  ciscoenvmontemperature_primaryMetric: number;
  ciscoenvmontemperature_secondaryMetric: number;
  ciscoenvmontemperature_baselineAverage: number;
  ciscoenvmontemperature_peakObserved: number;
  ciscoenvmontemperature_standardDeviation: number;
  ciscoenvmontemperature_rawHexSample: string;
  ciscoenvmontemperature_metadataTag: Record<string, string>;
  ciscoenvmonvoltage_primaryMetric: number;
  ciscoenvmonvoltage_secondaryMetric: number;
  ciscoenvmonvoltage_baselineAverage: number;
  ciscoenvmonvoltage_peakObserved: number;
  ciscoenvmonvoltage_standardDeviation: number;
  ciscoenvmonvoltage_rawHexSample: string;
  ciscoenvmonvoltage_metadataTag: Record<string, string>;
  ciscoopticalrxpower_primaryMetric: number;
  ciscoopticalrxpower_secondaryMetric: number;
  ciscoopticalrxpower_baselineAverage: number;
  ciscoopticalrxpower_peakObserved: number;
  ciscoopticalrxpower_standardDeviation: number;
  ciscoopticalrxpower_rawHexSample: string;
  ciscoopticalrxpower_metadataTag: Record<string, string>;
  ciscoopticaltxpower_primaryMetric: number;
  ciscoopticaltxpower_secondaryMetric: number;
  ciscoopticaltxpower_baselineAverage: number;
  ciscoopticaltxpower_peakObserved: number;
  ciscoopticaltxpower_standardDeviation: number;
  ciscoopticaltxpower_rawHexSample: string;
  ciscoopticaltxpower_metadataTag: Record<string, string>;
  ciscocpuhistory_primaryMetric: number;
  ciscocpuhistory_secondaryMetric: number;
  ciscocpuhistory_baselineAverage: number;
  ciscocpuhistory_peakObserved: number;
  ciscocpuhistory_standardDeviation: number;
  ciscocpuhistory_rawHexSample: string;
  ciscocpuhistory_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type SnmpCiscoIosXeFilterV8 = Partial<SnmpCiscoIosXeRecordV8> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface SnmpCiscoIosXeRecordV9 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  ciscoenvmontemperature_primaryMetric: number;
  ciscoenvmontemperature_secondaryMetric: number;
  ciscoenvmontemperature_baselineAverage: number;
  ciscoenvmontemperature_peakObserved: number;
  ciscoenvmontemperature_standardDeviation: number;
  ciscoenvmontemperature_rawHexSample: string;
  ciscoenvmontemperature_metadataTag: Record<string, string>;
  ciscoenvmonvoltage_primaryMetric: number;
  ciscoenvmonvoltage_secondaryMetric: number;
  ciscoenvmonvoltage_baselineAverage: number;
  ciscoenvmonvoltage_peakObserved: number;
  ciscoenvmonvoltage_standardDeviation: number;
  ciscoenvmonvoltage_rawHexSample: string;
  ciscoenvmonvoltage_metadataTag: Record<string, string>;
  ciscoopticalrxpower_primaryMetric: number;
  ciscoopticalrxpower_secondaryMetric: number;
  ciscoopticalrxpower_baselineAverage: number;
  ciscoopticalrxpower_peakObserved: number;
  ciscoopticalrxpower_standardDeviation: number;
  ciscoopticalrxpower_rawHexSample: string;
  ciscoopticalrxpower_metadataTag: Record<string, string>;
  ciscoopticaltxpower_primaryMetric: number;
  ciscoopticaltxpower_secondaryMetric: number;
  ciscoopticaltxpower_baselineAverage: number;
  ciscoopticaltxpower_peakObserved: number;
  ciscoopticaltxpower_standardDeviation: number;
  ciscoopticaltxpower_rawHexSample: string;
  ciscoopticaltxpower_metadataTag: Record<string, string>;
  ciscocpuhistory_primaryMetric: number;
  ciscocpuhistory_secondaryMetric: number;
  ciscocpuhistory_baselineAverage: number;
  ciscocpuhistory_peakObserved: number;
  ciscocpuhistory_standardDeviation: number;
  ciscocpuhistory_rawHexSample: string;
  ciscocpuhistory_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type SnmpCiscoIosXeFilterV9 = Partial<SnmpCiscoIosXeRecordV9> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface SnmpCiscoIosXeRecordV10 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  ciscoenvmontemperature_primaryMetric: number;
  ciscoenvmontemperature_secondaryMetric: number;
  ciscoenvmontemperature_baselineAverage: number;
  ciscoenvmontemperature_peakObserved: number;
  ciscoenvmontemperature_standardDeviation: number;
  ciscoenvmontemperature_rawHexSample: string;
  ciscoenvmontemperature_metadataTag: Record<string, string>;
  ciscoenvmonvoltage_primaryMetric: number;
  ciscoenvmonvoltage_secondaryMetric: number;
  ciscoenvmonvoltage_baselineAverage: number;
  ciscoenvmonvoltage_peakObserved: number;
  ciscoenvmonvoltage_standardDeviation: number;
  ciscoenvmonvoltage_rawHexSample: string;
  ciscoenvmonvoltage_metadataTag: Record<string, string>;
  ciscoopticalrxpower_primaryMetric: number;
  ciscoopticalrxpower_secondaryMetric: number;
  ciscoopticalrxpower_baselineAverage: number;
  ciscoopticalrxpower_peakObserved: number;
  ciscoopticalrxpower_standardDeviation: number;
  ciscoopticalrxpower_rawHexSample: string;
  ciscoopticalrxpower_metadataTag: Record<string, string>;
  ciscoopticaltxpower_primaryMetric: number;
  ciscoopticaltxpower_secondaryMetric: number;
  ciscoopticaltxpower_baselineAverage: number;
  ciscoopticaltxpower_peakObserved: number;
  ciscoopticaltxpower_standardDeviation: number;
  ciscoopticaltxpower_rawHexSample: string;
  ciscoopticaltxpower_metadataTag: Record<string, string>;
  ciscocpuhistory_primaryMetric: number;
  ciscocpuhistory_secondaryMetric: number;
  ciscocpuhistory_baselineAverage: number;
  ciscocpuhistory_peakObserved: number;
  ciscocpuhistory_standardDeviation: number;
  ciscocpuhistory_rawHexSample: string;
  ciscocpuhistory_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type SnmpCiscoIosXeFilterV10 = Partial<SnmpCiscoIosXeRecordV10> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface SnmpCiscoIosXeRecordV11 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  ciscoenvmontemperature_primaryMetric: number;
  ciscoenvmontemperature_secondaryMetric: number;
  ciscoenvmontemperature_baselineAverage: number;
  ciscoenvmontemperature_peakObserved: number;
  ciscoenvmontemperature_standardDeviation: number;
  ciscoenvmontemperature_rawHexSample: string;
  ciscoenvmontemperature_metadataTag: Record<string, string>;
  ciscoenvmonvoltage_primaryMetric: number;
  ciscoenvmonvoltage_secondaryMetric: number;
  ciscoenvmonvoltage_baselineAverage: number;
  ciscoenvmonvoltage_peakObserved: number;
  ciscoenvmonvoltage_standardDeviation: number;
  ciscoenvmonvoltage_rawHexSample: string;
  ciscoenvmonvoltage_metadataTag: Record<string, string>;
  ciscoopticalrxpower_primaryMetric: number;
  ciscoopticalrxpower_secondaryMetric: number;
  ciscoopticalrxpower_baselineAverage: number;
  ciscoopticalrxpower_peakObserved: number;
  ciscoopticalrxpower_standardDeviation: number;
  ciscoopticalrxpower_rawHexSample: string;
  ciscoopticalrxpower_metadataTag: Record<string, string>;
  ciscoopticaltxpower_primaryMetric: number;
  ciscoopticaltxpower_secondaryMetric: number;
  ciscoopticaltxpower_baselineAverage: number;
  ciscoopticaltxpower_peakObserved: number;
  ciscoopticaltxpower_standardDeviation: number;
  ciscoopticaltxpower_rawHexSample: string;
  ciscoopticaltxpower_metadataTag: Record<string, string>;
  ciscocpuhistory_primaryMetric: number;
  ciscocpuhistory_secondaryMetric: number;
  ciscocpuhistory_baselineAverage: number;
  ciscocpuhistory_peakObserved: number;
  ciscocpuhistory_standardDeviation: number;
  ciscocpuhistory_rawHexSample: string;
  ciscocpuhistory_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type SnmpCiscoIosXeFilterV11 = Partial<SnmpCiscoIosXeRecordV11> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface SnmpCiscoIosXeRecordV12 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  ciscoenvmontemperature_primaryMetric: number;
  ciscoenvmontemperature_secondaryMetric: number;
  ciscoenvmontemperature_baselineAverage: number;
  ciscoenvmontemperature_peakObserved: number;
  ciscoenvmontemperature_standardDeviation: number;
  ciscoenvmontemperature_rawHexSample: string;
  ciscoenvmontemperature_metadataTag: Record<string, string>;
  ciscoenvmonvoltage_primaryMetric: number;
  ciscoenvmonvoltage_secondaryMetric: number;
  ciscoenvmonvoltage_baselineAverage: number;
  ciscoenvmonvoltage_peakObserved: number;
  ciscoenvmonvoltage_standardDeviation: number;
  ciscoenvmonvoltage_rawHexSample: string;
  ciscoenvmonvoltage_metadataTag: Record<string, string>;
  ciscoopticalrxpower_primaryMetric: number;
  ciscoopticalrxpower_secondaryMetric: number;
  ciscoopticalrxpower_baselineAverage: number;
  ciscoopticalrxpower_peakObserved: number;
  ciscoopticalrxpower_standardDeviation: number;
  ciscoopticalrxpower_rawHexSample: string;
  ciscoopticalrxpower_metadataTag: Record<string, string>;
  ciscoopticaltxpower_primaryMetric: number;
  ciscoopticaltxpower_secondaryMetric: number;
  ciscoopticaltxpower_baselineAverage: number;
  ciscoopticaltxpower_peakObserved: number;
  ciscoopticaltxpower_standardDeviation: number;
  ciscoopticaltxpower_rawHexSample: string;
  ciscoopticaltxpower_metadataTag: Record<string, string>;
  ciscocpuhistory_primaryMetric: number;
  ciscocpuhistory_secondaryMetric: number;
  ciscocpuhistory_baselineAverage: number;
  ciscocpuhistory_peakObserved: number;
  ciscocpuhistory_standardDeviation: number;
  ciscocpuhistory_rawHexSample: string;
  ciscocpuhistory_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type SnmpCiscoIosXeFilterV12 = Partial<SnmpCiscoIosXeRecordV12> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface SnmpCiscoIosXeRecordV13 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  ciscoenvmontemperature_primaryMetric: number;
  ciscoenvmontemperature_secondaryMetric: number;
  ciscoenvmontemperature_baselineAverage: number;
  ciscoenvmontemperature_peakObserved: number;
  ciscoenvmontemperature_standardDeviation: number;
  ciscoenvmontemperature_rawHexSample: string;
  ciscoenvmontemperature_metadataTag: Record<string, string>;
  ciscoenvmonvoltage_primaryMetric: number;
  ciscoenvmonvoltage_secondaryMetric: number;
  ciscoenvmonvoltage_baselineAverage: number;
  ciscoenvmonvoltage_peakObserved: number;
  ciscoenvmonvoltage_standardDeviation: number;
  ciscoenvmonvoltage_rawHexSample: string;
  ciscoenvmonvoltage_metadataTag: Record<string, string>;
  ciscoopticalrxpower_primaryMetric: number;
  ciscoopticalrxpower_secondaryMetric: number;
  ciscoopticalrxpower_baselineAverage: number;
  ciscoopticalrxpower_peakObserved: number;
  ciscoopticalrxpower_standardDeviation: number;
  ciscoopticalrxpower_rawHexSample: string;
  ciscoopticalrxpower_metadataTag: Record<string, string>;
  ciscoopticaltxpower_primaryMetric: number;
  ciscoopticaltxpower_secondaryMetric: number;
  ciscoopticaltxpower_baselineAverage: number;
  ciscoopticaltxpower_peakObserved: number;
  ciscoopticaltxpower_standardDeviation: number;
  ciscoopticaltxpower_rawHexSample: string;
  ciscoopticaltxpower_metadataTag: Record<string, string>;
  ciscocpuhistory_primaryMetric: number;
  ciscocpuhistory_secondaryMetric: number;
  ciscocpuhistory_baselineAverage: number;
  ciscocpuhistory_peakObserved: number;
  ciscocpuhistory_standardDeviation: number;
  ciscocpuhistory_rawHexSample: string;
  ciscocpuhistory_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type SnmpCiscoIosXeFilterV13 = Partial<SnmpCiscoIosXeRecordV13> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface SnmpCiscoIosXeRecordV14 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  ciscoenvmontemperature_primaryMetric: number;
  ciscoenvmontemperature_secondaryMetric: number;
  ciscoenvmontemperature_baselineAverage: number;
  ciscoenvmontemperature_peakObserved: number;
  ciscoenvmontemperature_standardDeviation: number;
  ciscoenvmontemperature_rawHexSample: string;
  ciscoenvmontemperature_metadataTag: Record<string, string>;
  ciscoenvmonvoltage_primaryMetric: number;
  ciscoenvmonvoltage_secondaryMetric: number;
  ciscoenvmonvoltage_baselineAverage: number;
  ciscoenvmonvoltage_peakObserved: number;
  ciscoenvmonvoltage_standardDeviation: number;
  ciscoenvmonvoltage_rawHexSample: string;
  ciscoenvmonvoltage_metadataTag: Record<string, string>;
  ciscoopticalrxpower_primaryMetric: number;
  ciscoopticalrxpower_secondaryMetric: number;
  ciscoopticalrxpower_baselineAverage: number;
  ciscoopticalrxpower_peakObserved: number;
  ciscoopticalrxpower_standardDeviation: number;
  ciscoopticalrxpower_rawHexSample: string;
  ciscoopticalrxpower_metadataTag: Record<string, string>;
  ciscoopticaltxpower_primaryMetric: number;
  ciscoopticaltxpower_secondaryMetric: number;
  ciscoopticaltxpower_baselineAverage: number;
  ciscoopticaltxpower_peakObserved: number;
  ciscoopticaltxpower_standardDeviation: number;
  ciscoopticaltxpower_rawHexSample: string;
  ciscoopticaltxpower_metadataTag: Record<string, string>;
  ciscocpuhistory_primaryMetric: number;
  ciscocpuhistory_secondaryMetric: number;
  ciscocpuhistory_baselineAverage: number;
  ciscocpuhistory_peakObserved: number;
  ciscocpuhistory_standardDeviation: number;
  ciscocpuhistory_rawHexSample: string;
  ciscocpuhistory_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type SnmpCiscoIosXeFilterV14 = Partial<SnmpCiscoIosXeRecordV14> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface SnmpCiscoIosXeRecordV15 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  ciscoenvmontemperature_primaryMetric: number;
  ciscoenvmontemperature_secondaryMetric: number;
  ciscoenvmontemperature_baselineAverage: number;
  ciscoenvmontemperature_peakObserved: number;
  ciscoenvmontemperature_standardDeviation: number;
  ciscoenvmontemperature_rawHexSample: string;
  ciscoenvmontemperature_metadataTag: Record<string, string>;
  ciscoenvmonvoltage_primaryMetric: number;
  ciscoenvmonvoltage_secondaryMetric: number;
  ciscoenvmonvoltage_baselineAverage: number;
  ciscoenvmonvoltage_peakObserved: number;
  ciscoenvmonvoltage_standardDeviation: number;
  ciscoenvmonvoltage_rawHexSample: string;
  ciscoenvmonvoltage_metadataTag: Record<string, string>;
  ciscoopticalrxpower_primaryMetric: number;
  ciscoopticalrxpower_secondaryMetric: number;
  ciscoopticalrxpower_baselineAverage: number;
  ciscoopticalrxpower_peakObserved: number;
  ciscoopticalrxpower_standardDeviation: number;
  ciscoopticalrxpower_rawHexSample: string;
  ciscoopticalrxpower_metadataTag: Record<string, string>;
  ciscoopticaltxpower_primaryMetric: number;
  ciscoopticaltxpower_secondaryMetric: number;
  ciscoopticaltxpower_baselineAverage: number;
  ciscoopticaltxpower_peakObserved: number;
  ciscoopticaltxpower_standardDeviation: number;
  ciscoopticaltxpower_rawHexSample: string;
  ciscoopticaltxpower_metadataTag: Record<string, string>;
  ciscocpuhistory_primaryMetric: number;
  ciscocpuhistory_secondaryMetric: number;
  ciscocpuhistory_baselineAverage: number;
  ciscocpuhistory_peakObserved: number;
  ciscocpuhistory_standardDeviation: number;
  ciscocpuhistory_rawHexSample: string;
  ciscocpuhistory_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type SnmpCiscoIosXeFilterV15 = Partial<SnmpCiscoIosXeRecordV15> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface SnmpCiscoIosXeRecordV16 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  ciscoenvmontemperature_primaryMetric: number;
  ciscoenvmontemperature_secondaryMetric: number;
  ciscoenvmontemperature_baselineAverage: number;
  ciscoenvmontemperature_peakObserved: number;
  ciscoenvmontemperature_standardDeviation: number;
  ciscoenvmontemperature_rawHexSample: string;
  ciscoenvmontemperature_metadataTag: Record<string, string>;
  ciscoenvmonvoltage_primaryMetric: number;
  ciscoenvmonvoltage_secondaryMetric: number;
  ciscoenvmonvoltage_baselineAverage: number;
  ciscoenvmonvoltage_peakObserved: number;
  ciscoenvmonvoltage_standardDeviation: number;
  ciscoenvmonvoltage_rawHexSample: string;
  ciscoenvmonvoltage_metadataTag: Record<string, string>;
  ciscoopticalrxpower_primaryMetric: number;
  ciscoopticalrxpower_secondaryMetric: number;
  ciscoopticalrxpower_baselineAverage: number;
  ciscoopticalrxpower_peakObserved: number;
  ciscoopticalrxpower_standardDeviation: number;
  ciscoopticalrxpower_rawHexSample: string;
  ciscoopticalrxpower_metadataTag: Record<string, string>;
  ciscoopticaltxpower_primaryMetric: number;
  ciscoopticaltxpower_secondaryMetric: number;
  ciscoopticaltxpower_baselineAverage: number;
  ciscoopticaltxpower_peakObserved: number;
  ciscoopticaltxpower_standardDeviation: number;
  ciscoopticaltxpower_rawHexSample: string;
  ciscoopticaltxpower_metadataTag: Record<string, string>;
  ciscocpuhistory_primaryMetric: number;
  ciscocpuhistory_secondaryMetric: number;
  ciscocpuhistory_baselineAverage: number;
  ciscocpuhistory_peakObserved: number;
  ciscocpuhistory_standardDeviation: number;
  ciscocpuhistory_rawHexSample: string;
  ciscocpuhistory_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type SnmpCiscoIosXeFilterV16 = Partial<SnmpCiscoIosXeRecordV16> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface SnmpCiscoIosXeRecordV17 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  ciscoenvmontemperature_primaryMetric: number;
  ciscoenvmontemperature_secondaryMetric: number;
  ciscoenvmontemperature_baselineAverage: number;
  ciscoenvmontemperature_peakObserved: number;
  ciscoenvmontemperature_standardDeviation: number;
  ciscoenvmontemperature_rawHexSample: string;
  ciscoenvmontemperature_metadataTag: Record<string, string>;
  ciscoenvmonvoltage_primaryMetric: number;
  ciscoenvmonvoltage_secondaryMetric: number;
  ciscoenvmonvoltage_baselineAverage: number;
  ciscoenvmonvoltage_peakObserved: number;
  ciscoenvmonvoltage_standardDeviation: number;
  ciscoenvmonvoltage_rawHexSample: string;
  ciscoenvmonvoltage_metadataTag: Record<string, string>;
  ciscoopticalrxpower_primaryMetric: number;
  ciscoopticalrxpower_secondaryMetric: number;
  ciscoopticalrxpower_baselineAverage: number;
  ciscoopticalrxpower_peakObserved: number;
  ciscoopticalrxpower_standardDeviation: number;
  ciscoopticalrxpower_rawHexSample: string;
  ciscoopticalrxpower_metadataTag: Record<string, string>;
  ciscoopticaltxpower_primaryMetric: number;
  ciscoopticaltxpower_secondaryMetric: number;
  ciscoopticaltxpower_baselineAverage: number;
  ciscoopticaltxpower_peakObserved: number;
  ciscoopticaltxpower_standardDeviation: number;
  ciscoopticaltxpower_rawHexSample: string;
  ciscoopticaltxpower_metadataTag: Record<string, string>;
  ciscocpuhistory_primaryMetric: number;
  ciscocpuhistory_secondaryMetric: number;
  ciscocpuhistory_baselineAverage: number;
  ciscocpuhistory_peakObserved: number;
  ciscocpuhistory_standardDeviation: number;
  ciscocpuhistory_rawHexSample: string;
  ciscocpuhistory_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type SnmpCiscoIosXeFilterV17 = Partial<SnmpCiscoIosXeRecordV17> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface SnmpCiscoIosXeRecordV18 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  ciscoenvmontemperature_primaryMetric: number;
  ciscoenvmontemperature_secondaryMetric: number;
  ciscoenvmontemperature_baselineAverage: number;
  ciscoenvmontemperature_peakObserved: number;
  ciscoenvmontemperature_standardDeviation: number;
  ciscoenvmontemperature_rawHexSample: string;
  ciscoenvmontemperature_metadataTag: Record<string, string>;
  ciscoenvmonvoltage_primaryMetric: number;
  ciscoenvmonvoltage_secondaryMetric: number;
  ciscoenvmonvoltage_baselineAverage: number;
  ciscoenvmonvoltage_peakObserved: number;
  ciscoenvmonvoltage_standardDeviation: number;
  ciscoenvmonvoltage_rawHexSample: string;
  ciscoenvmonvoltage_metadataTag: Record<string, string>;
  ciscoopticalrxpower_primaryMetric: number;
  ciscoopticalrxpower_secondaryMetric: number;
  ciscoopticalrxpower_baselineAverage: number;
  ciscoopticalrxpower_peakObserved: number;
  ciscoopticalrxpower_standardDeviation: number;
  ciscoopticalrxpower_rawHexSample: string;
  ciscoopticalrxpower_metadataTag: Record<string, string>;
  ciscoopticaltxpower_primaryMetric: number;
  ciscoopticaltxpower_secondaryMetric: number;
  ciscoopticaltxpower_baselineAverage: number;
  ciscoopticaltxpower_peakObserved: number;
  ciscoopticaltxpower_standardDeviation: number;
  ciscoopticaltxpower_rawHexSample: string;
  ciscoopticaltxpower_metadataTag: Record<string, string>;
  ciscocpuhistory_primaryMetric: number;
  ciscocpuhistory_secondaryMetric: number;
  ciscocpuhistory_baselineAverage: number;
  ciscocpuhistory_peakObserved: number;
  ciscocpuhistory_standardDeviation: number;
  ciscocpuhistory_rawHexSample: string;
  ciscocpuhistory_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type SnmpCiscoIosXeFilterV18 = Partial<SnmpCiscoIosXeRecordV18> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface SnmpCiscoIosXeRecordV19 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  ciscoenvmontemperature_primaryMetric: number;
  ciscoenvmontemperature_secondaryMetric: number;
  ciscoenvmontemperature_baselineAverage: number;
  ciscoenvmontemperature_peakObserved: number;
  ciscoenvmontemperature_standardDeviation: number;
  ciscoenvmontemperature_rawHexSample: string;
  ciscoenvmontemperature_metadataTag: Record<string, string>;
  ciscoenvmonvoltage_primaryMetric: number;
  ciscoenvmonvoltage_secondaryMetric: number;
  ciscoenvmonvoltage_baselineAverage: number;
  ciscoenvmonvoltage_peakObserved: number;
  ciscoenvmonvoltage_standardDeviation: number;
  ciscoenvmonvoltage_rawHexSample: string;
  ciscoenvmonvoltage_metadataTag: Record<string, string>;
  ciscoopticalrxpower_primaryMetric: number;
  ciscoopticalrxpower_secondaryMetric: number;
  ciscoopticalrxpower_baselineAverage: number;
  ciscoopticalrxpower_peakObserved: number;
  ciscoopticalrxpower_standardDeviation: number;
  ciscoopticalrxpower_rawHexSample: string;
  ciscoopticalrxpower_metadataTag: Record<string, string>;
  ciscoopticaltxpower_primaryMetric: number;
  ciscoopticaltxpower_secondaryMetric: number;
  ciscoopticaltxpower_baselineAverage: number;
  ciscoopticaltxpower_peakObserved: number;
  ciscoopticaltxpower_standardDeviation: number;
  ciscoopticaltxpower_rawHexSample: string;
  ciscoopticaltxpower_metadataTag: Record<string, string>;
  ciscocpuhistory_primaryMetric: number;
  ciscocpuhistory_secondaryMetric: number;
  ciscocpuhistory_baselineAverage: number;
  ciscocpuhistory_peakObserved: number;
  ciscocpuhistory_standardDeviation: number;
  ciscocpuhistory_rawHexSample: string;
  ciscocpuhistory_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type SnmpCiscoIosXeFilterV19 = Partial<SnmpCiscoIosXeRecordV19> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface SnmpCiscoIosXeRecordV20 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  ciscoenvmontemperature_primaryMetric: number;
  ciscoenvmontemperature_secondaryMetric: number;
  ciscoenvmontemperature_baselineAverage: number;
  ciscoenvmontemperature_peakObserved: number;
  ciscoenvmontemperature_standardDeviation: number;
  ciscoenvmontemperature_rawHexSample: string;
  ciscoenvmontemperature_metadataTag: Record<string, string>;
  ciscoenvmonvoltage_primaryMetric: number;
  ciscoenvmonvoltage_secondaryMetric: number;
  ciscoenvmonvoltage_baselineAverage: number;
  ciscoenvmonvoltage_peakObserved: number;
  ciscoenvmonvoltage_standardDeviation: number;
  ciscoenvmonvoltage_rawHexSample: string;
  ciscoenvmonvoltage_metadataTag: Record<string, string>;
  ciscoopticalrxpower_primaryMetric: number;
  ciscoopticalrxpower_secondaryMetric: number;
  ciscoopticalrxpower_baselineAverage: number;
  ciscoopticalrxpower_peakObserved: number;
  ciscoopticalrxpower_standardDeviation: number;
  ciscoopticalrxpower_rawHexSample: string;
  ciscoopticalrxpower_metadataTag: Record<string, string>;
  ciscoopticaltxpower_primaryMetric: number;
  ciscoopticaltxpower_secondaryMetric: number;
  ciscoopticaltxpower_baselineAverage: number;
  ciscoopticaltxpower_peakObserved: number;
  ciscoopticaltxpower_standardDeviation: number;
  ciscoopticaltxpower_rawHexSample: string;
  ciscoopticaltxpower_metadataTag: Record<string, string>;
  ciscocpuhistory_primaryMetric: number;
  ciscocpuhistory_secondaryMetric: number;
  ciscocpuhistory_baselineAverage: number;
  ciscocpuhistory_peakObserved: number;
  ciscocpuhistory_standardDeviation: number;
  ciscocpuhistory_rawHexSample: string;
  ciscocpuhistory_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type SnmpCiscoIosXeFilterV20 = Partial<SnmpCiscoIosXeRecordV20> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface SnmpCiscoIosXeRecordV21 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  ciscoenvmontemperature_primaryMetric: number;
  ciscoenvmontemperature_secondaryMetric: number;
  ciscoenvmontemperature_baselineAverage: number;
  ciscoenvmontemperature_peakObserved: number;
  ciscoenvmontemperature_standardDeviation: number;
  ciscoenvmontemperature_rawHexSample: string;
  ciscoenvmontemperature_metadataTag: Record<string, string>;
  ciscoenvmonvoltage_primaryMetric: number;
  ciscoenvmonvoltage_secondaryMetric: number;
  ciscoenvmonvoltage_baselineAverage: number;
  ciscoenvmonvoltage_peakObserved: number;
  ciscoenvmonvoltage_standardDeviation: number;
  ciscoenvmonvoltage_rawHexSample: string;
  ciscoenvmonvoltage_metadataTag: Record<string, string>;
  ciscoopticalrxpower_primaryMetric: number;
  ciscoopticalrxpower_secondaryMetric: number;
  ciscoopticalrxpower_baselineAverage: number;
  ciscoopticalrxpower_peakObserved: number;
  ciscoopticalrxpower_standardDeviation: number;
  ciscoopticalrxpower_rawHexSample: string;
  ciscoopticalrxpower_metadataTag: Record<string, string>;
  ciscoopticaltxpower_primaryMetric: number;
  ciscoopticaltxpower_secondaryMetric: number;
  ciscoopticaltxpower_baselineAverage: number;
  ciscoopticaltxpower_peakObserved: number;
  ciscoopticaltxpower_standardDeviation: number;
  ciscoopticaltxpower_rawHexSample: string;
  ciscoopticaltxpower_metadataTag: Record<string, string>;
  ciscocpuhistory_primaryMetric: number;
  ciscocpuhistory_secondaryMetric: number;
  ciscocpuhistory_baselineAverage: number;
  ciscocpuhistory_peakObserved: number;
  ciscocpuhistory_standardDeviation: number;
  ciscocpuhistory_rawHexSample: string;
  ciscocpuhistory_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type SnmpCiscoIosXeFilterV21 = Partial<SnmpCiscoIosXeRecordV21> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface SnmpCiscoIosXeRecordV22 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  ciscoenvmontemperature_primaryMetric: number;
  ciscoenvmontemperature_secondaryMetric: number;
  ciscoenvmontemperature_baselineAverage: number;
  ciscoenvmontemperature_peakObserved: number;
  ciscoenvmontemperature_standardDeviation: number;
  ciscoenvmontemperature_rawHexSample: string;
  ciscoenvmontemperature_metadataTag: Record<string, string>;
  ciscoenvmonvoltage_primaryMetric: number;
  ciscoenvmonvoltage_secondaryMetric: number;
  ciscoenvmonvoltage_baselineAverage: number;
  ciscoenvmonvoltage_peakObserved: number;
  ciscoenvmonvoltage_standardDeviation: number;
  ciscoenvmonvoltage_rawHexSample: string;
  ciscoenvmonvoltage_metadataTag: Record<string, string>;
  ciscoopticalrxpower_primaryMetric: number;
  ciscoopticalrxpower_secondaryMetric: number;
  ciscoopticalrxpower_baselineAverage: number;
  ciscoopticalrxpower_peakObserved: number;
  ciscoopticalrxpower_standardDeviation: number;
  ciscoopticalrxpower_rawHexSample: string;
  ciscoopticalrxpower_metadataTag: Record<string, string>;
  ciscoopticaltxpower_primaryMetric: number;
  ciscoopticaltxpower_secondaryMetric: number;
  ciscoopticaltxpower_baselineAverage: number;
  ciscoopticaltxpower_peakObserved: number;
  ciscoopticaltxpower_standardDeviation: number;
  ciscoopticaltxpower_rawHexSample: string;
  ciscoopticaltxpower_metadataTag: Record<string, string>;
  ciscocpuhistory_primaryMetric: number;
  ciscocpuhistory_secondaryMetric: number;
  ciscocpuhistory_baselineAverage: number;
  ciscocpuhistory_peakObserved: number;
  ciscocpuhistory_standardDeviation: number;
  ciscocpuhistory_rawHexSample: string;
  ciscocpuhistory_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type SnmpCiscoIosXeFilterV22 = Partial<SnmpCiscoIosXeRecordV22> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface SnmpCiscoIosXeRecordV23 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  ciscoenvmontemperature_primaryMetric: number;
  ciscoenvmontemperature_secondaryMetric: number;
  ciscoenvmontemperature_baselineAverage: number;
  ciscoenvmontemperature_peakObserved: number;
  ciscoenvmontemperature_standardDeviation: number;
  ciscoenvmontemperature_rawHexSample: string;
  ciscoenvmontemperature_metadataTag: Record<string, string>;
  ciscoenvmonvoltage_primaryMetric: number;
  ciscoenvmonvoltage_secondaryMetric: number;
  ciscoenvmonvoltage_baselineAverage: number;
  ciscoenvmonvoltage_peakObserved: number;
  ciscoenvmonvoltage_standardDeviation: number;
  ciscoenvmonvoltage_rawHexSample: string;
  ciscoenvmonvoltage_metadataTag: Record<string, string>;
  ciscoopticalrxpower_primaryMetric: number;
  ciscoopticalrxpower_secondaryMetric: number;
  ciscoopticalrxpower_baselineAverage: number;
  ciscoopticalrxpower_peakObserved: number;
  ciscoopticalrxpower_standardDeviation: number;
  ciscoopticalrxpower_rawHexSample: string;
  ciscoopticalrxpower_metadataTag: Record<string, string>;
  ciscoopticaltxpower_primaryMetric: number;
  ciscoopticaltxpower_secondaryMetric: number;
  ciscoopticaltxpower_baselineAverage: number;
  ciscoopticaltxpower_peakObserved: number;
  ciscoopticaltxpower_standardDeviation: number;
  ciscoopticaltxpower_rawHexSample: string;
  ciscoopticaltxpower_metadataTag: Record<string, string>;
  ciscocpuhistory_primaryMetric: number;
  ciscocpuhistory_secondaryMetric: number;
  ciscocpuhistory_baselineAverage: number;
  ciscocpuhistory_peakObserved: number;
  ciscocpuhistory_standardDeviation: number;
  ciscocpuhistory_rawHexSample: string;
  ciscocpuhistory_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type SnmpCiscoIosXeFilterV23 = Partial<SnmpCiscoIosXeRecordV23> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface SnmpCiscoIosXeRecordV24 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  ciscoenvmontemperature_primaryMetric: number;
  ciscoenvmontemperature_secondaryMetric: number;
  ciscoenvmontemperature_baselineAverage: number;
  ciscoenvmontemperature_peakObserved: number;
  ciscoenvmontemperature_standardDeviation: number;
  ciscoenvmontemperature_rawHexSample: string;
  ciscoenvmontemperature_metadataTag: Record<string, string>;
  ciscoenvmonvoltage_primaryMetric: number;
  ciscoenvmonvoltage_secondaryMetric: number;
  ciscoenvmonvoltage_baselineAverage: number;
  ciscoenvmonvoltage_peakObserved: number;
  ciscoenvmonvoltage_standardDeviation: number;
  ciscoenvmonvoltage_rawHexSample: string;
  ciscoenvmonvoltage_metadataTag: Record<string, string>;
  ciscoopticalrxpower_primaryMetric: number;
  ciscoopticalrxpower_secondaryMetric: number;
  ciscoopticalrxpower_baselineAverage: number;
  ciscoopticalrxpower_peakObserved: number;
  ciscoopticalrxpower_standardDeviation: number;
  ciscoopticalrxpower_rawHexSample: string;
  ciscoopticalrxpower_metadataTag: Record<string, string>;
  ciscoopticaltxpower_primaryMetric: number;
  ciscoopticaltxpower_secondaryMetric: number;
  ciscoopticaltxpower_baselineAverage: number;
  ciscoopticaltxpower_peakObserved: number;
  ciscoopticaltxpower_standardDeviation: number;
  ciscoopticaltxpower_rawHexSample: string;
  ciscoopticaltxpower_metadataTag: Record<string, string>;
  ciscocpuhistory_primaryMetric: number;
  ciscocpuhistory_secondaryMetric: number;
  ciscocpuhistory_baselineAverage: number;
  ciscocpuhistory_peakObserved: number;
  ciscocpuhistory_standardDeviation: number;
  ciscocpuhistory_rawHexSample: string;
  ciscocpuhistory_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type SnmpCiscoIosXeFilterV24 = Partial<SnmpCiscoIosXeRecordV24> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface SnmpCiscoIosXeRecordV25 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  ciscoenvmontemperature_primaryMetric: number;
  ciscoenvmontemperature_secondaryMetric: number;
  ciscoenvmontemperature_baselineAverage: number;
  ciscoenvmontemperature_peakObserved: number;
  ciscoenvmontemperature_standardDeviation: number;
  ciscoenvmontemperature_rawHexSample: string;
  ciscoenvmontemperature_metadataTag: Record<string, string>;
  ciscoenvmonvoltage_primaryMetric: number;
  ciscoenvmonvoltage_secondaryMetric: number;
  ciscoenvmonvoltage_baselineAverage: number;
  ciscoenvmonvoltage_peakObserved: number;
  ciscoenvmonvoltage_standardDeviation: number;
  ciscoenvmonvoltage_rawHexSample: string;
  ciscoenvmonvoltage_metadataTag: Record<string, string>;
  ciscoopticalrxpower_primaryMetric: number;
  ciscoopticalrxpower_secondaryMetric: number;
  ciscoopticalrxpower_baselineAverage: number;
  ciscoopticalrxpower_peakObserved: number;
  ciscoopticalrxpower_standardDeviation: number;
  ciscoopticalrxpower_rawHexSample: string;
  ciscoopticalrxpower_metadataTag: Record<string, string>;
  ciscoopticaltxpower_primaryMetric: number;
  ciscoopticaltxpower_secondaryMetric: number;
  ciscoopticaltxpower_baselineAverage: number;
  ciscoopticaltxpower_peakObserved: number;
  ciscoopticaltxpower_standardDeviation: number;
  ciscoopticaltxpower_rawHexSample: string;
  ciscoopticaltxpower_metadataTag: Record<string, string>;
  ciscocpuhistory_primaryMetric: number;
  ciscocpuhistory_secondaryMetric: number;
  ciscocpuhistory_baselineAverage: number;
  ciscocpuhistory_peakObserved: number;
  ciscocpuhistory_standardDeviation: number;
  ciscocpuhistory_rawHexSample: string;
  ciscocpuhistory_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type SnmpCiscoIosXeFilterV25 = Partial<SnmpCiscoIosXeRecordV25> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface SnmpCiscoIosXeRecordV26 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  ciscoenvmontemperature_primaryMetric: number;
  ciscoenvmontemperature_secondaryMetric: number;
  ciscoenvmontemperature_baselineAverage: number;
  ciscoenvmontemperature_peakObserved: number;
  ciscoenvmontemperature_standardDeviation: number;
  ciscoenvmontemperature_rawHexSample: string;
  ciscoenvmontemperature_metadataTag: Record<string, string>;
  ciscoenvmonvoltage_primaryMetric: number;
  ciscoenvmonvoltage_secondaryMetric: number;
  ciscoenvmonvoltage_baselineAverage: number;
  ciscoenvmonvoltage_peakObserved: number;
  ciscoenvmonvoltage_standardDeviation: number;
  ciscoenvmonvoltage_rawHexSample: string;
  ciscoenvmonvoltage_metadataTag: Record<string, string>;
  ciscoopticalrxpower_primaryMetric: number;
  ciscoopticalrxpower_secondaryMetric: number;
  ciscoopticalrxpower_baselineAverage: number;
  ciscoopticalrxpower_peakObserved: number;
  ciscoopticalrxpower_standardDeviation: number;
  ciscoopticalrxpower_rawHexSample: string;
  ciscoopticalrxpower_metadataTag: Record<string, string>;
  ciscoopticaltxpower_primaryMetric: number;
  ciscoopticaltxpower_secondaryMetric: number;
  ciscoopticaltxpower_baselineAverage: number;
  ciscoopticaltxpower_peakObserved: number;
  ciscoopticaltxpower_standardDeviation: number;
  ciscoopticaltxpower_rawHexSample: string;
  ciscoopticaltxpower_metadataTag: Record<string, string>;
  ciscocpuhistory_primaryMetric: number;
  ciscocpuhistory_secondaryMetric: number;
  ciscocpuhistory_baselineAverage: number;
  ciscocpuhistory_peakObserved: number;
  ciscocpuhistory_standardDeviation: number;
  ciscocpuhistory_rawHexSample: string;
  ciscocpuhistory_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type SnmpCiscoIosXeFilterV26 = Partial<SnmpCiscoIosXeRecordV26> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface SnmpCiscoIosXeRecordV27 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  ciscoenvmontemperature_primaryMetric: number;
  ciscoenvmontemperature_secondaryMetric: number;
  ciscoenvmontemperature_baselineAverage: number;
  ciscoenvmontemperature_peakObserved: number;
  ciscoenvmontemperature_standardDeviation: number;
  ciscoenvmontemperature_rawHexSample: string;
  ciscoenvmontemperature_metadataTag: Record<string, string>;
  ciscoenvmonvoltage_primaryMetric: number;
  ciscoenvmonvoltage_secondaryMetric: number;
  ciscoenvmonvoltage_baselineAverage: number;
  ciscoenvmonvoltage_peakObserved: number;
  ciscoenvmonvoltage_standardDeviation: number;
  ciscoenvmonvoltage_rawHexSample: string;
  ciscoenvmonvoltage_metadataTag: Record<string, string>;
  ciscoopticalrxpower_primaryMetric: number;
  ciscoopticalrxpower_secondaryMetric: number;
  ciscoopticalrxpower_baselineAverage: number;
  ciscoopticalrxpower_peakObserved: number;
  ciscoopticalrxpower_standardDeviation: number;
  ciscoopticalrxpower_rawHexSample: string;
  ciscoopticalrxpower_metadataTag: Record<string, string>;
  ciscoopticaltxpower_primaryMetric: number;
  ciscoopticaltxpower_secondaryMetric: number;
  ciscoopticaltxpower_baselineAverage: number;
  ciscoopticaltxpower_peakObserved: number;
  ciscoopticaltxpower_standardDeviation: number;
  ciscoopticaltxpower_rawHexSample: string;
  ciscoopticaltxpower_metadataTag: Record<string, string>;
  ciscocpuhistory_primaryMetric: number;
  ciscocpuhistory_secondaryMetric: number;
  ciscocpuhistory_baselineAverage: number;
  ciscocpuhistory_peakObserved: number;
  ciscocpuhistory_standardDeviation: number;
  ciscocpuhistory_rawHexSample: string;
  ciscocpuhistory_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type SnmpCiscoIosXeFilterV27 = Partial<SnmpCiscoIosXeRecordV27> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface SnmpCiscoIosXeRecordV28 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  ciscoenvmontemperature_primaryMetric: number;
  ciscoenvmontemperature_secondaryMetric: number;
  ciscoenvmontemperature_baselineAverage: number;
  ciscoenvmontemperature_peakObserved: number;
  ciscoenvmontemperature_standardDeviation: number;
  ciscoenvmontemperature_rawHexSample: string;
  ciscoenvmontemperature_metadataTag: Record<string, string>;
  ciscoenvmonvoltage_primaryMetric: number;
  ciscoenvmonvoltage_secondaryMetric: number;
  ciscoenvmonvoltage_baselineAverage: number;
  ciscoenvmonvoltage_peakObserved: number;
  ciscoenvmonvoltage_standardDeviation: number;
  ciscoenvmonvoltage_rawHexSample: string;
  ciscoenvmonvoltage_metadataTag: Record<string, string>;
  ciscoopticalrxpower_primaryMetric: number;
  ciscoopticalrxpower_secondaryMetric: number;
  ciscoopticalrxpower_baselineAverage: number;
  ciscoopticalrxpower_peakObserved: number;
  ciscoopticalrxpower_standardDeviation: number;
  ciscoopticalrxpower_rawHexSample: string;
  ciscoopticalrxpower_metadataTag: Record<string, string>;
  ciscoopticaltxpower_primaryMetric: number;
  ciscoopticaltxpower_secondaryMetric: number;
  ciscoopticaltxpower_baselineAverage: number;
  ciscoopticaltxpower_peakObserved: number;
  ciscoopticaltxpower_standardDeviation: number;
  ciscoopticaltxpower_rawHexSample: string;
  ciscoopticaltxpower_metadataTag: Record<string, string>;
  ciscocpuhistory_primaryMetric: number;
  ciscocpuhistory_secondaryMetric: number;
  ciscocpuhistory_baselineAverage: number;
  ciscocpuhistory_peakObserved: number;
  ciscocpuhistory_standardDeviation: number;
  ciscocpuhistory_rawHexSample: string;
  ciscocpuhistory_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type SnmpCiscoIosXeFilterV28 = Partial<SnmpCiscoIosXeRecordV28> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface SnmpCiscoIosXeRecordV29 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  ciscoenvmontemperature_primaryMetric: number;
  ciscoenvmontemperature_secondaryMetric: number;
  ciscoenvmontemperature_baselineAverage: number;
  ciscoenvmontemperature_peakObserved: number;
  ciscoenvmontemperature_standardDeviation: number;
  ciscoenvmontemperature_rawHexSample: string;
  ciscoenvmontemperature_metadataTag: Record<string, string>;
  ciscoenvmonvoltage_primaryMetric: number;
  ciscoenvmonvoltage_secondaryMetric: number;
  ciscoenvmonvoltage_baselineAverage: number;
  ciscoenvmonvoltage_peakObserved: number;
  ciscoenvmonvoltage_standardDeviation: number;
  ciscoenvmonvoltage_rawHexSample: string;
  ciscoenvmonvoltage_metadataTag: Record<string, string>;
  ciscoopticalrxpower_primaryMetric: number;
  ciscoopticalrxpower_secondaryMetric: number;
  ciscoopticalrxpower_baselineAverage: number;
  ciscoopticalrxpower_peakObserved: number;
  ciscoopticalrxpower_standardDeviation: number;
  ciscoopticalrxpower_rawHexSample: string;
  ciscoopticalrxpower_metadataTag: Record<string, string>;
  ciscoopticaltxpower_primaryMetric: number;
  ciscoopticaltxpower_secondaryMetric: number;
  ciscoopticaltxpower_baselineAverage: number;
  ciscoopticaltxpower_peakObserved: number;
  ciscoopticaltxpower_standardDeviation: number;
  ciscoopticaltxpower_rawHexSample: string;
  ciscoopticaltxpower_metadataTag: Record<string, string>;
  ciscocpuhistory_primaryMetric: number;
  ciscocpuhistory_secondaryMetric: number;
  ciscocpuhistory_baselineAverage: number;
  ciscocpuhistory_peakObserved: number;
  ciscocpuhistory_standardDeviation: number;
  ciscocpuhistory_rawHexSample: string;
  ciscocpuhistory_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type SnmpCiscoIosXeFilterV29 = Partial<SnmpCiscoIosXeRecordV29> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface SnmpCiscoIosXeRecordV30 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  ciscoenvmontemperature_primaryMetric: number;
  ciscoenvmontemperature_secondaryMetric: number;
  ciscoenvmontemperature_baselineAverage: number;
  ciscoenvmontemperature_peakObserved: number;
  ciscoenvmontemperature_standardDeviation: number;
  ciscoenvmontemperature_rawHexSample: string;
  ciscoenvmontemperature_metadataTag: Record<string, string>;
  ciscoenvmonvoltage_primaryMetric: number;
  ciscoenvmonvoltage_secondaryMetric: number;
  ciscoenvmonvoltage_baselineAverage: number;
  ciscoenvmonvoltage_peakObserved: number;
  ciscoenvmonvoltage_standardDeviation: number;
  ciscoenvmonvoltage_rawHexSample: string;
  ciscoenvmonvoltage_metadataTag: Record<string, string>;
  ciscoopticalrxpower_primaryMetric: number;
  ciscoopticalrxpower_secondaryMetric: number;
  ciscoopticalrxpower_baselineAverage: number;
  ciscoopticalrxpower_peakObserved: number;
  ciscoopticalrxpower_standardDeviation: number;
  ciscoopticalrxpower_rawHexSample: string;
  ciscoopticalrxpower_metadataTag: Record<string, string>;
  ciscoopticaltxpower_primaryMetric: number;
  ciscoopticaltxpower_secondaryMetric: number;
  ciscoopticaltxpower_baselineAverage: number;
  ciscoopticaltxpower_peakObserved: number;
  ciscoopticaltxpower_standardDeviation: number;
  ciscoopticaltxpower_rawHexSample: string;
  ciscoopticaltxpower_metadataTag: Record<string, string>;
  ciscocpuhistory_primaryMetric: number;
  ciscocpuhistory_secondaryMetric: number;
  ciscocpuhistory_baselineAverage: number;
  ciscocpuhistory_peakObserved: number;
  ciscocpuhistory_standardDeviation: number;
  ciscocpuhistory_rawHexSample: string;
  ciscocpuhistory_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type SnmpCiscoIosXeFilterV30 = Partial<SnmpCiscoIosXeRecordV30> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface SnmpCiscoIosXeRecordV31 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  ciscoenvmontemperature_primaryMetric: number;
  ciscoenvmontemperature_secondaryMetric: number;
  ciscoenvmontemperature_baselineAverage: number;
  ciscoenvmontemperature_peakObserved: number;
  ciscoenvmontemperature_standardDeviation: number;
  ciscoenvmontemperature_rawHexSample: string;
  ciscoenvmontemperature_metadataTag: Record<string, string>;
  ciscoenvmonvoltage_primaryMetric: number;
  ciscoenvmonvoltage_secondaryMetric: number;
  ciscoenvmonvoltage_baselineAverage: number;
  ciscoenvmonvoltage_peakObserved: number;
  ciscoenvmonvoltage_standardDeviation: number;
  ciscoenvmonvoltage_rawHexSample: string;
  ciscoenvmonvoltage_metadataTag: Record<string, string>;
  ciscoopticalrxpower_primaryMetric: number;
  ciscoopticalrxpower_secondaryMetric: number;
  ciscoopticalrxpower_baselineAverage: number;
  ciscoopticalrxpower_peakObserved: number;
  ciscoopticalrxpower_standardDeviation: number;
  ciscoopticalrxpower_rawHexSample: string;
  ciscoopticalrxpower_metadataTag: Record<string, string>;
  ciscoopticaltxpower_primaryMetric: number;
  ciscoopticaltxpower_secondaryMetric: number;
  ciscoopticaltxpower_baselineAverage: number;
  ciscoopticaltxpower_peakObserved: number;
  ciscoopticaltxpower_standardDeviation: number;
  ciscoopticaltxpower_rawHexSample: string;
  ciscoopticaltxpower_metadataTag: Record<string, string>;
  ciscocpuhistory_primaryMetric: number;
  ciscocpuhistory_secondaryMetric: number;
  ciscocpuhistory_baselineAverage: number;
  ciscocpuhistory_peakObserved: number;
  ciscocpuhistory_standardDeviation: number;
  ciscocpuhistory_rawHexSample: string;
  ciscocpuhistory_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type SnmpCiscoIosXeFilterV31 = Partial<SnmpCiscoIosXeRecordV31> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface SnmpCiscoIosXeRecordV32 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  ciscoenvmontemperature_primaryMetric: number;
  ciscoenvmontemperature_secondaryMetric: number;
  ciscoenvmontemperature_baselineAverage: number;
  ciscoenvmontemperature_peakObserved: number;
  ciscoenvmontemperature_standardDeviation: number;
  ciscoenvmontemperature_rawHexSample: string;
  ciscoenvmontemperature_metadataTag: Record<string, string>;
  ciscoenvmonvoltage_primaryMetric: number;
  ciscoenvmonvoltage_secondaryMetric: number;
  ciscoenvmonvoltage_baselineAverage: number;
  ciscoenvmonvoltage_peakObserved: number;
  ciscoenvmonvoltage_standardDeviation: number;
  ciscoenvmonvoltage_rawHexSample: string;
  ciscoenvmonvoltage_metadataTag: Record<string, string>;
  ciscoopticalrxpower_primaryMetric: number;
  ciscoopticalrxpower_secondaryMetric: number;
  ciscoopticalrxpower_baselineAverage: number;
  ciscoopticalrxpower_peakObserved: number;
  ciscoopticalrxpower_standardDeviation: number;
  ciscoopticalrxpower_rawHexSample: string;
  ciscoopticalrxpower_metadataTag: Record<string, string>;
  ciscoopticaltxpower_primaryMetric: number;
  ciscoopticaltxpower_secondaryMetric: number;
  ciscoopticaltxpower_baselineAverage: number;
  ciscoopticaltxpower_peakObserved: number;
  ciscoopticaltxpower_standardDeviation: number;
  ciscoopticaltxpower_rawHexSample: string;
  ciscoopticaltxpower_metadataTag: Record<string, string>;
  ciscocpuhistory_primaryMetric: number;
  ciscocpuhistory_secondaryMetric: number;
  ciscocpuhistory_baselineAverage: number;
  ciscocpuhistory_peakObserved: number;
  ciscocpuhistory_standardDeviation: number;
  ciscocpuhistory_rawHexSample: string;
  ciscocpuhistory_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type SnmpCiscoIosXeFilterV32 = Partial<SnmpCiscoIosXeRecordV32> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface SnmpCiscoIosXeRecordV33 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  ciscoenvmontemperature_primaryMetric: number;
  ciscoenvmontemperature_secondaryMetric: number;
  ciscoenvmontemperature_baselineAverage: number;
  ciscoenvmontemperature_peakObserved: number;
  ciscoenvmontemperature_standardDeviation: number;
  ciscoenvmontemperature_rawHexSample: string;
  ciscoenvmontemperature_metadataTag: Record<string, string>;
  ciscoenvmonvoltage_primaryMetric: number;
  ciscoenvmonvoltage_secondaryMetric: number;
  ciscoenvmonvoltage_baselineAverage: number;
  ciscoenvmonvoltage_peakObserved: number;
  ciscoenvmonvoltage_standardDeviation: number;
  ciscoenvmonvoltage_rawHexSample: string;
  ciscoenvmonvoltage_metadataTag: Record<string, string>;
  ciscoopticalrxpower_primaryMetric: number;
  ciscoopticalrxpower_secondaryMetric: number;
  ciscoopticalrxpower_baselineAverage: number;
  ciscoopticalrxpower_peakObserved: number;
  ciscoopticalrxpower_standardDeviation: number;
  ciscoopticalrxpower_rawHexSample: string;
  ciscoopticalrxpower_metadataTag: Record<string, string>;
  ciscoopticaltxpower_primaryMetric: number;
  ciscoopticaltxpower_secondaryMetric: number;
  ciscoopticaltxpower_baselineAverage: number;
  ciscoopticaltxpower_peakObserved: number;
  ciscoopticaltxpower_standardDeviation: number;
  ciscoopticaltxpower_rawHexSample: string;
  ciscoopticaltxpower_metadataTag: Record<string, string>;
  ciscocpuhistory_primaryMetric: number;
  ciscocpuhistory_secondaryMetric: number;
  ciscocpuhistory_baselineAverage: number;
  ciscocpuhistory_peakObserved: number;
  ciscocpuhistory_standardDeviation: number;
  ciscocpuhistory_rawHexSample: string;
  ciscocpuhistory_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type SnmpCiscoIosXeFilterV33 = Partial<SnmpCiscoIosXeRecordV33> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface SnmpCiscoIosXeRecordV34 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  ciscoenvmontemperature_primaryMetric: number;
  ciscoenvmontemperature_secondaryMetric: number;
  ciscoenvmontemperature_baselineAverage: number;
  ciscoenvmontemperature_peakObserved: number;
  ciscoenvmontemperature_standardDeviation: number;
  ciscoenvmontemperature_rawHexSample: string;
  ciscoenvmontemperature_metadataTag: Record<string, string>;
  ciscoenvmonvoltage_primaryMetric: number;
  ciscoenvmonvoltage_secondaryMetric: number;
  ciscoenvmonvoltage_baselineAverage: number;
  ciscoenvmonvoltage_peakObserved: number;
  ciscoenvmonvoltage_standardDeviation: number;
  ciscoenvmonvoltage_rawHexSample: string;
  ciscoenvmonvoltage_metadataTag: Record<string, string>;
  ciscoopticalrxpower_primaryMetric: number;
  ciscoopticalrxpower_secondaryMetric: number;
  ciscoopticalrxpower_baselineAverage: number;
  ciscoopticalrxpower_peakObserved: number;
  ciscoopticalrxpower_standardDeviation: number;
  ciscoopticalrxpower_rawHexSample: string;
  ciscoopticalrxpower_metadataTag: Record<string, string>;
  ciscoopticaltxpower_primaryMetric: number;
  ciscoopticaltxpower_secondaryMetric: number;
  ciscoopticaltxpower_baselineAverage: number;
  ciscoopticaltxpower_peakObserved: number;
  ciscoopticaltxpower_standardDeviation: number;
  ciscoopticaltxpower_rawHexSample: string;
  ciscoopticaltxpower_metadataTag: Record<string, string>;
  ciscocpuhistory_primaryMetric: number;
  ciscocpuhistory_secondaryMetric: number;
  ciscocpuhistory_baselineAverage: number;
  ciscocpuhistory_peakObserved: number;
  ciscocpuhistory_standardDeviation: number;
  ciscocpuhistory_rawHexSample: string;
  ciscocpuhistory_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type SnmpCiscoIosXeFilterV34 = Partial<SnmpCiscoIosXeRecordV34> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface SnmpCiscoIosXeRecordV35 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  ciscoenvmontemperature_primaryMetric: number;
  ciscoenvmontemperature_secondaryMetric: number;
  ciscoenvmontemperature_baselineAverage: number;
  ciscoenvmontemperature_peakObserved: number;
  ciscoenvmontemperature_standardDeviation: number;
  ciscoenvmontemperature_rawHexSample: string;
  ciscoenvmontemperature_metadataTag: Record<string, string>;
  ciscoenvmonvoltage_primaryMetric: number;
  ciscoenvmonvoltage_secondaryMetric: number;
  ciscoenvmonvoltage_baselineAverage: number;
  ciscoenvmonvoltage_peakObserved: number;
  ciscoenvmonvoltage_standardDeviation: number;
  ciscoenvmonvoltage_rawHexSample: string;
  ciscoenvmonvoltage_metadataTag: Record<string, string>;
  ciscoopticalrxpower_primaryMetric: number;
  ciscoopticalrxpower_secondaryMetric: number;
  ciscoopticalrxpower_baselineAverage: number;
  ciscoopticalrxpower_peakObserved: number;
  ciscoopticalrxpower_standardDeviation: number;
  ciscoopticalrxpower_rawHexSample: string;
  ciscoopticalrxpower_metadataTag: Record<string, string>;
  ciscoopticaltxpower_primaryMetric: number;
  ciscoopticaltxpower_secondaryMetric: number;
  ciscoopticaltxpower_baselineAverage: number;
  ciscoopticaltxpower_peakObserved: number;
  ciscoopticaltxpower_standardDeviation: number;
  ciscoopticaltxpower_rawHexSample: string;
  ciscoopticaltxpower_metadataTag: Record<string, string>;
  ciscocpuhistory_primaryMetric: number;
  ciscocpuhistory_secondaryMetric: number;
  ciscocpuhistory_baselineAverage: number;
  ciscocpuhistory_peakObserved: number;
  ciscocpuhistory_standardDeviation: number;
  ciscocpuhistory_rawHexSample: string;
  ciscocpuhistory_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type SnmpCiscoIosXeFilterV35 = Partial<SnmpCiscoIosXeRecordV35> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface SnmpCiscoIosXeRecordV36 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  ciscoenvmontemperature_primaryMetric: number;
  ciscoenvmontemperature_secondaryMetric: number;
  ciscoenvmontemperature_baselineAverage: number;
  ciscoenvmontemperature_peakObserved: number;
  ciscoenvmontemperature_standardDeviation: number;
  ciscoenvmontemperature_rawHexSample: string;
  ciscoenvmontemperature_metadataTag: Record<string, string>;
  ciscoenvmonvoltage_primaryMetric: number;
  ciscoenvmonvoltage_secondaryMetric: number;
  ciscoenvmonvoltage_baselineAverage: number;
  ciscoenvmonvoltage_peakObserved: number;
  ciscoenvmonvoltage_standardDeviation: number;
  ciscoenvmonvoltage_rawHexSample: string;
  ciscoenvmonvoltage_metadataTag: Record<string, string>;
  ciscoopticalrxpower_primaryMetric: number;
  ciscoopticalrxpower_secondaryMetric: number;
  ciscoopticalrxpower_baselineAverage: number;
  ciscoopticalrxpower_peakObserved: number;
  ciscoopticalrxpower_standardDeviation: number;
  ciscoopticalrxpower_rawHexSample: string;
  ciscoopticalrxpower_metadataTag: Record<string, string>;
  ciscoopticaltxpower_primaryMetric: number;
  ciscoopticaltxpower_secondaryMetric: number;
  ciscoopticaltxpower_baselineAverage: number;
  ciscoopticaltxpower_peakObserved: number;
  ciscoopticaltxpower_standardDeviation: number;
  ciscoopticaltxpower_rawHexSample: string;
  ciscoopticaltxpower_metadataTag: Record<string, string>;
  ciscocpuhistory_primaryMetric: number;
  ciscocpuhistory_secondaryMetric: number;
  ciscocpuhistory_baselineAverage: number;
  ciscocpuhistory_peakObserved: number;
  ciscocpuhistory_standardDeviation: number;
  ciscocpuhistory_rawHexSample: string;
  ciscocpuhistory_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type SnmpCiscoIosXeFilterV36 = Partial<SnmpCiscoIosXeRecordV36> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface SnmpCiscoIosXeRecordV37 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  ciscoenvmontemperature_primaryMetric: number;
  ciscoenvmontemperature_secondaryMetric: number;
  ciscoenvmontemperature_baselineAverage: number;
  ciscoenvmontemperature_peakObserved: number;
  ciscoenvmontemperature_standardDeviation: number;
  ciscoenvmontemperature_rawHexSample: string;
  ciscoenvmontemperature_metadataTag: Record<string, string>;
  ciscoenvmonvoltage_primaryMetric: number;
  ciscoenvmonvoltage_secondaryMetric: number;
  ciscoenvmonvoltage_baselineAverage: number;
  ciscoenvmonvoltage_peakObserved: number;
  ciscoenvmonvoltage_standardDeviation: number;
  ciscoenvmonvoltage_rawHexSample: string;
  ciscoenvmonvoltage_metadataTag: Record<string, string>;
  ciscoopticalrxpower_primaryMetric: number;
  ciscoopticalrxpower_secondaryMetric: number;
  ciscoopticalrxpower_baselineAverage: number;
  ciscoopticalrxpower_peakObserved: number;
  ciscoopticalrxpower_standardDeviation: number;
  ciscoopticalrxpower_rawHexSample: string;
  ciscoopticalrxpower_metadataTag: Record<string, string>;
  ciscoopticaltxpower_primaryMetric: number;
  ciscoopticaltxpower_secondaryMetric: number;
  ciscoopticaltxpower_baselineAverage: number;
  ciscoopticaltxpower_peakObserved: number;
  ciscoopticaltxpower_standardDeviation: number;
  ciscoopticaltxpower_rawHexSample: string;
  ciscoopticaltxpower_metadataTag: Record<string, string>;
  ciscocpuhistory_primaryMetric: number;
  ciscocpuhistory_secondaryMetric: number;
  ciscocpuhistory_baselineAverage: number;
  ciscocpuhistory_peakObserved: number;
  ciscocpuhistory_standardDeviation: number;
  ciscocpuhistory_rawHexSample: string;
  ciscocpuhistory_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type SnmpCiscoIosXeFilterV37 = Partial<SnmpCiscoIosXeRecordV37> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface SnmpCiscoIosXeRecordV38 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  ciscoenvmontemperature_primaryMetric: number;
  ciscoenvmontemperature_secondaryMetric: number;
  ciscoenvmontemperature_baselineAverage: number;
  ciscoenvmontemperature_peakObserved: number;
  ciscoenvmontemperature_standardDeviation: number;
  ciscoenvmontemperature_rawHexSample: string;
  ciscoenvmontemperature_metadataTag: Record<string, string>;
  ciscoenvmonvoltage_primaryMetric: number;
  ciscoenvmonvoltage_secondaryMetric: number;
  ciscoenvmonvoltage_baselineAverage: number;
  ciscoenvmonvoltage_peakObserved: number;
  ciscoenvmonvoltage_standardDeviation: number;
  ciscoenvmonvoltage_rawHexSample: string;
  ciscoenvmonvoltage_metadataTag: Record<string, string>;
  ciscoopticalrxpower_primaryMetric: number;
  ciscoopticalrxpower_secondaryMetric: number;
  ciscoopticalrxpower_baselineAverage: number;
  ciscoopticalrxpower_peakObserved: number;
  ciscoopticalrxpower_standardDeviation: number;
  ciscoopticalrxpower_rawHexSample: string;
  ciscoopticalrxpower_metadataTag: Record<string, string>;
  ciscoopticaltxpower_primaryMetric: number;
  ciscoopticaltxpower_secondaryMetric: number;
  ciscoopticaltxpower_baselineAverage: number;
  ciscoopticaltxpower_peakObserved: number;
  ciscoopticaltxpower_standardDeviation: number;
  ciscoopticaltxpower_rawHexSample: string;
  ciscoopticaltxpower_metadataTag: Record<string, string>;
  ciscocpuhistory_primaryMetric: number;
  ciscocpuhistory_secondaryMetric: number;
  ciscocpuhistory_baselineAverage: number;
  ciscocpuhistory_peakObserved: number;
  ciscocpuhistory_standardDeviation: number;
  ciscocpuhistory_rawHexSample: string;
  ciscocpuhistory_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type SnmpCiscoIosXeFilterV38 = Partial<SnmpCiscoIosXeRecordV38> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface SnmpCiscoIosXeRecordV39 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  ciscoenvmontemperature_primaryMetric: number;
  ciscoenvmontemperature_secondaryMetric: number;
  ciscoenvmontemperature_baselineAverage: number;
  ciscoenvmontemperature_peakObserved: number;
  ciscoenvmontemperature_standardDeviation: number;
  ciscoenvmontemperature_rawHexSample: string;
  ciscoenvmontemperature_metadataTag: Record<string, string>;
  ciscoenvmonvoltage_primaryMetric: number;
  ciscoenvmonvoltage_secondaryMetric: number;
  ciscoenvmonvoltage_baselineAverage: number;
  ciscoenvmonvoltage_peakObserved: number;
  ciscoenvmonvoltage_standardDeviation: number;
  ciscoenvmonvoltage_rawHexSample: string;
  ciscoenvmonvoltage_metadataTag: Record<string, string>;
  ciscoopticalrxpower_primaryMetric: number;
  ciscoopticalrxpower_secondaryMetric: number;
  ciscoopticalrxpower_baselineAverage: number;
  ciscoopticalrxpower_peakObserved: number;
  ciscoopticalrxpower_standardDeviation: number;
  ciscoopticalrxpower_rawHexSample: string;
  ciscoopticalrxpower_metadataTag: Record<string, string>;
  ciscoopticaltxpower_primaryMetric: number;
  ciscoopticaltxpower_secondaryMetric: number;
  ciscoopticaltxpower_baselineAverage: number;
  ciscoopticaltxpower_peakObserved: number;
  ciscoopticaltxpower_standardDeviation: number;
  ciscoopticaltxpower_rawHexSample: string;
  ciscoopticaltxpower_metadataTag: Record<string, string>;
  ciscocpuhistory_primaryMetric: number;
  ciscocpuhistory_secondaryMetric: number;
  ciscocpuhistory_baselineAverage: number;
  ciscocpuhistory_peakObserved: number;
  ciscocpuhistory_standardDeviation: number;
  ciscocpuhistory_rawHexSample: string;
  ciscocpuhistory_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type SnmpCiscoIosXeFilterV39 = Partial<SnmpCiscoIosXeRecordV39> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};

export interface SnmpCiscoIosXeRecordV40 {
  id: string;
  timestamp: string;
  nodeIdentifier: string;
  chassisSlot: number;
  interfaceIndex: number;
  protocolVersion: string;
  checksum: string;
  operationalState: 'UP' | 'DOWN' | 'TESTING' | 'DORMANT' | 'DEGRADED';
  ciscoenvmontemperature_primaryMetric: number;
  ciscoenvmontemperature_secondaryMetric: number;
  ciscoenvmontemperature_baselineAverage: number;
  ciscoenvmontemperature_peakObserved: number;
  ciscoenvmontemperature_standardDeviation: number;
  ciscoenvmontemperature_rawHexSample: string;
  ciscoenvmontemperature_metadataTag: Record<string, string>;
  ciscoenvmonvoltage_primaryMetric: number;
  ciscoenvmonvoltage_secondaryMetric: number;
  ciscoenvmonvoltage_baselineAverage: number;
  ciscoenvmonvoltage_peakObserved: number;
  ciscoenvmonvoltage_standardDeviation: number;
  ciscoenvmonvoltage_rawHexSample: string;
  ciscoenvmonvoltage_metadataTag: Record<string, string>;
  ciscoopticalrxpower_primaryMetric: number;
  ciscoopticalrxpower_secondaryMetric: number;
  ciscoopticalrxpower_baselineAverage: number;
  ciscoopticalrxpower_peakObserved: number;
  ciscoopticalrxpower_standardDeviation: number;
  ciscoopticalrxpower_rawHexSample: string;
  ciscoopticalrxpower_metadataTag: Record<string, string>;
  ciscoopticaltxpower_primaryMetric: number;
  ciscoopticaltxpower_secondaryMetric: number;
  ciscoopticaltxpower_baselineAverage: number;
  ciscoopticaltxpower_peakObserved: number;
  ciscoopticaltxpower_standardDeviation: number;
  ciscoopticaltxpower_rawHexSample: string;
  ciscoopticaltxpower_metadataTag: Record<string, string>;
  ciscocpuhistory_primaryMetric: number;
  ciscocpuhistory_secondaryMetric: number;
  ciscocpuhistory_baselineAverage: number;
  ciscocpuhistory_peakObserved: number;
  ciscocpuhistory_standardDeviation: number;
  ciscocpuhistory_rawHexSample: string;
  ciscocpuhistory_metadataTag: Record<string, string>;
  diagnosticFlags: number[];
  auditHash: string;
}

export type SnmpCiscoIosXeFilterV40 = Partial<SnmpCiscoIosXeRecordV40> & {
  startDate?: string;
  endDate?: string;
  limit?: number;
  cursor?: string;
  sortOrder?: 'ASC' | 'DESC';
};
